gusimplewhiteboard: guWhiteboard::HeadJointSensors Class Reference
guWhiteboard::HeadJointSensors Class Reference
Provides a C++ wrapper around wb_head_joint_sensors.
#include <HeadJointSensors.hpp>
Public Member Functions
HeadJointSensors (int16_t t_headYaw=0, int16_t t_headPitch=0)
Create a new HeadJointSensors.
HeadJointSensors (const HeadJointSensors &t_other)
Copy Constructor.
HeadJointSensors (const struct wb_head_joint_sensors &t_other)
Copy Constructor.
HeadJointSensors & operator= (const HeadJointSensors &t_other)
Copy Assignment Operator.
HeadJointSensors & operator= (const struct wb_head_joint_sensors &t_other)
Copy Assignment Operator.
bool operator== (const HeadJointSensors &t_other) const
bool operator!= (const HeadJointSensors &t_other) const
bool operator== (const wb_head_joint_sensors &t_other) const
bool operator!= (const wb_head_joint_sensors &t_other) const
int16_t & headYaw ()
const int16_t & headYaw () const
void set_headYaw (const int16_t &t_newValue)
int16_t & headPitch ()
const int16_t & headPitch () const
void set_headPitch (const int16_t &t_newValue)
HeadJointSensors (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_head_joint_sensors
int16_t headYaw
Head pos in degrees.
int16_t headPitch
Head pos in degrees.
Detailed Description
Provides a C++ wrapper around wb_head_joint_sensors.
Definition at line 83 of file HeadJointSensors.hpp.
Constructor & Destructor Documentation
HeadJointSensors() [1/4]
guWhiteboard::HeadJointSensors::HeadJointSensors (int16_t t_headYaw = 0, int16_t t_headPitch = 0) inline
Create a new HeadJointSensors.
Definition at line 100 of file HeadJointSensors.hpp.
Referenced by operator==().
HeadJointSensors() [2/4]
guWhiteboard::HeadJointSensors::HeadJointSensors (const HeadJointSensors & t_other) inline
Copy Constructor.
Definition at line 107 of file HeadJointSensors.hpp.
References headPitch(), and headYaw().
HeadJointSensors() [3/4]
guWhiteboard::HeadJointSensors::HeadJointSensors (const struct wb_head_joint_sensors & t_other) inline
Copy Constructor.
Definition at line 114 of file HeadJointSensors.hpp.
References wb_head_joint_sensors::headPitch, and wb_head_joint_sensors::headYaw.
HeadJointSensors() [4/4]
guWhiteboard::HeadJointSensors::HeadJointSensors (const std::string & t_str) inline
String Constructor.
Definition at line 189 of file HeadJointSensors.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::HeadJointSensors::description () inline
USE_WB_HEAD_JOINT_SENSORS_C_CONVERSION
Definition at line 194 of file HeadJointSensors.hpp.
References HEAD_JOINT_SENSORS_DESC_BUFFER_SIZE, headPitch(), headYaw(), and wb_head_joint_sensors_description().
from_string()
void guWhiteboard::HeadJointSensors::from_string (const std::string & t_str) inline
USE_WB_HEAD_JOINT_SENSORS_C_CONVERSION
Definition at line 228 of file HeadJointSensors.hpp.
References HEAD_JOINT_SENSORS_DESC_BUFFER_SIZE, set_headPitch(), and set_headYaw().
Referenced by HeadJointSensors().
headPitch() [1/2]
int16_t & guWhiteboard::HeadJointSensors::headPitch () inline
Definition at line 170 of file HeadJointSensors.hpp.
References wb_head_joint_sensors::headPitch.
Referenced by HeadJointSensors(), description(), operator=(), operator==(), and to_string().
headPitch() [2/2]
const int16_t & guWhiteboard::HeadJointSensors::headPitch () const inline
Definition at line 175 of file HeadJointSensors.hpp.
References wb_head_joint_sensors::headPitch.
headYaw() [1/2]
int16_t & guWhiteboard::HeadJointSensors::headYaw () inline
Definition at line 155 of file HeadJointSensors.hpp.
References wb_head_joint_sensors::headYaw.
Referenced by HeadJointSensors(), description(), operator=(), operator==(), and to_string().
headYaw() [2/2]
const int16_t & guWhiteboard::HeadJointSensors::headYaw () const inline
Definition at line 160 of file HeadJointSensors.hpp.
References wb_head_joint_sensors::headYaw.
operator!=() [1/2]
bool guWhiteboard::HeadJointSensors::operator!= (const HeadJointSensors & t_other) const inline
Definition at line 140 of file HeadJointSensors.hpp.
operator!=() [2/2]
bool guWhiteboard::HeadJointSensors::operator!= (const wb_head_joint_sensors & t_other) const inline
Definition at line 150 of file HeadJointSensors.hpp.
operator=() [1/2]
HeadJointSensors & guWhiteboard::HeadJointSensors::operator= (const HeadJointSensors & t_other) inline
Copy Assignment Operator.
Definition at line 121 of file HeadJointSensors.hpp.
References headPitch(), and headYaw().
operator=() [2/2]
HeadJointSensors & guWhiteboard::HeadJointSensors::operator= (const struct wb_head_joint_sensors & t_other) inline
Copy Assignment Operator.
Definition at line 129 of file HeadJointSensors.hpp.
References wb_head_joint_sensors::headPitch, and wb_head_joint_sensors::headYaw.
operator==() [1/2]
bool guWhiteboard::HeadJointSensors::operator== (const HeadJointSensors & t_other) const inline
Definition at line 134 of file HeadJointSensors.hpp.
References headPitch(), and headYaw().
operator==() [2/2]
bool guWhiteboard::HeadJointSensors::operator== (const wb_head_joint_sensors & t_other) const inline
Definition at line 145 of file HeadJointSensors.hpp.
References HeadJointSensors().
set_headPitch()
void guWhiteboard::HeadJointSensors::set_headPitch (const int16_t & t_newValue) inline
Definition at line 180 of file HeadJointSensors.hpp.
References wb_head_joint_sensors::headPitch.
Referenced by from_string().
set_headYaw()
void guWhiteboard::HeadJointSensors::set_headYaw (const int16_t & t_newValue) inline
Definition at line 165 of file HeadJointSensors.hpp.
References wb_head_joint_sensors::headYaw.
Referenced by from_string().
to_string()
std::string guWhiteboard::HeadJointSensors::to_string () inline
USE_WB_HEAD_JOINT_SENSORS_C_CONVERSION
Definition at line 209 of file HeadJointSensors.hpp.
References HEAD_JOINT_SENSORS_TO_STRING_BUFFER_SIZE, headPitch(), headYaw(), and wb_head_joint_sensors_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/HeadJointSensors.hpp