gusimplewhiteboard: guWhiteboard::Buttons Class Reference
guWhiteboard::Buttons Class Reference
Provides a C++ wrapper around wb_buttons.
#include <Buttons.hpp>
Public Member Functions
Buttons (bool t_button1Pushed=false, bool t_button2Pushed=false)
Create a new Buttons.
Buttons (const Buttons &t_other)
Copy Constructor.
Buttons (const struct wb_buttons &t_other)
Copy Constructor.
Buttons & operator= (const Buttons &t_other)
Copy Assignment Operator.
Buttons & operator= (const struct wb_buttons &t_other)
Copy Assignment Operator.
bool operator== (const Buttons &t_other) const
bool operator!= (const Buttons &t_other) const
bool operator== (const wb_buttons &t_other) const
bool operator!= (const wb_buttons &t_other) const
bool & button1Pushed ()
const bool & button1Pushed () const
void set_button1Pushed (const bool &t_newValue)
bool & button2Pushed ()
const bool & button2Pushed () const
void set_button2Pushed (const bool &t_newValue)
Buttons (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_buttons
bool button1Pushed
The first button.
bool button2Pushed
The second button.
Detailed Description
Provides a C++ wrapper around wb_buttons.
Definition at line 83 of file Buttons.hpp.
Constructor & Destructor Documentation
Buttons() [1/4]
guWhiteboard::Buttons::Buttons (bool t_button1Pushed = false, bool t_button2Pushed = false) inline
Create a new Buttons.
Definition at line 100 of file Buttons.hpp.
Referenced by operator==().
Buttons() [2/4]
guWhiteboard::Buttons::Buttons (const Buttons & t_other) inline
Copy Constructor.
Definition at line 107 of file Buttons.hpp.
References button1Pushed(), and button2Pushed().
Buttons() [3/4]
guWhiteboard::Buttons::Buttons (const struct wb_buttons & t_other) inline
Copy Constructor.
Definition at line 114 of file Buttons.hpp.
References wb_buttons::button1Pushed, and wb_buttons::button2Pushed.
Buttons() [4/4]
guWhiteboard::Buttons::Buttons (const std::string & t_str) inline
String Constructor.
Definition at line 189 of file Buttons.hpp.
References from_string().
Member Function Documentation
button1Pushed() [1/2]
bool & guWhiteboard::Buttons::button1Pushed () inline
Definition at line 155 of file Buttons.hpp.
References wb_buttons::button1Pushed.
Referenced by Buttons(), description(), operator=(), operator==(), and to_string().
button1Pushed() [2/2]
const bool & guWhiteboard::Buttons::button1Pushed () const inline
Definition at line 160 of file Buttons.hpp.
References wb_buttons::button1Pushed.
button2Pushed() [1/2]
bool & guWhiteboard::Buttons::button2Pushed () inline
Definition at line 170 of file Buttons.hpp.
References wb_buttons::button2Pushed.
Referenced by Buttons(), description(), operator=(), operator==(), and to_string().
button2Pushed() [2/2]
const bool & guWhiteboard::Buttons::button2Pushed () const inline
Definition at line 175 of file Buttons.hpp.
References wb_buttons::button2Pushed.
description()
std::string guWhiteboard::Buttons::description () inline
USE_WB_BUTTONS_C_CONVERSION
Definition at line 194 of file Buttons.hpp.
References button1Pushed(), button2Pushed(), BUTTONS_DESC_BUFFER_SIZE, and wb_buttons_description().
from_string()
void guWhiteboard::Buttons::from_string (const std::string & t_str) inline
USE_WB_BUTTONS_C_CONVERSION
Definition at line 228 of file Buttons.hpp.
References BUTTONS_DESC_BUFFER_SIZE, set_button1Pushed(), and set_button2Pushed().
Referenced by Buttons().
operator!=() [1/2]
bool guWhiteboard::Buttons::operator!= (const Buttons & t_other) const inline
Definition at line 140 of file Buttons.hpp.
operator!=() [2/2]
bool guWhiteboard::Buttons::operator!= (const wb_buttons & t_other) const inline
Definition at line 150 of file Buttons.hpp.
operator=() [1/2]
Buttons & guWhiteboard::Buttons::operator= (const Buttons & t_other) inline
Copy Assignment Operator.
Definition at line 121 of file Buttons.hpp.
References button1Pushed(), and button2Pushed().
operator=() [2/2]
Buttons & guWhiteboard::Buttons::operator= (const struct wb_buttons & t_other) inline
Copy Assignment Operator.
Definition at line 129 of file Buttons.hpp.
References wb_buttons::button1Pushed, and wb_buttons::button2Pushed.
operator==() [1/2]
bool guWhiteboard::Buttons::operator== (const Buttons & t_other) const inline
Definition at line 134 of file Buttons.hpp.
References button1Pushed(), and button2Pushed().
operator==() [2/2]
bool guWhiteboard::Buttons::operator== (const wb_buttons & t_other) const inline
Definition at line 145 of file Buttons.hpp.
References Buttons().
set_button1Pushed()
void guWhiteboard::Buttons::set_button1Pushed (const bool & t_newValue) inline
Definition at line 165 of file Buttons.hpp.
References wb_buttons::button1Pushed.
Referenced by from_string().
set_button2Pushed()
void guWhiteboard::Buttons::set_button2Pushed (const bool & t_newValue) inline
Definition at line 180 of file Buttons.hpp.
References wb_buttons::button2Pushed.
Referenced by from_string().
to_string()
std::string guWhiteboard::Buttons::to_string () inline
USE_WB_BUTTONS_C_CONVERSION
Definition at line 209 of file Buttons.hpp.
References button1Pushed(), button2Pushed(), BUTTONS_TO_STRING_BUFFER_SIZE, and wb_buttons_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/Buttons.hpp