gusimplewhiteboard: guWhiteboard::SensorsHeadSensors Class Reference
guWhiteboard::SensorsHeadSensors Class Reference
Provides a C++ wrapper around wb_sensors_head_sensors.
#include <SensorsHeadSensors.hpp>
Public Member Functions
SensorsHeadSensors (bool t_Head_Touch_Front=true, bool t_Head_Touch_Middle=true, bool t_Head_Touch_Rear=true)
Create a new SensorsHeadSensors.
SensorsHeadSensors (const SensorsHeadSensors &t_other)
Copy Constructor.
SensorsHeadSensors (const struct wb_sensors_head_sensors &t_other)
Copy Constructor.
SensorsHeadSensors & operator= (const SensorsHeadSensors &t_other)
Copy Assignment Operator.
SensorsHeadSensors & operator= (const struct wb_sensors_head_sensors &t_other)
Copy Assignment Operator.
bool operator== (const SensorsHeadSensors &t_other) const
bool operator!= (const SensorsHeadSensors &t_other) const
bool operator== (const wb_sensors_head_sensors &t_other) const
bool operator!= (const wb_sensors_head_sensors &t_other) const
bool & Head_Touch_Front ()
const bool & Head_Touch_Front () const
void set_Head_Touch_Front (const bool &t_newValue)
bool & Head_Touch_Middle ()
const bool & Head_Touch_Middle () const
void set_Head_Touch_Middle (const bool &t_newValue)
bool & Head_Touch_Rear ()
const bool & Head_Touch_Rear () const
void set_Head_Touch_Rear (const bool &t_newValue)
SensorsHeadSensors (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_sensors_head_sensors
bool Head_Touch_Front
state of the front capacitive sensor located on top of the head, on / off.
bool Head_Touch_Middle
state of the middle capacitive sensor located on top of the head, on / off.
bool Head_Touch_Rear
state of the back capacitive sensor located on top of the head, on / off.
Detailed Description
Provides a C++ wrapper around wb_sensors_head_sensors.
Definition at line 83 of file SensorsHeadSensors.hpp.
Constructor & Destructor Documentation
SensorsHeadSensors() [1/4]
guWhiteboard::SensorsHeadSensors::SensorsHeadSensors (bool t_Head_Touch_Front = true, bool t_Head_Touch_Middle = true, bool t_Head_Touch_Rear = true) inline
Create a new SensorsHeadSensors.
Definition at line 101 of file SensorsHeadSensors.hpp.
Referenced by operator==().
SensorsHeadSensors() [2/4]
guWhiteboard::SensorsHeadSensors::SensorsHeadSensors (const SensorsHeadSensors & t_other) inline
Copy Constructor.
Definition at line 108 of file SensorsHeadSensors.hpp.
References Head_Touch_Front(), Head_Touch_Middle(), and Head_Touch_Rear().
SensorsHeadSensors() [3/4]
guWhiteboard::SensorsHeadSensors::SensorsHeadSensors (const struct wb_sensors_head_sensors & t_other) inline
Copy Constructor.
Definition at line 115 of file SensorsHeadSensors.hpp.
References wb_sensors_head_sensors::Head_Touch_Front, wb_sensors_head_sensors::Head_Touch_Middle, and wb_sensors_head_sensors::Head_Touch_Rear.
SensorsHeadSensors() [4/4]
guWhiteboard::SensorsHeadSensors::SensorsHeadSensors (const std::string & t_str) inline
String Constructor.
Definition at line 206 of file SensorsHeadSensors.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::SensorsHeadSensors::description () inline
USE_WB_SENSORS_HEAD_SENSORS_C_CONVERSION
Definition at line 211 of file SensorsHeadSensors.hpp.
References Head_Touch_Front(), Head_Touch_Middle(), Head_Touch_Rear(), SENSORS_HEAD_SENSORS_DESC_BUFFER_SIZE, and wb_sensors_head_sensors_description().
from_string()
void guWhiteboard::SensorsHeadSensors::from_string (const std::string & t_str) inline
USE_WB_SENSORS_HEAD_SENSORS_C_CONVERSION
Definition at line 249 of file SensorsHeadSensors.hpp.
References SENSORS_HEAD_SENSORS_DESC_BUFFER_SIZE, set_Head_Touch_Front(), set_Head_Touch_Middle(), and set_Head_Touch_Rear().
Referenced by SensorsHeadSensors().
Head_Touch_Front() [1/2]
bool & guWhiteboard::SensorsHeadSensors::Head_Touch_Front () inline
Definition at line 157 of file SensorsHeadSensors.hpp.
References wb_sensors_head_sensors::Head_Touch_Front.
Referenced by SensorsHeadSensors(), description(), operator=(), operator==(), and to_string().
Head_Touch_Front() [2/2]
const bool & guWhiteboard::SensorsHeadSensors::Head_Touch_Front () const inline
Definition at line 162 of file SensorsHeadSensors.hpp.
References wb_sensors_head_sensors::Head_Touch_Front.
Head_Touch_Middle() [1/2]
bool & guWhiteboard::SensorsHeadSensors::Head_Touch_Middle () inline
Definition at line 172 of file SensorsHeadSensors.hpp.
References wb_sensors_head_sensors::Head_Touch_Middle.
Referenced by SensorsHeadSensors(), description(), operator=(), operator==(), and to_string().
Head_Touch_Middle() [2/2]
const bool & guWhiteboard::SensorsHeadSensors::Head_Touch_Middle () const inline
Definition at line 177 of file SensorsHeadSensors.hpp.
References wb_sensors_head_sensors::Head_Touch_Middle.
Head_Touch_Rear() [1/2]
bool & guWhiteboard::SensorsHeadSensors::Head_Touch_Rear () inline
Definition at line 187 of file SensorsHeadSensors.hpp.
References wb_sensors_head_sensors::Head_Touch_Rear.
Referenced by SensorsHeadSensors(), description(), operator=(), operator==(), and to_string().
Head_Touch_Rear() [2/2]
const bool & guWhiteboard::SensorsHeadSensors::Head_Touch_Rear () const inline
Definition at line 192 of file SensorsHeadSensors.hpp.
References wb_sensors_head_sensors::Head_Touch_Rear.
operator!=() [1/2]
bool guWhiteboard::SensorsHeadSensors::operator!= (const SensorsHeadSensors & t_other) const inline
Definition at line 142 of file SensorsHeadSensors.hpp.
operator!=() [2/2]
bool guWhiteboard::SensorsHeadSensors::operator!= (const wb_sensors_head_sensors & t_other) const inline
Definition at line 152 of file SensorsHeadSensors.hpp.
operator=() [1/2]
SensorsHeadSensors & guWhiteboard::SensorsHeadSensors::operator= (const SensorsHeadSensors & t_other) inline
Copy Assignment Operator.
Definition at line 122 of file SensorsHeadSensors.hpp.
References Head_Touch_Front(), Head_Touch_Middle(), and Head_Touch_Rear().
operator=() [2/2]
SensorsHeadSensors & guWhiteboard::SensorsHeadSensors::operator= (const struct wb_sensors_head_sensors & t_other) inline
Copy Assignment Operator.
Definition at line 130 of file SensorsHeadSensors.hpp.
References wb_sensors_head_sensors::Head_Touch_Front, wb_sensors_head_sensors::Head_Touch_Middle, and wb_sensors_head_sensors::Head_Touch_Rear.
operator==() [1/2]
bool guWhiteboard::SensorsHeadSensors::operator== (const SensorsHeadSensors & t_other) const inline
Definition at line 135 of file SensorsHeadSensors.hpp.
References Head_Touch_Front(), Head_Touch_Middle(), and Head_Touch_Rear().
operator==() [2/2]
bool guWhiteboard::SensorsHeadSensors::operator== (const wb_sensors_head_sensors & t_other) const inline
Definition at line 147 of file SensorsHeadSensors.hpp.
References SensorsHeadSensors().
set_Head_Touch_Front()
void guWhiteboard::SensorsHeadSensors::set_Head_Touch_Front (const bool & t_newValue) inline
Definition at line 167 of file SensorsHeadSensors.hpp.
References wb_sensors_head_sensors::Head_Touch_Front.
Referenced by from_string().
set_Head_Touch_Middle()
void guWhiteboard::SensorsHeadSensors::set_Head_Touch_Middle (const bool & t_newValue) inline
Definition at line 182 of file SensorsHeadSensors.hpp.
References wb_sensors_head_sensors::Head_Touch_Middle.
Referenced by from_string().
set_Head_Touch_Rear()
void guWhiteboard::SensorsHeadSensors::set_Head_Touch_Rear (const bool & t_newValue) inline
Definition at line 197 of file SensorsHeadSensors.hpp.
References wb_sensors_head_sensors::Head_Touch_Rear.
Referenced by from_string().
to_string()
std::string guWhiteboard::SensorsHeadSensors::to_string () inline
USE_WB_SENSORS_HEAD_SENSORS_C_CONVERSION
Definition at line 228 of file SensorsHeadSensors.hpp.
References Head_Touch_Front(), Head_Touch_Middle(), Head_Touch_Rear(), SENSORS_HEAD_SENSORS_TO_STRING_BUFFER_SIZE, and wb_sensors_head_sensors_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/SensorsHeadSensors.hpp