gusimplewhiteboard: guWhiteboard::SENSORSTorsoJointTemps Class Reference
guWhiteboard::SENSORSTorsoJointTemps Class Reference
Provides a C++ wrapper around wb_sensors_torsojointtemps.
#include <SENSORSTorsoJointTemps.hpp>
Public Member Functions
SENSORSTorsoJointTemps (float t_HeadYaw=0.0f, float t_HeadPitch=0.0f, float t_LShoulderPitch=0.0f, float t_LShoulderRoll=0.0f, float t_LElbowYaw=0.0f, float t_LElbowRoll=0.0f, float t_LHipYawPitch=0.0f, float t_LHipRoll=0.0f, float t_LHipPitch=0.0f, float t_RHipRoll=0.0f, float t_RHipPitch=0.0f, float t_RShoulderPitch=0.0f, float t_RShoulderRoll=0.0f, float t_RElbowYaw=0.0f, float t_RElbowRoll=0.0f)
Create a new SENSORSTorsoJointTemps.
SENSORSTorsoJointTemps (const SENSORSTorsoJointTemps &t_other)
Copy Constructor.
SENSORSTorsoJointTemps (const struct wb_sensors_torsojointtemps &t_other)
Copy Constructor.
SENSORSTorsoJointTemps & operator= (const SENSORSTorsoJointTemps &t_other)
Copy Assignment Operator.
SENSORSTorsoJointTemps & operator= (const struct wb_sensors_torsojointtemps &t_other)
Copy Assignment Operator.
bool operator== (const SENSORSTorsoJointTemps &t_other) const
bool operator!= (const SENSORSTorsoJointTemps &t_other) const
bool operator== (const wb_sensors_torsojointtemps &t_other) const
bool operator!= (const wb_sensors_torsojointtemps &t_other) const
float & HeadYaw ()
const float & HeadYaw () const
void set_HeadYaw (const float &t_newValue)
float & HeadPitch ()
const float & HeadPitch () const
void set_HeadPitch (const float &t_newValue)
float & LShoulderPitch ()
const float & LShoulderPitch () const
void set_LShoulderPitch (const float &t_newValue)
float & LShoulderRoll ()
const float & LShoulderRoll () const
void set_LShoulderRoll (const float &t_newValue)
float & LElbowYaw ()
const float & LElbowYaw () const
void set_LElbowYaw (const float &t_newValue)
float & LElbowRoll ()
const float & LElbowRoll () const
void set_LElbowRoll (const float &t_newValue)
float & LHipYawPitch ()
const float & LHipYawPitch () const
void set_LHipYawPitch (const float &t_newValue)
float & LHipRoll ()
const float & LHipRoll () const
void set_LHipRoll (const float &t_newValue)
float & LHipPitch ()
const float & LHipPitch () const
void set_LHipPitch (const float &t_newValue)
float & RHipRoll ()
const float & RHipRoll () const
void set_RHipRoll (const float &t_newValue)
float & RHipPitch ()
const float & RHipPitch () const
void set_RHipPitch (const float &t_newValue)
float & RShoulderPitch ()
const float & RShoulderPitch () const
void set_RShoulderPitch (const float &t_newValue)
float & RShoulderRoll ()
const float & RShoulderRoll () const
void set_RShoulderRoll (const float &t_newValue)
float & RElbowYaw ()
const float & RElbowYaw () const
void set_RElbowYaw (const float &t_newValue)
float & RElbowRoll ()
const float & RElbowRoll () const
void set_RElbowRoll (const float &t_newValue)
SENSORSTorsoJointTemps (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_sensors_torsojointtemps
float HeadYaw
Deg Celsius.
float HeadPitch
Deg Celsius.
float LShoulderPitch
Deg Celsius.
float LShoulderRoll
Deg Celsius.
float LElbowYaw
Deg Celsius.
float LElbowRoll
Deg Celsius.
float LHipYawPitch
Deg Celsius.
float LHipRoll
Deg Celsius.
float LHipPitch
Deg Celsius.
float RHipRoll
Deg Celsius.
float RHipPitch
Deg Celsius.
float RShoulderPitch
Deg Celsius.
float RShoulderRoll
Deg Celsius.
float RElbowYaw
Deg Celsius.
float RElbowRoll
Deg Celsius.
Detailed Description
Provides a C++ wrapper around wb_sensors_torsojointtemps.
Definition at line 84 of file SENSORSTorsoJointTemps.hpp.
Constructor & Destructor Documentation
SENSORSTorsoJointTemps() [1/4]
guWhiteboard::SENSORSTorsoJointTemps::SENSORSTorsoJointTemps (float t_HeadYaw = 0.0f, float t_HeadPitch = 0.0f, float t_LShoulderPitch = 0.0f, float t_LShoulderRoll = 0.0f, float t_LElbowYaw = 0.0f, float t_LElbowRoll = 0.0f, float t_LHipYawPitch = 0.0f, float t_LHipRoll = 0.0f, float t_LHipPitch = 0.0f, float t_RHipRoll = 0.0f, float t_RHipPitch = 0.0f, float t_RShoulderPitch = 0.0f, float t_RShoulderRoll = 0.0f, float t_RElbowYaw = 0.0f, float t_RElbowRoll = 0.0f) inline
Create a new SENSORSTorsoJointTemps.
Definition at line 114 of file SENSORSTorsoJointTemps.hpp.
Referenced by operator==().
SENSORSTorsoJointTemps() [2/4]
guWhiteboard::SENSORSTorsoJointTemps::SENSORSTorsoJointTemps (const SENSORSTorsoJointTemps & t_other) inline
Copy Constructor.
Definition at line 121 of file SENSORSTorsoJointTemps.hpp.
References HeadPitch(), HeadYaw(), LElbowRoll(), LElbowYaw(), LHipPitch(), LHipRoll(), LHipYawPitch(), LShoulderPitch(), LShoulderRoll(), RElbowRoll(), RElbowYaw(), RHipPitch(), RHipRoll(), RShoulderPitch(), and RShoulderRoll().
SENSORSTorsoJointTemps() [3/4]
guWhiteboard::SENSORSTorsoJointTemps::SENSORSTorsoJointTemps (const struct wb_sensors_torsojointtemps & t_other) inline
Copy Constructor.
Definition at line 128 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::HeadPitch, wb_sensors_torsojointtemps::HeadYaw, wb_sensors_torsojointtemps::LElbowRoll, wb_sensors_torsojointtemps::LElbowYaw, wb_sensors_torsojointtemps::LHipPitch, wb_sensors_torsojointtemps::LHipRoll, wb_sensors_torsojointtemps::LHipYawPitch, wb_sensors_torsojointtemps::LShoulderPitch, wb_sensors_torsojointtemps::LShoulderRoll, wb_sensors_torsojointtemps::RElbowRoll, wb_sensors_torsojointtemps::RElbowYaw, wb_sensors_torsojointtemps::RHipPitch, wb_sensors_torsojointtemps::RHipRoll, wb_sensors_torsojointtemps::RShoulderPitch, and wb_sensors_torsojointtemps::RShoulderRoll.
SENSORSTorsoJointTemps() [4/4]
guWhiteboard::SENSORSTorsoJointTemps::SENSORSTorsoJointTemps (const std::string & t_str) inline
String Constructor.
Definition at line 411 of file SENSORSTorsoJointTemps.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::SENSORSTorsoJointTemps::description () inline
USE_WB_SENSORS_TORSOJOINTTEMPS_C_CONVERSION
Definition at line 416 of file SENSORSTorsoJointTemps.hpp.
References HeadPitch(), HeadYaw(), LElbowRoll(), LElbowYaw(), LHipPitch(), LHipRoll(), LHipYawPitch(), LShoulderPitch(), LShoulderRoll(), RElbowRoll(), RElbowYaw(), RHipPitch(), RHipRoll(), RShoulderPitch(), RShoulderRoll(), SENSORS_TORSOJOINTTEMPS_DESC_BUFFER_SIZE, and wb_sensors_torsojointtemps_description().
from_string()
void guWhiteboard::SENSORSTorsoJointTemps::from_string (const std::string & t_str) inline
USE_WB_SENSORS_TORSOJOINTTEMPS_C_CONVERSION
Definition at line 502 of file SENSORSTorsoJointTemps.hpp.
References SENSORS_TORSOJOINTTEMPS_DESC_BUFFER_SIZE, set_HeadPitch(), set_HeadYaw(), set_LElbowRoll(), set_LElbowYaw(), set_LHipPitch(), set_LHipRoll(), set_LHipYawPitch(), set_LShoulderPitch(), set_LShoulderRoll(), set_RElbowRoll(), set_RElbowYaw(), set_RHipPitch(), set_RHipRoll(), set_RShoulderPitch(), and set_RShoulderRoll().
Referenced by SENSORSTorsoJointTemps().
HeadPitch() [1/2]
float & guWhiteboard::SENSORSTorsoJointTemps::HeadPitch () inline
Definition at line 197 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::HeadPitch.
Referenced by SENSORSTorsoJointTemps(), description(), operator=(), operator==(), and to_string().
HeadPitch() [2/2]
const float & guWhiteboard::SENSORSTorsoJointTemps::HeadPitch () const inline
Definition at line 202 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::HeadPitch.
HeadYaw() [1/2]
float & guWhiteboard::SENSORSTorsoJointTemps::HeadYaw () inline
Definition at line 182 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::HeadYaw.
Referenced by SENSORSTorsoJointTemps(), description(), operator=(), operator==(), and to_string().
HeadYaw() [2/2]
const float & guWhiteboard::SENSORSTorsoJointTemps::HeadYaw () const inline
Definition at line 187 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::HeadYaw.
LElbowRoll() [1/2]
float & guWhiteboard::SENSORSTorsoJointTemps::LElbowRoll () inline
Definition at line 257 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::LElbowRoll.
Referenced by SENSORSTorsoJointTemps(), description(), operator=(), operator==(), and to_string().
LElbowRoll() [2/2]
const float & guWhiteboard::SENSORSTorsoJointTemps::LElbowRoll () const inline
Definition at line 262 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::LElbowRoll.
LElbowYaw() [1/2]
float & guWhiteboard::SENSORSTorsoJointTemps::LElbowYaw () inline
Definition at line 242 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::LElbowYaw.
Referenced by SENSORSTorsoJointTemps(), description(), operator=(), operator==(), and to_string().
LElbowYaw() [2/2]
const float & guWhiteboard::SENSORSTorsoJointTemps::LElbowYaw () const inline
Definition at line 247 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::LElbowYaw.
LHipPitch() [1/2]
float & guWhiteboard::SENSORSTorsoJointTemps::LHipPitch () inline
Definition at line 302 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::LHipPitch.
Referenced by SENSORSTorsoJointTemps(), description(), operator=(), operator==(), and to_string().
LHipPitch() [2/2]
const float & guWhiteboard::SENSORSTorsoJointTemps::LHipPitch () const inline
Definition at line 307 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::LHipPitch.
LHipRoll() [1/2]
float & guWhiteboard::SENSORSTorsoJointTemps::LHipRoll () inline
Definition at line 287 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::LHipRoll.
Referenced by SENSORSTorsoJointTemps(), description(), operator=(), operator==(), and to_string().
LHipRoll() [2/2]
const float & guWhiteboard::SENSORSTorsoJointTemps::LHipRoll () const inline
Definition at line 292 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::LHipRoll.
LHipYawPitch() [1/2]
float & guWhiteboard::SENSORSTorsoJointTemps::LHipYawPitch () inline
Definition at line 272 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::LHipYawPitch.
Referenced by SENSORSTorsoJointTemps(), description(), operator=(), operator==(), and to_string().
LHipYawPitch() [2/2]
const float & guWhiteboard::SENSORSTorsoJointTemps::LHipYawPitch () const inline
Definition at line 277 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::LHipYawPitch.
LShoulderPitch() [1/2]
float & guWhiteboard::SENSORSTorsoJointTemps::LShoulderPitch () inline
Definition at line 212 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::LShoulderPitch.
Referenced by SENSORSTorsoJointTemps(), description(), operator=(), operator==(), and to_string().
LShoulderPitch() [2/2]
const float & guWhiteboard::SENSORSTorsoJointTemps::LShoulderPitch () const inline
Definition at line 217 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::LShoulderPitch.
LShoulderRoll() [1/2]
float & guWhiteboard::SENSORSTorsoJointTemps::LShoulderRoll () inline
Definition at line 227 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::LShoulderRoll.
Referenced by SENSORSTorsoJointTemps(), description(), operator=(), operator==(), and to_string().
LShoulderRoll() [2/2]
const float & guWhiteboard::SENSORSTorsoJointTemps::LShoulderRoll () const inline
Definition at line 232 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::LShoulderRoll.
operator!=() [1/2]
bool guWhiteboard::SENSORSTorsoJointTemps::operator!= (const SENSORSTorsoJointTemps & t_other) const inline
Definition at line 167 of file SENSORSTorsoJointTemps.hpp.
operator!=() [2/2]
bool guWhiteboard::SENSORSTorsoJointTemps::operator!= (const wb_sensors_torsojointtemps & t_other) const inline
Definition at line 177 of file SENSORSTorsoJointTemps.hpp.
operator=() [1/2]
SENSORSTorsoJointTemps & guWhiteboard::SENSORSTorsoJointTemps::operator= (const SENSORSTorsoJointTemps & t_other) inline
Copy Assignment Operator.
Definition at line 135 of file SENSORSTorsoJointTemps.hpp.
References HeadPitch(), HeadYaw(), LElbowRoll(), LElbowYaw(), LHipPitch(), LHipRoll(), LHipYawPitch(), LShoulderPitch(), LShoulderRoll(), RElbowRoll(), RElbowYaw(), RHipPitch(), RHipRoll(), RShoulderPitch(), and RShoulderRoll().
operator=() [2/2]
SENSORSTorsoJointTemps & guWhiteboard::SENSORSTorsoJointTemps::operator= (const struct wb_sensors_torsojointtemps & t_other) inline
Copy Assignment Operator.
Definition at line 143 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::HeadPitch, wb_sensors_torsojointtemps::HeadYaw, wb_sensors_torsojointtemps::LElbowRoll, wb_sensors_torsojointtemps::LElbowYaw, wb_sensors_torsojointtemps::LHipPitch, wb_sensors_torsojointtemps::LHipRoll, wb_sensors_torsojointtemps::LHipYawPitch, wb_sensors_torsojointtemps::LShoulderPitch, wb_sensors_torsojointtemps::LShoulderRoll, wb_sensors_torsojointtemps::RElbowRoll, wb_sensors_torsojointtemps::RElbowYaw, wb_sensors_torsojointtemps::RHipPitch, wb_sensors_torsojointtemps::RHipRoll, wb_sensors_torsojointtemps::RShoulderPitch, and wb_sensors_torsojointtemps::RShoulderRoll.
operator==() [1/2]
bool guWhiteboard::SENSORSTorsoJointTemps::operator== (const SENSORSTorsoJointTemps & t_other) const inline
Definition at line 148 of file SENSORSTorsoJointTemps.hpp.
References HeadPitch(), HeadYaw(), LElbowRoll(), LElbowYaw(), LHipPitch(), LHipRoll(), LHipYawPitch(), LShoulderPitch(), LShoulderRoll(), RElbowRoll(), RElbowYaw(), RHipPitch(), RHipRoll(), RShoulderPitch(), and RShoulderRoll().
operator==() [2/2]
bool guWhiteboard::SENSORSTorsoJointTemps::operator== (const wb_sensors_torsojointtemps & t_other) const inline
Definition at line 172 of file SENSORSTorsoJointTemps.hpp.
References SENSORSTorsoJointTemps().
RElbowRoll() [1/2]
float & guWhiteboard::SENSORSTorsoJointTemps::RElbowRoll () inline
Definition at line 392 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::RElbowRoll.
Referenced by SENSORSTorsoJointTemps(), description(), operator=(), operator==(), and to_string().
RElbowRoll() [2/2]
const float & guWhiteboard::SENSORSTorsoJointTemps::RElbowRoll () const inline
Definition at line 397 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::RElbowRoll.
RElbowYaw() [1/2]
float & guWhiteboard::SENSORSTorsoJointTemps::RElbowYaw () inline
Definition at line 377 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::RElbowYaw.
Referenced by SENSORSTorsoJointTemps(), description(), operator=(), operator==(), and to_string().
RElbowYaw() [2/2]
const float & guWhiteboard::SENSORSTorsoJointTemps::RElbowYaw () const inline
Definition at line 382 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::RElbowYaw.
RHipPitch() [1/2]
float & guWhiteboard::SENSORSTorsoJointTemps::RHipPitch () inline
Definition at line 332 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::RHipPitch.
Referenced by SENSORSTorsoJointTemps(), description(), operator=(), operator==(), and to_string().
RHipPitch() [2/2]
const float & guWhiteboard::SENSORSTorsoJointTemps::RHipPitch () const inline
Definition at line 337 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::RHipPitch.
RHipRoll() [1/2]
float & guWhiteboard::SENSORSTorsoJointTemps::RHipRoll () inline
Definition at line 317 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::RHipRoll.
Referenced by SENSORSTorsoJointTemps(), description(), operator=(), operator==(), and to_string().
RHipRoll() [2/2]
const float & guWhiteboard::SENSORSTorsoJointTemps::RHipRoll () const inline
Definition at line 322 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::RHipRoll.
RShoulderPitch() [1/2]
float & guWhiteboard::SENSORSTorsoJointTemps::RShoulderPitch () inline
Definition at line 347 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::RShoulderPitch.
Referenced by SENSORSTorsoJointTemps(), description(), operator=(), operator==(), and to_string().
RShoulderPitch() [2/2]
const float & guWhiteboard::SENSORSTorsoJointTemps::RShoulderPitch () const inline
Definition at line 352 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::RShoulderPitch.
RShoulderRoll() [1/2]
float & guWhiteboard::SENSORSTorsoJointTemps::RShoulderRoll () inline
Definition at line 362 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::RShoulderRoll.
Referenced by SENSORSTorsoJointTemps(), description(), operator=(), operator==(), and to_string().
RShoulderRoll() [2/2]
const float & guWhiteboard::SENSORSTorsoJointTemps::RShoulderRoll () const inline
Definition at line 367 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::RShoulderRoll.
set_HeadPitch()
void guWhiteboard::SENSORSTorsoJointTemps::set_HeadPitch (const float & t_newValue) inline
Definition at line 207 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::HeadPitch.
Referenced by from_string().
set_HeadYaw()
void guWhiteboard::SENSORSTorsoJointTemps::set_HeadYaw (const float & t_newValue) inline
Definition at line 192 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::HeadYaw.
Referenced by from_string().
set_LElbowRoll()
void guWhiteboard::SENSORSTorsoJointTemps::set_LElbowRoll (const float & t_newValue) inline
Definition at line 267 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::LElbowRoll.
Referenced by from_string().
set_LElbowYaw()
void guWhiteboard::SENSORSTorsoJointTemps::set_LElbowYaw (const float & t_newValue) inline
Definition at line 252 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::LElbowYaw.
Referenced by from_string().
set_LHipPitch()
void guWhiteboard::SENSORSTorsoJointTemps::set_LHipPitch (const float & t_newValue) inline
Definition at line 312 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::LHipPitch.
Referenced by from_string().
set_LHipRoll()
void guWhiteboard::SENSORSTorsoJointTemps::set_LHipRoll (const float & t_newValue) inline
Definition at line 297 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::LHipRoll.
Referenced by from_string().
set_LHipYawPitch()
void guWhiteboard::SENSORSTorsoJointTemps::set_LHipYawPitch (const float & t_newValue) inline
Definition at line 282 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::LHipYawPitch.
Referenced by from_string().
set_LShoulderPitch()
void guWhiteboard::SENSORSTorsoJointTemps::set_LShoulderPitch (const float & t_newValue) inline
Definition at line 222 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::LShoulderPitch.
Referenced by from_string().
set_LShoulderRoll()
void guWhiteboard::SENSORSTorsoJointTemps::set_LShoulderRoll (const float & t_newValue) inline
Definition at line 237 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::LShoulderRoll.
Referenced by from_string().
set_RElbowRoll()
void guWhiteboard::SENSORSTorsoJointTemps::set_RElbowRoll (const float & t_newValue) inline
Definition at line 402 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::RElbowRoll.
Referenced by from_string().
set_RElbowYaw()
void guWhiteboard::SENSORSTorsoJointTemps::set_RElbowYaw (const float & t_newValue) inline
Definition at line 387 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::RElbowYaw.
Referenced by from_string().
set_RHipPitch()
void guWhiteboard::SENSORSTorsoJointTemps::set_RHipPitch (const float & t_newValue) inline
Definition at line 342 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::RHipPitch.
Referenced by from_string().
set_RHipRoll()
void guWhiteboard::SENSORSTorsoJointTemps::set_RHipRoll (const float & t_newValue) inline
Definition at line 327 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::RHipRoll.
Referenced by from_string().
set_RShoulderPitch()
void guWhiteboard::SENSORSTorsoJointTemps::set_RShoulderPitch (const float & t_newValue) inline
Definition at line 357 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::RShoulderPitch.
Referenced by from_string().
set_RShoulderRoll()
void guWhiteboard::SENSORSTorsoJointTemps::set_RShoulderRoll (const float & t_newValue) inline
Definition at line 372 of file SENSORSTorsoJointTemps.hpp.
References wb_sensors_torsojointtemps::RShoulderRoll.
Referenced by from_string().
to_string()
std::string guWhiteboard::SENSORSTorsoJointTemps::to_string () inline
USE_WB_SENSORS_TORSOJOINTTEMPS_C_CONVERSION
Definition at line 457 of file SENSORSTorsoJointTemps.hpp.
References HeadPitch(), HeadYaw(), LElbowRoll(), LElbowYaw(), LHipPitch(), LHipRoll(), LHipYawPitch(), LShoulderPitch(), LShoulderRoll(), RElbowRoll(), RElbowYaw(), RHipPitch(), RHipRoll(), RShoulderPitch(), RShoulderRoll(), SENSORS_TORSOJOINTTEMPS_TO_STRING_BUFFER_SIZE, and wb_sensors_torsojointtemps_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/SENSORSTorsoJointTemps.hpp