gusimplewhiteboard: guWhiteboard::TemperatureSensors Class Reference
guWhiteboard::TemperatureSensors Class Reference
Provides a C++ wrapper around wb_temperature_sensors.
#include <TemperatureSensors.hpp>
Public Member Functions
TemperatureSensors (bool t_LKneePitch=false, bool t_LAnklePitch=false, bool t_LAnkleRoll=false, bool t_RKneePitch=false, bool t_RAnklePitch=false, bool t_RAnkleRoll=false)
Create a new TemperatureSensors.
TemperatureSensors (const TemperatureSensors &t_other)
Copy Constructor.
TemperatureSensors (const struct wb_temperature_sensors &t_other)
Copy Constructor.
TemperatureSensors & operator= (const TemperatureSensors &t_other)
Copy Assignment Operator.
TemperatureSensors & operator= (const struct wb_temperature_sensors &t_other)
Copy Assignment Operator.
bool operator== (const TemperatureSensors &t_other) const
bool operator!= (const TemperatureSensors &t_other) const
bool operator== (const wb_temperature_sensors &t_other) const
bool operator!= (const wb_temperature_sensors &t_other) const
bool & LKneePitch ()
const bool & LKneePitch () const
void set_LKneePitch (const bool &t_newValue)
bool & LAnklePitch ()
const bool & LAnklePitch () const
void set_LAnklePitch (const bool &t_newValue)
bool & LAnkleRoll ()
const bool & LAnkleRoll () const
void set_LAnkleRoll (const bool &t_newValue)
bool & RKneePitch ()
const bool & RKneePitch () const
void set_RKneePitch (const bool &t_newValue)
bool & RAnklePitch ()
const bool & RAnklePitch () const
void set_RAnklePitch (const bool &t_newValue)
bool & RAnkleRoll ()
const bool & RAnkleRoll () const
void set_RAnkleRoll (const bool &t_newValue)
TemperatureSensors (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_temperature_sensors
bool LKneePitch
Is the left knee pitch overheating.
bool LAnklePitch
Is the left ankle pitch overheating.
bool LAnkleRoll
Is the left ankle roll overheating.
bool RKneePitch
Is the right knee pitch overheating.
bool RAnklePitch
Is the right ankle pitch overheating.
bool RAnkleRoll
Is the right ankle roll overheating.
Detailed Description
Provides a C++ wrapper around wb_temperature_sensors.
Definition at line 83 of file TemperatureSensors.hpp.
Constructor & Destructor Documentation
TemperatureSensors() [1/4]
guWhiteboard::TemperatureSensors::TemperatureSensors (bool t_LKneePitch = false, bool t_LAnklePitch = false, bool t_LAnkleRoll = false, bool t_RKneePitch = false, bool t_RAnklePitch = false, bool t_RAnkleRoll = false) inline
Create a new TemperatureSensors.
Definition at line 104 of file TemperatureSensors.hpp.
Referenced by operator==().
TemperatureSensors() [2/4]
guWhiteboard::TemperatureSensors::TemperatureSensors (const TemperatureSensors & t_other) inline
Copy Constructor.
Definition at line 111 of file TemperatureSensors.hpp.
References LAnklePitch(), LAnkleRoll(), LKneePitch(), RAnklePitch(), RAnkleRoll(), and RKneePitch().
TemperatureSensors() [3/4]
guWhiteboard::TemperatureSensors::TemperatureSensors (const struct wb_temperature_sensors & t_other) inline
Copy Constructor.
Definition at line 118 of file TemperatureSensors.hpp.
References wb_temperature_sensors::LAnklePitch, wb_temperature_sensors::LAnkleRoll, wb_temperature_sensors::LKneePitch, wb_temperature_sensors::RAnklePitch, wb_temperature_sensors::RAnkleRoll, and wb_temperature_sensors::RKneePitch.
TemperatureSensors() [4/4]
guWhiteboard::TemperatureSensors::TemperatureSensors (const std::string & t_str) inline
String Constructor.
Definition at line 257 of file TemperatureSensors.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::TemperatureSensors::description () inline
USE_WB_TEMPERATURE_SENSORS_C_CONVERSION
Definition at line 262 of file TemperatureSensors.hpp.
References LAnklePitch(), LAnkleRoll(), LKneePitch(), RAnklePitch(), RAnkleRoll(), RKneePitch(), TEMPERATURE_SENSORS_DESC_BUFFER_SIZE, and wb_temperature_sensors_description().
from_string()
void guWhiteboard::TemperatureSensors::from_string (const std::string & t_str) inline
USE_WB_TEMPERATURE_SENSORS_C_CONVERSION
Definition at line 312 of file TemperatureSensors.hpp.
References set_LAnklePitch(), set_LAnkleRoll(), set_LKneePitch(), set_RAnklePitch(), set_RAnkleRoll(), set_RKneePitch(), and TEMPERATURE_SENSORS_DESC_BUFFER_SIZE.
Referenced by TemperatureSensors().
LAnklePitch() [1/2]
bool & guWhiteboard::TemperatureSensors::LAnklePitch () inline
Definition at line 178 of file TemperatureSensors.hpp.
References wb_temperature_sensors::LAnklePitch.
Referenced by TemperatureSensors(), description(), operator=(), operator==(), and to_string().
LAnklePitch() [2/2]
const bool & guWhiteboard::TemperatureSensors::LAnklePitch () const inline
Definition at line 183 of file TemperatureSensors.hpp.
References wb_temperature_sensors::LAnklePitch.
LAnkleRoll() [1/2]
bool & guWhiteboard::TemperatureSensors::LAnkleRoll () inline
Definition at line 193 of file TemperatureSensors.hpp.
References wb_temperature_sensors::LAnkleRoll.
Referenced by TemperatureSensors(), description(), operator=(), operator==(), and to_string().
LAnkleRoll() [2/2]
const bool & guWhiteboard::TemperatureSensors::LAnkleRoll () const inline
Definition at line 198 of file TemperatureSensors.hpp.
References wb_temperature_sensors::LAnkleRoll.
LKneePitch() [1/2]
bool & guWhiteboard::TemperatureSensors::LKneePitch () inline
Definition at line 163 of file TemperatureSensors.hpp.
References wb_temperature_sensors::LKneePitch.
Referenced by TemperatureSensors(), description(), operator=(), operator==(), and to_string().
LKneePitch() [2/2]
const bool & guWhiteboard::TemperatureSensors::LKneePitch () const inline
Definition at line 168 of file TemperatureSensors.hpp.
References wb_temperature_sensors::LKneePitch.
operator!=() [1/2]
bool guWhiteboard::TemperatureSensors::operator!= (const TemperatureSensors & t_other) const inline
Definition at line 148 of file TemperatureSensors.hpp.
operator!=() [2/2]
bool guWhiteboard::TemperatureSensors::operator!= (const wb_temperature_sensors & t_other) const inline
Definition at line 158 of file TemperatureSensors.hpp.
operator=() [1/2]
TemperatureSensors & guWhiteboard::TemperatureSensors::operator= (const struct wb_temperature_sensors & t_other) inline
Copy Assignment Operator.
Definition at line 133 of file TemperatureSensors.hpp.
References wb_temperature_sensors::LAnklePitch, wb_temperature_sensors::LAnkleRoll, wb_temperature_sensors::LKneePitch, wb_temperature_sensors::RAnklePitch, wb_temperature_sensors::RAnkleRoll, and wb_temperature_sensors::RKneePitch.
operator=() [2/2]
TemperatureSensors & guWhiteboard::TemperatureSensors::operator= (const TemperatureSensors & t_other) inline
Copy Assignment Operator.
Definition at line 125 of file TemperatureSensors.hpp.
References LAnklePitch(), LAnkleRoll(), LKneePitch(), RAnklePitch(), RAnkleRoll(), and RKneePitch().
operator==() [1/2]
bool guWhiteboard::TemperatureSensors::operator== (const TemperatureSensors & t_other) const inline
Definition at line 138 of file TemperatureSensors.hpp.
References LAnklePitch(), LAnkleRoll(), LKneePitch(), RAnklePitch(), RAnkleRoll(), and RKneePitch().
operator==() [2/2]
bool guWhiteboard::TemperatureSensors::operator== (const wb_temperature_sensors & t_other) const inline
Definition at line 153 of file TemperatureSensors.hpp.
References TemperatureSensors().
RAnklePitch() [1/2]
bool & guWhiteboard::TemperatureSensors::RAnklePitch () inline
Definition at line 223 of file TemperatureSensors.hpp.
References wb_temperature_sensors::RAnklePitch.
Referenced by TemperatureSensors(), description(), operator=(), operator==(), and to_string().
RAnklePitch() [2/2]
const bool & guWhiteboard::TemperatureSensors::RAnklePitch () const inline
Definition at line 228 of file TemperatureSensors.hpp.
References wb_temperature_sensors::RAnklePitch.
RAnkleRoll() [1/2]
bool & guWhiteboard::TemperatureSensors::RAnkleRoll () inline
Definition at line 238 of file TemperatureSensors.hpp.
References wb_temperature_sensors::RAnkleRoll.
Referenced by TemperatureSensors(), description(), operator=(), operator==(), and to_string().
RAnkleRoll() [2/2]
const bool & guWhiteboard::TemperatureSensors::RAnkleRoll () const inline
Definition at line 243 of file TemperatureSensors.hpp.
References wb_temperature_sensors::RAnkleRoll.
RKneePitch() [1/2]
bool & guWhiteboard::TemperatureSensors::RKneePitch () inline
Definition at line 208 of file TemperatureSensors.hpp.
References wb_temperature_sensors::RKneePitch.
Referenced by TemperatureSensors(), description(), operator=(), operator==(), and to_string().
RKneePitch() [2/2]
const bool & guWhiteboard::TemperatureSensors::RKneePitch () const inline
Definition at line 213 of file TemperatureSensors.hpp.
References wb_temperature_sensors::RKneePitch.
set_LAnklePitch()
void guWhiteboard::TemperatureSensors::set_LAnklePitch (const bool & t_newValue) inline
Definition at line 188 of file TemperatureSensors.hpp.
References wb_temperature_sensors::LAnklePitch.
Referenced by from_string().
set_LAnkleRoll()
void guWhiteboard::TemperatureSensors::set_LAnkleRoll (const bool & t_newValue) inline
Definition at line 203 of file TemperatureSensors.hpp.
References wb_temperature_sensors::LAnkleRoll.
Referenced by from_string().
set_LKneePitch()
void guWhiteboard::TemperatureSensors::set_LKneePitch (const bool & t_newValue) inline
Definition at line 173 of file TemperatureSensors.hpp.
References wb_temperature_sensors::LKneePitch.
Referenced by from_string().
set_RAnklePitch()
void guWhiteboard::TemperatureSensors::set_RAnklePitch (const bool & t_newValue) inline
Definition at line 233 of file TemperatureSensors.hpp.
References wb_temperature_sensors::RAnklePitch.
Referenced by from_string().
set_RAnkleRoll()
void guWhiteboard::TemperatureSensors::set_RAnkleRoll (const bool & t_newValue) inline
Definition at line 248 of file TemperatureSensors.hpp.
References wb_temperature_sensors::RAnkleRoll.
Referenced by from_string().
set_RKneePitch()
void guWhiteboard::TemperatureSensors::set_RKneePitch (const bool & t_newValue) inline
Definition at line 218 of file TemperatureSensors.hpp.
References wb_temperature_sensors::RKneePitch.
Referenced by from_string().
to_string()
std::string guWhiteboard::TemperatureSensors::to_string () inline
USE_WB_TEMPERATURE_SENSORS_C_CONVERSION
Definition at line 285 of file TemperatureSensors.hpp.
References LAnklePitch(), LAnkleRoll(), LKneePitch(), RAnklePitch(), RAnkleRoll(), RKneePitch(), TEMPERATURE_SENSORS_TO_STRING_BUFFER_SIZE, and wb_temperature_sensors_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/TemperatureSensors.hpp