gusimplewhiteboard: guWhiteboard::SENSORSArmJointSensors Class Reference
guWhiteboard::SENSORSArmJointSensors Class Reference
Provides a C++ wrapper around wb_sensors_armjointsensors.
#include <SENSORSArmJointSensors.hpp>
Public Member Functions
SENSORSArmJointSensors (float t_LShoulderPitch=0.0f, float t_LShoulderRoll=0.0f, float t_LElbowRoll=0.0f, float t_LElbowYaw=0.0f, float t_RShoulderPitch=0.0f, float t_RShoulderRoll=0.0f, float t_RElbowRoll=0.0f, float t_RElbowYaw=0.0f, float t_LWristYaw=0.0f, float t_RWristYaw=0.0f)
Create a new SENSORSArmJointSensors.
SENSORSArmJointSensors (const SENSORSArmJointSensors &t_other)
Copy Constructor.
SENSORSArmJointSensors (const struct wb_sensors_armjointsensors &t_other)
Copy Constructor.
SENSORSArmJointSensors & operator= (const SENSORSArmJointSensors &t_other)
Copy Assignment Operator.
SENSORSArmJointSensors & operator= (const struct wb_sensors_armjointsensors &t_other)
Copy Assignment Operator.
bool operator== (const SENSORSArmJointSensors &t_other) const
bool operator!= (const SENSORSArmJointSensors &t_other) const
bool operator== (const wb_sensors_armjointsensors &t_other) const
bool operator!= (const wb_sensors_armjointsensors &t_other) const
float & LShoulderPitch ()
const float & LShoulderPitch () const
void set_LShoulderPitch (const float &t_newValue)
float & LShoulderRoll ()
const float & LShoulderRoll () const
void set_LShoulderRoll (const float &t_newValue)
float & LElbowRoll ()
const float & LElbowRoll () const
void set_LElbowRoll (const float &t_newValue)
float & LElbowYaw ()
const float & LElbowYaw () const
void set_LElbowYaw (const float &t_newValue)
float & RShoulderPitch ()
const float & RShoulderPitch () const
void set_RShoulderPitch (const float &t_newValue)
float & RShoulderRoll ()
const float & RShoulderRoll () const
void set_RShoulderRoll (const float &t_newValue)
float & RElbowRoll ()
const float & RElbowRoll () const
void set_RElbowRoll (const float &t_newValue)
float & RElbowYaw ()
const float & RElbowYaw () const
void set_RElbowYaw (const float &t_newValue)
float & LWristYaw ()
const float & LWristYaw () const
void set_LWristYaw (const float &t_newValue)
float & RWristYaw ()
const float & RWristYaw () const
void set_RWristYaw (const float &t_newValue)
SENSORSArmJointSensors (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_sensors_armjointsensors
float LShoulderPitch
pitch of the shoulder joint (left)
float LShoulderRoll
roll of the shoulder joint (left)
float LElbowRoll
roll of the elbow joint (left)
float LElbowYaw
yaw of the elbow joint (left)
float RShoulderPitch
pitch of the shoulder joint (right)
float RShoulderRoll
roll of the shoulder joint (right)
float RElbowRoll
roll of the elbow joint (right)
float RElbowYaw
yaw of the elbow joint (right)
float LWristYaw
yaw of the wrist joint (left)
float RWristYaw
yaw of the wrist joint (right)
Detailed Description
Provides a C++ wrapper around wb_sensors_armjointsensors.
Definition at line 84 of file SENSORSArmJointSensors.hpp.
Constructor & Destructor Documentation
SENSORSArmJointSensors() [1/4]
guWhiteboard::SENSORSArmJointSensors::SENSORSArmJointSensors (float t_LShoulderPitch = 0.0f, float t_LShoulderRoll = 0.0f, float t_LElbowRoll = 0.0f, float t_LElbowYaw = 0.0f, float t_RShoulderPitch = 0.0f, float t_RShoulderRoll = 0.0f, float t_RElbowRoll = 0.0f, float t_RElbowYaw = 0.0f, float t_LWristYaw = 0.0f, float t_RWristYaw = 0.0f) inline
Create a new SENSORSArmJointSensors.
Definition at line 109 of file SENSORSArmJointSensors.hpp.
Referenced by operator==().
SENSORSArmJointSensors() [2/4]
guWhiteboard::SENSORSArmJointSensors::SENSORSArmJointSensors (const SENSORSArmJointSensors & t_other) inline
Copy Constructor.
Definition at line 116 of file SENSORSArmJointSensors.hpp.
References LElbowRoll(), LElbowYaw(), LShoulderPitch(), LShoulderRoll(), LWristYaw(), RElbowRoll(), RElbowYaw(), RShoulderPitch(), RShoulderRoll(), and RWristYaw().
SENSORSArmJointSensors() [3/4]
guWhiteboard::SENSORSArmJointSensors::SENSORSArmJointSensors (const struct wb_sensors_armjointsensors & t_other) inline
Copy Constructor.
Definition at line 123 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::LElbowRoll, wb_sensors_armjointsensors::LElbowYaw, wb_sensors_armjointsensors::LShoulderPitch, wb_sensors_armjointsensors::LShoulderRoll, wb_sensors_armjointsensors::LWristYaw, wb_sensors_armjointsensors::RElbowRoll, wb_sensors_armjointsensors::RElbowYaw, wb_sensors_armjointsensors::RShoulderPitch, wb_sensors_armjointsensors::RShoulderRoll, and wb_sensors_armjointsensors::RWristYaw.
SENSORSArmJointSensors() [4/4]
guWhiteboard::SENSORSArmJointSensors::SENSORSArmJointSensors (const std::string & t_str) inline
String Constructor.
Definition at line 326 of file SENSORSArmJointSensors.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::SENSORSArmJointSensors::description () inline
USE_WB_SENSORS_ARMJOINTSENSORS_C_CONVERSION
Definition at line 331 of file SENSORSArmJointSensors.hpp.
References LElbowRoll(), LElbowYaw(), LShoulderPitch(), LShoulderRoll(), LWristYaw(), RElbowRoll(), RElbowYaw(), RShoulderPitch(), RShoulderRoll(), RWristYaw(), SENSORS_ARMJOINTSENSORS_DESC_BUFFER_SIZE, and wb_sensors_armjointsensors_description().
from_string()
void guWhiteboard::SENSORSArmJointSensors::from_string (const std::string & t_str) inline
USE_WB_SENSORS_ARMJOINTSENSORS_C_CONVERSION
Definition at line 397 of file SENSORSArmJointSensors.hpp.
References SENSORS_ARMJOINTSENSORS_DESC_BUFFER_SIZE, set_LElbowRoll(), set_LElbowYaw(), set_LShoulderPitch(), set_LShoulderRoll(), set_LWristYaw(), set_RElbowRoll(), set_RElbowYaw(), set_RShoulderPitch(), set_RShoulderRoll(), and set_RWristYaw().
Referenced by SENSORSArmJointSensors().
LElbowRoll() [1/2]
float & guWhiteboard::SENSORSArmJointSensors::LElbowRoll () inline
Definition at line 202 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::LElbowRoll.
Referenced by SENSORSArmJointSensors(), description(), operator=(), operator==(), and to_string().
LElbowRoll() [2/2]
const float & guWhiteboard::SENSORSArmJointSensors::LElbowRoll () const inline
Definition at line 207 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::LElbowRoll.
LElbowYaw() [1/2]
float & guWhiteboard::SENSORSArmJointSensors::LElbowYaw () inline
Definition at line 217 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::LElbowYaw.
Referenced by SENSORSArmJointSensors(), description(), operator=(), operator==(), and to_string().
LElbowYaw() [2/2]
const float & guWhiteboard::SENSORSArmJointSensors::LElbowYaw () const inline
Definition at line 222 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::LElbowYaw.
LShoulderPitch() [1/2]
float & guWhiteboard::SENSORSArmJointSensors::LShoulderPitch () inline
Definition at line 172 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::LShoulderPitch.
Referenced by SENSORSArmJointSensors(), description(), operator=(), operator==(), and to_string().
LShoulderPitch() [2/2]
const float & guWhiteboard::SENSORSArmJointSensors::LShoulderPitch () const inline
Definition at line 177 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::LShoulderPitch.
LShoulderRoll() [1/2]
float & guWhiteboard::SENSORSArmJointSensors::LShoulderRoll () inline
Definition at line 187 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::LShoulderRoll.
Referenced by SENSORSArmJointSensors(), description(), operator=(), operator==(), and to_string().
LShoulderRoll() [2/2]
const float & guWhiteboard::SENSORSArmJointSensors::LShoulderRoll () const inline
Definition at line 192 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::LShoulderRoll.
LWristYaw() [1/2]
float & guWhiteboard::SENSORSArmJointSensors::LWristYaw () inline
Definition at line 292 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::LWristYaw.
Referenced by SENSORSArmJointSensors(), description(), operator=(), operator==(), and to_string().
LWristYaw() [2/2]
const float & guWhiteboard::SENSORSArmJointSensors::LWristYaw () const inline
Definition at line 297 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::LWristYaw.
operator!=() [1/2]
bool guWhiteboard::SENSORSArmJointSensors::operator!= (const SENSORSArmJointSensors & t_other) const inline
Definition at line 157 of file SENSORSArmJointSensors.hpp.
operator!=() [2/2]
bool guWhiteboard::SENSORSArmJointSensors::operator!= (const wb_sensors_armjointsensors & t_other) const inline
Definition at line 167 of file SENSORSArmJointSensors.hpp.
operator=() [1/2]
SENSORSArmJointSensors & guWhiteboard::SENSORSArmJointSensors::operator= (const SENSORSArmJointSensors & t_other) inline
Copy Assignment Operator.
Definition at line 130 of file SENSORSArmJointSensors.hpp.
References LElbowRoll(), LElbowYaw(), LShoulderPitch(), LShoulderRoll(), LWristYaw(), RElbowRoll(), RElbowYaw(), RShoulderPitch(), RShoulderRoll(), and RWristYaw().
operator=() [2/2]
SENSORSArmJointSensors & guWhiteboard::SENSORSArmJointSensors::operator= (const struct wb_sensors_armjointsensors & t_other) inline
Copy Assignment Operator.
Definition at line 138 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::LElbowRoll, wb_sensors_armjointsensors::LElbowYaw, wb_sensors_armjointsensors::LShoulderPitch, wb_sensors_armjointsensors::LShoulderRoll, wb_sensors_armjointsensors::LWristYaw, wb_sensors_armjointsensors::RElbowRoll, wb_sensors_armjointsensors::RElbowYaw, wb_sensors_armjointsensors::RShoulderPitch, wb_sensors_armjointsensors::RShoulderRoll, and wb_sensors_armjointsensors::RWristYaw.
operator==() [1/2]
bool guWhiteboard::SENSORSArmJointSensors::operator== (const SENSORSArmJointSensors & t_other) const inline
Definition at line 143 of file SENSORSArmJointSensors.hpp.
References LElbowRoll(), LElbowYaw(), LShoulderPitch(), LShoulderRoll(), LWristYaw(), RElbowRoll(), RElbowYaw(), RShoulderPitch(), RShoulderRoll(), and RWristYaw().
operator==() [2/2]
bool guWhiteboard::SENSORSArmJointSensors::operator== (const wb_sensors_armjointsensors & t_other) const inline
Definition at line 162 of file SENSORSArmJointSensors.hpp.
References SENSORSArmJointSensors().
RElbowRoll() [1/2]
float & guWhiteboard::SENSORSArmJointSensors::RElbowRoll () inline
Definition at line 262 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::RElbowRoll.
Referenced by SENSORSArmJointSensors(), description(), operator=(), operator==(), and to_string().
RElbowRoll() [2/2]
const float & guWhiteboard::SENSORSArmJointSensors::RElbowRoll () const inline
Definition at line 267 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::RElbowRoll.
RElbowYaw() [1/2]
float & guWhiteboard::SENSORSArmJointSensors::RElbowYaw () inline
Definition at line 277 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::RElbowYaw.
Referenced by SENSORSArmJointSensors(), description(), operator=(), operator==(), and to_string().
RElbowYaw() [2/2]
const float & guWhiteboard::SENSORSArmJointSensors::RElbowYaw () const inline
Definition at line 282 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::RElbowYaw.
RShoulderPitch() [1/2]
float & guWhiteboard::SENSORSArmJointSensors::RShoulderPitch () inline
Definition at line 232 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::RShoulderPitch.
Referenced by SENSORSArmJointSensors(), description(), operator=(), operator==(), and to_string().
RShoulderPitch() [2/2]
const float & guWhiteboard::SENSORSArmJointSensors::RShoulderPitch () const inline
Definition at line 237 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::RShoulderPitch.
RShoulderRoll() [1/2]
float & guWhiteboard::SENSORSArmJointSensors::RShoulderRoll () inline
Definition at line 247 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::RShoulderRoll.
Referenced by SENSORSArmJointSensors(), description(), operator=(), operator==(), and to_string().
RShoulderRoll() [2/2]
const float & guWhiteboard::SENSORSArmJointSensors::RShoulderRoll () const inline
Definition at line 252 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::RShoulderRoll.
RWristYaw() [1/2]
float & guWhiteboard::SENSORSArmJointSensors::RWristYaw () inline
Definition at line 307 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::RWristYaw.
Referenced by SENSORSArmJointSensors(), description(), operator=(), operator==(), and to_string().
RWristYaw() [2/2]
const float & guWhiteboard::SENSORSArmJointSensors::RWristYaw () const inline
Definition at line 312 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::RWristYaw.
set_LElbowRoll()
void guWhiteboard::SENSORSArmJointSensors::set_LElbowRoll (const float & t_newValue) inline
Definition at line 212 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::LElbowRoll.
Referenced by from_string().
set_LElbowYaw()
void guWhiteboard::SENSORSArmJointSensors::set_LElbowYaw (const float & t_newValue) inline
Definition at line 227 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::LElbowYaw.
Referenced by from_string().
set_LShoulderPitch()
void guWhiteboard::SENSORSArmJointSensors::set_LShoulderPitch (const float & t_newValue) inline
Definition at line 182 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::LShoulderPitch.
Referenced by from_string().
set_LShoulderRoll()
void guWhiteboard::SENSORSArmJointSensors::set_LShoulderRoll (const float & t_newValue) inline
Definition at line 197 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::LShoulderRoll.
Referenced by from_string().
set_LWristYaw()
void guWhiteboard::SENSORSArmJointSensors::set_LWristYaw (const float & t_newValue) inline
Definition at line 302 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::LWristYaw.
Referenced by from_string().
set_RElbowRoll()
void guWhiteboard::SENSORSArmJointSensors::set_RElbowRoll (const float & t_newValue) inline
Definition at line 272 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::RElbowRoll.
Referenced by from_string().
set_RElbowYaw()
void guWhiteboard::SENSORSArmJointSensors::set_RElbowYaw (const float & t_newValue) inline
Definition at line 287 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::RElbowYaw.
Referenced by from_string().
set_RShoulderPitch()
void guWhiteboard::SENSORSArmJointSensors::set_RShoulderPitch (const float & t_newValue) inline
Definition at line 242 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::RShoulderPitch.
Referenced by from_string().
set_RShoulderRoll()
void guWhiteboard::SENSORSArmJointSensors::set_RShoulderRoll (const float & t_newValue) inline
Definition at line 257 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::RShoulderRoll.
Referenced by from_string().
set_RWristYaw()
void guWhiteboard::SENSORSArmJointSensors::set_RWristYaw (const float & t_newValue) inline
Definition at line 317 of file SENSORSArmJointSensors.hpp.
References wb_sensors_armjointsensors::RWristYaw.
Referenced by from_string().
to_string()
std::string guWhiteboard::SENSORSArmJointSensors::to_string () inline
USE_WB_SENSORS_ARMJOINTSENSORS_C_CONVERSION
Definition at line 362 of file SENSORSArmJointSensors.hpp.
References LElbowRoll(), LElbowYaw(), LShoulderPitch(), LShoulderRoll(), LWristYaw(), RElbowRoll(), RElbowYaw(), RShoulderPitch(), RShoulderRoll(), RWristYaw(), SENSORS_ARMJOINTSENSORS_TO_STRING_BUFFER_SIZE, and wb_sensors_armjointsensors_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/SENSORSArmJointSensors.hpp