gusimplewhiteboard: generic_whiteboard_object< object_type > Class Template Reference
generic_whiteboard_object< object_type > Class Template Reference
This class allows you to set and get data directly into or out of the local whiteboard in shared memory.
#include <gugenericwhiteboardobject.h>
Public Member Functions
generic_whiteboard_object (gu_simple_whiteboard_descriptor *wbd, uint16_t toffs, bool want_atomic=true, bool do_notify_subscribers=true)
designated constructor
generic_whiteboard_object (const generic_whiteboard_object< object_type > &source)
copy constructor
generic_whiteboard_object (const object_type &value, uint16_t toffs, gu_simple_whiteboard_descriptor *wbd=NULLPTR, bool want_atomic=true)
value conversion reference constructor (needs to be overridden by subclasses to set toffs to be useful)
void init (uint16_t toffs, gu_simple_whiteboard_descriptor *wbd=NULLPTR, bool want_atomic=true, bool do_notify_subscribers=true)
intialiser (called from constructors)
void set (const object_type &msg)
designated setter for posting whiteboard messages
object_type get ()
designated getter for getting a whiteboard message
object_type get_from (gu_simple_message *msg)
access method to get data from an existing, low-level message
void post (const object_type &msg)
post method (calls set())
const object_type & operator<< (const object_type &value)
shift left operator (calls set())
generic_whiteboard_object< object_type > & operator>> (object_type &value)
shift right operator (calls get())
const object_type & operator= (const object_type &value)
assignment operator (calls set())
object_type operator= (object_type value)
assignment copy operator (calls set())
operator object_type ()
cast operator (calls get())
object_type operator() ()
empty function operator (calls get())
void operator() (object_type value)
function operator with object_type copy parameter (calls set())
bool hasNewMessage ()
void set (const std::string &msg)
Generic object method for setting data into a specific whiteboard type.
void set (const std::vector< int > &msg)
Generic object method for setting data into a specific whiteboard type.
void set (const std::vector< bool > &msg)
Generic object method for setting data into a specific whiteboard type.
std::string get_from (gu_simple_message *msg)
Generic object method for unwrapping data from the underlying whiteboard storage union.
std::vector< int > get_from (gu_simple_message *msg)
Generic object method for unwrapping data from the underlying whiteboard storage union.
std::vector< bool > get_from (gu_simple_message *msg)
Generic object method for unwrapping data from the underlying whiteboard storage union.
std::string get_from (gu_simple_message *msg)
Generic object method for unwrapping data from the underlying whiteboard storage union.
std::vector< int > get_from (gu_simple_message *msg)
Generic object method for unwrapping data from the underlying whiteboard storage union.
std::vector< bool > get_from (gu_simple_message *msg)
Generic object method for unwrapping data from the underlying whiteboard storage union.
void set (const std::string &msg)
Generic object method for setting data into a specific whiteboard type.
void set (const std::vector< int > &msg)
Generic object method for setting data into a specific whiteboard type.
void set (const std::vector< bool > &msg)
Generic object method for setting data into a specific whiteboard type.
Protected Attributes
gu_simple_whiteboard_descriptor * _wbd
uint16_t type_offset
bool atomic
bool notify_subscribers
uint16_t last_count = 0
bool isFirst = true
Detailed Description
template<class object_type>
class generic_whiteboard_object< object_type >
This class allows you to set and get data directly into or out of the local whiteboard in shared memory.
Examples
Setting the Speech type
Say_t say_ptr;          //get a pointer to the Say type within the whiteboard
std::string str("Howdy World"); //make a string
say_ptr.set(str);           //set the string value into the Say type (and onto the whiteboard)
Nice overloads
Say_t say("Howdy World");       //create the Say variable and set it to a string value in one statement. This has posted the string to the whiteboard.
Getting data back out
std::string str;            //make a string
Say_t say_ptr;          //get a pointer to the Say type within the whiteboard
str = say_ptr.get();        //get the string value out of the whiteboard.
Other types and custom classes work the same way
Walk_ControlStatus w(100, 0, 0, 100);   //create the object
Walk_Command_t w_ptr;           //get a pointer to the Walk type within the whiteboard
w_ptr.set(w);               //set into the whiteboard
//lets get it out again using new variables
Walk_ControlStatus new_w;           //create an empty object
Walk_Command_t new_w_ptr;           //get a pointer to the Walk type within the whiteboard
new_w = new_w_ptr.get()         //get from whiteboard
//why not print it too
std::string new_s = new_w.description();    //get a pretty printed string of the content
fprintf(stdout, "%s", const_cast<char *>(new_s.c_str())); //print the content
Definition at line 78 of file gugenericwhiteboardobject.h.
Constructor & Destructor Documentation
generic_whiteboard_object() [1/3]
template<class object_type > generic_whiteboard_object< object_type >::generic_whiteboard_object (gu_simple_whiteboard_descriptor * wbd, uint16_t toffs, bool want_atomic = true, bool do_notify_subscribers = true) inline
designated constructor
Definition at line 92 of file gugenericwhiteboardobject.h.
References generic_whiteboard_object< object_type >::init().
generic_whiteboard_object() [2/3]
template<class object_type > generic_whiteboard_object< object_type >::generic_whiteboard_object (const generic_whiteboard_object< object_type > & source) inline
copy constructor
Definition at line 100 of file gugenericwhiteboardobject.h.
References generic_whiteboard_object< object_type >::_wbd, generic_whiteboard_object< object_type >::atomic, generic_whiteboard_object< object_type >::init(), generic_whiteboard_object< object_type >::notify_subscribers, and generic_whiteboard_object< object_type >::type_offset.
generic_whiteboard_object() [3/3]
template<class object_type > generic_whiteboard_object< object_type >::generic_whiteboard_object (const object_type & value, uint16_t toffs, gu_simple_whiteboard_descriptor * wbd = NULLPTR, bool want_atomic = true) inline
value conversion reference constructor (needs to be overridden by subclasses to set toffs to be useful)
Definition at line 108 of file gugenericwhiteboardobject.h.
References generic_whiteboard_object< object_type >::init(), and generic_whiteboard_object< object_type >::set().
Member Function Documentation
get()
template<class object_type > object_type generic_whiteboard_object< object_type >::get () inline
designated getter for getting a whiteboard message
Definition at line 137 of file gugenericwhiteboardobject.h.
References generic_whiteboard_object< object_type >::_wbd, generic_whiteboard_object< object_type >::get_from(), gsw_current_message(), generic_whiteboard_object< object_type >::type_offset, and gsw_whiteboard_s::wb.
Referenced by guWhiteboard::getmsg(), generic_whiteboard_object< object_type >::operator object_type(), generic_whiteboard_object< object_type >::operator()(), generic_whiteboard_object< object_type >::operator>>(), and guWhiteboard::postmsg().
get_from() [1/7]
std::string generic_whiteboard_object< std::string >::get_from (gu_simple_message * msg)
Generic object method for unwrapping data from the underlying whiteboard storage union.
string specialisation
Parameters
msg The union pointer
Returns
The unwrapped data in the template type
Definition at line 97 of file gugenericwhiteboardobject.cpp.
References gsw_simple_message::string.
get_from() [2/7]
std::vector< int > generic_whiteboard_object< std::vector< int > >::get_from (gu_simple_message * msg)
Generic object method for unwrapping data from the underlying whiteboard storage union.
vector<int> specialisation
Parameters
msg The union pointer
Returns
The unwrapped data in the template type
Definition at line 108 of file gugenericwhiteboardobject.cpp.
References gsw_simple_message::ivec.
get_from() [3/7]
std::vector< bool > generic_whiteboard_object< std::vector< bool > >::get_from (gu_simple_message * msg)
Generic object method for unwrapping data from the underlying whiteboard storage union.
vector<bool> specialisation
Parameters
msg The union pointer
Returns
The unwrapped data in the template type
Definition at line 119 of file gugenericwhiteboardobject.cpp.
References gsw_simple_message::bvec.
get_from() [4/7]
template<typename object_type > object_type generic_whiteboard_object< object_type >::get_from (gu_simple_message * msg)
access method to get data from an existing, low-level message
Generic object method for unwrapping data from the underlying whiteboard storage union.
Parameters
msg The union pointer
Returns
The unwrapped data in the template type
Definition at line 255 of file gugenericwhiteboardobject.h.
Referenced by wb_reserved_SubscribeToAllTypes_WBFunctor< wb_reserved_SubscribeToAllTypes_WBFunctor_T >::call(), Print_WBFunctor< Print_WBFunctor_T >::call(), Say_WBFunctor< Say_WBFunctor_T >::call(), Speech_WBFunctor< Speech_WBFunctor_T >::call(), QSay_WBFunctor< QSay_WBFunctor_T >::call(), QSpeech_WBFunctor< QSpeech_WBFunctor_T >::call(), SpeechOutput_WBFunctor< SpeechOutput_WBFunctor_T >::call(), SoloTypeExample_WBFunctor< SoloTypeExample_WBFunctor_T >::call(), PlayerNumber_WBFunctor< PlayerNumber_WBFunctor_T >::call(), ManuallyPenalized_WBFunctor< ManuallyPenalized_WBFunctor_T >::call(), PF_ControlStatus_Modes_WBFunctor< PF_ControlStatus_Modes_WBFunctor_T >::call(), TeleoperationConnection_WBFunctor< TeleoperationConnection_WBFunctor_T >::call(), UDPWBNumber_WBFunctor< UDPWBNumber_WBFunctor_T >::call(), VisionFace_WBFunctor< VisionFace_WBFunctor_T >::call(), Draw_WBFunctor< Draw_WBFunctor_T >::call(), REMOVED3_WBFunctor< REMOVED3_WBFunctor_T >::call(), REMOVED4_WBFunctor< REMOVED4_WBFunctor_T >::call(), CBall_WBFunctor< CBall_WBFunctor_T >::call(), GreenEWon_WBFunctor< GreenEWon_WBFunctor_T >::call(), WarnEW_WBFunctor< WarnEW_WBFunctor_T >::call(), TimeGTthirty_WBFunctor< TimeGTthirty_WBFunctor_T >::call(), AmberEWon_WBFunctor< AmberEWon_WBFunctor_T >::call(), TurnRedEW_WBFunctor< TurnRedEW_WBFunctor_T >::call(), TimeGTfive_WBFunctor< TimeGTfive_WBFunctor_T >::call(), RedEWon_WBFunctor< RedEWon_WBFunctor_T >::call(), GreenNSon_WBFunctor< GreenNSon_WBFunctor_T >::call(), WarnNS_WBFunctor< WarnNS_WBFunctor_T >::call(), AmberNSon_WBFunctor< AmberNSon_WBFunctor_T >::call(), TurnRedNS_WBFunctor< TurnRedNS_WBFunctor_T >::call(), RedNSon_WBFunctor< RedNSon_WBFunctor_T >::call(), TimerReset_WBFunctor< TimerReset_WBFunctor_T >::call(), SLOT_UNUSED_WBFunctor< SLOT_UNUSED_WBFunctor_T >::call(), CarSensorPressed_WBFunctor< CarSensorPressed_WBFunctor_T >::call(), Ball_Found_WBFunctor< Ball_Found_WBFunctor_T >::call(), Ball_Calibration_File_WBFunctor< Ball_Calibration_File_WBFunctor_T >::call(), Ball_Calibration_Num_WBFunctor< Ball_Calibration_Num_WBFunctor_T >::call(), Ball_Color_Num_WBFunctor< Ball_Color_Num_WBFunctor_T >::call(), WhistleBlown_WBFunctor< WhistleBlown_WBFunctor_T >::call(), VolumeControl_WBFunctor< VolumeControl_WBFunctor_T >::call(), ParticleOutputMap_WBFunctor< ParticleOutputMap_WBFunctor_T >::call(), ParticleOutputMapControl_WBFunctor< ParticleOutputMapControl_WBFunctor_T >::call(), FFTControl_WBFunctor< FFTControl_WBFunctor_T >::call(), WavLoad_WBFunctor< WavLoad_WBFunctor_T >::call(), WavPlay_WBFunctor< WavPlay_WBFunctor_T >::call(), ReproduceWavNotSilent_WBFunctor< ReproduceWavNotSilent_WBFunctor_T >::call(), buttonPushed_WBFunctor< buttonPushed_WBFunctor_T >::call(), doorOpen_WBFunctor< doorOpen_WBFunctor_T >::call(), timeLeft_WBFunctor< timeLeft_WBFunctor_T >::call(), motor_WBFunctor< motor_WBFunctor_T >::call(), sound_WBFunctor< sound_WBFunctor_T >::call(), light_WBFunctor< light_WBFunctor_T >::call(), Arduino2Pin_WBFunctor< Arduino2Pin_WBFunctor_T >::call(), Arduino2PinValue_WBFunctor< Arduino2PinValue_WBFunctor_T >::call(), Arduino3Pin_WBFunctor< Arduino3Pin_WBFunctor_T >::call(), Arduino3PinValue_WBFunctor< Arduino3PinValue_WBFunctor_T >::call(), Arduino4Pin_WBFunctor< Arduino4Pin_WBFunctor_T >::call(), Arduino4PinValue_WBFunctor< Arduino4PinValue_WBFunctor_T >::call(), Arduino5Pin_WBFunctor< Arduino5Pin_WBFunctor_T >::call(), Arduino5PinValue_WBFunctor< Arduino5PinValue_WBFunctor_T >::call(), Arduino6Pin_WBFunctor< Arduino6Pin_WBFunctor_T >::call(), Arduino6PinValue_WBFunctor< Arduino6PinValue_WBFunctor_T >::call(), Arduino7Pin_WBFunctor< Arduino7Pin_WBFunctor_T >::call(), Arduino7PinValue_WBFunctor< Arduino7PinValue_WBFunctor_T >::call(), Arduino8Pin_WBFunctor< Arduino8Pin_WBFunctor_T >::call(), Arduino8PinValue_WBFunctor< Arduino8PinValue_WBFunctor_T >::call(), Arduino9Pin_WBFunctor< Arduino9Pin_WBFunctor_T >::call(), Arduino9PinValue_WBFunctor< Arduino9PinValue_WBFunctor_T >::call(), LHandGripper_WBFunctor< LHandGripper_WBFunctor_T >::call(), RHandGripper_WBFunctor< RHandGripper_WBFunctor_T >::call(), generic_whiteboard_object< object_type >::get(), guWhiteboard::getmsg(), and SimpleWhiteboardTest::setUp.
get_from() [5/7]
std::string generic_whiteboard_object< std::string >::get_from (gu_simple_message * msg)
Generic object method for unwrapping data from the underlying whiteboard storage union.
string specialisation
Parameters
msg The union pointer
Returns
The unwrapped data in the template type
get_from() [6/7]
std::vector< int > generic_whiteboard_object< std::vector< int > >::get_from (gu_simple_message * msg)
Generic object method for unwrapping data from the underlying whiteboard storage union.
vector<int> specialisation
Parameters
msg The union pointer
Returns
The unwrapped data in the template type
get_from() [7/7]
std::vector< bool > generic_whiteboard_object< std::vector< bool > >::get_from (gu_simple_message * msg)
Generic object method for unwrapping data from the underlying whiteboard storage union.
vector<bool> specialisation
Parameters
msg The union pointer
Returns
The unwrapped data in the template type
hasNewMessage()
template<class object_type > bool generic_whiteboard_object< object_type >::hasNewMessage () inline
Definition at line 217 of file gugenericwhiteboardobject.h.
References gsw_simple_whiteboard_s::event_counters, generic_whiteboard_object< object_type >::last_count, generic_whiteboard_object< object_type >::type_offset, u_int16_t, and gsw_whiteboard_s::wb.
init()
template<class object_type > void generic_whiteboard_object< object_type >::init (uint16_t toffs, gu_simple_whiteboard_descriptor * wbd = NULLPTR, bool want_atomic = true, bool do_notify_subscribers = true) inline
intialiser (called from constructors)
Definition at line 117 of file gugenericwhiteboardobject.h.
References generic_whiteboard_object< object_type >::_wbd, generic_whiteboard_object< object_type >::atomic, get_local_singleton_whiteboard(), generic_whiteboard_object< object_type >::notify_subscribers, and generic_whiteboard_object< object_type >::type_offset.
Referenced by generic_whiteboard_object< object_type >::generic_whiteboard_object(), and wb_generic_whiteboard_object< object_type >::init().
operator object_type()
template<class object_type > generic_whiteboard_object< object_type >::operator object_type () inline
cast operator (calls get())
Definition at line 196 of file gugenericwhiteboardobject.h.
References generic_whiteboard_object< object_type >::get().
operator()() [1/2]
template<class object_type > object_type generic_whiteboard_object< object_type >::operator() () inline
empty function operator (calls get())
Definition at line 204 of file gugenericwhiteboardobject.h.
References generic_whiteboard_object< object_type >::get().
operator()() [2/2]
template<class object_type > void generic_whiteboard_object< object_type >::operator() (object_type value) inline
function operator with object_type copy parameter (calls set())
Definition at line 212 of file gugenericwhiteboardobject.h.
References generic_whiteboard_object< object_type >::set().
operator<<()
template<class object_type > const object_type & generic_whiteboard_object< object_type >::operator<< (const object_type & value) inline
shift left operator (calls set())
Definition at line 156 of file gugenericwhiteboardobject.h.
References generic_whiteboard_object< object_type >::set().
operator=() [1/2]
template<class object_type > const object_type & generic_whiteboard_object< object_type >::operator= (const object_type & value) inline
assignment operator (calls set())
Definition at line 176 of file gugenericwhiteboardobject.h.
References generic_whiteboard_object< object_type >::set().
operator=() [2/2]
template<class object_type > object_type generic_whiteboard_object< object_type >::operator= (object_type value) inline
assignment copy operator (calls set())
Definition at line 186 of file gugenericwhiteboardobject.h.
References generic_whiteboard_object< object_type >::set().
operator>>()
template<class object_type > generic_whiteboard_object< object_type > & generic_whiteboard_object< object_type >::operator>> (object_type & value) inline
shift right operator (calls get())
Definition at line 166 of file gugenericwhiteboardobject.h.
References generic_whiteboard_object< object_type >::get().
post()
template<class object_type > void generic_whiteboard_object< object_type >::post (const object_type & msg) inline
post method (calls set())
Definition at line 151 of file gugenericwhiteboardobject.h.
References generic_whiteboard_object< object_type >::set().
Referenced by guWhiteboard::postmsg().
set() [1/7]
template<class object_type > void generic_whiteboard_object< object_type >::set (const object_type & msg)
designated setter for posting whiteboard messages
Generic object method for setting data into a specific whiteboard type.
Parameters
msg The data to set into the whiteboard
Definition at line 281 of file gugenericwhiteboardobject.h.
References gsw_increment(), gsw_increment_event_counter(), gsw_next_message(), gsw_procure(), GSW_SEM_PUTMSG, gsw_signal_subscribers(), gsw_vacate(), GU_SIMPLE_WHITEBOARD_BUFSIZE, and gsw_simple_whiteboard_s::subscribed.
Referenced by generic_whiteboard_object< object_type >::generic_whiteboard_object(), wb_generic_whiteboard_object< object_type >::wb_generic_whiteboard_object(), generic_whiteboard_object< object_type >::operator()(), generic_whiteboard_object< object_type >::operator<<(), generic_whiteboard_object< object_type >::operator=(), and generic_whiteboard_object< object_type >::post().
set() [2/7]
void generic_whiteboard_object< std::string >::set (const std::string & msg)
Generic object method for setting data into a specific whiteboard type.
string specialisation
Parameters
msg The data to set into the whiteboard
Definition at line 17 of file gugenericwhiteboardobject.cpp.
References gsw_increment(), gsw_increment_event_counter(), gsw_next_message(), gsw_procure(), GSW_SEM_PUTMSG, gsw_signal_subscribers(), gsw_vacate(), GU_SIMPLE_WHITEBOARD_BUFSIZE, gsw_simple_message::string, and gsw_simple_whiteboard_s::subscribed.
set() [3/7]
void generic_whiteboard_object< std::string >::set (const std::string & msg)
Generic object method for setting data into a specific whiteboard type.
string specialisation
Parameters
msg The data to set into the whiteboard
set() [4/7]
void generic_whiteboard_object< std::vector< bool > >::set (const std::vector< bool > & msg)
Generic object method for setting data into a specific whiteboard type.
vector<bool> specialisation
Parameters
msg The data to set into the whiteboard
Definition at line 67 of file gugenericwhiteboardobject.cpp.
References gsw_simple_message::bvec, gsw_increment(), gsw_increment_event_counter(), gsw_next_message(), gsw_procure(), GSW_SEM_PUTMSG, gsw_signal_subscribers(), gsw_vacate(), GU_SIMPLE_WHITEBOARD_BUFSIZE, and gsw_simple_whiteboard_s::subscribed.
set() [5/7]
void generic_whiteboard_object< std::vector< bool > >::set (const std::vector< bool > & msg)
Generic object method for setting data into a specific whiteboard type.
vector<bool> specialisation
Parameters
msg The data to set into the whiteboard
set() [6/7]
void generic_whiteboard_object< std::vector< int > >::set (const std::vector< int > & msg)
Generic object method for setting data into a specific whiteboard type.
vector<int> specialisation
Parameters
msg The data to set into the whiteboard
Definition at line 42 of file gugenericwhiteboardobject.cpp.
References gsw_increment(), gsw_increment_event_counter(), gsw_next_message(), gsw_procure(), GSW_SEM_PUTMSG, gsw_signal_subscribers(), gsw_vacate(), GU_SIMPLE_WHITEBOARD_BUFSIZE, gsw_simple_message::ivec, and gsw_simple_whiteboard_s::subscribed.
set() [7/7]
void generic_whiteboard_object< std::vector< int > >::set (const std::vector< int > & msg)
Generic object method for setting data into a specific whiteboard type.
vector<int> specialisation
Parameters
msg The data to set into the whiteboard
Member Data Documentation
_wbd
template<class object_type > gu_simple_whiteboard_descriptor* generic_whiteboard_object< object_type >::_wbd protected
Definition at line 81 of file gugenericwhiteboardobject.h.
Referenced by generic_whiteboard_object< object_type >::generic_whiteboard_object(), guWhiteboard::wb_reserved_SubscribeToAllTypes_t::eventCounter(), guWhiteboard::Print_t::eventCounter(), guWhiteboard::Say_t::eventCounter(), guWhiteboard::Speech_t::eventCounter(), guWhiteboard::QSay_t::eventCounter(), guWhiteboard::QSpeech_t::eventCounter(), guWhiteboard::SpeechOutput_t::eventCounter(), guWhiteboard::GCGameState_t::eventCounter(), guWhiteboard::SensorsHandSensors_t::eventCounter(), guWhiteboard::SensorsHeadSensors_t::eventCounter(), guWhiteboard::MOTION_Commands_t::eventCounter(), guWhiteboard::MOTION_Status_t::eventCounter(), guWhiteboard::HAL_HeadTarget_t::eventCounter(), guWhiteboard::SensorsFootSensors_t::eventCounter(), guWhiteboard::SensorsBodySensors_t::eventCounter(), guWhiteboard::SENSORSLedsSensors_t::eventCounter(), guWhiteboard::SENSORSLegJointTemps_t::eventCounter(), guWhiteboard::SENSORSTorsoJointTemps_t::eventCounter(), guWhiteboard::SENSORSLegJointSensors_t::eventCounter(), guWhiteboard::SENSORSTorsoJointSensors_t::eventCounter(), guWhiteboard::SENSORSSonarSensors_t::eventCounter(), guWhiteboard::FSM_Control_t::eventCounter(), guWhiteboard::FSM_Status_t::eventCounter(), guWhiteboard::FSM_Names_t::eventCounter(), guWhiteboard::SoloTypeExample_t::eventCounter(), guWhiteboard::FilteredGoalSighting_t::eventCounter(), guWhiteboard::NAO_State_t::eventCounter(), guWhiteboard::UDPRN_t::eventCounter(), guWhiteboard::PlayerNumber_t::eventCounter(), guWhiteboard::ManuallyPenalized_t::eventCounter(), guWhiteboard::VisionControl_t::eventCounter(), guWhiteboard::VisionStatus_t::eventCounter(), guWhiteboard::FFTStatus_t::eventCounter(), guWhiteboard::FSOsighting_t::eventCounter(), guWhiteboard::TopParticles_t::eventCounter(), guWhiteboard::FilteredBallSighting_t::eventCounter(), guWhiteboard::PF_ControlStatus_Modes_t::eventCounter(), guWhiteboard::WEBOTS_NXT_bridge_t::eventCounter(), guWhiteboard::WEBOTS_NXT_encoders_t::eventCounter(), guWhiteboard::WEBOTS_NXT_camera_t::eventCounter(), guWhiteboard::WEBOTS_NXT_walk_isRunning_t::eventCounter(), guWhiteboard::WEBOTS_NXT_deadReakoning_walk_t::eventCounter(), guWhiteboard::WEBOTS_NXT_colorLine_walk_t::eventCounter(), guWhiteboard::WEBOTS_NXT_gridMotions_t::eventCounter(), guWhiteboard::VisionBall_t::eventCounter(), guWhiteboard::VisionGoals_t::eventCounter(), guWhiteboard::WalkData_t::eventCounter(), guWhiteboard::TeleoperationControlStatus_t::eventCounter(), guWhiteboard::TeleoperationConnection_t::eventCounter(), guWhiteboard::UDPWBNumber_t::eventCounter(), guWhiteboard::WEBOTS_NXT_bumper_t::eventCounter(), guWhiteboard::WEBOTS_NXT_vector_bridge_t::eventCounter(), guWhiteboard::TopVisionLines_t::eventCounter(), guWhiteboard::BottomVisionLines_t::eventCounter(), guWhiteboard::DifferentialRobotStatus_t::eventCounter(), guWhiteboard::DifferentialRobotControl_t::eventCounter(), guWhiteboard::XEyesPos_t::eventCounter(), guWhiteboard::VisionFace_t::eventCounter(), guWhiteboard::Draw_t::eventCounter(), guWhiteboard::FSM_States_t::eventCounter(), guWhiteboard::Giraff_Interface_Status_t::eventCounter(), guWhiteboard::Giraff_Interface_Command_t::eventCounter(), guWhiteboard::NXT_Status_t::eventCounter(), guWhiteboard::NXT_Command_t::eventCounter(), guWhiteboard::APM_Status_t::eventCounter(), guWhiteboard::APM_Command_t::eventCounter(), guWhiteboard::REMOVED3_t::eventCounter(), guWhiteboard::REMOVED4_t::eventCounter(), guWhiteboard::CBall_t::eventCounter(), guWhiteboard::OculusPrime_Command_t::eventCounter(), guWhiteboard::Input3D_t::eventCounter(), guWhiteboard::Oculus_Prime_Command_t::eventCounter(), guWhiteboard::IOPins_t::eventCounter(), guWhiteboard::NXT_Two_Touch_Status_t::eventCounter(), guWhiteboard::NXT_Sound_Control_t::eventCounter(), guWhiteboard::NXT_Lights_Control_t::eventCounter(), guWhiteboard::Clocks_t::eventCounter(), guWhiteboard::Channels_t::eventCounter(), guWhiteboard::SwitchSubsumption_t::eventCounter(), guWhiteboard::TotoDoingMotion_t::eventCounter(), guWhiteboard::Count_t::eventCounter(), guWhiteboard::GreenEWon_t::eventCounter(), guWhiteboard::WarnEW_t::eventCounter(), guWhiteboard::TimeGTthirty_t::eventCounter(), guWhiteboard::AmberEWon_t::eventCounter(), guWhiteboard::TurnRedEW_t::eventCounter(), guWhiteboard::TimeGTfive_t::eventCounter(), guWhiteboard::RedEWon_t::eventCounter(), guWhiteboard::GreenNSon_t::eventCounter(), guWhiteboard::WarnNS_t::eventCounter(), guWhiteboard::AmberNSon_t::eventCounter(), guWhiteboard::TurnRedNS_t::eventCounter(), guWhiteboard::RedNSon_t::eventCounter(), guWhiteboard::TimerReset_t::eventCounter(), guWhiteboard::SLOT_UNUSED_t::eventCounter(), guWhiteboard::CarSensorPressed_t::eventCounter(), guWhiteboard::SwitchSubsumptionTrafficLights_t::eventCounter(), guWhiteboard::Ball_Found_t::eventCounter(), guWhiteboard::Ball_Calibration_File_t::eventCounter(), guWhiteboard::Ball_Calibration_Num_t::eventCounter(), guWhiteboard::Ball_Color_Num_t::eventCounter(), guWhiteboard::HAL_LArmTarget_Ctrl_t::eventCounter(), guWhiteboard::HAL_LArmTarget_Stat_t::eventCounter(), guWhiteboard::HAL_LArmTarget_Tolr_t::eventCounter(), guWhiteboard::HAL_RArmTarget_Ctrl_t::eventCounter(), guWhiteboard::HAL_RArmTarget_Stat_t::eventCounter(), guWhiteboard::HAL_RArmTarget_Tolr_t::eventCounter(), guWhiteboard::VisionFieldFeatures_t::eventCounter(), guWhiteboard::WhistleBlown_t::eventCounter(), guWhiteboard::VolumeControl_t::eventCounter(), guWhiteboard::VisionRobots_t::eventCounter(), guWhiteboard::VisionDetectionHorizons_t::eventCounter(), guWhiteboard::NaoWalkCommand_t::eventCounter(), guWhiteboard::NaoWalkStatus_t::eventCounter(), guWhiteboard::HAL_LLegTarget_Ctrl_t::eventCounter(), guWhiteboard::HAL_LLegTarget_Stat_t::eventCounter(), guWhiteboard::HAL_LLegTarget_Tolr_t::eventCounter(), guWhiteboard::HAL_RLegTarget_Ctrl_t::eventCounter(), guWhiteboard::HAL_RLegTarget_Stat_t::eventCounter(), guWhiteboard::HAL_RLegTarget_Tolr_t::eventCounter(), guWhiteboard::VisionDetectionGoals_t::eventCounter(), guWhiteboard::TeleoperationControl_t::eventCounter(), guWhiteboard::TeleoperationStatus_t::eventCounter(), guWhiteboard::VisionDetectionBalls_t::eventCounter(), guWhiteboard::TeleoperationControlVR_t::eventCounter(), guWhiteboard::ParticleOutputMap_t::eventCounter(), guWhiteboard::ParticleOutputMapControl_t::eventCounter(), guWhiteboard::FFTControl_t::eventCounter(), guWhiteboard::MachineFilteredNaoVision_t::eventCounter(), guWhiteboard::MicrowaveStatus_t::eventCounter(), guWhiteboard::Buttons_t::eventCounter(), guWhiteboard::MachineFilteredLocalisationVision_t::eventCounter(), guWhiteboard::SensorsJointCurrent_t::eventCounter(), guWhiteboard::DataLogger_t::eventCounter(), guWhiteboard::MachineFilteredLines_t::eventCounter(), guWhiteboard::BallLocation_t::eventCounter(), guWhiteboard::LeftGoalPostLocation_t::eventCounter(), guWhiteboard::RightGoalPostLocation_t::eventCounter(), guWhiteboard::GoalLocation_t::eventCounter(), guWhiteboard::NaoSonarProtectedWalkCommand_t::eventCounter(), guWhiteboard::NaoObstacleDirection_t::eventCounter(), guWhiteboard::DominantFrequencies_t::eventCounter(), guWhiteboard::MissionPriorityForObstacles_t::eventCounter(), guWhiteboard::WavLoad_t::eventCounter(), guWhiteboard::WavPlay_t::eventCounter(), guWhiteboard::ReproduceWavNotSilent_t::eventCounter(), guWhiteboard::FrequencyControl_t::eventCounter(), guWhiteboard::FrequencyStatus_t::eventCounter(), guWhiteboard::HeadJointSensors_t::eventCounter(), guWhiteboard::AdjustPositionConfidence_t::eventCounter(), guWhiteboard::GuVrTeleopVulkanControl_t::eventCounter(), guWhiteboard::TemperatureSensors_t::eventCounter(), guWhiteboard::Overheating_t::eventCounter(), guWhiteboard::buttonPushed_t::eventCounter(), guWhiteboard::doorOpen_t::eventCounter(), guWhiteboard::timeLeft_t::eventCounter(), guWhiteboard::motor_t::eventCounter(), guWhiteboard::sound_t::eventCounter(), guWhiteboard::light_t::eventCounter(), guWhiteboard::Arduino2Pin_t::eventCounter(), guWhiteboard::Arduino2PinValue_t::eventCounter(), guWhiteboard::Arduino3Pin_t::eventCounter(), guWhiteboard::Arduino3PinValue_t::eventCounter(), guWhiteboard::Arduino4Pin_t::eventCounter(), guWhiteboard::Arduino4PinValue_t::eventCounter(), guWhiteboard::Arduino5Pin_t::eventCounter(), guWhiteboard::Arduino5PinValue_t::eventCounter(), guWhiteboard::Arduino6Pin_t::eventCounter(), guWhiteboard::Arduino6PinValue_t::eventCounter(), guWhiteboard::Arduino7Pin_t::eventCounter(), guWhiteboard::Arduino7PinValue_t::eventCounter(), guWhiteboard::Arduino8Pin_t::eventCounter(), guWhiteboard::Arduino8PinValue_t::eventCounter(), guWhiteboard::Arduino9Pin_t::eventCounter(), guWhiteboard::Arduino9PinValue_t::eventCounter(), guWhiteboard::BallPosition_t::eventCounter(), guWhiteboard::MemoryImageControl_t::eventCounter(), guWhiteboard::MemoryImageStatus_t::eventCounter(), guWhiteboard::LHandGripper_t::eventCounter(), guWhiteboard::RHandGripper_t::eventCounter(), guWhiteboard::MyPosition_t::eventCounter(), guWhiteboard::VisionDetectionLines_t::eventCounter(), guWhiteboard::VisionDetectionFeatures_t::eventCounter(), generic_whiteboard_object< object_type >::get(), and generic_whiteboard_object< object_type >::init().
atomic
template<class object_type > bool generic_whiteboard_object< object_type >::atomic protected
Definition at line 83 of file gugenericwhiteboardobject.h.
Referenced by generic_whiteboard_object< object_type >::generic_whiteboard_object(), and generic_whiteboard_object< object_type >::init().
isFirst
template<class object_type > bool generic_whiteboard_object< object_type >::isFirst = true protected
Definition at line 86 of file gugenericwhiteboardobject.h.
last_count
template<class object_type > uint16_t generic_whiteboard_object< object_type >::last_count = 0 protected
Definition at line 85 of file gugenericwhiteboardobject.h.
Referenced by generic_whiteboard_object< object_type >::hasNewMessage().
notify_subscribers
template<class object_type > bool generic_whiteboard_object< object_type >::notify_subscribers protected
Definition at line 84 of file gugenericwhiteboardobject.h.
Referenced by generic_whiteboard_object< object_type >::generic_whiteboard_object(), and generic_whiteboard_object< object_type >::init().
type_offset
template<class object_type > uint16_t generic_whiteboard_object< object_type >::type_offset protected
Definition at line 82 of file gugenericwhiteboardobject.h.
Referenced by generic_whiteboard_object< object_type >::generic_whiteboard_object(), generic_whiteboard_object< object_type >::get(), generic_whiteboard_object< object_type >::hasNewMessage(), and generic_whiteboard_object< object_type >::init().
The documentation for this class was generated from the following file:
gugenericwhiteboardobject.h