gusimplewhiteboard: guWhiteboard::SENSORSHeadJointSensors Class Reference
guWhiteboard::SENSORSHeadJointSensors Class Reference
Provides a C++ wrapper around wb_sensors_headjointsensors.
#include <SENSORSHeadJointSensors.hpp>
Public Member Functions
SENSORSHeadJointSensors (float t_HeadYaw=0.0f, float t_HeadPitch=0.0f)
Create a new SENSORSHeadJointSensors.
SENSORSHeadJointSensors (const SENSORSHeadJointSensors &t_other)
Copy Constructor.
SENSORSHeadJointSensors (const struct wb_sensors_headjointsensors &t_other)
Copy Constructor.
SENSORSHeadJointSensors & operator= (const SENSORSHeadJointSensors &t_other)
Copy Assignment Operator.
SENSORSHeadJointSensors & operator= (const struct wb_sensors_headjointsensors &t_other)
Copy Assignment Operator.
bool operator== (const SENSORSHeadJointSensors &t_other) const
bool operator!= (const SENSORSHeadJointSensors &t_other) const
bool operator== (const wb_sensors_headjointsensors &t_other) const
bool operator!= (const wb_sensors_headjointsensors &t_other) const
float & HeadYaw ()
const float & HeadYaw () const
void set_HeadYaw (const float &t_newValue)
float & HeadPitch ()
const float & HeadPitch () const
void set_HeadPitch (const float &t_newValue)
SENSORSHeadJointSensors (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_sensors_headjointsensors
float HeadYaw
Head pos in RAD.
float HeadPitch
Head pos in RAD.
Detailed Description
Provides a C++ wrapper around wb_sensors_headjointsensors.
Definition at line 84 of file SENSORSHeadJointSensors.hpp.
Constructor & Destructor Documentation
SENSORSHeadJointSensors() [1/4]
guWhiteboard::SENSORSHeadJointSensors::SENSORSHeadJointSensors (float t_HeadYaw = 0.0f, float t_HeadPitch = 0.0f) inline
Create a new SENSORSHeadJointSensors.
Definition at line 101 of file SENSORSHeadJointSensors.hpp.
Referenced by operator==().
SENSORSHeadJointSensors() [2/4]
guWhiteboard::SENSORSHeadJointSensors::SENSORSHeadJointSensors (const SENSORSHeadJointSensors & t_other) inline
Copy Constructor.
Definition at line 108 of file SENSORSHeadJointSensors.hpp.
References HeadPitch(), and HeadYaw().
SENSORSHeadJointSensors() [3/4]
guWhiteboard::SENSORSHeadJointSensors::SENSORSHeadJointSensors (const struct wb_sensors_headjointsensors & t_other) inline
Copy Constructor.
Definition at line 115 of file SENSORSHeadJointSensors.hpp.
References wb_sensors_headjointsensors::HeadPitch, and wb_sensors_headjointsensors::HeadYaw.
SENSORSHeadJointSensors() [4/4]
guWhiteboard::SENSORSHeadJointSensors::SENSORSHeadJointSensors (const std::string & t_str) inline
String Constructor.
Definition at line 190 of file SENSORSHeadJointSensors.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::SENSORSHeadJointSensors::description () inline
USE_WB_SENSORS_HEADJOINTSENSORS_C_CONVERSION
Definition at line 195 of file SENSORSHeadJointSensors.hpp.
References HeadPitch(), HeadYaw(), SENSORS_HEADJOINTSENSORS_DESC_BUFFER_SIZE, and wb_sensors_headjointsensors_description().
from_string()
void guWhiteboard::SENSORSHeadJointSensors::from_string (const std::string & t_str) inline
USE_WB_SENSORS_HEADJOINTSENSORS_C_CONVERSION
Definition at line 229 of file SENSORSHeadJointSensors.hpp.
References SENSORS_HEADJOINTSENSORS_DESC_BUFFER_SIZE, set_HeadPitch(), and set_HeadYaw().
Referenced by SENSORSHeadJointSensors().
HeadPitch() [1/2]
float & guWhiteboard::SENSORSHeadJointSensors::HeadPitch () inline
Definition at line 171 of file SENSORSHeadJointSensors.hpp.
References wb_sensors_headjointsensors::HeadPitch.
Referenced by SENSORSHeadJointSensors(), description(), operator=(), operator==(), and to_string().
HeadPitch() [2/2]
const float & guWhiteboard::SENSORSHeadJointSensors::HeadPitch () const inline
Definition at line 176 of file SENSORSHeadJointSensors.hpp.
References wb_sensors_headjointsensors::HeadPitch.
HeadYaw() [1/2]
float & guWhiteboard::SENSORSHeadJointSensors::HeadYaw () inline
Definition at line 156 of file SENSORSHeadJointSensors.hpp.
References wb_sensors_headjointsensors::HeadYaw.
Referenced by SENSORSHeadJointSensors(), description(), operator=(), operator==(), and to_string().
HeadYaw() [2/2]
const float & guWhiteboard::SENSORSHeadJointSensors::HeadYaw () const inline
Definition at line 161 of file SENSORSHeadJointSensors.hpp.
References wb_sensors_headjointsensors::HeadYaw.
operator!=() [1/2]
bool guWhiteboard::SENSORSHeadJointSensors::operator!= (const SENSORSHeadJointSensors & t_other) const inline
Definition at line 141 of file SENSORSHeadJointSensors.hpp.
operator!=() [2/2]
bool guWhiteboard::SENSORSHeadJointSensors::operator!= (const wb_sensors_headjointsensors & t_other) const inline
Definition at line 151 of file SENSORSHeadJointSensors.hpp.
operator=() [1/2]
SENSORSHeadJointSensors & guWhiteboard::SENSORSHeadJointSensors::operator= (const SENSORSHeadJointSensors & t_other) inline
Copy Assignment Operator.
Definition at line 122 of file SENSORSHeadJointSensors.hpp.
References HeadPitch(), and HeadYaw().
operator=() [2/2]
SENSORSHeadJointSensors & guWhiteboard::SENSORSHeadJointSensors::operator= (const struct wb_sensors_headjointsensors & t_other) inline
Copy Assignment Operator.
Definition at line 130 of file SENSORSHeadJointSensors.hpp.
References wb_sensors_headjointsensors::HeadPitch, and wb_sensors_headjointsensors::HeadYaw.
operator==() [1/2]
bool guWhiteboard::SENSORSHeadJointSensors::operator== (const SENSORSHeadJointSensors & t_other) const inline
Definition at line 135 of file SENSORSHeadJointSensors.hpp.
References HeadPitch(), and HeadYaw().
operator==() [2/2]
bool guWhiteboard::SENSORSHeadJointSensors::operator== (const wb_sensors_headjointsensors & t_other) const inline
Definition at line 146 of file SENSORSHeadJointSensors.hpp.
References SENSORSHeadJointSensors().
set_HeadPitch()
void guWhiteboard::SENSORSHeadJointSensors::set_HeadPitch (const float & t_newValue) inline
Definition at line 181 of file SENSORSHeadJointSensors.hpp.
References wb_sensors_headjointsensors::HeadPitch.
Referenced by from_string().
set_HeadYaw()
void guWhiteboard::SENSORSHeadJointSensors::set_HeadYaw (const float & t_newValue) inline
Definition at line 166 of file SENSORSHeadJointSensors.hpp.
References wb_sensors_headjointsensors::HeadYaw.
Referenced by from_string().
to_string()
std::string guWhiteboard::SENSORSHeadJointSensors::to_string () inline
USE_WB_SENSORS_HEADJOINTSENSORS_C_CONVERSION
Definition at line 210 of file SENSORSHeadJointSensors.hpp.
References HeadPitch(), HeadYaw(), SENSORS_HEADJOINTSENSORS_TO_STRING_BUFFER_SIZE, and wb_sensors_headjointsensors_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/SENSORSHeadJointSensors.hpp