gusimplewhiteboard: guWhiteboard::VisionDetectionHorizons Class Reference
guWhiteboard::VisionDetectionHorizons Class Reference
Provides a C++ wrapper around wb_vision_detection_horizons.
#include <VisionDetectionHorizons.hpp>
Public Member Functions
VisionDetectionHorizons (uint64_t t_frameNumber=0, const struct wb_vision_detection_horizon t_horizons[2]=NULLPTR, uint16_t t_res_width=0, uint16_t t_res_height=0)
Create a new VisionDetectionHorizons.
VisionDetectionHorizons (const VisionDetectionHorizons &t_other)
Copy Constructor.
VisionDetectionHorizons (const struct wb_vision_detection_horizons &t_other)
Copy Constructor.
VisionDetectionHorizons & operator= (const VisionDetectionHorizons &t_other)
Copy Assignment Operator.
VisionDetectionHorizons & operator= (const struct wb_vision_detection_horizons &t_other)
Copy Assignment Operator.
bool operator== (const VisionDetectionHorizons &t_other) const
bool operator!= (const VisionDetectionHorizons &t_other) const
bool operator== (const wb_vision_detection_horizons &t_other) const
bool operator!= (const wb_vision_detection_horizons &t_other) const
uint64_t & frameNumber ()
const uint64_t & frameNumber () const
void set_frameNumber (const uint64_t &t_newValue)
const VisionDetectionHorizon * horizons () const
size_t horizons_size () const
VisionDetectionHorizon & horizons (int t_i)
const VisionDetectionHorizon & horizons (int t_i) const
void set_horizons (const VisionDetectionHorizon *t_newValue)
void set_horizons (const VisionDetectionHorizon &t_newValue, int t_i)
uint16_t & res_width ()
const uint16_t & res_width () const
void set_res_width (const uint16_t &t_newValue)
uint16_t & res_height ()
const uint16_t & res_height () const
void set_res_height (const uint16_t &t_newValue)
VisionDetectionHorizons (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_vision_detection_horizons
uint64_t frameNumber
visionFrameNumber
struct wb_vision_detection_horizon horizons [2]
horizon objects
uint16_t res_width
The resolution width.
uint16_t res_height
The resolution height.
Detailed Description
Provides a C++ wrapper around wb_vision_detection_horizons.
Definition at line 85 of file VisionDetectionHorizons.hpp.
Constructor & Destructor Documentation
VisionDetectionHorizons() [1/4]
guWhiteboard::VisionDetectionHorizons::VisionDetectionHorizons (uint64_t t_frameNumber = 0, const struct wb_vision_detection_horizon t_horizons[2] = NULLPTR, uint16_t t_res_width = 0, uint16_t t_res_height = 0) inline
Create a new VisionDetectionHorizons.
Definition at line 109 of file VisionDetectionHorizons.hpp.
Referenced by operator==().
VisionDetectionHorizons() [2/4]
guWhiteboard::VisionDetectionHorizons::VisionDetectionHorizons (const VisionDetectionHorizons & t_other) inline
Copy Constructor.
Definition at line 116 of file VisionDetectionHorizons.hpp.
References frameNumber(), horizons(), res_height(), and res_width().
VisionDetectionHorizons() [3/4]
guWhiteboard::VisionDetectionHorizons::VisionDetectionHorizons (const struct wb_vision_detection_horizons & t_other) inline
Copy Constructor.
Definition at line 123 of file VisionDetectionHorizons.hpp.
References wb_vision_detection_horizons::frameNumber, wb_vision_detection_horizons::horizons, wb_vision_detection_horizons::res_height, and wb_vision_detection_horizons::res_width.
VisionDetectionHorizons() [4/4]
guWhiteboard::VisionDetectionHorizons::VisionDetectionHorizons (const std::string & t_str) inline
String Constructor.
Definition at line 252 of file VisionDetectionHorizons.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::VisionDetectionHorizons::description () inline
USE_WB_VISION_DETECTION_HORIZONS_C_CONVERSION
Definition at line 257 of file VisionDetectionHorizons.hpp.
References description(), frameNumber(), horizons(), res_height(), res_width(), VISION_DETECTION_HORIZONS_DESC_BUFFER_SIZE, VISION_DETECTION_HORIZONS_HORIZONS_ARRAY_SIZE, and wb_vision_detection_horizons_description().
Referenced by description().
frameNumber() [1/2]
uint64_t & guWhiteboard::VisionDetectionHorizons::frameNumber () inline
Definition at line 173 of file VisionDetectionHorizons.hpp.
References wb_vision_detection_horizons::frameNumber.
Referenced by VisionDetectionHorizons(), description(), operator=(), operator==(), and to_string().
frameNumber() [2/2]
const uint64_t & guWhiteboard::VisionDetectionHorizons::frameNumber () const inline
Definition at line 178 of file VisionDetectionHorizons.hpp.
References wb_vision_detection_horizons::frameNumber.
from_string()
void guWhiteboard::VisionDetectionHorizons::from_string (const std::string & t_str) inline
USE_WB_VISION_DETECTION_HORIZONS_C_CONVERSION
Definition at line 311 of file VisionDetectionHorizons.hpp.
References guWhiteboard::VisionDetectionHorizon::from_string(), set_frameNumber(), set_horizons(), set_res_height(), set_res_width(), VISION_DETECTION_HORIZONS_DESC_BUFFER_SIZE, and VISION_DETECTION_HORIZONS_HORIZONS_ARRAY_SIZE.
Referenced by VisionDetectionHorizons().
horizons() [1/3]
const VisionDetectionHorizon * guWhiteboard::VisionDetectionHorizons::horizons () const inline
Definition at line 188 of file VisionDetectionHorizons.hpp.
References wb_vision_detection_horizons::horizons.
Referenced by VisionDetectionHorizons(), description(), operator=(), operator==(), and to_string().
horizons() [2/3]
VisionDetectionHorizon & guWhiteboard::VisionDetectionHorizons::horizons (int t_i) inline
Definition at line 198 of file VisionDetectionHorizons.hpp.
References wb_vision_detection_horizons::horizons.
horizons() [3/3]
const VisionDetectionHorizon & guWhiteboard::VisionDetectionHorizons::horizons (int t_i) const inline
Definition at line 203 of file VisionDetectionHorizons.hpp.
References wb_vision_detection_horizons::horizons.
horizons_size()
size_t guWhiteboard::VisionDetectionHorizons::horizons_size () const inline
Definition at line 193 of file VisionDetectionHorizons.hpp.
References VISION_DETECTION_HORIZONS_HORIZONS_ARRAY_SIZE.
operator!=() [1/2]
bool guWhiteboard::VisionDetectionHorizons::operator!= (const VisionDetectionHorizons & t_other) const inline
Definition at line 158 of file VisionDetectionHorizons.hpp.
operator!=() [2/2]
bool guWhiteboard::VisionDetectionHorizons::operator!= (const wb_vision_detection_horizons & t_other) const inline
Definition at line 168 of file VisionDetectionHorizons.hpp.
operator=() [1/2]
VisionDetectionHorizons & guWhiteboard::VisionDetectionHorizons::operator= (const struct wb_vision_detection_horizons & t_other) inline
Copy Assignment Operator.
Definition at line 138 of file VisionDetectionHorizons.hpp.
References wb_vision_detection_horizons::frameNumber, wb_vision_detection_horizons::horizons, wb_vision_detection_horizons::res_height, and wb_vision_detection_horizons::res_width.
operator=() [2/2]
VisionDetectionHorizons & guWhiteboard::VisionDetectionHorizons::operator= (const VisionDetectionHorizons & t_other) inline
Copy Assignment Operator.
Definition at line 130 of file VisionDetectionHorizons.hpp.
References frameNumber(), horizons(), res_height(), and res_width().
operator==() [1/2]
bool guWhiteboard::VisionDetectionHorizons::operator== (const VisionDetectionHorizons & t_other) const inline
Definition at line 143 of file VisionDetectionHorizons.hpp.
References frameNumber(), horizons(), res_height(), and res_width().
operator==() [2/2]
bool guWhiteboard::VisionDetectionHorizons::operator== (const wb_vision_detection_horizons & t_other) const inline
Definition at line 163 of file VisionDetectionHorizons.hpp.
References VisionDetectionHorizons().
res_height() [1/2]
uint16_t & guWhiteboard::VisionDetectionHorizons::res_height () inline
Definition at line 233 of file VisionDetectionHorizons.hpp.
References wb_vision_detection_horizons::res_height.
Referenced by VisionDetectionHorizons(), description(), operator=(), operator==(), and to_string().
res_height() [2/2]
const uint16_t & guWhiteboard::VisionDetectionHorizons::res_height () const inline
Definition at line 238 of file VisionDetectionHorizons.hpp.
References wb_vision_detection_horizons::res_height.
res_width() [1/2]
uint16_t & guWhiteboard::VisionDetectionHorizons::res_width () inline
Definition at line 218 of file VisionDetectionHorizons.hpp.
References wb_vision_detection_horizons::res_width.
Referenced by VisionDetectionHorizons(), description(), operator=(), operator==(), and to_string().
res_width() [2/2]
const uint16_t & guWhiteboard::VisionDetectionHorizons::res_width () const inline
Definition at line 223 of file VisionDetectionHorizons.hpp.
References wb_vision_detection_horizons::res_width.
set_frameNumber()
void guWhiteboard::VisionDetectionHorizons::set_frameNumber (const uint64_t & t_newValue) inline
Definition at line 183 of file VisionDetectionHorizons.hpp.
References wb_vision_detection_horizons::frameNumber.
Referenced by from_string().
set_horizons() [1/2]
void guWhiteboard::VisionDetectionHorizons::set_horizons (const VisionDetectionHorizon & t_newValue, int t_i) inline
Definition at line 213 of file VisionDetectionHorizons.hpp.
References wb_vision_detection_horizons::horizons.
set_horizons() [2/2]
void guWhiteboard::VisionDetectionHorizons::set_horizons (const VisionDetectionHorizon * t_newValue) inline
Definition at line 208 of file VisionDetectionHorizons.hpp.
References wb_vision_detection_horizons::horizons, and VISION_DETECTION_HORIZONS_HORIZONS_ARRAY_SIZE.
Referenced by from_string().
set_res_height()
void guWhiteboard::VisionDetectionHorizons::set_res_height (const uint16_t & t_newValue) inline
Definition at line 243 of file VisionDetectionHorizons.hpp.
References wb_vision_detection_horizons::res_height.
Referenced by from_string().
set_res_width()
void guWhiteboard::VisionDetectionHorizons::set_res_width (const uint16_t & t_newValue) inline
Definition at line 228 of file VisionDetectionHorizons.hpp.
References wb_vision_detection_horizons::res_width.
Referenced by from_string().
to_string()
std::string guWhiteboard::VisionDetectionHorizons::to_string () inline
USE_WB_VISION_DETECTION_HORIZONS_C_CONVERSION
Definition at line 282 of file VisionDetectionHorizons.hpp.
References frameNumber(), horizons(), res_height(), res_width(), to_string(), VISION_DETECTION_HORIZONS_HORIZONS_ARRAY_SIZE, VISION_DETECTION_HORIZONS_TO_STRING_BUFFER_SIZE, and wb_vision_detection_horizons_to_string().
Referenced by to_string().
The documentation for this class was generated from the following file:
typeClassDefs/VisionDetectionHorizons.hpp