gusimplewhiteboard: guWhiteboard::SensorsHandSensors Class Reference
guWhiteboard::SensorsHandSensors Class Reference
Provides a C++ wrapper around wb_sensors_hand_sensors.
#include <SensorsHandSensors.hpp>
Public Member Functions
SensorsHandSensors (bool t_LHand_Touch_Left=true, bool t_LHand_Touch_Back=true, bool t_LHand_Touch_Right=true, bool t_RHand_Touch_Left=true, bool t_RHand_Touch_Back=true, bool t_RHand_Touch_Right=true)
Create a new SensorsHandSensors.
SensorsHandSensors (const SensorsHandSensors &t_other)
Copy Constructor.
SensorsHandSensors (const struct wb_sensors_hand_sensors &t_other)
Copy Constructor.
SensorsHandSensors & operator= (const SensorsHandSensors &t_other)
Copy Assignment Operator.
SensorsHandSensors & operator= (const struct wb_sensors_hand_sensors &t_other)
Copy Assignment Operator.
bool operator== (const SensorsHandSensors &t_other) const
bool operator!= (const SensorsHandSensors &t_other) const
bool operator== (const wb_sensors_hand_sensors &t_other) const
bool operator!= (const wb_sensors_hand_sensors &t_other) const
bool & LHand_Touch_Left ()
const bool & LHand_Touch_Left () const
void set_LHand_Touch_Left (const bool &t_newValue)
bool & LHand_Touch_Back ()
const bool & LHand_Touch_Back () const
void set_LHand_Touch_Back (const bool &t_newValue)
bool & LHand_Touch_Right ()
const bool & LHand_Touch_Right () const
void set_LHand_Touch_Right (const bool &t_newValue)
bool & RHand_Touch_Left ()
const bool & RHand_Touch_Left () const
void set_RHand_Touch_Left (const bool &t_newValue)
bool & RHand_Touch_Back ()
const bool & RHand_Touch_Back () const
void set_RHand_Touch_Back (const bool &t_newValue)
bool & RHand_Touch_Right ()
const bool & RHand_Touch_Right () const
void set_RHand_Touch_Right (const bool &t_newValue)
SensorsHandSensors (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_sensors_hand_sensors
bool LHand_Touch_Left
state of the hand capacitive sensor on the Left side of Left Hand, on / off.
bool LHand_Touch_Back
state of the hand capacitive sensor on the Back of Left Hand, on / off.
bool LHand_Touch_Right
state of the hand capacitive sensor on the Right side of Left Hand, on / off.
bool RHand_Touch_Left
state of the hand capacitive sensor on the Left side of Right Hand, on / off.
bool RHand_Touch_Back
state of the hand capacitive sensor on the Back of Right Hand, on / off.
bool RHand_Touch_Right
state of the hand capacitive sensor on the Right side of Right Hand, on / off.
Detailed Description
Provides a C++ wrapper around wb_sensors_hand_sensors.
Definition at line 83 of file SensorsHandSensors.hpp.
Constructor & Destructor Documentation
SensorsHandSensors() [1/4]
guWhiteboard::SensorsHandSensors::SensorsHandSensors (bool t_LHand_Touch_Left = true, bool t_LHand_Touch_Back = true, bool t_LHand_Touch_Right = true, bool t_RHand_Touch_Left = true, bool t_RHand_Touch_Back = true, bool t_RHand_Touch_Right = true) inline
Create a new SensorsHandSensors.
Definition at line 104 of file SensorsHandSensors.hpp.
Referenced by operator==().
SensorsHandSensors() [2/4]
guWhiteboard::SensorsHandSensors::SensorsHandSensors (const SensorsHandSensors & t_other) inline
Copy Constructor.
Definition at line 111 of file SensorsHandSensors.hpp.
References LHand_Touch_Back(), LHand_Touch_Left(), LHand_Touch_Right(), RHand_Touch_Back(), RHand_Touch_Left(), and RHand_Touch_Right().
SensorsHandSensors() [3/4]
guWhiteboard::SensorsHandSensors::SensorsHandSensors (const struct wb_sensors_hand_sensors & t_other) inline
Copy Constructor.
Definition at line 118 of file SensorsHandSensors.hpp.
References wb_sensors_hand_sensors::LHand_Touch_Back, wb_sensors_hand_sensors::LHand_Touch_Left, wb_sensors_hand_sensors::LHand_Touch_Right, wb_sensors_hand_sensors::RHand_Touch_Back, wb_sensors_hand_sensors::RHand_Touch_Left, and wb_sensors_hand_sensors::RHand_Touch_Right.
SensorsHandSensors() [4/4]
guWhiteboard::SensorsHandSensors::SensorsHandSensors (const std::string & t_str) inline
String Constructor.
Definition at line 257 of file SensorsHandSensors.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::SensorsHandSensors::description () inline
USE_WB_SENSORS_HAND_SENSORS_C_CONVERSION
Definition at line 262 of file SensorsHandSensors.hpp.
References LHand_Touch_Back(), LHand_Touch_Left(), LHand_Touch_Right(), RHand_Touch_Back(), RHand_Touch_Left(), RHand_Touch_Right(), SENSORS_HAND_SENSORS_DESC_BUFFER_SIZE, and wb_sensors_hand_sensors_description().
from_string()
void guWhiteboard::SensorsHandSensors::from_string (const std::string & t_str) inline
USE_WB_SENSORS_HAND_SENSORS_C_CONVERSION
Definition at line 312 of file SensorsHandSensors.hpp.
References SENSORS_HAND_SENSORS_DESC_BUFFER_SIZE, set_LHand_Touch_Back(), set_LHand_Touch_Left(), set_LHand_Touch_Right(), set_RHand_Touch_Back(), set_RHand_Touch_Left(), and set_RHand_Touch_Right().
Referenced by SensorsHandSensors().
LHand_Touch_Back() [1/2]
bool & guWhiteboard::SensorsHandSensors::LHand_Touch_Back () inline
Definition at line 178 of file SensorsHandSensors.hpp.
References wb_sensors_hand_sensors::LHand_Touch_Back.
Referenced by SensorsHandSensors(), description(), operator=(), operator==(), and to_string().
LHand_Touch_Back() [2/2]
const bool & guWhiteboard::SensorsHandSensors::LHand_Touch_Back () const inline
Definition at line 183 of file SensorsHandSensors.hpp.
References wb_sensors_hand_sensors::LHand_Touch_Back.
LHand_Touch_Left() [1/2]
bool & guWhiteboard::SensorsHandSensors::LHand_Touch_Left () inline
Definition at line 163 of file SensorsHandSensors.hpp.
References wb_sensors_hand_sensors::LHand_Touch_Left.
Referenced by SensorsHandSensors(), description(), operator=(), operator==(), and to_string().
LHand_Touch_Left() [2/2]
const bool & guWhiteboard::SensorsHandSensors::LHand_Touch_Left () const inline
Definition at line 168 of file SensorsHandSensors.hpp.
References wb_sensors_hand_sensors::LHand_Touch_Left.
LHand_Touch_Right() [1/2]
bool & guWhiteboard::SensorsHandSensors::LHand_Touch_Right () inline
Definition at line 193 of file SensorsHandSensors.hpp.
References wb_sensors_hand_sensors::LHand_Touch_Right.
Referenced by SensorsHandSensors(), description(), operator=(), operator==(), and to_string().
LHand_Touch_Right() [2/2]
const bool & guWhiteboard::SensorsHandSensors::LHand_Touch_Right () const inline
Definition at line 198 of file SensorsHandSensors.hpp.
References wb_sensors_hand_sensors::LHand_Touch_Right.
operator!=() [1/2]
bool guWhiteboard::SensorsHandSensors::operator!= (const SensorsHandSensors & t_other) const inline
Definition at line 148 of file SensorsHandSensors.hpp.
operator!=() [2/2]
bool guWhiteboard::SensorsHandSensors::operator!= (const wb_sensors_hand_sensors & t_other) const inline
Definition at line 158 of file SensorsHandSensors.hpp.
operator=() [1/2]
SensorsHandSensors & guWhiteboard::SensorsHandSensors::operator= (const SensorsHandSensors & t_other) inline
Copy Assignment Operator.
Definition at line 125 of file SensorsHandSensors.hpp.
References LHand_Touch_Back(), LHand_Touch_Left(), LHand_Touch_Right(), RHand_Touch_Back(), RHand_Touch_Left(), and RHand_Touch_Right().
operator=() [2/2]
SensorsHandSensors & guWhiteboard::SensorsHandSensors::operator= (const struct wb_sensors_hand_sensors & t_other) inline
Copy Assignment Operator.
Definition at line 133 of file SensorsHandSensors.hpp.
References wb_sensors_hand_sensors::LHand_Touch_Back, wb_sensors_hand_sensors::LHand_Touch_Left, wb_sensors_hand_sensors::LHand_Touch_Right, wb_sensors_hand_sensors::RHand_Touch_Back, wb_sensors_hand_sensors::RHand_Touch_Left, and wb_sensors_hand_sensors::RHand_Touch_Right.
operator==() [1/2]
bool guWhiteboard::SensorsHandSensors::operator== (const SensorsHandSensors & t_other) const inline
Definition at line 138 of file SensorsHandSensors.hpp.
References LHand_Touch_Back(), LHand_Touch_Left(), LHand_Touch_Right(), RHand_Touch_Back(), RHand_Touch_Left(), and RHand_Touch_Right().
operator==() [2/2]
bool guWhiteboard::SensorsHandSensors::operator== (const wb_sensors_hand_sensors & t_other) const inline
Definition at line 153 of file SensorsHandSensors.hpp.
References SensorsHandSensors().
RHand_Touch_Back() [1/2]
bool & guWhiteboard::SensorsHandSensors::RHand_Touch_Back () inline
Definition at line 223 of file SensorsHandSensors.hpp.
References wb_sensors_hand_sensors::RHand_Touch_Back.
Referenced by SensorsHandSensors(), description(), operator=(), operator==(), and to_string().
RHand_Touch_Back() [2/2]
const bool & guWhiteboard::SensorsHandSensors::RHand_Touch_Back () const inline
Definition at line 228 of file SensorsHandSensors.hpp.
References wb_sensors_hand_sensors::RHand_Touch_Back.
RHand_Touch_Left() [1/2]
bool & guWhiteboard::SensorsHandSensors::RHand_Touch_Left () inline
Definition at line 208 of file SensorsHandSensors.hpp.
References wb_sensors_hand_sensors::RHand_Touch_Left.
Referenced by SensorsHandSensors(), description(), operator=(), operator==(), and to_string().
RHand_Touch_Left() [2/2]
const bool & guWhiteboard::SensorsHandSensors::RHand_Touch_Left () const inline
Definition at line 213 of file SensorsHandSensors.hpp.
References wb_sensors_hand_sensors::RHand_Touch_Left.
RHand_Touch_Right() [1/2]
bool & guWhiteboard::SensorsHandSensors::RHand_Touch_Right () inline
Definition at line 238 of file SensorsHandSensors.hpp.
References wb_sensors_hand_sensors::RHand_Touch_Right.
Referenced by SensorsHandSensors(), description(), operator=(), operator==(), and to_string().
RHand_Touch_Right() [2/2]
const bool & guWhiteboard::SensorsHandSensors::RHand_Touch_Right () const inline
Definition at line 243 of file SensorsHandSensors.hpp.
References wb_sensors_hand_sensors::RHand_Touch_Right.
set_LHand_Touch_Back()
void guWhiteboard::SensorsHandSensors::set_LHand_Touch_Back (const bool & t_newValue) inline
Definition at line 188 of file SensorsHandSensors.hpp.
References wb_sensors_hand_sensors::LHand_Touch_Back.
Referenced by from_string().
set_LHand_Touch_Left()
void guWhiteboard::SensorsHandSensors::set_LHand_Touch_Left (const bool & t_newValue) inline
Definition at line 173 of file SensorsHandSensors.hpp.
References wb_sensors_hand_sensors::LHand_Touch_Left.
Referenced by from_string().
set_LHand_Touch_Right()
void guWhiteboard::SensorsHandSensors::set_LHand_Touch_Right (const bool & t_newValue) inline
Definition at line 203 of file SensorsHandSensors.hpp.
References wb_sensors_hand_sensors::LHand_Touch_Right.
Referenced by from_string().
set_RHand_Touch_Back()
void guWhiteboard::SensorsHandSensors::set_RHand_Touch_Back (const bool & t_newValue) inline
Definition at line 233 of file SensorsHandSensors.hpp.
References wb_sensors_hand_sensors::RHand_Touch_Back.
Referenced by from_string().
set_RHand_Touch_Left()
void guWhiteboard::SensorsHandSensors::set_RHand_Touch_Left (const bool & t_newValue) inline
Definition at line 218 of file SensorsHandSensors.hpp.
References wb_sensors_hand_sensors::RHand_Touch_Left.
Referenced by from_string().
set_RHand_Touch_Right()
void guWhiteboard::SensorsHandSensors::set_RHand_Touch_Right (const bool & t_newValue) inline
Definition at line 248 of file SensorsHandSensors.hpp.
References wb_sensors_hand_sensors::RHand_Touch_Right.
Referenced by from_string().
to_string()
std::string guWhiteboard::SensorsHandSensors::to_string () inline
USE_WB_SENSORS_HAND_SENSORS_C_CONVERSION
Definition at line 285 of file SensorsHandSensors.hpp.
References LHand_Touch_Back(), LHand_Touch_Left(), LHand_Touch_Right(), RHand_Touch_Back(), RHand_Touch_Left(), RHand_Touch_Right(), SENSORS_HAND_SENSORS_TO_STRING_BUFFER_SIZE, and wb_sensors_hand_sensors_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/SensorsHandSensors.hpp