gusimplewhiteboard: guWhiteboard::VisionDetectionLines Class Reference
guWhiteboard::VisionDetectionLines Class Reference
Provides a C++ wrapper around wb_vision_detection_lines.
#include <VisionDetectionLines.hpp>
Public Member Functions
VisionDetectionLines (uint64_t t_frameNumber=0, const struct wb_vision_detection_line_array t_lines[2]=NULLPTR, uint16_t t_res_width=0, uint16_t t_res_height=0)
Create a new VisionDetectionLines.
VisionDetectionLines (const VisionDetectionLines &t_other)
Copy Constructor.
VisionDetectionLines (const struct wb_vision_detection_lines &t_other)
Copy Constructor.
VisionDetectionLines & operator= (const VisionDetectionLines &t_other)
Copy Assignment Operator.
VisionDetectionLines & operator= (const struct wb_vision_detection_lines &t_other)
Copy Assignment Operator.
bool operator== (const VisionDetectionLines &t_other) const
bool operator!= (const VisionDetectionLines &t_other) const
bool operator== (const wb_vision_detection_lines &t_other) const
bool operator!= (const wb_vision_detection_lines &t_other) const
uint64_t & frameNumber ()
const uint64_t & frameNumber () const
void set_frameNumber (const uint64_t &t_newValue)
const VisionDetectionLineArray * lines () const
size_t lines_size () const
VisionDetectionLineArray & lines (int t_i)
const VisionDetectionLineArray & lines (int t_i) const
void set_lines (const VisionDetectionLineArray *t_newValue)
void set_lines (const VisionDetectionLineArray &t_newValue, int t_i)
uint16_t & res_width ()
const uint16_t & res_width () const
void set_res_width (const uint16_t &t_newValue)
uint16_t & res_height ()
const uint16_t & res_height () const
void set_res_height (const uint16_t &t_newValue)
VisionDetectionLines (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_vision_detection_lines
uint64_t frameNumber
The frame number that these lines were seen in.
struct wb_vision_detection_line_array lines [2]
Lines reported for each camera.
uint16_t res_width
The resolution width.
uint16_t res_height
The resolution height.
Detailed Description
Provides a C++ wrapper around wb_vision_detection_lines.
Definition at line 85 of file VisionDetectionLines.hpp.
Constructor & Destructor Documentation
VisionDetectionLines() [1/4]
guWhiteboard::VisionDetectionLines::VisionDetectionLines (uint64_t t_frameNumber = 0, const struct wb_vision_detection_line_array t_lines[2] = NULLPTR, uint16_t t_res_width = 0, uint16_t t_res_height = 0) inline
Create a new VisionDetectionLines.
Definition at line 109 of file VisionDetectionLines.hpp.
Referenced by operator==().
VisionDetectionLines() [2/4]
guWhiteboard::VisionDetectionLines::VisionDetectionLines (const VisionDetectionLines & t_other) inline
Copy Constructor.
Definition at line 116 of file VisionDetectionLines.hpp.
References frameNumber(), lines(), res_height(), and res_width().
VisionDetectionLines() [3/4]
guWhiteboard::VisionDetectionLines::VisionDetectionLines (const struct wb_vision_detection_lines & t_other) inline
Copy Constructor.
Definition at line 123 of file VisionDetectionLines.hpp.
References wb_vision_detection_lines::frameNumber, wb_vision_detection_lines::lines, wb_vision_detection_lines::res_height, and wb_vision_detection_lines::res_width.
VisionDetectionLines() [4/4]
guWhiteboard::VisionDetectionLines::VisionDetectionLines (const std::string & t_str) inline
String Constructor.
Definition at line 252 of file VisionDetectionLines.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::VisionDetectionLines::description () inline
USE_WB_VISION_DETECTION_LINES_C_CONVERSION
Definition at line 257 of file VisionDetectionLines.hpp.
References description(), frameNumber(), lines(), res_height(), res_width(), VISION_DETECTION_LINES_DESC_BUFFER_SIZE, VISION_DETECTION_LINES_LINES_ARRAY_SIZE, and wb_vision_detection_lines_description().
Referenced by description().
frameNumber() [1/2]
uint64_t & guWhiteboard::VisionDetectionLines::frameNumber () inline
Definition at line 173 of file VisionDetectionLines.hpp.
References wb_vision_detection_lines::frameNumber.
Referenced by VisionDetectionLines(), description(), operator=(), operator==(), and to_string().
frameNumber() [2/2]
const uint64_t & guWhiteboard::VisionDetectionLines::frameNumber () const inline
Definition at line 178 of file VisionDetectionLines.hpp.
References wb_vision_detection_lines::frameNumber.
from_string()
void guWhiteboard::VisionDetectionLines::from_string (const std::string & t_str) inline
USE_WB_VISION_DETECTION_LINES_C_CONVERSION
Definition at line 311 of file VisionDetectionLines.hpp.
References guWhiteboard::VisionDetectionLineArray::from_string(), set_frameNumber(), set_lines(), set_res_height(), set_res_width(), VISION_DETECTION_LINES_DESC_BUFFER_SIZE, and VISION_DETECTION_LINES_LINES_ARRAY_SIZE.
Referenced by VisionDetectionLines().
lines() [1/3]
const VisionDetectionLineArray * guWhiteboard::VisionDetectionLines::lines () const inline
Definition at line 188 of file VisionDetectionLines.hpp.
References wb_vision_detection_lines::lines.
Referenced by VisionDetectionLines(), description(), operator=(), operator==(), and to_string().
lines() [2/3]
VisionDetectionLineArray & guWhiteboard::VisionDetectionLines::lines (int t_i) inline
Definition at line 198 of file VisionDetectionLines.hpp.
References wb_vision_detection_lines::lines.
lines() [3/3]
const VisionDetectionLineArray & guWhiteboard::VisionDetectionLines::lines (int t_i) const inline
Definition at line 203 of file VisionDetectionLines.hpp.
References wb_vision_detection_lines::lines.
lines_size()
size_t guWhiteboard::VisionDetectionLines::lines_size () const inline
Definition at line 193 of file VisionDetectionLines.hpp.
References VISION_DETECTION_LINES_LINES_ARRAY_SIZE.
operator!=() [1/2]
bool guWhiteboard::VisionDetectionLines::operator!= (const VisionDetectionLines & t_other) const inline
Definition at line 158 of file VisionDetectionLines.hpp.
operator!=() [2/2]
bool guWhiteboard::VisionDetectionLines::operator!= (const wb_vision_detection_lines & t_other) const inline
Definition at line 168 of file VisionDetectionLines.hpp.
operator=() [1/2]
VisionDetectionLines & guWhiteboard::VisionDetectionLines::operator= (const struct wb_vision_detection_lines & t_other) inline
Copy Assignment Operator.
Definition at line 138 of file VisionDetectionLines.hpp.
References wb_vision_detection_lines::frameNumber, wb_vision_detection_lines::lines, wb_vision_detection_lines::res_height, and wb_vision_detection_lines::res_width.
operator=() [2/2]
VisionDetectionLines & guWhiteboard::VisionDetectionLines::operator= (const VisionDetectionLines & t_other) inline
Copy Assignment Operator.
Definition at line 130 of file VisionDetectionLines.hpp.
References frameNumber(), lines(), res_height(), and res_width().
operator==() [1/2]
bool guWhiteboard::VisionDetectionLines::operator== (const VisionDetectionLines & t_other) const inline
Definition at line 143 of file VisionDetectionLines.hpp.
References frameNumber(), lines(), res_height(), and res_width().
operator==() [2/2]
bool guWhiteboard::VisionDetectionLines::operator== (const wb_vision_detection_lines & t_other) const inline
Definition at line 163 of file VisionDetectionLines.hpp.
References VisionDetectionLines().
res_height() [1/2]
uint16_t & guWhiteboard::VisionDetectionLines::res_height () inline
Definition at line 233 of file VisionDetectionLines.hpp.
References wb_vision_detection_lines::res_height.
Referenced by VisionDetectionLines(), description(), operator=(), operator==(), and to_string().
res_height() [2/2]
const uint16_t & guWhiteboard::VisionDetectionLines::res_height () const inline
Definition at line 238 of file VisionDetectionLines.hpp.
References wb_vision_detection_lines::res_height.
res_width() [1/2]
uint16_t & guWhiteboard::VisionDetectionLines::res_width () inline
Definition at line 218 of file VisionDetectionLines.hpp.
References wb_vision_detection_lines::res_width.
Referenced by VisionDetectionLines(), description(), operator=(), operator==(), and to_string().
res_width() [2/2]
const uint16_t & guWhiteboard::VisionDetectionLines::res_width () const inline
Definition at line 223 of file VisionDetectionLines.hpp.
References wb_vision_detection_lines::res_width.
set_frameNumber()
void guWhiteboard::VisionDetectionLines::set_frameNumber (const uint64_t & t_newValue) inline
Definition at line 183 of file VisionDetectionLines.hpp.
References wb_vision_detection_lines::frameNumber.
Referenced by from_string().
set_lines() [1/2]
void guWhiteboard::VisionDetectionLines::set_lines (const VisionDetectionLineArray & t_newValue, int t_i) inline
Definition at line 213 of file VisionDetectionLines.hpp.
References wb_vision_detection_lines::lines.
set_lines() [2/2]
void guWhiteboard::VisionDetectionLines::set_lines (const VisionDetectionLineArray * t_newValue) inline
Definition at line 208 of file VisionDetectionLines.hpp.
References wb_vision_detection_lines::lines, and VISION_DETECTION_LINES_LINES_ARRAY_SIZE.
Referenced by from_string().
set_res_height()
void guWhiteboard::VisionDetectionLines::set_res_height (const uint16_t & t_newValue) inline
Definition at line 243 of file VisionDetectionLines.hpp.
References wb_vision_detection_lines::res_height.
Referenced by from_string().
set_res_width()
void guWhiteboard::VisionDetectionLines::set_res_width (const uint16_t & t_newValue) inline
Definition at line 228 of file VisionDetectionLines.hpp.
References wb_vision_detection_lines::res_width.
Referenced by from_string().
to_string()
std::string guWhiteboard::VisionDetectionLines::to_string () inline
USE_WB_VISION_DETECTION_LINES_C_CONVERSION
Definition at line 282 of file VisionDetectionLines.hpp.
References frameNumber(), lines(), res_height(), res_width(), to_string(), VISION_DETECTION_LINES_LINES_ARRAY_SIZE, VISION_DETECTION_LINES_TO_STRING_BUFFER_SIZE, and wb_vision_detection_lines_to_string().
Referenced by to_string().
The documentation for this class was generated from the following file:
typeClassDefs/VisionDetectionLines.hpp