gusimplewhiteboard: guWhiteboard::HalLegTarget Class Reference
guWhiteboard::HalLegTarget Class Reference
Class for moving a SINGLE robotic leg with up to 6 degrees of freedom using local coords of each joint.
#include <HAL_LegTarget.hpp>
Public Member Functions
HalLegTarget (const uint8_t &target_leg=0, const float hipyawpitch=0, const float hiproll=0, const float hippitch=0, const float kneepitch=0, const float anklepitch=0, const float ankleroll=0, const float hipyawpitchstiffness=0, const float hiprollstiffness=0, const float hippitchstiffness=0, const float kneepitchstiffness=0, const float anklepitchstiffness=0, const float anklerollstiffness=0, const bool hipyawpitch_active=true, const bool hiproll_active=true, const bool hippitch_active=true, const bool kneepitch_active=true, const bool anklepitch_active=true, const bool ankleroll_active=true, const int32_t movement_time=1000000, const uint8_t pliability=10, const bool leg_stop=false, const bool inRadians=false)
Constructor, defaults to LEFT_LEG.
void tieToLeg (uint8_t leg)
Specify which leg this instance manages.
void goToWithTime_Rad (float hipyawpitch, float hiproll, float hippitch, float kneepitch, float anklepitch, float ankleroll, int32_t time=INT_MAX)
move to position in radians over a given time
void goToWithTime_Deg (float hipyawpitch, float hiproll, float hippitch, float kneepitch, float anklepitch, float ankleroll, int32_t time=INT_MAX)
move to position in degrees over a given time
void stop ()
Command the leg to stop at its current location and not act on motion commands until ready() is called.
void ready ()
Set leg to ready state (Default) The leg will act on motion commands.
void isAtGoal (bool goalReached)
Leg at Goal Setter Clients/Machines should not use this method.
bool atGoal ()
Leg at Goal Getter Clients/Machines should use this getter to test if the DCM has reported that the leg has reached its goal pose.
bool atTargetLocation (HalLegTarget status, HalLegTarget tolerance)
Client side test to determine if leg is at the target location, allowing for specified tolerances.
void setPose_Rad (float hipyawpitch, float hiproll, float hippitch, float kneepitch, float anklepitch, float ankleroll)
Set Pose in radians.
void setPose_Deg (float hipyawpitch, float hiproll, float hippitch, float kneepitch, float anklepitch, float ankleroll)
Set Pose in degrees.
void mirrorLeg (const HalLegTarget &other)
Convenience function to mirror leg settings about the XZ plane from one HalLegTarget object to another.
void copyPose (const HalLegTarget &other)
Convenience function to copy pose settings from one HalLegTarget object to another.
void mirrorPose (const HalLegTarget &other)
Convenience function to mirror pose settings about the XZ plane from one HalLegTarget object to another.
bool hasSamePose (const HalLegTarget &other)
Tests if this HalLegTarget object has the same pose settings as the other HalLegTarget object.
bool hasSameMirroredPose (const HalLegTarget &other)
Tests if this HalLegTarget object has the same mirrored pose settings as the other HalLegTarget object.
void setLegStiffnessMax ()
Convenience function to set the stiffness of all the leg's joints to the maximum (1.0f).
void setLegStiffnessNormal ()
Convenience function to set the stiffness of all the leg's joints to what Aldebaran considers 'normal' (0.6f).
void setLegStiffness (float stiffness)
Convenience function to set uniform stiffness on all leg joints to a custom value.
void setLegStiffnessOff ()
Convenience function to turn off stiffness in all the leg's joints (0.0f).
void copyStiffness (const HalLegTarget &other)
Convenience function to copy stiffness settings from one HalLegTarget object to another.
bool hasSameStiffness (const HalLegTarget &other)
Tests if this HalLegTarget object has the same stiffness settings as the other HalLegTarget object.
void setLegActive ()
Set leg to be Active (DEDAULT DCM state) The leg is active and manual movements will be resisted, be careful when the stiffness is set high.
void setLegPassive ()
Set leg to be Passive Manually moving the leg causes the leg to stay in the new position.
void setLegPliability (bool hipyawpitch, bool hiproll, bool hippitch, bool kneepitch, bool anklepitch, bool ankleroll)
Individually set the active/passive state of each joint.
bool isLegPassive ()
Are any of the leg's joints set to passive.
bool isLegAllPassive ()
Are all of the legs's joints set to passive.
bool isLegAllActive ()
Are all of the leg's joints set to active.
void set_hipyawpitch_DEG (float setting)
Movement Setters (Degrees)
void set_hiproll_DEG (float setting)
void set_hippitch_DEG (float setting)
void set_kneepitch_DEG (float setting)
void set_anklepitch_DEG (float setting)
void set_ankleroll_DEG (float setting)
void set_hipyawpitch_RAD (float setting)
Movement Setters (Radians)
void set_hiproll_RAD (float setting)
void set_hippitch_RAD (float setting)
void set_kneepitch_RAD (float setting)
void set_anklepitch_RAD (float setting)
void set_ankleroll_RAD (float setting)
void set_hipyawpitchstiffness (float setting)
Stiffness Setters.
void set_hiprollstiffness (float setting)
void set_hippitchstiffness (float setting)
void set_kneepitchstiffness (float setting)
void set_anklepitchstiffness (float setting)
void set_anklerollstiffness (float setting)
float get_hipyawpitch_DEG ()
Movement Getters (Degrees)
float get_hiproll_DEG ()
float get_hippitch_DEG ()
float get_kneepitch_DEG ()
float get_anklepitch_DEG ()
float get_ankleroll_DEG ()
float get_hipyawpitch_RAD ()
Movement Getters (Radians)
float get_hiproll_RAD ()
float get_hippitch_RAD ()
float get_kneepitch_RAD ()
float get_anklepitch_RAD ()
float get_ankleroll_RAD ()
float get_hipyawpitchstiffness ()
Stiffness Getters.
float get_hiprollstiffness ()
float get_hippitchstiffness ()
float get_kneepitchstiffness ()
float get_anklepitchstiffness ()
float get_anklerollstiffness ()
std::string description () const
Description function.
HalLegTarget (const std::string &str)
String constructor (NYI)
void from_string (const std::string &str)
Parser for recreating this class (NYI)
HalLegTarget (int32_t t_target_movement_time=INT_MAX, int16_t t_target_hipyawpitch=0, int16_t t_target_hiproll=0, int16_t t_target_hippitch=0, int16_t t_target_kneepitch=0, int16_t t_target_anklepitch=0, int16_t t_target_ankleroll=0, uint8_t t_target_leg=(static_cast< uint8_t >(0)), uint8_t t_target_hipyawpitchstiffness=0, uint8_t t_target_hiprollstiffness=0, uint8_t t_target_hippitchstiffness=0, uint8_t t_target_kneepitchstiffness=0, uint8_t t_target_anklepitchstiffness=0, uint8_t t_target_anklerollstiffness=0, uint8_t t_target_pliability=0, unsigned int t_target_hipyawpitch_active=true, unsigned int t_target_hiproll_active=true, unsigned int t_target_hippitch_active=true, unsigned int t_target_kneepitch_active=true, unsigned int t_target_anklepitch_active=true, unsigned int t_target_ankleroll_active=true, unsigned int t_target_leg_at_goal=false, unsigned int t_target_leg_stop=false)
Create a new HalLegTarget.
HalLegTarget (const HalLegTarget &t_other)
Copy Constructor.
HalLegTarget (const struct wb_hal_leg_target &t_other)
Copy Constructor.
HalLegTarget & operator= (const HalLegTarget &t_other)
Copy Assignment Operator.
HalLegTarget & operator= (const struct wb_hal_leg_target &t_other)
Copy Assignment Operator.
bool operator== (const HalLegTarget &t_other) const
bool operator!= (const HalLegTarget &t_other) const
bool operator== (const wb_hal_leg_target &t_other) const
bool operator!= (const wb_hal_leg_target &t_other) const
int32_t & target_movement_time ()
const int32_t & target_movement_time () const
void set_target_movement_time (const int32_t &t_newValue)
int16_t & target_hipyawpitch ()
const int16_t & target_hipyawpitch () const
void set_target_hipyawpitch (const int16_t &t_newValue)
int16_t & target_hiproll ()
const int16_t & target_hiproll () const
void set_target_hiproll (const int16_t &t_newValue)
int16_t & target_hippitch ()
const int16_t & target_hippitch () const
void set_target_hippitch (const int16_t &t_newValue)
int16_t & target_kneepitch ()
const int16_t & target_kneepitch () const
void set_target_kneepitch (const int16_t &t_newValue)
int16_t & target_anklepitch ()
const int16_t & target_anklepitch () const
void set_target_anklepitch (const int16_t &t_newValue)
int16_t & target_ankleroll ()
const int16_t & target_ankleroll () const
void set_target_ankleroll (const int16_t &t_newValue)
uint8_t & target_leg ()
const uint8_t & target_leg () const
void set_target_leg (const uint8_t &t_newValue)
uint8_t & target_hipyawpitchstiffness ()
const uint8_t & target_hipyawpitchstiffness () const
void set_target_hipyawpitchstiffness (const uint8_t &t_newValue)
uint8_t & target_hiprollstiffness ()
const uint8_t & target_hiprollstiffness () const
void set_target_hiprollstiffness (const uint8_t &t_newValue)
uint8_t & target_hippitchstiffness ()
const uint8_t & target_hippitchstiffness () const
void set_target_hippitchstiffness (const uint8_t &t_newValue)
uint8_t & target_kneepitchstiffness ()
const uint8_t & target_kneepitchstiffness () const
void set_target_kneepitchstiffness (const uint8_t &t_newValue)
uint8_t & target_anklepitchstiffness ()
const uint8_t & target_anklepitchstiffness () const
void set_target_anklepitchstiffness (const uint8_t &t_newValue)
uint8_t & target_anklerollstiffness ()
const uint8_t & target_anklerollstiffness () const
void set_target_anklerollstiffness (const uint8_t &t_newValue)
uint8_t & target_pliability ()
const uint8_t & target_pliability () const
void set_target_pliability (const uint8_t &t_newValue)
unsigned int target_hipyawpitch_active () const
void set_target_hipyawpitch_active (const unsigned int &t_newValue)
unsigned int target_hiproll_active () const
void set_target_hiproll_active (const unsigned int &t_newValue)
unsigned int target_hippitch_active () const
void set_target_hippitch_active (const unsigned int &t_newValue)
unsigned int target_kneepitch_active () const
void set_target_kneepitch_active (const unsigned int &t_newValue)
unsigned int target_anklepitch_active () const
void set_target_anklepitch_active (const unsigned int &t_newValue)
unsigned int target_ankleroll_active () const
void set_target_ankleroll_active (const unsigned int &t_newValue)
unsigned int target_leg_at_goal () const
void set_target_leg_at_goal (const unsigned int &t_newValue)
unsigned int target_leg_stop () const
void set_target_leg_stop (const unsigned int &t_newValue)
HalLegTarget (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
std::string valueDescription ()
WHITEBOARD_POSTER_STRING_CONVERSION.
void tieToLeg (uint8_t leg)
USE_WB_HAL_LEG_TARGET_C_CONVERSION WHITEBOARD_POSTER_STRING_CONVERSION.
void goToWithTime_Rad (float hipyawpitch, float hiproll, float hippitch, float kneepitch, float anklepitch, float ankleroll, int32_t time=INT_MAX)
move to position in radians over a given time
void goToWithTime_Deg (float hipyawpitch, float hiproll, float hippitch, float kneepitch, float anklepitch, float ankleroll, int32_t time=INT_MAX)
move to position in degrees over a given time
void stop ()
Command the leg to stop at its current location and not act on motion commands until ready() is called.
void ready ()
Set leg to ready state (Default) The leg will act on motion commands.
void isAtGoal (bool goalReached)
Leg at Goal Setter Clients/Machines should not use this method.
bool atGoal ()
Leg at Goal Getter Clients/Machines should use this getter to test if the DCM has reported that the leg has reached its goal pose.
bool atTargetLocation (HalLegTarget status, HalLegTarget tolerance)
Client side test to determine if leg is at the target location, allowing for specified tolerances.
void setPose_Rad (float hipyawpitch, float hiproll, float hippitch, float kneepitch, float anklepitch, float ankleroll)
Set Pose in radians.
void setPose_Deg (float hipyawpitch, float hiproll, float hippitch, float kneepitch, float anklepitch, float ankleroll)
Set Pose in degrees.
void mirrorLeg (const HalLegTarget &other)
Convenience function to mirror leg settings about the XZ plane from one HalLegTarget object to another.
void copyPose (const HalLegTarget &other)
Convenience function to copy pose settings from one HalLegTarget object to another.
void mirrorPose (const HalLegTarget &other)
Convenience function to mirror pose settings about the XZ plane from one HalLegTarget object to another.
bool hasSamePose (const HalLegTarget &other)
Tests if this HalLegTarget object has the same pose settings as the other HalLegTarget object.
bool hasSameMirroredPose (const HalLegTarget &other)
Tests if this HalLegTarget object has the same mirrored pose settings as the other HalLegTarget object.
void setLegStiffnessMax ()
Convenience function to set the stiffness of all the leg's joints to the maximum (1.0f).
void setLegStiffnessNormal ()
Convenience function to set the stiffness of all the leg's joints to what Aldebaran considers 'normal' (0.6f).
void setLegStiffness (float stiffness)
Convenience function to set uniform stiffness on all leg joints to a custom value.
void setLegStiffnessOff ()
Convenience function to turn off stiffness in all the leg's joints (0.0f).
void copyStiffness (const HalLegTarget &other)
Convenience function to copy stiffness settings from one HalLegTarget object to another.
bool hasSameStiffness (const HalLegTarget &other)
Tests if this HalLegTarget object has the same stiffness settings as the other HalLegTarget object.
void setLegActive ()
Set leg to be Active (DEDAULT DCM state) The leg is active and manual movements will be resisted, be careful when the stiffness is set high.
void setLegPassive ()
Set leg to be Passive Manually moving the leg causes the leg to stay in the new position.
void setLegPliability (bool hipyawpitch, bool hiproll, bool hippitch, bool kneepitch, bool anklepitch, bool ankleroll)
Individually set the active/passive state of each joint.
bool isLegPassive ()
Are any of the leg's joints set to passive.
bool isLegAllPassive ()
Are all of the legs's joints set to passive.
bool isLegAllActive ()
Are all of the leg's joints set to active.
void set_hipyawpitch_DEG (float setting)
Movement Setters (Degrees)
void set_hiproll_DEG (float setting)
void set_hippitch_DEG (float setting)
void set_kneepitch_DEG (float setting)
void set_anklepitch_DEG (float setting)
void set_ankleroll_DEG (float setting)
void set_hipyawpitch_RAD (float setting)
Movement Setters (Radians)
void set_hiproll_RAD (float setting)
void set_hippitch_RAD (float setting)
void set_kneepitch_RAD (float setting)
void set_anklepitch_RAD (float setting)
void set_ankleroll_RAD (float setting)
void set_hipyawpitchstiffness (float setting)
Stiffness Setters.
void set_hiprollstiffness (float setting)
void set_hippitchstiffness (float setting)
void set_kneepitchstiffness (float setting)
void set_anklepitchstiffness (float setting)
void set_anklerollstiffness (float setting)
float get_hipyawpitch_DEG ()
Movement Getters (Degrees)
float get_hiproll_DEG ()
float get_hippitch_DEG ()
float get_kneepitch_DEG ()
float get_anklepitch_DEG ()
float get_ankleroll_DEG ()
float get_hipyawpitch_RAD ()
Movement Getters (Radians)
float get_hiproll_RAD ()
float get_hippitch_RAD ()
float get_kneepitch_RAD ()
float get_anklepitch_RAD ()
float get_ankleroll_RAD ()
float get_hipyawpitchstiffness ()
Stiffness Getters.
float get_hiprollstiffness ()
float get_hippitchstiffness ()
float get_kneepitchstiffness ()
float get_anklepitchstiffness ()
float get_anklerollstiffness ()
Public Member Functions inherited from wb_hal_legtarget
PROPERTY (int32_t, target_movement_time) PROPERTY(int16_t
Control Message: The elapsed time, in mSec, in which the movement should be completed.
target_hipyawpitch PROPERTY (int16_t, target_hiproll) PROPERTY(int16_t
target hip roll angle angle in 10ths of degrees
target_hipyawpitch target_hippitch PROPERTY (int16_t, target_kneepitch) PROPERTY(int16_t
target knee pitch angle in 10ths of degrees
target_hipyawpitch target_hippitch target_anklepitch PROPERTY (int16_t, target_ankleroll) PROPERTY(uint8_t
target ankle roll angle in 10ths of degrees
target_hipyawpitch target_hippitch target_anklepitch target_leg PROPERTY (uint8_t, target_hipyawpitchstiffness) PROPERTY(uint8_t
target hip yaw pitch stiffness as a percentage
target_hipyawpitch target_hippitch target_anklepitch target_leg target_hiprollstiffness PROPERTY (uint8_t, target_hippitchstiffness) PROPERTY(uint8_t
target hip pitch stiffness as a percentage
target_hipyawpitch target_hippitch target_anklepitch target_leg target_hiprollstiffness target_kneepitchstiffness PROPERTY (uint8_t, target_anklepitchstiffness) PROPERTY(uint8_t
target ankle pitch stiffness as a percentage
target_hipyawpitch target_hippitch target_anklepitch target_leg target_hiprollstiffness target_kneepitchstiffness target_anklerollstiffness PROPERTY (uint8_t, target_pliability) BIT_PROPERTY(target_hipyawpitch_active) BIT_PROPERTY(target_hiproll_active) BIT_PROPERTY(target_hippitch_active) BIT_PROPERTY(target_kneepitch_active) BIT_PROPERTY(target_anklepitch_active) BIT_PROPERTY(target_ankleroll_active) BIT_PROPERTY(target_leg_at_goal) BIT_PROPERTY(target_leg_stop) wb_hal_legtarget(uint8_t leg=0
target leg's pliability when in Passive Mode When the leg is passive, this value reduces the update frequency, thus making the leg more resistant to external forces.
Additional Inherited Members
Public Attributes inherited from wb_hal_legtarget
target_hipyawpitch target_hippitch target_anklepitch target_leg target_hiprollstiffness target_kneepitchstiffness target_anklerollstiffness int16_t hipyawpitch = 0
target_hipyawpitch target_hippitch target_anklepitch target_leg target_hiprollstiffness target_kneepitchstiffness target_anklerollstiffness int16_t int16_t hiproll = 0
target_hipyawpitch target_hippitch target_anklepitch target_leg target_hiprollstiffness target_kneepitchstiffness target_anklerollstiffness int16_t int16_t int16_t hippitch = 0
target_hipyawpitch target_hippitch target_anklepitch target_leg target_hiprollstiffness target_kneepitchstiffness target_anklerollstiffness int16_t int16_t int16_t int16_t kneepitch = 0
target_hipyawpitch target_hippitch target_anklepitch target_leg target_hiprollstiffness target_kneepitchstiffness target_anklerollstiffness int16_t int16_t int16_t int16_t int16_t anklepitch = 0
target_hipyawpitch target_hippitch target_anklepitch target_leg target_hiprollstiffness target_kneepitchstiffness target_anklerollstiffness int16_t int16_t int16_t int16_t int16_t int16_t ankleroll = 0
target_hipyawpitch target_hippitch target_anklepitch target_leg target_hiprollstiffness target_kneepitchstiffness target_anklerollstiffness int16_t int16_t int16_t int16_t int16_t int16_t uint8_t hipyawpitchstiffness = 0
target_hipyawpitch target_hippitch target_anklepitch target_leg target_hiprollstiffness target_kneepitchstiffness target_anklerollstiffness int16_t int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t hiprollstiffness = 0
target_hipyawpitch target_hippitch target_anklepitch target_leg target_hiprollstiffness target_kneepitchstiffness target_anklerollstiffness int16_t int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t hippitchstiffness = 0
target_hipyawpitch target_hippitch target_anklepitch target_leg target_hiprollstiffness target_kneepitchstiffness target_anklerollstiffness int16_t int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t kneepitchstiffness = 0
target_hipyawpitch target_hippitch target_anklepitch target_leg target_hiprollstiffness target_kneepitchstiffness target_anklerollstiffness int16_t int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t uint8_t anklepitchstiffness = 0
target_hipyawpitch target_hippitch target_anklepitch target_leg target_hiprollstiffness target_kneepitchstiffness target_anklerollstiffness int16_t int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t anklerollstiffness = 0
target_hipyawpitch target_hippitch target_anklepitch target_leg target_hiprollstiffness target_kneepitchstiffness target_anklerollstiffness int16_t int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t bool hipyawpitch_active = true
target_hipyawpitch target_hippitch target_anklepitch target_leg target_hiprollstiffness target_kneepitchstiffness target_anklerollstiffness int16_t int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t bool bool hiproll_active = true
target_hipyawpitch target_hippitch target_anklepitch target_leg target_hiprollstiffness target_kneepitchstiffness target_anklerollstiffness int16_t int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t bool bool bool hippitch_active = true
target_hipyawpitch target_hippitch target_anklepitch target_leg target_hiprollstiffness target_kneepitchstiffness target_anklerollstiffness int16_t int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t bool bool bool bool kneepitch_active = true
target_hipyawpitch target_hippitch target_anklepitch target_leg target_hiprollstiffness target_kneepitchstiffness target_anklerollstiffness int16_t int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t bool bool bool bool bool anklepitch_active = true
target_hipyawpitch target_hippitch target_anklepitch target_leg target_hiprollstiffness target_kneepitchstiffness target_anklerollstiffness int16_t int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t bool bool bool bool bool bool ankleroll_active = true
target_hipyawpitch target_hippitch target_anklepitch target_leg target_hiprollstiffness target_kneepitchstiffness target_anklerollstiffness int16_t int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t bool bool bool bool bool bool int32_t movement_time = INT_MAX
target_hipyawpitch target_hippitch target_anklepitch target_leg target_hiprollstiffness target_kneepitchstiffness target_anklerollstiffness int16_t int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t bool bool bool bool bool bool int32_t uint8_t pliability = 0
target_hipyawpitch target_hippitch target_anklepitch target_leg target_hiprollstiffness target_kneepitchstiffness target_anklerollstiffness int16_t int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t bool bool bool bool bool bool int32_t uint8_t bool leg_at_goal = false
Public Attributes inherited from wb_hal_leg_target
int32_t target_movement_time
Control Message: The elapsed time, in mSec, in which the movement should be completed.
int16_t target_hipyawpitch
target hip yaw pitch angle in 10ths of degrees
int16_t target_hiproll
target hip roll angle angle in 10ths of degrees
int16_t target_hippitch
target hip pitch angle in 10ths of degrees
int16_t target_kneepitch
target knee pitch angle in 10ths of degrees
int16_t target_anklepitch
target ankle pitch angle in 10ths of degrees
int16_t target_ankleroll
target ankle roll angle in 10ths of degrees
uint8_t target_leg
target leg number; This property is used strictly for accounting purposes when the struct is stored within an array and the robot has numerous legs.
uint8_t target_hipyawpitchstiffness
target hip yaw pitch stiffness as a percentage
uint8_t target_hiprollstiffness
target hip roll stiffness as a percentage
uint8_t target_hippitchstiffness
target hip pitch stiffness as a percentage
uint8_t target_kneepitchstiffness
target knee pitch stiffness as a percentage
uint8_t target_anklepitchstiffness
target ankle pitch stiffness as a percentage
uint8_t target_anklerollstiffness
target ankle roll stiffness as a percentage
uint8_t target_pliability
target leg's pliability when in Passive Mode; When the leg is passive, this value reduces the update frequency, thus making the leg more resistant to external forces.
unsigned int target_hipyawpitch_active: 1
Is the hipyawpitch Active (true[DEFAULT]) or Passive (false).
unsigned int target_hiproll_active: 1
Is the hip roll Active (true[DEFAULT]) or Passive (false)
unsigned int target_hippitch_active: 1
Is the hip pitch Active (true[DEFAULT]) or Passive (false)
unsigned int target_kneepitch_active: 1
Is the knee pitch Active (true[DEFAULT]) or Passive (false)
unsigned int target_anklepitch_active: 1
Is the ankle pitch Active (true[DEFAULT]) or Passive (false)
unsigned int target_ankleroll_active: 1
Is the ankle roll Active (true[DEFAULT]) or Passive (false)
unsigned int target_leg_at_goal: 1
Control Message: Not used.
unsigned int target_leg_stop: 1
Control Message: Stop the leg at its current location.
Detailed Description
Class for moving a SINGLE robotic leg with up to 6 degrees of freedom using local coords of each joint.
Provides a C++ wrapper around wb_hal_leg_target.
NAO Leg has upto 6 degrees of freedom with the axes being: 'hipyawpitch, hip roll, hip pitch, knee pitch, ankle pitch, ankle roll'. The left and right legs are mirrored about the XZ plane as are (most of) the movement limits and ranges. (Aldebaran Docs ./family/robots/links_robot.html)
Move the robotic leg to the (local) coord provided in this class.
Examples
Examples of what to do with the class
Move (left) leg such that the thigh is almost parallel to the ground pointing directly in front of the robot,
and the knee is bent right angle with the foot horizontal in the pitch and roll axis, in one second.
myLegTarget = new HalLegTarget(LEFT_LEG);
myLegTarget.GoToWithTime_Deg(0, 0, -88, 90, 0, 0, 1000);
HalLegTarget().GoToWithTime_Rad(...) provides a method to control the leg using radian based units.
HalLegTarget().setLegActive();   // Puts the leg into active mode, Naoqi DCM default.
HalLegTarget().setLegPassive();  // Puts the leg into passive mode, allowing the leg to be manupulated by external forces.
Class values need to be passed to the Whiteboard, using the handler, for them to take effect.
HalLegTarget_t.set(HalLegTarget());
HalLegTarget_t.set(HalLegTarget().setLegPassive());
Definition at line 54 of file HAL_LegTarget.hpp.
Constructor & Destructor Documentation
HalLegTarget() [1/6]
guWhiteboard::HalLegTarget::HalLegTarget (const uint8_t & target_leg = 0, const float hipyawpitch = 0, const float hiproll = 0, const float hippitch = 0, const float kneepitch = 0, const float anklepitch = 0, const float ankleroll = 0, const float hipyawpitchstiffness = 0, const float hiprollstiffness = 0, const float hippitchstiffness = 0, const float kneepitchstiffness = 0, const float anklepitchstiffness = 0, const float anklerollstiffness = 0, const bool hipyawpitch_active = true, const bool hiproll_active = true, const bool hippitch_active = true, const bool kneepitch_active = true, const bool anklepitch_active = true, const bool ankleroll_active = true, const int32_t movement_time = 1000000, const uint8_t pliability = 10, const bool leg_stop = false, const bool inRadians = false) inline
Constructor, defaults to LEFT_LEG.
Constructor using float parameters This constructor should be used because the whiteboard holds integer representations of the angles.
Definition at line 69 of file HAL_LegTarget.hpp.
References wb_hal_legtarget::anklepitch, wb_hal_legtarget::anklepitch_active, wb_hal_legtarget::anklepitchstiffness, wb_hal_legtarget::ankleroll, wb_hal_legtarget::ankleroll_active, wb_hal_legtarget::anklerollstiffness, wb_hal_legtarget::hippitch, wb_hal_legtarget::hippitch_active, wb_hal_legtarget::hippitchstiffness, wb_hal_legtarget::hiproll, wb_hal_legtarget::hiproll_active, wb_hal_legtarget::hiprollstiffness, wb_hal_legtarget::hipyawpitch, wb_hal_legtarget::hipyawpitch_active, wb_hal_legtarget::hipyawpitchstiffness, wb_hal_legtarget::kneepitch, wb_hal_legtarget::kneepitch_active, wb_hal_legtarget::kneepitchstiffness, wb_hal_legtarget::movement_time, wb_hal_legtarget::pliability, set_anklepitchstiffness(), set_anklerollstiffness(), set_hippitchstiffness(), set_hiprollstiffness(), set_hipyawpitchstiffness(), set_kneepitchstiffness(), set_target_leg_stop(), set_target_movement_time(), set_target_pliability(), setLegPliability(), setPose_Deg(), and setPose_Rad().
Referenced by operator==().
HalLegTarget() [2/6]
guWhiteboard::HalLegTarget::HalLegTarget (const std::string & str) inline
String constructor (NYI)
Parameters
str the string to parse and use to recreate the this object
Definition at line 826 of file HAL_LegTarget.hpp.
References from_string().
HalLegTarget() [3/6]
guWhiteboard::HalLegTarget::HalLegTarget (int32_t t_target_movement_time = INT_MAX, int16_t t_target_hipyawpitch = 0, int16_t t_target_hiproll = 0, int16_t t_target_hippitch = 0, int16_t t_target_kneepitch = 0, int16_t t_target_anklepitch = 0, int16_t t_target_ankleroll = 0, uint8_t t_target_leg = (static_cast<uint8_t>(0)), uint8_t t_target_hipyawpitchstiffness = 0, uint8_t t_target_hiprollstiffness = 0, uint8_t t_target_hippitchstiffness = 0, uint8_t t_target_kneepitchstiffness = 0, uint8_t t_target_anklepitchstiffness = 0, uint8_t t_target_anklerollstiffness = 0, uint8_t t_target_pliability = 0, unsigned int t_target_hipyawpitch_active = true, unsigned int t_target_hiproll_active = true, unsigned int t_target_hippitch_active = true, unsigned int t_target_kneepitch_active = true, unsigned int t_target_anklepitch_active = true, unsigned int t_target_ankleroll_active = true, unsigned int t_target_leg_at_goal = false, unsigned int t_target_leg_stop = false) inline
Create a new HalLegTarget.
Definition at line 121 of file HalLegTarget.hpp.
HalLegTarget() [4/6]
guWhiteboard::HalLegTarget::HalLegTarget (const HalLegTarget & t_other) inline
Copy Constructor.
Definition at line 128 of file HalLegTarget.hpp.
HalLegTarget() [5/6]
guWhiteboard::HalLegTarget::HalLegTarget (const struct wb_hal_leg_target & t_other) inline
Copy Constructor.
Definition at line 135 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_anklepitch, wb_hal_leg_target::target_anklepitch_active, wb_hal_leg_target::target_anklepitchstiffness, wb_hal_leg_target::target_ankleroll, wb_hal_leg_target::target_ankleroll_active, wb_hal_leg_target::target_anklerollstiffness, wb_hal_leg_target::target_hippitch, wb_hal_leg_target::target_hippitch_active, wb_hal_leg_target::target_hippitchstiffness, wb_hal_leg_target::target_hiproll, wb_hal_leg_target::target_hiproll_active, wb_hal_leg_target::target_hiprollstiffness, wb_hal_leg_target::target_hipyawpitch, wb_hal_leg_target::target_hipyawpitch_active, wb_hal_leg_target::target_hipyawpitchstiffness, wb_hal_leg_target::target_kneepitch, wb_hal_leg_target::target_kneepitch_active, wb_hal_leg_target::target_kneepitchstiffness, wb_hal_leg_target::target_leg, wb_hal_leg_target::target_leg_at_goal, wb_hal_leg_target::target_leg_stop, wb_hal_leg_target::target_movement_time, and wb_hal_leg_target::target_pliability.
HalLegTarget() [6/6]
guWhiteboard::HalLegTarget::HalLegTarget (const std::string & t_str) inline
String Constructor.
Definition at line 506 of file HalLegTarget.hpp.
References from_string().
Member Function Documentation
atGoal() [1/2]
bool guWhiteboard::HalLegTarget::atGoal () inline
Leg at Goal Getter Clients/Machines should use this getter to test if the DCM has reported that the leg has reached its goal pose.
Is the leg at the goal pose? gunaoqiinterface sets this true when the leg reaches the goal pose asked for in the previous control message.
Returns
bool whether the leg is at the goal location or not.
Definition at line 231 of file HAL_LegTarget.hpp.
References target_leg_at_goal().
atGoal() [2/2]
bool guWhiteboard::HalLegTarget::atGoal () inline
Leg at Goal Getter Clients/Machines should use this getter to test if the DCM has reported that the leg has reached its goal pose.
Is the leg at the goal pose? gunaoqiinterface sets this true when the leg reaches the goal pose asked for in the previous control message.
Returns
bool whether the leg is at the goal location or not.
Definition at line 1029 of file HalLegTarget.hpp.
References target_leg_at_goal().
atTargetLocation() [1/2]
bool guWhiteboard::HalLegTarget::atTargetLocation (HalLegTarget status, HalLegTarget tolerance) inline
Client side test to determine if leg is at the target location, allowing for specified tolerances.
The method tests if the pose 'status' is within 'tolerance' of 'this' target location, allowing for a specified tolerance.
'this' object contains the target pose settings.
Parameters
status HalLegTarget object which contains actual pose settings reported by the robot's sensors.
tolerance HalLegTarget object whose pose settings specify the tolerance for each joint
Returns
bool whether or not the status is within range of the target location.
Definition at line 248 of file HAL_LegTarget.hpp.
References target_anklepitch(), target_ankleroll(), target_hippitch(), target_hiproll(), target_hipyawpitch(), and target_kneepitch().
atTargetLocation() [2/2]
bool guWhiteboard::HalLegTarget::atTargetLocation (HalLegTarget status, HalLegTarget tolerance) inline
Client side test to determine if leg is at the target location, allowing for specified tolerances.
The method tests if the pose 'status' is within 'tolerance' of 'this' target location, allowing for a specified tolerance.
'this' object contains the target pose settings.
Parameters
status HalLegTarget object which contains actual pose settings reported by the robot's sensors.
tolerance HalLegTarget object whose pose settings specify the tolerance for each joint
Returns
bool whether or not the status is within range of the target location.
Definition at line 1046 of file HalLegTarget.hpp.
References target_anklepitch(), target_ankleroll(), target_hippitch(), target_hiproll(), target_hipyawpitch(), and target_kneepitch().
copyPose() [1/2]
void guWhiteboard::HalLegTarget::copyPose (const HalLegTarget & other) inline
Convenience function to copy pose settings from one HalLegTarget object to another.
Parameters
other HalLegTarget object from which to copy pose settings from.
Definition at line 359 of file HAL_LegTarget.hpp.
References set_target_anklepitch(), set_target_ankleroll(), set_target_hippitch(), set_target_hiproll(), set_target_hipyawpitch(), set_target_kneepitch(), target_anklepitch(), target_ankleroll(), target_hippitch(), target_hiproll(), target_hipyawpitch(), and target_kneepitch().
copyPose() [2/2]
void guWhiteboard::HalLegTarget::copyPose (const HalLegTarget & other) inline
Convenience function to copy pose settings from one HalLegTarget object to another.
Parameters
other HalLegTarget object from which to copy pose settings from.
Definition at line 1157 of file HalLegTarget.hpp.
References set_target_anklepitch(), set_target_ankleroll(), set_target_hippitch(), set_target_hiproll(), set_target_hipyawpitch(), and set_target_kneepitch().
copyStiffness() [1/2]
void guWhiteboard::HalLegTarget::copyStiffness (const HalLegTarget & other) inline
Convenience function to copy stiffness settings from one HalLegTarget object to another.
Parameters
other HalLegTarget object from which to copy stiffness settings.
Definition at line 508 of file HAL_LegTarget.hpp.
References target_anklepitchstiffness(), target_anklerollstiffness(), target_hippitchstiffness(), target_hiprollstiffness(), target_hipyawpitchstiffness(), and target_kneepitchstiffness().
copyStiffness() [2/2]
void guWhiteboard::HalLegTarget::copyStiffness (const HalLegTarget & other) inline
Convenience function to copy stiffness settings from one HalLegTarget object to another.
Parameters
other HalLegTarget object from which to copy stiffness settings.
Definition at line 1306 of file HalLegTarget.hpp.
References set_target_anklepitchstiffness(), set_target_anklerollstiffness(), set_target_hippitchstiffness(), set_target_hiprollstiffness(), set_target_hipyawpitchstiffness(), and set_target_kneepitchstiffness().
description() [1/2]
std::string guWhiteboard::HalLegTarget::description () inline
USE_WB_HAL_LEG_TARGET_C_CONVERSION
Definition at line 511 of file HalLegTarget.hpp.
References HAL_LEG_TARGET_DESC_BUFFER_SIZE, target_anklepitch(), target_anklepitch_active(), target_anklepitchstiffness(), target_ankleroll(), target_ankleroll_active(), target_anklerollstiffness(), target_hippitch(), target_hippitch_active(), target_hippitchstiffness(), target_hiproll(), target_hiproll_active(), target_hiprollstiffness(), target_hipyawpitch(), target_hipyawpitch_active(), target_hipyawpitchstiffness(), target_kneepitch(), target_kneepitch_active(), target_kneepitchstiffness(), target_leg(), target_leg_at_goal(), target_leg_stop(), target_movement_time(), target_pliability(), and wb_hal_leg_target_description().
description() [2/2]
std::string guWhiteboard::HalLegTarget::description () const inline
Description function.
Definition at line 792 of file HAL_LegTarget.hpp.
References target_anklepitch(), target_anklepitch_active(), target_anklepitchstiffness(), target_ankleroll(), target_ankleroll_active(), target_anklerollstiffness(), target_hippitch(), target_hippitch_active(), target_hippitchstiffness(), target_hiproll(), target_hiproll_active(), target_hiprollstiffness(), target_hipyawpitch(), target_hipyawpitch_active(), target_hipyawpitchstiffness(), target_kneepitch(), target_kneepitch_active(), target_kneepitchstiffness(), target_leg_at_goal(), target_leg_stop(), target_movement_time(), and target_pliability().
from_string() [1/2]
void guWhiteboard::HalLegTarget::from_string (const std::string & str) inline
Parser for recreating this class (NYI)
Parameters
str the string to parse and use to recreate the this object
Definition at line 832 of file HAL_LegTarget.hpp.
Referenced by HalLegTarget().
from_string() [2/2]
void guWhiteboard::HalLegTarget::from_string (const std::string & t_str) inline
USE_WB_HAL_LEG_TARGET_C_CONVERSION
Definition at line 629 of file HalLegTarget.hpp.
References HAL_LEG_TARGET_DESC_BUFFER_SIZE, set_target_anklepitch(), set_target_anklepitch_active(), set_target_anklepitchstiffness(), set_target_ankleroll(), set_target_ankleroll_active(), set_target_anklerollstiffness(), set_target_hippitch(), set_target_hippitch_active(), set_target_hippitchstiffness(), set_target_hiproll(), set_target_hiproll_active(), set_target_hiprollstiffness(), set_target_hipyawpitch(), set_target_hipyawpitch_active(), set_target_hipyawpitchstiffness(), set_target_kneepitch(), set_target_kneepitch_active(), set_target_kneepitchstiffness(), set_target_leg(), set_target_leg_at_goal(), set_target_leg_stop(), set_target_movement_time(), and set_target_pliability().
get_anklepitch_DEG() [1/2]
float guWhiteboard::HalLegTarget::get_anklepitch_DEG () inline
Definition at line 728 of file HAL_LegTarget.hpp.
References target_anklepitch().
get_anklepitch_DEG() [2/2]
float guWhiteboard::HalLegTarget::get_anklepitch_DEG () inline
Definition at line 1526 of file HalLegTarget.hpp.
References target_anklepitch().
get_anklepitch_RAD() [1/2]
float guWhiteboard::HalLegTarget::get_anklepitch_RAD () inline
Definition at line 754 of file HAL_LegTarget.hpp.
References target_anklepitch().
get_anklepitch_RAD() [2/2]
float guWhiteboard::HalLegTarget::get_anklepitch_RAD () inline
Definition at line 1552 of file HalLegTarget.hpp.
References target_anklepitch().
get_anklepitchstiffness() [1/2]
float guWhiteboard::HalLegTarget::get_anklepitchstiffness () inline
Definition at line 779 of file HAL_LegTarget.hpp.
References target_anklepitchstiffness().
get_anklepitchstiffness() [2/2]
float guWhiteboard::HalLegTarget::get_anklepitchstiffness () inline
Definition at line 1577 of file HalLegTarget.hpp.
References target_anklepitchstiffness().
get_ankleroll_DEG() [1/2]
float guWhiteboard::HalLegTarget::get_ankleroll_DEG () inline
Definition at line 732 of file HAL_LegTarget.hpp.
References target_ankleroll().
get_ankleroll_DEG() [2/2]
float guWhiteboard::HalLegTarget::get_ankleroll_DEG () inline
Definition at line 1530 of file HalLegTarget.hpp.
References target_ankleroll().
get_ankleroll_RAD() [1/2]
float guWhiteboard::HalLegTarget::get_ankleroll_RAD () inline
Definition at line 758 of file HAL_LegTarget.hpp.
References target_ankleroll().
get_ankleroll_RAD() [2/2]
float guWhiteboard::HalLegTarget::get_ankleroll_RAD () inline
Definition at line 1556 of file HalLegTarget.hpp.
References target_ankleroll().
get_anklerollstiffness() [1/2]
float guWhiteboard::HalLegTarget::get_anklerollstiffness () inline
Definition at line 783 of file HAL_LegTarget.hpp.
References target_anklerollstiffness().
get_anklerollstiffness() [2/2]
float guWhiteboard::HalLegTarget::get_anklerollstiffness () inline
Definition at line 1581 of file HalLegTarget.hpp.
References target_anklerollstiffness().
get_hippitch_DEG() [1/2]
float guWhiteboard::HalLegTarget::get_hippitch_DEG () inline
Definition at line 720 of file HAL_LegTarget.hpp.
References target_hippitch().
get_hippitch_DEG() [2/2]
float guWhiteboard::HalLegTarget::get_hippitch_DEG () inline
Definition at line 1518 of file HalLegTarget.hpp.
References target_hippitch().
get_hippitch_RAD() [1/2]
float guWhiteboard::HalLegTarget::get_hippitch_RAD () inline
Definition at line 746 of file HAL_LegTarget.hpp.
References target_hippitch().
get_hippitch_RAD() [2/2]
float guWhiteboard::HalLegTarget::get_hippitch_RAD () inline
Definition at line 1544 of file HalLegTarget.hpp.
References target_hippitch().
get_hippitchstiffness() [1/2]
float guWhiteboard::HalLegTarget::get_hippitchstiffness () inline
Definition at line 771 of file HAL_LegTarget.hpp.
References target_hippitchstiffness().
get_hippitchstiffness() [2/2]
float guWhiteboard::HalLegTarget::get_hippitchstiffness () inline
Definition at line 1569 of file HalLegTarget.hpp.
References target_hippitchstiffness().
get_hiproll_DEG() [1/2]
float guWhiteboard::HalLegTarget::get_hiproll_DEG () inline
Definition at line 716 of file HAL_LegTarget.hpp.
References target_hiproll().
get_hiproll_DEG() [2/2]
float guWhiteboard::HalLegTarget::get_hiproll_DEG () inline
Definition at line 1514 of file HalLegTarget.hpp.
References target_hiproll().
get_hiproll_RAD() [1/2]
float guWhiteboard::HalLegTarget::get_hiproll_RAD () inline
Definition at line 742 of file HAL_LegTarget.hpp.
References target_hiproll().
get_hiproll_RAD() [2/2]
float guWhiteboard::HalLegTarget::get_hiproll_RAD () inline
Definition at line 1540 of file HalLegTarget.hpp.
References target_hiproll().
get_hiprollstiffness() [1/2]
float guWhiteboard::HalLegTarget::get_hiprollstiffness () inline
Definition at line 767 of file HAL_LegTarget.hpp.
References target_hiprollstiffness().
get_hiprollstiffness() [2/2]
float guWhiteboard::HalLegTarget::get_hiprollstiffness () inline
Definition at line 1565 of file HalLegTarget.hpp.
References target_hiprollstiffness().
get_hipyawpitch_DEG() [1/2]
float guWhiteboard::HalLegTarget::get_hipyawpitch_DEG () inline
Movement Getters (Degrees)
Definition at line 712 of file HAL_LegTarget.hpp.
References target_hipyawpitch().
get_hipyawpitch_DEG() [2/2]
float guWhiteboard::HalLegTarget::get_hipyawpitch_DEG () inline
Movement Getters (Degrees)
Definition at line 1510 of file HalLegTarget.hpp.
References target_hipyawpitch().
get_hipyawpitch_RAD() [1/2]
float guWhiteboard::HalLegTarget::get_hipyawpitch_RAD () inline
Movement Getters (Radians)
Definition at line 738 of file HAL_LegTarget.hpp.
References target_hipyawpitch().
get_hipyawpitch_RAD() [2/2]
float guWhiteboard::HalLegTarget::get_hipyawpitch_RAD () inline
Movement Getters (Radians)
Definition at line 1536 of file HalLegTarget.hpp.
References target_hipyawpitch().
get_hipyawpitchstiffness() [1/2]
float guWhiteboard::HalLegTarget::get_hipyawpitchstiffness () inline
Stiffness Getters.
Definition at line 763 of file HAL_LegTarget.hpp.
References target_hipyawpitchstiffness().
get_hipyawpitchstiffness() [2/2]
float guWhiteboard::HalLegTarget::get_hipyawpitchstiffness () inline
Stiffness Getters.
Definition at line 1561 of file HalLegTarget.hpp.
References target_hipyawpitchstiffness().
get_kneepitch_DEG() [1/2]
float guWhiteboard::HalLegTarget::get_kneepitch_DEG () inline
Definition at line 724 of file HAL_LegTarget.hpp.
References target_kneepitch().
get_kneepitch_DEG() [2/2]
float guWhiteboard::HalLegTarget::get_kneepitch_DEG () inline
Definition at line 1522 of file HalLegTarget.hpp.
References target_kneepitch().
get_kneepitch_RAD() [1/2]
float guWhiteboard::HalLegTarget::get_kneepitch_RAD () inline
Definition at line 750 of file HAL_LegTarget.hpp.
References target_kneepitch().
get_kneepitch_RAD() [2/2]
float guWhiteboard::HalLegTarget::get_kneepitch_RAD () inline
Definition at line 1548 of file HalLegTarget.hpp.
References target_kneepitch().
get_kneepitchstiffness() [1/2]
float guWhiteboard::HalLegTarget::get_kneepitchstiffness () inline
Definition at line 775 of file HAL_LegTarget.hpp.
References target_kneepitchstiffness().
get_kneepitchstiffness() [2/2]
float guWhiteboard::HalLegTarget::get_kneepitchstiffness () inline
Definition at line 1573 of file HalLegTarget.hpp.
References target_kneepitchstiffness().
goToWithTime_Deg() [1/2]
void guWhiteboard::HalLegTarget::goToWithTime_Deg (float hipyawpitch, float hiproll, float hippitch, float kneepitch, float anklepitch, float ankleroll, int32_t time = INT_MAX) inline
move to position in degrees over a given time
Parameters
hipyawpitch down to up
hiproll out to in
hippitch swing thigh forward/back
kneepitch swig calf out/back
anklepitch raise/lower toes
ankleroll roll ankle out to in
time elapsed time in mSec for the motion to complete.
Definition at line 169 of file HAL_LegTarget.hpp.
References wb_hal_legtarget::anklepitch, wb_hal_legtarget::ankleroll, wb_hal_legtarget::hippitch, wb_hal_legtarget::hiproll, wb_hal_legtarget::hipyawpitch, wb_hal_legtarget::kneepitch, set_target_movement_time(), and setPose_Deg().
goToWithTime_Deg() [2/2]
void guWhiteboard::HalLegTarget::goToWithTime_Deg (float hipyawpitch, float hiproll, float hippitch, float kneepitch, float anklepitch, float ankleroll, int32_t time = INT_MAX) inline
move to position in degrees over a given time
Parameters
hipyawpitch down to up
hiproll out to in
hippitch swing thigh forward/back
kneepitch swig calf out/back
anklepitch raise/lower toes
ankleroll roll ankle out to in
time elapsed time in mSec for the motion to complete.
Definition at line 967 of file HalLegTarget.hpp.
References wb_hal_legtarget::anklepitch, wb_hal_legtarget::ankleroll, wb_hal_legtarget::hippitch, wb_hal_legtarget::hiproll, wb_hal_legtarget::hipyawpitch, wb_hal_legtarget::kneepitch, set_target_movement_time(), and setPose_Deg().
goToWithTime_Rad() [1/2]
void guWhiteboard::HalLegTarget::goToWithTime_Rad (float hipyawpitch, float hiproll, float hippitch, float kneepitch, float anklepitch, float ankleroll, int32_t time = INT_MAX) inline
move to position in radians over a given time
Parameters
hipyawpitch down to up
hiproll out to in
hippitch swing thigh forward/back
kneepitch swig calf out/back
anklepitch raise/lower toes
ankleroll roll ankle out to in
time elapsed time in mSec for the motion to complete.
Definition at line 144 of file HAL_LegTarget.hpp.
References wb_hal_legtarget::anklepitch, wb_hal_legtarget::ankleroll, wb_hal_legtarget::hippitch, wb_hal_legtarget::hiproll, wb_hal_legtarget::hipyawpitch, wb_hal_legtarget::kneepitch, set_target_movement_time(), and setPose_Rad().
goToWithTime_Rad() [2/2]
void guWhiteboard::HalLegTarget::goToWithTime_Rad (float hipyawpitch, float hiproll, float hippitch, float kneepitch, float anklepitch, float ankleroll, int32_t time = INT_MAX) inline
move to position in radians over a given time
Parameters
hipyawpitch down to up
hiproll out to in
hippitch swing thigh forward/back
kneepitch swig calf out/back
anklepitch raise/lower toes
ankleroll roll ankle out to in
time elapsed time in mSec for the motion to complete.
Definition at line 942 of file HalLegTarget.hpp.
References wb_hal_legtarget::anklepitch, wb_hal_legtarget::ankleroll, wb_hal_legtarget::hippitch, wb_hal_legtarget::hiproll, wb_hal_legtarget::hipyawpitch, wb_hal_legtarget::kneepitch, set_target_movement_time(), and setPose_Rad().
hasSameMirroredPose() [1/2]
bool guWhiteboard::HalLegTarget::hasSameMirroredPose (const HalLegTarget & other) inline
Tests if this HalLegTarget object has the same mirrored pose settings as the other HalLegTarget object.
NOTE this method DOES take into account mirroring about the XZ plane.
Parameters
other HalLegTarget object whose pose settings are being compared.
Returns
bool whether the two objects have the same pose or not.
Definition at line 418 of file HAL_LegTarget.hpp.
References target_anklepitch(), target_ankleroll(), target_hippitch(), target_hiproll(), target_hipyawpitch(), and target_kneepitch().
hasSameMirroredPose() [2/2]
bool guWhiteboard::HalLegTarget::hasSameMirroredPose (const HalLegTarget & other) inline
Tests if this HalLegTarget object has the same mirrored pose settings as the other HalLegTarget object.
NOTE this method DOES take into account mirroring about the XZ plane.
Parameters
other HalLegTarget object whose pose settings are being compared.
Returns
bool whether the two objects have the same pose or not.
Definition at line 1216 of file HalLegTarget.hpp.
References target_anklepitch(), target_ankleroll(), target_hippitch(), target_hiproll(), target_hipyawpitch(), and target_kneepitch().
hasSamePose() [1/2]
bool guWhiteboard::HalLegTarget::hasSamePose (const HalLegTarget & other) inline
Tests if this HalLegTarget object has the same pose settings as the other HalLegTarget object.
NOTE this DOES NOT take into account mirroring about the XZ plane.
Parameters
other HalLegTarget object whose pose settings are being compared.
Returns
bool whether the two objects have the same pose or not.
Definition at line 394 of file HAL_LegTarget.hpp.
References target_anklepitch(), target_ankleroll(), target_hippitch(), target_hiproll(), target_hipyawpitch(), and target_kneepitch().
hasSamePose() [2/2]
bool guWhiteboard::HalLegTarget::hasSamePose (const HalLegTarget & other) inline
Tests if this HalLegTarget object has the same pose settings as the other HalLegTarget object.
NOTE this DOES NOT take into account mirroring about the XZ plane.
Parameters
other HalLegTarget object whose pose settings are being compared.
Returns
bool whether the two objects have the same pose or not.
Definition at line 1192 of file HalLegTarget.hpp.
References target_anklepitch(), target_ankleroll(), target_hippitch(), target_hiproll(), target_hipyawpitch(), and target_kneepitch().
hasSameStiffness() [1/2]
bool guWhiteboard::HalLegTarget::hasSameStiffness (const HalLegTarget & other) inline
Tests if this HalLegTarget object has the same stiffness settings as the other HalLegTarget object.
Parameters
other HalLegTarget object whose stiffness settings are being compared.
Returns
bool whether the two objects have the same stiffness or not.
Definition at line 527 of file HAL_LegTarget.hpp.
References target_anklepitchstiffness(), target_anklerollstiffness(), target_hippitchstiffness(), target_hiprollstiffness(), target_hipyawpitchstiffness(), and target_kneepitchstiffness().
hasSameStiffness() [2/2]
bool guWhiteboard::HalLegTarget::hasSameStiffness (const HalLegTarget & other) inline
Tests if this HalLegTarget object has the same stiffness settings as the other HalLegTarget object.
Parameters
other HalLegTarget object whose stiffness settings are being compared.
Returns
bool whether the two objects have the same stiffness or not.
Definition at line 1325 of file HalLegTarget.hpp.
References target_anklepitchstiffness(), target_anklerollstiffness(), target_hippitchstiffness(), target_hiprollstiffness(), target_hipyawpitchstiffness(), and target_kneepitchstiffness().
isAtGoal() [1/2]
void guWhiteboard::HalLegTarget::isAtGoal (bool goalReached) inline
Leg at Goal Setter Clients/Machines should not use this method.
Leg arrived at goal pose. Only set in the status message by gunaoqiinterface when the leg has reached the goal pose.
Parameters
goalReached the leg has reached the goal (true/false)
Definition at line 214 of file HAL_LegTarget.hpp.
References set_target_leg_at_goal().
isAtGoal() [2/2]
void guWhiteboard::HalLegTarget::isAtGoal (bool goalReached) inline
Leg at Goal Setter Clients/Machines should not use this method.
Leg arrived at goal pose. Only set in the status message by gunaoqiinterface when the leg has reached the goal pose.
Parameters
goalReached the leg has reached the goal (true/false)
Definition at line 1012 of file HalLegTarget.hpp.
References set_target_leg_at_goal().
isLegAllActive() [1/2]
bool guWhiteboard::HalLegTarget::isLegAllActive () inline
Are all of the leg's joints set to active.
Definition at line 623 of file HAL_LegTarget.hpp.
References target_anklepitch_active(), target_ankleroll_active(), target_hippitch_active(), target_hiproll_active(), target_hipyawpitch_active(), and target_kneepitch_active().
isLegAllActive() [2/2]
bool guWhiteboard::HalLegTarget::isLegAllActive () inline
Are all of the leg's joints set to active.
Definition at line 1421 of file HalLegTarget.hpp.
References target_anklepitch_active(), target_ankleroll_active(), target_hippitch_active(), target_hiproll_active(), target_hipyawpitch_active(), and target_kneepitch_active().
isLegAllPassive() [1/2]
bool guWhiteboard::HalLegTarget::isLegAllPassive () inline
Are all of the legs's joints set to passive.
Definition at line 615 of file HAL_LegTarget.hpp.
References target_anklepitch_active(), target_ankleroll_active(), target_hippitch_active(), target_hiproll_active(), target_hipyawpitch_active(), and target_kneepitch_active().
isLegAllPassive() [2/2]
bool guWhiteboard::HalLegTarget::isLegAllPassive () inline
Are all of the legs's joints set to passive.
Definition at line 1413 of file HalLegTarget.hpp.
References target_anklepitch_active(), target_ankleroll_active(), target_hippitch_active(), target_hiproll_active(), target_hipyawpitch_active(), and target_kneepitch_active().
isLegPassive() [1/2]
bool guWhiteboard::HalLegTarget::isLegPassive () inline
Are any of the leg's joints set to passive.
Definition at line 607 of file HAL_LegTarget.hpp.
References target_anklepitch_active(), target_ankleroll_active(), target_hippitch_active(), target_hiproll_active(), target_hipyawpitch_active(), and target_kneepitch_active().
isLegPassive() [2/2]
bool guWhiteboard::HalLegTarget::isLegPassive () inline
Are any of the leg's joints set to passive.
Definition at line 1405 of file HalLegTarget.hpp.
References target_anklepitch_active(), target_ankleroll_active(), target_hippitch_active(), target_hiproll_active(), target_hipyawpitch_active(), and target_kneepitch_active().
mirrorLeg() [1/2]
void guWhiteboard::HalLegTarget::mirrorLeg (const HalLegTarget & other) inline
Convenience function to mirror leg settings about the XZ plane from one HalLegTarget object to another.
Parameters
other HalLegTarget object to be mirrored.
Definition at line 328 of file HAL_LegTarget.hpp.
References set_target_anklepitch(), set_target_anklepitch_active(), set_target_anklepitchstiffness(), set_target_ankleroll(), set_target_ankleroll_active(), set_target_anklerollstiffness(), set_target_hippitch(), set_target_hippitch_active(), set_target_hippitchstiffness(), set_target_hiproll(), set_target_hiproll_active(), set_target_hiprollstiffness(), set_target_hipyawpitch(), set_target_hipyawpitch_active(), set_target_hipyawpitchstiffness(), set_target_kneepitch(), set_target_kneepitch_active(), set_target_kneepitchstiffness(), set_target_movement_time(), set_target_pliability(), target_anklepitch(), target_anklepitch_active(), target_anklepitchstiffness(), target_ankleroll(), target_ankleroll_active(), target_anklerollstiffness(), target_hippitch(), target_hippitch_active(), target_hippitchstiffness(), target_hiproll(), target_hiproll_active(), target_hiprollstiffness(), target_hipyawpitch(), target_hipyawpitch_active(), target_hipyawpitchstiffness(), target_kneepitch(), target_kneepitch_active(), target_kneepitchstiffness(), target_movement_time(), and target_pliability().
mirrorLeg() [2/2]
void guWhiteboard::HalLegTarget::mirrorLeg (const HalLegTarget & other) inline
Convenience function to mirror leg settings about the XZ plane from one HalLegTarget object to another.
Parameters
other HalLegTarget object to be mirrored.
Definition at line 1126 of file HalLegTarget.hpp.
References set_target_anklepitch(), set_target_anklepitch_active(), set_target_anklepitchstiffness(), set_target_ankleroll(), set_target_ankleroll_active(), set_target_anklerollstiffness(), set_target_hippitch(), set_target_hippitch_active(), set_target_hippitchstiffness(), set_target_hiproll(), set_target_hiproll_active(), set_target_hiprollstiffness(), set_target_hipyawpitch(), set_target_hipyawpitch_active(), set_target_hipyawpitchstiffness(), set_target_kneepitch(), set_target_kneepitch_active(), set_target_kneepitchstiffness(), set_target_movement_time(), and set_target_pliability().
mirrorPose() [1/2]
void guWhiteboard::HalLegTarget::mirrorPose (const HalLegTarget & other) inline
Convenience function to mirror pose settings about the XZ plane from one HalLegTarget object to another.
Parameters
other HalLegTarget object whose pose settings are to be mirrored.
Definition at line 375 of file HAL_LegTarget.hpp.
References set_target_anklepitch(), set_target_ankleroll(), set_target_hippitch(), set_target_hiproll(), set_target_hipyawpitch(), set_target_kneepitch(), target_anklepitch(), target_ankleroll(), target_hippitch(), target_hiproll(), target_hipyawpitch(), and target_kneepitch().
mirrorPose() [2/2]
void guWhiteboard::HalLegTarget::mirrorPose (const HalLegTarget & other) inline
Convenience function to mirror pose settings about the XZ plane from one HalLegTarget object to another.
Parameters
other HalLegTarget object whose pose settings are to be mirrored.
Definition at line 1173 of file HalLegTarget.hpp.
References set_target_anklepitch(), set_target_ankleroll(), set_target_hippitch(), set_target_hiproll(), set_target_hipyawpitch(), and set_target_kneepitch().
operator!=() [1/2]
bool guWhiteboard::HalLegTarget::operator!= (const HalLegTarget & t_other) const inline
Definition at line 182 of file HalLegTarget.hpp.
operator!=() [2/2]
bool guWhiteboard::HalLegTarget::operator!= (const wb_hal_leg_target & t_other) const inline
Definition at line 192 of file HalLegTarget.hpp.
operator=() [1/2]
HalLegTarget & guWhiteboard::HalLegTarget::operator= (const HalLegTarget & t_other) inline
Copy Assignment Operator.
Definition at line 142 of file HalLegTarget.hpp.
operator=() [2/2]
HalLegTarget & guWhiteboard::HalLegTarget::operator= (const struct wb_hal_leg_target & t_other) inline
Copy Assignment Operator.
Definition at line 150 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_anklepitch, wb_hal_leg_target::target_anklepitch_active, wb_hal_leg_target::target_anklepitchstiffness, wb_hal_leg_target::target_ankleroll, wb_hal_leg_target::target_ankleroll_active, wb_hal_leg_target::target_anklerollstiffness, wb_hal_leg_target::target_hippitch, wb_hal_leg_target::target_hippitch_active, wb_hal_leg_target::target_hippitchstiffness, wb_hal_leg_target::target_hiproll, wb_hal_leg_target::target_hiproll_active, wb_hal_leg_target::target_hiprollstiffness, wb_hal_leg_target::target_hipyawpitch, wb_hal_leg_target::target_hipyawpitch_active, wb_hal_leg_target::target_hipyawpitchstiffness, wb_hal_leg_target::target_kneepitch, wb_hal_leg_target::target_kneepitch_active, wb_hal_leg_target::target_kneepitchstiffness, wb_hal_leg_target::target_leg, wb_hal_leg_target::target_leg_at_goal, wb_hal_leg_target::target_leg_stop, wb_hal_leg_target::target_movement_time, and wb_hal_leg_target::target_pliability.
operator==() [1/2]
bool guWhiteboard::HalLegTarget::operator== (const HalLegTarget & t_other) const inline
Definition at line 155 of file HalLegTarget.hpp.
References target_anklepitch(), target_anklepitch_active(), target_anklepitchstiffness(), target_ankleroll(), target_ankleroll_active(), target_anklerollstiffness(), target_hippitch(), target_hippitch_active(), target_hippitchstiffness(), target_hiproll(), target_hiproll_active(), target_hiprollstiffness(), target_hipyawpitch(), target_hipyawpitch_active(), target_hipyawpitchstiffness(), target_kneepitch(), target_kneepitch_active(), target_kneepitchstiffness(), target_leg(), target_leg_at_goal(), target_leg_stop(), target_movement_time(), and target_pliability().
operator==() [2/2]
bool guWhiteboard::HalLegTarget::operator== (const wb_hal_leg_target & t_other) const inline
Definition at line 187 of file HalLegTarget.hpp.
References HalLegTarget().
ready() [1/2]
void guWhiteboard::HalLegTarget::ready () inline
Set leg to ready state (Default) The leg will act on motion commands.
Definition at line 199 of file HAL_LegTarget.hpp.
References set_target_leg_stop().
ready() [2/2]
void guWhiteboard::HalLegTarget::ready () inline
Set leg to ready state (Default) The leg will act on motion commands.
Definition at line 997 of file HalLegTarget.hpp.
References set_target_leg_stop().
set_anklepitch_DEG() [1/2]
void guWhiteboard::HalLegTarget::set_anklepitch_DEG (float setting) inline
Definition at line 645 of file HAL_LegTarget.hpp.
References set_target_anklepitch().
Referenced by setPose_Deg().
set_anklepitch_DEG() [2/2]
void guWhiteboard::HalLegTarget::set_anklepitch_DEG (float setting) inline
Definition at line 1443 of file HalLegTarget.hpp.
References set_target_anklepitch().
set_anklepitch_RAD() [1/2]
void guWhiteboard::HalLegTarget::set_anklepitch_RAD (float setting) inline
Definition at line 671 of file HAL_LegTarget.hpp.
References set_target_anklepitch().
Referenced by setPose_Rad().
set_anklepitch_RAD() [2/2]
void guWhiteboard::HalLegTarget::set_anklepitch_RAD (float setting) inline
Definition at line 1469 of file HalLegTarget.hpp.
References set_target_anklepitch().
set_anklepitchstiffness() [1/2]
void guWhiteboard::HalLegTarget::set_anklepitchstiffness (float setting) inline
Definition at line 696 of file HAL_LegTarget.hpp.
References set_target_anklepitchstiffness().
Referenced by HalLegTarget(), setLegStiffness(), setLegStiffnessMax(), setLegStiffnessNormal(), and setLegStiffnessOff().
set_anklepitchstiffness() [2/2]
void guWhiteboard::HalLegTarget::set_anklepitchstiffness (float setting) inline
Definition at line 1494 of file HalLegTarget.hpp.
References set_target_anklepitchstiffness().
set_ankleroll_DEG() [1/2]
void guWhiteboard::HalLegTarget::set_ankleroll_DEG (float setting) inline
Definition at line 649 of file HAL_LegTarget.hpp.
References set_target_ankleroll().
Referenced by setPose_Deg().
set_ankleroll_DEG() [2/2]
void guWhiteboard::HalLegTarget::set_ankleroll_DEG (float setting) inline
Definition at line 1447 of file HalLegTarget.hpp.
References set_target_ankleroll().
set_ankleroll_RAD() [1/2]
void guWhiteboard::HalLegTarget::set_ankleroll_RAD (float setting) inline
Definition at line 675 of file HAL_LegTarget.hpp.
References set_target_ankleroll().
Referenced by setPose_Rad().
set_ankleroll_RAD() [2/2]
void guWhiteboard::HalLegTarget::set_ankleroll_RAD (float setting) inline
Definition at line 1473 of file HalLegTarget.hpp.
References set_target_ankleroll().
set_anklerollstiffness() [1/2]
void guWhiteboard::HalLegTarget::set_anklerollstiffness (float setting) inline
Definition at line 700 of file HAL_LegTarget.hpp.
References set_target_anklerollstiffness().
Referenced by HalLegTarget(), setLegStiffness(), setLegStiffnessMax(), setLegStiffnessNormal(), and setLegStiffnessOff().
set_anklerollstiffness() [2/2]
void guWhiteboard::HalLegTarget::set_anklerollstiffness (float setting) inline
Definition at line 1498 of file HalLegTarget.hpp.
References set_target_anklerollstiffness().
set_hippitch_DEG() [1/2]
void guWhiteboard::HalLegTarget::set_hippitch_DEG (float setting) inline
Definition at line 637 of file HAL_LegTarget.hpp.
References set_target_hippitch().
Referenced by setPose_Deg().
set_hippitch_DEG() [2/2]
void guWhiteboard::HalLegTarget::set_hippitch_DEG (float setting) inline
Definition at line 1435 of file HalLegTarget.hpp.
References set_target_hippitch().
set_hippitch_RAD() [1/2]
void guWhiteboard::HalLegTarget::set_hippitch_RAD (float setting) inline
Definition at line 663 of file HAL_LegTarget.hpp.
References set_target_hippitch().
Referenced by setPose_Rad().
set_hippitch_RAD() [2/2]
void guWhiteboard::HalLegTarget::set_hippitch_RAD (float setting) inline
Definition at line 1461 of file HalLegTarget.hpp.
References set_target_hippitch().
set_hippitchstiffness() [1/2]
void guWhiteboard::HalLegTarget::set_hippitchstiffness (float setting) inline
Definition at line 688 of file HAL_LegTarget.hpp.
References set_target_hippitchstiffness().
Referenced by HalLegTarget(), setLegStiffness(), setLegStiffnessMax(), setLegStiffnessNormal(), and setLegStiffnessOff().
set_hippitchstiffness() [2/2]
void guWhiteboard::HalLegTarget::set_hippitchstiffness (float setting) inline
Definition at line 1486 of file HalLegTarget.hpp.
References set_target_hippitchstiffness().
set_hiproll_DEG() [1/2]
void guWhiteboard::HalLegTarget::set_hiproll_DEG (float setting) inline
Definition at line 633 of file HAL_LegTarget.hpp.
References set_target_hiproll().
Referenced by setPose_Deg().
set_hiproll_DEG() [2/2]
void guWhiteboard::HalLegTarget::set_hiproll_DEG (float setting) inline
Definition at line 1431 of file HalLegTarget.hpp.
References set_target_hiproll().
set_hiproll_RAD() [1/2]
void guWhiteboard::HalLegTarget::set_hiproll_RAD (float setting) inline
Definition at line 659 of file HAL_LegTarget.hpp.
References set_target_hiproll().
Referenced by setPose_Rad().
set_hiproll_RAD() [2/2]
void guWhiteboard::HalLegTarget::set_hiproll_RAD (float setting) inline
Definition at line 1457 of file HalLegTarget.hpp.
References set_target_hiproll().
set_hiprollstiffness() [1/2]
void guWhiteboard::HalLegTarget::set_hiprollstiffness (float setting) inline
Definition at line 684 of file HAL_LegTarget.hpp.
References set_target_hiprollstiffness().
Referenced by HalLegTarget(), setLegStiffness(), setLegStiffnessMax(), setLegStiffnessNormal(), and setLegStiffnessOff().
set_hiprollstiffness() [2/2]
void guWhiteboard::HalLegTarget::set_hiprollstiffness (float setting) inline
Definition at line 1482 of file HalLegTarget.hpp.
References set_target_hiprollstiffness().
set_hipyawpitch_DEG() [1/2]
void guWhiteboard::HalLegTarget::set_hipyawpitch_DEG (float setting) inline
Movement Setters (Degrees)
Definition at line 629 of file HAL_LegTarget.hpp.
References set_target_hipyawpitch().
Referenced by setPose_Deg().
set_hipyawpitch_DEG() [2/2]
void guWhiteboard::HalLegTarget::set_hipyawpitch_DEG (float setting) inline
Movement Setters (Degrees)
Definition at line 1427 of file HalLegTarget.hpp.
References set_target_hipyawpitch().
set_hipyawpitch_RAD() [1/2]
void guWhiteboard::HalLegTarget::set_hipyawpitch_RAD (float setting) inline
Movement Setters (Radians)
Definition at line 655 of file HAL_LegTarget.hpp.
References set_target_hipyawpitch().
Referenced by setPose_Rad().
set_hipyawpitch_RAD() [2/2]
void guWhiteboard::HalLegTarget::set_hipyawpitch_RAD (float setting) inline
Movement Setters (Radians)
Definition at line 1453 of file HalLegTarget.hpp.
References set_target_hipyawpitch().
set_hipyawpitchstiffness() [1/2]
void guWhiteboard::HalLegTarget::set_hipyawpitchstiffness (float setting) inline
Stiffness Setters.
Definition at line 680 of file HAL_LegTarget.hpp.
References set_target_hipyawpitchstiffness().
Referenced by HalLegTarget(), setLegStiffness(), setLegStiffnessMax(), setLegStiffnessNormal(), and setLegStiffnessOff().
set_hipyawpitchstiffness() [2/2]
void guWhiteboard::HalLegTarget::set_hipyawpitchstiffness (float setting) inline
Stiffness Setters.
Definition at line 1478 of file HalLegTarget.hpp.
References set_target_hipyawpitchstiffness().
set_kneepitch_DEG() [1/2]
void guWhiteboard::HalLegTarget::set_kneepitch_DEG (float setting) inline
Definition at line 641 of file HAL_LegTarget.hpp.
References set_target_kneepitch().
Referenced by setPose_Deg().
set_kneepitch_DEG() [2/2]
void guWhiteboard::HalLegTarget::set_kneepitch_DEG (float setting) inline
Definition at line 1439 of file HalLegTarget.hpp.
References set_target_kneepitch().
set_kneepitch_RAD() [1/2]
void guWhiteboard::HalLegTarget::set_kneepitch_RAD (float setting) inline
Definition at line 667 of file HAL_LegTarget.hpp.
References set_target_kneepitch().
Referenced by setPose_Rad().
set_kneepitch_RAD() [2/2]
void guWhiteboard::HalLegTarget::set_kneepitch_RAD (float setting) inline
Definition at line 1465 of file HalLegTarget.hpp.
References set_target_kneepitch().
set_kneepitchstiffness() [1/2]
void guWhiteboard::HalLegTarget::set_kneepitchstiffness (float setting) inline
Definition at line 692 of file HAL_LegTarget.hpp.
References set_target_kneepitchstiffness().
Referenced by HalLegTarget(), setLegStiffness(), setLegStiffnessMax(), setLegStiffnessNormal(), and setLegStiffnessOff().
set_kneepitchstiffness() [2/2]
void guWhiteboard::HalLegTarget::set_kneepitchstiffness (float setting) inline
Definition at line 1490 of file HalLegTarget.hpp.
References set_target_kneepitchstiffness().
set_target_anklepitch()
void guWhiteboard::HalLegTarget::set_target_anklepitch (const int16_t & t_newValue) inline
Definition at line 282 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_anklepitch.
Referenced by copyPose(), from_string(), mirrorLeg(), mirrorPose(), set_anklepitch_DEG(), and set_anklepitch_RAD().
set_target_anklepitch_active()
void guWhiteboard::HalLegTarget::set_target_anklepitch_active (const unsigned int & t_newValue) inline
Definition at line 467 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_anklepitch_active.
Referenced by from_string(), mirrorLeg(), setLegActive(), setLegPassive(), and setLegPliability().
set_target_anklepitchstiffness()
void guWhiteboard::HalLegTarget::set_target_anklepitchstiffness (const uint8_t & t_newValue) inline
Definition at line 387 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_anklepitchstiffness.
Referenced by copyStiffness(), from_string(), mirrorLeg(), and set_anklepitchstiffness().
set_target_ankleroll()
void guWhiteboard::HalLegTarget::set_target_ankleroll (const int16_t & t_newValue) inline
Definition at line 297 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_ankleroll.
Referenced by copyPose(), from_string(), mirrorLeg(), mirrorPose(), set_ankleroll_DEG(), and set_ankleroll_RAD().
set_target_ankleroll_active()
void guWhiteboard::HalLegTarget::set_target_ankleroll_active (const unsigned int & t_newValue) inline
Definition at line 477 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_ankleroll_active.
Referenced by from_string(), mirrorLeg(), setLegActive(), setLegPassive(), and setLegPliability().
set_target_anklerollstiffness()
void guWhiteboard::HalLegTarget::set_target_anklerollstiffness (const uint8_t & t_newValue) inline
Definition at line 402 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_anklerollstiffness.
Referenced by copyStiffness(), from_string(), mirrorLeg(), and set_anklerollstiffness().
set_target_hippitch()
void guWhiteboard::HalLegTarget::set_target_hippitch (const int16_t & t_newValue) inline
Definition at line 252 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_hippitch.
Referenced by copyPose(), from_string(), mirrorLeg(), mirrorPose(), set_hippitch_DEG(), and set_hippitch_RAD().
set_target_hippitch_active()
void guWhiteboard::HalLegTarget::set_target_hippitch_active (const unsigned int & t_newValue) inline
Definition at line 447 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_hippitch_active.
Referenced by from_string(), mirrorLeg(), setLegActive(), setLegPassive(), and setLegPliability().
set_target_hippitchstiffness()
void guWhiteboard::HalLegTarget::set_target_hippitchstiffness (const uint8_t & t_newValue) inline
Definition at line 357 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_hippitchstiffness.
Referenced by copyStiffness(), from_string(), mirrorLeg(), and set_hippitchstiffness().
set_target_hiproll()
void guWhiteboard::HalLegTarget::set_target_hiproll (const int16_t & t_newValue) inline
Definition at line 237 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_hiproll.
Referenced by copyPose(), from_string(), mirrorLeg(), mirrorPose(), set_hiproll_DEG(), and set_hiproll_RAD().
set_target_hiproll_active()
void guWhiteboard::HalLegTarget::set_target_hiproll_active (const unsigned int & t_newValue) inline
Definition at line 437 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_hiproll_active.
Referenced by from_string(), mirrorLeg(), setLegActive(), setLegPassive(), and setLegPliability().
set_target_hiprollstiffness()
void guWhiteboard::HalLegTarget::set_target_hiprollstiffness (const uint8_t & t_newValue) inline
Definition at line 342 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_hiprollstiffness.
Referenced by copyStiffness(), from_string(), mirrorLeg(), and set_hiprollstiffness().
set_target_hipyawpitch()
void guWhiteboard::HalLegTarget::set_target_hipyawpitch (const int16_t & t_newValue) inline
Definition at line 222 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_hipyawpitch.
Referenced by copyPose(), from_string(), mirrorLeg(), mirrorPose(), set_hipyawpitch_DEG(), and set_hipyawpitch_RAD().
set_target_hipyawpitch_active()
void guWhiteboard::HalLegTarget::set_target_hipyawpitch_active (const unsigned int & t_newValue) inline
Definition at line 427 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_hipyawpitch_active.
Referenced by from_string(), mirrorLeg(), setLegActive(), setLegPassive(), and setLegPliability().
set_target_hipyawpitchstiffness()
void guWhiteboard::HalLegTarget::set_target_hipyawpitchstiffness (const uint8_t & t_newValue) inline
Definition at line 327 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_hipyawpitchstiffness.
Referenced by copyStiffness(), from_string(), mirrorLeg(), and set_hipyawpitchstiffness().
set_target_kneepitch()
void guWhiteboard::HalLegTarget::set_target_kneepitch (const int16_t & t_newValue) inline
Definition at line 267 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_kneepitch.
Referenced by copyPose(), from_string(), mirrorLeg(), mirrorPose(), set_kneepitch_DEG(), and set_kneepitch_RAD().
set_target_kneepitch_active()
void guWhiteboard::HalLegTarget::set_target_kneepitch_active (const unsigned int & t_newValue) inline
Definition at line 457 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_kneepitch_active.
Referenced by from_string(), mirrorLeg(), setLegActive(), setLegPassive(), and setLegPliability().
set_target_kneepitchstiffness()
void guWhiteboard::HalLegTarget::set_target_kneepitchstiffness (const uint8_t & t_newValue) inline
Definition at line 372 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_kneepitchstiffness.
Referenced by copyStiffness(), from_string(), mirrorLeg(), and set_kneepitchstiffness().
set_target_leg()
void guWhiteboard::HalLegTarget::set_target_leg (const uint8_t & t_newValue) inline
Definition at line 312 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_leg.
Referenced by from_string(), and tieToLeg().
set_target_leg_at_goal()
void guWhiteboard::HalLegTarget::set_target_leg_at_goal (const unsigned int & t_newValue) inline
Definition at line 487 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_leg_at_goal.
Referenced by from_string(), and isAtGoal().
set_target_leg_stop()
void guWhiteboard::HalLegTarget::set_target_leg_stop (const unsigned int & t_newValue) inline
Definition at line 497 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_leg_stop.
Referenced by HalLegTarget(), from_string(), ready(), and stop().
set_target_movement_time()
void guWhiteboard::HalLegTarget::set_target_movement_time (const int32_t & t_newValue) inline
Definition at line 207 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_movement_time.
Referenced by HalLegTarget(), from_string(), goToWithTime_Deg(), goToWithTime_Rad(), and mirrorLeg().
set_target_pliability()
void guWhiteboard::HalLegTarget::set_target_pliability (const uint8_t & t_newValue) inline
Definition at line 417 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_pliability.
Referenced by HalLegTarget(), from_string(), and mirrorLeg().
setLegActive() [1/2]
void guWhiteboard::HalLegTarget::setLegActive () inline
Set leg to be Active (DEDAULT DCM state) The leg is active and manual movements will be resisted, be careful when the stiffness is set high.
Once the applied force is removed, the leg will return to its previous location. Be careful using this with high stiffness settings (which vary per joint), as the gears will be stripped.
NOTE: This is the default DCM mode.
Definition at line 554 of file HAL_LegTarget.hpp.
References set_target_anklepitch_active(), set_target_ankleroll_active(), set_target_hippitch_active(), set_target_hiproll_active(), set_target_hipyawpitch_active(), and set_target_kneepitch_active().
setLegActive() [2/2]
void guWhiteboard::HalLegTarget::setLegActive () inline
Set leg to be Active (DEDAULT DCM state) The leg is active and manual movements will be resisted, be careful when the stiffness is set high.
Once the applied force is removed, the leg will return to its previous location. Be careful using this with high stiffness settings (which vary per joint), as the gears will be stripped.
NOTE: This is the default DCM mode.
Definition at line 1352 of file HalLegTarget.hpp.
References set_target_anklepitch_active(), set_target_ankleroll_active(), set_target_hippitch_active(), set_target_hiproll_active(), set_target_hipyawpitch_active(), and set_target_kneepitch_active().
setLegPassive() [1/2]
void guWhiteboard::HalLegTarget::setLegPassive () inline
Set leg to be Passive Manually moving the leg causes the leg to stay in the new position.
Be careful using this with high stiffness and pliability settings (which vary per joint). The robot may/will collapse under its own weight.
NOTE: This is achieved by telling the DCM to move the leg joints to the displaced position each DCM cyle. Thus the leg tracks the applied force. The 'pliability' setting reduces the update rate, thus making the leg stiffer. At higher pliability settings, the movement will become noticably stepped.
Definition at line 576 of file HAL_LegTarget.hpp.
References set_target_anklepitch_active(), set_target_ankleroll_active(), set_target_hippitch_active(), set_target_hiproll_active(), set_target_hipyawpitch_active(), and set_target_kneepitch_active().
setLegPassive() [2/2]
void guWhiteboard::HalLegTarget::setLegPassive () inline
Set leg to be Passive Manually moving the leg causes the leg to stay in the new position.
Be careful using this with high stiffness and pliability settings (which vary per joint). The robot may/will collapse under its own weight.
NOTE: This is achieved by telling the DCM to move the leg joints to the displaced position each DCM cyle. Thus the leg tracks the applied force. The 'pliability' setting reduces the update rate, thus making the leg stiffer. At higher pliability settings, the movement will become noticably stepped.
Definition at line 1374 of file HalLegTarget.hpp.
References set_target_anklepitch_active(), set_target_ankleroll_active(), set_target_hippitch_active(), set_target_hiproll_active(), set_target_hipyawpitch_active(), and set_target_kneepitch_active().
setLegPliability() [1/2]
void guWhiteboard::HalLegTarget::setLegPliability (bool hipyawpitch, bool hiproll, bool hippitch, bool kneepitch, bool anklepitch, bool ankleroll) inline
Individually set the active/passive state of each joint.
See setLegActive() and setLegPassive() methods for an explanation of the Active/Passive effect.
Definition at line 592 of file HAL_LegTarget.hpp.
References wb_hal_legtarget::anklepitch, wb_hal_legtarget::ankleroll, wb_hal_legtarget::hippitch, wb_hal_legtarget::hiproll, wb_hal_legtarget::hipyawpitch, wb_hal_legtarget::kneepitch, set_target_anklepitch_active(), set_target_ankleroll_active(), set_target_hippitch_active(), set_target_hiproll_active(), set_target_hipyawpitch_active(), and set_target_kneepitch_active().
Referenced by HalLegTarget().
setLegPliability() [2/2]
void guWhiteboard::HalLegTarget::setLegPliability (bool hipyawpitch, bool hiproll, bool hippitch, bool kneepitch, bool anklepitch, bool ankleroll) inline
Individually set the active/passive state of each joint.
See setLegActive() and setLegPassive() methods for an explanation of the Active/Passive effect.
Definition at line 1390 of file HalLegTarget.hpp.
References wb_hal_legtarget::anklepitch, wb_hal_legtarget::ankleroll, wb_hal_legtarget::hippitch, wb_hal_legtarget::hiproll, wb_hal_legtarget::hipyawpitch, wb_hal_legtarget::kneepitch, set_target_anklepitch_active(), set_target_ankleroll_active(), set_target_hippitch_active(), set_target_hiproll_active(), set_target_hipyawpitch_active(), and set_target_kneepitch_active().
setLegStiffness() [1/2]
void guWhiteboard::HalLegTarget::setLegStiffness (float stiffness) inline
Convenience function to set uniform stiffness on all leg joints to a custom value.
Parameters
stiffness float Stiffness setting between 0.0 and 1.0 (float).
Definition at line 474 of file HAL_LegTarget.hpp.
References set_anklepitchstiffness(), set_anklerollstiffness(), set_hippitchstiffness(), set_hiprollstiffness(), set_hipyawpitchstiffness(), and set_kneepitchstiffness().
setLegStiffness() [2/2]
void guWhiteboard::HalLegTarget::setLegStiffness (float stiffness) inline
Convenience function to set uniform stiffness on all leg joints to a custom value.
Parameters
stiffness float Stiffness setting between 0.0 and 1.0 (float).
Definition at line 1272 of file HalLegTarget.hpp.
References set_anklepitchstiffness(), set_anklerollstiffness(), set_hippitchstiffness(), set_hiprollstiffness(), set_hipyawpitchstiffness(), and set_kneepitchstiffness().
setLegStiffnessMax() [1/2]
void guWhiteboard::HalLegTarget::setLegStiffnessMax () inline
Convenience function to set the stiffness of all the leg's joints to the maximum (1.0f).
Definition at line 441 of file HAL_LegTarget.hpp.
References set_anklepitchstiffness(), set_anklerollstiffness(), set_hippitchstiffness(), set_hiprollstiffness(), set_hipyawpitchstiffness(), and set_kneepitchstiffness().
setLegStiffnessMax() [2/2]
void guWhiteboard::HalLegTarget::setLegStiffnessMax () inline
Convenience function to set the stiffness of all the leg's joints to the maximum (1.0f).
Definition at line 1239 of file HalLegTarget.hpp.
References set_anklepitchstiffness(), set_anklerollstiffness(), set_hippitchstiffness(), set_hiprollstiffness(), set_hipyawpitchstiffness(), and set_kneepitchstiffness().
setLegStiffnessNormal() [1/2]
void guWhiteboard::HalLegTarget::setLegStiffnessNormal () inline
Convenience function to set the stiffness of all the leg's joints to what Aldebaran considers 'normal' (0.6f).
Definition at line 457 of file HAL_LegTarget.hpp.
References set_anklepitchstiffness(), set_anklerollstiffness(), set_hippitchstiffness(), set_hiprollstiffness(), set_hipyawpitchstiffness(), and set_kneepitchstiffness().
setLegStiffnessNormal() [2/2]
void guWhiteboard::HalLegTarget::setLegStiffnessNormal () inline
Convenience function to set the stiffness of all the leg's joints to what Aldebaran considers 'normal' (0.6f).
Definition at line 1255 of file HalLegTarget.hpp.
References set_anklepitchstiffness(), set_anklerollstiffness(), set_hippitchstiffness(), set_hiprollstiffness(), set_hipyawpitchstiffness(), and set_kneepitchstiffness().
setLegStiffnessOff() [1/2]
void guWhiteboard::HalLegTarget::setLegStiffnessOff () inline
Convenience function to turn off stiffness in all the leg's joints (0.0f).
Definition at line 491 of file HAL_LegTarget.hpp.
References set_anklepitchstiffness(), set_anklerollstiffness(), set_hippitchstiffness(), set_hiprollstiffness(), set_hipyawpitchstiffness(), and set_kneepitchstiffness().
setLegStiffnessOff() [2/2]
void guWhiteboard::HalLegTarget::setLegStiffnessOff () inline
Convenience function to turn off stiffness in all the leg's joints (0.0f).
Definition at line 1289 of file HalLegTarget.hpp.
References set_anklepitchstiffness(), set_anklerollstiffness(), set_hippitchstiffness(), set_hiprollstiffness(), set_hipyawpitchstiffness(), and set_kneepitchstiffness().
setPose_Deg() [1/2]
void guWhiteboard::HalLegTarget::setPose_Deg (float hipyawpitch, float hiproll, float hippitch, float kneepitch, float anklepitch, float ankleroll) inline
Set Pose in degrees.
Parameters
hipyawpitch down to up
hiproll out to in
hippitch swing thigh forward/back
kneepitch swig calf out/back
anklepitch raise/lower toes
ankleroll roll ankle out to in
Definition at line 306 of file HAL_LegTarget.hpp.
References wb_hal_legtarget::anklepitch, wb_hal_legtarget::ankleroll, wb_hal_legtarget::hippitch, wb_hal_legtarget::hiproll, wb_hal_legtarget::hipyawpitch, wb_hal_legtarget::kneepitch, set_anklepitch_DEG(), set_ankleroll_DEG(), set_hippitch_DEG(), set_hiproll_DEG(), set_hipyawpitch_DEG(), and set_kneepitch_DEG().
Referenced by HalLegTarget(), and goToWithTime_Deg().
setPose_Deg() [2/2]
void guWhiteboard::HalLegTarget::setPose_Deg (float hipyawpitch, float hiproll, float hippitch, float kneepitch, float anklepitch, float ankleroll) inline
Set Pose in degrees.
Parameters
hipyawpitch down to up
hiproll out to in
hippitch swing thigh forward/back
kneepitch swig calf out/back
anklepitch raise/lower toes
ankleroll roll ankle out to in
Definition at line 1104 of file HalLegTarget.hpp.
References wb_hal_legtarget::anklepitch, wb_hal_legtarget::ankleroll, wb_hal_legtarget::hippitch, wb_hal_legtarget::hiproll, wb_hal_legtarget::hipyawpitch, wb_hal_legtarget::kneepitch, set_anklepitch_DEG(), set_ankleroll_DEG(), set_hippitch_DEG(), set_hiproll_DEG(), set_hipyawpitch_DEG(), and set_kneepitch_DEG().
setPose_Rad() [1/2]
void guWhiteboard::HalLegTarget::setPose_Rad (float hipyawpitch, float hiproll, float hippitch, float kneepitch, float anklepitch, float ankleroll) inline
Set Pose in radians.
Parameters
hipyawpitch down to up
hiproll out to in
hippitch swing thigh forward/back
kneepitch swig calf out/back
anklepitch raise/lower toes
ankleroll roll ankle out to in
Definition at line 281 of file HAL_LegTarget.hpp.
References wb_hal_legtarget::anklepitch, wb_hal_legtarget::ankleroll, wb_hal_legtarget::hippitch, wb_hal_legtarget::hiproll, wb_hal_legtarget::hipyawpitch, wb_hal_legtarget::kneepitch, set_anklepitch_RAD(), set_ankleroll_RAD(), set_hippitch_RAD(), set_hiproll_RAD(), set_hipyawpitch_RAD(), and set_kneepitch_RAD().
Referenced by HalLegTarget(), and goToWithTime_Rad().
setPose_Rad() [2/2]
void guWhiteboard::HalLegTarget::setPose_Rad (float hipyawpitch, float hiproll, float hippitch, float kneepitch, float anklepitch, float ankleroll) inline
Set Pose in radians.
Parameters
hipyawpitch down to up
hiproll out to in
hippitch swing thigh forward/back
kneepitch swig calf out/back
anklepitch raise/lower toes
ankleroll roll ankle out to in
Definition at line 1079 of file HalLegTarget.hpp.
References wb_hal_legtarget::anklepitch, wb_hal_legtarget::ankleroll, wb_hal_legtarget::hippitch, wb_hal_legtarget::hiproll, wb_hal_legtarget::hipyawpitch, wb_hal_legtarget::kneepitch, set_anklepitch_RAD(), set_ankleroll_RAD(), set_hippitch_RAD(), set_hiproll_RAD(), set_hipyawpitch_RAD(), and set_kneepitch_RAD().
stop() [1/2]
void guWhiteboard::HalLegTarget::stop () inline
Command the leg to stop at its current location and not act on motion commands until ready() is called.
Definition at line 189 of file HAL_LegTarget.hpp.
References set_target_leg_stop().
stop() [2/2]
void guWhiteboard::HalLegTarget::stop () inline
Command the leg to stop at its current location and not act on motion commands until ready() is called.
Definition at line 987 of file HalLegTarget.hpp.
References set_target_leg_stop().
target_anklepitch() [1/2]
int16_t & guWhiteboard::HalLegTarget::target_anklepitch () inline
Definition at line 272 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_anklepitch.
Referenced by atTargetLocation(), copyPose(), description(), get_anklepitch_DEG(), get_anklepitch_RAD(), hasSameMirroredPose(), hasSamePose(), mirrorLeg(), mirrorPose(), operator==(), to_string(), and valueDescription().
target_anklepitch() [2/2]
const int16_t & guWhiteboard::HalLegTarget::target_anklepitch () const inline
Definition at line 277 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_anklepitch.
target_anklepitch_active()
unsigned int guWhiteboard::HalLegTarget::target_anklepitch_active () const inline
Definition at line 462 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_anklepitch_active.
Referenced by description(), isLegAllActive(), isLegAllPassive(), isLegPassive(), mirrorLeg(), operator==(), to_string(), and valueDescription().
target_anklepitchstiffness() [1/2]
uint8_t & guWhiteboard::HalLegTarget::target_anklepitchstiffness () inline
Definition at line 377 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_anklepitchstiffness.
Referenced by copyStiffness(), description(), get_anklepitchstiffness(), hasSameStiffness(), mirrorLeg(), operator==(), to_string(), and valueDescription().
target_anklepitchstiffness() [2/2]
const uint8_t & guWhiteboard::HalLegTarget::target_anklepitchstiffness () const inline
Definition at line 382 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_anklepitchstiffness.
target_ankleroll() [1/2]
int16_t & guWhiteboard::HalLegTarget::target_ankleroll () inline
Definition at line 287 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_ankleroll.
Referenced by atTargetLocation(), copyPose(), description(), get_ankleroll_DEG(), get_ankleroll_RAD(), hasSameMirroredPose(), hasSamePose(), mirrorLeg(), mirrorPose(), operator==(), to_string(), and valueDescription().
target_ankleroll() [2/2]
const int16_t & guWhiteboard::HalLegTarget::target_ankleroll () const inline
Definition at line 292 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_ankleroll.
target_ankleroll_active()
unsigned int guWhiteboard::HalLegTarget::target_ankleroll_active () const inline
Definition at line 472 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_ankleroll_active.
Referenced by description(), isLegAllActive(), isLegAllPassive(), isLegPassive(), mirrorLeg(), operator==(), to_string(), and valueDescription().
target_anklerollstiffness() [1/2]
uint8_t & guWhiteboard::HalLegTarget::target_anklerollstiffness () inline
Definition at line 392 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_anklerollstiffness.
Referenced by copyStiffness(), description(), get_anklerollstiffness(), hasSameStiffness(), mirrorLeg(), operator==(), to_string(), and valueDescription().
target_anklerollstiffness() [2/2]
const uint8_t & guWhiteboard::HalLegTarget::target_anklerollstiffness () const inline
Definition at line 397 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_anklerollstiffness.
target_hippitch() [1/2]
int16_t & guWhiteboard::HalLegTarget::target_hippitch () inline
Definition at line 242 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_hippitch.
Referenced by atTargetLocation(), copyPose(), description(), get_hippitch_DEG(), get_hippitch_RAD(), hasSameMirroredPose(), hasSamePose(), mirrorLeg(), mirrorPose(), operator==(), to_string(), and valueDescription().
target_hippitch() [2/2]
const int16_t & guWhiteboard::HalLegTarget::target_hippitch () const inline
Definition at line 247 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_hippitch.
target_hippitch_active()
unsigned int guWhiteboard::HalLegTarget::target_hippitch_active () const inline
Definition at line 442 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_hippitch_active.
Referenced by description(), isLegAllActive(), isLegAllPassive(), isLegPassive(), mirrorLeg(), operator==(), to_string(), and valueDescription().
target_hippitchstiffness() [1/2]
uint8_t & guWhiteboard::HalLegTarget::target_hippitchstiffness () inline
Definition at line 347 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_hippitchstiffness.
Referenced by copyStiffness(), description(), get_hippitchstiffness(), hasSameStiffness(), mirrorLeg(), operator==(), to_string(), and valueDescription().
target_hippitchstiffness() [2/2]
const uint8_t & guWhiteboard::HalLegTarget::target_hippitchstiffness () const inline
Definition at line 352 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_hippitchstiffness.
target_hiproll() [1/2]
int16_t & guWhiteboard::HalLegTarget::target_hiproll () inline
Definition at line 227 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_hiproll.
Referenced by atTargetLocation(), copyPose(), description(), get_hiproll_DEG(), get_hiproll_RAD(), hasSameMirroredPose(), hasSamePose(), mirrorLeg(), mirrorPose(), operator==(), to_string(), and valueDescription().
target_hiproll() [2/2]
const int16_t & guWhiteboard::HalLegTarget::target_hiproll () const inline
Definition at line 232 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_hiproll.
target_hiproll_active()
unsigned int guWhiteboard::HalLegTarget::target_hiproll_active () const inline
Definition at line 432 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_hiproll_active.
Referenced by description(), isLegAllActive(), isLegAllPassive(), isLegPassive(), mirrorLeg(), operator==(), to_string(), and valueDescription().
target_hiprollstiffness() [1/2]
uint8_t & guWhiteboard::HalLegTarget::target_hiprollstiffness () inline
Definition at line 332 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_hiprollstiffness.
Referenced by copyStiffness(), description(), get_hiprollstiffness(), hasSameStiffness(), mirrorLeg(), operator==(), to_string(), and valueDescription().
target_hiprollstiffness() [2/2]
const uint8_t & guWhiteboard::HalLegTarget::target_hiprollstiffness () const inline
Definition at line 337 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_hiprollstiffness.
target_hipyawpitch() [1/2]
int16_t & guWhiteboard::HalLegTarget::target_hipyawpitch () inline
Definition at line 212 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_hipyawpitch.
Referenced by atTargetLocation(), copyPose(), description(), get_hipyawpitch_DEG(), get_hipyawpitch_RAD(), hasSameMirroredPose(), hasSamePose(), mirrorLeg(), mirrorPose(), operator==(), to_string(), and valueDescription().
target_hipyawpitch() [2/2]
const int16_t & guWhiteboard::HalLegTarget::target_hipyawpitch () const inline
Definition at line 217 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_hipyawpitch.
target_hipyawpitch_active()
unsigned int guWhiteboard::HalLegTarget::target_hipyawpitch_active () const inline
Definition at line 422 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_hipyawpitch_active.
Referenced by description(), isLegAllActive(), isLegAllPassive(), isLegPassive(), mirrorLeg(), operator==(), to_string(), and valueDescription().
target_hipyawpitchstiffness() [1/2]
uint8_t & guWhiteboard::HalLegTarget::target_hipyawpitchstiffness () inline
Definition at line 317 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_hipyawpitchstiffness.
Referenced by copyStiffness(), description(), get_hipyawpitchstiffness(), hasSameStiffness(), mirrorLeg(), operator==(), to_string(), and valueDescription().
target_hipyawpitchstiffness() [2/2]
const uint8_t & guWhiteboard::HalLegTarget::target_hipyawpitchstiffness () const inline
Definition at line 322 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_hipyawpitchstiffness.
target_kneepitch() [1/2]
int16_t & guWhiteboard::HalLegTarget::target_kneepitch () inline
Definition at line 257 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_kneepitch.
Referenced by atTargetLocation(), copyPose(), description(), get_kneepitch_DEG(), get_kneepitch_RAD(), hasSameMirroredPose(), hasSamePose(), mirrorLeg(), mirrorPose(), operator==(), to_string(), and valueDescription().
target_kneepitch() [2/2]
const int16_t & guWhiteboard::HalLegTarget::target_kneepitch () const inline
Definition at line 262 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_kneepitch.
target_kneepitch_active()
unsigned int guWhiteboard::HalLegTarget::target_kneepitch_active () const inline
Definition at line 452 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_kneepitch_active.
Referenced by description(), isLegAllActive(), isLegAllPassive(), isLegPassive(), mirrorLeg(), operator==(), to_string(), and valueDescription().
target_kneepitchstiffness() [1/2]
uint8_t & guWhiteboard::HalLegTarget::target_kneepitchstiffness () inline
Definition at line 362 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_kneepitchstiffness.
Referenced by copyStiffness(), description(), get_kneepitchstiffness(), hasSameStiffness(), mirrorLeg(), operator==(), to_string(), and valueDescription().
target_kneepitchstiffness() [2/2]
const uint8_t & guWhiteboard::HalLegTarget::target_kneepitchstiffness () const inline
Definition at line 367 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_kneepitchstiffness.
target_leg() [1/2]
uint8_t & guWhiteboard::HalLegTarget::target_leg () inline
Definition at line 302 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_leg.
Referenced by description(), operator==(), and to_string().
target_leg() [2/2]
const uint8_t & guWhiteboard::HalLegTarget::target_leg () const inline
Definition at line 307 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_leg.
target_leg_at_goal()
unsigned int guWhiteboard::HalLegTarget::target_leg_at_goal () const inline
Definition at line 482 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_leg_at_goal.
Referenced by atGoal(), description(), operator==(), to_string(), and valueDescription().
target_leg_stop()
unsigned int guWhiteboard::HalLegTarget::target_leg_stop () const inline
Definition at line 492 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_leg_stop.
Referenced by description(), operator==(), to_string(), and valueDescription().
target_movement_time() [1/2]
int32_t & guWhiteboard::HalLegTarget::target_movement_time () inline
Definition at line 197 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_movement_time.
Referenced by description(), mirrorLeg(), operator==(), to_string(), and valueDescription().
target_movement_time() [2/2]
const int32_t & guWhiteboard::HalLegTarget::target_movement_time () const inline
Definition at line 202 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_movement_time.
target_pliability() [1/2]
uint8_t & guWhiteboard::HalLegTarget::target_pliability () inline
Definition at line 407 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_pliability.
Referenced by description(), mirrorLeg(), operator==(), to_string(), and valueDescription().
target_pliability() [2/2]
const uint8_t & guWhiteboard::HalLegTarget::target_pliability () const inline
Definition at line 412 of file HalLegTarget.hpp.
References wb_hal_leg_target::target_pliability.
tieToLeg() [1/2]
void guWhiteboard::HalLegTarget::tieToLeg (uint8_t leg) inline
Specify which leg this instance manages.
Up to 256 legs are possible. Use prefedined macros LEFT_LEG and RIGHT_LEG for clarity.
Parameters
leg integer used to record which leg the object refers to.
Definition at line 126 of file HAL_LegTarget.hpp.
References set_target_leg().
tieToLeg() [2/2]
void guWhiteboard::HalLegTarget::tieToLeg (uint8_t leg) inline
USE_WB_HAL_LEG_TARGET_C_CONVERSION WHITEBOARD_POSTER_STRING_CONVERSION.
Specify which leg this instance manages. Up to 256 legs are possible. Use prefedined macros LEFT_LEG and RIGHT_LEG for clarity.
Parameters
leg integer used to record which leg the object refers to.
Definition at line 924 of file HalLegTarget.hpp.
References set_target_leg().
to_string()
std::string guWhiteboard::HalLegTarget::to_string () inline
USE_WB_HAL_LEG_TARGET_C_CONVERSION
Definition at line 568 of file HalLegTarget.hpp.
References HAL_LEG_TARGET_TO_STRING_BUFFER_SIZE, target_anklepitch(), target_anklepitch_active(), target_anklepitchstiffness(), target_ankleroll(), target_ankleroll_active(), target_anklerollstiffness(), target_hippitch(), target_hippitch_active(), target_hippitchstiffness(), target_hiproll(), target_hiproll_active(), target_hiprollstiffness(), target_hipyawpitch(), target_hipyawpitch_active(), target_hipyawpitchstiffness(), target_kneepitch(), target_kneepitch_active(), target_kneepitchstiffness(), target_leg(), target_leg_at_goal(), target_leg_stop(), target_movement_time(), target_pliability(), and wb_hal_leg_target_to_string().
valueDescription()
std::string guWhiteboard::HalLegTarget::valueDescription () inline
WHITEBOARD_POSTER_STRING_CONVERSION.
Description function which prints values only (Spreadsheet friendly)
Definition at line 880 of file HalLegTarget.hpp.
References HAL_LEG_TARGET_DESC_BUFFER_SIZE, target_anklepitch(), target_anklepitch_active(), target_anklepitchstiffness(), target_ankleroll(), target_ankleroll_active(), target_anklerollstiffness(), target_hippitch(), target_hippitch_active(), target_hippitchstiffness(), target_hiproll(), target_hiproll_active(), target_hiprollstiffness(), target_hipyawpitch(), target_hipyawpitch_active(), target_hipyawpitchstiffness(), target_kneepitch(), target_kneepitch_active(), target_kneepitchstiffness(), target_leg_at_goal(), target_leg_stop(), target_movement_time(), target_pliability(), and wb_hal_leg_target_value_description().
The documentation for this class was generated from the following files:
typeClassDefs/HAL_LegTarget.hpp
typeClassDefs/HalLegTarget.hpp