gusimplewhiteboard: guWhiteboard::VisionLine Class Reference
guWhiteboard::VisionLine Class Reference
Provides a C++ wrapper around wb_vision_line.
#include <VisionLine.hpp>
Public Member Functions
VisionLine (struct wb_pixel_coordinate_line t_lineEdgeTop=wb_pixel_coordinate_line(), struct wb_pixel_coordinate_line t_lineEdgeBottom=wb_pixel_coordinate_line())
Create a new VisionLine.
VisionLine (const VisionLine &t_other)
Copy Constructor.
VisionLine (const struct wb_vision_line &t_other)
Copy Constructor.
VisionLine & operator= (const VisionLine &t_other)
Copy Assignment Operator.
VisionLine & operator= (const struct wb_vision_line &t_other)
Copy Assignment Operator.
bool operator== (const VisionLine &t_other) const
bool operator!= (const VisionLine &t_other) const
bool operator== (const wb_vision_line &t_other) const
bool operator!= (const wb_vision_line &t_other) const
PixelCoordinateLine & lineEdgeTop ()
const PixelCoordinateLine & lineEdgeTop () const
void set_lineEdgeTop (const PixelCoordinateLine &t_newValue)
PixelCoordinateLine & lineEdgeBottom ()
const PixelCoordinateLine & lineEdgeBottom () const
void set_lineEdgeBottom (const PixelCoordinateLine &t_newValue)
VisionLine (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_vision_line
struct wb_pixel_coordinate_line lineEdgeTop
line object representing the top edge of an SPL line.
struct wb_pixel_coordinate_line lineEdgeBottom
line object representing the bottom edge of an SPL line.
Detailed Description
Provides a C++ wrapper around wb_vision_line.
Definition at line 85 of file VisionLine.hpp.
Constructor & Destructor Documentation
VisionLine() [1/4]
guWhiteboard::VisionLine::VisionLine (struct wb_pixel_coordinate_line t_lineEdgeTop = wb_pixel_coordinate_line(), struct wb_pixel_coordinate_line t_lineEdgeBottom = wb_pixel_coordinate_line()) inline
Create a new VisionLine.
Definition at line 102 of file VisionLine.hpp.
Referenced by operator==().
VisionLine() [2/4]
guWhiteboard::VisionLine::VisionLine (const VisionLine & t_other) inline
Copy Constructor.
Definition at line 109 of file VisionLine.hpp.
References lineEdgeBottom(), and lineEdgeTop().
VisionLine() [3/4]
guWhiteboard::VisionLine::VisionLine (const struct wb_vision_line & t_other) inline
Copy Constructor.
Definition at line 116 of file VisionLine.hpp.
References wb_vision_line::lineEdgeBottom, and wb_vision_line::lineEdgeTop.
VisionLine() [4/4]
guWhiteboard::VisionLine::VisionLine (const std::string & t_str) inline
String Constructor.
Definition at line 191 of file VisionLine.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::VisionLine::description () inline
USE_WB_VISION_LINE_C_CONVERSION
Definition at line 196 of file VisionLine.hpp.
References guWhiteboard::PixelCoordinateLine::description(), lineEdgeBottom(), lineEdgeTop(), VISION_LINE_DESC_BUFFER_SIZE, and wb_vision_line_description().
from_string()
void guWhiteboard::VisionLine::from_string (const std::string & t_str) inline
USE_WB_VISION_LINE_C_CONVERSION
Definition at line 230 of file VisionLine.hpp.
References guWhiteboard::PixelCoordinateLine::from_string(), set_lineEdgeBottom(), set_lineEdgeTop(), and VISION_LINE_DESC_BUFFER_SIZE.
Referenced by VisionLine(), and guWhiteboard::VisionLines::from_string().
lineEdgeBottom() [1/2]
PixelCoordinateLine & guWhiteboard::VisionLine::lineEdgeBottom () inline
Definition at line 172 of file VisionLine.hpp.
References wb_vision_line::lineEdgeBottom.
Referenced by VisionLine(), description(), operator=(), operator==(), and to_string().
lineEdgeBottom() [2/2]
const PixelCoordinateLine & guWhiteboard::VisionLine::lineEdgeBottom () const inline
Definition at line 177 of file VisionLine.hpp.
References wb_vision_line::lineEdgeBottom.
lineEdgeTop() [1/2]
PixelCoordinateLine & guWhiteboard::VisionLine::lineEdgeTop () inline
Definition at line 157 of file VisionLine.hpp.
References wb_vision_line::lineEdgeTop.
Referenced by VisionLine(), description(), operator=(), operator==(), and to_string().
lineEdgeTop() [2/2]
const PixelCoordinateLine & guWhiteboard::VisionLine::lineEdgeTop () const inline
Definition at line 162 of file VisionLine.hpp.
References wb_vision_line::lineEdgeTop.
operator!=() [1/2]
bool guWhiteboard::VisionLine::operator!= (const VisionLine & t_other) const inline
Definition at line 142 of file VisionLine.hpp.
operator!=() [2/2]
bool guWhiteboard::VisionLine::operator!= (const wb_vision_line & t_other) const inline
Definition at line 152 of file VisionLine.hpp.
operator=() [1/2]
VisionLine & guWhiteboard::VisionLine::operator= (const struct wb_vision_line & t_other) inline
Copy Assignment Operator.
Definition at line 131 of file VisionLine.hpp.
References wb_vision_line::lineEdgeBottom, and wb_vision_line::lineEdgeTop.
operator=() [2/2]
VisionLine & guWhiteboard::VisionLine::operator= (const VisionLine & t_other) inline
Copy Assignment Operator.
Definition at line 123 of file VisionLine.hpp.
References lineEdgeBottom(), and lineEdgeTop().
operator==() [1/2]
bool guWhiteboard::VisionLine::operator== (const VisionLine & t_other) const inline
Definition at line 136 of file VisionLine.hpp.
References lineEdgeBottom(), and lineEdgeTop().
operator==() [2/2]
bool guWhiteboard::VisionLine::operator== (const wb_vision_line & t_other) const inline
Definition at line 147 of file VisionLine.hpp.
References VisionLine().
set_lineEdgeBottom()
void guWhiteboard::VisionLine::set_lineEdgeBottom (const PixelCoordinateLine & t_newValue) inline
Definition at line 182 of file VisionLine.hpp.
References wb_vision_line::lineEdgeBottom.
Referenced by from_string().
set_lineEdgeTop()
void guWhiteboard::VisionLine::set_lineEdgeTop (const PixelCoordinateLine & t_newValue) inline
Definition at line 167 of file VisionLine.hpp.
References wb_vision_line::lineEdgeTop.
Referenced by from_string().
to_string()
std::string guWhiteboard::VisionLine::to_string () inline
USE_WB_VISION_LINE_C_CONVERSION
Definition at line 211 of file VisionLine.hpp.
References lineEdgeBottom(), lineEdgeTop(), guWhiteboard::PixelCoordinateLine::to_string(), VISION_LINE_TO_STRING_BUFFER_SIZE, and wb_vision_line_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/VisionLine.hpp