gusimplewhiteboard: guWhiteboard::VisionDetectionGoal Class Reference
guWhiteboard::VisionDetectionGoal Class Reference
Provides a C++ wrapper around wb_vision_detection_goal.
#include <VisionDetectionGoal.hpp>
Public Member Functions
VisionDetectionGoal (enum GoalOptions t_sightingType=NoGoalDetected, struct wb_vision_detection_goal_post t_post1=wb_vision_detection_goal_post(), struct wb_vision_detection_goal_post t_post2=wb_vision_detection_goal_post())
Create a new VisionDetectionGoal.
VisionDetectionGoal (const VisionDetectionGoal &t_other)
Copy Constructor.
VisionDetectionGoal (const struct wb_vision_detection_goal &t_other)
Copy Constructor.
VisionDetectionGoal & operator= (const VisionDetectionGoal &t_other)
Copy Assignment Operator.
VisionDetectionGoal & operator= (const struct wb_vision_detection_goal &t_other)
Copy Assignment Operator.
bool operator== (const VisionDetectionGoal &t_other) const
bool operator!= (const VisionDetectionGoal &t_other) const
bool operator== (const wb_vision_detection_goal &t_other) const
bool operator!= (const wb_vision_detection_goal &t_other) const
enum GoalOptions & sightingType ()
enum GoalOptions & sightingType () const
void set_sightingType (const enum GoalOptions &t_newValue)
VisionDetectionGoalPost & post1 ()
const VisionDetectionGoalPost & post1 () const
void set_post1 (const VisionDetectionGoalPost &t_newValue)
VisionDetectionGoalPost & post2 ()
const VisionDetectionGoalPost & post2 () const
void set_post2 (const VisionDetectionGoalPost &t_newValue)
VisionDetectionGoal (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_vision_detection_goal
enum GoalOptions sightingType
Goal detection details.
struct wb_vision_detection_goal_post post1
First post found.
struct wb_vision_detection_goal_post post2
Second post found.
Detailed Description
Provides a C++ wrapper around wb_vision_detection_goal.
Definition at line 85 of file VisionDetectionGoal.hpp.
Constructor & Destructor Documentation
VisionDetectionGoal() [1/4]
guWhiteboard::VisionDetectionGoal::VisionDetectionGoal (enum GoalOptions t_sightingType = NoGoalDetected, struct wb_vision_detection_goal_post t_post1 = wb_vision_detection_goal_post(), struct wb_vision_detection_goal_post t_post2 = wb_vision_detection_goal_post()) inline
Create a new VisionDetectionGoal.
Definition at line 103 of file VisionDetectionGoal.hpp.
Referenced by operator==().
VisionDetectionGoal() [2/4]
guWhiteboard::VisionDetectionGoal::VisionDetectionGoal (const VisionDetectionGoal & t_other) inline
Copy Constructor.
Definition at line 110 of file VisionDetectionGoal.hpp.
References post1(), post2(), and sightingType().
VisionDetectionGoal() [3/4]
guWhiteboard::VisionDetectionGoal::VisionDetectionGoal (const struct wb_vision_detection_goal & t_other) inline
Copy Constructor.
Definition at line 117 of file VisionDetectionGoal.hpp.
References wb_vision_detection_goal::post1, wb_vision_detection_goal::post2, and wb_vision_detection_goal::sightingType.
VisionDetectionGoal() [4/4]
guWhiteboard::VisionDetectionGoal::VisionDetectionGoal (const std::string & t_str) inline
String Constructor.
Definition at line 208 of file VisionDetectionGoal.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::VisionDetectionGoal::description () inline
USE_WB_VISION_DETECTION_GOAL_C_CONVERSION
Definition at line 213 of file VisionDetectionGoal.hpp.
References guWhiteboard::VisionDetectionGoalPost::description(), DoublePostGoal, NoGoalDetected, post1(), post2(), sightingType(), SinglePostGoal, VISION_DETECTION_GOAL_DESC_BUFFER_SIZE, and wb_vision_detection_goal_description().
from_string()
void guWhiteboard::VisionDetectionGoal::from_string (const std::string & t_str) inline
USE_WB_VISION_DETECTION_GOAL_C_CONVERSION
Definition at line 283 of file VisionDetectionGoal.hpp.
References DoublePostGoal, guWhiteboard::VisionDetectionGoalPost::from_string(), NoGoalDetected, set_post1(), set_post2(), set_sightingType(), SinglePostGoal, and VISION_DETECTION_GOAL_DESC_BUFFER_SIZE.
Referenced by VisionDetectionGoal(), and guWhiteboard::VisionDetectionGoals::from_string().
operator!=() [1/2]
bool guWhiteboard::VisionDetectionGoal::operator!= (const VisionDetectionGoal & t_other) const inline
Definition at line 144 of file VisionDetectionGoal.hpp.
operator!=() [2/2]
bool guWhiteboard::VisionDetectionGoal::operator!= (const wb_vision_detection_goal & t_other) const inline
Definition at line 154 of file VisionDetectionGoal.hpp.
operator=() [1/2]
VisionDetectionGoal & guWhiteboard::VisionDetectionGoal::operator= (const struct wb_vision_detection_goal & t_other) inline
Copy Assignment Operator.
Definition at line 132 of file VisionDetectionGoal.hpp.
References wb_vision_detection_goal::post1, wb_vision_detection_goal::post2, and wb_vision_detection_goal::sightingType.
operator=() [2/2]
VisionDetectionGoal & guWhiteboard::VisionDetectionGoal::operator= (const VisionDetectionGoal & t_other) inline
Copy Assignment Operator.
Definition at line 124 of file VisionDetectionGoal.hpp.
References post1(), post2(), and sightingType().
operator==() [1/2]
bool guWhiteboard::VisionDetectionGoal::operator== (const VisionDetectionGoal & t_other) const inline
Definition at line 137 of file VisionDetectionGoal.hpp.
References post1(), post2(), and sightingType().
operator==() [2/2]
bool guWhiteboard::VisionDetectionGoal::operator== (const wb_vision_detection_goal & t_other) const inline
Definition at line 149 of file VisionDetectionGoal.hpp.
References VisionDetectionGoal().
post1() [1/2]
VisionDetectionGoalPost & guWhiteboard::VisionDetectionGoal::post1 () inline
Definition at line 174 of file VisionDetectionGoal.hpp.
References wb_vision_detection_goal::post1.
Referenced by VisionDetectionGoal(), description(), operator=(), operator==(), and to_string().
post1() [2/2]
const VisionDetectionGoalPost & guWhiteboard::VisionDetectionGoal::post1 () const inline
Definition at line 179 of file VisionDetectionGoal.hpp.
References wb_vision_detection_goal::post1.
post2() [1/2]
VisionDetectionGoalPost & guWhiteboard::VisionDetectionGoal::post2 () inline
Definition at line 189 of file VisionDetectionGoal.hpp.
References wb_vision_detection_goal::post2.
Referenced by VisionDetectionGoal(), description(), operator=(), operator==(), and to_string().
post2() [2/2]
const VisionDetectionGoalPost & guWhiteboard::VisionDetectionGoal::post2 () const inline
Definition at line 194 of file VisionDetectionGoal.hpp.
References wb_vision_detection_goal::post2.
set_post1()
void guWhiteboard::VisionDetectionGoal::set_post1 (const VisionDetectionGoalPost & t_newValue) inline
Definition at line 184 of file VisionDetectionGoal.hpp.
References wb_vision_detection_goal::post1.
Referenced by from_string().
set_post2()
void guWhiteboard::VisionDetectionGoal::set_post2 (const VisionDetectionGoalPost & t_newValue) inline
Definition at line 199 of file VisionDetectionGoal.hpp.
References wb_vision_detection_goal::post2.
Referenced by from_string().
set_sightingType()
void guWhiteboard::VisionDetectionGoal::set_sightingType (const enum GoalOptions & t_newValue) inline
Definition at line 169 of file VisionDetectionGoal.hpp.
References wb_vision_detection_goal::sightingType.
Referenced by from_string().
sightingType() [1/2]
enum GoalOptions & guWhiteboard::VisionDetectionGoal::sightingType () inline
Definition at line 159 of file VisionDetectionGoal.hpp.
References wb_vision_detection_goal::sightingType.
Referenced by VisionDetectionGoal(), description(), operator=(), operator==(), and to_string().
sightingType() [2/2]
enum GoalOptions & guWhiteboard::VisionDetectionGoal::sightingType () const inline
Definition at line 164 of file VisionDetectionGoal.hpp.
References wb_vision_detection_goal::sightingType.
to_string()
std::string guWhiteboard::VisionDetectionGoal::to_string () inline
USE_WB_VISION_DETECTION_GOAL_C_CONVERSION
Definition at line 246 of file VisionDetectionGoal.hpp.
References DoublePostGoal, NoGoalDetected, post1(), post2(), sightingType(), SinglePostGoal, guWhiteboard::VisionDetectionGoalPost::to_string(), VISION_DETECTION_GOAL_TO_STRING_BUFFER_SIZE, and wb_vision_detection_goal_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/VisionDetectionGoal.hpp