gusimplewhiteboard: guWhiteboard::DominantFrequencies Class Reference
guWhiteboard::DominantFrequencies Class Reference
Provides a C++ wrapper around wb_dominant_frequencies.
#include <DominantFrequencies.hpp>
Public Member Functions
DominantFrequencies (struct wb_r_m_s_levels t_rms=wb_r_m_s_levels(), const struct wb_microphone_frequencies t_frequencies[static_cast< int >(((GU_SIMPLE_WHITEBOARD_BUFSIZE - sizeof(struct wb_r_m_s_levels))/sizeof(struct wb_microphone_frequencies)))]=NULLPTR)
Create a new DominantFrequencies.
DominantFrequencies (const DominantFrequencies &t_other)
Copy Constructor.
DominantFrequencies (const struct wb_dominant_frequencies &t_other)
Copy Constructor.
DominantFrequencies & operator= (const DominantFrequencies &t_other)
Copy Assignment Operator.
DominantFrequencies & operator= (const struct wb_dominant_frequencies &t_other)
Copy Assignment Operator.
bool operator== (const DominantFrequencies &t_other) const
bool operator!= (const DominantFrequencies &t_other) const
bool operator== (const wb_dominant_frequencies &t_other) const
bool operator!= (const wb_dominant_frequencies &t_other) const
RMSLevels & rms ()
const RMSLevels & rms () const
void set_rms (const RMSLevels &t_newValue)
const MicrophoneFrequencies * frequencies () const
size_t frequencies_size () const
MicrophoneFrequencies & frequencies (int t_i)
const MicrophoneFrequencies & frequencies (int t_i) const
void set_frequencies (const MicrophoneFrequencies *t_newValue)
void set_frequencies (const MicrophoneFrequencies &t_newValue, int t_i)
DominantFrequencies (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Static Public Member Functions
static int num_frequencies ()
WHITEBOARD_POSTER_STRING_CONVERSION.
Additional Inherited Members
Public Attributes inherited from wb_dominant_frequencies
struct wb_r_m_s_levels rms
RMS levels of dominant frequency.
struct wb_microphone_frequencies frequencies [static_cast< int >(((GU_SIMPLE_WHITEBOARD_BUFSIZE - sizeof(struct wb_r_m_s_levels))/sizeof(struct wb_microphone_frequencies)))]
dominant frequencies
Detailed Description
Provides a C++ wrapper around wb_dominant_frequencies.
Definition at line 86 of file DominantFrequencies.hpp.
Constructor & Destructor Documentation
DominantFrequencies() [1/4]
guWhiteboard::DominantFrequencies::DominantFrequencies (struct wb_r_m_s_levels t_rms = wb_r_m_s_levels(), const struct wb_microphone_frequencies t_frequencies[static_cast< int >(((GU_SIMPLE_WHITEBOARD_BUFSIZE - sizeof(struct wb_r_m_s_levels))/sizeof(struct wb_microphone_frequencies)))] = NULLPTR) inline
Create a new DominantFrequencies.
Definition at line 108 of file DominantFrequencies.hpp.
Referenced by operator==().
DominantFrequencies() [2/4]
guWhiteboard::DominantFrequencies::DominantFrequencies (const DominantFrequencies & t_other) inline
Copy Constructor.
Definition at line 115 of file DominantFrequencies.hpp.
References frequencies(), and rms().
DominantFrequencies() [3/4]
guWhiteboard::DominantFrequencies::DominantFrequencies (const struct wb_dominant_frequencies & t_other) inline
Copy Constructor.
Definition at line 122 of file DominantFrequencies.hpp.
References wb_dominant_frequencies::frequencies, and wb_dominant_frequencies::rms.
DominantFrequencies() [4/4]
guWhiteboard::DominantFrequencies::DominantFrequencies (const std::string & t_str) inline
String Constructor.
Definition at line 219 of file DominantFrequencies.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::DominantFrequencies::description () inline
USE_WB_DOMINANT_FREQUENCIES_C_CONVERSION
Definition at line 224 of file DominantFrequencies.hpp.
References description(), guWhiteboard::RMSLevels::description(), DOMINANT_FREQUENCIES_DESC_BUFFER_SIZE, DOMINANT_FREQUENCIES_FREQUENCIES_ARRAY_SIZE, frequencies(), rms(), and wb_dominant_frequencies_description().
Referenced by description().
frequencies() [1/3]
const MicrophoneFrequencies * guWhiteboard::DominantFrequencies::frequencies () const inline
Definition at line 185 of file DominantFrequencies.hpp.
References wb_dominant_frequencies::frequencies.
Referenced by DominantFrequencies(), description(), operator=(), operator==(), and to_string().
frequencies() [2/3]
MicrophoneFrequencies & guWhiteboard::DominantFrequencies::frequencies (int t_i) inline
Definition at line 195 of file DominantFrequencies.hpp.
References wb_dominant_frequencies::frequencies.
frequencies() [3/3]
const MicrophoneFrequencies & guWhiteboard::DominantFrequencies::frequencies (int t_i) const inline
Definition at line 200 of file DominantFrequencies.hpp.
References wb_dominant_frequencies::frequencies.
frequencies_size()
size_t guWhiteboard::DominantFrequencies::frequencies_size () const inline
Definition at line 190 of file DominantFrequencies.hpp.
References DOMINANT_FREQUENCIES_FREQUENCIES_ARRAY_SIZE.
from_string()
void guWhiteboard::DominantFrequencies::from_string (const std::string & t_str) inline
USE_WB_DOMINANT_FREQUENCIES_C_CONVERSION
Definition at line 270 of file DominantFrequencies.hpp.
References DOMINANT_FREQUENCIES_DESC_BUFFER_SIZE, DOMINANT_FREQUENCIES_FREQUENCIES_ARRAY_SIZE, guWhiteboard::MicrophoneFrequencies::from_string(), guWhiteboard::RMSLevels::from_string(), set_frequencies(), and set_rms().
Referenced by DominantFrequencies().
num_frequencies()
static int guWhiteboard::DominantFrequencies::num_frequencies () inline static
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 433 of file DominantFrequencies.hpp.
References DOMINANT_NUMFREQi.
operator!=() [1/2]
bool guWhiteboard::DominantFrequencies::operator!= (const DominantFrequencies & t_other) const inline
Definition at line 155 of file DominantFrequencies.hpp.
operator!=() [2/2]
bool guWhiteboard::DominantFrequencies::operator!= (const wb_dominant_frequencies & t_other) const inline
Definition at line 165 of file DominantFrequencies.hpp.
operator=() [1/2]
DominantFrequencies & guWhiteboard::DominantFrequencies::operator= (const DominantFrequencies & t_other) inline
Copy Assignment Operator.
Definition at line 129 of file DominantFrequencies.hpp.
References frequencies(), and rms().
operator=() [2/2]
DominantFrequencies & guWhiteboard::DominantFrequencies::operator= (const struct wb_dominant_frequencies & t_other) inline
Copy Assignment Operator.
Definition at line 137 of file DominantFrequencies.hpp.
References wb_dominant_frequencies::frequencies, and wb_dominant_frequencies::rms.
operator==() [1/2]
bool guWhiteboard::DominantFrequencies::operator== (const DominantFrequencies & t_other) const inline
Definition at line 142 of file DominantFrequencies.hpp.
References DOMINANT_NUMFREQi, frequencies(), and rms().
operator==() [2/2]
bool guWhiteboard::DominantFrequencies::operator== (const wb_dominant_frequencies & t_other) const inline
Definition at line 160 of file DominantFrequencies.hpp.
References DominantFrequencies().
rms() [1/2]
RMSLevels & guWhiteboard::DominantFrequencies::rms () inline
Definition at line 170 of file DominantFrequencies.hpp.
References wb_dominant_frequencies::rms.
Referenced by DominantFrequencies(), description(), operator=(), operator==(), and to_string().
rms() [2/2]
const RMSLevels & guWhiteboard::DominantFrequencies::rms () const inline
Definition at line 175 of file DominantFrequencies.hpp.
References wb_dominant_frequencies::rms.
set_frequencies() [1/2]
void guWhiteboard::DominantFrequencies::set_frequencies (const MicrophoneFrequencies & t_newValue, int t_i) inline
Definition at line 210 of file DominantFrequencies.hpp.
References wb_dominant_frequencies::frequencies.
set_frequencies() [2/2]
void guWhiteboard::DominantFrequencies::set_frequencies (const MicrophoneFrequencies * t_newValue) inline
Definition at line 205 of file DominantFrequencies.hpp.
References DOMINANT_FREQUENCIES_FREQUENCIES_ARRAY_SIZE, and wb_dominant_frequencies::frequencies.
Referenced by from_string().
set_rms()
void guWhiteboard::DominantFrequencies::set_rms (const RMSLevels & t_newValue) inline
Definition at line 180 of file DominantFrequencies.hpp.
References wb_dominant_frequencies::rms.
Referenced by from_string().
to_string()
std::string guWhiteboard::DominantFrequencies::to_string () inline
USE_WB_DOMINANT_FREQUENCIES_C_CONVERSION
Definition at line 245 of file DominantFrequencies.hpp.
References DOMINANT_FREQUENCIES_FREQUENCIES_ARRAY_SIZE, DOMINANT_FREQUENCIES_TO_STRING_BUFFER_SIZE, frequencies(), rms(), to_string(), guWhiteboard::RMSLevels::to_string(), and wb_dominant_frequencies_to_string().
Referenced by to_string().
The documentation for this class was generated from the following file:
typeClassDefs/DominantFrequencies.hpp