gusimplewhiteboard: guWhiteboard::NaoJointListFloat Class Reference
guWhiteboard::NaoJointListFloat Class Reference
Provides a C++ wrapper around wb_nao_joint_list_float.
#include <NaoJointListFloat.hpp>
Public Member Functions
NaoJointListFloat (float t_HeadYaw=0.0f, float t_HeadPitch=0.0f, float t_LShoulderPitch=0.0f, float t_LShoulderRoll=0.0f, float t_LElbowYaw=0.0f, float t_LElbowRoll=0.0f, float t_LWristYaw=0.0f, float t_LHand=0.0f, float t_RShoulderPitch=0.0f, float t_RShoulderRoll=0.0f, float t_RElbowYaw=0.0f, float t_RElbowRoll=0.0f, float t_RWristYaw=0.0f, float t_RHand=0.0f, float t_LHipYawPitch=0.0f, float t_LHipRoll=0.0f, float t_LHipPitch=0.0f, float t_LKneePitch=0.0f, float t_LAnklePitch=0.0f, float t_LAnkleRoll=0.0f, float t_RHipRoll=0.0f, float t_RHipPitch=0.0f, float t_RKneePitch=0.0f, float t_RAnklePitch=0.0f, float t_RAnkleRoll=0.0f)
Create a new NaoJointListFloat.
NaoJointListFloat (const NaoJointListFloat &t_other)
Copy Constructor.
NaoJointListFloat (const struct wb_nao_joint_list_float &t_other)
Copy Constructor.
NaoJointListFloat & operator= (const NaoJointListFloat &t_other)
Copy Assignment Operator.
NaoJointListFloat & operator= (const struct wb_nao_joint_list_float &t_other)
Copy Assignment Operator.
bool operator== (const NaoJointListFloat &t_other) const
bool operator!= (const NaoJointListFloat &t_other) const
bool operator== (const wb_nao_joint_list_float &t_other) const
bool operator!= (const wb_nao_joint_list_float &t_other) const
float & HeadYaw ()
const float & HeadYaw () const
void set_HeadYaw (const float &t_newValue)
float & HeadPitch ()
const float & HeadPitch () const
void set_HeadPitch (const float &t_newValue)
float & LShoulderPitch ()
const float & LShoulderPitch () const
void set_LShoulderPitch (const float &t_newValue)
float & LShoulderRoll ()
const float & LShoulderRoll () const
void set_LShoulderRoll (const float &t_newValue)
float & LElbowYaw ()
const float & LElbowYaw () const
void set_LElbowYaw (const float &t_newValue)
float & LElbowRoll ()
const float & LElbowRoll () const
void set_LElbowRoll (const float &t_newValue)
float & LWristYaw ()
const float & LWristYaw () const
void set_LWristYaw (const float &t_newValue)
float & LHand ()
const float & LHand () const
void set_LHand (const float &t_newValue)
float & RShoulderPitch ()
const float & RShoulderPitch () const
void set_RShoulderPitch (const float &t_newValue)
float & RShoulderRoll ()
const float & RShoulderRoll () const
void set_RShoulderRoll (const float &t_newValue)
float & RElbowYaw ()
const float & RElbowYaw () const
void set_RElbowYaw (const float &t_newValue)
float & RElbowRoll ()
const float & RElbowRoll () const
void set_RElbowRoll (const float &t_newValue)
float & RWristYaw ()
const float & RWristYaw () const
void set_RWristYaw (const float &t_newValue)
float & RHand ()
const float & RHand () const
void set_RHand (const float &t_newValue)
float & LHipYawPitch ()
const float & LHipYawPitch () const
void set_LHipYawPitch (const float &t_newValue)
float & LHipRoll ()
const float & LHipRoll () const
void set_LHipRoll (const float &t_newValue)
float & LHipPitch ()
const float & LHipPitch () const
void set_LHipPitch (const float &t_newValue)
float & LKneePitch ()
const float & LKneePitch () const
void set_LKneePitch (const float &t_newValue)
float & LAnklePitch ()
const float & LAnklePitch () const
void set_LAnklePitch (const float &t_newValue)
float & LAnkleRoll ()
const float & LAnkleRoll () const
void set_LAnkleRoll (const float &t_newValue)
float & RHipRoll ()
const float & RHipRoll () const
void set_RHipRoll (const float &t_newValue)
float & RHipPitch ()
const float & RHipPitch () const
void set_RHipPitch (const float &t_newValue)
float & RKneePitch ()
const float & RKneePitch () const
void set_RKneePitch (const float &t_newValue)
float & RAnklePitch ()
const float & RAnklePitch () const
void set_RAnklePitch (const float &t_newValue)
float & RAnkleRoll ()
const float & RAnkleRoll () const
void set_RAnkleRoll (const float &t_newValue)
NaoJointListFloat (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_nao_joint_list_float
float HeadYaw
float HeadPitch
float LShoulderPitch
float LShoulderRoll
float LElbowYaw
float LElbowRoll
float LWristYaw
float LHand
float RShoulderPitch
float RShoulderRoll
float RElbowYaw
float RElbowRoll
float RWristYaw
float RHand
float LHipYawPitch
float LHipRoll
float LHipPitch
float LKneePitch
float LAnklePitch
float LAnkleRoll
float RHipRoll
float RHipPitch
float RKneePitch
float RAnklePitch
float RAnkleRoll
Detailed Description
Provides a C++ wrapper around wb_nao_joint_list_float.
Definition at line 84 of file NaoJointListFloat.hpp.
Constructor & Destructor Documentation
NaoJointListFloat() [1/4]
guWhiteboard::NaoJointListFloat::NaoJointListFloat (float t_HeadYaw = 0.0f, float t_HeadPitch = 0.0f, float t_LShoulderPitch = 0.0f, float t_LShoulderRoll = 0.0f, float t_LElbowYaw = 0.0f, float t_LElbowRoll = 0.0f, float t_LWristYaw = 0.0f, float t_LHand = 0.0f, float t_RShoulderPitch = 0.0f, float t_RShoulderRoll = 0.0f, float t_RElbowYaw = 0.0f, float t_RElbowRoll = 0.0f, float t_RWristYaw = 0.0f, float t_RHand = 0.0f, float t_LHipYawPitch = 0.0f, float t_LHipRoll = 0.0f, float t_LHipPitch = 0.0f, float t_LKneePitch = 0.0f, float t_LAnklePitch = 0.0f, float t_LAnkleRoll = 0.0f, float t_RHipRoll = 0.0f, float t_RHipPitch = 0.0f, float t_RKneePitch = 0.0f, float t_RAnklePitch = 0.0f, float t_RAnkleRoll = 0.0f) inline
Create a new NaoJointListFloat.
Definition at line 124 of file NaoJointListFloat.hpp.
Referenced by operator==().
NaoJointListFloat() [2/4]
guWhiteboard::NaoJointListFloat::NaoJointListFloat (const NaoJointListFloat & t_other) inline
Copy Constructor.
Definition at line 131 of file NaoJointListFloat.hpp.
References HeadPitch(), HeadYaw(), LAnklePitch(), LAnkleRoll(), LElbowRoll(), LElbowYaw(), LHand(), LHipPitch(), LHipRoll(), LHipYawPitch(), LKneePitch(), LShoulderPitch(), LShoulderRoll(), LWristYaw(), RAnklePitch(), RAnkleRoll(), RElbowRoll(), RElbowYaw(), RHand(), RHipPitch(), RHipRoll(), RKneePitch(), RShoulderPitch(), RShoulderRoll(), and RWristYaw().
NaoJointListFloat() [3/4]
guWhiteboard::NaoJointListFloat::NaoJointListFloat (const struct wb_nao_joint_list_float & t_other) inline
Copy Constructor.
Definition at line 138 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::HeadPitch, wb_nao_joint_list_float::HeadYaw, wb_nao_joint_list_float::LAnklePitch, wb_nao_joint_list_float::LAnkleRoll, wb_nao_joint_list_float::LElbowRoll, wb_nao_joint_list_float::LElbowYaw, wb_nao_joint_list_float::LHand, wb_nao_joint_list_float::LHipPitch, wb_nao_joint_list_float::LHipRoll, wb_nao_joint_list_float::LHipYawPitch, wb_nao_joint_list_float::LKneePitch, wb_nao_joint_list_float::LShoulderPitch, wb_nao_joint_list_float::LShoulderRoll, wb_nao_joint_list_float::LWristYaw, wb_nao_joint_list_float::RAnklePitch, wb_nao_joint_list_float::RAnkleRoll, wb_nao_joint_list_float::RElbowRoll, wb_nao_joint_list_float::RElbowYaw, wb_nao_joint_list_float::RHand, wb_nao_joint_list_float::RHipPitch, wb_nao_joint_list_float::RHipRoll, wb_nao_joint_list_float::RKneePitch, wb_nao_joint_list_float::RShoulderPitch, wb_nao_joint_list_float::RShoulderRoll, and wb_nao_joint_list_float::RWristYaw.
NaoJointListFloat() [4/4]
guWhiteboard::NaoJointListFloat::NaoJointListFloat (const std::string & t_str) inline
String Constructor.
Definition at line 581 of file NaoJointListFloat.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::NaoJointListFloat::description () inline
USE_WB_NAO_JOINT_LIST_FLOAT_C_CONVERSION
Definition at line 586 of file NaoJointListFloat.hpp.
References HeadPitch(), HeadYaw(), LAnklePitch(), LAnkleRoll(), LElbowRoll(), LElbowYaw(), LHand(), LHipPitch(), LHipRoll(), LHipYawPitch(), LKneePitch(), LShoulderPitch(), LShoulderRoll(), LWristYaw(), NAO_JOINT_LIST_FLOAT_DESC_BUFFER_SIZE, RAnklePitch(), RAnkleRoll(), RElbowRoll(), RElbowYaw(), RHand(), RHipPitch(), RHipRoll(), RKneePitch(), RShoulderPitch(), RShoulderRoll(), RWristYaw(), and wb_nao_joint_list_float_description().
from_string()
void guWhiteboard::NaoJointListFloat::from_string (const std::string & t_str) inline
USE_WB_NAO_JOINT_LIST_FLOAT_C_CONVERSION
Definition at line 712 of file NaoJointListFloat.hpp.
References NAO_JOINT_LIST_FLOAT_DESC_BUFFER_SIZE, set_HeadPitch(), set_HeadYaw(), set_LAnklePitch(), set_LAnkleRoll(), set_LElbowRoll(), set_LElbowYaw(), set_LHand(), set_LHipPitch(), set_LHipRoll(), set_LHipYawPitch(), set_LKneePitch(), set_LShoulderPitch(), set_LShoulderRoll(), set_LWristYaw(), set_RAnklePitch(), set_RAnkleRoll(), set_RElbowRoll(), set_RElbowYaw(), set_RHand(), set_RHipPitch(), set_RHipRoll(), set_RKneePitch(), set_RShoulderPitch(), set_RShoulderRoll(), and set_RWristYaw().
Referenced by NaoJointListFloat().
HeadPitch() [1/2]
float & guWhiteboard::NaoJointListFloat::HeadPitch () inline
Definition at line 217 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::HeadPitch.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
HeadPitch() [2/2]
const float & guWhiteboard::NaoJointListFloat::HeadPitch () const inline
Definition at line 222 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::HeadPitch.
HeadYaw() [1/2]
float & guWhiteboard::NaoJointListFloat::HeadYaw () inline
Definition at line 202 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::HeadYaw.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
HeadYaw() [2/2]
const float & guWhiteboard::NaoJointListFloat::HeadYaw () const inline
Definition at line 207 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::HeadYaw.
LAnklePitch() [1/2]
float & guWhiteboard::NaoJointListFloat::LAnklePitch () inline
Definition at line 472 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LAnklePitch.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
LAnklePitch() [2/2]
const float & guWhiteboard::NaoJointListFloat::LAnklePitch () const inline
Definition at line 477 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LAnklePitch.
LAnkleRoll() [1/2]
float & guWhiteboard::NaoJointListFloat::LAnkleRoll () inline
Definition at line 487 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LAnkleRoll.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
LAnkleRoll() [2/2]
const float & guWhiteboard::NaoJointListFloat::LAnkleRoll () const inline
Definition at line 492 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LAnkleRoll.
LElbowRoll() [1/2]
float & guWhiteboard::NaoJointListFloat::LElbowRoll () inline
Definition at line 277 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LElbowRoll.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
LElbowRoll() [2/2]
const float & guWhiteboard::NaoJointListFloat::LElbowRoll () const inline
Definition at line 282 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LElbowRoll.
LElbowYaw() [1/2]
float & guWhiteboard::NaoJointListFloat::LElbowYaw () inline
Definition at line 262 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LElbowYaw.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
LElbowYaw() [2/2]
const float & guWhiteboard::NaoJointListFloat::LElbowYaw () const inline
Definition at line 267 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LElbowYaw.
LHand() [1/2]
float & guWhiteboard::NaoJointListFloat::LHand () inline
Definition at line 307 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LHand.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
LHand() [2/2]
const float & guWhiteboard::NaoJointListFloat::LHand () const inline
Definition at line 312 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LHand.
LHipPitch() [1/2]
float & guWhiteboard::NaoJointListFloat::LHipPitch () inline
Definition at line 442 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LHipPitch.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
LHipPitch() [2/2]
const float & guWhiteboard::NaoJointListFloat::LHipPitch () const inline
Definition at line 447 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LHipPitch.
LHipRoll() [1/2]
float & guWhiteboard::NaoJointListFloat::LHipRoll () inline
Definition at line 427 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LHipRoll.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
LHipRoll() [2/2]
const float & guWhiteboard::NaoJointListFloat::LHipRoll () const inline
Definition at line 432 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LHipRoll.
LHipYawPitch() [1/2]
float & guWhiteboard::NaoJointListFloat::LHipYawPitch () inline
Definition at line 412 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LHipYawPitch.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
LHipYawPitch() [2/2]
const float & guWhiteboard::NaoJointListFloat::LHipYawPitch () const inline
Definition at line 417 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LHipYawPitch.
LKneePitch() [1/2]
float & guWhiteboard::NaoJointListFloat::LKneePitch () inline
Definition at line 457 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LKneePitch.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
LKneePitch() [2/2]
const float & guWhiteboard::NaoJointListFloat::LKneePitch () const inline
Definition at line 462 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LKneePitch.
LShoulderPitch() [1/2]
float & guWhiteboard::NaoJointListFloat::LShoulderPitch () inline
Definition at line 232 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LShoulderPitch.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
LShoulderPitch() [2/2]
const float & guWhiteboard::NaoJointListFloat::LShoulderPitch () const inline
Definition at line 237 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LShoulderPitch.
LShoulderRoll() [1/2]
float & guWhiteboard::NaoJointListFloat::LShoulderRoll () inline
Definition at line 247 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LShoulderRoll.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
LShoulderRoll() [2/2]
const float & guWhiteboard::NaoJointListFloat::LShoulderRoll () const inline
Definition at line 252 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LShoulderRoll.
LWristYaw() [1/2]
float & guWhiteboard::NaoJointListFloat::LWristYaw () inline
Definition at line 292 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LWristYaw.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
LWristYaw() [2/2]
const float & guWhiteboard::NaoJointListFloat::LWristYaw () const inline
Definition at line 297 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LWristYaw.
operator!=() [1/2]
bool guWhiteboard::NaoJointListFloat::operator!= (const NaoJointListFloat & t_other) const inline
Definition at line 187 of file NaoJointListFloat.hpp.
operator!=() [2/2]
bool guWhiteboard::NaoJointListFloat::operator!= (const wb_nao_joint_list_float & t_other) const inline
Definition at line 197 of file NaoJointListFloat.hpp.
operator=() [1/2]
NaoJointListFloat & guWhiteboard::NaoJointListFloat::operator= (const NaoJointListFloat & t_other) inline
Copy Assignment Operator.
Definition at line 145 of file NaoJointListFloat.hpp.
References HeadPitch(), HeadYaw(), LAnklePitch(), LAnkleRoll(), LElbowRoll(), LElbowYaw(), LHand(), LHipPitch(), LHipRoll(), LHipYawPitch(), LKneePitch(), LShoulderPitch(), LShoulderRoll(), LWristYaw(), RAnklePitch(), RAnkleRoll(), RElbowRoll(), RElbowYaw(), RHand(), RHipPitch(), RHipRoll(), RKneePitch(), RShoulderPitch(), RShoulderRoll(), and RWristYaw().
operator=() [2/2]
NaoJointListFloat & guWhiteboard::NaoJointListFloat::operator= (const struct wb_nao_joint_list_float & t_other) inline
Copy Assignment Operator.
Definition at line 153 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::HeadPitch, wb_nao_joint_list_float::HeadYaw, wb_nao_joint_list_float::LAnklePitch, wb_nao_joint_list_float::LAnkleRoll, wb_nao_joint_list_float::LElbowRoll, wb_nao_joint_list_float::LElbowYaw, wb_nao_joint_list_float::LHand, wb_nao_joint_list_float::LHipPitch, wb_nao_joint_list_float::LHipRoll, wb_nao_joint_list_float::LHipYawPitch, wb_nao_joint_list_float::LKneePitch, wb_nao_joint_list_float::LShoulderPitch, wb_nao_joint_list_float::LShoulderRoll, wb_nao_joint_list_float::LWristYaw, wb_nao_joint_list_float::RAnklePitch, wb_nao_joint_list_float::RAnkleRoll, wb_nao_joint_list_float::RElbowRoll, wb_nao_joint_list_float::RElbowYaw, wb_nao_joint_list_float::RHand, wb_nao_joint_list_float::RHipPitch, wb_nao_joint_list_float::RHipRoll, wb_nao_joint_list_float::RKneePitch, wb_nao_joint_list_float::RShoulderPitch, wb_nao_joint_list_float::RShoulderRoll, and wb_nao_joint_list_float::RWristYaw.
operator==() [1/2]
bool guWhiteboard::NaoJointListFloat::operator== (const NaoJointListFloat & t_other) const inline
Definition at line 158 of file NaoJointListFloat.hpp.
References HeadPitch(), HeadYaw(), LAnklePitch(), LAnkleRoll(), LElbowRoll(), LElbowYaw(), LHand(), LHipPitch(), LHipRoll(), LHipYawPitch(), LKneePitch(), LShoulderPitch(), LShoulderRoll(), LWristYaw(), RAnklePitch(), RAnkleRoll(), RElbowRoll(), RElbowYaw(), RHand(), RHipPitch(), RHipRoll(), RKneePitch(), RShoulderPitch(), RShoulderRoll(), and RWristYaw().
operator==() [2/2]
bool guWhiteboard::NaoJointListFloat::operator== (const wb_nao_joint_list_float & t_other) const inline
Definition at line 192 of file NaoJointListFloat.hpp.
References NaoJointListFloat().
RAnklePitch() [1/2]
float & guWhiteboard::NaoJointListFloat::RAnklePitch () inline
Definition at line 547 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RAnklePitch.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
RAnklePitch() [2/2]
const float & guWhiteboard::NaoJointListFloat::RAnklePitch () const inline
Definition at line 552 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RAnklePitch.
RAnkleRoll() [1/2]
float & guWhiteboard::NaoJointListFloat::RAnkleRoll () inline
Definition at line 562 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RAnkleRoll.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
RAnkleRoll() [2/2]
const float & guWhiteboard::NaoJointListFloat::RAnkleRoll () const inline
Definition at line 567 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RAnkleRoll.
RElbowRoll() [1/2]
float & guWhiteboard::NaoJointListFloat::RElbowRoll () inline
Definition at line 367 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RElbowRoll.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
RElbowRoll() [2/2]
const float & guWhiteboard::NaoJointListFloat::RElbowRoll () const inline
Definition at line 372 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RElbowRoll.
RElbowYaw() [1/2]
float & guWhiteboard::NaoJointListFloat::RElbowYaw () inline
Definition at line 352 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RElbowYaw.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
RElbowYaw() [2/2]
const float & guWhiteboard::NaoJointListFloat::RElbowYaw () const inline
Definition at line 357 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RElbowYaw.
RHand() [1/2]
float & guWhiteboard::NaoJointListFloat::RHand () inline
Definition at line 397 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RHand.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
RHand() [2/2]
const float & guWhiteboard::NaoJointListFloat::RHand () const inline
Definition at line 402 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RHand.
RHipPitch() [1/2]
float & guWhiteboard::NaoJointListFloat::RHipPitch () inline
Definition at line 517 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RHipPitch.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
RHipPitch() [2/2]
const float & guWhiteboard::NaoJointListFloat::RHipPitch () const inline
Definition at line 522 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RHipPitch.
RHipRoll() [1/2]
float & guWhiteboard::NaoJointListFloat::RHipRoll () inline
Definition at line 502 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RHipRoll.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
RHipRoll() [2/2]
const float & guWhiteboard::NaoJointListFloat::RHipRoll () const inline
Definition at line 507 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RHipRoll.
RKneePitch() [1/2]
float & guWhiteboard::NaoJointListFloat::RKneePitch () inline
Definition at line 532 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RKneePitch.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
RKneePitch() [2/2]
const float & guWhiteboard::NaoJointListFloat::RKneePitch () const inline
Definition at line 537 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RKneePitch.
RShoulderPitch() [1/2]
float & guWhiteboard::NaoJointListFloat::RShoulderPitch () inline
Definition at line 322 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RShoulderPitch.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
RShoulderPitch() [2/2]
const float & guWhiteboard::NaoJointListFloat::RShoulderPitch () const inline
Definition at line 327 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RShoulderPitch.
RShoulderRoll() [1/2]
float & guWhiteboard::NaoJointListFloat::RShoulderRoll () inline
Definition at line 337 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RShoulderRoll.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
RShoulderRoll() [2/2]
const float & guWhiteboard::NaoJointListFloat::RShoulderRoll () const inline
Definition at line 342 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RShoulderRoll.
RWristYaw() [1/2]
float & guWhiteboard::NaoJointListFloat::RWristYaw () inline
Definition at line 382 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RWristYaw.
Referenced by NaoJointListFloat(), description(), operator=(), operator==(), and to_string().
RWristYaw() [2/2]
const float & guWhiteboard::NaoJointListFloat::RWristYaw () const inline
Definition at line 387 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RWristYaw.
set_HeadPitch()
void guWhiteboard::NaoJointListFloat::set_HeadPitch (const float & t_newValue) inline
Definition at line 227 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::HeadPitch.
Referenced by from_string().
set_HeadYaw()
void guWhiteboard::NaoJointListFloat::set_HeadYaw (const float & t_newValue) inline
Definition at line 212 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::HeadYaw.
Referenced by from_string().
set_LAnklePitch()
void guWhiteboard::NaoJointListFloat::set_LAnklePitch (const float & t_newValue) inline
Definition at line 482 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LAnklePitch.
Referenced by from_string().
set_LAnkleRoll()
void guWhiteboard::NaoJointListFloat::set_LAnkleRoll (const float & t_newValue) inline
Definition at line 497 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LAnkleRoll.
Referenced by from_string().
set_LElbowRoll()
void guWhiteboard::NaoJointListFloat::set_LElbowRoll (const float & t_newValue) inline
Definition at line 287 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LElbowRoll.
Referenced by from_string().
set_LElbowYaw()
void guWhiteboard::NaoJointListFloat::set_LElbowYaw (const float & t_newValue) inline
Definition at line 272 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LElbowYaw.
Referenced by from_string().
set_LHand()
void guWhiteboard::NaoJointListFloat::set_LHand (const float & t_newValue) inline
Definition at line 317 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LHand.
Referenced by from_string().
set_LHipPitch()
void guWhiteboard::NaoJointListFloat::set_LHipPitch (const float & t_newValue) inline
Definition at line 452 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LHipPitch.
Referenced by from_string().
set_LHipRoll()
void guWhiteboard::NaoJointListFloat::set_LHipRoll (const float & t_newValue) inline
Definition at line 437 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LHipRoll.
Referenced by from_string().
set_LHipYawPitch()
void guWhiteboard::NaoJointListFloat::set_LHipYawPitch (const float & t_newValue) inline
Definition at line 422 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LHipYawPitch.
Referenced by from_string().
set_LKneePitch()
void guWhiteboard::NaoJointListFloat::set_LKneePitch (const float & t_newValue) inline
Definition at line 467 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LKneePitch.
Referenced by from_string().
set_LShoulderPitch()
void guWhiteboard::NaoJointListFloat::set_LShoulderPitch (const float & t_newValue) inline
Definition at line 242 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LShoulderPitch.
Referenced by from_string().
set_LShoulderRoll()
void guWhiteboard::NaoJointListFloat::set_LShoulderRoll (const float & t_newValue) inline
Definition at line 257 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LShoulderRoll.
Referenced by from_string().
set_LWristYaw()
void guWhiteboard::NaoJointListFloat::set_LWristYaw (const float & t_newValue) inline
Definition at line 302 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::LWristYaw.
Referenced by from_string().
set_RAnklePitch()
void guWhiteboard::NaoJointListFloat::set_RAnklePitch (const float & t_newValue) inline
Definition at line 557 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RAnklePitch.
Referenced by from_string().
set_RAnkleRoll()
void guWhiteboard::NaoJointListFloat::set_RAnkleRoll (const float & t_newValue) inline
Definition at line 572 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RAnkleRoll.
Referenced by from_string().
set_RElbowRoll()
void guWhiteboard::NaoJointListFloat::set_RElbowRoll (const float & t_newValue) inline
Definition at line 377 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RElbowRoll.
Referenced by from_string().
set_RElbowYaw()
void guWhiteboard::NaoJointListFloat::set_RElbowYaw (const float & t_newValue) inline
Definition at line 362 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RElbowYaw.
Referenced by from_string().
set_RHand()
void guWhiteboard::NaoJointListFloat::set_RHand (const float & t_newValue) inline
Definition at line 407 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RHand.
Referenced by from_string().
set_RHipPitch()
void guWhiteboard::NaoJointListFloat::set_RHipPitch (const float & t_newValue) inline
Definition at line 527 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RHipPitch.
Referenced by from_string().
set_RHipRoll()
void guWhiteboard::NaoJointListFloat::set_RHipRoll (const float & t_newValue) inline
Definition at line 512 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RHipRoll.
Referenced by from_string().
set_RKneePitch()
void guWhiteboard::NaoJointListFloat::set_RKneePitch (const float & t_newValue) inline
Definition at line 542 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RKneePitch.
Referenced by from_string().
set_RShoulderPitch()
void guWhiteboard::NaoJointListFloat::set_RShoulderPitch (const float & t_newValue) inline
Definition at line 332 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RShoulderPitch.
Referenced by from_string().
set_RShoulderRoll()
void guWhiteboard::NaoJointListFloat::set_RShoulderRoll (const float & t_newValue) inline
Definition at line 347 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RShoulderRoll.
Referenced by from_string().
set_RWristYaw()
void guWhiteboard::NaoJointListFloat::set_RWristYaw (const float & t_newValue) inline
Definition at line 392 of file NaoJointListFloat.hpp.
References wb_nao_joint_list_float::RWristYaw.
Referenced by from_string().
to_string()
std::string guWhiteboard::NaoJointListFloat::to_string () inline
USE_WB_NAO_JOINT_LIST_FLOAT_C_CONVERSION
Definition at line 647 of file NaoJointListFloat.hpp.
References HeadPitch(), HeadYaw(), LAnklePitch(), LAnkleRoll(), LElbowRoll(), LElbowYaw(), LHand(), LHipPitch(), LHipRoll(), LHipYawPitch(), LKneePitch(), LShoulderPitch(), LShoulderRoll(), LWristYaw(), NAO_JOINT_LIST_FLOAT_TO_STRING_BUFFER_SIZE, RAnklePitch(), RAnkleRoll(), RElbowRoll(), RElbowYaw(), RHand(), RHipPitch(), RHipRoll(), RKneePitch(), RShoulderPitch(), RShoulderRoll(), RWristYaw(), and wb_nao_joint_list_float_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/NaoJointListFloat.hpp