gusimplewhiteboard: guWhiteboard::FilteredArrayBallSightings Class Reference
guWhiteboard::FilteredArrayBallSightings Class Reference
Provides a C++ wrapper around wb_filtered_arrayballsightings.
#include <FilteredArrayBallSightings.hpp>
Public Member Functions
FilteredArrayBallSightings (const struct wb_filtered_vision_object t_objects[2]=NULLPTR)
Create a new FilteredArrayBallSightings.
FilteredArrayBallSightings (const FilteredArrayBallSightings &t_other)
Copy Constructor.
FilteredArrayBallSightings (const struct wb_filtered_arrayballsightings &t_other)
Copy Constructor.
FilteredArrayBallSightings & operator= (const FilteredArrayBallSightings &t_other)
Copy Assignment Operator.
FilteredArrayBallSightings & operator= (const struct wb_filtered_arrayballsightings &t_other)
Copy Assignment Operator.
bool operator== (const FilteredArrayBallSightings &t_other) const
bool operator!= (const FilteredArrayBallSightings &t_other) const
bool operator== (const wb_filtered_arrayballsightings &t_other) const
bool operator!= (const wb_filtered_arrayballsightings &t_other) const
const FilteredVisionObject * objects () const
size_t objects_size () const
FilteredVisionObject & objects (int t_i)
const FilteredVisionObject & objects (int t_i) const
void set_objects (const FilteredVisionObject *t_newValue)
void set_objects (const FilteredVisionObject &t_newValue, int t_i)
FilteredArrayBallSightings (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_filtered_arrayballsightings
struct wb_filtered_vision_object objects [2]
the array containing filtered balls on separate cameras reported by vision FVO_NUM_CAMERAS =2
Detailed Description
Provides a C++ wrapper around wb_filtered_arrayballsightings.
Definition at line 85 of file FilteredArrayBallSightings.hpp.
Constructor & Destructor Documentation
FilteredArrayBallSightings() [1/4]
guWhiteboard::FilteredArrayBallSightings::FilteredArrayBallSightings (const struct wb_filtered_vision_object t_objects[2] = NULLPTR) inline
Create a new FilteredArrayBallSightings.
Definition at line 106 of file FilteredArrayBallSightings.hpp.
Referenced by operator==().
FilteredArrayBallSightings() [2/4]
guWhiteboard::FilteredArrayBallSightings::FilteredArrayBallSightings (const FilteredArrayBallSightings & t_other) inline
Copy Constructor.
Definition at line 113 of file FilteredArrayBallSightings.hpp.
References objects().
FilteredArrayBallSightings() [3/4]
guWhiteboard::FilteredArrayBallSightings::FilteredArrayBallSightings (const struct wb_filtered_arrayballsightings & t_other) inline
Copy Constructor.
Definition at line 120 of file FilteredArrayBallSightings.hpp.
References wb_filtered_arrayballsightings::objects.
FilteredArrayBallSightings() [4/4]
guWhiteboard::FilteredArrayBallSightings::FilteredArrayBallSightings (const std::string & t_str) inline
String Constructor.
Definition at line 198 of file FilteredArrayBallSightings.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::FilteredArrayBallSightings::description () inline
USE_WB_FILTERED_ARRAYBALLSIGHTINGS_C_CONVERSION
Definition at line 203 of file FilteredArrayBallSightings.hpp.
References description(), FILTERED_ARRAYBALLSIGHTINGS_DESC_BUFFER_SIZE, FILTERED_ARRAYBALLSIGHTINGS_OBJECTS_ARRAY_SIZE, objects(), and wb_filtered_arrayballsightings_description().
Referenced by description().
from_string()
void guWhiteboard::FilteredArrayBallSightings::from_string (const std::string & t_str) inline
USE_WB_FILTERED_ARRAYBALLSIGHTINGS_C_CONVERSION
Definition at line 245 of file FilteredArrayBallSightings.hpp.
References FILTERED_ARRAYBALLSIGHTINGS_DESC_BUFFER_SIZE, FILTERED_ARRAYBALLSIGHTINGS_OBJECTS_ARRAY_SIZE, guWhiteboard::FilteredVisionObject::from_string(), and set_objects().
Referenced by FilteredArrayBallSightings().
objects() [1/3]
const FilteredVisionObject * guWhiteboard::FilteredArrayBallSightings::objects () const inline
Definition at line 164 of file FilteredArrayBallSightings.hpp.
References wb_filtered_arrayballsightings::objects.
Referenced by FilteredArrayBallSightings(), description(), guWhiteboard::FilteredArrayOneDimBall::get_object(), operator=(), operator==(), guWhiteboard::FilteredArrayOneDimBall::set_objects(), and to_string().
objects() [2/3]
FilteredVisionObject & guWhiteboard::FilteredArrayBallSightings::objects (int t_i) inline
Definition at line 174 of file FilteredArrayBallSightings.hpp.
References wb_filtered_arrayballsightings::objects.
objects() [3/3]
const FilteredVisionObject & guWhiteboard::FilteredArrayBallSightings::objects (int t_i) const inline
Definition at line 179 of file FilteredArrayBallSightings.hpp.
References wb_filtered_arrayballsightings::objects.
objects_size()
size_t guWhiteboard::FilteredArrayBallSightings::objects_size () const inline
Definition at line 169 of file FilteredArrayBallSightings.hpp.
References FILTERED_ARRAYBALLSIGHTINGS_OBJECTS_ARRAY_SIZE.
operator!=() [1/2]
bool guWhiteboard::FilteredArrayBallSightings::operator!= (const FilteredArrayBallSightings & t_other) const inline
Definition at line 149 of file FilteredArrayBallSightings.hpp.
operator!=() [2/2]
bool guWhiteboard::FilteredArrayBallSightings::operator!= (const wb_filtered_arrayballsightings & t_other) const inline
Definition at line 159 of file FilteredArrayBallSightings.hpp.
operator=() [1/2]
FilteredArrayBallSightings & guWhiteboard::FilteredArrayBallSightings::operator= (const FilteredArrayBallSightings & t_other) inline
Copy Assignment Operator.
Definition at line 127 of file FilteredArrayBallSightings.hpp.
References objects().
operator=() [2/2]
FilteredArrayBallSightings & guWhiteboard::FilteredArrayBallSightings::operator= (const struct wb_filtered_arrayballsightings & t_other) inline
Copy Assignment Operator.
Definition at line 135 of file FilteredArrayBallSightings.hpp.
References wb_filtered_arrayballsightings::objects.
operator==() [1/2]
bool guWhiteboard::FilteredArrayBallSightings::operator== (const FilteredArrayBallSightings & t_other) const inline
Definition at line 140 of file FilteredArrayBallSightings.hpp.
References objects().
operator==() [2/2]
bool guWhiteboard::FilteredArrayBallSightings::operator== (const wb_filtered_arrayballsightings & t_other) const inline
Definition at line 154 of file FilteredArrayBallSightings.hpp.
References FilteredArrayBallSightings().
set_objects() [1/2]
void guWhiteboard::FilteredArrayBallSightings::set_objects (const FilteredVisionObject & t_newValue, int t_i) inline
Definition at line 189 of file FilteredArrayBallSightings.hpp.
References wb_filtered_arrayballsightings::objects.
set_objects() [2/2]
void guWhiteboard::FilteredArrayBallSightings::set_objects (const FilteredVisionObject * t_newValue) inline
Definition at line 184 of file FilteredArrayBallSightings.hpp.
References FILTERED_ARRAYBALLSIGHTINGS_OBJECTS_ARRAY_SIZE, and wb_filtered_arrayballsightings::objects.
Referenced by guWhiteboard::FilteredArrayOneDimBall::FilteredArrayOneDimBall(), from_string(), and guWhiteboard::FilteredArrayOneDimBall::set_object().
to_string()
std::string guWhiteboard::FilteredArrayBallSightings::to_string () inline
USE_WB_FILTERED_ARRAYBALLSIGHTINGS_C_CONVERSION
Definition at line 222 of file FilteredArrayBallSightings.hpp.
References FILTERED_ARRAYBALLSIGHTINGS_OBJECTS_ARRAY_SIZE, FILTERED_ARRAYBALLSIGHTINGS_TO_STRING_BUFFER_SIZE, objects(), to_string(), and wb_filtered_arrayballsightings_to_string().
Referenced by to_string().
The documentation for this class was generated from the following file:
typeClassDefs/FilteredArrayBallSightings.hpp