gusimplewhiteboard: guWhiteboard::RMSLevels Class Reference
guWhiteboard::RMSLevels Class Reference
Provides a C++ wrapper around wb_r_m_s_levels.
#include <RMSLevels.hpp>
Public Member Functions
RMSLevels (int16_t t_rear_left=0, int16_t t_rear_right=0, int16_t t_front_left=0, int16_t t_front_right=0)
Create a new RMSLevels.
RMSLevels (const RMSLevels &t_other)
Copy Constructor.
RMSLevels (const struct wb_r_m_s_levels &t_other)
Copy Constructor.
RMSLevels & operator= (const RMSLevels &t_other)
Copy Assignment Operator.
RMSLevels & operator= (const struct wb_r_m_s_levels &t_other)
Copy Assignment Operator.
bool operator== (const RMSLevels &t_other) const
bool operator!= (const RMSLevels &t_other) const
bool operator== (const wb_r_m_s_levels &t_other) const
bool operator!= (const wb_r_m_s_levels &t_other) const
int16_t & rear_left ()
const int16_t & rear_left () const
void set_rear_left (const int16_t &t_newValue)
int16_t & rear_right ()
const int16_t & rear_right () const
void set_rear_right (const int16_t &t_newValue)
int16_t & front_left ()
const int16_t & front_left () const
void set_front_left (const int16_t &t_newValue)
int16_t & front_right ()
const int16_t & front_right () const
void set_front_right (const int16_t &t_newValue)
RMSLevels (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_r_m_s_levels
int16_t rear_left
rear left RMS level
int16_t rear_right
rear right RMS level
int16_t front_left
front left RMS level
int16_t front_right
front left RMS level
Detailed Description
Provides a C++ wrapper around wb_r_m_s_levels.
Definition at line 83 of file RMSLevels.hpp.
Constructor & Destructor Documentation
RMSLevels() [1/4]
guWhiteboard::RMSLevels::RMSLevels (int16_t t_rear_left = 0, int16_t t_rear_right = 0, int16_t t_front_left = 0, int16_t t_front_right = 0) inline
Create a new RMSLevels.
Definition at line 102 of file RMSLevels.hpp.
Referenced by operator==().
RMSLevels() [2/4]
guWhiteboard::RMSLevels::RMSLevels (const RMSLevels & t_other) inline
Copy Constructor.
Definition at line 109 of file RMSLevels.hpp.
References front_left(), front_right(), rear_left(), and rear_right().
RMSLevels() [3/4]
guWhiteboard::RMSLevels::RMSLevels (const struct wb_r_m_s_levels & t_other) inline
Copy Constructor.
Definition at line 116 of file RMSLevels.hpp.
References wb_r_m_s_levels::front_left, wb_r_m_s_levels::front_right, wb_r_m_s_levels::rear_left, and wb_r_m_s_levels::rear_right.
RMSLevels() [4/4]
guWhiteboard::RMSLevels::RMSLevels (const std::string & t_str) inline
String Constructor.
Definition at line 223 of file RMSLevels.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::RMSLevels::description () inline
USE_WB_R_M_S_LEVELS_C_CONVERSION
Definition at line 228 of file RMSLevels.hpp.
References front_left(), front_right(), rear_left(), rear_right(), RMS_LEVELS_DESC_BUFFER_SIZE, and wb_r_m_s_levels_description().
Referenced by guWhiteboard::DominantFrequencies::description().
from_string()
void guWhiteboard::RMSLevels::from_string (const std::string & t_str) inline
USE_WB_R_M_S_LEVELS_C_CONVERSION
Definition at line 270 of file RMSLevels.hpp.
References RMS_LEVELS_DESC_BUFFER_SIZE, set_front_left(), set_front_right(), set_rear_left(), and set_rear_right().
Referenced by RMSLevels(), and guWhiteboard::DominantFrequencies::from_string().
front_left() [1/2]
int16_t & guWhiteboard::RMSLevels::front_left () inline
Definition at line 189 of file RMSLevels.hpp.
References wb_r_m_s_levels::front_left.
Referenced by RMSLevels(), description(), operator=(), operator==(), and to_string().
front_left() [2/2]
const int16_t & guWhiteboard::RMSLevels::front_left () const inline
Definition at line 194 of file RMSLevels.hpp.
References wb_r_m_s_levels::front_left.
front_right() [1/2]
int16_t & guWhiteboard::RMSLevels::front_right () inline
Definition at line 204 of file RMSLevels.hpp.
References wb_r_m_s_levels::front_right.
Referenced by RMSLevels(), description(), operator=(), operator==(), and to_string().
front_right() [2/2]
const int16_t & guWhiteboard::RMSLevels::front_right () const inline
Definition at line 209 of file RMSLevels.hpp.
References wb_r_m_s_levels::front_right.
operator!=() [1/2]
bool guWhiteboard::RMSLevels::operator!= (const RMSLevels & t_other) const inline
Definition at line 144 of file RMSLevels.hpp.
operator!=() [2/2]
bool guWhiteboard::RMSLevels::operator!= (const wb_r_m_s_levels & t_other) const inline
Definition at line 154 of file RMSLevels.hpp.
operator=() [1/2]
RMSLevels & guWhiteboard::RMSLevels::operator= (const RMSLevels & t_other) inline
Copy Assignment Operator.
Definition at line 123 of file RMSLevels.hpp.
References front_left(), front_right(), rear_left(), and rear_right().
operator=() [2/2]
RMSLevels & guWhiteboard::RMSLevels::operator= (const struct wb_r_m_s_levels & t_other) inline
Copy Assignment Operator.
Definition at line 131 of file RMSLevels.hpp.
References wb_r_m_s_levels::front_left, wb_r_m_s_levels::front_right, wb_r_m_s_levels::rear_left, and wb_r_m_s_levels::rear_right.
operator==() [1/2]
bool guWhiteboard::RMSLevels::operator== (const RMSLevels & t_other) const inline
Definition at line 136 of file RMSLevels.hpp.
References front_left(), front_right(), rear_left(), and rear_right().
operator==() [2/2]
bool guWhiteboard::RMSLevels::operator== (const wb_r_m_s_levels & t_other) const inline
Definition at line 149 of file RMSLevels.hpp.
References RMSLevels().
rear_left() [1/2]
int16_t & guWhiteboard::RMSLevels::rear_left () inline
Definition at line 159 of file RMSLevels.hpp.
References wb_r_m_s_levels::rear_left.
Referenced by RMSLevels(), description(), operator=(), operator==(), and to_string().
rear_left() [2/2]
const int16_t & guWhiteboard::RMSLevels::rear_left () const inline
Definition at line 164 of file RMSLevels.hpp.
References wb_r_m_s_levels::rear_left.
rear_right() [1/2]
int16_t & guWhiteboard::RMSLevels::rear_right () inline
Definition at line 174 of file RMSLevels.hpp.
References wb_r_m_s_levels::rear_right.
Referenced by RMSLevels(), description(), operator=(), operator==(), and to_string().
rear_right() [2/2]
const int16_t & guWhiteboard::RMSLevels::rear_right () const inline
Definition at line 179 of file RMSLevels.hpp.
References wb_r_m_s_levels::rear_right.
set_front_left()
void guWhiteboard::RMSLevels::set_front_left (const int16_t & t_newValue) inline
Definition at line 199 of file RMSLevels.hpp.
References wb_r_m_s_levels::front_left.
Referenced by from_string().
set_front_right()
void guWhiteboard::RMSLevels::set_front_right (const int16_t & t_newValue) inline
Definition at line 214 of file RMSLevels.hpp.
References wb_r_m_s_levels::front_right.
Referenced by from_string().
set_rear_left()
void guWhiteboard::RMSLevels::set_rear_left (const int16_t & t_newValue) inline
Definition at line 169 of file RMSLevels.hpp.
References wb_r_m_s_levels::rear_left.
Referenced by from_string().
set_rear_right()
void guWhiteboard::RMSLevels::set_rear_right (const int16_t & t_newValue) inline
Definition at line 184 of file RMSLevels.hpp.
References wb_r_m_s_levels::rear_right.
Referenced by from_string().
to_string()
std::string guWhiteboard::RMSLevels::to_string () inline
USE_WB_R_M_S_LEVELS_C_CONVERSION
Definition at line 247 of file RMSLevels.hpp.
References front_left(), front_right(), rear_left(), rear_right(), RMS_LEVELS_TO_STRING_BUFFER_SIZE, and wb_r_m_s_levels_to_string().
Referenced by guWhiteboard::DominantFrequencies::to_string().
The documentation for this class was generated from the following file:
typeClassDefs/RMSLevels.hpp