gusimplewhiteboard: guWhiteboard::VisionFieldFeature Class Reference
guWhiteboard::VisionFieldFeature Class Reference
Provides a C++ wrapper around wb_vision_field_feature.
#include <VisionFieldFeature.hpp>
Public Member Functions
VisionFieldFeature (struct wb_pixel_coordinate t_coordinate=wb_pixel_coordinate(), uint8_t t_camera=1)
Create a new VisionFieldFeature.
VisionFieldFeature (const VisionFieldFeature &t_other)
Copy Constructor.
VisionFieldFeature (const struct wb_vision_field_feature &t_other)
Copy Constructor.
VisionFieldFeature & operator= (const VisionFieldFeature &t_other)
Copy Assignment Operator.
VisionFieldFeature & operator= (const struct wb_vision_field_feature &t_other)
Copy Assignment Operator.
bool operator== (const VisionFieldFeature &t_other) const
bool operator!= (const VisionFieldFeature &t_other) const
bool operator== (const wb_vision_field_feature &t_other) const
bool operator!= (const wb_vision_field_feature &t_other) const
PixelCoordinate & coordinate ()
const PixelCoordinate & coordinate () const
void set_coordinate (const PixelCoordinate &t_newValue)
uint8_t & camera ()
const uint8_t & camera () const
void set_camera (const uint8_t &t_newValue)
VisionFieldFeature (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
GU::PixelCoordinate coordinatePixelCoordinate (const uint16_t resWidth, const uint16_t resHeight)
WHITEBOARD_POSTER_STRING_CONVERSION.
Additional Inherited Members
Public Attributes inherited from wb_vision_field_feature
struct wb_pixel_coordinate coordinate
The pixel coordinate.
uint8_t camera
camera it was seen on
Detailed Description
Provides a C++ wrapper around wb_vision_field_feature.
Definition at line 88 of file VisionFieldFeature.hpp.
Constructor & Destructor Documentation
VisionFieldFeature() [1/4]
guWhiteboard::VisionFieldFeature::VisionFieldFeature (struct wb_pixel_coordinate t_coordinate = wb_pixel_coordinate(), uint8_t t_camera = 1) inline
Create a new VisionFieldFeature.
Definition at line 105 of file VisionFieldFeature.hpp.
Referenced by operator==().
VisionFieldFeature() [2/4]
guWhiteboard::VisionFieldFeature::VisionFieldFeature (const VisionFieldFeature & t_other) inline
Copy Constructor.
Definition at line 112 of file VisionFieldFeature.hpp.
References camera(), and coordinate().
VisionFieldFeature() [3/4]
guWhiteboard::VisionFieldFeature::VisionFieldFeature (const struct wb_vision_field_feature & t_other) inline
Copy Constructor.
Definition at line 119 of file VisionFieldFeature.hpp.
References wb_vision_field_feature::camera, and wb_vision_field_feature::coordinate.
VisionFieldFeature() [4/4]
guWhiteboard::VisionFieldFeature::VisionFieldFeature (const std::string & t_str) inline
String Constructor.
Definition at line 194 of file VisionFieldFeature.hpp.
References from_string().
Member Function Documentation
camera() [1/2]
uint8_t & guWhiteboard::VisionFieldFeature::camera () inline
Definition at line 175 of file VisionFieldFeature.hpp.
References wb_vision_field_feature::camera.
Referenced by VisionFieldFeature(), description(), operator=(), operator==(), and to_string().
camera() [2/2]
const uint8_t & guWhiteboard::VisionFieldFeature::camera () const inline
Definition at line 180 of file VisionFieldFeature.hpp.
References wb_vision_field_feature::camera.
coordinate() [1/2]
PixelCoordinate & guWhiteboard::VisionFieldFeature::coordinate () inline
Definition at line 160 of file VisionFieldFeature.hpp.
References wb_vision_field_feature::coordinate.
Referenced by VisionFieldFeature(), coordinatePixelCoordinate(), description(), operator=(), operator==(), and to_string().
coordinate() [2/2]
const PixelCoordinate & guWhiteboard::VisionFieldFeature::coordinate () const inline
Definition at line 165 of file VisionFieldFeature.hpp.
References wb_vision_field_feature::coordinate.
coordinatePixelCoordinate()
GU::PixelCoordinate guWhiteboard::VisionFieldFeature::coordinatePixelCoordinate (const uint16_t resWidth, const uint16_t resHeight) inline
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 334 of file VisionFieldFeature.hpp.
References coordinate(), and guWhiteboard::PixelCoordinate::pixelCoordinate().
description()
std::string guWhiteboard::VisionFieldFeature::description () inline
USE_WB_VISION_FIELD_FEATURE_C_CONVERSION
Definition at line 199 of file VisionFieldFeature.hpp.
References camera(), coordinate(), guWhiteboard::PixelCoordinate::description(), VISION_FIELD_FEATURE_DESC_BUFFER_SIZE, and wb_vision_field_feature_description().
from_string()
void guWhiteboard::VisionFieldFeature::from_string (const std::string & t_str) inline
USE_WB_VISION_FIELD_FEATURE_C_CONVERSION
Definition at line 233 of file VisionFieldFeature.hpp.
References guWhiteboard::PixelCoordinate::from_string(), set_camera(), set_coordinate(), and VISION_FIELD_FEATURE_DESC_BUFFER_SIZE.
Referenced by VisionFieldFeature(), and guWhiteboard::VisionFieldFeatures::from_string().
operator!=() [1/2]
bool guWhiteboard::VisionFieldFeature::operator!= (const VisionFieldFeature & t_other) const inline
Definition at line 145 of file VisionFieldFeature.hpp.
operator!=() [2/2]
bool guWhiteboard::VisionFieldFeature::operator!= (const wb_vision_field_feature & t_other) const inline
Definition at line 155 of file VisionFieldFeature.hpp.
operator=() [1/2]
VisionFieldFeature & guWhiteboard::VisionFieldFeature::operator= (const struct wb_vision_field_feature & t_other) inline
Copy Assignment Operator.
Definition at line 134 of file VisionFieldFeature.hpp.
References wb_vision_field_feature::camera, and wb_vision_field_feature::coordinate.
operator=() [2/2]
VisionFieldFeature & guWhiteboard::VisionFieldFeature::operator= (const VisionFieldFeature & t_other) inline
Copy Assignment Operator.
Definition at line 126 of file VisionFieldFeature.hpp.
References camera(), and coordinate().
operator==() [1/2]
bool guWhiteboard::VisionFieldFeature::operator== (const VisionFieldFeature & t_other) const inline
Definition at line 139 of file VisionFieldFeature.hpp.
References camera(), and coordinate().
operator==() [2/2]
bool guWhiteboard::VisionFieldFeature::operator== (const wb_vision_field_feature & t_other) const inline
Definition at line 150 of file VisionFieldFeature.hpp.
References VisionFieldFeature().
set_camera()
void guWhiteboard::VisionFieldFeature::set_camera (const uint8_t & t_newValue) inline
Definition at line 185 of file VisionFieldFeature.hpp.
References wb_vision_field_feature::camera.
Referenced by from_string().
set_coordinate()
void guWhiteboard::VisionFieldFeature::set_coordinate (const PixelCoordinate & t_newValue) inline
Definition at line 170 of file VisionFieldFeature.hpp.
References wb_vision_field_feature::coordinate.
Referenced by from_string().
to_string()
std::string guWhiteboard::VisionFieldFeature::to_string () inline
USE_WB_VISION_FIELD_FEATURE_C_CONVERSION
Definition at line 214 of file VisionFieldFeature.hpp.
References camera(), coordinate(), guWhiteboard::PixelCoordinate::to_string(), VISION_FIELD_FEATURE_TO_STRING_BUFFER_SIZE, and wb_vision_field_feature_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/VisionFieldFeature.hpp