gusimplewhiteboard: guWhiteboard::SensorsBodySensors Class Reference
guWhiteboard::SensorsBodySensors Class Reference
Provides a C++ wrapper around wb_sensors_body_sensors.
#include <SensorsBodySensors.hpp>
Public Member Functions
SensorsBodySensors (signed int t_DCM_Time=0, float t_InertialSensor_AccX=0.0f, float t_InertialSensor_AccY=0.0f, float t_InertialSensor_AccZ=0.0f, float t_InertialSensor_GyrX=0.0f, float t_InertialSensor_GyrY=0.0f, float t_InertialSensor_GyrZ=0.0f, float t_InertialSensor_AngleX=0.0f, float t_InertialSensor_AngleY=0.0f, float t_InertialSensor_AngleZ=0.0f, float t_InertialSensor_AccelerometerX=0.0f, float t_InertialSensor_AccelerometerY=0.0f, float t_InertialSensor_AccelerometerZ=0.0f, float t_InertialSensor_GyroscopeX=0.0f, float t_InertialSensor_GyroscopeY=0.0f, float t_InertialSensor_GyroscopeZ=0.0f, uint8_t t_Battery_Charge=0, uint8_t t_Battery_Current=0, float t_US=0.0f, bool t_ChestBoard_Button=true)
Create a new SensorsBodySensors.
SensorsBodySensors (const SensorsBodySensors &t_other)
Copy Constructor.
SensorsBodySensors (const struct wb_sensors_body_sensors &t_other)
Copy Constructor.
SensorsBodySensors & operator= (const SensorsBodySensors &t_other)
Copy Assignment Operator.
SensorsBodySensors & operator= (const struct wb_sensors_body_sensors &t_other)
Copy Assignment Operator.
bool operator== (const SensorsBodySensors &t_other) const
bool operator!= (const SensorsBodySensors &t_other) const
bool operator== (const wb_sensors_body_sensors &t_other) const
bool operator!= (const wb_sensors_body_sensors &t_other) const
signed int & DCM_Time ()
const signed int & DCM_Time () const
void set_DCM_Time (const signed int &t_newValue)
float & InertialSensor_AccX ()
const float & InertialSensor_AccX () const
void set_InertialSensor_AccX (const float &t_newValue)
float & InertialSensor_AccY ()
const float & InertialSensor_AccY () const
void set_InertialSensor_AccY (const float &t_newValue)
float & InertialSensor_AccZ ()
const float & InertialSensor_AccZ () const
void set_InertialSensor_AccZ (const float &t_newValue)
float & InertialSensor_GyrX ()
const float & InertialSensor_GyrX () const
void set_InertialSensor_GyrX (const float &t_newValue)
float & InertialSensor_GyrY ()
const float & InertialSensor_GyrY () const
void set_InertialSensor_GyrY (const float &t_newValue)
float & InertialSensor_GyrZ ()
const float & InertialSensor_GyrZ () const
void set_InertialSensor_GyrZ (const float &t_newValue)
float & InertialSensor_AngleX ()
const float & InertialSensor_AngleX () const
void set_InertialSensor_AngleX (const float &t_newValue)
float & InertialSensor_AngleY ()
const float & InertialSensor_AngleY () const
void set_InertialSensor_AngleY (const float &t_newValue)
float & InertialSensor_AngleZ ()
const float & InertialSensor_AngleZ () const
void set_InertialSensor_AngleZ (const float &t_newValue)
float & InertialSensor_AccelerometerX ()
const float & InertialSensor_AccelerometerX () const
void set_InertialSensor_AccelerometerX (const float &t_newValue)
float & InertialSensor_AccelerometerY ()
const float & InertialSensor_AccelerometerY () const
void set_InertialSensor_AccelerometerY (const float &t_newValue)
float & InertialSensor_AccelerometerZ ()
const float & InertialSensor_AccelerometerZ () const
void set_InertialSensor_AccelerometerZ (const float &t_newValue)
float & InertialSensor_GyroscopeX ()
const float & InertialSensor_GyroscopeX () const
void set_InertialSensor_GyroscopeX (const float &t_newValue)
float & InertialSensor_GyroscopeY ()
const float & InertialSensor_GyroscopeY () const
void set_InertialSensor_GyroscopeY (const float &t_newValue)
float & InertialSensor_GyroscopeZ ()
const float & InertialSensor_GyroscopeZ () const
void set_InertialSensor_GyroscopeZ (const float &t_newValue)
uint8_t & Battery_Charge ()
const uint8_t & Battery_Charge () const
void set_Battery_Charge (const uint8_t &t_newValue)
uint8_t & Battery_Current ()
const uint8_t & Battery_Current () const
void set_Battery_Current (const uint8_t &t_newValue)
float & US ()
const float & US () const
void set_US (const float &t_newValue)
bool & ChestBoard_Button ()
const bool & ChestBoard_Button () const
void set_ChestBoard_Button (const bool &t_newValue)
SensorsBodySensors (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_sensors_body_sensors
signed int DCM_Time
Absolute time used for all timed commands in the DCM, an integer (signed), with 1 ms precision.
float InertialSensor_AccX
accelerometer X value
float InertialSensor_AccY
accelerometer Y value
float InertialSensor_AccZ
accelerometer Z value
float InertialSensor_GyrX
gyro X value
float InertialSensor_GyrY
gyro Y value
float InertialSensor_GyrZ
gyro Z value (Nao V5 have a Z axis)
float InertialSensor_AngleX
new acc values: AL_Docs 'Theses are direct acceleration values in m.s-2 (one g is approximately 9.81 m.s-2)'
float InertialSensor_AngleY
new acc values: AL_Docs 'Theses are direct acceleration values in m.s-2 (one g is approximately 9.81 m.s-2)'
float InertialSensor_AngleZ
new acc values: AL_Docs 'Theses are direct acceleration values in m.s-2 (one g is approximately 9.81 m.s-2)'
float InertialSensor_AccelerometerX
new Accelerometer X value
float InertialSensor_AccelerometerY
new Accelerometer Y value
float InertialSensor_AccelerometerZ
new Accelerometer Z value
float InertialSensor_GyroscopeX
new Gyro X value
float InertialSensor_GyroscopeY
new Gyro Y value
float InertialSensor_GyroscopeZ
new Gyro Z value
uint8_t Battery_Charge
% of charge
uint8_t Battery_Current
Amps.
float US
unsure, check naoqi docs! Not sure about this type, might only be 1 byte
bool ChestBoard_Button
state of the chest button, on / off.
Detailed Description
Provides a C++ wrapper around wb_sensors_body_sensors.
Definition at line 84 of file SensorsBodySensors.hpp.
Constructor & Destructor Documentation
SensorsBodySensors() [1/4]
guWhiteboard::SensorsBodySensors::SensorsBodySensors (signed int t_DCM_Time = 0, float t_InertialSensor_AccX = 0.0f, float t_InertialSensor_AccY = 0.0f, float t_InertialSensor_AccZ = 0.0f, float t_InertialSensor_GyrX = 0.0f, float t_InertialSensor_GyrY = 0.0f, float t_InertialSensor_GyrZ = 0.0f, float t_InertialSensor_AngleX = 0.0f, float t_InertialSensor_AngleY = 0.0f, float t_InertialSensor_AngleZ = 0.0f, float t_InertialSensor_AccelerometerX = 0.0f, float t_InertialSensor_AccelerometerY = 0.0f, float t_InertialSensor_AccelerometerZ = 0.0f, float t_InertialSensor_GyroscopeX = 0.0f, float t_InertialSensor_GyroscopeY = 0.0f, float t_InertialSensor_GyroscopeZ = 0.0f, uint8_t t_Battery_Charge = 0, uint8_t t_Battery_Current = 0, float t_US = 0.0f, bool t_ChestBoard_Button = true) inline
Create a new SensorsBodySensors.
Definition at line 119 of file SensorsBodySensors.hpp.
Referenced by operator==().
SensorsBodySensors() [2/4]
guWhiteboard::SensorsBodySensors::SensorsBodySensors (const SensorsBodySensors & t_other) inline
Copy Constructor.
Definition at line 126 of file SensorsBodySensors.hpp.
References Battery_Charge(), Battery_Current(), ChestBoard_Button(), DCM_Time(), InertialSensor_AccelerometerX(), InertialSensor_AccelerometerY(), InertialSensor_AccelerometerZ(), InertialSensor_AccX(), InertialSensor_AccY(), InertialSensor_AccZ(), InertialSensor_AngleX(), InertialSensor_AngleY(), InertialSensor_AngleZ(), InertialSensor_GyroscopeX(), InertialSensor_GyroscopeY(), InertialSensor_GyroscopeZ(), InertialSensor_GyrX(), InertialSensor_GyrY(), InertialSensor_GyrZ(), and US().
SensorsBodySensors() [3/4]
guWhiteboard::SensorsBodySensors::SensorsBodySensors (const struct wb_sensors_body_sensors & t_other) inline
Copy Constructor.
Definition at line 133 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::Battery_Charge, wb_sensors_body_sensors::Battery_Current, wb_sensors_body_sensors::ChestBoard_Button, wb_sensors_body_sensors::DCM_Time, wb_sensors_body_sensors::InertialSensor_AccelerometerX, wb_sensors_body_sensors::InertialSensor_AccelerometerY, wb_sensors_body_sensors::InertialSensor_AccelerometerZ, wb_sensors_body_sensors::InertialSensor_AccX, wb_sensors_body_sensors::InertialSensor_AccY, wb_sensors_body_sensors::InertialSensor_AccZ, wb_sensors_body_sensors::InertialSensor_AngleX, wb_sensors_body_sensors::InertialSensor_AngleY, wb_sensors_body_sensors::InertialSensor_AngleZ, wb_sensors_body_sensors::InertialSensor_GyroscopeX, wb_sensors_body_sensors::InertialSensor_GyroscopeY, wb_sensors_body_sensors::InertialSensor_GyroscopeZ, wb_sensors_body_sensors::InertialSensor_GyrX, wb_sensors_body_sensors::InertialSensor_GyrY, wb_sensors_body_sensors::InertialSensor_GyrZ, and wb_sensors_body_sensors::US.
SensorsBodySensors() [4/4]
guWhiteboard::SensorsBodySensors::SensorsBodySensors (const std::string & t_str) inline
String Constructor.
Definition at line 496 of file SensorsBodySensors.hpp.
References from_string().
Member Function Documentation
Battery_Charge() [1/2]
uint8_t & guWhiteboard::SensorsBodySensors::Battery_Charge () inline
Definition at line 432 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::Battery_Charge.
Referenced by SensorsBodySensors(), description(), operator=(), operator==(), and to_string().
Battery_Charge() [2/2]
const uint8_t & guWhiteboard::SensorsBodySensors::Battery_Charge () const inline
Definition at line 437 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::Battery_Charge.
Battery_Current() [1/2]
uint8_t & guWhiteboard::SensorsBodySensors::Battery_Current () inline
Definition at line 447 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::Battery_Current.
Referenced by SensorsBodySensors(), description(), operator=(), operator==(), and to_string().
Battery_Current() [2/2]
const uint8_t & guWhiteboard::SensorsBodySensors::Battery_Current () const inline
Definition at line 452 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::Battery_Current.
ChestBoard_Button() [1/2]
bool & guWhiteboard::SensorsBodySensors::ChestBoard_Button () inline
Definition at line 477 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::ChestBoard_Button.
Referenced by SensorsBodySensors(), description(), operator=(), operator==(), and to_string().
ChestBoard_Button() [2/2]
const bool & guWhiteboard::SensorsBodySensors::ChestBoard_Button () const inline
Definition at line 482 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::ChestBoard_Button.
DCM_Time() [1/2]
signed int & guWhiteboard::SensorsBodySensors::DCM_Time () inline
Definition at line 192 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::DCM_Time.
Referenced by SensorsBodySensors(), description(), operator=(), operator==(), and to_string().
DCM_Time() [2/2]
const signed int & guWhiteboard::SensorsBodySensors::DCM_Time () const inline
Definition at line 197 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::DCM_Time.
description()
std::string guWhiteboard::SensorsBodySensors::description () inline
USE_WB_SENSORS_BODY_SENSORS_C_CONVERSION
Definition at line 501 of file SensorsBodySensors.hpp.
References Battery_Charge(), Battery_Current(), ChestBoard_Button(), DCM_Time(), InertialSensor_AccelerometerX(), InertialSensor_AccelerometerY(), InertialSensor_AccelerometerZ(), InertialSensor_AccX(), InertialSensor_AccY(), InertialSensor_AccZ(), InertialSensor_AngleX(), InertialSensor_AngleY(), InertialSensor_AngleZ(), InertialSensor_GyroscopeX(), InertialSensor_GyroscopeY(), InertialSensor_GyroscopeZ(), InertialSensor_GyrX(), InertialSensor_GyrY(), InertialSensor_GyrZ(), SENSORS_BODY_SENSORS_DESC_BUFFER_SIZE, US(), and wb_sensors_body_sensors_description().
from_string()
void guWhiteboard::SensorsBodySensors::from_string (const std::string & t_str) inline
USE_WB_SENSORS_BODY_SENSORS_C_CONVERSION
Definition at line 607 of file SensorsBodySensors.hpp.
References SENSORS_BODY_SENSORS_DESC_BUFFER_SIZE, set_Battery_Charge(), set_Battery_Current(), set_ChestBoard_Button(), set_DCM_Time(), set_InertialSensor_AccelerometerX(), set_InertialSensor_AccelerometerY(), set_InertialSensor_AccelerometerZ(), set_InertialSensor_AccX(), set_InertialSensor_AccY(), set_InertialSensor_AccZ(), set_InertialSensor_AngleX(), set_InertialSensor_AngleY(), set_InertialSensor_AngleZ(), set_InertialSensor_GyroscopeX(), set_InertialSensor_GyroscopeY(), set_InertialSensor_GyroscopeZ(), set_InertialSensor_GyrX(), set_InertialSensor_GyrY(), set_InertialSensor_GyrZ(), and set_US().
Referenced by SensorsBodySensors().
InertialSensor_AccelerometerX() [1/2]
float & guWhiteboard::SensorsBodySensors::InertialSensor_AccelerometerX () inline
Definition at line 342 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AccelerometerX.
Referenced by SensorsBodySensors(), description(), operator=(), operator==(), and to_string().
InertialSensor_AccelerometerX() [2/2]
const float & guWhiteboard::SensorsBodySensors::InertialSensor_AccelerometerX () const inline
Definition at line 347 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AccelerometerX.
InertialSensor_AccelerometerY() [1/2]
float & guWhiteboard::SensorsBodySensors::InertialSensor_AccelerometerY () inline
Definition at line 357 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AccelerometerY.
Referenced by SensorsBodySensors(), description(), operator=(), operator==(), and to_string().
InertialSensor_AccelerometerY() [2/2]
const float & guWhiteboard::SensorsBodySensors::InertialSensor_AccelerometerY () const inline
Definition at line 362 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AccelerometerY.
InertialSensor_AccelerometerZ() [1/2]
float & guWhiteboard::SensorsBodySensors::InertialSensor_AccelerometerZ () inline
Definition at line 372 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AccelerometerZ.
Referenced by SensorsBodySensors(), description(), operator=(), operator==(), and to_string().
InertialSensor_AccelerometerZ() [2/2]
const float & guWhiteboard::SensorsBodySensors::InertialSensor_AccelerometerZ () const inline
Definition at line 377 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AccelerometerZ.
InertialSensor_AccX() [1/2]
float & guWhiteboard::SensorsBodySensors::InertialSensor_AccX () inline
Definition at line 207 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AccX.
Referenced by SensorsBodySensors(), description(), operator=(), operator==(), and to_string().
InertialSensor_AccX() [2/2]
const float & guWhiteboard::SensorsBodySensors::InertialSensor_AccX () const inline
Definition at line 212 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AccX.
InertialSensor_AccY() [1/2]
float & guWhiteboard::SensorsBodySensors::InertialSensor_AccY () inline
Definition at line 222 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AccY.
Referenced by SensorsBodySensors(), description(), operator=(), operator==(), and to_string().
InertialSensor_AccY() [2/2]
const float & guWhiteboard::SensorsBodySensors::InertialSensor_AccY () const inline
Definition at line 227 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AccY.
InertialSensor_AccZ() [1/2]
float & guWhiteboard::SensorsBodySensors::InertialSensor_AccZ () inline
Definition at line 237 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AccZ.
Referenced by SensorsBodySensors(), description(), operator=(), operator==(), and to_string().
InertialSensor_AccZ() [2/2]
const float & guWhiteboard::SensorsBodySensors::InertialSensor_AccZ () const inline
Definition at line 242 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AccZ.
InertialSensor_AngleX() [1/2]
float & guWhiteboard::SensorsBodySensors::InertialSensor_AngleX () inline
Definition at line 297 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AngleX.
Referenced by SensorsBodySensors(), description(), operator=(), operator==(), and to_string().
InertialSensor_AngleX() [2/2]
const float & guWhiteboard::SensorsBodySensors::InertialSensor_AngleX () const inline
Definition at line 302 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AngleX.
InertialSensor_AngleY() [1/2]
float & guWhiteboard::SensorsBodySensors::InertialSensor_AngleY () inline
Definition at line 312 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AngleY.
Referenced by SensorsBodySensors(), description(), operator=(), operator==(), and to_string().
InertialSensor_AngleY() [2/2]
const float & guWhiteboard::SensorsBodySensors::InertialSensor_AngleY () const inline
Definition at line 317 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AngleY.
InertialSensor_AngleZ() [1/2]
float & guWhiteboard::SensorsBodySensors::InertialSensor_AngleZ () inline
Definition at line 327 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AngleZ.
Referenced by SensorsBodySensors(), description(), operator=(), operator==(), and to_string().
InertialSensor_AngleZ() [2/2]
const float & guWhiteboard::SensorsBodySensors::InertialSensor_AngleZ () const inline
Definition at line 332 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AngleZ.
InertialSensor_GyroscopeX() [1/2]
float & guWhiteboard::SensorsBodySensors::InertialSensor_GyroscopeX () inline
Definition at line 387 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_GyroscopeX.
Referenced by SensorsBodySensors(), description(), operator=(), operator==(), and to_string().
InertialSensor_GyroscopeX() [2/2]
const float & guWhiteboard::SensorsBodySensors::InertialSensor_GyroscopeX () const inline
Definition at line 392 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_GyroscopeX.
InertialSensor_GyroscopeY() [1/2]
float & guWhiteboard::SensorsBodySensors::InertialSensor_GyroscopeY () inline
Definition at line 402 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_GyroscopeY.
Referenced by SensorsBodySensors(), description(), operator=(), operator==(), and to_string().
InertialSensor_GyroscopeY() [2/2]
const float & guWhiteboard::SensorsBodySensors::InertialSensor_GyroscopeY () const inline
Definition at line 407 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_GyroscopeY.
InertialSensor_GyroscopeZ() [1/2]
float & guWhiteboard::SensorsBodySensors::InertialSensor_GyroscopeZ () inline
Definition at line 417 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_GyroscopeZ.
Referenced by SensorsBodySensors(), description(), operator=(), operator==(), and to_string().
InertialSensor_GyroscopeZ() [2/2]
const float & guWhiteboard::SensorsBodySensors::InertialSensor_GyroscopeZ () const inline
Definition at line 422 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_GyroscopeZ.
InertialSensor_GyrX() [1/2]
float & guWhiteboard::SensorsBodySensors::InertialSensor_GyrX () inline
Definition at line 252 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_GyrX.
Referenced by SensorsBodySensors(), description(), operator=(), operator==(), and to_string().
InertialSensor_GyrX() [2/2]
const float & guWhiteboard::SensorsBodySensors::InertialSensor_GyrX () const inline
Definition at line 257 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_GyrX.
InertialSensor_GyrY() [1/2]
float & guWhiteboard::SensorsBodySensors::InertialSensor_GyrY () inline
Definition at line 267 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_GyrY.
Referenced by SensorsBodySensors(), description(), operator=(), operator==(), and to_string().
InertialSensor_GyrY() [2/2]
const float & guWhiteboard::SensorsBodySensors::InertialSensor_GyrY () const inline
Definition at line 272 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_GyrY.
InertialSensor_GyrZ() [1/2]
float & guWhiteboard::SensorsBodySensors::InertialSensor_GyrZ () inline
Definition at line 282 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_GyrZ.
Referenced by SensorsBodySensors(), description(), operator=(), operator==(), and to_string().
InertialSensor_GyrZ() [2/2]
const float & guWhiteboard::SensorsBodySensors::InertialSensor_GyrZ () const inline
Definition at line 287 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_GyrZ.
operator!=() [1/2]
bool guWhiteboard::SensorsBodySensors::operator!= (const SensorsBodySensors & t_other) const inline
Definition at line 177 of file SensorsBodySensors.hpp.
operator!=() [2/2]
bool guWhiteboard::SensorsBodySensors::operator!= (const wb_sensors_body_sensors & t_other) const inline
Definition at line 187 of file SensorsBodySensors.hpp.
operator=() [1/2]
SensorsBodySensors & guWhiteboard::SensorsBodySensors::operator= (const SensorsBodySensors & t_other) inline
Copy Assignment Operator.
Definition at line 140 of file SensorsBodySensors.hpp.
References Battery_Charge(), Battery_Current(), ChestBoard_Button(), DCM_Time(), InertialSensor_AccelerometerX(), InertialSensor_AccelerometerY(), InertialSensor_AccelerometerZ(), InertialSensor_AccX(), InertialSensor_AccY(), InertialSensor_AccZ(), InertialSensor_AngleX(), InertialSensor_AngleY(), InertialSensor_AngleZ(), InertialSensor_GyroscopeX(), InertialSensor_GyroscopeY(), InertialSensor_GyroscopeZ(), InertialSensor_GyrX(), InertialSensor_GyrY(), InertialSensor_GyrZ(), and US().
operator=() [2/2]
SensorsBodySensors & guWhiteboard::SensorsBodySensors::operator= (const struct wb_sensors_body_sensors & t_other) inline
Copy Assignment Operator.
Definition at line 148 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::Battery_Charge, wb_sensors_body_sensors::Battery_Current, wb_sensors_body_sensors::ChestBoard_Button, wb_sensors_body_sensors::DCM_Time, wb_sensors_body_sensors::InertialSensor_AccelerometerX, wb_sensors_body_sensors::InertialSensor_AccelerometerY, wb_sensors_body_sensors::InertialSensor_AccelerometerZ, wb_sensors_body_sensors::InertialSensor_AccX, wb_sensors_body_sensors::InertialSensor_AccY, wb_sensors_body_sensors::InertialSensor_AccZ, wb_sensors_body_sensors::InertialSensor_AngleX, wb_sensors_body_sensors::InertialSensor_AngleY, wb_sensors_body_sensors::InertialSensor_AngleZ, wb_sensors_body_sensors::InertialSensor_GyroscopeX, wb_sensors_body_sensors::InertialSensor_GyroscopeY, wb_sensors_body_sensors::InertialSensor_GyroscopeZ, wb_sensors_body_sensors::InertialSensor_GyrX, wb_sensors_body_sensors::InertialSensor_GyrY, wb_sensors_body_sensors::InertialSensor_GyrZ, and wb_sensors_body_sensors::US.
operator==() [1/2]
bool guWhiteboard::SensorsBodySensors::operator== (const SensorsBodySensors & t_other) const inline
Definition at line 153 of file SensorsBodySensors.hpp.
References Battery_Charge(), Battery_Current(), ChestBoard_Button(), DCM_Time(), InertialSensor_AccelerometerX(), InertialSensor_AccelerometerY(), InertialSensor_AccelerometerZ(), InertialSensor_AccX(), InertialSensor_AccY(), InertialSensor_AccZ(), InertialSensor_AngleX(), InertialSensor_AngleY(), InertialSensor_AngleZ(), InertialSensor_GyroscopeX(), InertialSensor_GyroscopeY(), InertialSensor_GyroscopeZ(), InertialSensor_GyrX(), InertialSensor_GyrY(), InertialSensor_GyrZ(), and US().
operator==() [2/2]
bool guWhiteboard::SensorsBodySensors::operator== (const wb_sensors_body_sensors & t_other) const inline
Definition at line 182 of file SensorsBodySensors.hpp.
References SensorsBodySensors().
set_Battery_Charge()
void guWhiteboard::SensorsBodySensors::set_Battery_Charge (const uint8_t & t_newValue) inline
Definition at line 442 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::Battery_Charge.
Referenced by from_string().
set_Battery_Current()
void guWhiteboard::SensorsBodySensors::set_Battery_Current (const uint8_t & t_newValue) inline
Definition at line 457 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::Battery_Current.
Referenced by from_string().
set_ChestBoard_Button()
void guWhiteboard::SensorsBodySensors::set_ChestBoard_Button (const bool & t_newValue) inline
Definition at line 487 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::ChestBoard_Button.
Referenced by from_string().
set_DCM_Time()
void guWhiteboard::SensorsBodySensors::set_DCM_Time (const signed int & t_newValue) inline
Definition at line 202 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::DCM_Time.
Referenced by from_string().
set_InertialSensor_AccelerometerX()
void guWhiteboard::SensorsBodySensors::set_InertialSensor_AccelerometerX (const float & t_newValue) inline
Definition at line 352 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AccelerometerX.
Referenced by from_string().
set_InertialSensor_AccelerometerY()
void guWhiteboard::SensorsBodySensors::set_InertialSensor_AccelerometerY (const float & t_newValue) inline
Definition at line 367 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AccelerometerY.
Referenced by from_string().
set_InertialSensor_AccelerometerZ()
void guWhiteboard::SensorsBodySensors::set_InertialSensor_AccelerometerZ (const float & t_newValue) inline
Definition at line 382 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AccelerometerZ.
Referenced by from_string().
set_InertialSensor_AccX()
void guWhiteboard::SensorsBodySensors::set_InertialSensor_AccX (const float & t_newValue) inline
Definition at line 217 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AccX.
Referenced by from_string().
set_InertialSensor_AccY()
void guWhiteboard::SensorsBodySensors::set_InertialSensor_AccY (const float & t_newValue) inline
Definition at line 232 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AccY.
Referenced by from_string().
set_InertialSensor_AccZ()
void guWhiteboard::SensorsBodySensors::set_InertialSensor_AccZ (const float & t_newValue) inline
Definition at line 247 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AccZ.
Referenced by from_string().
set_InertialSensor_AngleX()
void guWhiteboard::SensorsBodySensors::set_InertialSensor_AngleX (const float & t_newValue) inline
Definition at line 307 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AngleX.
Referenced by from_string().
set_InertialSensor_AngleY()
void guWhiteboard::SensorsBodySensors::set_InertialSensor_AngleY (const float & t_newValue) inline
Definition at line 322 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AngleY.
Referenced by from_string().
set_InertialSensor_AngleZ()
void guWhiteboard::SensorsBodySensors::set_InertialSensor_AngleZ (const float & t_newValue) inline
Definition at line 337 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_AngleZ.
Referenced by from_string().
set_InertialSensor_GyroscopeX()
void guWhiteboard::SensorsBodySensors::set_InertialSensor_GyroscopeX (const float & t_newValue) inline
Definition at line 397 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_GyroscopeX.
Referenced by from_string().
set_InertialSensor_GyroscopeY()
void guWhiteboard::SensorsBodySensors::set_InertialSensor_GyroscopeY (const float & t_newValue) inline
Definition at line 412 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_GyroscopeY.
Referenced by from_string().
set_InertialSensor_GyroscopeZ()
void guWhiteboard::SensorsBodySensors::set_InertialSensor_GyroscopeZ (const float & t_newValue) inline
Definition at line 427 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_GyroscopeZ.
Referenced by from_string().
set_InertialSensor_GyrX()
void guWhiteboard::SensorsBodySensors::set_InertialSensor_GyrX (const float & t_newValue) inline
Definition at line 262 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_GyrX.
Referenced by from_string().
set_InertialSensor_GyrY()
void guWhiteboard::SensorsBodySensors::set_InertialSensor_GyrY (const float & t_newValue) inline
Definition at line 277 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_GyrY.
Referenced by from_string().
set_InertialSensor_GyrZ()
void guWhiteboard::SensorsBodySensors::set_InertialSensor_GyrZ (const float & t_newValue) inline
Definition at line 292 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::InertialSensor_GyrZ.
Referenced by from_string().
set_US()
void guWhiteboard::SensorsBodySensors::set_US (const float & t_newValue) inline
Definition at line 472 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::US.
Referenced by from_string().
to_string()
std::string guWhiteboard::SensorsBodySensors::to_string () inline
USE_WB_SENSORS_BODY_SENSORS_C_CONVERSION
Definition at line 552 of file SensorsBodySensors.hpp.
References Battery_Charge(), Battery_Current(), ChestBoard_Button(), DCM_Time(), InertialSensor_AccelerometerX(), InertialSensor_AccelerometerY(), InertialSensor_AccelerometerZ(), InertialSensor_AccX(), InertialSensor_AccY(), InertialSensor_AccZ(), InertialSensor_AngleX(), InertialSensor_AngleY(), InertialSensor_AngleZ(), InertialSensor_GyroscopeX(), InertialSensor_GyroscopeY(), InertialSensor_GyroscopeZ(), InertialSensor_GyrX(), InertialSensor_GyrY(), InertialSensor_GyrZ(), SENSORS_BODY_SENSORS_TO_STRING_BUFFER_SIZE, US(), and wb_sensors_body_sensors_to_string().
US() [1/2]
float & guWhiteboard::SensorsBodySensors::US () inline
Definition at line 462 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::US.
Referenced by SensorsBodySensors(), description(), operator=(), operator==(), and to_string().
US() [2/2]
const float & guWhiteboard::SensorsBodySensors::US () const inline
Definition at line 467 of file SensorsBodySensors.hpp.
References wb_sensors_body_sensors::US.
The documentation for this class was generated from the following file:
typeClassDefs/SensorsBodySensors.hpp