gusimplewhiteboard: guWhiteboard::PixelCoordinateLine Class Reference
guWhiteboard::PixelCoordinateLine Class Reference
Provides a C++ wrapper around wb_pixel_coordinate_line.
#include <PixelCoordinateLine.hpp>
Public Member Functions
PixelCoordinateLine (struct wb_pixel_coordinate t_start=wb_pixel_coordinate(), struct wb_pixel_coordinate t_end=wb_pixel_coordinate())
Create a new PixelCoordinateLine.
PixelCoordinateLine (const PixelCoordinateLine &t_other)
Copy Constructor.
PixelCoordinateLine (const struct wb_pixel_coordinate_line &t_other)
Copy Constructor.
PixelCoordinateLine & operator= (const PixelCoordinateLine &t_other)
Copy Assignment Operator.
PixelCoordinateLine & operator= (const struct wb_pixel_coordinate_line &t_other)
Copy Assignment Operator.
bool operator== (const PixelCoordinateLine &t_other) const
bool operator!= (const PixelCoordinateLine &t_other) const
bool operator== (const wb_pixel_coordinate_line &t_other) const
bool operator!= (const wb_pixel_coordinate_line &t_other) const
PixelCoordinate & start ()
const PixelCoordinate & start () const
void set_start (const PixelCoordinate &t_newValue)
PixelCoordinate & end ()
const PixelCoordinate & end () const
void set_end (const PixelCoordinate &t_newValue)
PixelCoordinateLine (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
GU::PixelCoordinate startPixelCoordinate (const uint16_t resWidth, const uint16_t resHeight)
WHITEBOARD_POSTER_STRING_CONVERSION.
GU::PixelCoordinate endPixelCoordinate (const uint16_t resWidth, const uint16_t resHeight)
Additional Inherited Members
Public Attributes inherited from wb_pixel_coordinate_line
struct wb_pixel_coordinate start
Start point of the line.
struct wb_pixel_coordinate end
End point of the line.
Detailed Description
Provides a C++ wrapper around wb_pixel_coordinate_line.
Definition at line 92 of file PixelCoordinateLine.hpp.
Constructor & Destructor Documentation
PixelCoordinateLine() [1/4]
guWhiteboard::PixelCoordinateLine::PixelCoordinateLine (struct wb_pixel_coordinate t_start = wb_pixel_coordinate(), struct wb_pixel_coordinate t_end = wb_pixel_coordinate()) inline
Create a new PixelCoordinateLine.
Definition at line 109 of file PixelCoordinateLine.hpp.
Referenced by operator==().
PixelCoordinateLine() [2/4]
guWhiteboard::PixelCoordinateLine::PixelCoordinateLine (const PixelCoordinateLine & t_other) inline
Copy Constructor.
Definition at line 116 of file PixelCoordinateLine.hpp.
References end(), and start().
PixelCoordinateLine() [3/4]
guWhiteboard::PixelCoordinateLine::PixelCoordinateLine (const struct wb_pixel_coordinate_line & t_other) inline
Copy Constructor.
Definition at line 123 of file PixelCoordinateLine.hpp.
References wb_pixel_coordinate_line::end, and wb_pixel_coordinate_line::start.
PixelCoordinateLine() [4/4]
guWhiteboard::PixelCoordinateLine::PixelCoordinateLine (const std::string & t_str) inline
String Constructor.
Definition at line 198 of file PixelCoordinateLine.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::PixelCoordinateLine::description () inline
USE_WB_PIXEL_COORDINATE_LINE_C_CONVERSION
Definition at line 203 of file PixelCoordinateLine.hpp.
References guWhiteboard::PixelCoordinate::description(), end(), PIXEL_COORDINATE_LINE_DESC_BUFFER_SIZE, start(), and wb_pixel_coordinate_line_description().
Referenced by guWhiteboard::VisionLine::description().
end() [1/2]
PixelCoordinate & guWhiteboard::PixelCoordinateLine::end () inline
Definition at line 179 of file PixelCoordinateLine.hpp.
References wb_pixel_coordinate_line::end.
Referenced by PixelCoordinateLine(), description(), endPixelCoordinate(), operator=(), operator==(), and to_string().
end() [2/2]
const PixelCoordinate & guWhiteboard::PixelCoordinateLine::end () const inline
Definition at line 184 of file PixelCoordinateLine.hpp.
References wb_pixel_coordinate_line::end.
endPixelCoordinate()
GU::PixelCoordinate guWhiteboard::PixelCoordinateLine::endPixelCoordinate (const uint16_t resWidth, const uint16_t resHeight) inline
Definition at line 344 of file PixelCoordinateLine.hpp.
References end(), and guWhiteboard::PixelCoordinate::pixelCoordinate().
from_string()
void guWhiteboard::PixelCoordinateLine::from_string (const std::string & t_str) inline
USE_WB_PIXEL_COORDINATE_LINE_C_CONVERSION
Definition at line 237 of file PixelCoordinateLine.hpp.
References guWhiteboard::PixelCoordinate::from_string(), PIXEL_COORDINATE_LINE_DESC_BUFFER_SIZE, set_end(), and set_start().
Referenced by PixelCoordinateLine(), guWhiteboard::VisionDetectionLineArray::from_string(), and guWhiteboard::VisionLine::from_string().
operator!=() [1/2]
bool guWhiteboard::PixelCoordinateLine::operator!= (const PixelCoordinateLine & t_other) const inline
Definition at line 149 of file PixelCoordinateLine.hpp.
operator!=() [2/2]
bool guWhiteboard::PixelCoordinateLine::operator!= (const wb_pixel_coordinate_line & t_other) const inline
Definition at line 159 of file PixelCoordinateLine.hpp.
operator=() [1/2]
PixelCoordinateLine & guWhiteboard::PixelCoordinateLine::operator= (const PixelCoordinateLine & t_other) inline
Copy Assignment Operator.
Definition at line 130 of file PixelCoordinateLine.hpp.
References end(), and start().
operator=() [2/2]
PixelCoordinateLine & guWhiteboard::PixelCoordinateLine::operator= (const struct wb_pixel_coordinate_line & t_other) inline
Copy Assignment Operator.
Definition at line 138 of file PixelCoordinateLine.hpp.
References wb_pixel_coordinate_line::end, and wb_pixel_coordinate_line::start.
operator==() [1/2]
bool guWhiteboard::PixelCoordinateLine::operator== (const PixelCoordinateLine & t_other) const inline
Definition at line 143 of file PixelCoordinateLine.hpp.
References end(), and start().
operator==() [2/2]
bool guWhiteboard::PixelCoordinateLine::operator== (const wb_pixel_coordinate_line & t_other) const inline
Definition at line 154 of file PixelCoordinateLine.hpp.
References PixelCoordinateLine().
set_end()
void guWhiteboard::PixelCoordinateLine::set_end (const PixelCoordinate & t_newValue) inline
Definition at line 189 of file PixelCoordinateLine.hpp.
References wb_pixel_coordinate_line::end.
Referenced by from_string().
set_start()
void guWhiteboard::PixelCoordinateLine::set_start (const PixelCoordinate & t_newValue) inline
Definition at line 174 of file PixelCoordinateLine.hpp.
References wb_pixel_coordinate_line::start.
Referenced by from_string().
start() [1/2]
PixelCoordinate & guWhiteboard::PixelCoordinateLine::start () inline
Definition at line 164 of file PixelCoordinateLine.hpp.
References wb_pixel_coordinate_line::start.
Referenced by PixelCoordinateLine(), description(), operator=(), operator==(), startPixelCoordinate(), and to_string().
start() [2/2]
const PixelCoordinate & guWhiteboard::PixelCoordinateLine::start () const inline
Definition at line 169 of file PixelCoordinateLine.hpp.
References wb_pixel_coordinate_line::start.
startPixelCoordinate()
GU::PixelCoordinate guWhiteboard::PixelCoordinateLine::startPixelCoordinate (const uint16_t resWidth, const uint16_t resHeight) inline
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 340 of file PixelCoordinateLine.hpp.
References guWhiteboard::PixelCoordinate::pixelCoordinate(), and start().
to_string()
std::string guWhiteboard::PixelCoordinateLine::to_string () inline
USE_WB_PIXEL_COORDINATE_LINE_C_CONVERSION
Definition at line 218 of file PixelCoordinateLine.hpp.
References end(), PIXEL_COORDINATE_LINE_TO_STRING_BUFFER_SIZE, start(), guWhiteboard::PixelCoordinate::to_string(), and wb_pixel_coordinate_line_to_string().
Referenced by guWhiteboard::VisionLine::to_string().
The documentation for this class was generated from the following file:
typeClassDefs/PixelCoordinateLine.hpp