gusimplewhiteboard: guWhiteboard::FilteredOneDimSonar Class Reference
guWhiteboard::FilteredOneDimSonar Class Reference
Class for for one filtered sonar message.
#include <FilteredOneDimSonar.hpp>
Public Member Functions
FilteredOneDimSonar (bool isVisible=false, int16_t distance=0, int32_t frameCounter=0)
designated constructor
FilteredOneDimSonar (const FilteredOneDimSonar &other)
copy constructor
FilteredOneDimSonar (const wb_filteredsonarobject &other)
BASECONSTRUCTOR: INTERESTING !!!!
FilteredOneDimSonar & operator= (const FilteredOneDimSonar &other)
copy assignment operator
FilteredOneDimSonar & operator= (const wb_filteredsonarobject &other)
copy assignment operator:INTERESTING!!!
FilteredOneDimSonar (const std::string &names)
string constructor
FilteredOneDimSonar (const char *names)
const char * constructor
std::string description () const
convert to a string; string serialization
void from_string (const std::string &str)
build from string
Public Member Functions inherited from wb_filteredsonarobject
PROPERTY (int32_t, frameCounter) PROPERTY(int16_t
frame counter in cm
distance PROPERTY (bool, isVisible) PROPERTY(bool
is this a credible sighting
distance pad wb_filteredsonarobject (bool isVisible=false, int16_t distance=0, int32_t frameCounter=0)
constructor with default values
Detailed Description
Class for for one filtered sonar message.
Definition at line 79 of file FilteredOneDimSonar.hpp.
Constructor & Destructor Documentation
FilteredOneDimSonar() [1/5]
guWhiteboard::FilteredOneDimSonar::FilteredOneDimSonar (bool isVisible = false, int16_t distance = 0, int32_t frameCounter = 0) inline
designated constructor
Definition at line 84 of file FilteredOneDimSonar.hpp.
Referenced by from_string().
FilteredOneDimSonar() [2/5]
guWhiteboard::FilteredOneDimSonar::FilteredOneDimSonar (const FilteredOneDimSonar & other) inline
copy constructor
Definition at line 92 of file FilteredOneDimSonar.hpp.
FilteredOneDimSonar() [3/5]
guWhiteboard::FilteredOneDimSonar::FilteredOneDimSonar (const wb_filteredsonarobject & other) inline
BASECONSTRUCTOR: INTERESTING !!!!
Definition at line 98 of file FilteredOneDimSonar.hpp.
FilteredOneDimSonar() [4/5]
guWhiteboard::FilteredOneDimSonar::FilteredOneDimSonar (const std::string & names) inline
string constructor
Definition at line 126 of file FilteredOneDimSonar.hpp.
References from_string().
FilteredOneDimSonar() [5/5]
guWhiteboard::FilteredOneDimSonar::FilteredOneDimSonar (const char * names) inline
const char * constructor
Definition at line 129 of file FilteredOneDimSonar.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::FilteredOneDimSonar::description () const inline
convert to a string; string serialization
Definition at line 132 of file FilteredOneDimSonar.hpp.
References SEPARATOR_IS_COLON, and SEPARATOR_IS_COMMA.
Referenced by guWhiteboard::FilteredArrayOneDimSonar::description().
from_string()
void guWhiteboard::FilteredOneDimSonar::from_string (const std::string & str) inline
build from string
Definition at line 145 of file FilteredOneDimSonar.hpp.
References FilteredOneDimSonar(), IS_VISIBLE_ID, SEPARATOR_IS_COLON, and SEPARATOR_IS_COMMA.
Referenced by FilteredOneDimSonar().
operator=() [1/2]
FilteredOneDimSonar & guWhiteboard::FilteredOneDimSonar::operator= (const FilteredOneDimSonar & other) inline
copy assignment operator
Definition at line 102 of file FilteredOneDimSonar.hpp.
operator=() [2/2]
FilteredOneDimSonar & guWhiteboard::FilteredOneDimSonar::operator= (const wb_filteredsonarobject & other) inline
copy assignment operator:INTERESTING!!!
Definition at line 112 of file FilteredOneDimSonar.hpp.
The documentation for this class was generated from the following file:
typeClassDefs/FilteredOneDimSonar.hpp