gusimplewhiteboard: guWhiteboard::FilteredVisionObject Class Reference
guWhiteboard::FilteredVisionObject Class Reference
Provides a C++ wrapper around wb_filtered_vision_object.
#include <FilteredVisionObject.hpp>
Public Member Functions
FilteredVisionObject (uint64_t t_visibilityHistory=0, int32_t t_frameCounter=0, int16_t t_distance=0, int16_t t_x=0, int16_t t_y=0, int16_t t_yaw=0, int16_t t_ray_angle=0, bool t_isVisible=true, bool t_pad1=true)
Create a new FilteredVisionObject.
FilteredVisionObject (const FilteredVisionObject &t_other)
Copy Constructor.
FilteredVisionObject (const struct wb_filtered_vision_object &t_other)
Copy Constructor.
FilteredVisionObject & operator= (const FilteredVisionObject &t_other)
Copy Assignment Operator.
FilteredVisionObject & operator= (const struct wb_filtered_vision_object &t_other)
Copy Assignment Operator.
bool operator== (const FilteredVisionObject &t_other) const
bool operator!= (const FilteredVisionObject &t_other) const
bool operator== (const wb_filtered_vision_object &t_other) const
bool operator!= (const wb_filtered_vision_object &t_other) const
uint64_t & visibilityHistory ()
const uint64_t & visibilityHistory () const
void set_visibilityHistory (const uint64_t &t_newValue)
int32_t & frameCounter ()
const int32_t & frameCounter () const
void set_frameCounter (const int32_t &t_newValue)
int16_t & distance ()
const int16_t & distance () const
void set_distance (const int16_t &t_newValue)
int16_t & x ()
const int16_t & x () const
void set_x (const int16_t &t_newValue)
int16_t & y ()
const int16_t & y () const
void set_y (const int16_t &t_newValue)
int16_t & yaw ()
const int16_t & yaw () const
void set_yaw (const int16_t &t_newValue)
int16_t & ray_angle ()
const int16_t & ray_angle () const
void set_ray_angle (const int16_t &t_newValue)
bool & isVisible ()
const bool & isVisible () const
void set_isVisible (const bool &t_newValue)
bool & pad1 ()
const bool & pad1 () const
void set_pad1 (const bool &t_newValue)
FilteredVisionObject (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_filtered_vision_object
uint64_t visibilityHistory
a 64-bit history of whether vision said visible 1 or not visible 0.
int32_t frameCounter
incremented every time we do not see the object.
int16_t distance
distance to landmark in cm
int16_t x
centre x-coordinate in image (0,0) is the centre of the image, positive is to the right
int16_t y
centre y-coordinate in image, positive is upwards
int16_t yaw
the Yaw in Degrees when the object was last used to generated filtered values.
int16_t ray_angle
In degrees, position of the object, positive is left, negative is right, with distance polar position of object in frame of reference of robot.
bool isVisible
is this a credible sighting.
bool pad1
16 bit padding .
Detailed Description
Provides a C++ wrapper around wb_filtered_vision_object.
Definition at line 83 of file FilteredVisionObject.hpp.
Constructor & Destructor Documentation
FilteredVisionObject() [1/4]
guWhiteboard::FilteredVisionObject::FilteredVisionObject (uint64_t t_visibilityHistory = 0, int32_t t_frameCounter = 0, int16_t t_distance = 0, int16_t t_x = 0, int16_t t_y = 0, int16_t t_yaw = 0, int16_t t_ray_angle = 0, bool t_isVisible = true, bool t_pad1 = true) inline
Create a new FilteredVisionObject.
Definition at line 107 of file FilteredVisionObject.hpp.
Referenced by operator==().
FilteredVisionObject() [2/4]
guWhiteboard::FilteredVisionObject::FilteredVisionObject (const FilteredVisionObject & t_other) inline
Copy Constructor.
Definition at line 114 of file FilteredVisionObject.hpp.
References distance(), frameCounter(), isVisible(), pad1(), ray_angle(), visibilityHistory(), x(), y(), and yaw().
FilteredVisionObject() [3/4]
guWhiteboard::FilteredVisionObject::FilteredVisionObject (const struct wb_filtered_vision_object & t_other) inline
Copy Constructor.
Definition at line 121 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::distance, wb_filtered_vision_object::frameCounter, wb_filtered_vision_object::isVisible, wb_filtered_vision_object::pad1, wb_filtered_vision_object::ray_angle, wb_filtered_vision_object::visibilityHistory, wb_filtered_vision_object::x, wb_filtered_vision_object::y, and wb_filtered_vision_object::yaw.
FilteredVisionObject() [4/4]
guWhiteboard::FilteredVisionObject::FilteredVisionObject (const std::string & t_str) inline
String Constructor.
Definition at line 308 of file FilteredVisionObject.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::FilteredVisionObject::description () inline
USE_WB_FILTERED_VISION_OBJECT_C_CONVERSION
Definition at line 313 of file FilteredVisionObject.hpp.
References distance(), FILTERED_VISION_OBJECT_DESC_BUFFER_SIZE, frameCounter(), isVisible(), pad1(), ray_angle(), visibilityHistory(), wb_filtered_vision_object_description(), x(), y(), and yaw().
distance() [1/2]
int16_t & guWhiteboard::FilteredVisionObject::distance () inline
Definition at line 199 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::distance.
Referenced by FilteredVisionObject(), description(), guWhiteboard::FilteredOneDimObject::description(), guWhiteboard::FilteredOneDimObject::operator=(), operator=(), operator==(), and to_string().
distance() [2/2]
const int16_t & guWhiteboard::FilteredVisionObject::distance () const inline
Definition at line 204 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::distance.
frameCounter() [1/2]
int32_t & guWhiteboard::FilteredVisionObject::frameCounter () inline
Definition at line 184 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::frameCounter.
Referenced by FilteredVisionObject(), description(), guWhiteboard::FilteredOneDimObject::description(), guWhiteboard::FilteredOneDimObject::operator=(), operator=(), operator==(), and to_string().
frameCounter() [2/2]
const int32_t & guWhiteboard::FilteredVisionObject::frameCounter () const inline
Definition at line 189 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::frameCounter.
from_string()
void guWhiteboard::FilteredVisionObject::from_string (const std::string & t_str) inline
USE_WB_FILTERED_VISION_OBJECT_C_CONVERSION
Definition at line 375 of file FilteredVisionObject.hpp.
References FILTERED_VISION_OBJECT_DESC_BUFFER_SIZE, set_distance(), set_frameCounter(), set_isVisible(), set_pad1(), set_ray_angle(), set_visibilityHistory(), set_x(), set_y(), and set_yaw().
Referenced by FilteredVisionObject(), guWhiteboard::FilteredArrayBallSightings::from_string(), and guWhiteboard::FilteredArrayOneDimObjects::from_string().
isVisible() [1/2]
bool & guWhiteboard::FilteredVisionObject::isVisible () inline
Definition at line 274 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::isVisible.
Referenced by FilteredVisionObject(), description(), guWhiteboard::FilteredOneDimObject::description(), guWhiteboard::FilteredOneDimObject::operator=(), operator=(), operator==(), and to_string().
isVisible() [2/2]
const bool & guWhiteboard::FilteredVisionObject::isVisible () const inline
Definition at line 279 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::isVisible.
operator!=() [1/2]
bool guWhiteboard::FilteredVisionObject::operator!= (const FilteredVisionObject & t_other) const inline
Definition at line 154 of file FilteredVisionObject.hpp.
operator!=() [2/2]
bool guWhiteboard::FilteredVisionObject::operator!= (const wb_filtered_vision_object & t_other) const inline
Definition at line 164 of file FilteredVisionObject.hpp.
operator=() [1/2]
FilteredVisionObject & guWhiteboard::FilteredVisionObject::operator= (const FilteredVisionObject & t_other) inline
Copy Assignment Operator.
Definition at line 128 of file FilteredVisionObject.hpp.
References distance(), frameCounter(), isVisible(), pad1(), ray_angle(), visibilityHistory(), x(), y(), and yaw().
operator=() [2/2]
FilteredVisionObject & guWhiteboard::FilteredVisionObject::operator= (const struct wb_filtered_vision_object & t_other) inline
Copy Assignment Operator.
Definition at line 136 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::distance, wb_filtered_vision_object::frameCounter, wb_filtered_vision_object::isVisible, wb_filtered_vision_object::pad1, wb_filtered_vision_object::ray_angle, wb_filtered_vision_object::visibilityHistory, wb_filtered_vision_object::x, wb_filtered_vision_object::y, and wb_filtered_vision_object::yaw.
operator==() [1/2]
bool guWhiteboard::FilteredVisionObject::operator== (const FilteredVisionObject & t_other) const inline
Definition at line 141 of file FilteredVisionObject.hpp.
References distance(), frameCounter(), isVisible(), pad1(), ray_angle(), visibilityHistory(), x(), y(), and yaw().
operator==() [2/2]
bool guWhiteboard::FilteredVisionObject::operator== (const wb_filtered_vision_object & t_other) const inline
Definition at line 159 of file FilteredVisionObject.hpp.
References FilteredVisionObject().
pad1() [1/2]
bool & guWhiteboard::FilteredVisionObject::pad1 () inline
Definition at line 289 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::pad1.
Referenced by FilteredVisionObject(), description(), operator=(), operator==(), and to_string().
pad1() [2/2]
const bool & guWhiteboard::FilteredVisionObject::pad1 () const inline
Definition at line 294 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::pad1.
ray_angle() [1/2]
int16_t & guWhiteboard::FilteredVisionObject::ray_angle () inline
Definition at line 259 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::ray_angle.
Referenced by FilteredVisionObject(), description(), operator=(), operator==(), and to_string().
ray_angle() [2/2]
const int16_t & guWhiteboard::FilteredVisionObject::ray_angle () const inline
Definition at line 264 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::ray_angle.
set_distance()
void guWhiteboard::FilteredVisionObject::set_distance (const int16_t & t_newValue) inline
Definition at line 209 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::distance.
Referenced by guWhiteboard::FilteredOneDimObject::FilteredOneDimObject(), guWhiteboard::FilteredOneDimObject::from_string(), from_string(), and guWhiteboard::FilteredOneDimObject::operator=().
set_frameCounter()
void guWhiteboard::FilteredVisionObject::set_frameCounter (const int32_t & t_newValue) inline
Definition at line 194 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::frameCounter.
Referenced by guWhiteboard::FilteredOneDimObject::FilteredOneDimObject(), guWhiteboard::FilteredOneDimObject::from_string(), from_string(), and guWhiteboard::FilteredOneDimObject::operator=().
set_isVisible()
void guWhiteboard::FilteredVisionObject::set_isVisible (const bool & t_newValue) inline
Definition at line 284 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::isVisible.
Referenced by guWhiteboard::FilteredOneDimObject::FilteredOneDimObject(), guWhiteboard::FilteredOneDimObject::from_string(), from_string(), and guWhiteboard::FilteredOneDimObject::operator=().
set_pad1()
void guWhiteboard::FilteredVisionObject::set_pad1 (const bool & t_newValue) inline
Definition at line 299 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::pad1.
Referenced by from_string().
set_ray_angle()
void guWhiteboard::FilteredVisionObject::set_ray_angle (const int16_t & t_newValue) inline
Definition at line 269 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::ray_angle.
Referenced by from_string().
set_visibilityHistory()
void guWhiteboard::FilteredVisionObject::set_visibilityHistory (const uint64_t & t_newValue) inline
Definition at line 179 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::visibilityHistory.
Referenced by guWhiteboard::FilteredOneDimObject::FilteredOneDimObject(), from_string(), and guWhiteboard::FilteredOneDimObject::operator=().
set_x()
void guWhiteboard::FilteredVisionObject::set_x (const int16_t & t_newValue) inline
Definition at line 224 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::x.
Referenced by guWhiteboard::FilteredOneDimObject::FilteredOneDimObject(), guWhiteboard::FilteredOneDimObject::from_string(), from_string(), and guWhiteboard::FilteredOneDimObject::operator=().
set_y()
void guWhiteboard::FilteredVisionObject::set_y (const int16_t & t_newValue) inline
Definition at line 239 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::y.
Referenced by guWhiteboard::FilteredOneDimObject::FilteredOneDimObject(), guWhiteboard::FilteredOneDimObject::from_string(), from_string(), and guWhiteboard::FilteredOneDimObject::operator=().
set_yaw()
void guWhiteboard::FilteredVisionObject::set_yaw (const int16_t & t_newValue) inline
Definition at line 254 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::yaw.
Referenced by guWhiteboard::FilteredOneDimObject::FilteredOneDimObject(), guWhiteboard::FilteredOneDimObject::from_string(), from_string(), and guWhiteboard::FilteredOneDimObject::operator=().
to_string()
std::string guWhiteboard::FilteredVisionObject::to_string () inline
USE_WB_FILTERED_VISION_OBJECT_C_CONVERSION
Definition at line 342 of file FilteredVisionObject.hpp.
References distance(), FILTERED_VISION_OBJECT_TO_STRING_BUFFER_SIZE, frameCounter(), isVisible(), pad1(), ray_angle(), visibilityHistory(), wb_filtered_vision_object_to_string(), x(), y(), and yaw().
visibilityHistory() [1/2]
uint64_t & guWhiteboard::FilteredVisionObject::visibilityHistory () inline
Definition at line 169 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::visibilityHistory.
Referenced by FilteredVisionObject(), description(), guWhiteboard::FilteredOneDimObject::operator=(), operator=(), operator==(), guWhiteboard::FilteredOneDimObject::ratioOfSightings(), and to_string().
visibilityHistory() [2/2]
const uint64_t & guWhiteboard::FilteredVisionObject::visibilityHistory () const inline
Definition at line 174 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::visibilityHistory.
x() [1/2]
int16_t & guWhiteboard::FilteredVisionObject::x () inline
Definition at line 214 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::x.
Referenced by FilteredVisionObject(), description(), guWhiteboard::FilteredOneDimObject::description(), guWhiteboard::FilteredOneDimObject::horizontal_angle(), guWhiteboard::FilteredOneDimObject::operator=(), operator=(), operator==(), and to_string().
x() [2/2]
const int16_t & guWhiteboard::FilteredVisionObject::x () const inline
Definition at line 219 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::x.
y() [1/2]
int16_t & guWhiteboard::FilteredVisionObject::y () inline
Definition at line 229 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::y.
Referenced by FilteredVisionObject(), description(), guWhiteboard::FilteredOneDimObject::description(), guWhiteboard::FilteredOneDimObject::operator=(), operator=(), operator==(), and to_string().
y() [2/2]
const int16_t & guWhiteboard::FilteredVisionObject::y () const inline
Definition at line 234 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::y.
yaw() [1/2]
int16_t & guWhiteboard::FilteredVisionObject::yaw () inline
Definition at line 244 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::yaw.
Referenced by FilteredVisionObject(), description(), guWhiteboard::FilteredOneDimObject::description(), guWhiteboard::FilteredOneDimObject::horizontal_angle(), guWhiteboard::FilteredOneDimObject::operator=(), operator=(), operator==(), and to_string().
yaw() [2/2]
const int16_t & guWhiteboard::FilteredVisionObject::yaw () const inline
Definition at line 249 of file FilteredVisionObject.hpp.
References wb_filtered_vision_object::yaw.
The documentation for this class was generated from the following file:
typeClassDefs/FilteredVisionObject.hpp