gusimplewhiteboard: WBSubscriber Class Reference
WBSubscriber Class Reference
subscription test class
Public Member Functions
WBSubscriber (SimpleWhiteboardTest *t)
Test Constructor.
~WBSubscriber ()
Test Destructor.
void sub (WBTypes, gu_simple_message *m)
Trigger subscription test.
Detailed Description
subscription test class
Definition at line 76 of file SimpleWhiteboardTest.mm.
Constructor & Destructor Documentation
WBSubscriber()
WBSubscriber::WBSubscriber (SimpleWhiteboardTest * t) inline
Test Constructor.
Definition at line 84 of file SimpleWhiteboardTest.mm.
References kPrint_v, sub(), whiteboard_watcher::subscribe(), and WB_TYPE_BIND.
~WBSubscriber()
WBSubscriber::~WBSubscriber () inline
Test Destructor.
Definition at line 94 of file SimpleWhiteboardTest.mm.
References kPrint_v, and whiteboard_watcher::unsubscribe().
Member Function Documentation
sub()
void WBSubscriber::sub (WBTypes , gu_simple_message * m) inline
Trigger subscription test.
Definition at line 103 of file SimpleWhiteboardTest.mm.
Referenced by WBSubscriber().
The documentation for this class was generated from the following file:
SimpleWhiteboardTest/SimpleWhiteboardTest.mm