gusimplewhiteboard: guWhiteboard::VisionDetectionBall Class Reference
guWhiteboard::VisionDetectionBall Class Reference
Provides a C++ wrapper around wb_vision_detection_ball.
#include <VisionDetectionBall.hpp>
Public Member Functions
VisionDetectionBall (enum BallOptions t_sightingType=NoBallDetected, struct wb_pixel_coordinate t_coordinate=wb_pixel_coordinate(), uint16_t t_verticalRadius=0, uint16_t t_horizontalRadius=0)
Create a new VisionDetectionBall.
VisionDetectionBall (const VisionDetectionBall &t_other)
Copy Constructor.
VisionDetectionBall (const struct wb_vision_detection_ball &t_other)
Copy Constructor.
VisionDetectionBall & operator= (const VisionDetectionBall &t_other)
Copy Assignment Operator.
VisionDetectionBall & operator= (const struct wb_vision_detection_ball &t_other)
Copy Assignment Operator.
bool operator== (const VisionDetectionBall &t_other) const
bool operator!= (const VisionDetectionBall &t_other) const
bool operator== (const wb_vision_detection_ball &t_other) const
bool operator!= (const wb_vision_detection_ball &t_other) const
enum BallOptions & sightingType ()
enum BallOptions & sightingType () const
void set_sightingType (const enum BallOptions &t_newValue)
PixelCoordinate & coordinate ()
const PixelCoordinate & coordinate () const
void set_coordinate (const PixelCoordinate &t_newValue)
uint16_t & verticalRadius ()
const uint16_t & verticalRadius () const
void set_verticalRadius (const uint16_t &t_newValue)
uint16_t & horizontalRadius ()
const uint16_t & horizontalRadius () const
void set_horizontalRadius (const uint16_t &t_newValue)
VisionDetectionBall (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
GU::PixelCoordinate coordinatePixelCoordinate (const uint16_t resWidth, const uint16_t resHeight)
WHITEBOARD_POSTER_STRING_CONVERSION.
Additional Inherited Members
Public Attributes inherited from wb_vision_detection_ball
enum BallOptions sightingType
Ball detection details.
struct wb_pixel_coordinate coordinate
The pixel coordinate.
uint16_t verticalRadius
The vertical radius in pixels.
uint16_t horizontalRadius
The horizontal radius in pixels.
Detailed Description
Provides a C++ wrapper around wb_vision_detection_ball.
Definition at line 88 of file VisionDetectionBall.hpp.
Constructor & Destructor Documentation
VisionDetectionBall() [1/4]
guWhiteboard::VisionDetectionBall::VisionDetectionBall (enum BallOptions t_sightingType = NoBallDetected, struct wb_pixel_coordinate t_coordinate = wb_pixel_coordinate(), uint16_t t_verticalRadius = 0, uint16_t t_horizontalRadius = 0) inline
Create a new VisionDetectionBall.
Definition at line 107 of file VisionDetectionBall.hpp.
Referenced by operator==().
VisionDetectionBall() [2/4]
guWhiteboard::VisionDetectionBall::VisionDetectionBall (const VisionDetectionBall & t_other) inline
Copy Constructor.
Definition at line 114 of file VisionDetectionBall.hpp.
References coordinate(), horizontalRadius(), sightingType(), and verticalRadius().
VisionDetectionBall() [3/4]
guWhiteboard::VisionDetectionBall::VisionDetectionBall (const struct wb_vision_detection_ball & t_other) inline
Copy Constructor.
Definition at line 121 of file VisionDetectionBall.hpp.
References wb_vision_detection_ball::coordinate, wb_vision_detection_ball::horizontalRadius, wb_vision_detection_ball::sightingType, and wb_vision_detection_ball::verticalRadius.
VisionDetectionBall() [4/4]
guWhiteboard::VisionDetectionBall::VisionDetectionBall (const std::string & t_str) inline
String Constructor.
Definition at line 228 of file VisionDetectionBall.hpp.
References from_string().
Member Function Documentation
coordinate() [1/2]
PixelCoordinate & guWhiteboard::VisionDetectionBall::coordinate () inline
Definition at line 179 of file VisionDetectionBall.hpp.
References wb_vision_detection_ball::coordinate.
Referenced by VisionDetectionBall(), coordinatePixelCoordinate(), description(), operator=(), operator==(), and to_string().
coordinate() [2/2]
const PixelCoordinate & guWhiteboard::VisionDetectionBall::coordinate () const inline
Definition at line 184 of file VisionDetectionBall.hpp.
References wb_vision_detection_ball::coordinate.
coordinatePixelCoordinate()
GU::PixelCoordinate guWhiteboard::VisionDetectionBall::coordinatePixelCoordinate (const uint16_t resWidth, const uint16_t resHeight) inline
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 427 of file VisionDetectionBall.hpp.
References coordinate(), and guWhiteboard::PixelCoordinate::pixelCoordinate().
description()
std::string guWhiteboard::VisionDetectionBall::description () inline
USE_WB_VISION_DETECTION_BALL_C_CONVERSION
Definition at line 233 of file VisionDetectionBall.hpp.
References BallDetected, coordinate(), guWhiteboard::PixelCoordinate::description(), horizontalRadius(), NoBallDetected, sightingType(), verticalRadius(), VISION_DETECTION_BALL_DESC_BUFFER_SIZE, and wb_vision_detection_ball_description().
from_string()
void guWhiteboard::VisionDetectionBall::from_string (const std::string & t_str) inline
USE_WB_VISION_DETECTION_BALL_C_CONVERSION
Definition at line 297 of file VisionDetectionBall.hpp.
References BallDetected, guWhiteboard::PixelCoordinate::from_string(), NoBallDetected, set_coordinate(), set_horizontalRadius(), set_sightingType(), set_verticalRadius(), and VISION_DETECTION_BALL_DESC_BUFFER_SIZE.
Referenced by VisionDetectionBall(), and guWhiteboard::VisionDetectionBalls::from_string().
horizontalRadius() [1/2]
uint16_t & guWhiteboard::VisionDetectionBall::horizontalRadius () inline
Definition at line 209 of file VisionDetectionBall.hpp.
References wb_vision_detection_ball::horizontalRadius.
Referenced by VisionDetectionBall(), description(), operator=(), operator==(), and to_string().
horizontalRadius() [2/2]
const uint16_t & guWhiteboard::VisionDetectionBall::horizontalRadius () const inline
Definition at line 214 of file VisionDetectionBall.hpp.
References wb_vision_detection_ball::horizontalRadius.
operator!=() [1/2]
bool guWhiteboard::VisionDetectionBall::operator!= (const VisionDetectionBall & t_other) const inline
Definition at line 149 of file VisionDetectionBall.hpp.
operator!=() [2/2]
bool guWhiteboard::VisionDetectionBall::operator!= (const wb_vision_detection_ball & t_other) const inline
Definition at line 159 of file VisionDetectionBall.hpp.
operator=() [1/2]
VisionDetectionBall & guWhiteboard::VisionDetectionBall::operator= (const struct wb_vision_detection_ball & t_other) inline
Copy Assignment Operator.
Definition at line 136 of file VisionDetectionBall.hpp.
References wb_vision_detection_ball::coordinate, wb_vision_detection_ball::horizontalRadius, wb_vision_detection_ball::sightingType, and wb_vision_detection_ball::verticalRadius.
operator=() [2/2]
VisionDetectionBall & guWhiteboard::VisionDetectionBall::operator= (const VisionDetectionBall & t_other) inline
Copy Assignment Operator.
Definition at line 128 of file VisionDetectionBall.hpp.
References coordinate(), horizontalRadius(), sightingType(), and verticalRadius().
operator==() [1/2]
bool guWhiteboard::VisionDetectionBall::operator== (const VisionDetectionBall & t_other) const inline
Definition at line 141 of file VisionDetectionBall.hpp.
References coordinate(), horizontalRadius(), sightingType(), and verticalRadius().
operator==() [2/2]
bool guWhiteboard::VisionDetectionBall::operator== (const wb_vision_detection_ball & t_other) const inline
Definition at line 154 of file VisionDetectionBall.hpp.
References VisionDetectionBall().
set_coordinate()
void guWhiteboard::VisionDetectionBall::set_coordinate (const PixelCoordinate & t_newValue) inline
Definition at line 189 of file VisionDetectionBall.hpp.
References wb_vision_detection_ball::coordinate.
Referenced by from_string().
set_horizontalRadius()
void guWhiteboard::VisionDetectionBall::set_horizontalRadius (const uint16_t & t_newValue) inline
Definition at line 219 of file VisionDetectionBall.hpp.
References wb_vision_detection_ball::horizontalRadius.
Referenced by from_string().
set_sightingType()
void guWhiteboard::VisionDetectionBall::set_sightingType (const enum BallOptions & t_newValue) inline
Definition at line 174 of file VisionDetectionBall.hpp.
References wb_vision_detection_ball::sightingType.
Referenced by from_string().
set_verticalRadius()
void guWhiteboard::VisionDetectionBall::set_verticalRadius (const uint16_t & t_newValue) inline
Definition at line 204 of file VisionDetectionBall.hpp.
References wb_vision_detection_ball::verticalRadius.
Referenced by from_string().
sightingType() [1/2]
enum BallOptions & guWhiteboard::VisionDetectionBall::sightingType () inline
Definition at line 164 of file VisionDetectionBall.hpp.
References wb_vision_detection_ball::sightingType.
Referenced by VisionDetectionBall(), description(), operator=(), operator==(), and to_string().
sightingType() [2/2]
enum BallOptions & guWhiteboard::VisionDetectionBall::sightingType () const inline
Definition at line 169 of file VisionDetectionBall.hpp.
References wb_vision_detection_ball::sightingType.
to_string()
std::string guWhiteboard::VisionDetectionBall::to_string () inline
USE_WB_VISION_DETECTION_BALL_C_CONVERSION
Definition at line 263 of file VisionDetectionBall.hpp.
References BallDetected, coordinate(), horizontalRadius(), NoBallDetected, sightingType(), guWhiteboard::PixelCoordinate::to_string(), verticalRadius(), VISION_DETECTION_BALL_TO_STRING_BUFFER_SIZE, and wb_vision_detection_ball_to_string().
verticalRadius() [1/2]
uint16_t & guWhiteboard::VisionDetectionBall::verticalRadius () inline
Definition at line 194 of file VisionDetectionBall.hpp.
References wb_vision_detection_ball::verticalRadius.
Referenced by VisionDetectionBall(), description(), operator=(), operator==(), and to_string().
verticalRadius() [2/2]
const uint16_t & guWhiteboard::VisionDetectionBall::verticalRadius () const inline
Definition at line 199 of file VisionDetectionBall.hpp.
References wb_vision_detection_ball::verticalRadius.
The documentation for this class was generated from the following file:
typeClassDefs/VisionDetectionBall.hpp