gusimplewhiteboard: guWhiteboard::FilteredArrayOneDimSonar Class Reference
guWhiteboard::FilteredArrayOneDimSonar Class Reference
Class for for the array of sonar messages, LEFT and RIGHT.
#include <FilteredArrayOneDimSonar.hpp>
Public Member Functions
FilteredArrayOneDimSonar ()
designated constructor
FilteredArrayOneDimSonar (const class FilteredOneDimSonar &obj, enum FilteredSonarObjectType landmarkType=FSLeft)
constructor with one setter
FilteredArrayOneDimSonar (const FilteredArrayOneDimSonar &other)
copy constructor
FilteredArrayOneDimSonar & operator= (const FilteredArrayOneDimSonar &other)
copy assignment operator
void set_objects (const class FilteredArrayOneDimSonar *objects)
property getter
void set_object (const class FilteredOneDimSonar &obj, enum FilteredSonarObjectType landmarkType=FSLeft)
single vision object setter
FilteredOneDimSonar get_object (enum FilteredSonarObjectType landmarkType=FSLeft)
single vision object setter
FilteredArrayOneDimSonar (const std::string &names)
string constructor
FilteredArrayOneDimSonar (const char *names)
const char * constructor
std::string description ()
convert to a string; string serialization
void from_string (const std::string &str)
build from string
Detailed Description
Class for for the array of sonar messages, LEFT and RIGHT.
Definition at line 81 of file FilteredArrayOneDimSonar.hpp.
Constructor & Destructor Documentation
FilteredArrayOneDimSonar() [1/5]
guWhiteboard::FilteredArrayOneDimSonar::FilteredArrayOneDimSonar () inline
designated constructor
Definition at line 91 of file FilteredArrayOneDimSonar.hpp.
FilteredArrayOneDimSonar() [2/5]
guWhiteboard::FilteredArrayOneDimSonar::FilteredArrayOneDimSonar (const class FilteredOneDimSonar & obj, enum FilteredSonarObjectType landmarkType = FSLeft) inline
constructor with one setter
Definition at line 95 of file FilteredArrayOneDimSonar.hpp.
FilteredArrayOneDimSonar() [3/5]
guWhiteboard::FilteredArrayOneDimSonar::FilteredArrayOneDimSonar (const FilteredArrayOneDimSonar & other) inline
copy constructor
Definition at line 103 of file FilteredArrayOneDimSonar.hpp.
FilteredArrayOneDimSonar() [4/5]
guWhiteboard::FilteredArrayOneDimSonar::FilteredArrayOneDimSonar (const std::string & names) inline
string constructor
Definition at line 146 of file FilteredArrayOneDimSonar.hpp.
References from_string().
FilteredArrayOneDimSonar() [5/5]
guWhiteboard::FilteredArrayOneDimSonar::FilteredArrayOneDimSonar (const char * names) inline
const char * constructor
Definition at line 149 of file FilteredArrayOneDimSonar.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::FilteredArrayOneDimSonar::description () inline
convert to a string; string serialization
Definition at line 157 of file FilteredArrayOneDimSonar.hpp.
References guWhiteboard::FilteredOneDimSonar::description(), FSLeft, FSO_NUM_OBJECTS, FSRight, get_object(), LEFT_ID, RIGHT_ID, and SEPARATOR_IS_COLON.
from_string()
void guWhiteboard::FilteredArrayOneDimSonar::from_string (const std::string & str) inline
build from string
Definition at line 178 of file FilteredArrayOneDimSonar.hpp.
References FSLeft, FSRight, LEFT_ID, RIGHT_ID, SEPARATOR_IS_COLON, and set_object().
Referenced by FilteredArrayOneDimSonar().
get_object()
FilteredOneDimSonar guWhiteboard::FilteredArrayOneDimSonar::get_object (enum FilteredSonarObjectType landmarkType = FSLeft) inline
single vision object setter
Definition at line 138 of file FilteredArrayOneDimSonar.hpp.
Referenced by description().
operator=()
FilteredArrayOneDimSonar & guWhiteboard::FilteredArrayOneDimSonar::operator= (const FilteredArrayOneDimSonar & other) inline
copy assignment operator
Definition at line 112 of file FilteredArrayOneDimSonar.hpp.
set_object()
void guWhiteboard::FilteredArrayOneDimSonar::set_object (const class FilteredOneDimSonar & obj, enum FilteredSonarObjectType landmarkType = FSLeft) inline
single vision object setter
Definition at line 132 of file FilteredArrayOneDimSonar.hpp.
Referenced by from_string().
set_objects()
void guWhiteboard::FilteredArrayOneDimSonar::set_objects (const class FilteredArrayOneDimSonar * objects) inline
property getter
property setter
Parameters
objects setter object
Definition at line 126 of file FilteredArrayOneDimSonar.hpp.
The documentation for this class was generated from the following file:
typeClassDefs/FilteredArrayOneDimSonar.hpp