gusimplewhiteboard: guWhiteboard::HalArmTarget Class Reference
guWhiteboard::HalArmTarget Class Reference
Class for moving a SINGLE robotic arm with up to 6 degrees of freedom using local coords of each joint.
#include <HAL_ArmTarget.hpp>
Public Member Functions
HalArmTarget (const uint8_t &target_arm=0, const float shoulderpitch=0, const float shoulderroll=0, const float elbowroll=0, const float elbowyaw=0, const float wristyaw=0, const float hand_PCT=0, const float shoulderpitchstiffness=0, const float shoulderrollstiffness=0, const float elbowrollstiffness=0, const float elbowyawstiffness=0, const float wristyawstiffness=0, const float handstiffness=0, const bool shoulderpitch_active=true, const bool shoulderroll_active=true, const bool elbowroll_active=true, const bool elbowyaw_active=true, const bool wrist_active=true, const bool hand_active=true, const int32_t movement_time=1000000, const uint8_t pliability=10, const bool arm_stop=false, const bool inRadians=false)
Constructor, defaults to LEFT_ARM.
void tieToArm (uint8_t arm)
Specify which arm this instance manages.
void goToWithTime_Rad (float shoulderpitch, float shoulderroll, float elbowroll, float elbowyaw, float wristyaw, float hand, int32_t time=INT_MAX)
move to position in radians over a given time
void goToWithTime_Deg (float shoulderpitch, float shoulderroll, float elbowroll, float elbowyaw, float wristyaw, float hand, int32_t time=INT_MAX)
move to position expressed in degrees over a given time
void stop ()
Command the arm to stop at its current location and not act on motion commands until ready() is called.
void ready ()
Set arm to ready state (Default) The arm will act on motion commands.
void isAtGoal (bool goalReached)
Arm at Goal Setter Clients/Machines should not use this method.
bool atGoal ()
Arm at Goal Getter Clients/Machines should use this getter to test if the DCM has reported that the arm has reached its goal pose.
bool atTargetLocation (HalArmTarget status, HalArmTarget tolerance)
Client side test to determine if arm is at the target location, allowing for specified tolerances.
void setPose_Rad (float shoulderpitch, float shoulderroll, float elbowroll, float elbowyaw, float wristyaw, float hand)
Set Pose in radians.
void setPose_Deg (float shoulderpitch, float shoulderroll, float elbowroll, float elbowyaw, float wristyaw, float hand)
Set Pose in degrees.
void mirrorArm (const HalArmTarget &other)
Convenience function to mirror arm settings about the XZ plane from one HalArmTarget object to another.
void copyPose (const HalArmTarget &other)
Convenience function to copy pose settings from one HalArmTarget object to another.
void mirrorPose (const HalArmTarget &other)
Convenience function to mirror pose settings about the XZ plane from one HalArmTarget object to another.
bool hasSamePose (const HalArmTarget &other)
Tests if this HalArmTarget object has the same pose settings as the other HalArmTarget object.
bool hasSameMirroredPose (const HalArmTarget &other)
Tests if this HalArmTarget object has the same mirrored pose settings as the other HalArmTarget object.
void setArmStiffnessMax ()
Convenience function to set the stiffness of all the arm's joints to the maximum (1.0f).
void setArmStiffnessNormal ()
Convenience function to set the stiffness of all the arm's joints to what Aldebaran considers 'normal' (0.6f).
void setArmStiffness (float stiffness)
Convenience function to set uniform stiffness on all arm joints to a custom value.
void setArmStiffnessOff ()
Convenience function to turn off stiffness in all the arm's joints (0.0f).
void copyStiffness (const HalArmTarget &other)
Convenience function to copy stiffness settings from one HalArmTarget object to another.
bool hasSameStiffness (const HalArmTarget &other)
Tests if this HalArmTarget object has the same stiffness settings as the other HalArmTarget object.
void setArmActive ()
Set arm to be Active (DEDAULT DCM state) The arm is active and manual movements will be resisted, be careful when the stiffness is set high.
void setArmPassive ()
Set arm to be Passive Manually moving the arm causes the arm to remain in the new position.
void setArmPliability (bool shoulderpitch, bool shoulderroll, bool elbowroll, bool elbowyaw, bool wristyaw, bool hand)
Individually set the active/passive state of each joint.
bool isArmPassive ()
Are any of the arm's joints set to passive.
bool isArmAllPassive ()
Are all of the arm's joints set to passive.
bool isArmAllActive ()
Are all of the arm's joints set to active.
void set_shoulderpitch_DEG (float setting)
Movement Setters (Degrees)
void set_shoulderroll_DEG (float setting)
void set_elbowroll_DEG (float setting)
void set_elbowyaw_DEG (float setting)
void set_wristyaw_DEG (float setting)
void set_shoulderpitch_RAD (float setting)
Movement Setters (Radians)
void set_shoulderroll_RAD (float setting)
void set_elbowroll_RAD (float setting)
void set_elbowyaw_RAD (float setting)
void set_wristyaw_RAD (float setting)
void set_hand (float setting)
Hand Movement Setter.
void set_shoulderpitchstiffness (float setting)
Stiffness Setters.
void set_shoulderrollstiffness (float setting)
void set_elbowrollstiffness (float setting)
void set_elbowyawstiffness (float setting)
void set_wristyawstiffness (float setting)
void set_handstiffness (float setting)
float get_shoulderpitch_DEG ()
Movement Getters (Degrees)
float get_shoulderroll_DEG ()
float get_elbowroll_DEG ()
float get_elbowyaw_DEG ()
float get_wristyaw_DEG ()
float get_shoulderpitch_RAD ()
Movement Getters (Radians)
float get_shoulderroll_RAD ()
float get_elbowroll_RAD ()
float get_elbowyaw_RAD ()
float get_wristyaw_RAD ()
float get_hand ()
Hand Movement Getter.
float get_shoulderpitchstiffness ()
Stiffness Getters.
float get_shoulderrollstiffness ()
float get_elbowrollstiffness ()
float get_elbowyawstiffness ()
float get_wristyawstiffness ()
float get_handstiffness ()
std::string description () const
Description function.
HalArmTarget (const std::string &str)
String constructor (NYI)
void from_string (const std::string &str)
Parser for recreating this class (NYI)
HalArmTarget (int32_t t_target_movement_time=INT_MAX, int16_t t_target_shoulderpitch=0, int16_t t_target_shoulderroll=0, int16_t t_target_elbowroll=0, int16_t t_target_elbowyaw=0, int16_t t_target_wristyaw=0, uint8_t t_target_arm=(static_cast< uint8_t >(0)), uint8_t t_target_hand=0, uint8_t t_target_shoulderpitchstiffness=0, uint8_t t_target_shoulderrollstiffness=0, uint8_t t_target_elbowrollstiffness=0, uint8_t t_target_elbowyawstiffness=0, uint8_t t_target_wristyawstiffness=0, uint8_t t_target_handstiffness=0, uint8_t t_target_pliability=0, unsigned int t_target_shoulderpitch_active=true, unsigned int t_target_shoulderroll_active=true, unsigned int t_target_elbowroll_active=true, unsigned int t_target_elbowyaw_active=true, unsigned int t_target_wrist_active=true, unsigned int t_target_hand_active=true, unsigned int t_target_arm_at_goal=false, unsigned int t_target_arm_stop=false)
Create a new HalArmTarget.
HalArmTarget (const HalArmTarget &t_other)
Copy Constructor.
HalArmTarget (const struct wb_hal_arm_target &t_other)
Copy Constructor.
HalArmTarget & operator= (const HalArmTarget &t_other)
Copy Assignment Operator.
HalArmTarget & operator= (const struct wb_hal_arm_target &t_other)
Copy Assignment Operator.
bool operator== (const HalArmTarget &t_other) const
bool operator!= (const HalArmTarget &t_other) const
bool operator== (const wb_hal_arm_target &t_other) const
bool operator!= (const wb_hal_arm_target &t_other) const
int32_t & target_movement_time ()
const int32_t & target_movement_time () const
void set_target_movement_time (const int32_t &t_newValue)
int16_t & target_shoulderpitch ()
const int16_t & target_shoulderpitch () const
void set_target_shoulderpitch (const int16_t &t_newValue)
int16_t & target_shoulderroll ()
const int16_t & target_shoulderroll () const
void set_target_shoulderroll (const int16_t &t_newValue)
int16_t & target_elbowroll ()
const int16_t & target_elbowroll () const
void set_target_elbowroll (const int16_t &t_newValue)
int16_t & target_elbowyaw ()
const int16_t & target_elbowyaw () const
void set_target_elbowyaw (const int16_t &t_newValue)
int16_t & target_wristyaw ()
const int16_t & target_wristyaw () const
void set_target_wristyaw (const int16_t &t_newValue)
uint8_t & target_arm ()
const uint8_t & target_arm () const
void set_target_arm (const uint8_t &t_newValue)
uint8_t & target_hand ()
const uint8_t & target_hand () const
void set_target_hand (const uint8_t &t_newValue)
uint8_t & target_shoulderpitchstiffness ()
const uint8_t & target_shoulderpitchstiffness () const
void set_target_shoulderpitchstiffness (const uint8_t &t_newValue)
uint8_t & target_shoulderrollstiffness ()
const uint8_t & target_shoulderrollstiffness () const
void set_target_shoulderrollstiffness (const uint8_t &t_newValue)
uint8_t & target_elbowrollstiffness ()
const uint8_t & target_elbowrollstiffness () const
void set_target_elbowrollstiffness (const uint8_t &t_newValue)
uint8_t & target_elbowyawstiffness ()
const uint8_t & target_elbowyawstiffness () const
void set_target_elbowyawstiffness (const uint8_t &t_newValue)
uint8_t & target_wristyawstiffness ()
const uint8_t & target_wristyawstiffness () const
void set_target_wristyawstiffness (const uint8_t &t_newValue)
uint8_t & target_handstiffness ()
const uint8_t & target_handstiffness () const
void set_target_handstiffness (const uint8_t &t_newValue)
uint8_t & target_pliability ()
const uint8_t & target_pliability () const
void set_target_pliability (const uint8_t &t_newValue)
unsigned int target_shoulderpitch_active () const
void set_target_shoulderpitch_active (const unsigned int &t_newValue)
unsigned int target_shoulderroll_active () const
void set_target_shoulderroll_active (const unsigned int &t_newValue)
unsigned int target_elbowroll_active () const
void set_target_elbowroll_active (const unsigned int &t_newValue)
unsigned int target_elbowyaw_active () const
void set_target_elbowyaw_active (const unsigned int &t_newValue)
unsigned int target_wrist_active () const
void set_target_wrist_active (const unsigned int &t_newValue)
unsigned int target_hand_active () const
void set_target_hand_active (const unsigned int &t_newValue)
unsigned int target_arm_at_goal () const
void set_target_arm_at_goal (const unsigned int &t_newValue)
unsigned int target_arm_stop () const
void set_target_arm_stop (const unsigned int &t_newValue)
HalArmTarget (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
std::string valueDescription ()
WHITEBOARD_POSTER_STRING_CONVERSION.
void tieToArm (uint8_t arm)
USE_WB_HAL_ARM_TARGET_C_CONVERSION WHITEBOARD_POSTER_STRING_CONVERSION.
void goToWithTime_Rad (float shoulderpitch, float shoulderroll, float elbowroll, float elbowyaw, float wristyaw, float hand, int32_t time=INT_MAX)
move to position in radians over a given time
void goToWithTime_Deg (float shoulderpitch, float shoulderroll, float elbowroll, float elbowyaw, float wristyaw, float hand, int32_t time=INT_MAX)
move to position expressed in degrees over a given time
void stop ()
Command the arm to stop at its current location and not act on motion commands until ready() is called.
void ready ()
Set arm to ready state (Default) The arm will act on motion commands.
void isAtGoal (bool goalReached)
Arm at Goal Setter Clients/Machines should not use this method.
bool atGoal ()
Arm at Goal Getter Clients/Machines should use this getter to test if the DCM has reported that the arm has reached its goal pose.
bool atTargetLocation (HalArmTarget status, HalArmTarget tolerance)
Client side test to determine if arm is at the target location, allowing for specified tolerances.
void setPose_Rad (float shoulderpitch, float shoulderroll, float elbowroll, float elbowyaw, float wristyaw, float hand)
Set Pose in radians.
void setPose_Deg (float shoulderpitch, float shoulderroll, float elbowroll, float elbowyaw, float wristyaw, float hand)
Set Pose in degrees.
void mirrorArm (const HalArmTarget &other)
Convenience function to mirror arm settings about the XZ plane from one HalArmTarget object to another.
void copyPose (const HalArmTarget &other)
Convenience function to copy pose settings from one HalArmTarget object to another.
void mirrorPose (const HalArmTarget &other)
Convenience function to mirror pose settings about the XZ plane from one HalArmTarget object to another.
bool hasSamePose (const HalArmTarget &other)
Tests if this HalArmTarget object has the same pose settings as the other HalArmTarget object.
bool hasSameMirroredPose (const HalArmTarget &other)
Tests if this HalArmTarget object has the same mirrored pose settings as the other HalArmTarget object.
void setArmStiffnessMax ()
Convenience function to set the stiffness of all the arm's joints to the maximum (1.0f).
void setArmStiffnessNormal ()
Convenience function to set the stiffness of all the arm's joints to what Aldebaran considers 'normal' (0.6f).
void setArmStiffness (float stiffness)
Convenience function to set uniform stiffness on all arm joints to a custom value.
void setArmStiffnessOff ()
Convenience function to turn off stiffness in all the arm's joints (0.0f).
void copyStiffness (const HalArmTarget &other)
Convenience function to copy stiffness settings from one HalArmTarget object to another.
bool hasSameStiffness (const HalArmTarget &other)
Tests if this HalArmTarget object has the same stiffness settings as the other HalArmTarget object.
void setArmActive ()
Set arm to be Active (DEDAULT DCM state) The arm is active and manual movements will be resisted, be careful when the stiffness is set high.
void setArmPassive ()
Set arm to be Passive Manually moving the arm causes the arm to remain in the new position.
void setArmPliability (bool shoulderpitch, bool shoulderroll, bool elbowroll, bool elbowyaw, bool wristyaw, bool hand)
Individually set the active/passive state of each joint.
bool isArmPassive ()
Are any of the arm's joints set to passive.
bool isArmAllPassive ()
Are all of the arm's joints set to passive.
bool isArmAllActive ()
Are all of the arm's joints set to active.
void set_shoulderpitch_DEG (float setting)
Movement Setters (Degrees)
void set_shoulderroll_DEG (float setting)
void set_elbowroll_DEG (float setting)
void set_elbowyaw_DEG (float setting)
void set_wristyaw_DEG (float setting)
void set_shoulderpitch_RAD (float setting)
Movement Setters (Radians)
void set_shoulderroll_RAD (float setting)
void set_elbowroll_RAD (float setting)
void set_elbowyaw_RAD (float setting)
void set_wristyaw_RAD (float setting)
void set_hand (float setting)
Hand Movement Setter.
void set_shoulderpitchstiffness (float setting)
Stiffness Setters.
void set_shoulderrollstiffness (float setting)
void set_elbowrollstiffness (float setting)
void set_elbowyawstiffness (float setting)
void set_wristyawstiffness (float setting)
void set_handstiffness (float setting)
float get_shoulderpitch_DEG ()
Movement Getters (Degrees)
float get_shoulderroll_DEG ()
float get_elbowroll_DEG ()
float get_elbowyaw_DEG ()
float get_wristyaw_DEG ()
float get_shoulderpitch_RAD ()
Movement Getters (Radians)
float get_shoulderroll_RAD ()
float get_elbowroll_RAD ()
float get_elbowyaw_RAD ()
float get_wristyaw_RAD ()
float get_hand ()
Hand Movement Getter.
float get_shoulderpitchstiffness ()
Stiffness Getters.
float get_shoulderrollstiffness ()
float get_elbowrollstiffness ()
float get_elbowyawstiffness ()
float get_wristyawstiffness ()
float get_handstiffness ()
Public Member Functions inherited from wb_hal_armtarget
PROPERTY (int32_t, target_movement_time) PROPERTY(int16_t
Control Message: The elapsed time, in mSec, in which the movement should be completed.
target_shoulderpitch PROPERTY (int16_t, target_shoulderroll) PROPERTY(int16_t
target shoulder roll angle angle in 10ths of degrees
target_shoulderpitch target_elbowroll PROPERTY (int16_t, target_elbowyaw) PROPERTY(int16_t
target elbow yaw angle in 10ths of degrees
target_shoulderpitch target_elbowroll target_wristyaw PROPERTY (uint8_t, target_arm) PROPERTY(uint8_t
target arm number This property is used strictly for accounting purposes when the struct is stored within an array and the robot has numerous arms.
target_shoulderpitch target_elbowroll target_wristyaw target_hand PROPERTY (uint8_t, target_shoulderpitchstiffness) PROPERTY(uint8_t
target shoulder pitch stiffness as a percentage
target_shoulderpitch target_elbowroll target_wristyaw target_hand target_shoulderrollstiffness PROPERTY (uint8_t, target_elbowrollstiffness) PROPERTY(uint8_t
target elbow roll stiffness as a percentage
target_shoulderpitch target_elbowroll target_wristyaw target_hand target_shoulderrollstiffness target_elbowyawstiffness PROPERTY (uint8_t, target_wristyawstiffness) PROPERTY(uint8_t
target wrist yaw stiffness as a percentage
target_shoulderpitch target_elbowroll target_wristyaw target_hand target_shoulderrollstiffness target_elbowyawstiffness target_handstiffness PROPERTY (uint8_t, target_pliability) BIT_PROPERTY(target_shoulderpitch_active) BIT_PROPERTY(target_shoulderroll_active) BIT_PROPERTY(target_elbowroll_active) BIT_PROPERTY(target_elbowyaw_active) BIT_PROPERTY(target_wrist_active) BIT_PROPERTY(target_hand_active) BIT_PROPERTY(target_arm_at_goal) BIT_PROPERTY(target_arm_stop) wb_hal_armtarget(uint8_t arm=0
target arm's pliability when in Passive Mode When the arm is passive, this value reduces the update frequency, thus making the arm more resistant to external forces.
Additional Inherited Members
Public Attributes inherited from wb_hal_armtarget
target_shoulderpitch target_elbowroll target_wristyaw target_hand target_shoulderrollstiffness target_elbowyawstiffness target_handstiffness int16_t shoulderpitch = 0
target_shoulderpitch target_elbowroll target_wristyaw target_hand target_shoulderrollstiffness target_elbowyawstiffness target_handstiffness int16_t int16_t shoulderroll = 0
target_shoulderpitch target_elbowroll target_wristyaw target_hand target_shoulderrollstiffness target_elbowyawstiffness target_handstiffness int16_t int16_t int16_t elbowroll = 0
target_shoulderpitch target_elbowroll target_wristyaw target_hand target_shoulderrollstiffness target_elbowyawstiffness target_handstiffness int16_t int16_t int16_t int16_t elbowyaw = 0
target_shoulderpitch target_elbowroll target_wristyaw target_hand target_shoulderrollstiffness target_elbowyawstiffness target_handstiffness int16_t int16_t int16_t int16_t int16_t wristyaw = 0
target_shoulderpitch target_elbowroll target_wristyaw target_hand target_shoulderrollstiffness target_elbowyawstiffness target_handstiffness int16_t int16_t int16_t int16_t int16_t uint8_t hand = 0
target_shoulderpitch target_elbowroll target_wristyaw target_hand target_shoulderrollstiffness target_elbowyawstiffness target_handstiffness int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t shoulderpitchstiffness = 0
target_shoulderpitch target_elbowroll target_wristyaw target_hand target_shoulderrollstiffness target_elbowyawstiffness target_handstiffness int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t shoulderrollstiffness = 0
target_shoulderpitch target_elbowroll target_wristyaw target_hand target_shoulderrollstiffness target_elbowyawstiffness target_handstiffness int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t elbowrollstiffness = 0
target_shoulderpitch target_elbowroll target_wristyaw target_hand target_shoulderrollstiffness target_elbowyawstiffness target_handstiffness int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t uint8_t elbowyawstiffness = 0
target_shoulderpitch target_elbowroll target_wristyaw target_hand target_shoulderrollstiffness target_elbowyawstiffness target_handstiffness int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t wristyawstiffness = 0
target_shoulderpitch target_elbowroll target_wristyaw target_hand target_shoulderrollstiffness target_elbowyawstiffness target_handstiffness int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t handstiffness = 0
target_shoulderpitch target_elbowroll target_wristyaw target_hand target_shoulderrollstiffness target_elbowyawstiffness target_handstiffness int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t bool shoulderpitch_active = true
target_shoulderpitch target_elbowroll target_wristyaw target_hand target_shoulderrollstiffness target_elbowyawstiffness target_handstiffness int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t bool bool shoulderroll_active = true
target_shoulderpitch target_elbowroll target_wristyaw target_hand target_shoulderrollstiffness target_elbowyawstiffness target_handstiffness int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t bool bool bool elbowroll_active = true
target_shoulderpitch target_elbowroll target_wristyaw target_hand target_shoulderrollstiffness target_elbowyawstiffness target_handstiffness int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t bool bool bool bool elbowyaw_active = true
target_shoulderpitch target_elbowroll target_wristyaw target_hand target_shoulderrollstiffness target_elbowyawstiffness target_handstiffness int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t bool bool bool bool bool wrist_active = true
target_shoulderpitch target_elbowroll target_wristyaw target_hand target_shoulderrollstiffness target_elbowyawstiffness target_handstiffness int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t bool bool bool bool bool bool hand_active = true
target_shoulderpitch target_elbowroll target_wristyaw target_hand target_shoulderrollstiffness target_elbowyawstiffness target_handstiffness int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t bool bool bool bool bool bool int32_t movement_time = INT_MAX
target_shoulderpitch target_elbowroll target_wristyaw target_hand target_shoulderrollstiffness target_elbowyawstiffness target_handstiffness int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t bool bool bool bool bool bool int32_t uint8_t pliability = 0
target_shoulderpitch target_elbowroll target_wristyaw target_hand target_shoulderrollstiffness target_elbowyawstiffness target_handstiffness int16_t int16_t int16_t int16_t int16_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t uint8_t bool bool bool bool bool bool int32_t uint8_t bool arm_at_goal = false
Public Attributes inherited from wb_hal_arm_target
int32_t target_movement_time
The elapsed time, in mSec, in which the movement should be completed.
int16_t target_shoulderpitch
target shoulder pitch angle in 10ths of degrees
int16_t target_shoulderroll
target shoulder roll angle angle in 10ths of degrees
int16_t target_elbowroll
target elbow roll angle in 10ths of degrees
int16_t target_elbowyaw
target elbow yaw angle in 10ths of degrees
int16_t target_wristyaw
target wrist yaw angle in 10ths of degrees
uint8_t target_arm
target arm number: This property is used strictly for accounting purposes when the struct is stored within an array and the robot has numerous arms.
uint8_t target_hand
target hand grasper opening as a percentage: 0 gripper will be clasped shut, 100 gripper will be fully openned
uint8_t target_shoulderpitchstiffness
target shoulder pitch stiffness as a percentage
uint8_t target_shoulderrollstiffness
target shoulder roll stiffness as a percentage
uint8_t target_elbowrollstiffness
target elbow roll stiffness as a percentage
uint8_t target_elbowyawstiffness
target elbow yaw stiffness as a percentage
uint8_t target_wristyawstiffness
target wrist yaw stiffness as a percentage
uint8_t target_handstiffness
target hand grasper stiffness as a percentage
uint8_t target_pliability
target arm's pliability when in Passive Mode.
unsigned int target_shoulderpitch_active: 1
Is the shoulderpitch Active (true[DEFAULT]) or Passive (false).
unsigned int target_shoulderroll_active: 1
Is the shoulderroll Active (true[DEFAULT]) or Passive (false)
unsigned int target_elbowroll_active: 1
Is the elbowroll Active (true[DEFAULT]) or Passive (false)
unsigned int target_elbowyaw_active: 1
Is the elbowyaw Active (true[DEFAULT]) or Passive (false)
unsigned int target_wrist_active: 1
Is the wrist Active (true[DEFAULT]) or Passive (false)
unsigned int target_hand_active: 1
Is the hand Active (true[DEFAULT]) or Passive (false)
unsigned int target_arm_at_goal: 1
Control Message: Not used.
unsigned int target_arm_stop: 1
Control Message: Stop the arm at its current location.
Detailed Description
Class for moving a SINGLE robotic arm with up to 6 degrees of freedom using local coords of each joint.
Provides a C++ wrapper around wb_hal_arm_target.
NAO Arm has upto 6 degrees of freedom with the axes being: 'shoulder pitch, shoulder roll, elbow roll, elbow yaw, wrist yaw, gripper position'. (NOTE: The V3 does not have wrist yaw or gripper capabilites. Naoqi Interface will automatically ignore wrist and hand settings if the robot does not have them.) The left and right arm are mirrored about the XZ plane as are the movement limits and ranges. (doc-release-1.14.5-public/doc-release-1.14-public/family/robots/links_robot.html)
Move the robotic arm to the (local) coord provided in this class.
Examples
Examples of what to do with the class
Move (left) arm down such that it is parallel to the body at an angle of 5 deg with elbow straight,
inner-forearm and palm facing body, gripper closed over 1 second
HalArmTarget().GoToWithTime_Rad(1.5708, 0.0873, -0.0349, -1.5708, -1.5708, 0.0f 10000);
HalArmTarget().GoToWithTime_Deg(90, 5, -2, -90, -90, 0.0 10000);
     // Note the NAO elbow cannot actually move to a roll angle of 0 degrees.
Move (right) arm down such that it is parallel to the body at an angle of 5 deg with elbow straight,
inner-forearm and palm facing body, gripper fully openned over 1 second
HalArmTarget().GoToWithTime_Rad(1.5708, -0.0873, 0.0349, 1.5708, 1.5708, 1.0, 10000);
HalArmTarget().GoToWithTime_Deg(90, -5, 2, 90, 90, 1.0, 10000);
     // Note the NAO elbow cannot actually move to a roll angle of 0 degrees.
HalArmTarget().Active();    // Puts the arm into active mode, Naoqi DCM default.
HalArmTarget().Passive();   // Puts the arm into passive mode, allowing the arm to be manupulated by external forces.
Class values need to be passed to the Whiteboard, using the handler, for them to take effect.
HalArmTarget_t.set(HalArmTarget());
HalArmTarget_t.set(HalArmTarget().Passive());
Definition at line 61 of file HAL_ArmTarget.hpp.
Constructor & Destructor Documentation
HalArmTarget() [1/6]
guWhiteboard::HalArmTarget::HalArmTarget (const uint8_t & target_arm = 0, const float shoulderpitch = 0, const float shoulderroll = 0, const float elbowroll = 0, const float elbowyaw = 0, const float wristyaw = 0, const float hand_PCT = 0, const float shoulderpitchstiffness = 0, const float shoulderrollstiffness = 0, const float elbowrollstiffness = 0, const float elbowyawstiffness = 0, const float wristyawstiffness = 0, const float handstiffness = 0, const bool shoulderpitch_active = true, const bool shoulderroll_active = true, const bool elbowroll_active = true, const bool elbowyaw_active = true, const bool wrist_active = true, const bool hand_active = true, const int32_t movement_time = 1000000, const uint8_t pliability = 10, const bool arm_stop = false, const bool inRadians = false) inline
Constructor, defaults to LEFT_ARM.
Constructor using float parameters This constructor should be used because the whiteboard holds integer representations of the angles.
Definition at line 76 of file HAL_ArmTarget.hpp.
References wb_hal_armtarget::elbowroll, wb_hal_armtarget::elbowroll_active, wb_hal_armtarget::elbowrollstiffness, wb_hal_armtarget::elbowyaw, wb_hal_armtarget::elbowyaw_active, wb_hal_armtarget::elbowyawstiffness, wb_hal_armtarget::hand_active, wb_hal_armtarget::handstiffness, wb_hal_armtarget::movement_time, wb_hal_armtarget::pliability, set_elbowrollstiffness(), set_elbowyawstiffness(), set_handstiffness(), set_shoulderpitchstiffness(), set_shoulderrollstiffness(), set_target_arm_stop(), set_target_movement_time(), set_target_pliability(), set_wristyawstiffness(), setArmPliability(), setPose_Deg(), setPose_Rad(), wb_hal_armtarget::shoulderpitch, wb_hal_armtarget::shoulderpitch_active, wb_hal_armtarget::shoulderpitchstiffness, wb_hal_armtarget::shoulderroll, wb_hal_armtarget::shoulderroll_active, wb_hal_armtarget::shoulderrollstiffness, wb_hal_armtarget::wrist_active, wb_hal_armtarget::wristyaw, and wb_hal_armtarget::wristyawstiffness.
Referenced by operator==().
HalArmTarget() [2/6]
guWhiteboard::HalArmTarget::HalArmTarget (const std::string & str) inline
String constructor (NYI)
Parameters
str the string to parse and use to recreate the this object
Definition at line 860 of file HAL_ArmTarget.hpp.
References from_string().
HalArmTarget() [3/6]
guWhiteboard::HalArmTarget::HalArmTarget (int32_t t_target_movement_time = INT_MAX, int16_t t_target_shoulderpitch = 0, int16_t t_target_shoulderroll = 0, int16_t t_target_elbowroll = 0, int16_t t_target_elbowyaw = 0, int16_t t_target_wristyaw = 0, uint8_t t_target_arm = (static_cast<uint8_t>(0)), uint8_t t_target_hand = 0, uint8_t t_target_shoulderpitchstiffness = 0, uint8_t t_target_shoulderrollstiffness = 0, uint8_t t_target_elbowrollstiffness = 0, uint8_t t_target_elbowyawstiffness = 0, uint8_t t_target_wristyawstiffness = 0, uint8_t t_target_handstiffness = 0, uint8_t t_target_pliability = 0, unsigned int t_target_shoulderpitch_active = true, unsigned int t_target_shoulderroll_active = true, unsigned int t_target_elbowroll_active = true, unsigned int t_target_elbowyaw_active = true, unsigned int t_target_wrist_active = true, unsigned int t_target_hand_active = true, unsigned int t_target_arm_at_goal = false, unsigned int t_target_arm_stop = false) inline
Create a new HalArmTarget.
Definition at line 121 of file HalArmTarget.hpp.
HalArmTarget() [4/6]
guWhiteboard::HalArmTarget::HalArmTarget (const HalArmTarget & t_other) inline
Copy Constructor.
Definition at line 128 of file HalArmTarget.hpp.
HalArmTarget() [5/6]
guWhiteboard::HalArmTarget::HalArmTarget (const struct wb_hal_arm_target & t_other) inline
Copy Constructor.
Definition at line 135 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_arm, wb_hal_arm_target::target_arm_at_goal, wb_hal_arm_target::target_arm_stop, wb_hal_arm_target::target_elbowroll, wb_hal_arm_target::target_elbowroll_active, wb_hal_arm_target::target_elbowrollstiffness, wb_hal_arm_target::target_elbowyaw, wb_hal_arm_target::target_elbowyaw_active, wb_hal_arm_target::target_elbowyawstiffness, wb_hal_arm_target::target_hand, wb_hal_arm_target::target_hand_active, wb_hal_arm_target::target_handstiffness, wb_hal_arm_target::target_movement_time, wb_hal_arm_target::target_pliability, wb_hal_arm_target::target_shoulderpitch, wb_hal_arm_target::target_shoulderpitch_active, wb_hal_arm_target::target_shoulderpitchstiffness, wb_hal_arm_target::target_shoulderroll, wb_hal_arm_target::target_shoulderroll_active, wb_hal_arm_target::target_shoulderrollstiffness, wb_hal_arm_target::target_wrist_active, wb_hal_arm_target::target_wristyaw, and wb_hal_arm_target::target_wristyawstiffness.
HalArmTarget() [6/6]
guWhiteboard::HalArmTarget::HalArmTarget (const std::string & t_str) inline
String Constructor.
Definition at line 506 of file HalArmTarget.hpp.
References from_string().
Member Function Documentation
atGoal() [1/2]
bool guWhiteboard::HalArmTarget::atGoal () inline
Arm at Goal Getter Clients/Machines should use this getter to test if the DCM has reported that the arm has reached its goal pose.
Is the arm at the goal pose? Naoqi Interface sets this true when the arm reaches the goal pose asked for in the previous control message.
Returns
bool whether the arm is at the goal location or not.
Definition at line 273 of file HAL_ArmTarget.hpp.
References target_arm_at_goal().
atGoal() [2/2]
bool guWhiteboard::HalArmTarget::atGoal () inline
Arm at Goal Getter Clients/Machines should use this getter to test if the DCM has reported that the arm has reached its goal pose.
Is the arm at the goal pose? Naoqi Interface sets this true when the arm reaches the goal pose asked for in the previous control message.
Returns
bool whether the arm is at the goal location or not.
Definition at line 1029 of file HalArmTarget.hpp.
References target_arm_at_goal().
atTargetLocation() [1/2]
bool guWhiteboard::HalArmTarget::atTargetLocation (HalArmTarget status, HalArmTarget tolerance) inline
Client side test to determine if arm is at the target location, allowing for specified tolerances.
The method tests if the pose 'status' is within 'tolerance' of 'this' target location, allowing for a specified tolerance.
'this' object contains the target pose settings.
Parameters
status HalArmTarget object which contains actual pose settings reported by the robot's sensors.
tolerance HalArmTarget object whose pose settings specify the tolerance for each joint/gripper
Returns
bool whether or not the status is within range of the target location.
Definition at line 290 of file HAL_ArmTarget.hpp.
References target_elbowroll(), target_elbowyaw(), target_shoulderpitch(), and target_shoulderroll().
atTargetLocation() [2/2]
bool guWhiteboard::HalArmTarget::atTargetLocation (HalArmTarget status, HalArmTarget tolerance) inline
Client side test to determine if arm is at the target location, allowing for specified tolerances.
The method tests if the pose 'status' is within 'tolerance' of 'this' target location, allowing for a specified tolerance.
'this' object contains the target pose settings.
Parameters
status HalArmTarget object which contains actual pose settings reported by the robot's sensors.
tolerance HalArmTarget object whose pose settings specify the tolerance for each joint/gripper
Returns
bool whether or not the status is within range of the target location.
Definition at line 1046 of file HalArmTarget.hpp.
References target_elbowroll(), target_elbowyaw(), target_shoulderpitch(), and target_shoulderroll().
copyPose() [1/2]
void guWhiteboard::HalArmTarget::copyPose (const HalArmTarget & other) inline
Convenience function to copy pose settings from one HalArmTarget object to another.
Parameters
other HalArmTarget object from which to copy pose settings from.
Definition at line 403 of file HAL_ArmTarget.hpp.
References set_target_elbowroll(), set_target_elbowyaw(), set_target_hand(), set_target_shoulderpitch(), set_target_shoulderroll(), set_target_wristyaw(), target_elbowroll(), target_elbowyaw(), target_hand(), target_shoulderpitch(), target_shoulderroll(), and target_wristyaw().
copyPose() [2/2]
void guWhiteboard::HalArmTarget::copyPose (const HalArmTarget & other) inline
Convenience function to copy pose settings from one HalArmTarget object to another.
Parameters
other HalArmTarget object from which to copy pose settings from.
Definition at line 1159 of file HalArmTarget.hpp.
References set_target_elbowroll(), set_target_elbowyaw(), set_target_hand(), set_target_shoulderpitch(), set_target_shoulderroll(), and set_target_wristyaw().
copyStiffness() [1/2]
void guWhiteboard::HalArmTarget::copyStiffness (const HalArmTarget & other) inline
Convenience function to copy stiffness settings from one HalArmTarget object to another.
Parameters
other HalArmTarget object from which to copy stiffness settings.
Definition at line 551 of file HAL_ArmTarget.hpp.
References target_elbowrollstiffness(), target_elbowyawstiffness(), target_handstiffness(), target_shoulderpitchstiffness(), target_shoulderrollstiffness(), and target_wristyawstiffness().
copyStiffness() [2/2]
void guWhiteboard::HalArmTarget::copyStiffness (const HalArmTarget & other) inline
Convenience function to copy stiffness settings from one HalArmTarget object to another.
Parameters
other HalArmTarget object from which to copy stiffness settings.
Definition at line 1307 of file HalArmTarget.hpp.
References set_target_elbowrollstiffness(), set_target_elbowyawstiffness(), set_target_handstiffness(), set_target_shoulderpitchstiffness(), set_target_shoulderrollstiffness(), and set_target_wristyawstiffness().
description() [1/2]
std::string guWhiteboard::HalArmTarget::description () inline
USE_WB_HAL_ARM_TARGET_C_CONVERSION
Definition at line 511 of file HalArmTarget.hpp.
References HAL_ARM_TARGET_DESC_BUFFER_SIZE, target_arm(), target_arm_at_goal(), target_arm_stop(), target_elbowroll(), target_elbowroll_active(), target_elbowrollstiffness(), target_elbowyaw(), target_elbowyaw_active(), target_elbowyawstiffness(), target_hand(), target_hand_active(), target_handstiffness(), target_movement_time(), target_pliability(), target_shoulderpitch(), target_shoulderpitch_active(), target_shoulderpitchstiffness(), target_shoulderroll(), target_shoulderroll_active(), target_shoulderrollstiffness(), target_wrist_active(), target_wristyaw(), target_wristyawstiffness(), and wb_hal_arm_target_description().
description() [2/2]
std::string guWhiteboard::HalArmTarget::description () const inline
Description function.
Definition at line 826 of file HAL_ArmTarget.hpp.
References target_arm_at_goal(), target_arm_stop(), target_elbowroll(), target_elbowroll_active(), target_elbowrollstiffness(), target_elbowyaw(), target_elbowyaw_active(), target_elbowyawstiffness(), target_hand(), target_hand_active(), target_handstiffness(), target_movement_time(), target_pliability(), target_shoulderpitch(), target_shoulderpitch_active(), target_shoulderpitchstiffness(), target_shoulderroll(), target_shoulderroll_active(), target_shoulderrollstiffness(), target_wrist_active(), target_wristyaw(), and target_wristyawstiffness().
from_string() [1/2]
void guWhiteboard::HalArmTarget::from_string (const std::string & str) inline
Parser for recreating this class (NYI)
Parameters
str the string to parse and use to recreate the this object
Definition at line 866 of file HAL_ArmTarget.hpp.
Referenced by HalArmTarget().
from_string() [2/2]
void guWhiteboard::HalArmTarget::from_string (const std::string & t_str) inline
USE_WB_HAL_ARM_TARGET_C_CONVERSION
Definition at line 629 of file HalArmTarget.hpp.
References HAL_ARM_TARGET_DESC_BUFFER_SIZE, set_target_arm(), set_target_arm_at_goal(), set_target_arm_stop(), set_target_elbowroll(), set_target_elbowroll_active(), set_target_elbowrollstiffness(), set_target_elbowyaw(), set_target_elbowyaw_active(), set_target_elbowyawstiffness(), set_target_hand(), set_target_hand_active(), set_target_handstiffness(), set_target_movement_time(), set_target_pliability(), set_target_shoulderpitch(), set_target_shoulderpitch_active(), set_target_shoulderpitchstiffness(), set_target_shoulderroll(), set_target_shoulderroll_active(), set_target_shoulderrollstiffness(), set_target_wrist_active(), set_target_wristyaw(), and set_target_wristyawstiffness().
get_elbowroll_DEG() [1/2]
float guWhiteboard::HalArmTarget::get_elbowroll_DEG () inline
Definition at line 758 of file HAL_ArmTarget.hpp.
References target_elbowroll().
get_elbowroll_DEG() [2/2]
float guWhiteboard::HalArmTarget::get_elbowroll_DEG () inline
Definition at line 1514 of file HalArmTarget.hpp.
References target_elbowroll().
get_elbowroll_RAD() [1/2]
float guWhiteboard::HalArmTarget::get_elbowroll_RAD () inline
Definition at line 779 of file HAL_ArmTarget.hpp.
References target_elbowroll().
get_elbowroll_RAD() [2/2]
float guWhiteboard::HalArmTarget::get_elbowroll_RAD () inline
Definition at line 1535 of file HalArmTarget.hpp.
References target_elbowroll().
get_elbowrollstiffness() [1/2]
float guWhiteboard::HalArmTarget::get_elbowrollstiffness () inline
Definition at line 805 of file HAL_ArmTarget.hpp.
References target_elbowrollstiffness().
get_elbowrollstiffness() [2/2]
float guWhiteboard::HalArmTarget::get_elbowrollstiffness () inline
Definition at line 1561 of file HalArmTarget.hpp.
References target_elbowrollstiffness().
get_elbowyaw_DEG() [1/2]
float guWhiteboard::HalArmTarget::get_elbowyaw_DEG () inline
Definition at line 762 of file HAL_ArmTarget.hpp.
References target_elbowyaw().
get_elbowyaw_DEG() [2/2]
float guWhiteboard::HalArmTarget::get_elbowyaw_DEG () inline
Definition at line 1518 of file HalArmTarget.hpp.
References target_elbowyaw().
get_elbowyaw_RAD() [1/2]
float guWhiteboard::HalArmTarget::get_elbowyaw_RAD () inline
Definition at line 783 of file HAL_ArmTarget.hpp.
References target_elbowyaw().
get_elbowyaw_RAD() [2/2]
float guWhiteboard::HalArmTarget::get_elbowyaw_RAD () inline
Definition at line 1539 of file HalArmTarget.hpp.
References target_elbowyaw().
get_elbowyawstiffness() [1/2]
float guWhiteboard::HalArmTarget::get_elbowyawstiffness () inline
Definition at line 809 of file HAL_ArmTarget.hpp.
References target_elbowyawstiffness().
get_elbowyawstiffness() [2/2]
float guWhiteboard::HalArmTarget::get_elbowyawstiffness () inline
Definition at line 1565 of file HalArmTarget.hpp.
References target_elbowyawstiffness().
get_hand() [1/2]
float guWhiteboard::HalArmTarget::get_hand () inline
Hand Movement Getter.
Definition at line 792 of file HAL_ArmTarget.hpp.
References target_hand().
get_hand() [2/2]
float guWhiteboard::HalArmTarget::get_hand () inline
Hand Movement Getter.
Definition at line 1548 of file HalArmTarget.hpp.
References target_hand().
get_handstiffness() [1/2]
float guWhiteboard::HalArmTarget::get_handstiffness () inline
Definition at line 817 of file HAL_ArmTarget.hpp.
References target_handstiffness().
get_handstiffness() [2/2]
float guWhiteboard::HalArmTarget::get_handstiffness () inline
Definition at line 1573 of file HalArmTarget.hpp.
References target_handstiffness().
get_shoulderpitch_DEG() [1/2]
float guWhiteboard::HalArmTarget::get_shoulderpitch_DEG () inline
Movement Getters (Degrees)
Definition at line 750 of file HAL_ArmTarget.hpp.
References target_shoulderpitch().
get_shoulderpitch_DEG() [2/2]
float guWhiteboard::HalArmTarget::get_shoulderpitch_DEG () inline
Movement Getters (Degrees)
Definition at line 1506 of file HalArmTarget.hpp.
References target_shoulderpitch().
get_shoulderpitch_RAD() [1/2]
float guWhiteboard::HalArmTarget::get_shoulderpitch_RAD () inline
Movement Getters (Radians)
Definition at line 771 of file HAL_ArmTarget.hpp.
References target_shoulderpitch().
get_shoulderpitch_RAD() [2/2]
float guWhiteboard::HalArmTarget::get_shoulderpitch_RAD () inline
Movement Getters (Radians)
Definition at line 1527 of file HalArmTarget.hpp.
References target_shoulderpitch().
get_shoulderpitchstiffness() [1/2]
float guWhiteboard::HalArmTarget::get_shoulderpitchstiffness () inline
Stiffness Getters.
Definition at line 797 of file HAL_ArmTarget.hpp.
References target_shoulderpitchstiffness().
get_shoulderpitchstiffness() [2/2]
float guWhiteboard::HalArmTarget::get_shoulderpitchstiffness () inline
Stiffness Getters.
Definition at line 1553 of file HalArmTarget.hpp.
References target_shoulderpitchstiffness().
get_shoulderroll_DEG() [1/2]
float guWhiteboard::HalArmTarget::get_shoulderroll_DEG () inline
Definition at line 754 of file HAL_ArmTarget.hpp.
References target_shoulderroll().
get_shoulderroll_DEG() [2/2]
float guWhiteboard::HalArmTarget::get_shoulderroll_DEG () inline
Definition at line 1510 of file HalArmTarget.hpp.
References target_shoulderroll().
get_shoulderroll_RAD() [1/2]
float guWhiteboard::HalArmTarget::get_shoulderroll_RAD () inline
Definition at line 775 of file HAL_ArmTarget.hpp.
References target_shoulderroll().
get_shoulderroll_RAD() [2/2]
float guWhiteboard::HalArmTarget::get_shoulderroll_RAD () inline
Definition at line 1531 of file HalArmTarget.hpp.
References target_shoulderroll().
get_shoulderrollstiffness() [1/2]
float guWhiteboard::HalArmTarget::get_shoulderrollstiffness () inline
Definition at line 801 of file HAL_ArmTarget.hpp.
References target_shoulderrollstiffness().
get_shoulderrollstiffness() [2/2]
float guWhiteboard::HalArmTarget::get_shoulderrollstiffness () inline
Definition at line 1557 of file HalArmTarget.hpp.
References target_shoulderrollstiffness().
get_wristyaw_DEG() [1/2]
float guWhiteboard::HalArmTarget::get_wristyaw_DEG () inline
Definition at line 766 of file HAL_ArmTarget.hpp.
References target_wristyaw().
get_wristyaw_DEG() [2/2]
float guWhiteboard::HalArmTarget::get_wristyaw_DEG () inline
Definition at line 1522 of file HalArmTarget.hpp.
References target_wristyaw().
get_wristyaw_RAD() [1/2]
float guWhiteboard::HalArmTarget::get_wristyaw_RAD () inline
Definition at line 787 of file HAL_ArmTarget.hpp.
References target_wristyaw().
get_wristyaw_RAD() [2/2]
float guWhiteboard::HalArmTarget::get_wristyaw_RAD () inline
Definition at line 1543 of file HalArmTarget.hpp.
References target_wristyaw().
get_wristyawstiffness() [1/2]
float guWhiteboard::HalArmTarget::get_wristyawstiffness () inline
Definition at line 813 of file HAL_ArmTarget.hpp.
References target_wristyawstiffness().
get_wristyawstiffness() [2/2]
float guWhiteboard::HalArmTarget::get_wristyawstiffness () inline
Definition at line 1569 of file HalArmTarget.hpp.
References target_wristyawstiffness().
goToWithTime_Deg() [1/2]
void guWhiteboard::HalArmTarget::goToWithTime_Deg (float shoulderpitch, float shoulderroll, float elbowroll, float elbowyaw, float wristyaw, float hand, int32_t time = INT_MAX) inline
move to position expressed in degrees over a given time
Parameters
shoulderpitch down to up
shoulderroll out to in
elbowroll straight to bent
elbowyaw rolled right to rolled left
wristyaw rolled right to rolled left
hand closed to open
time elapsed time in mSec for the motion to complete.
Definition at line 211 of file HAL_ArmTarget.hpp.
References wb_hal_armtarget::elbowroll, wb_hal_armtarget::elbowyaw, wb_hal_armtarget::hand, set_target_movement_time(), setPose_Deg(), wb_hal_armtarget::shoulderpitch, wb_hal_armtarget::shoulderroll, and wb_hal_armtarget::wristyaw.
goToWithTime_Deg() [2/2]
void guWhiteboard::HalArmTarget::goToWithTime_Deg (float shoulderpitch, float shoulderroll, float elbowroll, float elbowyaw, float wristyaw, float hand, int32_t time = INT_MAX) inline
move to position expressed in degrees over a given time
Parameters
shoulderpitch down to up
shoulderroll out to in
elbowroll straight to bent
elbowyaw rolled right to rolled left
wristyaw rolled right to rolled left
hand closed to open
time elapsed time in mSec for the motion to complete.
Definition at line 967 of file HalArmTarget.hpp.
References wb_hal_armtarget::elbowroll, wb_hal_armtarget::elbowyaw, wb_hal_armtarget::hand, set_target_movement_time(), setPose_Deg(), wb_hal_armtarget::shoulderpitch, wb_hal_armtarget::shoulderroll, and wb_hal_armtarget::wristyaw.
goToWithTime_Rad() [1/2]
void guWhiteboard::HalArmTarget::goToWithTime_Rad (float shoulderpitch, float shoulderroll, float elbowroll, float elbowyaw, float wristyaw, float hand, int32_t time = INT_MAX) inline
move to position in radians over a given time
Parameters
shoulderpitch down to up
shoulderroll out to in
elbowroll straight to bent
elbowyaw rolled right to rolled left
wristyaw rolled right to rolled left
hand closed to open
time elapsed time in mSec for the motion to complete.
Definition at line 186 of file HAL_ArmTarget.hpp.
References wb_hal_armtarget::elbowroll, wb_hal_armtarget::elbowyaw, wb_hal_armtarget::hand, set_target_movement_time(), setPose_Rad(), wb_hal_armtarget::shoulderpitch, wb_hal_armtarget::shoulderroll, and wb_hal_armtarget::wristyaw.
goToWithTime_Rad() [2/2]
void guWhiteboard::HalArmTarget::goToWithTime_Rad (float shoulderpitch, float shoulderroll, float elbowroll, float elbowyaw, float wristyaw, float hand, int32_t time = INT_MAX) inline
move to position in radians over a given time
Parameters
shoulderpitch down to up
shoulderroll out to in
elbowroll straight to bent
elbowyaw rolled right to rolled left
wristyaw rolled right to rolled left
hand closed to open
time elapsed time in mSec for the motion to complete.
Definition at line 942 of file HalArmTarget.hpp.
References wb_hal_armtarget::elbowroll, wb_hal_armtarget::elbowyaw, wb_hal_armtarget::hand, set_target_movement_time(), setPose_Rad(), wb_hal_armtarget::shoulderpitch, wb_hal_armtarget::shoulderroll, and wb_hal_armtarget::wristyaw.
hasSameMirroredPose() [1/2]
bool guWhiteboard::HalArmTarget::hasSameMirroredPose (const HalArmTarget & other) inline
Tests if this HalArmTarget object has the same mirrored pose settings as the other HalArmTarget object.
NOTE this method takes into account mirroring about the XZ plane.
Parameters
other HalArmTarget object whose pose settings are being compared.
Returns
bool whether the two objects have the same pose or not.
Definition at line 461 of file HAL_ArmTarget.hpp.
References target_elbowroll(), target_elbowyaw(), target_hand(), target_shoulderpitch(), target_shoulderroll(), and target_wristyaw().
hasSameMirroredPose() [2/2]
bool guWhiteboard::HalArmTarget::hasSameMirroredPose (const HalArmTarget & other) inline
Tests if this HalArmTarget object has the same mirrored pose settings as the other HalArmTarget object.
NOTE this method takes into account mirroring about the XZ plane.
Parameters
other HalArmTarget object whose pose settings are being compared.
Returns
bool whether the two objects have the same pose or not.
Definition at line 1217 of file HalArmTarget.hpp.
References target_elbowroll(), target_elbowyaw(), target_hand(), target_shoulderpitch(), target_shoulderroll(), and target_wristyaw().
hasSamePose() [1/2]
bool guWhiteboard::HalArmTarget::hasSamePose (const HalArmTarget & other) inline
Tests if this HalArmTarget object has the same pose settings as the other HalArmTarget object.
NOTE this does not take into account mirroring about the XZ plane.
Parameters
other HalArmTarget object whose pose settings are being compared.
Returns
bool whether the two objects have the same pose or not.
Definition at line 437 of file HAL_ArmTarget.hpp.
References target_elbowroll(), target_elbowyaw(), target_hand(), target_shoulderpitch(), target_shoulderroll(), and target_wristyaw().
hasSamePose() [2/2]
bool guWhiteboard::HalArmTarget::hasSamePose (const HalArmTarget & other) inline
Tests if this HalArmTarget object has the same pose settings as the other HalArmTarget object.
NOTE this does not take into account mirroring about the XZ plane.
Parameters
other HalArmTarget object whose pose settings are being compared.
Returns
bool whether the two objects have the same pose or not.
Definition at line 1193 of file HalArmTarget.hpp.
References target_elbowroll(), target_elbowyaw(), target_hand(), target_shoulderpitch(), target_shoulderroll(), and target_wristyaw().
hasSameStiffness() [1/2]
bool guWhiteboard::HalArmTarget::hasSameStiffness (const HalArmTarget & other) inline
Tests if this HalArmTarget object has the same stiffness settings as the other HalArmTarget object.
Parameters
other HalArmTarget object whose stiffness settings are being compared.
Returns
bool whether the two objects have the same stiffness or not.
Definition at line 570 of file HAL_ArmTarget.hpp.
References target_elbowrollstiffness(), target_elbowyawstiffness(), target_handstiffness(), target_shoulderpitchstiffness(), target_shoulderrollstiffness(), and target_wristyawstiffness().
hasSameStiffness() [2/2]
bool guWhiteboard::HalArmTarget::hasSameStiffness (const HalArmTarget & other) inline
Tests if this HalArmTarget object has the same stiffness settings as the other HalArmTarget object.
Parameters
other HalArmTarget object whose stiffness settings are being compared.
Returns
bool whether the two objects have the same stiffness or not.
Definition at line 1326 of file HalArmTarget.hpp.
References target_elbowrollstiffness(), target_elbowyawstiffness(), target_handstiffness(), target_shoulderpitchstiffness(), target_shoulderrollstiffness(), and target_wristyawstiffness().
isArmAllActive() [1/2]
bool guWhiteboard::HalArmTarget::isArmAllActive () inline
Are all of the arm's joints set to active.
Definition at line 665 of file HAL_ArmTarget.hpp.
References target_elbowroll_active(), target_elbowyaw_active(), target_hand_active(), target_shoulderpitch_active(), target_shoulderroll_active(), and target_wrist_active().
isArmAllActive() [2/2]
bool guWhiteboard::HalArmTarget::isArmAllActive () inline
Are all of the arm's joints set to active.
Definition at line 1421 of file HalArmTarget.hpp.
References target_elbowroll_active(), target_elbowyaw_active(), target_hand_active(), target_shoulderpitch_active(), target_shoulderroll_active(), and target_wrist_active().
isArmAllPassive() [1/2]
bool guWhiteboard::HalArmTarget::isArmAllPassive () inline
Are all of the arm's joints set to passive.
Definition at line 657 of file HAL_ArmTarget.hpp.
References target_elbowroll_active(), target_elbowyaw_active(), target_hand_active(), target_shoulderpitch_active(), target_shoulderroll_active(), and target_wrist_active().
isArmAllPassive() [2/2]
bool guWhiteboard::HalArmTarget::isArmAllPassive () inline
Are all of the arm's joints set to passive.
Definition at line 1413 of file HalArmTarget.hpp.
References target_elbowroll_active(), target_elbowyaw_active(), target_hand_active(), target_shoulderpitch_active(), target_shoulderroll_active(), and target_wrist_active().
isArmPassive() [1/2]
bool guWhiteboard::HalArmTarget::isArmPassive () inline
Are any of the arm's joints set to passive.
Definition at line 649 of file HAL_ArmTarget.hpp.
References target_elbowroll_active(), target_elbowyaw_active(), target_hand_active(), target_shoulderpitch_active(), target_shoulderroll_active(), and target_wrist_active().
isArmPassive() [2/2]
bool guWhiteboard::HalArmTarget::isArmPassive () inline
Are any of the arm's joints set to passive.
Definition at line 1405 of file HalArmTarget.hpp.
References target_elbowroll_active(), target_elbowyaw_active(), target_hand_active(), target_shoulderpitch_active(), target_shoulderroll_active(), and target_wrist_active().
isAtGoal() [1/2]
void guWhiteboard::HalArmTarget::isAtGoal (bool goalReached) inline
Arm at Goal Setter Clients/Machines should not use this method.
Arm arrived at goal pose. Only set in the status message by naoqiinterface when the arm has reached the goal pose.
Parameters
goalReached the arm has reached the goal (true/false)
Definition at line 256 of file HAL_ArmTarget.hpp.
References set_target_arm_at_goal().
isAtGoal() [2/2]
void guWhiteboard::HalArmTarget::isAtGoal (bool goalReached) inline
Arm at Goal Setter Clients/Machines should not use this method.
Arm arrived at goal pose. Only set in the status message by naoqiinterface when the arm has reached the goal pose.
Parameters
goalReached the arm has reached the goal (true/false)
Definition at line 1012 of file HalArmTarget.hpp.
References set_target_arm_at_goal().
mirrorArm() [1/2]
void guWhiteboard::HalArmTarget::mirrorArm (const HalArmTarget & other) inline
Convenience function to mirror arm settings about the XZ plane from one HalArmTarget object to another.
Parameters
other HalArmTarget object to be mirrored.
Definition at line 372 of file HAL_ArmTarget.hpp.
References set_target_elbowroll(), set_target_elbowroll_active(), set_target_elbowrollstiffness(), set_target_elbowyaw(), set_target_elbowyaw_active(), set_target_elbowyawstiffness(), set_target_hand(), set_target_hand_active(), set_target_handstiffness(), set_target_movement_time(), set_target_pliability(), set_target_shoulderpitch(), set_target_shoulderpitch_active(), set_target_shoulderpitchstiffness(), set_target_shoulderroll(), set_target_shoulderroll_active(), set_target_shoulderrollstiffness(), set_target_wrist_active(), set_target_wristyaw(), set_target_wristyawstiffness(), target_elbowroll(), target_elbowroll_active(), target_elbowrollstiffness(), target_elbowyaw(), target_elbowyaw_active(), target_elbowyawstiffness(), target_hand(), target_hand_active(), target_handstiffness(), target_movement_time(), target_pliability(), target_shoulderpitch(), target_shoulderpitch_active(), target_shoulderpitchstiffness(), target_shoulderroll(), target_shoulderroll_active(), target_shoulderrollstiffness(), target_wrist_active(), target_wristyaw(), and target_wristyawstiffness().
mirrorArm() [2/2]
void guWhiteboard::HalArmTarget::mirrorArm (const HalArmTarget & other) inline
Convenience function to mirror arm settings about the XZ plane from one HalArmTarget object to another.
Parameters
other HalArmTarget object to be mirrored.
Definition at line 1128 of file HalArmTarget.hpp.
References set_target_elbowroll(), set_target_elbowroll_active(), set_target_elbowrollstiffness(), set_target_elbowyaw(), set_target_elbowyaw_active(), set_target_elbowyawstiffness(), set_target_hand(), set_target_hand_active(), set_target_handstiffness(), set_target_movement_time(), set_target_pliability(), set_target_shoulderpitch(), set_target_shoulderpitch_active(), set_target_shoulderpitchstiffness(), set_target_shoulderroll(), set_target_shoulderroll_active(), set_target_shoulderrollstiffness(), set_target_wrist_active(), set_target_wristyaw(), and set_target_wristyawstiffness().
mirrorPose() [1/2]
void guWhiteboard::HalArmTarget::mirrorPose (const HalArmTarget & other) inline
Convenience function to mirror pose settings about the XZ plane from one HalArmTarget object to another.
Parameters
other HalArmTarget object whose pose settings are to be mirrored.
Definition at line 419 of file HAL_ArmTarget.hpp.
References set_target_elbowroll(), set_target_elbowyaw(), set_target_hand(), set_target_shoulderpitch(), set_target_shoulderroll(), set_target_wristyaw(), target_elbowroll(), target_elbowyaw(), target_hand(), target_shoulderpitch(), target_shoulderroll(), and target_wristyaw().
mirrorPose() [2/2]
void guWhiteboard::HalArmTarget::mirrorPose (const HalArmTarget & other) inline
Convenience function to mirror pose settings about the XZ plane from one HalArmTarget object to another.
Parameters
other HalArmTarget object whose pose settings are to be mirrored.
Definition at line 1175 of file HalArmTarget.hpp.
References set_target_elbowroll(), set_target_elbowyaw(), set_target_hand(), set_target_shoulderpitch(), set_target_shoulderroll(), and set_target_wristyaw().
operator!=() [1/2]
bool guWhiteboard::HalArmTarget::operator!= (const HalArmTarget & t_other) const inline
Definition at line 182 of file HalArmTarget.hpp.
operator!=() [2/2]
bool guWhiteboard::HalArmTarget::operator!= (const wb_hal_arm_target & t_other) const inline
Definition at line 192 of file HalArmTarget.hpp.
operator=() [1/2]
HalArmTarget & guWhiteboard::HalArmTarget::operator= (const HalArmTarget & t_other) inline
Copy Assignment Operator.
Definition at line 142 of file HalArmTarget.hpp.
operator=() [2/2]
HalArmTarget & guWhiteboard::HalArmTarget::operator= (const struct wb_hal_arm_target & t_other) inline
Copy Assignment Operator.
Definition at line 150 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_arm, wb_hal_arm_target::target_arm_at_goal, wb_hal_arm_target::target_arm_stop, wb_hal_arm_target::target_elbowroll, wb_hal_arm_target::target_elbowroll_active, wb_hal_arm_target::target_elbowrollstiffness, wb_hal_arm_target::target_elbowyaw, wb_hal_arm_target::target_elbowyaw_active, wb_hal_arm_target::target_elbowyawstiffness, wb_hal_arm_target::target_hand, wb_hal_arm_target::target_hand_active, wb_hal_arm_target::target_handstiffness, wb_hal_arm_target::target_movement_time, wb_hal_arm_target::target_pliability, wb_hal_arm_target::target_shoulderpitch, wb_hal_arm_target::target_shoulderpitch_active, wb_hal_arm_target::target_shoulderpitchstiffness, wb_hal_arm_target::target_shoulderroll, wb_hal_arm_target::target_shoulderroll_active, wb_hal_arm_target::target_shoulderrollstiffness, wb_hal_arm_target::target_wrist_active, wb_hal_arm_target::target_wristyaw, and wb_hal_arm_target::target_wristyawstiffness.
operator==() [1/2]
bool guWhiteboard::HalArmTarget::operator== (const HalArmTarget & t_other) const inline
Definition at line 155 of file HalArmTarget.hpp.
References target_arm(), target_arm_at_goal(), target_arm_stop(), target_elbowroll(), target_elbowroll_active(), target_elbowrollstiffness(), target_elbowyaw(), target_elbowyaw_active(), target_elbowyawstiffness(), target_hand(), target_hand_active(), target_handstiffness(), target_movement_time(), target_pliability(), target_shoulderpitch(), target_shoulderpitch_active(), target_shoulderpitchstiffness(), target_shoulderroll(), target_shoulderroll_active(), target_shoulderrollstiffness(), target_wrist_active(), target_wristyaw(), and target_wristyawstiffness().
operator==() [2/2]
bool guWhiteboard::HalArmTarget::operator== (const wb_hal_arm_target & t_other) const inline
Definition at line 187 of file HalArmTarget.hpp.
References HalArmTarget().
ready() [1/2]
void guWhiteboard::HalArmTarget::ready () inline
Set arm to ready state (Default) The arm will act on motion commands.
Definition at line 241 of file HAL_ArmTarget.hpp.
References set_target_arm_stop().
ready() [2/2]
void guWhiteboard::HalArmTarget::ready () inline
Set arm to ready state (Default) The arm will act on motion commands.
Definition at line 997 of file HalArmTarget.hpp.
References set_target_arm_stop().
set_elbowroll_DEG() [1/2]
void guWhiteboard::HalArmTarget::set_elbowroll_DEG (float setting) inline
Definition at line 679 of file HAL_ArmTarget.hpp.
References set_target_elbowroll().
Referenced by setPose_Deg().
set_elbowroll_DEG() [2/2]
void guWhiteboard::HalArmTarget::set_elbowroll_DEG (float setting) inline
Definition at line 1435 of file HalArmTarget.hpp.
References set_target_elbowroll().
set_elbowroll_RAD() [1/2]
void guWhiteboard::HalArmTarget::set_elbowroll_RAD (float setting) inline
Definition at line 700 of file HAL_ArmTarget.hpp.
References set_target_elbowroll().
Referenced by setPose_Rad().
set_elbowroll_RAD() [2/2]
void guWhiteboard::HalArmTarget::set_elbowroll_RAD (float setting) inline
Definition at line 1456 of file HalArmTarget.hpp.
References set_target_elbowroll().
set_elbowrollstiffness() [1/2]
void guWhiteboard::HalArmTarget::set_elbowrollstiffness (float setting) inline
Definition at line 726 of file HAL_ArmTarget.hpp.
References set_target_elbowrollstiffness().
Referenced by HalArmTarget(), setArmStiffness(), setArmStiffnessMax(), setArmStiffnessNormal(), and setArmStiffnessOff().
set_elbowrollstiffness() [2/2]
void guWhiteboard::HalArmTarget::set_elbowrollstiffness (float setting) inline
Definition at line 1482 of file HalArmTarget.hpp.
References set_target_elbowrollstiffness().
set_elbowyaw_DEG() [1/2]
void guWhiteboard::HalArmTarget::set_elbowyaw_DEG (float setting) inline
Definition at line 683 of file HAL_ArmTarget.hpp.
References set_target_elbowyaw().
Referenced by setPose_Deg().
set_elbowyaw_DEG() [2/2]
void guWhiteboard::HalArmTarget::set_elbowyaw_DEG (float setting) inline
Definition at line 1439 of file HalArmTarget.hpp.
References set_target_elbowyaw().
set_elbowyaw_RAD() [1/2]
void guWhiteboard::HalArmTarget::set_elbowyaw_RAD (float setting) inline
Definition at line 704 of file HAL_ArmTarget.hpp.
References set_target_elbowyaw().
Referenced by setPose_Rad().
set_elbowyaw_RAD() [2/2]
void guWhiteboard::HalArmTarget::set_elbowyaw_RAD (float setting) inline
Definition at line 1460 of file HalArmTarget.hpp.
References set_target_elbowyaw().
set_elbowyawstiffness() [1/2]
void guWhiteboard::HalArmTarget::set_elbowyawstiffness (float setting) inline
Definition at line 730 of file HAL_ArmTarget.hpp.
References set_target_elbowyawstiffness().
Referenced by HalArmTarget(), setArmStiffness(), setArmStiffnessMax(), setArmStiffnessNormal(), and setArmStiffnessOff().
set_elbowyawstiffness() [2/2]
void guWhiteboard::HalArmTarget::set_elbowyawstiffness (float setting) inline
Definition at line 1486 of file HalArmTarget.hpp.
References set_target_elbowyawstiffness().
set_hand() [1/2]
void guWhiteboard::HalArmTarget::set_hand (float setting) inline
Hand Movement Setter.
Definition at line 713 of file HAL_ArmTarget.hpp.
References set_target_hand().
Referenced by setPose_Deg(), and setPose_Rad().
set_hand() [2/2]
void guWhiteboard::HalArmTarget::set_hand (float setting) inline
Hand Movement Setter.
Definition at line 1469 of file HalArmTarget.hpp.
References set_target_hand().
set_handstiffness() [1/2]
void guWhiteboard::HalArmTarget::set_handstiffness (float setting) inline
Definition at line 738 of file HAL_ArmTarget.hpp.
References set_target_handstiffness().
Referenced by HalArmTarget(), setArmStiffness(), setArmStiffnessMax(), setArmStiffnessNormal(), and setArmStiffnessOff().
set_handstiffness() [2/2]
void guWhiteboard::HalArmTarget::set_handstiffness (float setting) inline
Definition at line 1494 of file HalArmTarget.hpp.
References set_target_handstiffness().
set_shoulderpitch_DEG() [1/2]
void guWhiteboard::HalArmTarget::set_shoulderpitch_DEG (float setting) inline
Movement Setters (Degrees)
Definition at line 671 of file HAL_ArmTarget.hpp.
References set_target_shoulderpitch().
Referenced by setPose_Deg().
set_shoulderpitch_DEG() [2/2]
void guWhiteboard::HalArmTarget::set_shoulderpitch_DEG (float setting) inline
Movement Setters (Degrees)
Definition at line 1427 of file HalArmTarget.hpp.
References set_target_shoulderpitch().
set_shoulderpitch_RAD() [1/2]
void guWhiteboard::HalArmTarget::set_shoulderpitch_RAD (float setting) inline
Movement Setters (Radians)
Definition at line 692 of file HAL_ArmTarget.hpp.
References set_target_shoulderpitch().
Referenced by setPose_Rad().
set_shoulderpitch_RAD() [2/2]
void guWhiteboard::HalArmTarget::set_shoulderpitch_RAD (float setting) inline
Movement Setters (Radians)
Definition at line 1448 of file HalArmTarget.hpp.
References set_target_shoulderpitch().
set_shoulderpitchstiffness() [1/2]
void guWhiteboard::HalArmTarget::set_shoulderpitchstiffness (float setting) inline
Stiffness Setters.
Definition at line 718 of file HAL_ArmTarget.hpp.
References set_target_shoulderpitchstiffness().
Referenced by HalArmTarget(), setArmStiffness(), setArmStiffnessMax(), setArmStiffnessNormal(), and setArmStiffnessOff().
set_shoulderpitchstiffness() [2/2]
void guWhiteboard::HalArmTarget::set_shoulderpitchstiffness (float setting) inline
Stiffness Setters.
Definition at line 1474 of file HalArmTarget.hpp.
References set_target_shoulderpitchstiffness().
set_shoulderroll_DEG() [1/2]
void guWhiteboard::HalArmTarget::set_shoulderroll_DEG (float setting) inline
Definition at line 675 of file HAL_ArmTarget.hpp.
References set_target_shoulderroll().
Referenced by setPose_Deg().
set_shoulderroll_DEG() [2/2]
void guWhiteboard::HalArmTarget::set_shoulderroll_DEG (float setting) inline
Definition at line 1431 of file HalArmTarget.hpp.
References set_target_shoulderroll().
set_shoulderroll_RAD() [1/2]
void guWhiteboard::HalArmTarget::set_shoulderroll_RAD (float setting) inline
Definition at line 696 of file HAL_ArmTarget.hpp.
References set_target_shoulderroll().
Referenced by setPose_Rad().
set_shoulderroll_RAD() [2/2]
void guWhiteboard::HalArmTarget::set_shoulderroll_RAD (float setting) inline
Definition at line 1452 of file HalArmTarget.hpp.
References set_target_shoulderroll().
set_shoulderrollstiffness() [1/2]
void guWhiteboard::HalArmTarget::set_shoulderrollstiffness (float setting) inline
Definition at line 722 of file HAL_ArmTarget.hpp.
References set_target_shoulderrollstiffness().
Referenced by HalArmTarget(), setArmStiffness(), setArmStiffnessMax(), setArmStiffnessNormal(), and setArmStiffnessOff().
set_shoulderrollstiffness() [2/2]
void guWhiteboard::HalArmTarget::set_shoulderrollstiffness (float setting) inline
Definition at line 1478 of file HalArmTarget.hpp.
References set_target_shoulderrollstiffness().
set_target_arm()
void guWhiteboard::HalArmTarget::set_target_arm (const uint8_t & t_newValue) inline
Definition at line 297 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_arm.
Referenced by from_string(), and tieToArm().
set_target_arm_at_goal()
void guWhiteboard::HalArmTarget::set_target_arm_at_goal (const unsigned int & t_newValue) inline
Definition at line 487 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_arm_at_goal.
Referenced by from_string(), and isAtGoal().
set_target_arm_stop()
void guWhiteboard::HalArmTarget::set_target_arm_stop (const unsigned int & t_newValue) inline
Definition at line 497 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_arm_stop.
Referenced by HalArmTarget(), from_string(), ready(), and stop().
set_target_elbowroll()
void guWhiteboard::HalArmTarget::set_target_elbowroll (const int16_t & t_newValue) inline
Definition at line 252 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_elbowroll.
Referenced by copyPose(), from_string(), mirrorArm(), mirrorPose(), set_elbowroll_DEG(), and set_elbowroll_RAD().
set_target_elbowroll_active()
void guWhiteboard::HalArmTarget::set_target_elbowroll_active (const unsigned int & t_newValue) inline
Definition at line 447 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_elbowroll_active.
Referenced by from_string(), mirrorArm(), setArmActive(), setArmPassive(), and setArmPliability().
set_target_elbowrollstiffness()
void guWhiteboard::HalArmTarget::set_target_elbowrollstiffness (const uint8_t & t_newValue) inline
Definition at line 357 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_elbowrollstiffness.
Referenced by copyStiffness(), from_string(), mirrorArm(), and set_elbowrollstiffness().
set_target_elbowyaw()
void guWhiteboard::HalArmTarget::set_target_elbowyaw (const int16_t & t_newValue) inline
Definition at line 267 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_elbowyaw.
Referenced by copyPose(), from_string(), mirrorArm(), mirrorPose(), set_elbowyaw_DEG(), and set_elbowyaw_RAD().
set_target_elbowyaw_active()
void guWhiteboard::HalArmTarget::set_target_elbowyaw_active (const unsigned int & t_newValue) inline
Definition at line 457 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_elbowyaw_active.
Referenced by from_string(), mirrorArm(), setArmActive(), setArmPassive(), and setArmPliability().
set_target_elbowyawstiffness()
void guWhiteboard::HalArmTarget::set_target_elbowyawstiffness (const uint8_t & t_newValue) inline
Definition at line 372 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_elbowyawstiffness.
Referenced by copyStiffness(), from_string(), mirrorArm(), and set_elbowyawstiffness().
set_target_hand()
void guWhiteboard::HalArmTarget::set_target_hand (const uint8_t & t_newValue) inline
Definition at line 312 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_hand.
Referenced by copyPose(), from_string(), mirrorArm(), mirrorPose(), and set_hand().
set_target_hand_active()
void guWhiteboard::HalArmTarget::set_target_hand_active (const unsigned int & t_newValue) inline
Definition at line 477 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_hand_active.
Referenced by from_string(), mirrorArm(), setArmActive(), setArmPassive(), and setArmPliability().
set_target_handstiffness()
void guWhiteboard::HalArmTarget::set_target_handstiffness (const uint8_t & t_newValue) inline
Definition at line 402 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_handstiffness.
Referenced by copyStiffness(), from_string(), mirrorArm(), and set_handstiffness().
set_target_movement_time()
void guWhiteboard::HalArmTarget::set_target_movement_time (const int32_t & t_newValue) inline
Definition at line 207 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_movement_time.
Referenced by HalArmTarget(), from_string(), goToWithTime_Deg(), goToWithTime_Rad(), and mirrorArm().
set_target_pliability()
void guWhiteboard::HalArmTarget::set_target_pliability (const uint8_t & t_newValue) inline
Definition at line 417 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_pliability.
Referenced by HalArmTarget(), from_string(), and mirrorArm().
set_target_shoulderpitch()
void guWhiteboard::HalArmTarget::set_target_shoulderpitch (const int16_t & t_newValue) inline
Definition at line 222 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_shoulderpitch.
Referenced by copyPose(), from_string(), mirrorArm(), mirrorPose(), set_shoulderpitch_DEG(), and set_shoulderpitch_RAD().
set_target_shoulderpitch_active()
void guWhiteboard::HalArmTarget::set_target_shoulderpitch_active (const unsigned int & t_newValue) inline
Definition at line 427 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_shoulderpitch_active.
Referenced by from_string(), mirrorArm(), setArmActive(), setArmPassive(), and setArmPliability().
set_target_shoulderpitchstiffness()
void guWhiteboard::HalArmTarget::set_target_shoulderpitchstiffness (const uint8_t & t_newValue) inline
Definition at line 327 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_shoulderpitchstiffness.
Referenced by copyStiffness(), from_string(), mirrorArm(), and set_shoulderpitchstiffness().
set_target_shoulderroll()
void guWhiteboard::HalArmTarget::set_target_shoulderroll (const int16_t & t_newValue) inline
Definition at line 237 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_shoulderroll.
Referenced by copyPose(), from_string(), mirrorArm(), mirrorPose(), set_shoulderroll_DEG(), and set_shoulderroll_RAD().
set_target_shoulderroll_active()
void guWhiteboard::HalArmTarget::set_target_shoulderroll_active (const unsigned int & t_newValue) inline
Definition at line 437 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_shoulderroll_active.
Referenced by from_string(), mirrorArm(), setArmActive(), setArmPassive(), and setArmPliability().
set_target_shoulderrollstiffness()
void guWhiteboard::HalArmTarget::set_target_shoulderrollstiffness (const uint8_t & t_newValue) inline
Definition at line 342 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_shoulderrollstiffness.
Referenced by copyStiffness(), from_string(), mirrorArm(), and set_shoulderrollstiffness().
set_target_wrist_active()
void guWhiteboard::HalArmTarget::set_target_wrist_active (const unsigned int & t_newValue) inline
Definition at line 467 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_wrist_active.
Referenced by from_string(), mirrorArm(), setArmActive(), setArmPassive(), and setArmPliability().
set_target_wristyaw()
void guWhiteboard::HalArmTarget::set_target_wristyaw (const int16_t & t_newValue) inline
Definition at line 282 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_wristyaw.
Referenced by copyPose(), from_string(), mirrorArm(), mirrorPose(), set_wristyaw_DEG(), and set_wristyaw_RAD().
set_target_wristyawstiffness()
void guWhiteboard::HalArmTarget::set_target_wristyawstiffness (const uint8_t & t_newValue) inline
Definition at line 387 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_wristyawstiffness.
Referenced by copyStiffness(), from_string(), mirrorArm(), and set_wristyawstiffness().
set_wristyaw_DEG() [1/2]
void guWhiteboard::HalArmTarget::set_wristyaw_DEG (float setting) inline
Definition at line 687 of file HAL_ArmTarget.hpp.
References set_target_wristyaw().
Referenced by setPose_Deg().
set_wristyaw_DEG() [2/2]
void guWhiteboard::HalArmTarget::set_wristyaw_DEG (float setting) inline
Definition at line 1443 of file HalArmTarget.hpp.
References set_target_wristyaw().
set_wristyaw_RAD() [1/2]
void guWhiteboard::HalArmTarget::set_wristyaw_RAD (float setting) inline
Definition at line 708 of file HAL_ArmTarget.hpp.
References set_target_wristyaw().
Referenced by setPose_Rad().
set_wristyaw_RAD() [2/2]
void guWhiteboard::HalArmTarget::set_wristyaw_RAD (float setting) inline
Definition at line 1464 of file HalArmTarget.hpp.
References set_target_wristyaw().
set_wristyawstiffness() [1/2]
void guWhiteboard::HalArmTarget::set_wristyawstiffness (float setting) inline
Definition at line 734 of file HAL_ArmTarget.hpp.
References set_target_wristyawstiffness().
Referenced by HalArmTarget(), setArmStiffness(), setArmStiffnessMax(), setArmStiffnessNormal(), and setArmStiffnessOff().
set_wristyawstiffness() [2/2]
void guWhiteboard::HalArmTarget::set_wristyawstiffness (float setting) inline
Definition at line 1490 of file HalArmTarget.hpp.
References set_target_wristyawstiffness().
setArmActive() [1/2]
void guWhiteboard::HalArmTarget::setArmActive () inline
Set arm to be Active (DEDAULT DCM state) The arm is active and manual movements will be resisted, be careful when the stiffness is set high.
Once the applied force is removed, the arm will return to its previous location. Be careful using this with high stiffness settings (which vary per joint), as the gears will be stripped.
NOTE: This is the default DCM mode.
Definition at line 597 of file HAL_ArmTarget.hpp.
References set_target_elbowroll_active(), set_target_elbowyaw_active(), set_target_hand_active(), set_target_shoulderpitch_active(), set_target_shoulderroll_active(), and set_target_wrist_active().
setArmActive() [2/2]
void guWhiteboard::HalArmTarget::setArmActive () inline
Set arm to be Active (DEDAULT DCM state) The arm is active and manual movements will be resisted, be careful when the stiffness is set high.
Once the applied force is removed, the arm will return to its previous location. Be careful using this with high stiffness settings (which vary per joint), as the gears will be stripped.
NOTE: This is the default DCM mode.
Definition at line 1353 of file HalArmTarget.hpp.
References set_target_elbowroll_active(), set_target_elbowyaw_active(), set_target_hand_active(), set_target_shoulderpitch_active(), set_target_shoulderroll_active(), and set_target_wrist_active().
setArmPassive() [1/2]
void guWhiteboard::HalArmTarget::setArmPassive () inline
Set arm to be Passive Manually moving the arm causes the arm to remain in the new position.
Be careful using this with high stiffness and pliability settings (which vary per joint).
NOTE: This is achieved by telling the DCM to move the arm to the displaced position each DCM cyle. Thus the arm tracks the applied force. The 'pliability' setting reduces the update rate, thus making the arm stiffer. At higher pliability settings, the movement will become noticably stepped.
Definition at line 618 of file HAL_ArmTarget.hpp.
References set_target_elbowroll_active(), set_target_elbowyaw_active(), set_target_hand_active(), set_target_shoulderpitch_active(), set_target_shoulderroll_active(), and set_target_wrist_active().
setArmPassive() [2/2]
void guWhiteboard::HalArmTarget::setArmPassive () inline
Set arm to be Passive Manually moving the arm causes the arm to remain in the new position.
Be careful using this with high stiffness and pliability settings (which vary per joint).
NOTE: This is achieved by telling the DCM to move the arm to the displaced position each DCM cyle. Thus the arm tracks the applied force. The 'pliability' setting reduces the update rate, thus making the arm stiffer. At higher pliability settings, the movement will become noticably stepped.
Definition at line 1374 of file HalArmTarget.hpp.
References set_target_elbowroll_active(), set_target_elbowyaw_active(), set_target_hand_active(), set_target_shoulderpitch_active(), set_target_shoulderroll_active(), and set_target_wrist_active().
setArmPliability() [1/2]
void guWhiteboard::HalArmTarget::setArmPliability (bool shoulderpitch, bool shoulderroll, bool elbowroll, bool elbowyaw, bool wristyaw, bool hand) inline
Individually set the active/passive state of each joint.
See Arm_Active() and Arm_Passive() methods for an explanation of the Active/Passive effect.
Definition at line 634 of file HAL_ArmTarget.hpp.
References wb_hal_armtarget::elbowroll, wb_hal_armtarget::elbowyaw, wb_hal_armtarget::hand, set_target_elbowroll_active(), set_target_elbowyaw_active(), set_target_hand_active(), set_target_shoulderpitch_active(), set_target_shoulderroll_active(), set_target_wrist_active(), wb_hal_armtarget::shoulderpitch, wb_hal_armtarget::shoulderroll, and wb_hal_armtarget::wristyaw.
Referenced by HalArmTarget().
setArmPliability() [2/2]
void guWhiteboard::HalArmTarget::setArmPliability (bool shoulderpitch, bool shoulderroll, bool elbowroll, bool elbowyaw, bool wristyaw, bool hand) inline
Individually set the active/passive state of each joint.
See Arm_Active() and Arm_Passive() methods for an explanation of the Active/Passive effect.
Definition at line 1390 of file HalArmTarget.hpp.
References wb_hal_armtarget::elbowroll, wb_hal_armtarget::elbowyaw, wb_hal_armtarget::hand, set_target_elbowroll_active(), set_target_elbowyaw_active(), set_target_hand_active(), set_target_shoulderpitch_active(), set_target_shoulderroll_active(), set_target_wrist_active(), wb_hal_armtarget::shoulderpitch, wb_hal_armtarget::shoulderroll, and wb_hal_armtarget::wristyaw.
setArmStiffness() [1/2]
void guWhiteboard::HalArmTarget::setArmStiffness (float stiffness) inline
Convenience function to set uniform stiffness on all arm joints to a custom value.
Parameters
stiffness float Stiffness setting between 0.0 and 1.0 (float).
Definition at line 517 of file HAL_ArmTarget.hpp.
References set_elbowrollstiffness(), set_elbowyawstiffness(), set_handstiffness(), set_shoulderpitchstiffness(), set_shoulderrollstiffness(), and set_wristyawstiffness().
setArmStiffness() [2/2]
void guWhiteboard::HalArmTarget::setArmStiffness (float stiffness) inline
Convenience function to set uniform stiffness on all arm joints to a custom value.
Parameters
stiffness float Stiffness setting between 0.0 and 1.0 (float).
Definition at line 1273 of file HalArmTarget.hpp.
References set_elbowrollstiffness(), set_elbowyawstiffness(), set_handstiffness(), set_shoulderpitchstiffness(), set_shoulderrollstiffness(), and set_wristyawstiffness().
setArmStiffnessMax() [1/2]
void guWhiteboard::HalArmTarget::setArmStiffnessMax () inline
Convenience function to set the stiffness of all the arm's joints to the maximum (1.0f).
Definition at line 484 of file HAL_ArmTarget.hpp.
References set_elbowrollstiffness(), set_elbowyawstiffness(), set_handstiffness(), set_shoulderpitchstiffness(), set_shoulderrollstiffness(), and set_wristyawstiffness().
setArmStiffnessMax() [2/2]
void guWhiteboard::HalArmTarget::setArmStiffnessMax () inline
Convenience function to set the stiffness of all the arm's joints to the maximum (1.0f).
Definition at line 1240 of file HalArmTarget.hpp.
References set_elbowrollstiffness(), set_elbowyawstiffness(), set_handstiffness(), set_shoulderpitchstiffness(), set_shoulderrollstiffness(), and set_wristyawstiffness().
setArmStiffnessNormal() [1/2]
void guWhiteboard::HalArmTarget::setArmStiffnessNormal () inline
Convenience function to set the stiffness of all the arm's joints to what Aldebaran considers 'normal' (0.6f).
Definition at line 500 of file HAL_ArmTarget.hpp.
References set_elbowrollstiffness(), set_elbowyawstiffness(), set_handstiffness(), set_shoulderpitchstiffness(), set_shoulderrollstiffness(), and set_wristyawstiffness().
setArmStiffnessNormal() [2/2]
void guWhiteboard::HalArmTarget::setArmStiffnessNormal () inline
Convenience function to set the stiffness of all the arm's joints to what Aldebaran considers 'normal' (0.6f).
Definition at line 1256 of file HalArmTarget.hpp.
References set_elbowrollstiffness(), set_elbowyawstiffness(), set_handstiffness(), set_shoulderpitchstiffness(), set_shoulderrollstiffness(), and set_wristyawstiffness().
setArmStiffnessOff() [1/2]
void guWhiteboard::HalArmTarget::setArmStiffnessOff () inline
Convenience function to turn off stiffness in all the arm's joints (0.0f).
Definition at line 534 of file HAL_ArmTarget.hpp.
References set_elbowrollstiffness(), set_elbowyawstiffness(), set_handstiffness(), set_shoulderpitchstiffness(), set_shoulderrollstiffness(), and set_wristyawstiffness().
setArmStiffnessOff() [2/2]
void guWhiteboard::HalArmTarget::setArmStiffnessOff () inline
Convenience function to turn off stiffness in all the arm's joints (0.0f).
Definition at line 1290 of file HalArmTarget.hpp.
References set_elbowrollstiffness(), set_elbowyawstiffness(), set_handstiffness(), set_shoulderpitchstiffness(), set_shoulderrollstiffness(), and set_wristyawstiffness().
setPose_Deg() [1/2]
void guWhiteboard::HalArmTarget::setPose_Deg (float shoulderpitch, float shoulderroll, float elbowroll, float elbowyaw, float wristyaw, float hand) inline
Set Pose in degrees.
Parameters
shoulderpitch down to up
shoulderroll out to in
elbowroll straight to bent
elbowyaw rolled right to rolled left
wristyaw rolled right to rolled left
hand closed to open.
Definition at line 350 of file HAL_ArmTarget.hpp.
References wb_hal_armtarget::elbowroll, wb_hal_armtarget::elbowyaw, wb_hal_armtarget::hand, set_elbowroll_DEG(), set_elbowyaw_DEG(), set_hand(), set_shoulderpitch_DEG(), set_shoulderroll_DEG(), set_wristyaw_DEG(), wb_hal_armtarget::shoulderpitch, wb_hal_armtarget::shoulderroll, and wb_hal_armtarget::wristyaw.
Referenced by HalArmTarget(), and goToWithTime_Deg().
setPose_Deg() [2/2]
void guWhiteboard::HalArmTarget::setPose_Deg (float shoulderpitch, float shoulderroll, float elbowroll, float elbowyaw, float wristyaw, float hand) inline
Set Pose in degrees.
Parameters
shoulderpitch down to up
shoulderroll out to in
elbowroll straight to bent
elbowyaw rolled right to rolled left
wristyaw rolled right to rolled left
hand closed to open.
Definition at line 1106 of file HalArmTarget.hpp.
References wb_hal_armtarget::elbowroll, wb_hal_armtarget::elbowyaw, wb_hal_armtarget::hand, set_elbowroll_DEG(), set_elbowyaw_DEG(), set_hand(), set_shoulderpitch_DEG(), set_shoulderroll_DEG(), set_wristyaw_DEG(), wb_hal_armtarget::shoulderpitch, wb_hal_armtarget::shoulderroll, and wb_hal_armtarget::wristyaw.
setPose_Rad() [1/2]
void guWhiteboard::HalArmTarget::setPose_Rad (float shoulderpitch, float shoulderroll, float elbowroll, float elbowyaw, float wristyaw, float hand) inline
Set Pose in radians.
Parameters
shoulderpitch down to up
shoulderroll out to in
elbowroll straight to bent
elbowyaw rolled right to rolled left
wristyaw rolled right to rolled left
hand closed to open.
Definition at line 325 of file HAL_ArmTarget.hpp.
References wb_hal_armtarget::elbowroll, wb_hal_armtarget::elbowyaw, wb_hal_armtarget::hand, set_elbowroll_RAD(), set_elbowyaw_RAD(), set_hand(), set_shoulderpitch_RAD(), set_shoulderroll_RAD(), set_wristyaw_RAD(), wb_hal_armtarget::shoulderpitch, wb_hal_armtarget::shoulderroll, and wb_hal_armtarget::wristyaw.
Referenced by HalArmTarget(), and goToWithTime_Rad().
setPose_Rad() [2/2]
void guWhiteboard::HalArmTarget::setPose_Rad (float shoulderpitch, float shoulderroll, float elbowroll, float elbowyaw, float wristyaw, float hand) inline
Set Pose in radians.
Parameters
shoulderpitch down to up
shoulderroll out to in
elbowroll straight to bent
elbowyaw rolled right to rolled left
wristyaw rolled right to rolled left
hand closed to open.
Definition at line 1081 of file HalArmTarget.hpp.
References wb_hal_armtarget::elbowroll, wb_hal_armtarget::elbowyaw, wb_hal_armtarget::hand, set_elbowroll_RAD(), set_elbowyaw_RAD(), set_hand(), set_shoulderpitch_RAD(), set_shoulderroll_RAD(), set_wristyaw_RAD(), wb_hal_armtarget::shoulderpitch, wb_hal_armtarget::shoulderroll, and wb_hal_armtarget::wristyaw.
stop() [1/2]
void guWhiteboard::HalArmTarget::stop () inline
Command the arm to stop at its current location and not act on motion commands until ready() is called.
Definition at line 231 of file HAL_ArmTarget.hpp.
References set_target_arm_stop().
stop() [2/2]
void guWhiteboard::HalArmTarget::stop () inline
Command the arm to stop at its current location and not act on motion commands until ready() is called.
Definition at line 987 of file HalArmTarget.hpp.
References set_target_arm_stop().
target_arm() [1/2]
uint8_t & guWhiteboard::HalArmTarget::target_arm () inline
Definition at line 287 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_arm.
Referenced by description(), operator==(), and to_string().
target_arm() [2/2]
const uint8_t & guWhiteboard::HalArmTarget::target_arm () const inline
Definition at line 292 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_arm.
target_arm_at_goal()
unsigned int guWhiteboard::HalArmTarget::target_arm_at_goal () const inline
Definition at line 482 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_arm_at_goal.
Referenced by atGoal(), description(), operator==(), to_string(), and valueDescription().
target_arm_stop()
unsigned int guWhiteboard::HalArmTarget::target_arm_stop () const inline
Definition at line 492 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_arm_stop.
Referenced by description(), operator==(), to_string(), and valueDescription().
target_elbowroll() [1/2]
int16_t & guWhiteboard::HalArmTarget::target_elbowroll () inline
Definition at line 242 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_elbowroll.
Referenced by atTargetLocation(), copyPose(), description(), get_elbowroll_DEG(), get_elbowroll_RAD(), hasSameMirroredPose(), hasSamePose(), mirrorArm(), mirrorPose(), operator==(), to_string(), and valueDescription().
target_elbowroll() [2/2]
const int16_t & guWhiteboard::HalArmTarget::target_elbowroll () const inline
Definition at line 247 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_elbowroll.
target_elbowroll_active()
unsigned int guWhiteboard::HalArmTarget::target_elbowroll_active () const inline
Definition at line 442 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_elbowroll_active.
Referenced by description(), isArmAllActive(), isArmAllPassive(), isArmPassive(), mirrorArm(), operator==(), to_string(), and valueDescription().
target_elbowrollstiffness() [1/2]
uint8_t & guWhiteboard::HalArmTarget::target_elbowrollstiffness () inline
Definition at line 347 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_elbowrollstiffness.
Referenced by copyStiffness(), description(), get_elbowrollstiffness(), hasSameStiffness(), mirrorArm(), operator==(), to_string(), and valueDescription().
target_elbowrollstiffness() [2/2]
const uint8_t & guWhiteboard::HalArmTarget::target_elbowrollstiffness () const inline
Definition at line 352 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_elbowrollstiffness.
target_elbowyaw() [1/2]
int16_t & guWhiteboard::HalArmTarget::target_elbowyaw () inline
Definition at line 257 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_elbowyaw.
Referenced by atTargetLocation(), copyPose(), description(), get_elbowyaw_DEG(), get_elbowyaw_RAD(), hasSameMirroredPose(), hasSamePose(), mirrorArm(), mirrorPose(), operator==(), to_string(), and valueDescription().
target_elbowyaw() [2/2]
const int16_t & guWhiteboard::HalArmTarget::target_elbowyaw () const inline
Definition at line 262 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_elbowyaw.
target_elbowyaw_active()
unsigned int guWhiteboard::HalArmTarget::target_elbowyaw_active () const inline
Definition at line 452 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_elbowyaw_active.
Referenced by description(), isArmAllActive(), isArmAllPassive(), isArmPassive(), mirrorArm(), operator==(), to_string(), and valueDescription().
target_elbowyawstiffness() [1/2]
uint8_t & guWhiteboard::HalArmTarget::target_elbowyawstiffness () inline
Definition at line 362 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_elbowyawstiffness.
Referenced by copyStiffness(), description(), get_elbowyawstiffness(), hasSameStiffness(), mirrorArm(), operator==(), to_string(), and valueDescription().
target_elbowyawstiffness() [2/2]
const uint8_t & guWhiteboard::HalArmTarget::target_elbowyawstiffness () const inline
Definition at line 367 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_elbowyawstiffness.
target_hand() [1/2]
uint8_t & guWhiteboard::HalArmTarget::target_hand () inline
Definition at line 302 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_hand.
Referenced by copyPose(), description(), get_hand(), hasSameMirroredPose(), hasSamePose(), mirrorArm(), mirrorPose(), operator==(), to_string(), and valueDescription().
target_hand() [2/2]
const uint8_t & guWhiteboard::HalArmTarget::target_hand () const inline
Definition at line 307 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_hand.
target_hand_active()
unsigned int guWhiteboard::HalArmTarget::target_hand_active () const inline
Definition at line 472 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_hand_active.
Referenced by description(), isArmAllActive(), isArmAllPassive(), isArmPassive(), mirrorArm(), operator==(), to_string(), and valueDescription().
target_handstiffness() [1/2]
uint8_t & guWhiteboard::HalArmTarget::target_handstiffness () inline
Definition at line 392 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_handstiffness.
Referenced by copyStiffness(), description(), get_handstiffness(), hasSameStiffness(), mirrorArm(), operator==(), to_string(), and valueDescription().
target_handstiffness() [2/2]
const uint8_t & guWhiteboard::HalArmTarget::target_handstiffness () const inline
Definition at line 397 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_handstiffness.
target_movement_time() [1/2]
int32_t & guWhiteboard::HalArmTarget::target_movement_time () inline
Definition at line 197 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_movement_time.
Referenced by description(), mirrorArm(), operator==(), to_string(), and valueDescription().
target_movement_time() [2/2]
const int32_t & guWhiteboard::HalArmTarget::target_movement_time () const inline
Definition at line 202 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_movement_time.
target_pliability() [1/2]
uint8_t & guWhiteboard::HalArmTarget::target_pliability () inline
Definition at line 407 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_pliability.
Referenced by description(), mirrorArm(), operator==(), to_string(), and valueDescription().
target_pliability() [2/2]
const uint8_t & guWhiteboard::HalArmTarget::target_pliability () const inline
Definition at line 412 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_pliability.
target_shoulderpitch() [1/2]
int16_t & guWhiteboard::HalArmTarget::target_shoulderpitch () inline
Definition at line 212 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_shoulderpitch.
Referenced by atTargetLocation(), copyPose(), description(), get_shoulderpitch_DEG(), get_shoulderpitch_RAD(), hasSameMirroredPose(), hasSamePose(), mirrorArm(), mirrorPose(), operator==(), to_string(), and valueDescription().
target_shoulderpitch() [2/2]
const int16_t & guWhiteboard::HalArmTarget::target_shoulderpitch () const inline
Definition at line 217 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_shoulderpitch.
target_shoulderpitch_active()
unsigned int guWhiteboard::HalArmTarget::target_shoulderpitch_active () const inline
Definition at line 422 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_shoulderpitch_active.
Referenced by description(), isArmAllActive(), isArmAllPassive(), isArmPassive(), mirrorArm(), operator==(), to_string(), and valueDescription().
target_shoulderpitchstiffness() [1/2]
uint8_t & guWhiteboard::HalArmTarget::target_shoulderpitchstiffness () inline
Definition at line 317 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_shoulderpitchstiffness.
Referenced by copyStiffness(), description(), get_shoulderpitchstiffness(), hasSameStiffness(), mirrorArm(), operator==(), to_string(), and valueDescription().
target_shoulderpitchstiffness() [2/2]
const uint8_t & guWhiteboard::HalArmTarget::target_shoulderpitchstiffness () const inline
Definition at line 322 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_shoulderpitchstiffness.
target_shoulderroll() [1/2]
int16_t & guWhiteboard::HalArmTarget::target_shoulderroll () inline
Definition at line 227 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_shoulderroll.
Referenced by atTargetLocation(), copyPose(), description(), get_shoulderroll_DEG(), get_shoulderroll_RAD(), hasSameMirroredPose(), hasSamePose(), mirrorArm(), mirrorPose(), operator==(), to_string(), and valueDescription().
target_shoulderroll() [2/2]
const int16_t & guWhiteboard::HalArmTarget::target_shoulderroll () const inline
Definition at line 232 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_shoulderroll.
target_shoulderroll_active()
unsigned int guWhiteboard::HalArmTarget::target_shoulderroll_active () const inline
Definition at line 432 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_shoulderroll_active.
Referenced by description(), isArmAllActive(), isArmAllPassive(), isArmPassive(), mirrorArm(), operator==(), to_string(), and valueDescription().
target_shoulderrollstiffness() [1/2]
uint8_t & guWhiteboard::HalArmTarget::target_shoulderrollstiffness () inline
Definition at line 332 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_shoulderrollstiffness.
Referenced by copyStiffness(), description(), get_shoulderrollstiffness(), hasSameStiffness(), mirrorArm(), operator==(), to_string(), and valueDescription().
target_shoulderrollstiffness() [2/2]
const uint8_t & guWhiteboard::HalArmTarget::target_shoulderrollstiffness () const inline
Definition at line 337 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_shoulderrollstiffness.
target_wrist_active()
unsigned int guWhiteboard::HalArmTarget::target_wrist_active () const inline
Definition at line 462 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_wrist_active.
Referenced by description(), isArmAllActive(), isArmAllPassive(), isArmPassive(), mirrorArm(), operator==(), to_string(), and valueDescription().
target_wristyaw() [1/2]
int16_t & guWhiteboard::HalArmTarget::target_wristyaw () inline
Definition at line 272 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_wristyaw.
Referenced by copyPose(), description(), get_wristyaw_DEG(), get_wristyaw_RAD(), hasSameMirroredPose(), hasSamePose(), mirrorArm(), mirrorPose(), operator==(), to_string(), and valueDescription().
target_wristyaw() [2/2]
const int16_t & guWhiteboard::HalArmTarget::target_wristyaw () const inline
Definition at line 277 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_wristyaw.
target_wristyawstiffness() [1/2]
uint8_t & guWhiteboard::HalArmTarget::target_wristyawstiffness () inline
Definition at line 377 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_wristyawstiffness.
Referenced by copyStiffness(), description(), get_wristyawstiffness(), hasSameStiffness(), mirrorArm(), operator==(), to_string(), and valueDescription().
target_wristyawstiffness() [2/2]
const uint8_t & guWhiteboard::HalArmTarget::target_wristyawstiffness () const inline
Definition at line 382 of file HalArmTarget.hpp.
References wb_hal_arm_target::target_wristyawstiffness.
tieToArm() [1/2]
void guWhiteboard::HalArmTarget::tieToArm (uint8_t arm) inline
Specify which arm this instance manages.
Up to 256 arms are possible. Use prefedined macros LEFT_ARM and RIGHT_ARM for clarity.
Parameters
arm integer used to record which arm the object refers to.
Definition at line 168 of file HAL_ArmTarget.hpp.
References set_target_arm().
tieToArm() [2/2]
void guWhiteboard::HalArmTarget::tieToArm (uint8_t arm) inline
USE_WB_HAL_ARM_TARGET_C_CONVERSION WHITEBOARD_POSTER_STRING_CONVERSION.
Specify which arm this instance manages. Up to 256 arms are possible. Use prefedined macros LEFT_ARM and RIGHT_ARM for clarity.
Parameters
arm integer used to record which arm the object refers to.
Definition at line 924 of file HalArmTarget.hpp.
References set_target_arm().
to_string()
std::string guWhiteboard::HalArmTarget::to_string () inline
USE_WB_HAL_ARM_TARGET_C_CONVERSION
Definition at line 568 of file HalArmTarget.hpp.
References HAL_ARM_TARGET_TO_STRING_BUFFER_SIZE, target_arm(), target_arm_at_goal(), target_arm_stop(), target_elbowroll(), target_elbowroll_active(), target_elbowrollstiffness(), target_elbowyaw(), target_elbowyaw_active(), target_elbowyawstiffness(), target_hand(), target_hand_active(), target_handstiffness(), target_movement_time(), target_pliability(), target_shoulderpitch(), target_shoulderpitch_active(), target_shoulderpitchstiffness(), target_shoulderroll(), target_shoulderroll_active(), target_shoulderrollstiffness(), target_wrist_active(), target_wristyaw(), target_wristyawstiffness(), and wb_hal_arm_target_to_string().
valueDescription()
std::string guWhiteboard::HalArmTarget::valueDescription () inline
WHITEBOARD_POSTER_STRING_CONVERSION.
Description function which prints values only (Spreadsheet friendly)
Definition at line 880 of file HalArmTarget.hpp.
References HAL_ARM_TARGET_DESC_BUFFER_SIZE, target_arm_at_goal(), target_arm_stop(), target_elbowroll(), target_elbowroll_active(), target_elbowrollstiffness(), target_elbowyaw(), target_elbowyaw_active(), target_elbowyawstiffness(), target_hand(), target_hand_active(), target_handstiffness(), target_movement_time(), target_pliability(), target_shoulderpitch(), target_shoulderpitch_active(), target_shoulderpitchstiffness(), target_shoulderroll(), target_shoulderroll_active(), target_shoulderrollstiffness(), target_wrist_active(), target_wristyaw(), target_wristyawstiffness(), and wb_hal_arm_target_value_description().
The documentation for this class was generated from the following files:
typeClassDefs/HAL_ArmTarget.hpp
typeClassDefs/HalArmTarget.hpp