gusimplewhiteboard: guWhiteboard::LineSighting Class Reference
guWhiteboard::LineSighting Class Reference
Provides a C++ wrapper around wb_line_sighting.
#include <LineSighting.hpp>
Public Member Functions
LineSighting (struct wb_polar_coordinate t_leftPoint=wb_polar_coordinate(), struct wb_polar_coordinate t_rightPoint=wb_polar_coordinate(), enum LineSightingType t_sightingType=static_cast< enum LineSightingType >(0))
Create a new LineSighting.
LineSighting (const LineSighting &t_other)
Copy Constructor.
LineSighting (const struct wb_line_sighting &t_other)
Copy Constructor.
LineSighting & operator= (const LineSighting &t_other)
Copy Assignment Operator.
LineSighting & operator= (const struct wb_line_sighting &t_other)
Copy Assignment Operator.
bool operator== (const LineSighting &t_other) const
bool operator!= (const LineSighting &t_other) const
bool operator== (const wb_line_sighting &t_other) const
bool operator!= (const wb_line_sighting &t_other) const
PolarCoordinate & leftPoint ()
const PolarCoordinate & leftPoint () const
void set_leftPoint (const PolarCoordinate &t_newValue)
PolarCoordinate & rightPoint ()
const PolarCoordinate & rightPoint () const
void set_rightPoint (const PolarCoordinate &t_newValue)
enum LineSightingType & sightingType ()
enum LineSightingType & sightingType () const
void set_sightingType (const enum LineSightingType &t_newValue)
LineSighting (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
SimpleLine simpleLine ()
WHITEBOARD_POSTER_STRING_CONVERSION.
Additional Inherited Members
Public Attributes inherited from wb_line_sighting
struct wb_polar_coordinate leftPoint
The left/bottom point of the line.
struct wb_polar_coordinate rightPoint
The right/top point of the line.
enum LineSightingType sightingType
The type of sighting.
Detailed Description
Provides a C++ wrapper around wb_line_sighting.
Definition at line 86 of file LineSighting.hpp.
Constructor & Destructor Documentation
LineSighting() [1/4]
guWhiteboard::LineSighting::LineSighting (struct wb_polar_coordinate t_leftPoint = wb_polar_coordinate(), struct wb_polar_coordinate t_rightPoint = wb_polar_coordinate(), enum LineSightingType t_sightingType = static_cast<enum LineSightingType>(0)) inline
Create a new LineSighting.
Definition at line 104 of file LineSighting.hpp.
Referenced by operator==().
LineSighting() [2/4]
guWhiteboard::LineSighting::LineSighting (const LineSighting & t_other) inline
Copy Constructor.
Definition at line 111 of file LineSighting.hpp.
References leftPoint(), rightPoint(), and sightingType().
LineSighting() [3/4]
guWhiteboard::LineSighting::LineSighting (const struct wb_line_sighting & t_other) inline
Copy Constructor.
Definition at line 118 of file LineSighting.hpp.
References wb_line_sighting::leftPoint, wb_line_sighting::rightPoint, and wb_line_sighting::sightingType.
LineSighting() [4/4]
guWhiteboard::LineSighting::LineSighting (const std::string & t_str) inline
String Constructor.
Definition at line 209 of file LineSighting.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::LineSighting::description () inline
USE_WB_LINE_SIGHTING_C_CONVERSION
Definition at line 214 of file LineSighting.hpp.
References guWhiteboard::PolarCoordinate::description(), FieldLineSightingType, HorizonLineSightingType, leftPoint(), LINE_SIGHTING_DESC_BUFFER_SIZE, rightPoint(), sightingType(), and wb_line_sighting_description().
from_string()
void guWhiteboard::LineSighting::from_string (const std::string & t_str) inline
USE_WB_LINE_SIGHTING_C_CONVERSION
Definition at line 274 of file LineSighting.hpp.
References FieldLineSightingType, guWhiteboard::PolarCoordinate::from_string(), HorizonLineSightingType, LINE_SIGHTING_DESC_BUFFER_SIZE, set_leftPoint(), set_rightPoint(), and set_sightingType().
Referenced by LineSighting(), and guWhiteboard::MachineFilteredLines::from_string().
leftPoint() [1/2]
PolarCoordinate & guWhiteboard::LineSighting::leftPoint () inline
Definition at line 160 of file LineSighting.hpp.
References wb_line_sighting::leftPoint.
Referenced by LineSighting(), description(), operator=(), operator==(), simpleLine(), and to_string().
leftPoint() [2/2]
const PolarCoordinate & guWhiteboard::LineSighting::leftPoint () const inline
Definition at line 165 of file LineSighting.hpp.
References wb_line_sighting::leftPoint.
operator!=() [1/2]
bool guWhiteboard::LineSighting::operator!= (const LineSighting & t_other) const inline
Definition at line 145 of file LineSighting.hpp.
operator!=() [2/2]
bool guWhiteboard::LineSighting::operator!= (const wb_line_sighting & t_other) const inline
Definition at line 155 of file LineSighting.hpp.
operator=() [1/2]
LineSighting & guWhiteboard::LineSighting::operator= (const LineSighting & t_other) inline
Copy Assignment Operator.
Definition at line 125 of file LineSighting.hpp.
References leftPoint(), rightPoint(), and sightingType().
operator=() [2/2]
LineSighting & guWhiteboard::LineSighting::operator= (const struct wb_line_sighting & t_other) inline
Copy Assignment Operator.
Definition at line 133 of file LineSighting.hpp.
References wb_line_sighting::leftPoint, wb_line_sighting::rightPoint, and wb_line_sighting::sightingType.
operator==() [1/2]
bool guWhiteboard::LineSighting::operator== (const LineSighting & t_other) const inline
Definition at line 138 of file LineSighting.hpp.
References leftPoint(), rightPoint(), and sightingType().
operator==() [2/2]
bool guWhiteboard::LineSighting::operator== (const wb_line_sighting & t_other) const inline
Definition at line 150 of file LineSighting.hpp.
References LineSighting().
rightPoint() [1/2]
PolarCoordinate & guWhiteboard::LineSighting::rightPoint () inline
Definition at line 175 of file LineSighting.hpp.
References wb_line_sighting::rightPoint.
Referenced by LineSighting(), description(), operator=(), operator==(), simpleLine(), and to_string().
rightPoint() [2/2]
const PolarCoordinate & guWhiteboard::LineSighting::rightPoint () const inline
Definition at line 180 of file LineSighting.hpp.
References wb_line_sighting::rightPoint.
set_leftPoint()
void guWhiteboard::LineSighting::set_leftPoint (const PolarCoordinate & t_newValue) inline
Definition at line 170 of file LineSighting.hpp.
References wb_line_sighting::leftPoint.
Referenced by from_string().
set_rightPoint()
void guWhiteboard::LineSighting::set_rightPoint (const PolarCoordinate & t_newValue) inline
Definition at line 185 of file LineSighting.hpp.
References wb_line_sighting::rightPoint.
Referenced by from_string().
set_sightingType()
void guWhiteboard::LineSighting::set_sightingType (const enum LineSightingType & t_newValue) inline
Definition at line 200 of file LineSighting.hpp.
References wb_line_sighting::sightingType.
Referenced by from_string().
sightingType() [1/2]
enum LineSightingType & guWhiteboard::LineSighting::sightingType () inline
Definition at line 190 of file LineSighting.hpp.
References wb_line_sighting::sightingType.
Referenced by LineSighting(), guWhiteboard::MachineFilteredLines::closestFeildLine(), description(), guWhiteboard::MachineFilteredLines::firstSighting(), operator=(), operator==(), and to_string().
sightingType() [2/2]
enum LineSightingType & guWhiteboard::LineSighting::sightingType () const inline
Definition at line 195 of file LineSighting.hpp.
References wb_line_sighting::sightingType.
simpleLine()
SimpleLine guWhiteboard::LineSighting::simpleLine () inline
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 399 of file LineSighting.hpp.
References leftPoint(), and rightPoint().
Referenced by guWhiteboard::MachineFilteredLines::closestFeildLine().
to_string()
std::string guWhiteboard::LineSighting::to_string () inline
USE_WB_LINE_SIGHTING_C_CONVERSION
Definition at line 242 of file LineSighting.hpp.
References FieldLineSightingType, HorizonLineSightingType, leftPoint(), LINE_SIGHTING_TO_STRING_BUFFER_SIZE, rightPoint(), sightingType(), guWhiteboard::PolarCoordinate::to_string(), and wb_line_sighting_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/LineSighting.hpp