gusimplewhiteboard: guWhiteboard::MachineFilteredLines Class Reference
guWhiteboard::MachineFilteredLines Class Reference
Provides a C++ wrapper around wb_machine_filtered_lines.
#include <MachineFilteredLines.hpp>
Public Member Functions
MachineFilteredLines (uint8_t t_numberOfSightings=0, const struct wb_line_sighting t_sightings[8]=NULLPTR)
Create a new MachineFilteredLines.
MachineFilteredLines (const MachineFilteredLines &t_other)
Copy Constructor.
MachineFilteredLines (const struct wb_machine_filtered_lines &t_other)
Copy Constructor.
MachineFilteredLines & operator= (const MachineFilteredLines &t_other)
Copy Assignment Operator.
MachineFilteredLines & operator= (const struct wb_machine_filtered_lines &t_other)
Copy Assignment Operator.
bool operator== (const MachineFilteredLines &t_other) const
bool operator!= (const MachineFilteredLines &t_other) const
bool operator== (const wb_machine_filtered_lines &t_other) const
bool operator!= (const wb_machine_filtered_lines &t_other) const
uint8_t & numberOfSightings ()
const uint8_t & numberOfSightings () const
void set_numberOfSightings (const uint8_t &t_newValue)
const LineSighting * sightings () const
size_t sightings_size () const
LineSighting & sightings (int t_i)
const LineSighting & sightings (int t_i) const
void set_sightings (const LineSighting *t_newValue)
void set_sightings (const LineSighting &t_newValue, int t_i)
MachineFilteredLines (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
int firstSighting (LineSightingType sightingType)
WHITEBOARD_POSTER_STRING_CONVERSION.
int closestFeildLine ()
int horizonLine ()
int fieldLine ()
Additional Inherited Members
Public Attributes inherited from wb_machine_filtered_lines
uint8_t numberOfSightings
The number of sightings in sightings.
struct wb_line_sighting sightings [8]
All sightings.
Detailed Description
Provides a C++ wrapper around wb_machine_filtered_lines.
Definition at line 86 of file MachineFilteredLines.hpp.
Constructor & Destructor Documentation
MachineFilteredLines() [1/4]
guWhiteboard::MachineFilteredLines::MachineFilteredLines (uint8_t t_numberOfSightings = 0, const struct wb_line_sighting t_sightings[8] = NULLPTR) inline
Create a new MachineFilteredLines.
Definition at line 108 of file MachineFilteredLines.hpp.
Referenced by operator==().
MachineFilteredLines() [2/4]
guWhiteboard::MachineFilteredLines::MachineFilteredLines (const MachineFilteredLines & t_other) inline
Copy Constructor.
Definition at line 115 of file MachineFilteredLines.hpp.
References numberOfSightings(), and sightings().
MachineFilteredLines() [3/4]
guWhiteboard::MachineFilteredLines::MachineFilteredLines (const struct wb_machine_filtered_lines & t_other) inline
Copy Constructor.
Definition at line 122 of file MachineFilteredLines.hpp.
References wb_machine_filtered_lines::numberOfSightings, and wb_machine_filtered_lines::sightings.
MachineFilteredLines() [4/4]
guWhiteboard::MachineFilteredLines::MachineFilteredLines (const std::string & t_str) inline
String Constructor.
Definition at line 219 of file MachineFilteredLines.hpp.
References from_string().
Member Function Documentation
closestFeildLine()
int guWhiteboard::MachineFilteredLines::closestFeildLine () inline
Definition at line 443 of file MachineFilteredLines.hpp.
References FieldLineSightingType, numberOfSightings(), sightings(), guWhiteboard::LineSighting::sightingType(), and guWhiteboard::LineSighting::simpleLine().
description()
std::string guWhiteboard::MachineFilteredLines::description () inline
USE_WB_MACHINE_FILTERED_LINES_C_CONVERSION
Definition at line 224 of file MachineFilteredLines.hpp.
References description(), MACHINE_FILTERED_LINES_DESC_BUFFER_SIZE, MACHINE_FILTERED_LINES_SIGHTINGS_ARRAY_SIZE, numberOfSightings(), sightings(), and wb_machine_filtered_lines_description().
Referenced by description().
fieldLine()
int guWhiteboard::MachineFilteredLines::fieldLine () inline
Definition at line 464 of file MachineFilteredLines.hpp.
References FieldLineSightingType, and firstSighting().
firstSighting()
int guWhiteboard::MachineFilteredLines::firstSighting (LineSightingType sightingType) inline
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 431 of file MachineFilteredLines.hpp.
References numberOfSightings(), sightings(), guWhiteboard::LineSighting::sightingType(), and wb_line_sighting::sightingType.
Referenced by fieldLine(), and horizonLine().
from_string()
void guWhiteboard::MachineFilteredLines::from_string (const std::string & t_str) inline
USE_WB_MACHINE_FILTERED_LINES_C_CONVERSION
Definition at line 270 of file MachineFilteredLines.hpp.
References guWhiteboard::LineSighting::from_string(), MACHINE_FILTERED_LINES_DESC_BUFFER_SIZE, MACHINE_FILTERED_LINES_SIGHTINGS_ARRAY_SIZE, set_numberOfSightings(), and set_sightings().
Referenced by MachineFilteredLines().
horizonLine()
int guWhiteboard::MachineFilteredLines::horizonLine () inline
Definition at line 459 of file MachineFilteredLines.hpp.
References firstSighting(), and HorizonLineSightingType.
numberOfSightings() [1/2]
uint8_t & guWhiteboard::MachineFilteredLines::numberOfSightings () inline
Definition at line 170 of file MachineFilteredLines.hpp.
References wb_machine_filtered_lines::numberOfSightings.
Referenced by MachineFilteredLines(), closestFeildLine(), description(), firstSighting(), operator=(), operator==(), and to_string().
numberOfSightings() [2/2]
const uint8_t & guWhiteboard::MachineFilteredLines::numberOfSightings () const inline
Definition at line 175 of file MachineFilteredLines.hpp.
References wb_machine_filtered_lines::numberOfSightings.
operator!=() [1/2]
bool guWhiteboard::MachineFilteredLines::operator!= (const MachineFilteredLines & t_other) const inline
Definition at line 155 of file MachineFilteredLines.hpp.
operator!=() [2/2]
bool guWhiteboard::MachineFilteredLines::operator!= (const wb_machine_filtered_lines & t_other) const inline
Definition at line 165 of file MachineFilteredLines.hpp.
operator=() [1/2]
MachineFilteredLines & guWhiteboard::MachineFilteredLines::operator= (const MachineFilteredLines & t_other) inline
Copy Assignment Operator.
Definition at line 129 of file MachineFilteredLines.hpp.
References numberOfSightings(), and sightings().
operator=() [2/2]
MachineFilteredLines & guWhiteboard::MachineFilteredLines::operator= (const struct wb_machine_filtered_lines & t_other) inline
Copy Assignment Operator.
Definition at line 137 of file MachineFilteredLines.hpp.
References wb_machine_filtered_lines::numberOfSightings, and wb_machine_filtered_lines::sightings.
operator==() [1/2]
bool guWhiteboard::MachineFilteredLines::operator== (const MachineFilteredLines & t_other) const inline
Definition at line 142 of file MachineFilteredLines.hpp.
References numberOfSightings(), and sightings().
operator==() [2/2]
bool guWhiteboard::MachineFilteredLines::operator== (const wb_machine_filtered_lines & t_other) const inline
Definition at line 160 of file MachineFilteredLines.hpp.
References MachineFilteredLines().
set_numberOfSightings()
void guWhiteboard::MachineFilteredLines::set_numberOfSightings (const uint8_t & t_newValue) inline
Definition at line 180 of file MachineFilteredLines.hpp.
References wb_machine_filtered_lines::numberOfSightings.
Referenced by from_string().
set_sightings() [1/2]
void guWhiteboard::MachineFilteredLines::set_sightings (const LineSighting & t_newValue, int t_i) inline
Definition at line 210 of file MachineFilteredLines.hpp.
References wb_machine_filtered_lines::sightings.
set_sightings() [2/2]
void guWhiteboard::MachineFilteredLines::set_sightings (const LineSighting * t_newValue) inline
Definition at line 205 of file MachineFilteredLines.hpp.
References MACHINE_FILTERED_LINES_SIGHTINGS_ARRAY_SIZE, and wb_machine_filtered_lines::sightings.
Referenced by from_string().
sightings() [1/3]
const LineSighting * guWhiteboard::MachineFilteredLines::sightings () const inline
Definition at line 185 of file MachineFilteredLines.hpp.
References wb_machine_filtered_lines::sightings.
Referenced by MachineFilteredLines(), closestFeildLine(), description(), firstSighting(), operator=(), operator==(), and to_string().
sightings() [2/3]
LineSighting & guWhiteboard::MachineFilteredLines::sightings (int t_i) inline
Definition at line 195 of file MachineFilteredLines.hpp.
References wb_machine_filtered_lines::sightings.
sightings() [3/3]
const LineSighting & guWhiteboard::MachineFilteredLines::sightings (int t_i) const inline
Definition at line 200 of file MachineFilteredLines.hpp.
References wb_machine_filtered_lines::sightings.
sightings_size()
size_t guWhiteboard::MachineFilteredLines::sightings_size () const inline
Definition at line 190 of file MachineFilteredLines.hpp.
References MACHINE_FILTERED_LINES_SIGHTINGS_ARRAY_SIZE.
to_string()
std::string guWhiteboard::MachineFilteredLines::to_string () inline
USE_WB_MACHINE_FILTERED_LINES_C_CONVERSION
Definition at line 245 of file MachineFilteredLines.hpp.
References MACHINE_FILTERED_LINES_SIGHTINGS_ARRAY_SIZE, MACHINE_FILTERED_LINES_TO_STRING_BUFFER_SIZE, numberOfSightings(), sightings(), to_string(), and wb_machine_filtered_lines_to_string().
Referenced by to_string().
The documentation for this class was generated from the following file:
typeClassDefs/MachineFilteredLines.hpp