gusimplewhiteboard: guWhiteboard::VisionFieldFeatures Class Reference
guWhiteboard::VisionFieldFeatures Class Reference
Provides a C++ wrapper around wb_vision_field_features.
#include <VisionFieldFeatures.hpp>
Public Member Functions
VisionFieldFeatures (const struct wb_vision_field_feature t_fieldCorner[8]=NULLPTR, const struct wb_vision_field_feature t_fieldIntersection[8]=NULLPTR, const struct wb_vision_field_feature t_fieldCrosses[3]=NULLPTR, uint8_t t_numCorners=0, uint8_t t_numIntersections=0, uint8_t t_numCrosses=0, uint16_t t_res_width=0, uint16_t t_res_height=0)
Create a new VisionFieldFeatures.
VisionFieldFeatures (const VisionFieldFeatures &t_other)
Copy Constructor.
VisionFieldFeatures (const struct wb_vision_field_features &t_other)
Copy Constructor.
VisionFieldFeatures & operator= (const VisionFieldFeatures &t_other)
Copy Assignment Operator.
VisionFieldFeatures & operator= (const struct wb_vision_field_features &t_other)
Copy Assignment Operator.
bool operator== (const VisionFieldFeatures &t_other) const
bool operator!= (const VisionFieldFeatures &t_other) const
bool operator== (const wb_vision_field_features &t_other) const
bool operator!= (const wb_vision_field_features &t_other) const
const VisionFieldFeature * fieldCorner () const
size_t fieldCorner_size () const
VisionFieldFeature & fieldCorner (int t_i)
const VisionFieldFeature & fieldCorner (int t_i) const
void set_fieldCorner (const VisionFieldFeature *t_newValue)
void set_fieldCorner (const VisionFieldFeature &t_newValue, int t_i)
const VisionFieldFeature * fieldIntersection () const
size_t fieldIntersection_size () const
VisionFieldFeature & fieldIntersection (int t_i)
const VisionFieldFeature & fieldIntersection (int t_i) const
void set_fieldIntersection (const VisionFieldFeature *t_newValue)
void set_fieldIntersection (const VisionFieldFeature &t_newValue, int t_i)
const VisionFieldFeature * fieldCrosses () const
size_t fieldCrosses_size () const
VisionFieldFeature & fieldCrosses (int t_i)
const VisionFieldFeature & fieldCrosses (int t_i) const
void set_fieldCrosses (const VisionFieldFeature *t_newValue)
void set_fieldCrosses (const VisionFieldFeature &t_newValue, int t_i)
uint8_t & numCorners ()
const uint8_t & numCorners () const
void set_numCorners (const uint8_t &t_newValue)
uint8_t & numIntersections ()
const uint8_t & numIntersections () const
void set_numIntersections (const uint8_t &t_newValue)
uint8_t & numCrosses ()
const uint8_t & numCrosses () const
void set_numCrosses (const uint8_t &t_newValue)
uint16_t & res_width ()
const uint16_t & res_width () const
void set_res_width (const uint16_t &t_newValue)
uint16_t & res_height ()
const uint16_t & res_height () const
void set_res_height (const uint16_t &t_newValue)
VisionFieldFeatures (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_vision_field_features
struct wb_vision_field_feature fieldCorner [8]
Location of corners on the field.
struct wb_vision_field_feature fieldIntersection [8]
Location of T-Intersections on the field.
struct wb_vision_field_feature fieldCrosses [3]
Location of T-Intersections on the field.
uint8_t numCorners
Number of corners in this message.
uint8_t numIntersections
Number of T-Intersections in this message.
uint8_t numCrosses
Numer of Crosses in this message.
uint16_t res_width
The resolution width.
uint16_t res_height
The resolution height.
Detailed Description
Provides a C++ wrapper around wb_vision_field_features.
Definition at line 85 of file VisionFieldFeatures.hpp.
Constructor & Destructor Documentation
VisionFieldFeatures() [1/4]
guWhiteboard::VisionFieldFeatures::VisionFieldFeatures (const struct wb_vision_field_feature t_fieldCorner[8] = NULLPTR, const struct wb_vision_field_feature t_fieldIntersection[8] = NULLPTR, const struct wb_vision_field_feature t_fieldCrosses[3] = NULLPTR, uint8_t t_numCorners = 0, uint8_t t_numIntersections = 0, uint8_t t_numCrosses = 0, uint16_t t_res_width = 0, uint16_t t_res_height = 0) inline
Create a new VisionFieldFeatures.
Definition at line 123 of file VisionFieldFeatures.hpp.
Referenced by operator==().
VisionFieldFeatures() [2/4]
guWhiteboard::VisionFieldFeatures::VisionFieldFeatures (const VisionFieldFeatures & t_other) inline
Copy Constructor.
Definition at line 130 of file VisionFieldFeatures.hpp.
References fieldCorner(), fieldCrosses(), fieldIntersection(), numCorners(), numCrosses(), numIntersections(), res_height(), and res_width().
VisionFieldFeatures() [3/4]
guWhiteboard::VisionFieldFeatures::VisionFieldFeatures (const struct wb_vision_field_features & t_other) inline
Copy Constructor.
Definition at line 137 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::fieldCorner, wb_vision_field_features::fieldCrosses, wb_vision_field_features::fieldIntersection, wb_vision_field_features::numCorners, wb_vision_field_features::numCrosses, wb_vision_field_features::numIntersections, wb_vision_field_features::res_height, and wb_vision_field_features::res_width.
VisionFieldFeatures() [4/4]
guWhiteboard::VisionFieldFeatures::VisionFieldFeatures (const std::string & t_str) inline
String Constructor.
Definition at line 366 of file VisionFieldFeatures.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::VisionFieldFeatures::description () inline
USE_WB_VISION_FIELD_FEATURES_C_CONVERSION
Definition at line 371 of file VisionFieldFeatures.hpp.
References description(), fieldCorner(), fieldCrosses(), fieldIntersection(), numCorners(), numCrosses(), numIntersections(), res_height(), res_width(), VISION_FIELD_FEATURES_DESC_BUFFER_SIZE, VISION_FIELD_FEATURES_FIELDCORNER_ARRAY_SIZE, VISION_FIELD_FEATURES_FIELDCROSSES_ARRAY_SIZE, VISION_FIELD_FEATURES_FIELDINTERSECTION_ARRAY_SIZE, and wb_vision_field_features_description().
Referenced by description().
fieldCorner() [1/3]
const VisionFieldFeature * guWhiteboard::VisionFieldFeatures::fieldCorner () const inline
Definition at line 197 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::fieldCorner.
Referenced by VisionFieldFeatures(), description(), operator=(), operator==(), and to_string().
fieldCorner() [2/3]
VisionFieldFeature & guWhiteboard::VisionFieldFeatures::fieldCorner (int t_i) inline
Definition at line 207 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::fieldCorner.
fieldCorner() [3/3]
const VisionFieldFeature & guWhiteboard::VisionFieldFeatures::fieldCorner (int t_i) const inline
Definition at line 212 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::fieldCorner.
fieldCorner_size()
size_t guWhiteboard::VisionFieldFeatures::fieldCorner_size () const inline
Definition at line 202 of file VisionFieldFeatures.hpp.
References VISION_FIELD_FEATURES_FIELDCORNER_ARRAY_SIZE.
fieldCrosses() [1/3]
const VisionFieldFeature * guWhiteboard::VisionFieldFeatures::fieldCrosses () const inline
Definition at line 257 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::fieldCrosses.
Referenced by VisionFieldFeatures(), description(), operator=(), operator==(), and to_string().
fieldCrosses() [2/3]
VisionFieldFeature & guWhiteboard::VisionFieldFeatures::fieldCrosses (int t_i) inline
Definition at line 267 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::fieldCrosses.
fieldCrosses() [3/3]
const VisionFieldFeature & guWhiteboard::VisionFieldFeatures::fieldCrosses (int t_i) const inline
Definition at line 272 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::fieldCrosses.
fieldCrosses_size()
size_t guWhiteboard::VisionFieldFeatures::fieldCrosses_size () const inline
Definition at line 262 of file VisionFieldFeatures.hpp.
References VISION_FIELD_FEATURES_FIELDCROSSES_ARRAY_SIZE.
fieldIntersection() [1/3]
const VisionFieldFeature * guWhiteboard::VisionFieldFeatures::fieldIntersection () const inline
Definition at line 227 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::fieldIntersection.
Referenced by VisionFieldFeatures(), description(), operator=(), operator==(), and to_string().
fieldIntersection() [2/3]
VisionFieldFeature & guWhiteboard::VisionFieldFeatures::fieldIntersection (int t_i) inline
Definition at line 237 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::fieldIntersection.
fieldIntersection() [3/3]
const VisionFieldFeature & guWhiteboard::VisionFieldFeatures::fieldIntersection (int t_i) const inline
Definition at line 242 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::fieldIntersection.
fieldIntersection_size()
size_t guWhiteboard::VisionFieldFeatures::fieldIntersection_size () const inline
Definition at line 232 of file VisionFieldFeatures.hpp.
References VISION_FIELD_FEATURES_FIELDINTERSECTION_ARRAY_SIZE.
from_string()
void guWhiteboard::VisionFieldFeatures::from_string (const std::string & t_str) inline
USE_WB_VISION_FIELD_FEATURES_C_CONVERSION
Definition at line 465 of file VisionFieldFeatures.hpp.
References guWhiteboard::VisionFieldFeature::from_string(), set_fieldCorner(), set_fieldCrosses(), set_fieldIntersection(), set_numCorners(), set_numCrosses(), set_numIntersections(), set_res_height(), set_res_width(), VISION_FIELD_FEATURES_DESC_BUFFER_SIZE, VISION_FIELD_FEATURES_FIELDCORNER_ARRAY_SIZE, VISION_FIELD_FEATURES_FIELDCROSSES_ARRAY_SIZE, and VISION_FIELD_FEATURES_FIELDINTERSECTION_ARRAY_SIZE.
Referenced by VisionFieldFeatures().
numCorners() [1/2]
uint8_t & guWhiteboard::VisionFieldFeatures::numCorners () inline
Definition at line 287 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::numCorners.
Referenced by VisionFieldFeatures(), description(), operator=(), operator==(), and to_string().
numCorners() [2/2]
const uint8_t & guWhiteboard::VisionFieldFeatures::numCorners () const inline
Definition at line 292 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::numCorners.
numCrosses() [1/2]
uint8_t & guWhiteboard::VisionFieldFeatures::numCrosses () inline
Definition at line 317 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::numCrosses.
Referenced by VisionFieldFeatures(), description(), operator=(), operator==(), and to_string().
numCrosses() [2/2]
const uint8_t & guWhiteboard::VisionFieldFeatures::numCrosses () const inline
Definition at line 322 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::numCrosses.
numIntersections() [1/2]
uint8_t & guWhiteboard::VisionFieldFeatures::numIntersections () inline
Definition at line 302 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::numIntersections.
Referenced by VisionFieldFeatures(), description(), operator=(), operator==(), and to_string().
numIntersections() [2/2]
const uint8_t & guWhiteboard::VisionFieldFeatures::numIntersections () const inline
Definition at line 307 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::numIntersections.
operator!=() [1/2]
bool guWhiteboard::VisionFieldFeatures::operator!= (const VisionFieldFeatures & t_other) const inline
Definition at line 182 of file VisionFieldFeatures.hpp.
operator!=() [2/2]
bool guWhiteboard::VisionFieldFeatures::operator!= (const wb_vision_field_features & t_other) const inline
Definition at line 192 of file VisionFieldFeatures.hpp.
operator=() [1/2]
VisionFieldFeatures & guWhiteboard::VisionFieldFeatures::operator= (const struct wb_vision_field_features & t_other) inline
Copy Assignment Operator.
Definition at line 152 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::fieldCorner, wb_vision_field_features::fieldCrosses, wb_vision_field_features::fieldIntersection, wb_vision_field_features::numCorners, wb_vision_field_features::numCrosses, wb_vision_field_features::numIntersections, wb_vision_field_features::res_height, and wb_vision_field_features::res_width.
operator=() [2/2]
VisionFieldFeatures & guWhiteboard::VisionFieldFeatures::operator= (const VisionFieldFeatures & t_other) inline
Copy Assignment Operator.
Definition at line 144 of file VisionFieldFeatures.hpp.
References fieldCorner(), fieldCrosses(), fieldIntersection(), numCorners(), numCrosses(), numIntersections(), res_height(), and res_width().
operator==() [1/2]
bool guWhiteboard::VisionFieldFeatures::operator== (const VisionFieldFeatures & t_other) const inline
Definition at line 157 of file VisionFieldFeatures.hpp.
References fieldCorner(), fieldCrosses(), fieldIntersection(), numCorners(), numCrosses(), numIntersections(), res_height(), and res_width().
operator==() [2/2]
bool guWhiteboard::VisionFieldFeatures::operator== (const wb_vision_field_features & t_other) const inline
Definition at line 187 of file VisionFieldFeatures.hpp.
References VisionFieldFeatures().
res_height() [1/2]
uint16_t & guWhiteboard::VisionFieldFeatures::res_height () inline
Definition at line 347 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::res_height.
Referenced by VisionFieldFeatures(), description(), operator=(), operator==(), and to_string().
res_height() [2/2]
const uint16_t & guWhiteboard::VisionFieldFeatures::res_height () const inline
Definition at line 352 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::res_height.
res_width() [1/2]
uint16_t & guWhiteboard::VisionFieldFeatures::res_width () inline
Definition at line 332 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::res_width.
Referenced by VisionFieldFeatures(), description(), operator=(), operator==(), and to_string().
res_width() [2/2]
const uint16_t & guWhiteboard::VisionFieldFeatures::res_width () const inline
Definition at line 337 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::res_width.
set_fieldCorner() [1/2]
void guWhiteboard::VisionFieldFeatures::set_fieldCorner (const VisionFieldFeature & t_newValue, int t_i) inline
Definition at line 222 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::fieldCorner.
set_fieldCorner() [2/2]
void guWhiteboard::VisionFieldFeatures::set_fieldCorner (const VisionFieldFeature * t_newValue) inline
Definition at line 217 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::fieldCorner, and VISION_FIELD_FEATURES_FIELDCORNER_ARRAY_SIZE.
Referenced by from_string().
set_fieldCrosses() [1/2]
void guWhiteboard::VisionFieldFeatures::set_fieldCrosses (const VisionFieldFeature & t_newValue, int t_i) inline
Definition at line 282 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::fieldCrosses.
set_fieldCrosses() [2/2]
void guWhiteboard::VisionFieldFeatures::set_fieldCrosses (const VisionFieldFeature * t_newValue) inline
Definition at line 277 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::fieldCrosses, and VISION_FIELD_FEATURES_FIELDCROSSES_ARRAY_SIZE.
Referenced by from_string().
set_fieldIntersection() [1/2]
void guWhiteboard::VisionFieldFeatures::set_fieldIntersection (const VisionFieldFeature & t_newValue, int t_i) inline
Definition at line 252 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::fieldIntersection.
set_fieldIntersection() [2/2]
void guWhiteboard::VisionFieldFeatures::set_fieldIntersection (const VisionFieldFeature * t_newValue) inline
Definition at line 247 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::fieldIntersection, and VISION_FIELD_FEATURES_FIELDINTERSECTION_ARRAY_SIZE.
Referenced by from_string().
set_numCorners()
void guWhiteboard::VisionFieldFeatures::set_numCorners (const uint8_t & t_newValue) inline
Definition at line 297 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::numCorners.
Referenced by from_string().
set_numCrosses()
void guWhiteboard::VisionFieldFeatures::set_numCrosses (const uint8_t & t_newValue) inline
Definition at line 327 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::numCrosses.
Referenced by from_string().
set_numIntersections()
void guWhiteboard::VisionFieldFeatures::set_numIntersections (const uint8_t & t_newValue) inline
Definition at line 312 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::numIntersections.
Referenced by from_string().
set_res_height()
void guWhiteboard::VisionFieldFeatures::set_res_height (const uint16_t & t_newValue) inline
Definition at line 357 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::res_height.
Referenced by from_string().
set_res_width()
void guWhiteboard::VisionFieldFeatures::set_res_width (const uint16_t & t_newValue) inline
Definition at line 342 of file VisionFieldFeatures.hpp.
References wb_vision_field_features::res_width.
Referenced by from_string().
to_string()
std::string guWhiteboard::VisionFieldFeatures::to_string () inline
USE_WB_VISION_FIELD_FEATURES_C_CONVERSION
Definition at line 416 of file VisionFieldFeatures.hpp.
References fieldCorner(), fieldCrosses(), fieldIntersection(), numCorners(), numCrosses(), numIntersections(), res_height(), res_width(), to_string(), VISION_FIELD_FEATURES_FIELDCORNER_ARRAY_SIZE, VISION_FIELD_FEATURES_FIELDCROSSES_ARRAY_SIZE, VISION_FIELD_FEATURES_FIELDINTERSECTION_ARRAY_SIZE, VISION_FIELD_FEATURES_TO_STRING_BUFFER_SIZE, and wb_vision_field_features_to_string().
Referenced by to_string().
The documentation for this class was generated from the following file:
typeClassDefs/VisionFieldFeatures.hpp