gusimplewhiteboard: guWhiteboard::VisionDetectionFeatureArray Class Reference
guWhiteboard::VisionDetectionFeatureArray Class Reference
Provides a C++ wrapper around wb_vision_detection_feature_array.
#include <VisionDetectionFeatureArray.hpp>
Public Member Functions
VisionDetectionFeatureArray (uint8_t t_numFeatures=0, const struct wb_vision_detection_feature t_features[7]=NULLPTR)
Create a new VisionDetectionFeatureArray.
VisionDetectionFeatureArray (const VisionDetectionFeatureArray &t_other)
Copy Constructor.
VisionDetectionFeatureArray (const struct wb_vision_detection_feature_array &t_other)
Copy Constructor.
VisionDetectionFeatureArray & operator= (const VisionDetectionFeatureArray &t_other)
Copy Assignment Operator.
VisionDetectionFeatureArray & operator= (const struct wb_vision_detection_feature_array &t_other)
Copy Assignment Operator.
bool operator== (const VisionDetectionFeatureArray &t_other) const
bool operator!= (const VisionDetectionFeatureArray &t_other) const
bool operator== (const wb_vision_detection_feature_array &t_other) const
bool operator!= (const wb_vision_detection_feature_array &t_other) const
uint8_t & numFeatures ()
const uint8_t & numFeatures () const
void set_numFeatures (const uint8_t &t_newValue)
const VisionDetectionFeature * features () const
size_t features_size () const
VisionDetectionFeature & features (int t_i)
const VisionDetectionFeature & features (int t_i) const
void set_features (const VisionDetectionFeature *t_newValue)
void set_features (const VisionDetectionFeature &t_newValue, int t_i)
VisionDetectionFeatureArray (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_vision_detection_feature_array
uint8_t numFeatures
The number of features reported on the camera.
struct wb_vision_detection_feature features [7]
Features reported from the camera.
Detailed Description
Provides a C++ wrapper around wb_vision_detection_feature_array.
Definition at line 85 of file VisionDetectionFeatureArray.hpp.
Constructor & Destructor Documentation
VisionDetectionFeatureArray() [1/4]
guWhiteboard::VisionDetectionFeatureArray::VisionDetectionFeatureArray (uint8_t t_numFeatures = 0, const struct wb_vision_detection_feature t_features[7] = NULLPTR) inline
Create a new VisionDetectionFeatureArray.
Definition at line 107 of file VisionDetectionFeatureArray.hpp.
Referenced by operator==().
VisionDetectionFeatureArray() [2/4]
guWhiteboard::VisionDetectionFeatureArray::VisionDetectionFeatureArray (const VisionDetectionFeatureArray & t_other) inline
Copy Constructor.
Definition at line 114 of file VisionDetectionFeatureArray.hpp.
References features(), and numFeatures().
VisionDetectionFeatureArray() [3/4]
guWhiteboard::VisionDetectionFeatureArray::VisionDetectionFeatureArray (const struct wb_vision_detection_feature_array & t_other) inline
Copy Constructor.
Definition at line 121 of file VisionDetectionFeatureArray.hpp.
References wb_vision_detection_feature_array::features, and wb_vision_detection_feature_array::numFeatures.
VisionDetectionFeatureArray() [4/4]
guWhiteboard::VisionDetectionFeatureArray::VisionDetectionFeatureArray (const std::string & t_str) inline
String Constructor.
Definition at line 218 of file VisionDetectionFeatureArray.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::VisionDetectionFeatureArray::description () inline
USE_WB_VISION_DETECTION_FEATURE_ARRAY_C_CONVERSION
Definition at line 223 of file VisionDetectionFeatureArray.hpp.
References description(), features(), numFeatures(), VISION_DETECTION_FEATURE_ARRAY_DESC_BUFFER_SIZE, VISION_DETECTION_FEATURE_ARRAY_FEATURES_ARRAY_SIZE, and wb_vision_detection_feature_array_description().
Referenced by description().
features() [1/3]
const VisionDetectionFeature * guWhiteboard::VisionDetectionFeatureArray::features () const inline
Definition at line 184 of file VisionDetectionFeatureArray.hpp.
References wb_vision_detection_feature_array::features.
Referenced by VisionDetectionFeatureArray(), description(), operator=(), operator==(), and to_string().
features() [2/3]
VisionDetectionFeature & guWhiteboard::VisionDetectionFeatureArray::features (int t_i) inline
Definition at line 194 of file VisionDetectionFeatureArray.hpp.
References wb_vision_detection_feature_array::features.
features() [3/3]
const VisionDetectionFeature & guWhiteboard::VisionDetectionFeatureArray::features (int t_i) const inline
Definition at line 199 of file VisionDetectionFeatureArray.hpp.
References wb_vision_detection_feature_array::features.
features_size()
size_t guWhiteboard::VisionDetectionFeatureArray::features_size () const inline
Definition at line 189 of file VisionDetectionFeatureArray.hpp.
References VISION_DETECTION_FEATURE_ARRAY_FEATURES_ARRAY_SIZE.
from_string()
void guWhiteboard::VisionDetectionFeatureArray::from_string (const std::string & t_str) inline
USE_WB_VISION_DETECTION_FEATURE_ARRAY_C_CONVERSION
Definition at line 269 of file VisionDetectionFeatureArray.hpp.
References guWhiteboard::VisionDetectionFeature::from_string(), set_features(), set_numFeatures(), VISION_DETECTION_FEATURE_ARRAY_DESC_BUFFER_SIZE, and VISION_DETECTION_FEATURE_ARRAY_FEATURES_ARRAY_SIZE.
Referenced by VisionDetectionFeatureArray(), and guWhiteboard::VisionDetectionFeatures::from_string().
numFeatures() [1/2]
uint8_t & guWhiteboard::VisionDetectionFeatureArray::numFeatures () inline
Definition at line 169 of file VisionDetectionFeatureArray.hpp.
References wb_vision_detection_feature_array::numFeatures.
Referenced by VisionDetectionFeatureArray(), description(), operator=(), operator==(), and to_string().
numFeatures() [2/2]
const uint8_t & guWhiteboard::VisionDetectionFeatureArray::numFeatures () const inline
Definition at line 174 of file VisionDetectionFeatureArray.hpp.
References wb_vision_detection_feature_array::numFeatures.
operator!=() [1/2]
bool guWhiteboard::VisionDetectionFeatureArray::operator!= (const VisionDetectionFeatureArray & t_other) const inline
Definition at line 154 of file VisionDetectionFeatureArray.hpp.
operator!=() [2/2]
bool guWhiteboard::VisionDetectionFeatureArray::operator!= (const wb_vision_detection_feature_array & t_other) const inline
Definition at line 164 of file VisionDetectionFeatureArray.hpp.
operator=() [1/2]
VisionDetectionFeatureArray & guWhiteboard::VisionDetectionFeatureArray::operator= (const struct wb_vision_detection_feature_array & t_other) inline
Copy Assignment Operator.
Definition at line 136 of file VisionDetectionFeatureArray.hpp.
References wb_vision_detection_feature_array::features, and wb_vision_detection_feature_array::numFeatures.
operator=() [2/2]
VisionDetectionFeatureArray & guWhiteboard::VisionDetectionFeatureArray::operator= (const VisionDetectionFeatureArray & t_other) inline
Copy Assignment Operator.
Definition at line 128 of file VisionDetectionFeatureArray.hpp.
References features(), and numFeatures().
operator==() [1/2]
bool guWhiteboard::VisionDetectionFeatureArray::operator== (const VisionDetectionFeatureArray & t_other) const inline
Definition at line 141 of file VisionDetectionFeatureArray.hpp.
References features(), and numFeatures().
operator==() [2/2]
bool guWhiteboard::VisionDetectionFeatureArray::operator== (const wb_vision_detection_feature_array & t_other) const inline
Definition at line 159 of file VisionDetectionFeatureArray.hpp.
References VisionDetectionFeatureArray().
set_features() [1/2]
void guWhiteboard::VisionDetectionFeatureArray::set_features (const VisionDetectionFeature & t_newValue, int t_i) inline
Definition at line 209 of file VisionDetectionFeatureArray.hpp.
References wb_vision_detection_feature_array::features.
set_features() [2/2]
void guWhiteboard::VisionDetectionFeatureArray::set_features (const VisionDetectionFeature * t_newValue) inline
Definition at line 204 of file VisionDetectionFeatureArray.hpp.
References wb_vision_detection_feature_array::features, and VISION_DETECTION_FEATURE_ARRAY_FEATURES_ARRAY_SIZE.
Referenced by from_string().
set_numFeatures()
void guWhiteboard::VisionDetectionFeatureArray::set_numFeatures (const uint8_t & t_newValue) inline
Definition at line 179 of file VisionDetectionFeatureArray.hpp.
References wb_vision_detection_feature_array::numFeatures.
Referenced by from_string().
to_string()
std::string guWhiteboard::VisionDetectionFeatureArray::to_string () inline
USE_WB_VISION_DETECTION_FEATURE_ARRAY_C_CONVERSION
Definition at line 244 of file VisionDetectionFeatureArray.hpp.
References features(), numFeatures(), to_string(), VISION_DETECTION_FEATURE_ARRAY_FEATURES_ARRAY_SIZE, VISION_DETECTION_FEATURE_ARRAY_TO_STRING_BUFFER_SIZE, and wb_vision_detection_feature_array_to_string().
Referenced by to_string().
The documentation for this class was generated from the following file:
typeClassDefs/VisionDetectionFeatureArray.hpp