gusimplewhiteboard: guWhiteboard::FilteredArrayOneDimObjects Class Reference
guWhiteboard::FilteredArrayOneDimObjects Class Reference
Provides a C++ wrapper around wb_filtered_arrayonedimobjects.
#include <FilteredArrayOneDimObjects.hpp>
Public Member Functions
FilteredArrayOneDimObjects (const struct wb_filtered_vision_object t_objects[4]=NULLPTR)
Create a new FilteredArrayOneDimObjects.
FilteredArrayOneDimObjects (const FilteredArrayOneDimObjects &t_other)
Copy Constructor.
FilteredArrayOneDimObjects (const struct wb_filtered_arrayonedimobjects &t_other)
Copy Constructor.
FilteredArrayOneDimObjects & operator= (const FilteredArrayOneDimObjects &t_other)
Copy Assignment Operator.
FilteredArrayOneDimObjects & operator= (const struct wb_filtered_arrayonedimobjects &t_other)
Copy Assignment Operator.
bool operator== (const FilteredArrayOneDimObjects &t_other) const
bool operator!= (const FilteredArrayOneDimObjects &t_other) const
bool operator== (const wb_filtered_arrayonedimobjects &t_other) const
bool operator!= (const wb_filtered_arrayonedimobjects &t_other) const
const FilteredVisionObject * objects () const
size_t objects_size () const
FilteredVisionObject & objects (int t_i)
const FilteredVisionObject & objects (int t_i) const
void set_objects (const FilteredVisionObject *t_newValue)
void set_objects (const FilteredVisionObject &t_newValue, int t_i)
FilteredArrayOneDimObjects (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_filtered_arrayonedimobjects
struct wb_filtered_vision_object objects [4]
the array containing various filtered parts of the goals reported by vision FVO_NUM_OBJECTS =4
Detailed Description
Provides a C++ wrapper around wb_filtered_arrayonedimobjects.
Definition at line 85 of file FilteredArrayOneDimObjects.hpp.
Constructor & Destructor Documentation
FilteredArrayOneDimObjects() [1/4]
guWhiteboard::FilteredArrayOneDimObjects::FilteredArrayOneDimObjects (const struct wb_filtered_vision_object t_objects[4] = NULLPTR) inline
Create a new FilteredArrayOneDimObjects.
Definition at line 106 of file FilteredArrayOneDimObjects.hpp.
Referenced by operator==().
FilteredArrayOneDimObjects() [2/4]
guWhiteboard::FilteredArrayOneDimObjects::FilteredArrayOneDimObjects (const FilteredArrayOneDimObjects & t_other) inline
Copy Constructor.
Definition at line 113 of file FilteredArrayOneDimObjects.hpp.
References objects().
FilteredArrayOneDimObjects() [3/4]
guWhiteboard::FilteredArrayOneDimObjects::FilteredArrayOneDimObjects (const struct wb_filtered_arrayonedimobjects & t_other) inline
Copy Constructor.
Definition at line 120 of file FilteredArrayOneDimObjects.hpp.
References wb_filtered_arrayonedimobjects::objects.
FilteredArrayOneDimObjects() [4/4]
guWhiteboard::FilteredArrayOneDimObjects::FilteredArrayOneDimObjects (const std::string & t_str) inline
String Constructor.
Definition at line 198 of file FilteredArrayOneDimObjects.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::FilteredArrayOneDimObjects::description () inline
USE_WB_FILTERED_ARRAYONEDIMOBJECTS_C_CONVERSION
Definition at line 203 of file FilteredArrayOneDimObjects.hpp.
References description(), FILTERED_ARRAYONEDIMOBJECTS_DESC_BUFFER_SIZE, FILTERED_ARRAYONEDIMOBJECTS_OBJECTS_ARRAY_SIZE, objects(), and wb_filtered_arrayonedimobjects_description().
Referenced by description().
from_string()
void guWhiteboard::FilteredArrayOneDimObjects::from_string (const std::string & t_str) inline
USE_WB_FILTERED_ARRAYONEDIMOBJECTS_C_CONVERSION
Definition at line 245 of file FilteredArrayOneDimObjects.hpp.
References FILTERED_ARRAYONEDIMOBJECTS_DESC_BUFFER_SIZE, FILTERED_ARRAYONEDIMOBJECTS_OBJECTS_ARRAY_SIZE, guWhiteboard::FilteredVisionObject::from_string(), and set_objects().
Referenced by FilteredArrayOneDimObjects().
objects() [1/3]
const FilteredVisionObject * guWhiteboard::FilteredArrayOneDimObjects::objects () const inline
Definition at line 164 of file FilteredArrayOneDimObjects.hpp.
References wb_filtered_arrayonedimobjects::objects.
Referenced by FilteredArrayOneDimObjects(), description(), operator=(), operator==(), and to_string().
objects() [2/3]
FilteredVisionObject & guWhiteboard::FilteredArrayOneDimObjects::objects (int t_i) inline
Definition at line 174 of file FilteredArrayOneDimObjects.hpp.
References wb_filtered_arrayonedimobjects::objects.
objects() [3/3]
const FilteredVisionObject & guWhiteboard::FilteredArrayOneDimObjects::objects (int t_i) const inline
Definition at line 179 of file FilteredArrayOneDimObjects.hpp.
References wb_filtered_arrayonedimobjects::objects.
objects_size()
size_t guWhiteboard::FilteredArrayOneDimObjects::objects_size () const inline
Definition at line 169 of file FilteredArrayOneDimObjects.hpp.
References FILTERED_ARRAYONEDIMOBJECTS_OBJECTS_ARRAY_SIZE.
operator!=() [1/2]
bool guWhiteboard::FilteredArrayOneDimObjects::operator!= (const FilteredArrayOneDimObjects & t_other) const inline
Definition at line 149 of file FilteredArrayOneDimObjects.hpp.
operator!=() [2/2]
bool guWhiteboard::FilteredArrayOneDimObjects::operator!= (const wb_filtered_arrayonedimobjects & t_other) const inline
Definition at line 159 of file FilteredArrayOneDimObjects.hpp.
operator=() [1/2]
FilteredArrayOneDimObjects & guWhiteboard::FilteredArrayOneDimObjects::operator= (const FilteredArrayOneDimObjects & t_other) inline
Copy Assignment Operator.
Definition at line 127 of file FilteredArrayOneDimObjects.hpp.
References objects().
operator=() [2/2]
FilteredArrayOneDimObjects & guWhiteboard::FilteredArrayOneDimObjects::operator= (const struct wb_filtered_arrayonedimobjects & t_other) inline
Copy Assignment Operator.
Definition at line 135 of file FilteredArrayOneDimObjects.hpp.
References wb_filtered_arrayonedimobjects::objects.
operator==() [1/2]
bool guWhiteboard::FilteredArrayOneDimObjects::operator== (const FilteredArrayOneDimObjects & t_other) const inline
Definition at line 140 of file FilteredArrayOneDimObjects.hpp.
References objects().
operator==() [2/2]
bool guWhiteboard::FilteredArrayOneDimObjects::operator== (const wb_filtered_arrayonedimobjects & t_other) const inline
Definition at line 154 of file FilteredArrayOneDimObjects.hpp.
References FilteredArrayOneDimObjects().
set_objects() [1/2]
void guWhiteboard::FilteredArrayOneDimObjects::set_objects (const FilteredVisionObject & t_newValue, int t_i) inline
Definition at line 189 of file FilteredArrayOneDimObjects.hpp.
References wb_filtered_arrayonedimobjects::objects.
set_objects() [2/2]
void guWhiteboard::FilteredArrayOneDimObjects::set_objects (const FilteredVisionObject * t_newValue) inline
Definition at line 184 of file FilteredArrayOneDimObjects.hpp.
References FILTERED_ARRAYONEDIMOBJECTS_OBJECTS_ARRAY_SIZE, and wb_filtered_arrayonedimobjects::objects.
Referenced by from_string().
to_string()
std::string guWhiteboard::FilteredArrayOneDimObjects::to_string () inline
USE_WB_FILTERED_ARRAYONEDIMOBJECTS_C_CONVERSION
Definition at line 222 of file FilteredArrayOneDimObjects.hpp.
References FILTERED_ARRAYONEDIMOBJECTS_OBJECTS_ARRAY_SIZE, FILTERED_ARRAYONEDIMOBJECTS_TO_STRING_BUFFER_SIZE, objects(), to_string(), and wb_filtered_arrayonedimobjects_to_string().
Referenced by to_string().
The documentation for this class was generated from the following file:
typeClassDefs/FilteredArrayOneDimObjects.hpp