gusimplewhiteboard: guWhiteboard::VisionDetectionFeature Class Reference
guWhiteboard::VisionDetectionFeature Class Reference
Provides a C++ wrapper around wb_vision_detection_feature.
#include <VisionDetectionFeature.hpp>
Public Member Functions
VisionDetectionFeature (enum FeatureTypes t_featureType=NUMBER_OF_FEATURE_TYPES, struct wb_polar_coordinate t_coordinate=wb_polar_coordinate())
Create a new VisionDetectionFeature.
VisionDetectionFeature (const VisionDetectionFeature &t_other)
Copy Constructor.
VisionDetectionFeature (const struct wb_vision_detection_feature &t_other)
Copy Constructor.
VisionDetectionFeature & operator= (const VisionDetectionFeature &t_other)
Copy Assignment Operator.
VisionDetectionFeature & operator= (const struct wb_vision_detection_feature &t_other)
Copy Assignment Operator.
bool operator== (const VisionDetectionFeature &t_other) const
bool operator!= (const VisionDetectionFeature &t_other) const
bool operator== (const wb_vision_detection_feature &t_other) const
bool operator!= (const wb_vision_detection_feature &t_other) const
enum FeatureTypes & featureType ()
enum FeatureTypes & featureType () const
void set_featureType (const enum FeatureTypes &t_newValue)
PolarCoordinate & coordinate ()
const PolarCoordinate & coordinate () const
void set_coordinate (const PolarCoordinate &t_newValue)
VisionDetectionFeature (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_vision_detection_feature
enum FeatureTypes featureType
Type of the Feature.
struct wb_polar_coordinate coordinate
Where the feature is.
Detailed Description
Provides a C++ wrapper around wb_vision_detection_feature.
Definition at line 85 of file VisionDetectionFeature.hpp.
Constructor & Destructor Documentation
VisionDetectionFeature() [1/4]
guWhiteboard::VisionDetectionFeature::VisionDetectionFeature (enum FeatureTypes t_featureType = NUMBER_OF_FEATURE_TYPES, struct wb_polar_coordinate t_coordinate = wb_polar_coordinate()) inline
Create a new VisionDetectionFeature.
Definition at line 102 of file VisionDetectionFeature.hpp.
Referenced by operator==().
VisionDetectionFeature() [2/4]
guWhiteboard::VisionDetectionFeature::VisionDetectionFeature (const VisionDetectionFeature & t_other) inline
Copy Constructor.
Definition at line 109 of file VisionDetectionFeature.hpp.
References coordinate(), and featureType().
VisionDetectionFeature() [3/4]
guWhiteboard::VisionDetectionFeature::VisionDetectionFeature (const struct wb_vision_detection_feature & t_other) inline
Copy Constructor.
Definition at line 116 of file VisionDetectionFeature.hpp.
References wb_vision_detection_feature::coordinate, and wb_vision_detection_feature::featureType.
VisionDetectionFeature() [4/4]
guWhiteboard::VisionDetectionFeature::VisionDetectionFeature (const std::string & t_str) inline
String Constructor.
Definition at line 191 of file VisionDetectionFeature.hpp.
References from_string().
Member Function Documentation
coordinate() [1/2]
PolarCoordinate & guWhiteboard::VisionDetectionFeature::coordinate () inline
Definition at line 172 of file VisionDetectionFeature.hpp.
References wb_vision_detection_feature::coordinate.
Referenced by VisionDetectionFeature(), description(), operator=(), operator==(), and to_string().
coordinate() [2/2]
const PolarCoordinate & guWhiteboard::VisionDetectionFeature::coordinate () const inline
Definition at line 177 of file VisionDetectionFeature.hpp.
References wb_vision_detection_feature::coordinate.
description()
std::string guWhiteboard::VisionDetectionFeature::description () inline
USE_WB_VISION_DETECTION_FEATURE_C_CONVERSION
Definition at line 196 of file VisionDetectionFeature.hpp.
References coordinate(), guWhiteboard::PolarCoordinate::description(), featureType(), FeatureTypeCircle, FeatureTypeL, FeatureTypeT, FeatureTypeX, NUMBER_OF_FEATURE_TYPES, VISION_DETECTION_FEATURE_DESC_BUFFER_SIZE, and wb_vision_detection_feature_description().
featureType() [1/2]
enum FeatureTypes & guWhiteboard::VisionDetectionFeature::featureType () inline
Definition at line 157 of file VisionDetectionFeature.hpp.
References wb_vision_detection_feature::featureType.
Referenced by VisionDetectionFeature(), description(), operator=(), operator==(), and to_string().
featureType() [2/2]
enum FeatureTypes & guWhiteboard::VisionDetectionFeature::featureType () const inline
Definition at line 162 of file VisionDetectionFeature.hpp.
References wb_vision_detection_feature::featureType.
from_string()
void guWhiteboard::VisionDetectionFeature::from_string (const std::string & t_str) inline
USE_WB_VISION_DETECTION_FEATURE_C_CONVERSION
Definition at line 282 of file VisionDetectionFeature.hpp.
References FeatureTypeCircle, FeatureTypeL, FeatureTypeT, FeatureTypeX, guWhiteboard::PolarCoordinate::from_string(), NUMBER_OF_FEATURE_TYPES, set_coordinate(), set_featureType(), and VISION_DETECTION_FEATURE_DESC_BUFFER_SIZE.
Referenced by VisionDetectionFeature(), and guWhiteboard::VisionDetectionFeatureArray::from_string().
operator!=() [1/2]
bool guWhiteboard::VisionDetectionFeature::operator!= (const VisionDetectionFeature & t_other) const inline
Definition at line 142 of file VisionDetectionFeature.hpp.
operator!=() [2/2]
bool guWhiteboard::VisionDetectionFeature::operator!= (const wb_vision_detection_feature & t_other) const inline
Definition at line 152 of file VisionDetectionFeature.hpp.
operator=() [1/2]
VisionDetectionFeature & guWhiteboard::VisionDetectionFeature::operator= (const struct wb_vision_detection_feature & t_other) inline
Copy Assignment Operator.
Definition at line 131 of file VisionDetectionFeature.hpp.
References wb_vision_detection_feature::coordinate, and wb_vision_detection_feature::featureType.
operator=() [2/2]
VisionDetectionFeature & guWhiteboard::VisionDetectionFeature::operator= (const VisionDetectionFeature & t_other) inline
Copy Assignment Operator.
Definition at line 123 of file VisionDetectionFeature.hpp.
References coordinate(), and featureType().
operator==() [1/2]
bool guWhiteboard::VisionDetectionFeature::operator== (const VisionDetectionFeature & t_other) const inline
Definition at line 136 of file VisionDetectionFeature.hpp.
References coordinate(), and featureType().
operator==() [2/2]
bool guWhiteboard::VisionDetectionFeature::operator== (const wb_vision_detection_feature & t_other) const inline
Definition at line 147 of file VisionDetectionFeature.hpp.
References VisionDetectionFeature().
set_coordinate()
void guWhiteboard::VisionDetectionFeature::set_coordinate (const PolarCoordinate & t_newValue) inline
Definition at line 182 of file VisionDetectionFeature.hpp.
References wb_vision_detection_feature::coordinate.
Referenced by from_string().
set_featureType()
void guWhiteboard::VisionDetectionFeature::set_featureType (const enum FeatureTypes & t_newValue) inline
Definition at line 167 of file VisionDetectionFeature.hpp.
References wb_vision_detection_feature::featureType.
Referenced by from_string().
to_string()
std::string guWhiteboard::VisionDetectionFeature::to_string () inline
USE_WB_VISION_DETECTION_FEATURE_C_CONVERSION
Definition at line 237 of file VisionDetectionFeature.hpp.
References coordinate(), featureType(), FeatureTypeCircle, FeatureTypeL, FeatureTypeT, FeatureTypeX, NUMBER_OF_FEATURE_TYPES, guWhiteboard::PolarCoordinate::to_string(), VISION_DETECTION_FEATURE_TO_STRING_BUFFER_SIZE, and wb_vision_detection_feature_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/VisionDetectionFeature.hpp