gusimplewhiteboard: guWhiteboard::MachineFilteredLocalisationVision Class Reference
guWhiteboard::MachineFilteredLocalisationVision Class Reference
Provides a C++ wrapper around wb_machine_filtered_localisation_vision.
#include <MachineFilteredLocalisationVision.hpp>
Public Member Functions
MachineFilteredLocalisationVision (uint8_t t_numberOfSightings=0, const struct wb_landmark_sighting t_sightings[12]=NULLPTR)
Create a new MachineFilteredLocalisationVision.
MachineFilteredLocalisationVision (const MachineFilteredLocalisationVision &t_other)
Copy Constructor.
MachineFilteredLocalisationVision (const struct wb_machine_filtered_localisation_vision &t_other)
Copy Constructor.
MachineFilteredLocalisationVision & operator= (const MachineFilteredLocalisationVision &t_other)
Copy Assignment Operator.
MachineFilteredLocalisationVision & operator= (const struct wb_machine_filtered_localisation_vision &t_other)
Copy Assignment Operator.
bool operator== (const MachineFilteredLocalisationVision &t_other) const
bool operator!= (const MachineFilteredLocalisationVision &t_other) const
bool operator== (const wb_machine_filtered_localisation_vision &t_other) const
bool operator!= (const wb_machine_filtered_localisation_vision &t_other) const
uint8_t & numberOfSightings ()
const uint8_t & numberOfSightings () const
void set_numberOfSightings (const uint8_t &t_newValue)
const LandmarkSighting * sightings () const
size_t sightings_size () const
LandmarkSighting & sightings (int t_i)
const LandmarkSighting & sightings (int t_i) const
void set_sightings (const LandmarkSighting *t_newValue)
void set_sightings (const LandmarkSighting &t_newValue, int t_i)
MachineFilteredLocalisationVision (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
int firstSighting (LandmarkSightingType sightingType)
WHITEBOARD_POSTER_STRING_CONVERSION.
int ball ()
int firstGenericGoalPost ()
int leftGoalPost ()
int rightGoalPost ()
int goal ()
int lineHorizon ()
int cornerHorizon ()
int horizon ()
int line ()
int cornerLine ()
int tLine ()
int crossLine ()
Additional Inherited Members
Public Attributes inherited from wb_machine_filtered_localisation_vision
uint8_t numberOfSightings
The number of sightings in sightings.
struct wb_landmark_sighting sightings [12]
All sightings.
Detailed Description
Provides a C++ wrapper around wb_machine_filtered_localisation_vision.
Definition at line 85 of file MachineFilteredLocalisationVision.hpp.
Constructor & Destructor Documentation
MachineFilteredLocalisationVision() [1/4]
guWhiteboard::MachineFilteredLocalisationVision::MachineFilteredLocalisationVision (uint8_t t_numberOfSightings = 0, const struct wb_landmark_sighting t_sightings[12] = NULLPTR) inline
Create a new MachineFilteredLocalisationVision.
Definition at line 107 of file MachineFilteredLocalisationVision.hpp.
Referenced by operator==().
MachineFilteredLocalisationVision() [2/4]
guWhiteboard::MachineFilteredLocalisationVision::MachineFilteredLocalisationVision (const MachineFilteredLocalisationVision & t_other) inline
Copy Constructor.
Definition at line 114 of file MachineFilteredLocalisationVision.hpp.
References numberOfSightings(), and sightings().
MachineFilteredLocalisationVision() [3/4]
guWhiteboard::MachineFilteredLocalisationVision::MachineFilteredLocalisationVision (const struct wb_machine_filtered_localisation_vision & t_other) inline
Copy Constructor.
Definition at line 121 of file MachineFilteredLocalisationVision.hpp.
References wb_machine_filtered_localisation_vision::numberOfSightings, and wb_machine_filtered_localisation_vision::sightings.
MachineFilteredLocalisationVision() [4/4]
guWhiteboard::MachineFilteredLocalisationVision::MachineFilteredLocalisationVision (const std::string & t_str) inline
String Constructor.
Definition at line 218 of file MachineFilteredLocalisationVision.hpp.
References from_string().
Member Function Documentation
ball()
int guWhiteboard::MachineFilteredLocalisationVision::ball () inline
Definition at line 442 of file MachineFilteredLocalisationVision.hpp.
References BallSightingType, and firstSighting().
cornerHorizon()
int guWhiteboard::MachineFilteredLocalisationVision::cornerHorizon () inline
Definition at line 470 of file MachineFilteredLocalisationVision.hpp.
References CornerHorizonSightingType, and firstSighting().
Referenced by horizon().
cornerLine()
int guWhiteboard::MachineFilteredLocalisationVision::cornerLine () inline
Definition at line 485 of file MachineFilteredLocalisationVision.hpp.
References CornerLineSightingType, and firstSighting().
crossLine()
int guWhiteboard::MachineFilteredLocalisationVision::crossLine () inline
Definition at line 495 of file MachineFilteredLocalisationVision.hpp.
References CrossLineSightingType, and firstSighting().
description()
std::string guWhiteboard::MachineFilteredLocalisationVision::description () inline
USE_WB_MACHINE_FILTERED_LOCALISATION_VISION_C_CONVERSION
Definition at line 223 of file MachineFilteredLocalisationVision.hpp.
References description(), MACHINE_FILTERED_LOCALISATION_VISION_DESC_BUFFER_SIZE, MACHINE_FILTERED_LOCALISATION_VISION_SIGHTINGS_ARRAY_SIZE, numberOfSightings(), sightings(), and wb_machine_filtered_localisation_vision_description().
Referenced by description().
firstGenericGoalPost()
int guWhiteboard::MachineFilteredLocalisationVision::firstGenericGoalPost () inline
Definition at line 447 of file MachineFilteredLocalisationVision.hpp.
References firstSighting(), and GenericGoalPostSightingType.
firstSighting()
int guWhiteboard::MachineFilteredLocalisationVision::firstSighting (LandmarkSightingType sightingType) inline
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 430 of file MachineFilteredLocalisationVision.hpp.
References numberOfSightings(), sightings(), guWhiteboard::LandmarkSighting::sightingType(), and wb_landmark_sighting::sightingType.
Referenced by ball(), cornerHorizon(), cornerLine(), crossLine(), firstGenericGoalPost(), goal(), leftGoalPost(), line(), lineHorizon(), rightGoalPost(), and tLine().
from_string()
void guWhiteboard::MachineFilteredLocalisationVision::from_string (const std::string & t_str) inline
USE_WB_MACHINE_FILTERED_LOCALISATION_VISION_C_CONVERSION
Definition at line 269 of file MachineFilteredLocalisationVision.hpp.
References guWhiteboard::LandmarkSighting::from_string(), MACHINE_FILTERED_LOCALISATION_VISION_DESC_BUFFER_SIZE, MACHINE_FILTERED_LOCALISATION_VISION_SIGHTINGS_ARRAY_SIZE, set_numberOfSightings(), and set_sightings().
Referenced by MachineFilteredLocalisationVision().
goal()
int guWhiteboard::MachineFilteredLocalisationVision::goal () inline
Definition at line 461 of file MachineFilteredLocalisationVision.hpp.
References firstSighting(), and GoalLandmarkSightingType.
horizon()
int guWhiteboard::MachineFilteredLocalisationVision::horizon () inline
Definition at line 475 of file MachineFilteredLocalisationVision.hpp.
References cornerHorizon(), and lineHorizon().
leftGoalPost()
int guWhiteboard::MachineFilteredLocalisationVision::leftGoalPost () inline
Definition at line 452 of file MachineFilteredLocalisationVision.hpp.
References firstSighting(), and LeftGoalPostSightingType.
line()
int guWhiteboard::MachineFilteredLocalisationVision::line () inline
Definition at line 480 of file MachineFilteredLocalisationVision.hpp.
References firstSighting(), and StraightLineSightingType.
lineHorizon()
int guWhiteboard::MachineFilteredLocalisationVision::lineHorizon () inline
Definition at line 465 of file MachineFilteredLocalisationVision.hpp.
References firstSighting(), and LineHorizonSightingType.
Referenced by horizon().
numberOfSightings() [1/2]
uint8_t & guWhiteboard::MachineFilteredLocalisationVision::numberOfSightings () inline
Definition at line 169 of file MachineFilteredLocalisationVision.hpp.
References wb_machine_filtered_localisation_vision::numberOfSightings.
Referenced by MachineFilteredLocalisationVision(), description(), firstSighting(), operator=(), operator==(), and to_string().
numberOfSightings() [2/2]
const uint8_t & guWhiteboard::MachineFilteredLocalisationVision::numberOfSightings () const inline
Definition at line 174 of file MachineFilteredLocalisationVision.hpp.
References wb_machine_filtered_localisation_vision::numberOfSightings.
operator!=() [1/2]
bool guWhiteboard::MachineFilteredLocalisationVision::operator!= (const MachineFilteredLocalisationVision & t_other) const inline
Definition at line 154 of file MachineFilteredLocalisationVision.hpp.
operator!=() [2/2]
bool guWhiteboard::MachineFilteredLocalisationVision::operator!= (const wb_machine_filtered_localisation_vision & t_other) const inline
Definition at line 164 of file MachineFilteredLocalisationVision.hpp.
operator=() [1/2]
MachineFilteredLocalisationVision & guWhiteboard::MachineFilteredLocalisationVision::operator= (const MachineFilteredLocalisationVision & t_other) inline
Copy Assignment Operator.
Definition at line 128 of file MachineFilteredLocalisationVision.hpp.
References numberOfSightings(), and sightings().
operator=() [2/2]
MachineFilteredLocalisationVision & guWhiteboard::MachineFilteredLocalisationVision::operator= (const struct wb_machine_filtered_localisation_vision & t_other) inline
Copy Assignment Operator.
Definition at line 136 of file MachineFilteredLocalisationVision.hpp.
References wb_machine_filtered_localisation_vision::numberOfSightings, and wb_machine_filtered_localisation_vision::sightings.
operator==() [1/2]
bool guWhiteboard::MachineFilteredLocalisationVision::operator== (const MachineFilteredLocalisationVision & t_other) const inline
Definition at line 141 of file MachineFilteredLocalisationVision.hpp.
References numberOfSightings(), and sightings().
operator==() [2/2]
bool guWhiteboard::MachineFilteredLocalisationVision::operator== (const wb_machine_filtered_localisation_vision & t_other) const inline
Definition at line 159 of file MachineFilteredLocalisationVision.hpp.
References MachineFilteredLocalisationVision().
rightGoalPost()
int guWhiteboard::MachineFilteredLocalisationVision::rightGoalPost () inline
Definition at line 457 of file MachineFilteredLocalisationVision.hpp.
References firstSighting(), and RightGoalPostSightingType.
set_numberOfSightings()
void guWhiteboard::MachineFilteredLocalisationVision::set_numberOfSightings (const uint8_t & t_newValue) inline
Definition at line 179 of file MachineFilteredLocalisationVision.hpp.
References wb_machine_filtered_localisation_vision::numberOfSightings.
Referenced by from_string().
set_sightings() [1/2]
void guWhiteboard::MachineFilteredLocalisationVision::set_sightings (const LandmarkSighting & t_newValue, int t_i) inline
Definition at line 209 of file MachineFilteredLocalisationVision.hpp.
References wb_machine_filtered_localisation_vision::sightings.
set_sightings() [2/2]
void guWhiteboard::MachineFilteredLocalisationVision::set_sightings (const LandmarkSighting * t_newValue) inline
Definition at line 204 of file MachineFilteredLocalisationVision.hpp.
References MACHINE_FILTERED_LOCALISATION_VISION_SIGHTINGS_ARRAY_SIZE, and wb_machine_filtered_localisation_vision::sightings.
Referenced by from_string().
sightings() [1/3]
const LandmarkSighting * guWhiteboard::MachineFilteredLocalisationVision::sightings () const inline
Definition at line 184 of file MachineFilteredLocalisationVision.hpp.
References wb_machine_filtered_localisation_vision::sightings.
Referenced by MachineFilteredLocalisationVision(), description(), firstSighting(), operator=(), operator==(), and to_string().
sightings() [2/3]
LandmarkSighting & guWhiteboard::MachineFilteredLocalisationVision::sightings (int t_i) inline
Definition at line 194 of file MachineFilteredLocalisationVision.hpp.
References wb_machine_filtered_localisation_vision::sightings.
sightings() [3/3]
const LandmarkSighting & guWhiteboard::MachineFilteredLocalisationVision::sightings (int t_i) const inline
Definition at line 199 of file MachineFilteredLocalisationVision.hpp.
References wb_machine_filtered_localisation_vision::sightings.
sightings_size()
size_t guWhiteboard::MachineFilteredLocalisationVision::sightings_size () const inline
Definition at line 189 of file MachineFilteredLocalisationVision.hpp.
References MACHINE_FILTERED_LOCALISATION_VISION_SIGHTINGS_ARRAY_SIZE.
tLine()
int guWhiteboard::MachineFilteredLocalisationVision::tLine () inline
Definition at line 490 of file MachineFilteredLocalisationVision.hpp.
References firstSighting(), and TIntersectionLineSightingType.
to_string()
std::string guWhiteboard::MachineFilteredLocalisationVision::to_string () inline
USE_WB_MACHINE_FILTERED_LOCALISATION_VISION_C_CONVERSION
Definition at line 244 of file MachineFilteredLocalisationVision.hpp.
References MACHINE_FILTERED_LOCALISATION_VISION_SIGHTINGS_ARRAY_SIZE, MACHINE_FILTERED_LOCALISATION_VISION_TO_STRING_BUFFER_SIZE, numberOfSightings(), sightings(), to_string(), and wb_machine_filtered_localisation_vision_to_string().
Referenced by to_string().
The documentation for this class was generated from the following file:
typeClassDefs/MachineFilteredLocalisationVision.hpp