gusimplewhiteboard: guWhiteboard::VisionLines Class Reference
guWhiteboard::VisionLines Class Reference
Provides a C++ wrapper around wb_vision_lines.
#include <VisionLines.hpp>
Public Member Functions
VisionLines (const struct wb_vision_line t_lines[7]=NULLPTR, uint8_t t_numLines=0, uint64_t t_frameNumber=0, uint16_t t_res_width=0, uint16_t t_res_height=0)
Create a new VisionLines.
VisionLines (const VisionLines &t_other)
Copy Constructor.
VisionLines (const struct wb_vision_lines &t_other)
Copy Constructor.
VisionLines & operator= (const VisionLines &t_other)
Copy Assignment Operator.
VisionLines & operator= (const struct wb_vision_lines &t_other)
Copy Assignment Operator.
bool operator== (const VisionLines &t_other) const
bool operator!= (const VisionLines &t_other) const
bool operator== (const wb_vision_lines &t_other) const
bool operator!= (const wb_vision_lines &t_other) const
const VisionLine * lines () const
size_t lines_size () const
VisionLine & lines (int t_i)
const VisionLine & lines (int t_i) const
void set_lines (const VisionLine *t_newValue)
void set_lines (const VisionLine &t_newValue, int t_i)
uint8_t & numLines ()
const uint8_t & numLines () const
void set_numLines (const uint8_t &t_newValue)
uint64_t & frameNumber ()
const uint64_t & frameNumber () const
void set_frameNumber (const uint64_t &t_newValue)
uint16_t & res_width ()
const uint16_t & res_width () const
void set_res_width (const uint16_t &t_newValue)
uint16_t & res_height ()
const uint16_t & res_height () const
void set_res_height (const uint16_t &t_newValue)
VisionLines (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_vision_lines
struct wb_vision_line lines [7]
Lines reported from the camera.
uint8_t numLines
The number of lines reported on the camera.
uint64_t frameNumber
The frame number that these lines were seen in.
uint16_t res_width
The resolution width.
uint16_t res_height
The resolution height.
Detailed Description
Provides a C++ wrapper around wb_vision_lines.
Definition at line 85 of file VisionLines.hpp.
Constructor & Destructor Documentation
VisionLines() [1/4]
guWhiteboard::VisionLines::VisionLines (const struct wb_vision_line t_lines[7] = NULLPTR, uint8_t t_numLines = 0, uint64_t t_frameNumber = 0, uint16_t t_res_width = 0, uint16_t t_res_height = 0) inline
Create a new VisionLines.
Definition at line 110 of file VisionLines.hpp.
Referenced by operator==().
VisionLines() [2/4]
guWhiteboard::VisionLines::VisionLines (const VisionLines & t_other) inline
Copy Constructor.
Definition at line 117 of file VisionLines.hpp.
References frameNumber(), lines(), numLines(), res_height(), and res_width().
VisionLines() [3/4]
guWhiteboard::VisionLines::VisionLines (const struct wb_vision_lines & t_other) inline
Copy Constructor.
Definition at line 124 of file VisionLines.hpp.
References wb_vision_lines::frameNumber, wb_vision_lines::lines, wb_vision_lines::numLines, wb_vision_lines::res_height, and wb_vision_lines::res_width.
VisionLines() [4/4]
guWhiteboard::VisionLines::VisionLines (const std::string & t_str) inline
String Constructor.
Definition at line 269 of file VisionLines.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::VisionLines::description () inline
USE_WB_VISION_LINES_C_CONVERSION
Definition at line 274 of file VisionLines.hpp.
References description(), frameNumber(), lines(), numLines(), res_height(), res_width(), VISION_LINES_DESC_BUFFER_SIZE, VISION_LINES_LINES_ARRAY_SIZE, and wb_vision_lines_description().
Referenced by description().
frameNumber() [1/2]
uint64_t & guWhiteboard::VisionLines::frameNumber () inline
Definition at line 220 of file VisionLines.hpp.
References wb_vision_lines::frameNumber.
Referenced by VisionLines(), description(), operator=(), operator==(), and to_string().
frameNumber() [2/2]
const uint64_t & guWhiteboard::VisionLines::frameNumber () const inline
Definition at line 225 of file VisionLines.hpp.
References wb_vision_lines::frameNumber.
from_string()
void guWhiteboard::VisionLines::from_string (const std::string & t_str) inline
USE_WB_VISION_LINES_C_CONVERSION
Definition at line 332 of file VisionLines.hpp.
References guWhiteboard::VisionLine::from_string(), set_frameNumber(), set_lines(), set_numLines(), set_res_height(), set_res_width(), VISION_LINES_DESC_BUFFER_SIZE, and VISION_LINES_LINES_ARRAY_SIZE.
Referenced by VisionLines().
lines() [1/3]
const VisionLine * guWhiteboard::VisionLines::lines () const inline
Definition at line 175 of file VisionLines.hpp.
References wb_vision_lines::lines.
Referenced by VisionLines(), description(), operator=(), operator==(), and to_string().
lines() [2/3]
VisionLine & guWhiteboard::VisionLines::lines (int t_i) inline
Definition at line 185 of file VisionLines.hpp.
References wb_vision_lines::lines.
lines() [3/3]
const VisionLine & guWhiteboard::VisionLines::lines (int t_i) const inline
Definition at line 190 of file VisionLines.hpp.
References wb_vision_lines::lines.
lines_size()
size_t guWhiteboard::VisionLines::lines_size () const inline
Definition at line 180 of file VisionLines.hpp.
References VISION_LINES_LINES_ARRAY_SIZE.
numLines() [1/2]
uint8_t & guWhiteboard::VisionLines::numLines () inline
Definition at line 205 of file VisionLines.hpp.
References wb_vision_lines::numLines.
Referenced by VisionLines(), description(), operator=(), operator==(), and to_string().
numLines() [2/2]
const uint8_t & guWhiteboard::VisionLines::numLines () const inline
Definition at line 210 of file VisionLines.hpp.
References wb_vision_lines::numLines.
operator!=() [1/2]
bool guWhiteboard::VisionLines::operator!= (const VisionLines & t_other) const inline
Definition at line 160 of file VisionLines.hpp.
operator!=() [2/2]
bool guWhiteboard::VisionLines::operator!= (const wb_vision_lines & t_other) const inline
Definition at line 170 of file VisionLines.hpp.
operator=() [1/2]
VisionLines & guWhiteboard::VisionLines::operator= (const struct wb_vision_lines & t_other) inline
Copy Assignment Operator.
Definition at line 139 of file VisionLines.hpp.
References wb_vision_lines::frameNumber, wb_vision_lines::lines, wb_vision_lines::numLines, wb_vision_lines::res_height, and wb_vision_lines::res_width.
operator=() [2/2]
VisionLines & guWhiteboard::VisionLines::operator= (const VisionLines & t_other) inline
Copy Assignment Operator.
Definition at line 131 of file VisionLines.hpp.
References frameNumber(), lines(), numLines(), res_height(), and res_width().
operator==() [1/2]
bool guWhiteboard::VisionLines::operator== (const VisionLines & t_other) const inline
Definition at line 144 of file VisionLines.hpp.
References frameNumber(), lines(), numLines(), res_height(), and res_width().
operator==() [2/2]
bool guWhiteboard::VisionLines::operator== (const wb_vision_lines & t_other) const inline
Definition at line 165 of file VisionLines.hpp.
References VisionLines().
res_height() [1/2]
uint16_t & guWhiteboard::VisionLines::res_height () inline
Definition at line 250 of file VisionLines.hpp.
References wb_vision_lines::res_height.
Referenced by VisionLines(), description(), operator=(), operator==(), and to_string().
res_height() [2/2]
const uint16_t & guWhiteboard::VisionLines::res_height () const inline
Definition at line 255 of file VisionLines.hpp.
References wb_vision_lines::res_height.
res_width() [1/2]
uint16_t & guWhiteboard::VisionLines::res_width () inline
Definition at line 235 of file VisionLines.hpp.
References wb_vision_lines::res_width.
Referenced by VisionLines(), description(), operator=(), operator==(), and to_string().
res_width() [2/2]
const uint16_t & guWhiteboard::VisionLines::res_width () const inline
Definition at line 240 of file VisionLines.hpp.
References wb_vision_lines::res_width.
set_frameNumber()
void guWhiteboard::VisionLines::set_frameNumber (const uint64_t & t_newValue) inline
Definition at line 230 of file VisionLines.hpp.
References wb_vision_lines::frameNumber.
Referenced by from_string().
set_lines() [1/2]
void guWhiteboard::VisionLines::set_lines (const VisionLine & t_newValue, int t_i) inline
Definition at line 200 of file VisionLines.hpp.
References wb_vision_lines::lines.
set_lines() [2/2]
void guWhiteboard::VisionLines::set_lines (const VisionLine * t_newValue) inline
Definition at line 195 of file VisionLines.hpp.
References wb_vision_lines::lines, and VISION_LINES_LINES_ARRAY_SIZE.
Referenced by from_string().
set_numLines()
void guWhiteboard::VisionLines::set_numLines (const uint8_t & t_newValue) inline
Definition at line 215 of file VisionLines.hpp.
References wb_vision_lines::numLines.
Referenced by from_string().
set_res_height()
void guWhiteboard::VisionLines::set_res_height (const uint16_t & t_newValue) inline
Definition at line 260 of file VisionLines.hpp.
References wb_vision_lines::res_height.
Referenced by from_string().
set_res_width()
void guWhiteboard::VisionLines::set_res_width (const uint16_t & t_newValue) inline
Definition at line 245 of file VisionLines.hpp.
References wb_vision_lines::res_width.
Referenced by from_string().
to_string()
std::string guWhiteboard::VisionLines::to_string () inline
USE_WB_VISION_LINES_C_CONVERSION
Definition at line 301 of file VisionLines.hpp.
References frameNumber(), lines(), numLines(), res_height(), res_width(), to_string(), VISION_LINES_LINES_ARRAY_SIZE, VISION_LINES_TO_STRING_BUFFER_SIZE, and wb_vision_lines_to_string().
Referenced by to_string().
The documentation for this class was generated from the following file:
typeClassDefs/VisionLines.hpp