gusimplewhiteboard: guWhiteboard::AdjustPositionConfidence Class Reference
guWhiteboard::AdjustPositionConfidence Class Reference
Provides a C++ wrapper around wb_adjust_position_confidence.
#include <AdjustPositionConfidence.hpp>
Public Member Functions
AdjustPositionConfidence (int8_t t_adjustment=0)
Create a new AdjustPositionConfidence.
AdjustPositionConfidence (const AdjustPositionConfidence &t_other)
Copy Constructor.
AdjustPositionConfidence (const struct wb_adjust_position_confidence &t_other)
Copy Constructor.
AdjustPositionConfidence & operator= (const AdjustPositionConfidence &t_other)
Copy Assignment Operator.
AdjustPositionConfidence & operator= (const struct wb_adjust_position_confidence &t_other)
Copy Assignment Operator.
bool operator== (const AdjustPositionConfidence &t_other) const
bool operator!= (const AdjustPositionConfidence &t_other) const
bool operator== (const wb_adjust_position_confidence &t_other) const
bool operator!= (const wb_adjust_position_confidence &t_other) const
int8_t & adjustment ()
const int8_t & adjustment () const
void set_adjustment (const int8_t &t_newValue)
AdjustPositionConfidence (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_adjust_position_confidence
int8_t adjustment
Change the confidence as a signed percentage (-100% -> 100%)
Detailed Description
Provides a C++ wrapper around wb_adjust_position_confidence.
Definition at line 83 of file AdjustPositionConfidence.hpp.
Constructor & Destructor Documentation
AdjustPositionConfidence() [1/4]
guWhiteboard::AdjustPositionConfidence::AdjustPositionConfidence (int8_t t_adjustment = 0) inline
Create a new AdjustPositionConfidence.
Definition at line 99 of file AdjustPositionConfidence.hpp.
Referenced by operator==().
AdjustPositionConfidence() [2/4]
guWhiteboard::AdjustPositionConfidence::AdjustPositionConfidence (const AdjustPositionConfidence & t_other) inline
Copy Constructor.
Definition at line 106 of file AdjustPositionConfidence.hpp.
References adjustment().
AdjustPositionConfidence() [3/4]
guWhiteboard::AdjustPositionConfidence::AdjustPositionConfidence (const struct wb_adjust_position_confidence & t_other) inline
Copy Constructor.
Definition at line 113 of file AdjustPositionConfidence.hpp.
References wb_adjust_position_confidence::adjustment.
AdjustPositionConfidence() [4/4]
guWhiteboard::AdjustPositionConfidence::AdjustPositionConfidence (const std::string & t_str) inline
String Constructor.
Definition at line 172 of file AdjustPositionConfidence.hpp.
References from_string().
Member Function Documentation
adjustment() [1/2]
int8_t & guWhiteboard::AdjustPositionConfidence::adjustment () inline
Definition at line 153 of file AdjustPositionConfidence.hpp.
References wb_adjust_position_confidence::adjustment.
Referenced by AdjustPositionConfidence(), description(), operator=(), operator==(), and to_string().
adjustment() [2/2]
const int8_t & guWhiteboard::AdjustPositionConfidence::adjustment () const inline
Definition at line 158 of file AdjustPositionConfidence.hpp.
References wb_adjust_position_confidence::adjustment.
description()
std::string guWhiteboard::AdjustPositionConfidence::description () inline
USE_WB_ADJUST_POSITION_CONFIDENCE_C_CONVERSION
Definition at line 177 of file AdjustPositionConfidence.hpp.
References ADJUST_POSITION_CONFIDENCE_DESC_BUFFER_SIZE, adjustment(), and wb_adjust_position_confidence_description().
from_string()
void guWhiteboard::AdjustPositionConfidence::from_string (const std::string & t_str) inline
USE_WB_ADJUST_POSITION_CONFIDENCE_C_CONVERSION
Definition at line 207 of file AdjustPositionConfidence.hpp.
References ADJUST_POSITION_CONFIDENCE_DESC_BUFFER_SIZE, and set_adjustment().
Referenced by AdjustPositionConfidence().
operator!=() [1/2]
bool guWhiteboard::AdjustPositionConfidence::operator!= (const AdjustPositionConfidence & t_other) const inline
Definition at line 138 of file AdjustPositionConfidence.hpp.
operator!=() [2/2]
bool guWhiteboard::AdjustPositionConfidence::operator!= (const wb_adjust_position_confidence & t_other) const inline
Definition at line 148 of file AdjustPositionConfidence.hpp.
operator=() [1/2]
AdjustPositionConfidence & guWhiteboard::AdjustPositionConfidence::operator= (const AdjustPositionConfidence & t_other) inline
Copy Assignment Operator.
Definition at line 120 of file AdjustPositionConfidence.hpp.
References adjustment().
operator=() [2/2]
AdjustPositionConfidence & guWhiteboard::AdjustPositionConfidence::operator= (const struct wb_adjust_position_confidence & t_other) inline
Copy Assignment Operator.
Definition at line 128 of file AdjustPositionConfidence.hpp.
References wb_adjust_position_confidence::adjustment.
operator==() [1/2]
bool guWhiteboard::AdjustPositionConfidence::operator== (const AdjustPositionConfidence & t_other) const inline
Definition at line 133 of file AdjustPositionConfidence.hpp.
References adjustment().
operator==() [2/2]
bool guWhiteboard::AdjustPositionConfidence::operator== (const wb_adjust_position_confidence & t_other) const inline
Definition at line 143 of file AdjustPositionConfidence.hpp.
References AdjustPositionConfidence().
set_adjustment()
void guWhiteboard::AdjustPositionConfidence::set_adjustment (const int8_t & t_newValue) inline
Definition at line 163 of file AdjustPositionConfidence.hpp.
References wb_adjust_position_confidence::adjustment.
Referenced by from_string().
to_string()
std::string guWhiteboard::AdjustPositionConfidence::to_string () inline
USE_WB_ADJUST_POSITION_CONFIDENCE_C_CONVERSION
Definition at line 190 of file AdjustPositionConfidence.hpp.
References ADJUST_POSITION_CONFIDENCE_TO_STRING_BUFFER_SIZE, adjustment(), and wb_adjust_position_confidence_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/AdjustPositionConfidence.hpp