gusimplewhiteboard: guWhiteboard::TeleoperationControlVR Class Reference
guWhiteboard::TeleoperationControlVR Class Reference
Provides a C++ wrapper around wb_teleoperation_control_v_r.
#include <TeleoperationControlVR.hpp>
Public Member Functions
TeleoperationControlVR (uint8_t t_ip=0, int32_t t_action=0, float t_HeadYaw=0, float t_HeadPitch=0, int32_t t_stance=0, int32_t t_streamType=0, int32_t t_selectedCamera=0, std::string t_sayString="", int32_t t_walk=0, int32_t t_turn=0, int32_t t_timestamp=0)
Create a new TeleoperationControlVR.
TeleoperationControlVR (const TeleoperationControlVR &t_other)
Copy Constructor.
TeleoperationControlVR (const struct wb_teleoperation_control_v_r &t_other)
Copy Constructor.
TeleoperationControlVR & operator= (const TeleoperationControlVR &t_other)
Copy Assignment Operator.
TeleoperationControlVR & operator= (const struct wb_teleoperation_control_v_r &t_other)
Copy Assignment Operator.
bool operator== (const TeleoperationControlVR &t_other) const
bool operator!= (const TeleoperationControlVR &t_other) const
bool operator== (const wb_teleoperation_control_v_r &t_other) const
bool operator!= (const wb_teleoperation_control_v_r &t_other) const
uint8_t & ip ()
const uint8_t & ip () const
void set_ip (const uint8_t &t_newValue)
int32_t & action ()
const int32_t & action () const
void set_action (const int32_t &t_newValue)
float & HeadYaw ()
const float & HeadYaw () const
void set_HeadYaw (const float &t_newValue)
float & HeadPitch ()
const float & HeadPitch () const
void set_HeadPitch (const float &t_newValue)
int32_t & stance ()
const int32_t & stance () const
void set_stance (const int32_t &t_newValue)
int32_t & streamType ()
const int32_t & streamType () const
void set_streamType (const int32_t &t_newValue)
int32_t & selectedCamera ()
const int32_t & selectedCamera () const
void set_selectedCamera (const int32_t &t_newValue)
const char * sayString () const
size_t sayString_size () const
char & sayString (int t_i)
const char & sayString (int t_i) const
void set_sayString (const char *t_newValue)
int32_t & walk ()
const int32_t & walk () const
void set_walk (const int32_t &t_newValue)
int32_t & turn ()
const int32_t & turn () const
void set_turn (const int32_t &t_newValue)
int32_t & timestamp ()
const int32_t & timestamp () const
void set_timestamp (const int32_t &t_newValue)
TeleoperationControlVR (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_teleoperation_control_v_r
uint8_t ip
Last octet of IP address.
int32_t action
Use guWhiteboard::Motions::action enum values!
float HeadYaw
Head pos in RAD.
float HeadPitch
Head pos in RAD.
int32_t stance
guWhiteboard::Motions::stance
int32_t streamType
Use enum StreamingType (Vision_Control.h)
int32_t selectedCamera
VisionCamera.
char sayString [30]
String passed to Say_t.
int32_t walk
Walk value.
int32_t turn
Turn value.
int32_t timestamp
Timestamp for task distinguishing.
Detailed Description
Provides a C++ wrapper around wb_teleoperation_control_v_r.
Definition at line 84 of file TeleoperationControlVR.hpp.
Constructor & Destructor Documentation
TeleoperationControlVR() [1/4]
guWhiteboard::TeleoperationControlVR::TeleoperationControlVR (uint8_t t_ip = 0, int32_t t_action = 0, float t_HeadYaw = 0, float t_HeadPitch = 0, int32_t t_stance = 0, int32_t t_streamType = 0, int32_t t_selectedCamera = 0, std::string t_sayString = "", int32_t t_walk = 0, int32_t t_turn = 0, int32_t t_timestamp = 0) inline
Create a new TeleoperationControlVR.
Definition at line 110 of file TeleoperationControlVR.hpp.
Referenced by operator==().
TeleoperationControlVR() [2/4]
guWhiteboard::TeleoperationControlVR::TeleoperationControlVR (const TeleoperationControlVR & t_other) inline
Copy Constructor.
Definition at line 117 of file TeleoperationControlVR.hpp.
References action(), HeadPitch(), HeadYaw(), ip(), sayString(), selectedCamera(), stance(), streamType(), timestamp(), turn(), and walk().
TeleoperationControlVR() [3/4]
guWhiteboard::TeleoperationControlVR::TeleoperationControlVR (const struct wb_teleoperation_control_v_r & t_other) inline
Copy Constructor.
Definition at line 124 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::action, wb_teleoperation_control_v_r::HeadPitch, wb_teleoperation_control_v_r::HeadYaw, wb_teleoperation_control_v_r::ip, wb_teleoperation_control_v_r::sayString, wb_teleoperation_control_v_r::selectedCamera, wb_teleoperation_control_v_r::stance, wb_teleoperation_control_v_r::streamType, wb_teleoperation_control_v_r::timestamp, wb_teleoperation_control_v_r::turn, and wb_teleoperation_control_v_r::walk.
TeleoperationControlVR() [4/4]
guWhiteboard::TeleoperationControlVR::TeleoperationControlVR (const std::string & t_str) inline
String Constructor.
Definition at line 353 of file TeleoperationControlVR.hpp.
References from_string().
Member Function Documentation
action() [1/2]
int32_t & guWhiteboard::TeleoperationControlVR::action () inline
Definition at line 189 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::action.
Referenced by TeleoperationControlVR(), description(), operator=(), operator==(), and to_string().
action() [2/2]
const int32_t & guWhiteboard::TeleoperationControlVR::action () const inline
Definition at line 194 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::action.
description()
std::string guWhiteboard::TeleoperationControlVR::description () inline
USE_WB_TELEOPERATION_CONTROL_V_R_C_CONVERSION
Definition at line 358 of file TeleoperationControlVR.hpp.
References action(), HeadPitch(), HeadYaw(), ip(), sayString(), selectedCamera(), stance(), streamType(), TELEOPERATIONCONTROLVR_DESC_BUFFER_SIZE, timestamp(), turn(), walk(), and wb_teleoperation_control_v_r_description().
from_string()
void guWhiteboard::TeleoperationControlVR::from_string (const std::string & t_str) inline
USE_WB_TELEOPERATION_CONTROL_V_R_C_CONVERSION
Definition at line 436 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::sayString, set_action(), set_HeadPitch(), set_HeadYaw(), set_ip(), set_selectedCamera(), set_stance(), set_streamType(), set_timestamp(), set_turn(), set_walk(), and TELEOPERATIONCONTROLVR_DESC_BUFFER_SIZE.
Referenced by TeleoperationControlVR().
HeadPitch() [1/2]
float & guWhiteboard::TeleoperationControlVR::HeadPitch () inline
Definition at line 219 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::HeadPitch.
Referenced by TeleoperationControlVR(), description(), operator=(), operator==(), and to_string().
HeadPitch() [2/2]
const float & guWhiteboard::TeleoperationControlVR::HeadPitch () const inline
Definition at line 224 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::HeadPitch.
HeadYaw() [1/2]
float & guWhiteboard::TeleoperationControlVR::HeadYaw () inline
Definition at line 204 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::HeadYaw.
Referenced by TeleoperationControlVR(), description(), operator=(), operator==(), and to_string().
HeadYaw() [2/2]
const float & guWhiteboard::TeleoperationControlVR::HeadYaw () const inline
Definition at line 209 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::HeadYaw.
ip() [1/2]
uint8_t & guWhiteboard::TeleoperationControlVR::ip () inline
Definition at line 174 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::ip.
Referenced by TeleoperationControlVR(), description(), operator=(), operator==(), and to_string().
ip() [2/2]
const uint8_t & guWhiteboard::TeleoperationControlVR::ip () const inline
Definition at line 179 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::ip.
operator!=() [1/2]
bool guWhiteboard::TeleoperationControlVR::operator!= (const TeleoperationControlVR & t_other) const inline
Definition at line 159 of file TeleoperationControlVR.hpp.
operator!=() [2/2]
bool guWhiteboard::TeleoperationControlVR::operator!= (const wb_teleoperation_control_v_r & t_other) const inline
Definition at line 169 of file TeleoperationControlVR.hpp.
operator=() [1/2]
TeleoperationControlVR & guWhiteboard::TeleoperationControlVR::operator= (const struct wb_teleoperation_control_v_r & t_other) inline
Copy Assignment Operator.
Definition at line 139 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::action, wb_teleoperation_control_v_r::HeadPitch, wb_teleoperation_control_v_r::HeadYaw, wb_teleoperation_control_v_r::ip, wb_teleoperation_control_v_r::sayString, wb_teleoperation_control_v_r::selectedCamera, wb_teleoperation_control_v_r::stance, wb_teleoperation_control_v_r::streamType, wb_teleoperation_control_v_r::timestamp, wb_teleoperation_control_v_r::turn, and wb_teleoperation_control_v_r::walk.
operator=() [2/2]
TeleoperationControlVR & guWhiteboard::TeleoperationControlVR::operator= (const TeleoperationControlVR & t_other) inline
Copy Assignment Operator.
Definition at line 131 of file TeleoperationControlVR.hpp.
References action(), HeadPitch(), HeadYaw(), ip(), sayString(), selectedCamera(), stance(), streamType(), timestamp(), turn(), and walk().
operator==() [1/2]
bool guWhiteboard::TeleoperationControlVR::operator== (const TeleoperationControlVR & t_other) const inline
Definition at line 144 of file TeleoperationControlVR.hpp.
References action(), HeadPitch(), HeadYaw(), ip(), sayString(), selectedCamera(), stance(), streamType(), timestamp(), turn(), and walk().
operator==() [2/2]
bool guWhiteboard::TeleoperationControlVR::operator== (const wb_teleoperation_control_v_r & t_other) const inline
Definition at line 164 of file TeleoperationControlVR.hpp.
References TeleoperationControlVR().
sayString() [1/3]
const char * guWhiteboard::TeleoperationControlVR::sayString () const inline
Definition at line 279 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::sayString.
Referenced by TeleoperationControlVR(), description(), operator=(), operator==(), and to_string().
sayString() [2/3]
char & guWhiteboard::TeleoperationControlVR::sayString (int t_i) inline
Definition at line 289 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::sayString.
sayString() [3/3]
const char & guWhiteboard::TeleoperationControlVR::sayString (int t_i) const inline
Definition at line 294 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::sayString.
sayString_size()
size_t guWhiteboard::TeleoperationControlVR::sayString_size () const inline
Definition at line 284 of file TeleoperationControlVR.hpp.
selectedCamera() [1/2]
int32_t & guWhiteboard::TeleoperationControlVR::selectedCamera () inline
Definition at line 264 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::selectedCamera.
Referenced by TeleoperationControlVR(), description(), operator=(), operator==(), and to_string().
selectedCamera() [2/2]
const int32_t & guWhiteboard::TeleoperationControlVR::selectedCamera () const inline
Definition at line 269 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::selectedCamera.
set_action()
void guWhiteboard::TeleoperationControlVR::set_action (const int32_t & t_newValue) inline
Definition at line 199 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::action.
Referenced by from_string().
set_HeadPitch()
void guWhiteboard::TeleoperationControlVR::set_HeadPitch (const float & t_newValue) inline
Definition at line 229 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::HeadPitch.
Referenced by from_string().
set_HeadYaw()
void guWhiteboard::TeleoperationControlVR::set_HeadYaw (const float & t_newValue) inline
Definition at line 214 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::HeadYaw.
Referenced by from_string().
set_ip()
void guWhiteboard::TeleoperationControlVR::set_ip (const uint8_t & t_newValue) inline
Definition at line 184 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::ip.
Referenced by from_string().
set_sayString()
void guWhiteboard::TeleoperationControlVR::set_sayString (const char * t_newValue) inline
Definition at line 299 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::sayString.
set_selectedCamera()
void guWhiteboard::TeleoperationControlVR::set_selectedCamera (const int32_t & t_newValue) inline
Definition at line 274 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::selectedCamera.
Referenced by from_string().
set_stance()
void guWhiteboard::TeleoperationControlVR::set_stance (const int32_t & t_newValue) inline
Definition at line 244 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::stance.
Referenced by from_string().
set_streamType()
void guWhiteboard::TeleoperationControlVR::set_streamType (const int32_t & t_newValue) inline
Definition at line 259 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::streamType.
Referenced by from_string().
set_timestamp()
void guWhiteboard::TeleoperationControlVR::set_timestamp (const int32_t & t_newValue) inline
Definition at line 344 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::timestamp.
Referenced by from_string().
set_turn()
void guWhiteboard::TeleoperationControlVR::set_turn (const int32_t & t_newValue) inline
Definition at line 329 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::turn.
Referenced by from_string().
set_walk()
void guWhiteboard::TeleoperationControlVR::set_walk (const int32_t & t_newValue) inline
Definition at line 314 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::walk.
Referenced by from_string().
stance() [1/2]
int32_t & guWhiteboard::TeleoperationControlVR::stance () inline
Definition at line 234 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::stance.
Referenced by TeleoperationControlVR(), description(), operator=(), operator==(), and to_string().
stance() [2/2]
const int32_t & guWhiteboard::TeleoperationControlVR::stance () const inline
Definition at line 239 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::stance.
streamType() [1/2]
int32_t & guWhiteboard::TeleoperationControlVR::streamType () inline
Definition at line 249 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::streamType.
Referenced by TeleoperationControlVR(), description(), operator=(), operator==(), and to_string().
streamType() [2/2]
const int32_t & guWhiteboard::TeleoperationControlVR::streamType () const inline
Definition at line 254 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::streamType.
timestamp() [1/2]
int32_t & guWhiteboard::TeleoperationControlVR::timestamp () inline
Definition at line 334 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::timestamp.
Referenced by TeleoperationControlVR(), description(), operator=(), operator==(), and to_string().
timestamp() [2/2]
const int32_t & guWhiteboard::TeleoperationControlVR::timestamp () const inline
Definition at line 339 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::timestamp.
to_string()
std::string guWhiteboard::TeleoperationControlVR::to_string () inline
USE_WB_TELEOPERATION_CONTROL_V_R_C_CONVERSION
Definition at line 395 of file TeleoperationControlVR.hpp.
References action(), HeadPitch(), HeadYaw(), ip(), sayString(), selectedCamera(), stance(), streamType(), TELEOPERATIONCONTROLVR_TO_STRING_BUFFER_SIZE, timestamp(), turn(), walk(), and wb_teleoperation_control_v_r_to_string().
turn() [1/2]
int32_t & guWhiteboard::TeleoperationControlVR::turn () inline
Definition at line 319 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::turn.
Referenced by TeleoperationControlVR(), description(), operator=(), operator==(), and to_string().
turn() [2/2]
const int32_t & guWhiteboard::TeleoperationControlVR::turn () const inline
Definition at line 324 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::turn.
walk() [1/2]
int32_t & guWhiteboard::TeleoperationControlVR::walk () inline
Definition at line 304 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::walk.
Referenced by TeleoperationControlVR(), description(), operator=(), operator==(), and to_string().
walk() [2/2]
const int32_t & guWhiteboard::TeleoperationControlVR::walk () const inline
Definition at line 309 of file TeleoperationControlVR.hpp.
References wb_teleoperation_control_v_r::walk.
The documentation for this class was generated from the following file:
typeClassDefs/TeleoperationControlVR.hpp