gusimplewhiteboard: guWhiteboard::FSMNames Class Reference
guWhiteboard::FSMNames Class Reference
Class for transmitting machine names over the whiteboard.
#include <FSMControlStatus.hpp>
Public Member Functions
FSMNames (uint16_t startoffs=0, const char *names=NULLPTR)
designated constructor
FSMNames (const FSMNames &other)
copy constructor
const FSMNames & operator= (const FSMNames &other)
assignment operator
char * names ()
names getter
const char * end ()
end of string
char * next_name (const char *name=NULLPTR)
get the next name
char * next_slot (const char *name=NULLPTR)
get the next empty slot
int available_space (const char *pos)
return the available space after a given pointer
char * add_name (char *name)
try to add a new name
FSMNames (std::string names)
string constructor
std::string description ()
convert to a string
void from_string (const std::string &str)
convert from a string
Detailed Description
Class for transmitting machine names over the whiteboard.
Definition at line 156 of file FSMControlStatus.hpp.
Constructor & Destructor Documentation
FSMNames() [1/3]
guWhiteboard::FSMNames::FSMNames (uint16_t startoffs = 0, const char * names = NULLPTR) inline
designated constructor
Definition at line 164 of file FSMControlStatus.hpp.
References names().
FSMNames() [2/3]
guWhiteboard::FSMNames::FSMNames (const FSMNames & other) inline
copy constructor
Definition at line 173 of file FSMControlStatus.hpp.
FSMNames() [3/3]
guWhiteboard::FSMNames::FSMNames (std::string names) inline
string constructor
Definition at line 208 of file FSMControlStatus.hpp.
References from_string(), and names().
Member Function Documentation
add_name()
char * guWhiteboard::FSMNames::add_name (char * name) inline
try to add a new name
Definition at line 197 of file FSMControlStatus.hpp.
References available_space(), and next_slot().
available_space()
int guWhiteboard::FSMNames::available_space (const char * pos) inline
return the available space after a given pointer
Definition at line 194 of file FSMControlStatus.hpp.
References end().
Referenced by add_name(), and from_string().
description()
std::string guWhiteboard::FSMNames::description () inline
convert to a string
Definition at line 211 of file FSMControlStatus.hpp.
References end(), names(), and next_name().
end()
const char * guWhiteboard::FSMNames::end () inline
end of string
Definition at line 185 of file FSMControlStatus.hpp.
Referenced by available_space(), description(), next_name(), and next_slot().
from_string()
void guWhiteboard::FSMNames::from_string (const std::string & str) inline
convert from a string
Definition at line 222 of file FSMControlStatus.hpp.
References available_space(), and names().
Referenced by FSMNames().
names()
char * guWhiteboard::FSMNames::names () inline
names getter
Definition at line 182 of file FSMControlStatus.hpp.
Referenced by FSMNames(), description(), from_string(), and next_name().
next_name()
char * guWhiteboard::FSMNames::next_name (const char * name = NULLPTR) inline
get the next name
Definition at line 188 of file FSMControlStatus.hpp.
References end(), and names().
Referenced by description(), and next_slot().
next_slot()
char * guWhiteboard::FSMNames::next_slot (const char * name = NULLPTR) inline
get the next empty slot
Definition at line 191 of file FSMControlStatus.hpp.
References end(), and next_name().
Referenced by add_name().
operator=()
const FSMNames & guWhiteboard::FSMNames::operator= (const FSMNames & other) inline
assignment operator
Definition at line 179 of file FSMControlStatus.hpp.
The documentation for this class was generated from the following file:
typeClassDefs/FSMControlStatus.hpp