gusimplewhiteboard: guWhiteboard::MemoryImageControlStatus Class Reference
guWhiteboard::MemoryImageControlStatus Class Reference
Provides a C++ wrapper around wb_memory_image_control_status.
#include <MemoryImageControlStatus.hpp>
Public Member Functions
MemoryImageControlStatus (uint16_t t_res_width=0, uint16_t t_res_height=0, enum MemoryImagePixelFormat t_pixelFormat=MI_RGBA)
Create a new MemoryImageControlStatus.
MemoryImageControlStatus (const MemoryImageControlStatus &t_other)
Copy Constructor.
MemoryImageControlStatus (const struct wb_memory_image_control_status &t_other)
Copy Constructor.
MemoryImageControlStatus & operator= (const MemoryImageControlStatus &t_other)
Copy Assignment Operator.
MemoryImageControlStatus & operator= (const struct wb_memory_image_control_status &t_other)
Copy Assignment Operator.
bool operator== (const MemoryImageControlStatus &t_other) const
bool operator!= (const MemoryImageControlStatus &t_other) const
bool operator== (const wb_memory_image_control_status &t_other) const
bool operator!= (const wb_memory_image_control_status &t_other) const
uint16_t & res_width ()
const uint16_t & res_width () const
void set_res_width (const uint16_t &t_newValue)
uint16_t & res_height ()
const uint16_t & res_height () const
void set_res_height (const uint16_t &t_newValue)
enum MemoryImagePixelFormat & pixelFormat ()
enum MemoryImagePixelFormat & pixelFormat () const
void set_pixelFormat (const enum MemoryImagePixelFormat &t_newValue)
MemoryImageControlStatus (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_memory_image_control_status
uint16_t res_width
The resolution width.
uint16_t res_height
The resolution height.
enum MemoryImagePixelFormat pixelFormat
The pixel format of the images.
Detailed Description
Provides a C++ wrapper around wb_memory_image_control_status.
Definition at line 83 of file MemoryImageControlStatus.hpp.
Constructor & Destructor Documentation
MemoryImageControlStatus() [1/4]
guWhiteboard::MemoryImageControlStatus::MemoryImageControlStatus (uint16_t t_res_width = 0, uint16_t t_res_height = 0, enum MemoryImagePixelFormat t_pixelFormat = MI_RGBA) inline
Create a new MemoryImageControlStatus.
Definition at line 101 of file MemoryImageControlStatus.hpp.
Referenced by operator==().
MemoryImageControlStatus() [2/4]
guWhiteboard::MemoryImageControlStatus::MemoryImageControlStatus (const MemoryImageControlStatus & t_other) inline
Copy Constructor.
Definition at line 108 of file MemoryImageControlStatus.hpp.
References pixelFormat(), res_height(), and res_width().
MemoryImageControlStatus() [3/4]
guWhiteboard::MemoryImageControlStatus::MemoryImageControlStatus (const struct wb_memory_image_control_status & t_other) inline
Copy Constructor.
Definition at line 115 of file MemoryImageControlStatus.hpp.
References wb_memory_image_control_status::pixelFormat, wb_memory_image_control_status::res_height, and wb_memory_image_control_status::res_width.
MemoryImageControlStatus() [4/4]
guWhiteboard::MemoryImageControlStatus::MemoryImageControlStatus (const std::string & t_str) inline
String Constructor.
Definition at line 206 of file MemoryImageControlStatus.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::MemoryImageControlStatus::description () inline
USE_WB_MEMORY_IMAGE_CONTROL_STATUS_C_CONVERSION
Definition at line 211 of file MemoryImageControlStatus.hpp.
References MEMORY_IMAGE_CONTROL_STATUS_DESC_BUFFER_SIZE, MI_BGRA, MI_RGBA, MI_UYV422, pixelFormat(), res_height(), res_width(), and wb_memory_image_control_status_description().
from_string()
void guWhiteboard::MemoryImageControlStatus::from_string (const std::string & t_str) inline
USE_WB_MEMORY_IMAGE_CONTROL_STATUS_C_CONVERSION
Definition at line 281 of file MemoryImageControlStatus.hpp.
References MEMORY_IMAGE_CONTROL_STATUS_DESC_BUFFER_SIZE, MI_BGRA, MI_RGBA, MI_UYV422, set_pixelFormat(), set_res_height(), and set_res_width().
Referenced by MemoryImageControlStatus().
operator!=() [1/2]
bool guWhiteboard::MemoryImageControlStatus::operator!= (const MemoryImageControlStatus & t_other) const inline
Definition at line 142 of file MemoryImageControlStatus.hpp.
operator!=() [2/2]
bool guWhiteboard::MemoryImageControlStatus::operator!= (const wb_memory_image_control_status & t_other) const inline
Definition at line 152 of file MemoryImageControlStatus.hpp.
operator=() [1/2]
MemoryImageControlStatus & guWhiteboard::MemoryImageControlStatus::operator= (const MemoryImageControlStatus & t_other) inline
Copy Assignment Operator.
Definition at line 122 of file MemoryImageControlStatus.hpp.
References pixelFormat(), res_height(), and res_width().
operator=() [2/2]
MemoryImageControlStatus & guWhiteboard::MemoryImageControlStatus::operator= (const struct wb_memory_image_control_status & t_other) inline
Copy Assignment Operator.
Definition at line 130 of file MemoryImageControlStatus.hpp.
References wb_memory_image_control_status::pixelFormat, wb_memory_image_control_status::res_height, and wb_memory_image_control_status::res_width.
operator==() [1/2]
bool guWhiteboard::MemoryImageControlStatus::operator== (const MemoryImageControlStatus & t_other) const inline
Definition at line 135 of file MemoryImageControlStatus.hpp.
References pixelFormat(), res_height(), and res_width().
operator==() [2/2]
bool guWhiteboard::MemoryImageControlStatus::operator== (const wb_memory_image_control_status & t_other) const inline
Definition at line 147 of file MemoryImageControlStatus.hpp.
References MemoryImageControlStatus().
pixelFormat() [1/2]
enum MemoryImagePixelFormat & guWhiteboard::MemoryImageControlStatus::pixelFormat () inline
Definition at line 187 of file MemoryImageControlStatus.hpp.
References wb_memory_image_control_status::pixelFormat.
Referenced by MemoryImageControlStatus(), description(), operator=(), operator==(), and to_string().
pixelFormat() [2/2]
enum MemoryImagePixelFormat & guWhiteboard::MemoryImageControlStatus::pixelFormat () const inline
Definition at line 192 of file MemoryImageControlStatus.hpp.
References wb_memory_image_control_status::pixelFormat.
res_height() [1/2]
uint16_t & guWhiteboard::MemoryImageControlStatus::res_height () inline
Definition at line 172 of file MemoryImageControlStatus.hpp.
References wb_memory_image_control_status::res_height.
Referenced by MemoryImageControlStatus(), description(), operator=(), operator==(), and to_string().
res_height() [2/2]
const uint16_t & guWhiteboard::MemoryImageControlStatus::res_height () const inline
Definition at line 177 of file MemoryImageControlStatus.hpp.
References wb_memory_image_control_status::res_height.
res_width() [1/2]
uint16_t & guWhiteboard::MemoryImageControlStatus::res_width () inline
Definition at line 157 of file MemoryImageControlStatus.hpp.
References wb_memory_image_control_status::res_width.
Referenced by MemoryImageControlStatus(), description(), operator=(), operator==(), and to_string().
res_width() [2/2]
const uint16_t & guWhiteboard::MemoryImageControlStatus::res_width () const inline
Definition at line 162 of file MemoryImageControlStatus.hpp.
References wb_memory_image_control_status::res_width.
set_pixelFormat()
void guWhiteboard::MemoryImageControlStatus::set_pixelFormat (const enum MemoryImagePixelFormat & t_newValue) inline
Definition at line 197 of file MemoryImageControlStatus.hpp.
References wb_memory_image_control_status::pixelFormat.
Referenced by from_string().
set_res_height()
void guWhiteboard::MemoryImageControlStatus::set_res_height (const uint16_t & t_newValue) inline
Definition at line 182 of file MemoryImageControlStatus.hpp.
References wb_memory_image_control_status::res_height.
Referenced by from_string().
set_res_width()
void guWhiteboard::MemoryImageControlStatus::set_res_width (const uint16_t & t_newValue) inline
Definition at line 167 of file MemoryImageControlStatus.hpp.
References wb_memory_image_control_status::res_width.
Referenced by from_string().
to_string()
std::string guWhiteboard::MemoryImageControlStatus::to_string () inline
USE_WB_MEMORY_IMAGE_CONTROL_STATUS_C_CONVERSION
Definition at line 244 of file MemoryImageControlStatus.hpp.
References MEMORY_IMAGE_CONTROL_STATUS_TO_STRING_BUFFER_SIZE, MI_BGRA, MI_RGBA, MI_UYV422, pixelFormat(), res_height(), res_width(), and wb_memory_image_control_status_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/MemoryImageControlStatus.hpp