gusimplewhiteboard: guWhiteboard::VisionControlStatus Class Reference
guWhiteboard::VisionControlStatus Class Reference
Provides a C++ wrapper around wb_vision_control_status.
#include <VisionControlStatus.hpp>
Public Member Functions
VisionControlStatus (enum Resolutions t_cameraResolution=VGA, bool t_pipelineRunning=true, enum VisionCamera t_selectedCamera=Top, enum SaveFileType t_saveImage=None, bool t_saveClassifiedImage=false, enum NamedPipeline t_pipeline=Soccer, int t_chooseCamera=0, float t_confidence=0.8f, enum NeuralNetworkType t_networkTop=v2, enum NeuralNetworkType t_networkBottom=v2, enum StreamingType t_streamingSource=Normal, bool t_imageInput=false, int t_jpegStreamQuality=30, int t_jpegStreamStride=4, int t_frameRate=0, bool t_runPipelineOnce=false, uint64_t t_frameNumber=0, std::string t_colourCalibration="class", struct timeval t_imageTime={})
Create a new VisionControlStatus.
VisionControlStatus (const VisionControlStatus &t_other)
Copy Constructor.
VisionControlStatus (const struct wb_vision_control_status &t_other)
Copy Constructor.
VisionControlStatus & operator= (const VisionControlStatus &t_other)
Copy Assignment Operator.
VisionControlStatus & operator= (const struct wb_vision_control_status &t_other)
Copy Assignment Operator.
bool operator== (const VisionControlStatus &t_other) const
bool operator!= (const VisionControlStatus &t_other) const
bool operator== (const wb_vision_control_status &t_other) const
bool operator!= (const wb_vision_control_status &t_other) const
enum Resolutions & cameraResolution ()
enum Resolutions & cameraResolution () const
void set_cameraResolution (const enum Resolutions &t_newValue)
bool & pipelineRunning ()
const bool & pipelineRunning () const
void set_pipelineRunning (const bool &t_newValue)
enum VisionCamera & selectedCamera ()
enum VisionCamera & selectedCamera () const
void set_selectedCamera (const enum VisionCamera &t_newValue)
enum SaveFileType & saveImage ()
enum SaveFileType & saveImage () const
void set_saveImage (const enum SaveFileType &t_newValue)
bool & saveClassifiedImage ()
const bool & saveClassifiedImage () const
void set_saveClassifiedImage (const bool &t_newValue)
enum NamedPipeline & pipeline ()
enum NamedPipeline & pipeline () const
void set_pipeline (const enum NamedPipeline &t_newValue)
int & chooseCamera ()
const int & chooseCamera () const
void set_chooseCamera (const int &t_newValue)
float & confidence ()
const float & confidence () const
void set_confidence (const float &t_newValue)
enum NeuralNetworkType & networkTop ()
enum NeuralNetworkType & networkTop () const
void set_networkTop (const enum NeuralNetworkType &t_newValue)
enum NeuralNetworkType & networkBottom ()
enum NeuralNetworkType & networkBottom () const
void set_networkBottom (const enum NeuralNetworkType &t_newValue)
enum StreamingType & streamingSource ()
enum StreamingType & streamingSource () const
void set_streamingSource (const enum StreamingType &t_newValue)
bool & imageInput ()
const bool & imageInput () const
void set_imageInput (const bool &t_newValue)
int & jpegStreamQuality ()
const int & jpegStreamQuality () const
void set_jpegStreamQuality (const int &t_newValue)
int & jpegStreamStride ()
const int & jpegStreamStride () const
void set_jpegStreamStride (const int &t_newValue)
int & frameRate ()
const int & frameRate () const
void set_frameRate (const int &t_newValue)
bool & runPipelineOnce ()
const bool & runPipelineOnce () const
void set_runPipelineOnce (const bool &t_newValue)
uint64_t & frameNumber ()
const uint64_t & frameNumber () const
void set_frameNumber (const uint64_t &t_newValue)
const char * colourCalibration () const
size_t colourCalibration_size () const
char & colourCalibration (int t_i)
const char & colourCalibration (int t_i) const
void set_colourCalibration (const char *t_newValue)
struct timeval & imageTime ()
const struct timeval & imageTime () const
void set_imageTime (const struct timeval &t_newValue)
VisionControlStatus (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_vision_control_status
enum Resolutions cameraResolution
Resolution that the camera should caputre images at.
bool pipelineRunning
Whether the pipeline is running or not.
enum VisionCamera selectedCamera
Which camera to use.
enum SaveFileType saveImage
Whether to save the image used in the next iteration of the pipeline to file.
bool saveClassifiedImage
Whether to save the classified version of the image used in the next iteration of the pipeline to file.
enum NamedPipeline pipeline
vision pipeline to be run
int chooseCamera
Choose which camera to run on (0-Top, 1-Bottom, 2-Both)
float confidence
Confidence threshold for the neural net.
enum NeuralNetworkType networkTop
neural network to run on top camera
enum NeuralNetworkType networkBottom
neural network to run on bottom camera
enum StreamingType streamingSource
The type of streaming to be used.
bool imageInput
Use /tmp/test.ai2 as pipeline image rather then camera if true.
int jpegStreamQuality
The quality to compress jpeg images at for streaming can be between 0 and 100.
int jpegStreamStride
The stride to use when streaming jpeg images.
int frameRate
The current framerate that the pipeline is running at.
bool runPipelineOnce
run the pipeline one time only if true
uint64_t frameNumber
The current frame number reported by guvison.
char colourCalibration [10]
the DLC file to use for segmentation, searched in $HOME/data/ with the .dlc extension
struct timeval imageTime
the time that the image was taken that this status message refers to
Detailed Description
Provides a C++ wrapper around wb_vision_control_status.
Definition at line 84 of file VisionControlStatus.hpp.
Constructor & Destructor Documentation
VisionControlStatus() [1/4]
guWhiteboard::VisionControlStatus::VisionControlStatus (enum Resolutions t_cameraResolution = VGA, bool t_pipelineRunning = true, enum VisionCamera t_selectedCamera = Top, enum SaveFileType t_saveImage = None, bool t_saveClassifiedImage = false, enum NamedPipeline t_pipeline = Soccer, int t_chooseCamera = 0, float t_confidence = 0.8f, enum NeuralNetworkType t_networkTop = v2, enum NeuralNetworkType t_networkBottom = v2, enum StreamingType t_streamingSource = Normal, bool t_imageInput = false, int t_jpegStreamQuality = 30, int t_jpegStreamStride = 4, int t_frameRate = 0, bool t_runPipelineOnce = false, uint64_t t_frameNumber = 0, std::string t_colourCalibration = "class", struct timeval t_imageTime = {}) inline
Create a new VisionControlStatus.
Definition at line 118 of file VisionControlStatus.hpp.
Referenced by operator==().
VisionControlStatus() [2/4]
guWhiteboard::VisionControlStatus::VisionControlStatus (const VisionControlStatus & t_other) inline
Copy Constructor.
Definition at line 125 of file VisionControlStatus.hpp.
References cameraResolution(), chooseCamera(), colourCalibration(), confidence(), frameNumber(), frameRate(), imageInput(), imageTime(), jpegStreamQuality(), jpegStreamStride(), networkBottom(), networkTop(), pipeline(), pipelineRunning(), runPipelineOnce(), saveClassifiedImage(), saveImage(), selectedCamera(), and streamingSource().
VisionControlStatus() [3/4]
guWhiteboard::VisionControlStatus::VisionControlStatus (const struct wb_vision_control_status & t_other) inline
Copy Constructor.
Definition at line 132 of file VisionControlStatus.hpp.
References wb_vision_control_status::cameraResolution, wb_vision_control_status::chooseCamera, wb_vision_control_status::colourCalibration, wb_vision_control_status::confidence, wb_vision_control_status::frameNumber, wb_vision_control_status::frameRate, wb_vision_control_status::imageInput, wb_vision_control_status::imageTime, wb_vision_control_status::jpegStreamQuality, wb_vision_control_status::jpegStreamStride, wb_vision_control_status::networkBottom, wb_vision_control_status::networkTop, wb_vision_control_status::pipeline, wb_vision_control_status::pipelineRunning, wb_vision_control_status::runPipelineOnce, wb_vision_control_status::saveClassifiedImage, wb_vision_control_status::saveImage, wb_vision_control_status::selectedCamera, and wb_vision_control_status::streamingSource.
VisionControlStatus() [4/4]
guWhiteboard::VisionControlStatus::VisionControlStatus (const std::string & t_str) inline
String Constructor.
Definition at line 488 of file VisionControlStatus.hpp.
References from_string().
Member Function Documentation
cameraResolution() [1/2]
enum Resolutions & guWhiteboard::VisionControlStatus::cameraResolution () inline
Definition at line 189 of file VisionControlStatus.hpp.
References wb_vision_control_status::cameraResolution.
Referenced by VisionControlStatus(), description(), operator=(), operator==(), and to_string().
cameraResolution() [2/2]
enum Resolutions & guWhiteboard::VisionControlStatus::cameraResolution () const inline
Definition at line 194 of file VisionControlStatus.hpp.
References wb_vision_control_status::cameraResolution.
chooseCamera() [1/2]
int & guWhiteboard::VisionControlStatus::chooseCamera () inline
Definition at line 279 of file VisionControlStatus.hpp.
References wb_vision_control_status::chooseCamera.
Referenced by VisionControlStatus(), description(), operator=(), operator==(), and to_string().
chooseCamera() [2/2]
const int & guWhiteboard::VisionControlStatus::chooseCamera () const inline
Definition at line 284 of file VisionControlStatus.hpp.
References wb_vision_control_status::chooseCamera.
colourCalibration() [1/3]
const char * guWhiteboard::VisionControlStatus::colourCalibration () const inline
Definition at line 444 of file VisionControlStatus.hpp.
References wb_vision_control_status::colourCalibration.
Referenced by VisionControlStatus(), description(), operator=(), operator==(), and to_string().
colourCalibration() [2/3]
char & guWhiteboard::VisionControlStatus::colourCalibration (int t_i) inline
Definition at line 454 of file VisionControlStatus.hpp.
References wb_vision_control_status::colourCalibration.
colourCalibration() [3/3]
const char & guWhiteboard::VisionControlStatus::colourCalibration (int t_i) const inline
Definition at line 459 of file VisionControlStatus.hpp.
References wb_vision_control_status::colourCalibration.
colourCalibration_size()
size_t guWhiteboard::VisionControlStatus::colourCalibration_size () const inline
Definition at line 449 of file VisionControlStatus.hpp.
confidence() [1/2]
float & guWhiteboard::VisionControlStatus::confidence () inline
Definition at line 294 of file VisionControlStatus.hpp.
References wb_vision_control_status::confidence.
Referenced by VisionControlStatus(), description(), operator=(), operator==(), and to_string().
confidence() [2/2]
const float & guWhiteboard::VisionControlStatus::confidence () const inline
Definition at line 299 of file VisionControlStatus.hpp.
References wb_vision_control_status::confidence.
description()
std::string guWhiteboard::VisionControlStatus::description () inline
USE_WB_VISION_CONTROL_STATUS_C_CONVERSION
Definition at line 493 of file VisionControlStatus.hpp.
References AI2, AI3, BallOnly, Bottom, cameraResolution(), chooseCamera(), Classified, colourCalibration(), confidence(), frameNumber(), frameRate(), HD_4VGA, HTWK, imageInput(), jpegStreamQuality(), jpegStreamStride(), JPG, networkBottom(), networkTop(), Neural_Network, None, Normal, NUM_VISION_CAMERAS, OpenChallenge, OpenCVFaces, pipeline(), pipelineRunning(), QQVGA, QVGA, Recognized, runPipelineOnce(), saveClassifiedImage(), saveImage(), selectedCamera(), Soccer, Streaming, streamingSource(), SVGA, Top, v2, Vanilla, VGA, VGANet, VISION_CONTROL_STATUS_DESC_BUFFER_SIZE, and wb_vision_control_status_description().
frameNumber() [1/2]
uint64_t & guWhiteboard::VisionControlStatus::frameNumber () inline
Definition at line 429 of file VisionControlStatus.hpp.
References wb_vision_control_status::frameNumber.
Referenced by VisionControlStatus(), description(), operator=(), operator==(), and to_string().
frameNumber() [2/2]
const uint64_t & guWhiteboard::VisionControlStatus::frameNumber () const inline
Definition at line 434 of file VisionControlStatus.hpp.
References wb_vision_control_status::frameNumber.
frameRate() [1/2]
int & guWhiteboard::VisionControlStatus::frameRate () inline
Definition at line 399 of file VisionControlStatus.hpp.
References wb_vision_control_status::frameRate.
Referenced by VisionControlStatus(), description(), operator=(), operator==(), and to_string().
frameRate() [2/2]
const int & guWhiteboard::VisionControlStatus::frameRate () const inline
Definition at line 404 of file VisionControlStatus.hpp.
References wb_vision_control_status::frameRate.
from_string()
void guWhiteboard::VisionControlStatus::from_string (const std::string & t_str) inline
USE_WB_VISION_CONTROL_STATUS_C_CONVERSION
Definition at line 903 of file VisionControlStatus.hpp.
References AI2, AI3, BallOnly, Bottom, Classified, wb_vision_control_status::colourCalibration, HD_4VGA, HTWK, JPG, Neural_Network, None, Normal, NUM_VISION_CAMERAS, OpenChallenge, OpenCVFaces, QQVGA, QVGA, Recognized, set_cameraResolution(), set_chooseCamera(), set_confidence(), set_frameNumber(), set_frameRate(), set_imageInput(), set_jpegStreamQuality(), set_jpegStreamStride(), set_networkBottom(), set_networkTop(), set_pipeline(), set_pipelineRunning(), set_runPipelineOnce(), set_saveClassifiedImage(), set_saveImage(), set_selectedCamera(), set_streamingSource(), Soccer, Streaming, SVGA, Top, v2, Vanilla, VGA, VGANet, and VISION_CONTROL_STATUS_DESC_BUFFER_SIZE.
Referenced by VisionControlStatus().
imageInput() [1/2]
bool & guWhiteboard::VisionControlStatus::imageInput () inline
Definition at line 354 of file VisionControlStatus.hpp.
References wb_vision_control_status::imageInput.
Referenced by VisionControlStatus(), description(), operator=(), operator==(), and to_string().
imageInput() [2/2]
const bool & guWhiteboard::VisionControlStatus::imageInput () const inline
Definition at line 359 of file VisionControlStatus.hpp.
References wb_vision_control_status::imageInput.
imageTime() [1/2]
struct timeval & guWhiteboard::VisionControlStatus::imageTime () inline
Definition at line 469 of file VisionControlStatus.hpp.
References wb_vision_control_status::imageTime.
Referenced by VisionControlStatus(), and operator=().
imageTime() [2/2]
const struct timeval & guWhiteboard::VisionControlStatus::imageTime () const inline
Definition at line 474 of file VisionControlStatus.hpp.
References wb_vision_control_status::imageTime.
jpegStreamQuality() [1/2]
int & guWhiteboard::VisionControlStatus::jpegStreamQuality () inline
Definition at line 369 of file VisionControlStatus.hpp.
References wb_vision_control_status::jpegStreamQuality.
Referenced by VisionControlStatus(), description(), operator=(), operator==(), and to_string().
jpegStreamQuality() [2/2]
const int & guWhiteboard::VisionControlStatus::jpegStreamQuality () const inline
Definition at line 374 of file VisionControlStatus.hpp.
References wb_vision_control_status::jpegStreamQuality.
jpegStreamStride() [1/2]
int & guWhiteboard::VisionControlStatus::jpegStreamStride () inline
Definition at line 384 of file VisionControlStatus.hpp.
References wb_vision_control_status::jpegStreamStride.
Referenced by VisionControlStatus(), description(), operator=(), operator==(), and to_string().
jpegStreamStride() [2/2]
const int & guWhiteboard::VisionControlStatus::jpegStreamStride () const inline
Definition at line 389 of file VisionControlStatus.hpp.
References wb_vision_control_status::jpegStreamStride.
networkBottom() [1/2]
enum NeuralNetworkType & guWhiteboard::VisionControlStatus::networkBottom () inline
Definition at line 324 of file VisionControlStatus.hpp.
References wb_vision_control_status::networkBottom.
Referenced by VisionControlStatus(), description(), operator=(), operator==(), and to_string().
networkBottom() [2/2]
enum NeuralNetworkType & guWhiteboard::VisionControlStatus::networkBottom () const inline
Definition at line 329 of file VisionControlStatus.hpp.
References wb_vision_control_status::networkBottom.
networkTop() [1/2]
enum NeuralNetworkType & guWhiteboard::VisionControlStatus::networkTop () inline
Definition at line 309 of file VisionControlStatus.hpp.
References wb_vision_control_status::networkTop.
Referenced by VisionControlStatus(), description(), operator=(), operator==(), and to_string().
networkTop() [2/2]
enum NeuralNetworkType & guWhiteboard::VisionControlStatus::networkTop () const inline
Definition at line 314 of file VisionControlStatus.hpp.
References wb_vision_control_status::networkTop.
operator!=() [1/2]
bool guWhiteboard::VisionControlStatus::operator!= (const VisionControlStatus & t_other) const inline
Definition at line 174 of file VisionControlStatus.hpp.
operator!=() [2/2]
bool guWhiteboard::VisionControlStatus::operator!= (const wb_vision_control_status & t_other) const inline
Definition at line 184 of file VisionControlStatus.hpp.
operator=() [1/2]
VisionControlStatus & guWhiteboard::VisionControlStatus::operator= (const struct wb_vision_control_status & t_other) inline
Copy Assignment Operator.
Definition at line 147 of file VisionControlStatus.hpp.
References wb_vision_control_status::cameraResolution, wb_vision_control_status::chooseCamera, wb_vision_control_status::colourCalibration, wb_vision_control_status::confidence, wb_vision_control_status::frameNumber, wb_vision_control_status::frameRate, wb_vision_control_status::imageInput, wb_vision_control_status::imageTime, wb_vision_control_status::jpegStreamQuality, wb_vision_control_status::jpegStreamStride, wb_vision_control_status::networkBottom, wb_vision_control_status::networkTop, wb_vision_control_status::pipeline, wb_vision_control_status::pipelineRunning, wb_vision_control_status::runPipelineOnce, wb_vision_control_status::saveClassifiedImage, wb_vision_control_status::saveImage, wb_vision_control_status::selectedCamera, and wb_vision_control_status::streamingSource.
operator=() [2/2]
VisionControlStatus & guWhiteboard::VisionControlStatus::operator= (const VisionControlStatus & t_other) inline
Copy Assignment Operator.
Definition at line 139 of file VisionControlStatus.hpp.
References cameraResolution(), chooseCamera(), colourCalibration(), confidence(), frameNumber(), frameRate(), imageInput(), imageTime(), jpegStreamQuality(), jpegStreamStride(), networkBottom(), networkTop(), pipeline(), pipelineRunning(), runPipelineOnce(), saveClassifiedImage(), saveImage(), selectedCamera(), and streamingSource().
operator==() [1/2]
bool guWhiteboard::VisionControlStatus::operator== (const VisionControlStatus & t_other) const inline
Definition at line 152 of file VisionControlStatus.hpp.
References cameraResolution(), chooseCamera(), colourCalibration(), confidence(), frameNumber(), frameRate(), imageInput(), jpegStreamQuality(), jpegStreamStride(), networkBottom(), networkTop(), pipeline(), pipelineRunning(), runPipelineOnce(), saveClassifiedImage(), saveImage(), selectedCamera(), and streamingSource().
operator==() [2/2]
bool guWhiteboard::VisionControlStatus::operator== (const wb_vision_control_status & t_other) const inline
Definition at line 179 of file VisionControlStatus.hpp.
References VisionControlStatus().
pipeline() [1/2]
enum NamedPipeline & guWhiteboard::VisionControlStatus::pipeline () inline
Definition at line 264 of file VisionControlStatus.hpp.
References wb_vision_control_status::pipeline.
Referenced by VisionControlStatus(), description(), operator=(), operator==(), and to_string().
pipeline() [2/2]
enum NamedPipeline & guWhiteboard::VisionControlStatus::pipeline () const inline
Definition at line 269 of file VisionControlStatus.hpp.
References wb_vision_control_status::pipeline.
pipelineRunning() [1/2]
bool & guWhiteboard::VisionControlStatus::pipelineRunning () inline
Definition at line 204 of file VisionControlStatus.hpp.
References wb_vision_control_status::pipelineRunning.
Referenced by VisionControlStatus(), description(), operator=(), operator==(), and to_string().
pipelineRunning() [2/2]
const bool & guWhiteboard::VisionControlStatus::pipelineRunning () const inline
Definition at line 209 of file VisionControlStatus.hpp.
References wb_vision_control_status::pipelineRunning.
runPipelineOnce() [1/2]
bool & guWhiteboard::VisionControlStatus::runPipelineOnce () inline
Definition at line 414 of file VisionControlStatus.hpp.
References wb_vision_control_status::runPipelineOnce.
Referenced by VisionControlStatus(), description(), operator=(), operator==(), and to_string().
runPipelineOnce() [2/2]
const bool & guWhiteboard::VisionControlStatus::runPipelineOnce () const inline
Definition at line 419 of file VisionControlStatus.hpp.
References wb_vision_control_status::runPipelineOnce.
saveClassifiedImage() [1/2]
bool & guWhiteboard::VisionControlStatus::saveClassifiedImage () inline
Definition at line 249 of file VisionControlStatus.hpp.
References wb_vision_control_status::saveClassifiedImage.
Referenced by VisionControlStatus(), description(), operator=(), operator==(), and to_string().
saveClassifiedImage() [2/2]
const bool & guWhiteboard::VisionControlStatus::saveClassifiedImage () const inline
Definition at line 254 of file VisionControlStatus.hpp.
References wb_vision_control_status::saveClassifiedImage.
saveImage() [1/2]
enum SaveFileType & guWhiteboard::VisionControlStatus::saveImage () inline
Definition at line 234 of file VisionControlStatus.hpp.
References wb_vision_control_status::saveImage.
Referenced by VisionControlStatus(), description(), operator=(), operator==(), and to_string().
saveImage() [2/2]
enum SaveFileType & guWhiteboard::VisionControlStatus::saveImage () const inline
Definition at line 239 of file VisionControlStatus.hpp.
References wb_vision_control_status::saveImage.
selectedCamera() [1/2]
enum VisionCamera & guWhiteboard::VisionControlStatus::selectedCamera () inline
Definition at line 219 of file VisionControlStatus.hpp.
References wb_vision_control_status::selectedCamera.
Referenced by VisionControlStatus(), description(), operator=(), operator==(), and to_string().
selectedCamera() [2/2]
enum VisionCamera & guWhiteboard::VisionControlStatus::selectedCamera () const inline
Definition at line 224 of file VisionControlStatus.hpp.
References wb_vision_control_status::selectedCamera.
set_cameraResolution()
void guWhiteboard::VisionControlStatus::set_cameraResolution (const enum Resolutions & t_newValue) inline
Definition at line 199 of file VisionControlStatus.hpp.
References wb_vision_control_status::cameraResolution.
Referenced by from_string().
set_chooseCamera()
void guWhiteboard::VisionControlStatus::set_chooseCamera (const int & t_newValue) inline
Definition at line 289 of file VisionControlStatus.hpp.
References wb_vision_control_status::chooseCamera.
Referenced by from_string().
set_colourCalibration()
void guWhiteboard::VisionControlStatus::set_colourCalibration (const char * t_newValue) inline
Definition at line 464 of file VisionControlStatus.hpp.
References wb_vision_control_status::colourCalibration.
set_confidence()
void guWhiteboard::VisionControlStatus::set_confidence (const float & t_newValue) inline
Definition at line 304 of file VisionControlStatus.hpp.
References wb_vision_control_status::confidence.
Referenced by from_string().
set_frameNumber()
void guWhiteboard::VisionControlStatus::set_frameNumber (const uint64_t & t_newValue) inline
Definition at line 439 of file VisionControlStatus.hpp.
References wb_vision_control_status::frameNumber.
Referenced by from_string().
set_frameRate()
void guWhiteboard::VisionControlStatus::set_frameRate (const int & t_newValue) inline
Definition at line 409 of file VisionControlStatus.hpp.
References wb_vision_control_status::frameRate.
Referenced by from_string().
set_imageInput()
void guWhiteboard::VisionControlStatus::set_imageInput (const bool & t_newValue) inline
Definition at line 364 of file VisionControlStatus.hpp.
References wb_vision_control_status::imageInput.
Referenced by from_string().
set_imageTime()
void guWhiteboard::VisionControlStatus::set_imageTime (const struct timeval & t_newValue) inline
Definition at line 479 of file VisionControlStatus.hpp.
References wb_vision_control_status::imageTime.
set_jpegStreamQuality()
void guWhiteboard::VisionControlStatus::set_jpegStreamQuality (const int & t_newValue) inline
Definition at line 379 of file VisionControlStatus.hpp.
References wb_vision_control_status::jpegStreamQuality.
Referenced by from_string().
set_jpegStreamStride()
void guWhiteboard::VisionControlStatus::set_jpegStreamStride (const int & t_newValue) inline
Definition at line 394 of file VisionControlStatus.hpp.
References wb_vision_control_status::jpegStreamStride.
Referenced by from_string().
set_networkBottom()
void guWhiteboard::VisionControlStatus::set_networkBottom (const enum NeuralNetworkType & t_newValue) inline
Definition at line 334 of file VisionControlStatus.hpp.
References wb_vision_control_status::networkBottom.
Referenced by from_string().
set_networkTop()
void guWhiteboard::VisionControlStatus::set_networkTop (const enum NeuralNetworkType & t_newValue) inline
Definition at line 319 of file VisionControlStatus.hpp.
References wb_vision_control_status::networkTop.
Referenced by from_string().
set_pipeline()
void guWhiteboard::VisionControlStatus::set_pipeline (const enum NamedPipeline & t_newValue) inline
Definition at line 274 of file VisionControlStatus.hpp.
References wb_vision_control_status::pipeline.
Referenced by from_string().
set_pipelineRunning()
void guWhiteboard::VisionControlStatus::set_pipelineRunning (const bool & t_newValue) inline
Definition at line 214 of file VisionControlStatus.hpp.
References wb_vision_control_status::pipelineRunning.
Referenced by from_string().
set_runPipelineOnce()
void guWhiteboard::VisionControlStatus::set_runPipelineOnce (const bool & t_newValue) inline
Definition at line 424 of file VisionControlStatus.hpp.
References wb_vision_control_status::runPipelineOnce.
Referenced by from_string().
set_saveClassifiedImage()
void guWhiteboard::VisionControlStatus::set_saveClassifiedImage (const bool & t_newValue) inline
Definition at line 259 of file VisionControlStatus.hpp.
References wb_vision_control_status::saveClassifiedImage.
Referenced by from_string().
set_saveImage()
void guWhiteboard::VisionControlStatus::set_saveImage (const enum SaveFileType & t_newValue) inline
Definition at line 244 of file VisionControlStatus.hpp.
References wb_vision_control_status::saveImage.
Referenced by from_string().
set_selectedCamera()
void guWhiteboard::VisionControlStatus::set_selectedCamera (const enum VisionCamera & t_newValue) inline
Definition at line 229 of file VisionControlStatus.hpp.
References wb_vision_control_status::selectedCamera.
Referenced by from_string().
set_streamingSource()
void guWhiteboard::VisionControlStatus::set_streamingSource (const enum StreamingType & t_newValue) inline
Definition at line 349 of file VisionControlStatus.hpp.
References wb_vision_control_status::streamingSource.
Referenced by from_string().
streamingSource() [1/2]
enum StreamingType & guWhiteboard::VisionControlStatus::streamingSource () inline
Definition at line 339 of file VisionControlStatus.hpp.
References wb_vision_control_status::streamingSource.
Referenced by VisionControlStatus(), description(), operator=(), operator==(), and to_string().
streamingSource() [2/2]
enum StreamingType & guWhiteboard::VisionControlStatus::streamingSource () const inline
Definition at line 344 of file VisionControlStatus.hpp.
References wb_vision_control_status::streamingSource.
to_string()
std::string guWhiteboard::VisionControlStatus::to_string () inline
USE_WB_VISION_CONTROL_STATUS_C_CONVERSION
Definition at line 696 of file VisionControlStatus.hpp.
References AI2, AI3, BallOnly, Bottom, cameraResolution(), chooseCamera(), Classified, colourCalibration(), confidence(), frameNumber(), frameRate(), HD_4VGA, HTWK, imageInput(), jpegStreamQuality(), jpegStreamStride(), JPG, networkBottom(), networkTop(), Neural_Network, None, Normal, NUM_VISION_CAMERAS, OpenChallenge, OpenCVFaces, pipeline(), pipelineRunning(), QQVGA, QVGA, Recognized, runPipelineOnce(), saveClassifiedImage(), saveImage(), selectedCamera(), Soccer, Streaming, streamingSource(), SVGA, Top, v2, Vanilla, VGA, VGANet, VISION_CONTROL_STATUS_TO_STRING_BUFFER_SIZE, and wb_vision_control_status_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/VisionControlStatus.hpp