gusimplewhiteboard: guWhiteboard::VisionDetectionHorizon Class Reference
guWhiteboard::VisionDetectionHorizon Class Reference
Provides a C++ wrapper around wb_vision_detection_horizon.
#include <VisionDetectionHorizon.hpp>
Public Member Functions
VisionDetectionHorizon (enum HorizonOptions t_horizonType=HorizonFailed, struct wb_pixel_coordinate t_leftCoordinate=wb_pixel_coordinate(), struct wb_pixel_coordinate t_centerCoordinate=wb_pixel_coordinate(), struct wb_pixel_coordinate t_rightCoordinate=wb_pixel_coordinate())
Create a new VisionDetectionHorizon.
VisionDetectionHorizon (const VisionDetectionHorizon &t_other)
Copy Constructor.
VisionDetectionHorizon (const struct wb_vision_detection_horizon &t_other)
Copy Constructor.
VisionDetectionHorizon & operator= (const VisionDetectionHorizon &t_other)
Copy Assignment Operator.
VisionDetectionHorizon & operator= (const struct wb_vision_detection_horizon &t_other)
Copy Assignment Operator.
bool operator== (const VisionDetectionHorizon &t_other) const
bool operator!= (const VisionDetectionHorizon &t_other) const
bool operator== (const wb_vision_detection_horizon &t_other) const
bool operator!= (const wb_vision_detection_horizon &t_other) const
enum HorizonOptions & horizonType ()
enum HorizonOptions & horizonType () const
void set_horizonType (const enum HorizonOptions &t_newValue)
PixelCoordinate & leftCoordinate ()
const PixelCoordinate & leftCoordinate () const
void set_leftCoordinate (const PixelCoordinate &t_newValue)
PixelCoordinate & centerCoordinate ()
const PixelCoordinate & centerCoordinate () const
void set_centerCoordinate (const PixelCoordinate &t_newValue)
PixelCoordinate & rightCoordinate ()
const PixelCoordinate & rightCoordinate () const
void set_rightCoordinate (const PixelCoordinate &t_newValue)
VisionDetectionHorizon (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
GU::PixelCoordinate leftCoordinatePixelCoordinate (const uint16_t resWidth, const uint16_t resHeight)
WHITEBOARD_POSTER_STRING_CONVERSION.
GU::PixelCoordinate centerCoordinatePixelCoordinate (const uint16_t resWidth, const uint16_t resHeight)
GU::PixelCoordinate rightCoordinatePixelCoordinate (const uint16_t resWidth, const uint16_t resHeight)
Additional Inherited Members
Public Attributes inherited from wb_vision_detection_horizon
enum HorizonOptions horizonType
Type of Horizon.
struct wb_pixel_coordinate leftCoordinate
Left horizon point pixel coordinate.
struct wb_pixel_coordinate centerCoordinate
Center horizon point pixel coordinate.
struct wb_pixel_coordinate rightCoordinate
Right horizon point pixel coordinate.
Detailed Description
Provides a C++ wrapper around wb_vision_detection_horizon.
Definition at line 96 of file VisionDetectionHorizon.hpp.
Constructor & Destructor Documentation
VisionDetectionHorizon() [1/4]
guWhiteboard::VisionDetectionHorizon::VisionDetectionHorizon (enum HorizonOptions t_horizonType = HorizonFailed, struct wb_pixel_coordinate t_leftCoordinate = wb_pixel_coordinate(), struct wb_pixel_coordinate t_centerCoordinate = wb_pixel_coordinate(), struct wb_pixel_coordinate t_rightCoordinate = wb_pixel_coordinate()) inline
Create a new VisionDetectionHorizon.
Definition at line 115 of file VisionDetectionHorizon.hpp.
Referenced by operator==().
VisionDetectionHorizon() [2/4]
guWhiteboard::VisionDetectionHorizon::VisionDetectionHorizon (const VisionDetectionHorizon & t_other) inline
Copy Constructor.
Definition at line 122 of file VisionDetectionHorizon.hpp.
References centerCoordinate(), horizonType(), leftCoordinate(), and rightCoordinate().
VisionDetectionHorizon() [3/4]
guWhiteboard::VisionDetectionHorizon::VisionDetectionHorizon (const struct wb_vision_detection_horizon & t_other) inline
Copy Constructor.
Definition at line 129 of file VisionDetectionHorizon.hpp.
References wb_vision_detection_horizon::centerCoordinate, wb_vision_detection_horizon::horizonType, wb_vision_detection_horizon::leftCoordinate, and wb_vision_detection_horizon::rightCoordinate.
VisionDetectionHorizon() [4/4]
guWhiteboard::VisionDetectionHorizon::VisionDetectionHorizon (const std::string & t_str) inline
String Constructor.
Definition at line 236 of file VisionDetectionHorizon.hpp.
References from_string().
Member Function Documentation
centerCoordinate() [1/2]
PixelCoordinate & guWhiteboard::VisionDetectionHorizon::centerCoordinate () inline
Definition at line 202 of file VisionDetectionHorizon.hpp.
References wb_vision_detection_horizon::centerCoordinate.
Referenced by VisionDetectionHorizon(), centerCoordinatePixelCoordinate(), description(), operator=(), operator==(), and to_string().
centerCoordinate() [2/2]
const PixelCoordinate & guWhiteboard::VisionDetectionHorizon::centerCoordinate () const inline
Definition at line 207 of file VisionDetectionHorizon.hpp.
References wb_vision_detection_horizon::centerCoordinate.
centerCoordinatePixelCoordinate()
GU::PixelCoordinate guWhiteboard::VisionDetectionHorizon::centerCoordinatePixelCoordinate (const uint16_t resWidth, const uint16_t resHeight) inline
Definition at line 473 of file VisionDetectionHorizon.hpp.
References centerCoordinate(), and guWhiteboard::PixelCoordinate::pixelCoordinate().
description()
std::string guWhiteboard::VisionDetectionHorizon::description () inline
USE_WB_VISION_DETECTION_HORIZON_C_CONVERSION
Definition at line 241 of file VisionDetectionHorizon.hpp.
References centerCoordinate(), CornerHorizon, guWhiteboard::PixelCoordinate::description(), HorizonFailed, horizonType(), leftCoordinate(), OnlyField, rightCoordinate(), SingleHorizon, VISION_DETECTION_HORIZON_DESC_BUFFER_SIZE, and wb_vision_detection_horizon_description().
from_string()
void guWhiteboard::VisionDetectionHorizon::from_string (const std::string & t_str) inline
USE_WB_VISION_DETECTION_HORIZON_C_CONVERSION
Definition at line 325 of file VisionDetectionHorizon.hpp.
References CornerHorizon, guWhiteboard::PixelCoordinate::from_string(), HorizonFailed, OnlyField, set_centerCoordinate(), set_horizonType(), set_leftCoordinate(), set_rightCoordinate(), SingleHorizon, and VISION_DETECTION_HORIZON_DESC_BUFFER_SIZE.
Referenced by VisionDetectionHorizon(), and guWhiteboard::VisionDetectionHorizons::from_string().
horizonType() [1/2]
enum HorizonOptions & guWhiteboard::VisionDetectionHorizon::horizonType () inline
Definition at line 172 of file VisionDetectionHorizon.hpp.
References wb_vision_detection_horizon::horizonType.
Referenced by VisionDetectionHorizon(), description(), operator=(), operator==(), and to_string().
horizonType() [2/2]
enum HorizonOptions & guWhiteboard::VisionDetectionHorizon::horizonType () const inline
Definition at line 177 of file VisionDetectionHorizon.hpp.
References wb_vision_detection_horizon::horizonType.
leftCoordinate() [1/2]
PixelCoordinate & guWhiteboard::VisionDetectionHorizon::leftCoordinate () inline
Definition at line 187 of file VisionDetectionHorizon.hpp.
References wb_vision_detection_horizon::leftCoordinate.
Referenced by VisionDetectionHorizon(), description(), leftCoordinatePixelCoordinate(), operator=(), operator==(), and to_string().
leftCoordinate() [2/2]
const PixelCoordinate & guWhiteboard::VisionDetectionHorizon::leftCoordinate () const inline
Definition at line 192 of file VisionDetectionHorizon.hpp.
References wb_vision_detection_horizon::leftCoordinate.
leftCoordinatePixelCoordinate()
GU::PixelCoordinate guWhiteboard::VisionDetectionHorizon::leftCoordinatePixelCoordinate (const uint16_t resWidth, const uint16_t resHeight) inline
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 469 of file VisionDetectionHorizon.hpp.
References leftCoordinate(), and guWhiteboard::PixelCoordinate::pixelCoordinate().
operator!=() [1/2]
bool guWhiteboard::VisionDetectionHorizon::operator!= (const VisionDetectionHorizon & t_other) const inline
Definition at line 157 of file VisionDetectionHorizon.hpp.
operator!=() [2/2]
bool guWhiteboard::VisionDetectionHorizon::operator!= (const wb_vision_detection_horizon & t_other) const inline
Definition at line 167 of file VisionDetectionHorizon.hpp.
operator=() [1/2]
VisionDetectionHorizon & guWhiteboard::VisionDetectionHorizon::operator= (const struct wb_vision_detection_horizon & t_other) inline
Copy Assignment Operator.
Definition at line 144 of file VisionDetectionHorizon.hpp.
References wb_vision_detection_horizon::centerCoordinate, wb_vision_detection_horizon::horizonType, wb_vision_detection_horizon::leftCoordinate, and wb_vision_detection_horizon::rightCoordinate.
operator=() [2/2]
VisionDetectionHorizon & guWhiteboard::VisionDetectionHorizon::operator= (const VisionDetectionHorizon & t_other) inline
Copy Assignment Operator.
Definition at line 136 of file VisionDetectionHorizon.hpp.
References centerCoordinate(), horizonType(), leftCoordinate(), and rightCoordinate().
operator==() [1/2]
bool guWhiteboard::VisionDetectionHorizon::operator== (const VisionDetectionHorizon & t_other) const inline
Definition at line 149 of file VisionDetectionHorizon.hpp.
References centerCoordinate(), horizonType(), leftCoordinate(), and rightCoordinate().
operator==() [2/2]
bool guWhiteboard::VisionDetectionHorizon::operator== (const wb_vision_detection_horizon & t_other) const inline
Definition at line 162 of file VisionDetectionHorizon.hpp.
References VisionDetectionHorizon().
rightCoordinate() [1/2]
PixelCoordinate & guWhiteboard::VisionDetectionHorizon::rightCoordinate () inline
Definition at line 217 of file VisionDetectionHorizon.hpp.
References wb_vision_detection_horizon::rightCoordinate.
Referenced by VisionDetectionHorizon(), description(), operator=(), operator==(), rightCoordinatePixelCoordinate(), and to_string().
rightCoordinate() [2/2]
const PixelCoordinate & guWhiteboard::VisionDetectionHorizon::rightCoordinate () const inline
Definition at line 222 of file VisionDetectionHorizon.hpp.
References wb_vision_detection_horizon::rightCoordinate.
rightCoordinatePixelCoordinate()
GU::PixelCoordinate guWhiteboard::VisionDetectionHorizon::rightCoordinatePixelCoordinate (const uint16_t resWidth, const uint16_t resHeight) inline
Definition at line 477 of file VisionDetectionHorizon.hpp.
References guWhiteboard::PixelCoordinate::pixelCoordinate(), and rightCoordinate().
set_centerCoordinate()
void guWhiteboard::VisionDetectionHorizon::set_centerCoordinate (const PixelCoordinate & t_newValue) inline
Definition at line 212 of file VisionDetectionHorizon.hpp.
References wb_vision_detection_horizon::centerCoordinate.
Referenced by from_string().
set_horizonType()
void guWhiteboard::VisionDetectionHorizon::set_horizonType (const enum HorizonOptions & t_newValue) inline
Definition at line 182 of file VisionDetectionHorizon.hpp.
References wb_vision_detection_horizon::horizonType.
Referenced by from_string().
set_leftCoordinate()
void guWhiteboard::VisionDetectionHorizon::set_leftCoordinate (const PixelCoordinate & t_newValue) inline
Definition at line 197 of file VisionDetectionHorizon.hpp.
References wb_vision_detection_horizon::leftCoordinate.
Referenced by from_string().
set_rightCoordinate()
void guWhiteboard::VisionDetectionHorizon::set_rightCoordinate (const PixelCoordinate & t_newValue) inline
Definition at line 227 of file VisionDetectionHorizon.hpp.
References wb_vision_detection_horizon::rightCoordinate.
Referenced by from_string().
to_string()
std::string guWhiteboard::VisionDetectionHorizon::to_string () inline
USE_WB_VISION_DETECTION_HORIZON_C_CONVERSION
Definition at line 281 of file VisionDetectionHorizon.hpp.
References centerCoordinate(), CornerHorizon, HorizonFailed, horizonType(), leftCoordinate(), OnlyField, rightCoordinate(), SingleHorizon, guWhiteboard::PixelCoordinate::to_string(), VISION_DETECTION_HORIZON_TO_STRING_BUFFER_SIZE, and wb_vision_detection_horizon_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/VisionDetectionHorizon.hpp