gusimplewhiteboard: guWhiteboard::VisionDetectionGoalPost Class Reference
guWhiteboard::VisionDetectionGoalPost Class Reference
Provides a C++ wrapper around wb_vision_detection_goal_post.
#include <VisionDetectionGoalPost.hpp>
Public Member Functions
VisionDetectionGoalPost (enum GoalPostOptions t_sightingType=NoPostDetected, enum GoalPostOrientation t_orientation=GenericPost, struct wb_pixel_coordinate t_topLeftCoordinate=wb_pixel_coordinate(), struct wb_pixel_coordinate t_topRightCoordinate=wb_pixel_coordinate(), struct wb_pixel_coordinate t_bottomLeftCoordinate=wb_pixel_coordinate(), struct wb_pixel_coordinate t_bottomRightCoordinate=wb_pixel_coordinate())
Create a new VisionDetectionGoalPost.
VisionDetectionGoalPost (const VisionDetectionGoalPost &t_other)
Copy Constructor.
VisionDetectionGoalPost (const struct wb_vision_detection_goal_post &t_other)
Copy Constructor.
VisionDetectionGoalPost & operator= (const VisionDetectionGoalPost &t_other)
Copy Assignment Operator.
VisionDetectionGoalPost & operator= (const struct wb_vision_detection_goal_post &t_other)
Copy Assignment Operator.
bool operator== (const VisionDetectionGoalPost &t_other) const
bool operator!= (const VisionDetectionGoalPost &t_other) const
bool operator== (const wb_vision_detection_goal_post &t_other) const
bool operator!= (const wb_vision_detection_goal_post &t_other) const
enum GoalPostOptions & sightingType ()
enum GoalPostOptions & sightingType () const
void set_sightingType (const enum GoalPostOptions &t_newValue)
enum GoalPostOrientation & orientation ()
enum GoalPostOrientation & orientation () const
void set_orientation (const enum GoalPostOrientation &t_newValue)
PixelCoordinate & topLeftCoordinate ()
const PixelCoordinate & topLeftCoordinate () const
void set_topLeftCoordinate (const PixelCoordinate &t_newValue)
PixelCoordinate & topRightCoordinate ()
const PixelCoordinate & topRightCoordinate () const
void set_topRightCoordinate (const PixelCoordinate &t_newValue)
PixelCoordinate & bottomLeftCoordinate ()
const PixelCoordinate & bottomLeftCoordinate () const
void set_bottomLeftCoordinate (const PixelCoordinate &t_newValue)
PixelCoordinate & bottomRightCoordinate ()
const PixelCoordinate & bottomRightCoordinate () const
void set_bottomRightCoordinate (const PixelCoordinate &t_newValue)
VisionDetectionGoalPost (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
GU::PixelCoordinate topLeftCoordinatePixelCoordinate (const uint16_t resWidth, const uint16_t resHeight)
WHITEBOARD_POSTER_STRING_CONVERSION.
GU::PixelCoordinate topRightCoordinatePixelCoordinate (const uint16_t resWidth, const uint16_t resHeight)
GU::PixelCoordinate bottomLeftCoordinatePixelCoordinate (const uint16_t resWidth, const uint16_t resHeight)
GU::PixelCoordinate bottomRightCoordinatePixelCoordinate (const uint16_t resWidth, const uint16_t resHeight)
Additional Inherited Members
Public Attributes inherited from wb_vision_detection_goal_post
enum GoalPostOptions sightingType
Goal post details.
enum GoalPostOrientation orientation
Goal post orientation.
struct wb_pixel_coordinate topLeftCoordinate
The top left pixel coordinate.
struct wb_pixel_coordinate topRightCoordinate
The top right pixel coordinate.
struct wb_pixel_coordinate bottomLeftCoordinate
The bottom left pixel coordinate.
struct wb_pixel_coordinate bottomRightCoordinate
The bottom right pixel coordinate.
Detailed Description
Provides a C++ wrapper around wb_vision_detection_goal_post.
Definition at line 100 of file VisionDetectionGoalPost.hpp.
Constructor & Destructor Documentation
VisionDetectionGoalPost() [1/4]
guWhiteboard::VisionDetectionGoalPost::VisionDetectionGoalPost (enum GoalPostOptions t_sightingType = NoPostDetected, enum GoalPostOrientation t_orientation = GenericPost, struct wb_pixel_coordinate t_topLeftCoordinate = wb_pixel_coordinate(), struct wb_pixel_coordinate t_topRightCoordinate = wb_pixel_coordinate(), struct wb_pixel_coordinate t_bottomLeftCoordinate = wb_pixel_coordinate(), struct wb_pixel_coordinate t_bottomRightCoordinate = wb_pixel_coordinate()) inline
Create a new VisionDetectionGoalPost.
Definition at line 121 of file VisionDetectionGoalPost.hpp.
Referenced by operator==().
VisionDetectionGoalPost() [2/4]
guWhiteboard::VisionDetectionGoalPost::VisionDetectionGoalPost (const VisionDetectionGoalPost & t_other) inline
Copy Constructor.
Definition at line 128 of file VisionDetectionGoalPost.hpp.
References bottomLeftCoordinate(), bottomRightCoordinate(), orientation(), sightingType(), topLeftCoordinate(), and topRightCoordinate().
VisionDetectionGoalPost() [3/4]
guWhiteboard::VisionDetectionGoalPost::VisionDetectionGoalPost (const struct wb_vision_detection_goal_post & t_other) inline
Copy Constructor.
Definition at line 135 of file VisionDetectionGoalPost.hpp.
References wb_vision_detection_goal_post::bottomLeftCoordinate, wb_vision_detection_goal_post::bottomRightCoordinate, wb_vision_detection_goal_post::orientation, wb_vision_detection_goal_post::sightingType, wb_vision_detection_goal_post::topLeftCoordinate, and wb_vision_detection_goal_post::topRightCoordinate.
VisionDetectionGoalPost() [4/4]
guWhiteboard::VisionDetectionGoalPost::VisionDetectionGoalPost (const std::string & t_str) inline
String Constructor.
Definition at line 274 of file VisionDetectionGoalPost.hpp.
References from_string().
Member Function Documentation
bottomLeftCoordinate() [1/2]
PixelCoordinate & guWhiteboard::VisionDetectionGoalPost::bottomLeftCoordinate () inline
Definition at line 240 of file VisionDetectionGoalPost.hpp.
References wb_vision_detection_goal_post::bottomLeftCoordinate.
Referenced by VisionDetectionGoalPost(), bottomLeftCoordinatePixelCoordinate(), description(), operator=(), operator==(), and to_string().
bottomLeftCoordinate() [2/2]
const PixelCoordinate & guWhiteboard::VisionDetectionGoalPost::bottomLeftCoordinate () const inline
Definition at line 245 of file VisionDetectionGoalPost.hpp.
References wb_vision_detection_goal_post::bottomLeftCoordinate.
bottomLeftCoordinatePixelCoordinate()
GU::PixelCoordinate guWhiteboard::VisionDetectionGoalPost::bottomLeftCoordinatePixelCoordinate (const uint16_t resWidth, const uint16_t resHeight) inline
Definition at line 576 of file VisionDetectionGoalPost.hpp.
References bottomLeftCoordinate(), and guWhiteboard::PixelCoordinate::pixelCoordinate().
bottomRightCoordinate() [1/2]
PixelCoordinate & guWhiteboard::VisionDetectionGoalPost::bottomRightCoordinate () inline
Definition at line 255 of file VisionDetectionGoalPost.hpp.
References wb_vision_detection_goal_post::bottomRightCoordinate.
Referenced by VisionDetectionGoalPost(), bottomRightCoordinatePixelCoordinate(), description(), operator=(), operator==(), and to_string().
bottomRightCoordinate() [2/2]
const PixelCoordinate & guWhiteboard::VisionDetectionGoalPost::bottomRightCoordinate () const inline
Definition at line 260 of file VisionDetectionGoalPost.hpp.
References wb_vision_detection_goal_post::bottomRightCoordinate.
bottomRightCoordinatePixelCoordinate()
GU::PixelCoordinate guWhiteboard::VisionDetectionGoalPost::bottomRightCoordinatePixelCoordinate (const uint16_t resWidth, const uint16_t resHeight) inline
Definition at line 580 of file VisionDetectionGoalPost.hpp.
References bottomRightCoordinate(), and guWhiteboard::PixelCoordinate::pixelCoordinate().
description()
std::string guWhiteboard::VisionDetectionGoalPost::description () inline
USE_WB_VISION_DETECTION_GOAL_POST_C_CONVERSION
Definition at line 279 of file VisionDetectionGoalPost.hpp.
References bottomLeftCoordinate(), bottomRightCoordinate(), guWhiteboard::PixelCoordinate::description(), FullPostSeen, GenericPost, LeftPost, NoPostDetected, orientation(), PartialPostSeen, RightPost, sightingType(), topLeftCoordinate(), topRightCoordinate(), VISION_DETECTION_GOAL_POST_DESC_BUFFER_SIZE, and wb_vision_detection_goal_post_description().
Referenced by guWhiteboard::VisionDetectionGoal::description().
from_string()
void guWhiteboard::VisionDetectionGoalPost::from_string (const std::string & t_str) inline
USE_WB_VISION_DETECTION_GOAL_POST_C_CONVERSION
Definition at line 393 of file VisionDetectionGoalPost.hpp.
References guWhiteboard::PixelCoordinate::from_string(), FullPostSeen, GenericPost, LeftPost, NoPostDetected, PartialPostSeen, RightPost, set_bottomLeftCoordinate(), set_bottomRightCoordinate(), set_orientation(), set_sightingType(), set_topLeftCoordinate(), set_topRightCoordinate(), and VISION_DETECTION_GOAL_POST_DESC_BUFFER_SIZE.
Referenced by VisionDetectionGoalPost(), and guWhiteboard::VisionDetectionGoal::from_string().
operator!=() [1/2]
bool guWhiteboard::VisionDetectionGoalPost::operator!= (const VisionDetectionGoalPost & t_other) const inline
Definition at line 165 of file VisionDetectionGoalPost.hpp.
operator!=() [2/2]
bool guWhiteboard::VisionDetectionGoalPost::operator!= (const wb_vision_detection_goal_post & t_other) const inline
Definition at line 175 of file VisionDetectionGoalPost.hpp.
operator=() [1/2]
VisionDetectionGoalPost & guWhiteboard::VisionDetectionGoalPost::operator= (const struct wb_vision_detection_goal_post & t_other) inline
Copy Assignment Operator.
Definition at line 150 of file VisionDetectionGoalPost.hpp.
References wb_vision_detection_goal_post::bottomLeftCoordinate, wb_vision_detection_goal_post::bottomRightCoordinate, wb_vision_detection_goal_post::orientation, wb_vision_detection_goal_post::sightingType, wb_vision_detection_goal_post::topLeftCoordinate, and wb_vision_detection_goal_post::topRightCoordinate.
operator=() [2/2]
VisionDetectionGoalPost & guWhiteboard::VisionDetectionGoalPost::operator= (const VisionDetectionGoalPost & t_other) inline
Copy Assignment Operator.
Definition at line 142 of file VisionDetectionGoalPost.hpp.
References bottomLeftCoordinate(), bottomRightCoordinate(), orientation(), sightingType(), topLeftCoordinate(), and topRightCoordinate().
operator==() [1/2]
bool guWhiteboard::VisionDetectionGoalPost::operator== (const VisionDetectionGoalPost & t_other) const inline
Definition at line 155 of file VisionDetectionGoalPost.hpp.
References bottomLeftCoordinate(), bottomRightCoordinate(), orientation(), sightingType(), topLeftCoordinate(), and topRightCoordinate().
operator==() [2/2]
bool guWhiteboard::VisionDetectionGoalPost::operator== (const wb_vision_detection_goal_post & t_other) const inline
Definition at line 170 of file VisionDetectionGoalPost.hpp.
References VisionDetectionGoalPost().
orientation() [1/2]
enum GoalPostOrientation & guWhiteboard::VisionDetectionGoalPost::orientation () inline
Definition at line 195 of file VisionDetectionGoalPost.hpp.
References wb_vision_detection_goal_post::orientation.
Referenced by VisionDetectionGoalPost(), description(), operator=(), operator==(), and to_string().
orientation() [2/2]
enum GoalPostOrientation & guWhiteboard::VisionDetectionGoalPost::orientation () const inline
Definition at line 200 of file VisionDetectionGoalPost.hpp.
References wb_vision_detection_goal_post::orientation.
set_bottomLeftCoordinate()
void guWhiteboard::VisionDetectionGoalPost::set_bottomLeftCoordinate (const PixelCoordinate & t_newValue) inline
Definition at line 250 of file VisionDetectionGoalPost.hpp.
References wb_vision_detection_goal_post::bottomLeftCoordinate.
Referenced by from_string().
set_bottomRightCoordinate()
void guWhiteboard::VisionDetectionGoalPost::set_bottomRightCoordinate (const PixelCoordinate & t_newValue) inline
Definition at line 265 of file VisionDetectionGoalPost.hpp.
References wb_vision_detection_goal_post::bottomRightCoordinate.
Referenced by from_string().
set_orientation()
void guWhiteboard::VisionDetectionGoalPost::set_orientation (const enum GoalPostOrientation & t_newValue) inline
Definition at line 205 of file VisionDetectionGoalPost.hpp.
References wb_vision_detection_goal_post::orientation.
Referenced by from_string().
set_sightingType()
void guWhiteboard::VisionDetectionGoalPost::set_sightingType (const enum GoalPostOptions & t_newValue) inline
Definition at line 190 of file VisionDetectionGoalPost.hpp.
References wb_vision_detection_goal_post::sightingType.
Referenced by from_string().
set_topLeftCoordinate()
void guWhiteboard::VisionDetectionGoalPost::set_topLeftCoordinate (const PixelCoordinate & t_newValue) inline
Definition at line 220 of file VisionDetectionGoalPost.hpp.
References wb_vision_detection_goal_post::topLeftCoordinate.
Referenced by from_string().
set_topRightCoordinate()
void guWhiteboard::VisionDetectionGoalPost::set_topRightCoordinate (const PixelCoordinate & t_newValue) inline
Definition at line 235 of file VisionDetectionGoalPost.hpp.
References wb_vision_detection_goal_post::topRightCoordinate.
Referenced by from_string().
sightingType() [1/2]
enum GoalPostOptions & guWhiteboard::VisionDetectionGoalPost::sightingType () inline
Definition at line 180 of file VisionDetectionGoalPost.hpp.
References wb_vision_detection_goal_post::sightingType.
Referenced by VisionDetectionGoalPost(), description(), operator=(), operator==(), and to_string().
sightingType() [2/2]
enum GoalPostOptions & guWhiteboard::VisionDetectionGoalPost::sightingType () const inline
Definition at line 185 of file VisionDetectionGoalPost.hpp.
References wb_vision_detection_goal_post::sightingType.
to_string()
std::string guWhiteboard::VisionDetectionGoalPost::to_string () inline
USE_WB_VISION_DETECTION_GOAL_POST_C_CONVERSION
Definition at line 334 of file VisionDetectionGoalPost.hpp.
References bottomLeftCoordinate(), bottomRightCoordinate(), FullPostSeen, GenericPost, LeftPost, NoPostDetected, orientation(), PartialPostSeen, RightPost, sightingType(), guWhiteboard::PixelCoordinate::to_string(), topLeftCoordinate(), topRightCoordinate(), VISION_DETECTION_GOAL_POST_TO_STRING_BUFFER_SIZE, and wb_vision_detection_goal_post_to_string().
Referenced by guWhiteboard::VisionDetectionGoal::to_string().
topLeftCoordinate() [1/2]
PixelCoordinate & guWhiteboard::VisionDetectionGoalPost::topLeftCoordinate () inline
Definition at line 210 of file VisionDetectionGoalPost.hpp.
References wb_vision_detection_goal_post::topLeftCoordinate.
Referenced by VisionDetectionGoalPost(), description(), operator=(), operator==(), to_string(), and topLeftCoordinatePixelCoordinate().
topLeftCoordinate() [2/2]
const PixelCoordinate & guWhiteboard::VisionDetectionGoalPost::topLeftCoordinate () const inline
Definition at line 215 of file VisionDetectionGoalPost.hpp.
References wb_vision_detection_goal_post::topLeftCoordinate.
topLeftCoordinatePixelCoordinate()
GU::PixelCoordinate guWhiteboard::VisionDetectionGoalPost::topLeftCoordinatePixelCoordinate (const uint16_t resWidth, const uint16_t resHeight) inline
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 568 of file VisionDetectionGoalPost.hpp.
References guWhiteboard::PixelCoordinate::pixelCoordinate(), and topLeftCoordinate().
topRightCoordinate() [1/2]
PixelCoordinate & guWhiteboard::VisionDetectionGoalPost::topRightCoordinate () inline
Definition at line 225 of file VisionDetectionGoalPost.hpp.
References wb_vision_detection_goal_post::topRightCoordinate.
Referenced by VisionDetectionGoalPost(), description(), operator=(), operator==(), to_string(), and topRightCoordinatePixelCoordinate().
topRightCoordinate() [2/2]
const PixelCoordinate & guWhiteboard::VisionDetectionGoalPost::topRightCoordinate () const inline
Definition at line 230 of file VisionDetectionGoalPost.hpp.
References wb_vision_detection_goal_post::topRightCoordinate.
topRightCoordinatePixelCoordinate()
GU::PixelCoordinate guWhiteboard::VisionDetectionGoalPost::topRightCoordinatePixelCoordinate (const uint16_t resWidth, const uint16_t resHeight) inline
Definition at line 572 of file VisionDetectionGoalPost.hpp.
References guWhiteboard::PixelCoordinate::pixelCoordinate(), and topRightCoordinate().
The documentation for this class was generated from the following file:
typeClassDefs/VisionDetectionGoalPost.hpp