gusimplewhiteboard: guWhiteboard::Count Class Reference
guWhiteboard::Count Class Reference
Provides a C++ wrapper around wb_count.
#include <Count.hpp>
Public Member Functions
Count (int64_t t_count=0)
Create a new Count.
Count (const Count &t_other)
Copy Constructor.
Count (const struct wb_count &t_other)
Copy Constructor.
Count & operator= (const Count &t_other)
Copy Assignment Operator.
Count & operator= (const struct wb_count &t_other)
Copy Assignment Operator.
bool operator== (const Count &t_other) const
bool operator!= (const Count &t_other) const
bool operator== (const wb_count &t_other) const
bool operator!= (const wb_count &t_other) const
int64_t & count ()
const int64_t & count () const
void set_count (const int64_t &t_newValue)
Count (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_count
int64_t count
The count.
Detailed Description
Provides a C++ wrapper around wb_count.
Definition at line 83 of file Count.hpp.
Constructor & Destructor Documentation
Count() [1/4]
guWhiteboard::Count::Count (int64_t t_count = 0) inline
Create a new Count.
Definition at line 99 of file Count.hpp.
Referenced by operator==().
Count() [2/4]
guWhiteboard::Count::Count (const Count & t_other) inline
Copy Constructor.
Definition at line 106 of file Count.hpp.
References count().
Count() [3/4]
guWhiteboard::Count::Count (const struct wb_count & t_other) inline
Copy Constructor.
Definition at line 113 of file Count.hpp.
References wb_count::count.
Count() [4/4]
guWhiteboard::Count::Count (const std::string & t_str) inline
String Constructor.
Definition at line 172 of file Count.hpp.
References from_string().
Member Function Documentation
count() [1/2]
int64_t & guWhiteboard::Count::count () inline
Definition at line 153 of file Count.hpp.
References wb_count::count.
Referenced by Count(), description(), operator=(), operator==(), and to_string().
count() [2/2]
const int64_t & guWhiteboard::Count::count () const inline
Definition at line 158 of file Count.hpp.
References wb_count::count.
description()
std::string guWhiteboard::Count::description () inline
USE_WB_COUNT_C_CONVERSION
Definition at line 177 of file Count.hpp.
References count(), COUNT_DESC_BUFFER_SIZE, and wb_count_description().
from_string()
void guWhiteboard::Count::from_string (const std::string & t_str) inline
USE_WB_COUNT_C_CONVERSION
Definition at line 207 of file Count.hpp.
References COUNT_DESC_BUFFER_SIZE, and set_count().
Referenced by Count().
operator!=() [1/2]
bool guWhiteboard::Count::operator!= (const Count & t_other) const inline
Definition at line 138 of file Count.hpp.
operator!=() [2/2]
bool guWhiteboard::Count::operator!= (const wb_count & t_other) const inline
Definition at line 148 of file Count.hpp.
operator=() [1/2]
Count & guWhiteboard::Count::operator= (const Count & t_other) inline
Copy Assignment Operator.
Definition at line 120 of file Count.hpp.
References count().
operator=() [2/2]
Count & guWhiteboard::Count::operator= (const struct wb_count & t_other) inline
Copy Assignment Operator.
Definition at line 128 of file Count.hpp.
References wb_count::count.
operator==() [1/2]
bool guWhiteboard::Count::operator== (const Count & t_other) const inline
Definition at line 133 of file Count.hpp.
References count().
operator==() [2/2]
bool guWhiteboard::Count::operator== (const wb_count & t_other) const inline
Definition at line 143 of file Count.hpp.
References Count().
set_count()
void guWhiteboard::Count::set_count (const int64_t & t_newValue) inline
Definition at line 163 of file Count.hpp.
References wb_count::count.
Referenced by from_string().
to_string()
std::string guWhiteboard::Count::to_string () inline
USE_WB_COUNT_C_CONVERSION
Definition at line 190 of file Count.hpp.
References count(), COUNT_TO_STRING_BUFFER_SIZE, and wb_count_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/Count.hpp