gusimplewhiteboard: guWhiteboard::FFTStatus Class Reference
guWhiteboard::FFTStatus Class Reference
Container for RMS levels and dominant frequencies.
#include <FFTStatus.hpp>
Public Member Functions
FFTStatus ()
default constructor
FFTStatus (int16_t lrms, int16_t rrms, uint16_t hi, uint16_t lo, uint16_t fsk, va_list freqs)
designated constructor
FFTStatus (int16_t lrms, int16_t rrms, uint16_t hi=320, uint16_t lo=200, uint16_t fsk=0,...)
alternate constructor
FFTStatus (const FFTStatus &other)
copy constructor
FFTStatus & operator= (const FFTStatus &other)
copy assignment operator
FFTStatus (const std::string &names)
string constructor
FFTStatus (const char *names)
const char *constructor
std::string description ()
convert to a string
void from_string (const std::string &str)
convert from a string
Public Member Functions inherited from fft_dominant_frequency
PROPERTY (struct rms_strength, rms) PROPERTY(struct fsk_frequencies
overall RMS levels
fsk ARRAY_PROPERTY (struct fft_frequency_level_pair, frequencies, 0) fft_dominant_frequency(int16_t lrms=0
Array of frequency pairs ordered by level (strongest first.
fsk int16_t uint16_t uint16_t uint16_t _fsk (hi, lo, fsk)
Static Public Member Functions
static int num_frequencies ()
number of frequencies that can be put on the wb
Additional Inherited Members
Public Attributes inherited from fft_dominant_frequency
fsk int16_t rrms = 0
fsk int16_t uint16_t hi = 320
fsk int16_t uint16_t uint16_t lo = 200
fsk int16_t uint16_t uint16_t uint16_t fsk = 0
fsk int16_t uint16_t uint16_t uint16_t rrms
Detailed Description
Container for RMS levels and dominant frequencies.
Definition at line 83 of file FFTStatus.hpp.
Constructor & Destructor Documentation
FFTStatus() [1/6]
guWhiteboard::FFTStatus::FFTStatus () inline
default constructor
Definition at line 87 of file FFTStatus.hpp.
FFTStatus() [2/6]
guWhiteboard::FFTStatus::FFTStatus (int16_t lrms, int16_t rrms, uint16_t hi, uint16_t lo, uint16_t fsk, va_list freqs) inline
designated constructor
Definition at line 90 of file FFTStatus.hpp.
FFTStatus() [3/6]
guWhiteboard::FFTStatus::FFTStatus (int16_t lrms, int16_t rrms, uint16_t hi = 320, uint16_t lo = 200, uint16_t fsk = 0, ...) inline
alternate constructor
Definition at line 93 of file FFTStatus.hpp.
References fft_dominant_frequency::fsk.
FFTStatus() [4/6]
guWhiteboard::FFTStatus::FFTStatus (const FFTStatus & other) inline
copy constructor
Definition at line 106 of file FFTStatus.hpp.
References GU_SIMPLE_WHITEBOARD_BUFSIZE.
FFTStatus() [5/6]
guWhiteboard::FFTStatus::FFTStatus (const std::string & names) inline
string constructor
Definition at line 116 of file FFTStatus.hpp.
References from_string().
FFTStatus() [6/6]
guWhiteboard::FFTStatus::FFTStatus (const char * names) inline
const char *constructor
Definition at line 119 of file FFTStatus.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::FFTStatus::description () inline
convert to a string
Definition at line 122 of file FFTStatus.hpp.
References fft_dominant_frequency::fsk, and num_frequencies().
from_string()
void guWhiteboard::FFTStatus::from_string (const std::string & str) inline
convert from a string
Definition at line 142 of file FFTStatus.hpp.
References fft_dominant_frequency::fsk.
Referenced by FFTStatus().
num_frequencies()
static int guWhiteboard::FFTStatus::num_frequencies () inline static
number of frequencies that can be put on the wb
Definition at line 112 of file FFTStatus.hpp.
References FFT_DOMINANT_NUMFREQ.
Referenced by description().
operator=()
FFTStatus & guWhiteboard::FFTStatus::operator= (const FFTStatus & other) inline
copy assignment operator
Definition at line 109 of file FFTStatus.hpp.
References GU_SIMPLE_WHITEBOARD_BUFSIZE.
The documentation for this class was generated from the following file:
typeClassDefs/FFTStatus.hpp