gusimplewhiteboard: guWhiteboard::DataLogger Class Reference
guWhiteboard::DataLogger Class Reference
Provides a C++ wrapper around wb_data_logger.
#include <DataLogger.hpp>
Public Member Functions
DataLogger (std::string t_machineName="", uint32_t t_currentState=0, uint32_t t_currentSection=0, uint8_t t_dataSet=0, bool t_loggerRunning=false, bool t_shouldExit=false, std::string t_comment="")
Create a new DataLogger.
DataLogger (const DataLogger &t_other)
Copy Constructor.
DataLogger (const struct wb_data_logger &t_other)
Copy Constructor.
DataLogger & operator= (const DataLogger &t_other)
Copy Assignment Operator.
DataLogger & operator= (const struct wb_data_logger &t_other)
Copy Assignment Operator.
bool operator== (const DataLogger &t_other) const
bool operator!= (const DataLogger &t_other) const
bool operator== (const wb_data_logger &t_other) const
bool operator!= (const wb_data_logger &t_other) const
const char * machineName () const
size_t machineName_size () const
char & machineName (int t_i)
const char & machineName (int t_i) const
void set_machineName (const char *t_newValue)
uint32_t & currentState ()
const uint32_t & currentState () const
void set_currentState (const uint32_t &t_newValue)
uint32_t & currentSection ()
const uint32_t & currentSection () const
void set_currentSection (const uint32_t &t_newValue)
uint8_t & dataSet ()
const uint8_t & dataSet () const
void set_dataSet (const uint8_t &t_newValue)
bool & loggerRunning ()
const bool & loggerRunning () const
void set_loggerRunning (const bool &t_newValue)
bool & shouldExit ()
const bool & shouldExit () const
void set_shouldExit (const bool &t_newValue)
const char * comment () const
size_t comment_size () const
char & comment (int t_i)
const char & comment (int t_i) const
void set_comment (const char *t_newValue)
DataLogger (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_data_logger
char machineName [40]
Name of the machine being monitored, but could be anything.
uint32_t currentState
The machine's currently executing state (use integer rather than the state's name)
uint32_t currentSection
Section within the state (e.g.
uint8_t dataSet
Enables selection of a data set to be logged (default = 0, joints and sensors) (NYI)
bool loggerRunning
Starts/Stops logging.
bool shouldExit
Switch to cause DataLogger to exit.
char comment [30]
Comment to be attached to the logged data (NYI)
Detailed Description
Provides a C++ wrapper around wb_data_logger.
Definition at line 83 of file DataLogger.hpp.
Constructor & Destructor Documentation
DataLogger() [1/4]
guWhiteboard::DataLogger::DataLogger (std::string t_machineName = "", uint32_t t_currentState = 0, uint32_t t_currentSection = 0, uint8_t t_dataSet = 0, bool t_loggerRunning = false, bool t_shouldExit = false, std::string t_comment = "") inline
Create a new DataLogger.
Definition at line 105 of file DataLogger.hpp.
Referenced by operator==().
DataLogger() [2/4]
guWhiteboard::DataLogger::DataLogger (const DataLogger & t_other) inline
Copy Constructor.
Definition at line 112 of file DataLogger.hpp.
References comment(), currentSection(), currentState(), dataSet(), loggerRunning(), machineName(), and shouldExit().
DataLogger() [3/4]
guWhiteboard::DataLogger::DataLogger (const struct wb_data_logger & t_other) inline
Copy Constructor.
Definition at line 119 of file DataLogger.hpp.
References wb_data_logger::comment, wb_data_logger::currentSection, wb_data_logger::currentState, wb_data_logger::dataSet, wb_data_logger::loggerRunning, wb_data_logger::machineName, and wb_data_logger::shouldExit.
DataLogger() [4/4]
guWhiteboard::DataLogger::DataLogger (const std::string & t_str) inline
String Constructor.
Definition at line 294 of file DataLogger.hpp.
References from_string().
Member Function Documentation
comment() [1/3]
const char * guWhiteboard::DataLogger::comment () const inline
Definition at line 265 of file DataLogger.hpp.
References wb_data_logger::comment.
Referenced by DataLogger(), description(), operator=(), operator==(), and to_string().
comment() [2/3]
char & guWhiteboard::DataLogger::comment (int t_i) inline
Definition at line 275 of file DataLogger.hpp.
References wb_data_logger::comment.
comment() [3/3]
const char & guWhiteboard::DataLogger::comment (int t_i) const inline
Definition at line 280 of file DataLogger.hpp.
References wb_data_logger::comment.
comment_size()
size_t guWhiteboard::DataLogger::comment_size () const inline
Definition at line 270 of file DataLogger.hpp.
currentSection() [1/2]
uint32_t & guWhiteboard::DataLogger::currentSection () inline
Definition at line 205 of file DataLogger.hpp.
References wb_data_logger::currentSection.
Referenced by DataLogger(), description(), operator=(), operator==(), and to_string().
currentSection() [2/2]
const uint32_t & guWhiteboard::DataLogger::currentSection () const inline
Definition at line 210 of file DataLogger.hpp.
References wb_data_logger::currentSection.
currentState() [1/2]
uint32_t & guWhiteboard::DataLogger::currentState () inline
Definition at line 190 of file DataLogger.hpp.
References wb_data_logger::currentState.
Referenced by DataLogger(), description(), operator=(), operator==(), and to_string().
currentState() [2/2]
const uint32_t & guWhiteboard::DataLogger::currentState () const inline
Definition at line 195 of file DataLogger.hpp.
References wb_data_logger::currentState.
dataSet() [1/2]
uint8_t & guWhiteboard::DataLogger::dataSet () inline
Definition at line 220 of file DataLogger.hpp.
References wb_data_logger::dataSet.
Referenced by DataLogger(), description(), operator=(), operator==(), and to_string().
dataSet() [2/2]
const uint8_t & guWhiteboard::DataLogger::dataSet () const inline
Definition at line 225 of file DataLogger.hpp.
References wb_data_logger::dataSet.
description()
std::string guWhiteboard::DataLogger::description () inline
USE_WB_DATA_LOGGER_C_CONVERSION
Definition at line 299 of file DataLogger.hpp.
References comment(), currentSection(), currentState(), DATA_LOGGER_DESC_BUFFER_SIZE, dataSet(), loggerRunning(), machineName(), shouldExit(), and wb_data_logger_description().
from_string()
void guWhiteboard::DataLogger::from_string (const std::string & t_str) inline
USE_WB_DATA_LOGGER_C_CONVERSION
Definition at line 369 of file DataLogger.hpp.
References wb_data_logger::comment, DATA_LOGGER_DESC_BUFFER_SIZE, wb_data_logger::machineName, set_currentSection(), set_currentState(), set_dataSet(), set_loggerRunning(), and set_shouldExit().
Referenced by DataLogger().
loggerRunning() [1/2]
bool & guWhiteboard::DataLogger::loggerRunning () inline
Definition at line 235 of file DataLogger.hpp.
References wb_data_logger::loggerRunning.
Referenced by DataLogger(), description(), operator=(), operator==(), and to_string().
loggerRunning() [2/2]
const bool & guWhiteboard::DataLogger::loggerRunning () const inline
Definition at line 240 of file DataLogger.hpp.
References wb_data_logger::loggerRunning.
machineName() [1/3]
const char * guWhiteboard::DataLogger::machineName () const inline
Definition at line 165 of file DataLogger.hpp.
References wb_data_logger::machineName.
Referenced by DataLogger(), description(), operator=(), operator==(), and to_string().
machineName() [2/3]
char & guWhiteboard::DataLogger::machineName (int t_i) inline
Definition at line 175 of file DataLogger.hpp.
References wb_data_logger::machineName.
machineName() [3/3]
const char & guWhiteboard::DataLogger::machineName (int t_i) const inline
Definition at line 180 of file DataLogger.hpp.
References wb_data_logger::machineName.
machineName_size()
size_t guWhiteboard::DataLogger::machineName_size () const inline
Definition at line 170 of file DataLogger.hpp.
operator!=() [1/2]
bool guWhiteboard::DataLogger::operator!= (const DataLogger & t_other) const inline
Definition at line 150 of file DataLogger.hpp.
operator!=() [2/2]
bool guWhiteboard::DataLogger::operator!= (const wb_data_logger & t_other) const inline
Definition at line 160 of file DataLogger.hpp.
operator=() [1/2]
DataLogger & guWhiteboard::DataLogger::operator= (const DataLogger & t_other) inline
Copy Assignment Operator.
Definition at line 126 of file DataLogger.hpp.
References comment(), currentSection(), currentState(), dataSet(), loggerRunning(), machineName(), and shouldExit().
operator=() [2/2]
DataLogger & guWhiteboard::DataLogger::operator= (const struct wb_data_logger & t_other) inline
Copy Assignment Operator.
Definition at line 134 of file DataLogger.hpp.
References wb_data_logger::comment, wb_data_logger::currentSection, wb_data_logger::currentState, wb_data_logger::dataSet, wb_data_logger::loggerRunning, wb_data_logger::machineName, and wb_data_logger::shouldExit.
operator==() [1/2]
bool guWhiteboard::DataLogger::operator== (const DataLogger & t_other) const inline
Definition at line 139 of file DataLogger.hpp.
References comment(), currentSection(), currentState(), dataSet(), loggerRunning(), machineName(), and shouldExit().
operator==() [2/2]
bool guWhiteboard::DataLogger::operator== (const wb_data_logger & t_other) const inline
Definition at line 155 of file DataLogger.hpp.
References DataLogger().
set_comment()
void guWhiteboard::DataLogger::set_comment (const char * t_newValue) inline
Definition at line 285 of file DataLogger.hpp.
References wb_data_logger::comment.
set_currentSection()
void guWhiteboard::DataLogger::set_currentSection (const uint32_t & t_newValue) inline
Definition at line 215 of file DataLogger.hpp.
References wb_data_logger::currentSection.
Referenced by from_string().
set_currentState()
void guWhiteboard::DataLogger::set_currentState (const uint32_t & t_newValue) inline
Definition at line 200 of file DataLogger.hpp.
References wb_data_logger::currentState.
Referenced by from_string().
set_dataSet()
void guWhiteboard::DataLogger::set_dataSet (const uint8_t & t_newValue) inline
Definition at line 230 of file DataLogger.hpp.
References wb_data_logger::dataSet.
Referenced by from_string().
set_loggerRunning()
void guWhiteboard::DataLogger::set_loggerRunning (const bool & t_newValue) inline
Definition at line 245 of file DataLogger.hpp.
References wb_data_logger::loggerRunning.
Referenced by from_string().
set_machineName()
void guWhiteboard::DataLogger::set_machineName (const char * t_newValue) inline
Definition at line 185 of file DataLogger.hpp.
References wb_data_logger::machineName.
set_shouldExit()
void guWhiteboard::DataLogger::set_shouldExit (const bool & t_newValue) inline
Definition at line 260 of file DataLogger.hpp.
References wb_data_logger::shouldExit.
Referenced by from_string().
shouldExit() [1/2]
bool & guWhiteboard::DataLogger::shouldExit () inline
Definition at line 250 of file DataLogger.hpp.
References wb_data_logger::shouldExit.
Referenced by DataLogger(), description(), operator=(), operator==(), and to_string().
shouldExit() [2/2]
const bool & guWhiteboard::DataLogger::shouldExit () const inline
Definition at line 255 of file DataLogger.hpp.
References wb_data_logger::shouldExit.
to_string()
std::string guWhiteboard::DataLogger::to_string () inline
USE_WB_DATA_LOGGER_C_CONVERSION
Definition at line 332 of file DataLogger.hpp.
References comment(), currentSection(), currentState(), DATA_LOGGER_TO_STRING_BUFFER_SIZE, dataSet(), loggerRunning(), machineName(), shouldExit(), and wb_data_logger_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/DataLogger.hpp