gusimplewhiteboard: guWhiteboard::VisionDetectionLineArray Class Reference
guWhiteboard::VisionDetectionLineArray Class Reference
Provides a C++ wrapper around wb_vision_detection_line_array.
#include <VisionDetectionLineArray.hpp>
Public Member Functions
VisionDetectionLineArray (uint8_t t_numLines=0, const struct wb_pixel_coordinate_line t_lines[7]=NULLPTR)
Create a new VisionDetectionLineArray.
VisionDetectionLineArray (const VisionDetectionLineArray &t_other)
Copy Constructor.
VisionDetectionLineArray (const struct wb_vision_detection_line_array &t_other)
Copy Constructor.
VisionDetectionLineArray & operator= (const VisionDetectionLineArray &t_other)
Copy Assignment Operator.
VisionDetectionLineArray & operator= (const struct wb_vision_detection_line_array &t_other)
Copy Assignment Operator.
bool operator== (const VisionDetectionLineArray &t_other) const
bool operator!= (const VisionDetectionLineArray &t_other) const
bool operator== (const wb_vision_detection_line_array &t_other) const
bool operator!= (const wb_vision_detection_line_array &t_other) const
uint8_t & numLines ()
const uint8_t & numLines () const
void set_numLines (const uint8_t &t_newValue)
const PixelCoordinateLine * lines () const
size_t lines_size () const
PixelCoordinateLine & lines (int t_i)
const PixelCoordinateLine & lines (int t_i) const
void set_lines (const PixelCoordinateLine *t_newValue)
void set_lines (const PixelCoordinateLine &t_newValue, int t_i)
VisionDetectionLineArray (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_vision_detection_line_array
uint8_t numLines
The number of lines reported on the camera.
struct wb_pixel_coordinate_line lines [7]
Lines reported from the camera.
Detailed Description
Provides a C++ wrapper around wb_vision_detection_line_array.
Definition at line 85 of file VisionDetectionLineArray.hpp.
Constructor & Destructor Documentation
VisionDetectionLineArray() [1/4]
guWhiteboard::VisionDetectionLineArray::VisionDetectionLineArray (uint8_t t_numLines = 0, const struct wb_pixel_coordinate_line t_lines[7] = NULLPTR) inline
Create a new VisionDetectionLineArray.
Definition at line 107 of file VisionDetectionLineArray.hpp.
Referenced by operator==().
VisionDetectionLineArray() [2/4]
guWhiteboard::VisionDetectionLineArray::VisionDetectionLineArray (const VisionDetectionLineArray & t_other) inline
Copy Constructor.
Definition at line 114 of file VisionDetectionLineArray.hpp.
References lines(), and numLines().
VisionDetectionLineArray() [3/4]
guWhiteboard::VisionDetectionLineArray::VisionDetectionLineArray (const struct wb_vision_detection_line_array & t_other) inline
Copy Constructor.
Definition at line 121 of file VisionDetectionLineArray.hpp.
References wb_vision_detection_line_array::lines, and wb_vision_detection_line_array::numLines.
VisionDetectionLineArray() [4/4]
guWhiteboard::VisionDetectionLineArray::VisionDetectionLineArray (const std::string & t_str) inline
String Constructor.
Definition at line 218 of file VisionDetectionLineArray.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::VisionDetectionLineArray::description () inline
USE_WB_VISION_DETECTION_LINE_ARRAY_C_CONVERSION
Definition at line 223 of file VisionDetectionLineArray.hpp.
References description(), lines(), numLines(), VISION_DETECTION_LINE_ARRAY_DESC_BUFFER_SIZE, VISION_DETECTION_LINE_ARRAY_LINES_ARRAY_SIZE, and wb_vision_detection_line_array_description().
Referenced by description().
from_string()
void guWhiteboard::VisionDetectionLineArray::from_string (const std::string & t_str) inline
USE_WB_VISION_DETECTION_LINE_ARRAY_C_CONVERSION
Definition at line 269 of file VisionDetectionLineArray.hpp.
References guWhiteboard::PixelCoordinateLine::from_string(), set_lines(), set_numLines(), VISION_DETECTION_LINE_ARRAY_DESC_BUFFER_SIZE, and VISION_DETECTION_LINE_ARRAY_LINES_ARRAY_SIZE.
Referenced by VisionDetectionLineArray(), and guWhiteboard::VisionDetectionLines::from_string().
lines() [1/3]
const PixelCoordinateLine * guWhiteboard::VisionDetectionLineArray::lines () const inline
Definition at line 184 of file VisionDetectionLineArray.hpp.
References wb_vision_detection_line_array::lines.
Referenced by VisionDetectionLineArray(), description(), operator=(), operator==(), and to_string().
lines() [2/3]
PixelCoordinateLine & guWhiteboard::VisionDetectionLineArray::lines (int t_i) inline
Definition at line 194 of file VisionDetectionLineArray.hpp.
References wb_vision_detection_line_array::lines.
lines() [3/3]
const PixelCoordinateLine & guWhiteboard::VisionDetectionLineArray::lines (int t_i) const inline
Definition at line 199 of file VisionDetectionLineArray.hpp.
References wb_vision_detection_line_array::lines.
lines_size()
size_t guWhiteboard::VisionDetectionLineArray::lines_size () const inline
Definition at line 189 of file VisionDetectionLineArray.hpp.
References VISION_DETECTION_LINE_ARRAY_LINES_ARRAY_SIZE.
numLines() [1/2]
uint8_t & guWhiteboard::VisionDetectionLineArray::numLines () inline
Definition at line 169 of file VisionDetectionLineArray.hpp.
References wb_vision_detection_line_array::numLines.
Referenced by VisionDetectionLineArray(), description(), operator=(), operator==(), and to_string().
numLines() [2/2]
const uint8_t & guWhiteboard::VisionDetectionLineArray::numLines () const inline
Definition at line 174 of file VisionDetectionLineArray.hpp.
References wb_vision_detection_line_array::numLines.
operator!=() [1/2]
bool guWhiteboard::VisionDetectionLineArray::operator!= (const VisionDetectionLineArray & t_other) const inline
Definition at line 154 of file VisionDetectionLineArray.hpp.
operator!=() [2/2]
bool guWhiteboard::VisionDetectionLineArray::operator!= (const wb_vision_detection_line_array & t_other) const inline
Definition at line 164 of file VisionDetectionLineArray.hpp.
operator=() [1/2]
VisionDetectionLineArray & guWhiteboard::VisionDetectionLineArray::operator= (const struct wb_vision_detection_line_array & t_other) inline
Copy Assignment Operator.
Definition at line 136 of file VisionDetectionLineArray.hpp.
References wb_vision_detection_line_array::lines, and wb_vision_detection_line_array::numLines.
operator=() [2/2]
VisionDetectionLineArray & guWhiteboard::VisionDetectionLineArray::operator= (const VisionDetectionLineArray & t_other) inline
Copy Assignment Operator.
Definition at line 128 of file VisionDetectionLineArray.hpp.
References lines(), and numLines().
operator==() [1/2]
bool guWhiteboard::VisionDetectionLineArray::operator== (const VisionDetectionLineArray & t_other) const inline
Definition at line 141 of file VisionDetectionLineArray.hpp.
References lines(), and numLines().
operator==() [2/2]
bool guWhiteboard::VisionDetectionLineArray::operator== (const wb_vision_detection_line_array & t_other) const inline
Definition at line 159 of file VisionDetectionLineArray.hpp.
References VisionDetectionLineArray().
set_lines() [1/2]
void guWhiteboard::VisionDetectionLineArray::set_lines (const PixelCoordinateLine & t_newValue, int t_i) inline
Definition at line 209 of file VisionDetectionLineArray.hpp.
References wb_vision_detection_line_array::lines.
set_lines() [2/2]
void guWhiteboard::VisionDetectionLineArray::set_lines (const PixelCoordinateLine * t_newValue) inline
Definition at line 204 of file VisionDetectionLineArray.hpp.
References wb_vision_detection_line_array::lines, and VISION_DETECTION_LINE_ARRAY_LINES_ARRAY_SIZE.
Referenced by from_string().
set_numLines()
void guWhiteboard::VisionDetectionLineArray::set_numLines (const uint8_t & t_newValue) inline
Definition at line 179 of file VisionDetectionLineArray.hpp.
References wb_vision_detection_line_array::numLines.
Referenced by from_string().
to_string()
std::string guWhiteboard::VisionDetectionLineArray::to_string () inline
USE_WB_VISION_DETECTION_LINE_ARRAY_C_CONVERSION
Definition at line 244 of file VisionDetectionLineArray.hpp.
References lines(), numLines(), to_string(), VISION_DETECTION_LINE_ARRAY_LINES_ARRAY_SIZE, VISION_DETECTION_LINE_ARRAY_TO_STRING_BUFFER_SIZE, and wb_vision_detection_line_array_to_string().
Referenced by to_string().
The documentation for this class was generated from the following file:
typeClassDefs/VisionDetectionLineArray.hpp