gusimplewhiteboard: guWhiteboard::SENSORSTorsoJointSensors Class Reference
guWhiteboard::SENSORSTorsoJointSensors Class Reference
Provides a C++ wrapper around wb_sensors_torsojointsensors.
#include <SENSORSTorsoJointSensors.hpp>
Public Member Functions
SENSORSTorsoJointSensors (float t_HeadYaw=0.0f, float t_HeadPitch=0.0f, float t_LShoulderPitch=0.0f, float t_LShoulderRoll=0.0f, float t_LElbowYaw=0.0f, float t_LElbowRoll=0.0f, float t_RShoulderPitch=0.0f, float t_RShoulderRoll=0.0f, float t_RElbowYaw=0.0f, float t_RElbowRoll=0.0f, float t_LWristYaw=0.0f, float t_RWristYaw=0.0f)
Create a new SENSORSTorsoJointSensors.
SENSORSTorsoJointSensors (const SENSORSTorsoJointSensors &t_other)
Copy Constructor.
SENSORSTorsoJointSensors (const struct wb_sensors_torsojointsensors &t_other)
Copy Constructor.
SENSORSTorsoJointSensors & operator= (const SENSORSTorsoJointSensors &t_other)
Copy Assignment Operator.
SENSORSTorsoJointSensors & operator= (const struct wb_sensors_torsojointsensors &t_other)
Copy Assignment Operator.
bool operator== (const SENSORSTorsoJointSensors &t_other) const
bool operator!= (const SENSORSTorsoJointSensors &t_other) const
bool operator== (const wb_sensors_torsojointsensors &t_other) const
bool operator!= (const wb_sensors_torsojointsensors &t_other) const
float & HeadYaw ()
const float & HeadYaw () const
void set_HeadYaw (const float &t_newValue)
float & HeadPitch ()
const float & HeadPitch () const
void set_HeadPitch (const float &t_newValue)
float & LShoulderPitch ()
const float & LShoulderPitch () const
void set_LShoulderPitch (const float &t_newValue)
float & LShoulderRoll ()
const float & LShoulderRoll () const
void set_LShoulderRoll (const float &t_newValue)
float & LElbowYaw ()
const float & LElbowYaw () const
void set_LElbowYaw (const float &t_newValue)
float & LElbowRoll ()
const float & LElbowRoll () const
void set_LElbowRoll (const float &t_newValue)
float & RShoulderPitch ()
const float & RShoulderPitch () const
void set_RShoulderPitch (const float &t_newValue)
float & RShoulderRoll ()
const float & RShoulderRoll () const
void set_RShoulderRoll (const float &t_newValue)
float & RElbowYaw ()
const float & RElbowYaw () const
void set_RElbowYaw (const float &t_newValue)
float & RElbowRoll ()
const float & RElbowRoll () const
void set_RElbowRoll (const float &t_newValue)
float & LWristYaw ()
const float & LWristYaw () const
void set_LWristYaw (const float &t_newValue)
float & RWristYaw ()
const float & RWristYaw () const
void set_RWristYaw (const float &t_newValue)
SENSORSTorsoJointSensors (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_sensors_torsojointsensors
float HeadYaw
Head pos in RAD.
float HeadPitch
Head pos in RAD.
float LShoulderPitch
pitch of the shoulder joint (left) RAD
float LShoulderRoll
roll of the shoulder joint (left) RAD
float LElbowYaw
yaw of the elbow joint (left) RAD
float LElbowRoll
roll of the elbow joint (left) RAD
float RShoulderPitch
pitch of the shoulder joint (right) RAD
float RShoulderRoll
roll of the shoulder joint (right) RAD
float RElbowYaw
yaw of the elbow joint (right) RAD
float RElbowRoll
roll of the elbow joint (right) RAD
float LWristYaw
yaw of the wrist joint (left)
float RWristYaw
yaw of the wrist joint (right)
Detailed Description
Provides a C++ wrapper around wb_sensors_torsojointsensors.
Definition at line 84 of file SENSORSTorsoJointSensors.hpp.
Constructor & Destructor Documentation
SENSORSTorsoJointSensors() [1/4]
guWhiteboard::SENSORSTorsoJointSensors::SENSORSTorsoJointSensors (float t_HeadYaw = 0.0f, float t_HeadPitch = 0.0f, float t_LShoulderPitch = 0.0f, float t_LShoulderRoll = 0.0f, float t_LElbowYaw = 0.0f, float t_LElbowRoll = 0.0f, float t_RShoulderPitch = 0.0f, float t_RShoulderRoll = 0.0f, float t_RElbowYaw = 0.0f, float t_RElbowRoll = 0.0f, float t_LWristYaw = 0.0f, float t_RWristYaw = 0.0f) inline
Create a new SENSORSTorsoJointSensors.
Definition at line 111 of file SENSORSTorsoJointSensors.hpp.
Referenced by operator==().
SENSORSTorsoJointSensors() [2/4]
guWhiteboard::SENSORSTorsoJointSensors::SENSORSTorsoJointSensors (const SENSORSTorsoJointSensors & t_other) inline
Copy Constructor.
Definition at line 118 of file SENSORSTorsoJointSensors.hpp.
References HeadPitch(), HeadYaw(), LElbowRoll(), LElbowYaw(), LShoulderPitch(), LShoulderRoll(), LWristYaw(), RElbowRoll(), RElbowYaw(), RShoulderPitch(), RShoulderRoll(), and RWristYaw().
SENSORSTorsoJointSensors() [3/4]
guWhiteboard::SENSORSTorsoJointSensors::SENSORSTorsoJointSensors (const struct wb_sensors_torsojointsensors & t_other) inline
Copy Constructor.
Definition at line 125 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::HeadPitch, wb_sensors_torsojointsensors::HeadYaw, wb_sensors_torsojointsensors::LElbowRoll, wb_sensors_torsojointsensors::LElbowYaw, wb_sensors_torsojointsensors::LShoulderPitch, wb_sensors_torsojointsensors::LShoulderRoll, wb_sensors_torsojointsensors::LWristYaw, wb_sensors_torsojointsensors::RElbowRoll, wb_sensors_torsojointsensors::RElbowYaw, wb_sensors_torsojointsensors::RShoulderPitch, wb_sensors_torsojointsensors::RShoulderRoll, and wb_sensors_torsojointsensors::RWristYaw.
SENSORSTorsoJointSensors() [4/4]
guWhiteboard::SENSORSTorsoJointSensors::SENSORSTorsoJointSensors (const std::string & t_str) inline
String Constructor.
Definition at line 360 of file SENSORSTorsoJointSensors.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::SENSORSTorsoJointSensors::description () inline
USE_WB_SENSORS_TORSOJOINTSENSORS_C_CONVERSION
Definition at line 365 of file SENSORSTorsoJointSensors.hpp.
References HeadPitch(), HeadYaw(), LElbowRoll(), LElbowYaw(), LShoulderPitch(), LShoulderRoll(), LWristYaw(), RElbowRoll(), RElbowYaw(), RShoulderPitch(), RShoulderRoll(), RWristYaw(), SENSORS_TORSOJOINTSENSORS_DESC_BUFFER_SIZE, and wb_sensors_torsojointsensors_description().
from_string()
void guWhiteboard::SENSORSTorsoJointSensors::from_string (const std::string & t_str) inline
USE_WB_SENSORS_TORSOJOINTSENSORS_C_CONVERSION
Definition at line 439 of file SENSORSTorsoJointSensors.hpp.
References SENSORS_TORSOJOINTSENSORS_DESC_BUFFER_SIZE, set_HeadPitch(), set_HeadYaw(), set_LElbowRoll(), set_LElbowYaw(), set_LShoulderPitch(), set_LShoulderRoll(), set_LWristYaw(), set_RElbowRoll(), set_RElbowYaw(), set_RShoulderPitch(), set_RShoulderRoll(), and set_RWristYaw().
Referenced by SENSORSTorsoJointSensors().
HeadPitch() [1/2]
float & guWhiteboard::SENSORSTorsoJointSensors::HeadPitch () inline
Definition at line 191 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::HeadPitch.
Referenced by SENSORSTorsoJointSensors(), description(), operator=(), operator==(), and to_string().
HeadPitch() [2/2]
const float & guWhiteboard::SENSORSTorsoJointSensors::HeadPitch () const inline
Definition at line 196 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::HeadPitch.
HeadYaw() [1/2]
float & guWhiteboard::SENSORSTorsoJointSensors::HeadYaw () inline
Definition at line 176 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::HeadYaw.
Referenced by SENSORSTorsoJointSensors(), description(), operator=(), operator==(), and to_string().
HeadYaw() [2/2]
const float & guWhiteboard::SENSORSTorsoJointSensors::HeadYaw () const inline
Definition at line 181 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::HeadYaw.
LElbowRoll() [1/2]
float & guWhiteboard::SENSORSTorsoJointSensors::LElbowRoll () inline
Definition at line 251 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::LElbowRoll.
Referenced by SENSORSTorsoJointSensors(), description(), operator=(), operator==(), and to_string().
LElbowRoll() [2/2]
const float & guWhiteboard::SENSORSTorsoJointSensors::LElbowRoll () const inline
Definition at line 256 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::LElbowRoll.
LElbowYaw() [1/2]
float & guWhiteboard::SENSORSTorsoJointSensors::LElbowYaw () inline
Definition at line 236 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::LElbowYaw.
Referenced by SENSORSTorsoJointSensors(), description(), operator=(), operator==(), and to_string().
LElbowYaw() [2/2]
const float & guWhiteboard::SENSORSTorsoJointSensors::LElbowYaw () const inline
Definition at line 241 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::LElbowYaw.
LShoulderPitch() [1/2]
float & guWhiteboard::SENSORSTorsoJointSensors::LShoulderPitch () inline
Definition at line 206 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::LShoulderPitch.
Referenced by SENSORSTorsoJointSensors(), description(), operator=(), operator==(), and to_string().
LShoulderPitch() [2/2]
const float & guWhiteboard::SENSORSTorsoJointSensors::LShoulderPitch () const inline
Definition at line 211 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::LShoulderPitch.
LShoulderRoll() [1/2]
float & guWhiteboard::SENSORSTorsoJointSensors::LShoulderRoll () inline
Definition at line 221 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::LShoulderRoll.
Referenced by SENSORSTorsoJointSensors(), description(), operator=(), operator==(), and to_string().
LShoulderRoll() [2/2]
const float & guWhiteboard::SENSORSTorsoJointSensors::LShoulderRoll () const inline
Definition at line 226 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::LShoulderRoll.
LWristYaw() [1/2]
float & guWhiteboard::SENSORSTorsoJointSensors::LWristYaw () inline
Definition at line 326 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::LWristYaw.
Referenced by SENSORSTorsoJointSensors(), description(), operator=(), operator==(), and to_string().
LWristYaw() [2/2]
const float & guWhiteboard::SENSORSTorsoJointSensors::LWristYaw () const inline
Definition at line 331 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::LWristYaw.
operator!=() [1/2]
bool guWhiteboard::SENSORSTorsoJointSensors::operator!= (const SENSORSTorsoJointSensors & t_other) const inline
Definition at line 161 of file SENSORSTorsoJointSensors.hpp.
operator!=() [2/2]
bool guWhiteboard::SENSORSTorsoJointSensors::operator!= (const wb_sensors_torsojointsensors & t_other) const inline
Definition at line 171 of file SENSORSTorsoJointSensors.hpp.
operator=() [1/2]
SENSORSTorsoJointSensors & guWhiteboard::SENSORSTorsoJointSensors::operator= (const SENSORSTorsoJointSensors & t_other) inline
Copy Assignment Operator.
Definition at line 132 of file SENSORSTorsoJointSensors.hpp.
References HeadPitch(), HeadYaw(), LElbowRoll(), LElbowYaw(), LShoulderPitch(), LShoulderRoll(), LWristYaw(), RElbowRoll(), RElbowYaw(), RShoulderPitch(), RShoulderRoll(), and RWristYaw().
operator=() [2/2]
SENSORSTorsoJointSensors & guWhiteboard::SENSORSTorsoJointSensors::operator= (const struct wb_sensors_torsojointsensors & t_other) inline
Copy Assignment Operator.
Definition at line 140 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::HeadPitch, wb_sensors_torsojointsensors::HeadYaw, wb_sensors_torsojointsensors::LElbowRoll, wb_sensors_torsojointsensors::LElbowYaw, wb_sensors_torsojointsensors::LShoulderPitch, wb_sensors_torsojointsensors::LShoulderRoll, wb_sensors_torsojointsensors::LWristYaw, wb_sensors_torsojointsensors::RElbowRoll, wb_sensors_torsojointsensors::RElbowYaw, wb_sensors_torsojointsensors::RShoulderPitch, wb_sensors_torsojointsensors::RShoulderRoll, and wb_sensors_torsojointsensors::RWristYaw.
operator==() [1/2]
bool guWhiteboard::SENSORSTorsoJointSensors::operator== (const SENSORSTorsoJointSensors & t_other) const inline
Definition at line 145 of file SENSORSTorsoJointSensors.hpp.
References HeadPitch(), HeadYaw(), LElbowRoll(), LElbowYaw(), LShoulderPitch(), LShoulderRoll(), LWristYaw(), RElbowRoll(), RElbowYaw(), RShoulderPitch(), RShoulderRoll(), and RWristYaw().
operator==() [2/2]
bool guWhiteboard::SENSORSTorsoJointSensors::operator== (const wb_sensors_torsojointsensors & t_other) const inline
Definition at line 166 of file SENSORSTorsoJointSensors.hpp.
References SENSORSTorsoJointSensors().
RElbowRoll() [1/2]
float & guWhiteboard::SENSORSTorsoJointSensors::RElbowRoll () inline
Definition at line 311 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::RElbowRoll.
Referenced by SENSORSTorsoJointSensors(), description(), operator=(), operator==(), and to_string().
RElbowRoll() [2/2]
const float & guWhiteboard::SENSORSTorsoJointSensors::RElbowRoll () const inline
Definition at line 316 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::RElbowRoll.
RElbowYaw() [1/2]
float & guWhiteboard::SENSORSTorsoJointSensors::RElbowYaw () inline
Definition at line 296 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::RElbowYaw.
Referenced by SENSORSTorsoJointSensors(), description(), operator=(), operator==(), and to_string().
RElbowYaw() [2/2]
const float & guWhiteboard::SENSORSTorsoJointSensors::RElbowYaw () const inline
Definition at line 301 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::RElbowYaw.
RShoulderPitch() [1/2]
float & guWhiteboard::SENSORSTorsoJointSensors::RShoulderPitch () inline
Definition at line 266 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::RShoulderPitch.
Referenced by SENSORSTorsoJointSensors(), description(), operator=(), operator==(), and to_string().
RShoulderPitch() [2/2]
const float & guWhiteboard::SENSORSTorsoJointSensors::RShoulderPitch () const inline
Definition at line 271 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::RShoulderPitch.
RShoulderRoll() [1/2]
float & guWhiteboard::SENSORSTorsoJointSensors::RShoulderRoll () inline
Definition at line 281 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::RShoulderRoll.
Referenced by SENSORSTorsoJointSensors(), description(), operator=(), operator==(), and to_string().
RShoulderRoll() [2/2]
const float & guWhiteboard::SENSORSTorsoJointSensors::RShoulderRoll () const inline
Definition at line 286 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::RShoulderRoll.
RWristYaw() [1/2]
float & guWhiteboard::SENSORSTorsoJointSensors::RWristYaw () inline
Definition at line 341 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::RWristYaw.
Referenced by SENSORSTorsoJointSensors(), description(), operator=(), operator==(), and to_string().
RWristYaw() [2/2]
const float & guWhiteboard::SENSORSTorsoJointSensors::RWristYaw () const inline
Definition at line 346 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::RWristYaw.
set_HeadPitch()
void guWhiteboard::SENSORSTorsoJointSensors::set_HeadPitch (const float & t_newValue) inline
Definition at line 201 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::HeadPitch.
Referenced by from_string().
set_HeadYaw()
void guWhiteboard::SENSORSTorsoJointSensors::set_HeadYaw (const float & t_newValue) inline
Definition at line 186 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::HeadYaw.
Referenced by from_string().
set_LElbowRoll()
void guWhiteboard::SENSORSTorsoJointSensors::set_LElbowRoll (const float & t_newValue) inline
Definition at line 261 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::LElbowRoll.
Referenced by from_string().
set_LElbowYaw()
void guWhiteboard::SENSORSTorsoJointSensors::set_LElbowYaw (const float & t_newValue) inline
Definition at line 246 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::LElbowYaw.
Referenced by from_string().
set_LShoulderPitch()
void guWhiteboard::SENSORSTorsoJointSensors::set_LShoulderPitch (const float & t_newValue) inline
Definition at line 216 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::LShoulderPitch.
Referenced by from_string().
set_LShoulderRoll()
void guWhiteboard::SENSORSTorsoJointSensors::set_LShoulderRoll (const float & t_newValue) inline
Definition at line 231 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::LShoulderRoll.
Referenced by from_string().
set_LWristYaw()
void guWhiteboard::SENSORSTorsoJointSensors::set_LWristYaw (const float & t_newValue) inline
Definition at line 336 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::LWristYaw.
Referenced by from_string().
set_RElbowRoll()
void guWhiteboard::SENSORSTorsoJointSensors::set_RElbowRoll (const float & t_newValue) inline
Definition at line 321 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::RElbowRoll.
Referenced by from_string().
set_RElbowYaw()
void guWhiteboard::SENSORSTorsoJointSensors::set_RElbowYaw (const float & t_newValue) inline
Definition at line 306 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::RElbowYaw.
Referenced by from_string().
set_RShoulderPitch()
void guWhiteboard::SENSORSTorsoJointSensors::set_RShoulderPitch (const float & t_newValue) inline
Definition at line 276 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::RShoulderPitch.
Referenced by from_string().
set_RShoulderRoll()
void guWhiteboard::SENSORSTorsoJointSensors::set_RShoulderRoll (const float & t_newValue) inline
Definition at line 291 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::RShoulderRoll.
Referenced by from_string().
set_RWristYaw()
void guWhiteboard::SENSORSTorsoJointSensors::set_RWristYaw (const float & t_newValue) inline
Definition at line 351 of file SENSORSTorsoJointSensors.hpp.
References wb_sensors_torsojointsensors::RWristYaw.
Referenced by from_string().
to_string()
std::string guWhiteboard::SENSORSTorsoJointSensors::to_string () inline
USE_WB_SENSORS_TORSOJOINTSENSORS_C_CONVERSION
Definition at line 400 of file SENSORSTorsoJointSensors.hpp.
References HeadPitch(), HeadYaw(), LElbowRoll(), LElbowYaw(), LShoulderPitch(), LShoulderRoll(), LWristYaw(), RElbowRoll(), RElbowYaw(), RShoulderPitch(), RShoulderRoll(), RWristYaw(), SENSORS_TORSOJOINTSENSORS_TO_STRING_BUFFER_SIZE, and wb_sensors_torsojointsensors_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/SENSORSTorsoJointSensors.hpp