gusimplewhiteboard: guWhiteboard::NaoWalkStatus Class Reference
guWhiteboard::NaoWalkStatus Class Reference
Provides a C++ wrapper around wb_nao_walk_status.
#include <NaoWalkStatus.hpp>
Public Member Functions
NaoWalkStatus (enum WalkEngineState t_walkEngineState=wes_Disconnected, struct wb_odometry t_odometry=wb_odometry(), uint8_t t_odometryResetCounter=0)
Create a new NaoWalkStatus.
NaoWalkStatus (const NaoWalkStatus &t_other)
Copy Constructor.
NaoWalkStatus (const struct wb_nao_walk_status &t_other)
Copy Constructor.
NaoWalkStatus & operator= (const NaoWalkStatus &t_other)
Copy Assignment Operator.
NaoWalkStatus & operator= (const struct wb_nao_walk_status &t_other)
Copy Assignment Operator.
bool operator== (const NaoWalkStatus &t_other) const
bool operator!= (const NaoWalkStatus &t_other) const
bool operator== (const wb_nao_walk_status &t_other) const
bool operator!= (const wb_nao_walk_status &t_other) const
enum WalkEngineState & walkEngineState ()
enum WalkEngineState & walkEngineState () const
void set_walkEngineState (const enum WalkEngineState &t_newValue)
Odometry & odometry ()
const Odometry & odometry () const
void set_odometry (const Odometry &t_newValue)
uint8_t & odometryResetCounter ()
const uint8_t & odometryResetCounter () const
void set_odometryResetCounter (const uint8_t &t_newValue)
NaoWalkStatus (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_nao_walk_status
enum WalkEngineState walkEngineState
The current state of the walk engine, see enum documentation.
struct wb_odometry odometry
Current odometry object.
uint8_t odometryResetCounter
A counter used to reset the odometry object, change this value and send it via NaoWalkCommand to trigger an odometry reset.
Detailed Description
Provides a C++ wrapper around wb_nao_walk_status.
Definition at line 85 of file NaoWalkStatus.hpp.
Constructor & Destructor Documentation
NaoWalkStatus() [1/4]
guWhiteboard::NaoWalkStatus::NaoWalkStatus (enum WalkEngineState t_walkEngineState = wes_Disconnected, struct wb_odometry t_odometry = wb_odometry(), uint8_t t_odometryResetCounter = 0) inline
Create a new NaoWalkStatus.
Definition at line 103 of file NaoWalkStatus.hpp.
Referenced by operator==().
NaoWalkStatus() [2/4]
guWhiteboard::NaoWalkStatus::NaoWalkStatus (const NaoWalkStatus & t_other) inline
Copy Constructor.
Definition at line 110 of file NaoWalkStatus.hpp.
References odometry(), odometryResetCounter(), and walkEngineState().
NaoWalkStatus() [3/4]
guWhiteboard::NaoWalkStatus::NaoWalkStatus (const struct wb_nao_walk_status & t_other) inline
Copy Constructor.
Definition at line 117 of file NaoWalkStatus.hpp.
References wb_nao_walk_status::odometry, wb_nao_walk_status::odometryResetCounter, and wb_nao_walk_status::walkEngineState.
NaoWalkStatus() [4/4]
guWhiteboard::NaoWalkStatus::NaoWalkStatus (const std::string & t_str) inline
String Constructor.
Definition at line 208 of file NaoWalkStatus.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::NaoWalkStatus::description () inline
USE_WB_NAO_WALK_STATUS_C_CONVERSION
Definition at line 213 of file NaoWalkStatus.hpp.
References guWhiteboard::Odometry::description(), NAOWALKSTATUS_DESC_BUFFER_SIZE, odometry(), odometryResetCounter(), walkEngineState(), wb_nao_walk_status_description(), wes_Disconnected, wes_StoppedReady, wes_StoppedStanding, and wes_Walking.
from_string()
void guWhiteboard::NaoWalkStatus::from_string (const std::string & t_str) inline
USE_WB_NAO_WALK_STATUS_C_CONVERSION
Definition at line 293 of file NaoWalkStatus.hpp.
References guWhiteboard::Odometry::from_string(), NAOWALKSTATUS_DESC_BUFFER_SIZE, set_odometry(), set_odometryResetCounter(), set_walkEngineState(), wes_Disconnected, wes_StoppedReady, wes_StoppedStanding, and wes_Walking.
Referenced by NaoWalkStatus().
odometry() [1/2]
Odometry & guWhiteboard::NaoWalkStatus::odometry () inline
Definition at line 174 of file NaoWalkStatus.hpp.
References wb_nao_walk_status::odometry.
Referenced by NaoWalkStatus(), description(), operator=(), operator==(), and to_string().
odometry() [2/2]
const Odometry & guWhiteboard::NaoWalkStatus::odometry () const inline
Definition at line 179 of file NaoWalkStatus.hpp.
References wb_nao_walk_status::odometry.
odometryResetCounter() [1/2]
uint8_t & guWhiteboard::NaoWalkStatus::odometryResetCounter () inline
Definition at line 189 of file NaoWalkStatus.hpp.
References wb_nao_walk_status::odometryResetCounter.
Referenced by NaoWalkStatus(), description(), operator=(), operator==(), and to_string().
odometryResetCounter() [2/2]
const uint8_t & guWhiteboard::NaoWalkStatus::odometryResetCounter () const inline
Definition at line 194 of file NaoWalkStatus.hpp.
References wb_nao_walk_status::odometryResetCounter.
operator!=() [1/2]
bool guWhiteboard::NaoWalkStatus::operator!= (const NaoWalkStatus & t_other) const inline
Definition at line 144 of file NaoWalkStatus.hpp.
operator!=() [2/2]
bool guWhiteboard::NaoWalkStatus::operator!= (const wb_nao_walk_status & t_other) const inline
Definition at line 154 of file NaoWalkStatus.hpp.
operator=() [1/2]
NaoWalkStatus & guWhiteboard::NaoWalkStatus::operator= (const NaoWalkStatus & t_other) inline
Copy Assignment Operator.
Definition at line 124 of file NaoWalkStatus.hpp.
References odometry(), odometryResetCounter(), and walkEngineState().
operator=() [2/2]
NaoWalkStatus & guWhiteboard::NaoWalkStatus::operator= (const struct wb_nao_walk_status & t_other) inline
Copy Assignment Operator.
Definition at line 132 of file NaoWalkStatus.hpp.
References wb_nao_walk_status::odometry, wb_nao_walk_status::odometryResetCounter, and wb_nao_walk_status::walkEngineState.
operator==() [1/2]
bool guWhiteboard::NaoWalkStatus::operator== (const NaoWalkStatus & t_other) const inline
Definition at line 137 of file NaoWalkStatus.hpp.
References odometry(), odometryResetCounter(), and walkEngineState().
operator==() [2/2]
bool guWhiteboard::NaoWalkStatus::operator== (const wb_nao_walk_status & t_other) const inline
Definition at line 149 of file NaoWalkStatus.hpp.
References NaoWalkStatus().
set_odometry()
void guWhiteboard::NaoWalkStatus::set_odometry (const Odometry & t_newValue) inline
Definition at line 184 of file NaoWalkStatus.hpp.
References wb_nao_walk_status::odometry.
Referenced by from_string().
set_odometryResetCounter()
void guWhiteboard::NaoWalkStatus::set_odometryResetCounter (const uint8_t & t_newValue) inline
Definition at line 199 of file NaoWalkStatus.hpp.
References wb_nao_walk_status::odometryResetCounter.
Referenced by from_string().
set_walkEngineState()
void guWhiteboard::NaoWalkStatus::set_walkEngineState (const enum WalkEngineState & t_newValue) inline
Definition at line 169 of file NaoWalkStatus.hpp.
References wb_nao_walk_status::walkEngineState.
Referenced by from_string().
to_string()
std::string guWhiteboard::NaoWalkStatus::to_string () inline
USE_WB_NAO_WALK_STATUS_C_CONVERSION
Definition at line 251 of file NaoWalkStatus.hpp.
References NAOWALKSTATUS_TO_STRING_BUFFER_SIZE, odometry(), odometryResetCounter(), guWhiteboard::Odometry::to_string(), walkEngineState(), wb_nao_walk_status_to_string(), wes_Disconnected, wes_StoppedReady, wes_StoppedStanding, and wes_Walking.
walkEngineState() [1/2]
enum WalkEngineState & guWhiteboard::NaoWalkStatus::walkEngineState () inline
Definition at line 159 of file NaoWalkStatus.hpp.
References wb_nao_walk_status::walkEngineState.
Referenced by NaoWalkStatus(), description(), operator=(), operator==(), and to_string().
walkEngineState() [2/2]
enum WalkEngineState & guWhiteboard::NaoWalkStatus::walkEngineState () const inline
Definition at line 164 of file NaoWalkStatus.hpp.
References wb_nao_walk_status::walkEngineState.
The documentation for this class was generated from the following file:
typeClassDefs/NaoWalkStatus.hpp