gusimplewhiteboard: guWhiteboard::TeleoperationStatus Class Reference
guWhiteboard::TeleoperationStatus Class Reference
Provides a C++ wrapper around wb_teleoperation_status.
#include <TeleoperationStatus.hpp>
Public Member Functions
TeleoperationStatus (std::string t_sayString="")
Create a new TeleoperationStatus.
TeleoperationStatus (const TeleoperationStatus &t_other)
Copy Constructor.
TeleoperationStatus (const struct wb_teleoperation_status &t_other)
Copy Constructor.
TeleoperationStatus & operator= (const TeleoperationStatus &t_other)
Copy Assignment Operator.
TeleoperationStatus & operator= (const struct wb_teleoperation_status &t_other)
Copy Assignment Operator.
bool operator== (const TeleoperationStatus &t_other) const
bool operator!= (const TeleoperationStatus &t_other) const
bool operator== (const wb_teleoperation_status &t_other) const
bool operator!= (const wb_teleoperation_status &t_other) const
const char * sayString () const
size_t sayString_size () const
char & sayString (int t_i)
const char & sayString (int t_i) const
void set_sayString (const char *t_newValue)
TeleoperationStatus (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_teleoperation_status
char sayString [30]
String passed to Say_t.
Detailed Description
Provides a C++ wrapper around wb_teleoperation_status.
Definition at line 83 of file TeleoperationStatus.hpp.
Constructor & Destructor Documentation
TeleoperationStatus() [1/4]
guWhiteboard::TeleoperationStatus::TeleoperationStatus (std::string t_sayString = "") inline
Create a new TeleoperationStatus.
Definition at line 99 of file TeleoperationStatus.hpp.
Referenced by operator==().
TeleoperationStatus() [2/4]
guWhiteboard::TeleoperationStatus::TeleoperationStatus (const TeleoperationStatus & t_other) inline
Copy Constructor.
Definition at line 106 of file TeleoperationStatus.hpp.
References sayString().
TeleoperationStatus() [3/4]
guWhiteboard::TeleoperationStatus::TeleoperationStatus (const struct wb_teleoperation_status & t_other) inline
Copy Constructor.
Definition at line 113 of file TeleoperationStatus.hpp.
References wb_teleoperation_status::sayString.
TeleoperationStatus() [4/4]
guWhiteboard::TeleoperationStatus::TeleoperationStatus (const std::string & t_str) inline
String Constructor.
Definition at line 182 of file TeleoperationStatus.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::TeleoperationStatus::description () inline
USE_WB_TELEOPERATION_STATUS_C_CONVERSION
Definition at line 187 of file TeleoperationStatus.hpp.
References sayString(), TELEOPERATIONSTATUS_DESC_BUFFER_SIZE, and wb_teleoperation_status_description().
from_string()
void guWhiteboard::TeleoperationStatus::from_string (const std::string & t_str) inline
USE_WB_TELEOPERATION_STATUS_C_CONVERSION
Definition at line 225 of file TeleoperationStatus.hpp.
References wb_teleoperation_status::sayString, and TELEOPERATIONSTATUS_DESC_BUFFER_SIZE.
Referenced by TeleoperationStatus().
operator!=() [1/2]
bool guWhiteboard::TeleoperationStatus::operator!= (const TeleoperationStatus & t_other) const inline
Definition at line 138 of file TeleoperationStatus.hpp.
operator!=() [2/2]
bool guWhiteboard::TeleoperationStatus::operator!= (const wb_teleoperation_status & t_other) const inline
Definition at line 148 of file TeleoperationStatus.hpp.
operator=() [1/2]
TeleoperationStatus & guWhiteboard::TeleoperationStatus::operator= (const struct wb_teleoperation_status & t_other) inline
Copy Assignment Operator.
Definition at line 128 of file TeleoperationStatus.hpp.
References wb_teleoperation_status::sayString.
operator=() [2/2]
TeleoperationStatus & guWhiteboard::TeleoperationStatus::operator= (const TeleoperationStatus & t_other) inline
Copy Assignment Operator.
Definition at line 120 of file TeleoperationStatus.hpp.
References sayString().
operator==() [1/2]
bool guWhiteboard::TeleoperationStatus::operator== (const TeleoperationStatus & t_other) const inline
Definition at line 133 of file TeleoperationStatus.hpp.
References sayString().
operator==() [2/2]
bool guWhiteboard::TeleoperationStatus::operator== (const wb_teleoperation_status & t_other) const inline
Definition at line 143 of file TeleoperationStatus.hpp.
References TeleoperationStatus().
sayString() [1/3]
const char * guWhiteboard::TeleoperationStatus::sayString () const inline
Definition at line 153 of file TeleoperationStatus.hpp.
References wb_teleoperation_status::sayString.
Referenced by TeleoperationStatus(), description(), operator=(), operator==(), and to_string().
sayString() [2/3]
char & guWhiteboard::TeleoperationStatus::sayString (int t_i) inline
Definition at line 163 of file TeleoperationStatus.hpp.
References wb_teleoperation_status::sayString.
sayString() [3/3]
const char & guWhiteboard::TeleoperationStatus::sayString (int t_i) const inline
Definition at line 168 of file TeleoperationStatus.hpp.
References wb_teleoperation_status::sayString.
sayString_size()
size_t guWhiteboard::TeleoperationStatus::sayString_size () const inline
Definition at line 158 of file TeleoperationStatus.hpp.
set_sayString()
void guWhiteboard::TeleoperationStatus::set_sayString (const char * t_newValue) inline
Definition at line 173 of file TeleoperationStatus.hpp.
References wb_teleoperation_status::sayString.
to_string()
std::string guWhiteboard::TeleoperationStatus::to_string () inline
USE_WB_TELEOPERATION_STATUS_C_CONVERSION
Definition at line 204 of file TeleoperationStatus.hpp.
References sayString(), TELEOPERATIONSTATUS_TO_STRING_BUFFER_SIZE, and wb_teleoperation_status_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/TeleoperationStatus.hpp