gusimplewhiteboard: guWhiteboard::GuVrTeleopVulkanControl Class Reference
guWhiteboard::GuVrTeleopVulkanControl Class Reference
Provides a C++ wrapper around wb_gu_vr_teleop_vulkan_control.
#include <GuVrTeleopVulkanControl.hpp>
Public Member Functions
GuVrTeleopVulkanControl (enum VRControlMovementOptions t_movementOptions=VRResting, enum VRControlWalkingOptions t_walkingOptions=NUM_VR_CONTROL_WALKING_OPTIONS)
Create a new GuVrTeleopVulkanControl.
GuVrTeleopVulkanControl (const GuVrTeleopVulkanControl &t_other)
Copy Constructor.
GuVrTeleopVulkanControl (const struct wb_gu_vr_teleop_vulkan_control &t_other)
Copy Constructor.
GuVrTeleopVulkanControl & operator= (const GuVrTeleopVulkanControl &t_other)
Copy Assignment Operator.
GuVrTeleopVulkanControl & operator= (const struct wb_gu_vr_teleop_vulkan_control &t_other)
Copy Assignment Operator.
bool operator== (const GuVrTeleopVulkanControl &t_other) const
bool operator!= (const GuVrTeleopVulkanControl &t_other) const
bool operator== (const wb_gu_vr_teleop_vulkan_control &t_other) const
bool operator!= (const wb_gu_vr_teleop_vulkan_control &t_other) const
enum VRControlMovementOptions & movementOptions ()
enum VRControlMovementOptions & movementOptions () const
void set_movementOptions (const enum VRControlMovementOptions &t_newValue)
enum VRControlWalkingOptions & walkingOptions ()
enum VRControlWalkingOptions & walkingOptions () const
void set_walkingOptions (const enum VRControlWalkingOptions &t_newValue)
GuVrTeleopVulkanControl (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_gu_vr_teleop_vulkan_control
enum VRControlMovementOptions movementOptions
controls the robots movement
enum VRControlWalkingOptions walkingOptions
controls the direction of high-level walk commands
Detailed Description
Provides a C++ wrapper around wb_gu_vr_teleop_vulkan_control.
Definition at line 83 of file GuVrTeleopVulkanControl.hpp.
Constructor & Destructor Documentation
GuVrTeleopVulkanControl() [1/4]
guWhiteboard::GuVrTeleopVulkanControl::GuVrTeleopVulkanControl (enum VRControlMovementOptions t_movementOptions = VRResting, enum VRControlWalkingOptions t_walkingOptions = NUM_VR_CONTROL_WALKING_OPTIONS) inline
Create a new GuVrTeleopVulkanControl.
Definition at line 100 of file GuVrTeleopVulkanControl.hpp.
Referenced by operator==().
GuVrTeleopVulkanControl() [2/4]
guWhiteboard::GuVrTeleopVulkanControl::GuVrTeleopVulkanControl (const GuVrTeleopVulkanControl & t_other) inline
Copy Constructor.
Definition at line 107 of file GuVrTeleopVulkanControl.hpp.
References movementOptions(), and walkingOptions().
GuVrTeleopVulkanControl() [3/4]
guWhiteboard::GuVrTeleopVulkanControl::GuVrTeleopVulkanControl (const struct wb_gu_vr_teleop_vulkan_control & t_other) inline
Copy Constructor.
Definition at line 114 of file GuVrTeleopVulkanControl.hpp.
References wb_gu_vr_teleop_vulkan_control::movementOptions, and wb_gu_vr_teleop_vulkan_control::walkingOptions.
GuVrTeleopVulkanControl() [4/4]
guWhiteboard::GuVrTeleopVulkanControl::GuVrTeleopVulkanControl (const std::string & t_str) inline
String Constructor.
Definition at line 189 of file GuVrTeleopVulkanControl.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::GuVrTeleopVulkanControl::description () inline
USE_WB_GU_VR_TELEOP_VULKAN_CONTROL_C_CONVERSION
Definition at line 194 of file GuVrTeleopVulkanControl.hpp.
References GU_VR_TELEOP_VULKAN_CONTROL_DESC_BUFFER_SIZE, movementOptions(), NUM_VR_CONTROL_WALKING_OPTIONS, VRMovementBack, VRMovementForward, VRMovementLeft, VRMovementRight, VRMovementRotateLeft, VRMovementRotateRight, VRResting, VRStanding, VRWalking, walkingOptions(), and wb_gu_vr_teleop_vulkan_control_description().
from_string()
void guWhiteboard::GuVrTeleopVulkanControl::from_string (const std::string & t_str) inline
USE_WB_GU_VR_TELEOP_VULKAN_CONTROL_C_CONVERSION
Definition at line 332 of file GuVrTeleopVulkanControl.hpp.
References GU_VR_TELEOP_VULKAN_CONTROL_DESC_BUFFER_SIZE, NUM_VR_CONTROL_WALKING_OPTIONS, set_movementOptions(), set_walkingOptions(), VRMovementBack, VRMovementForward, VRMovementLeft, VRMovementRight, VRMovementRotateLeft, VRMovementRotateRight, VRResting, VRStanding, and VRWalking.
Referenced by GuVrTeleopVulkanControl().
movementOptions() [1/2]
enum VRControlMovementOptions & guWhiteboard::GuVrTeleopVulkanControl::movementOptions () inline
Definition at line 155 of file GuVrTeleopVulkanControl.hpp.
References wb_gu_vr_teleop_vulkan_control::movementOptions.
Referenced by GuVrTeleopVulkanControl(), description(), operator=(), operator==(), and to_string().
movementOptions() [2/2]
enum VRControlMovementOptions & guWhiteboard::GuVrTeleopVulkanControl::movementOptions () const inline
Definition at line 160 of file GuVrTeleopVulkanControl.hpp.
References wb_gu_vr_teleop_vulkan_control::movementOptions.
operator!=() [1/2]
bool guWhiteboard::GuVrTeleopVulkanControl::operator!= (const GuVrTeleopVulkanControl & t_other) const inline
Definition at line 140 of file GuVrTeleopVulkanControl.hpp.
operator!=() [2/2]
bool guWhiteboard::GuVrTeleopVulkanControl::operator!= (const wb_gu_vr_teleop_vulkan_control & t_other) const inline
Definition at line 150 of file GuVrTeleopVulkanControl.hpp.
operator=() [1/2]
GuVrTeleopVulkanControl & guWhiteboard::GuVrTeleopVulkanControl::operator= (const GuVrTeleopVulkanControl & t_other) inline
Copy Assignment Operator.
Definition at line 121 of file GuVrTeleopVulkanControl.hpp.
References movementOptions(), and walkingOptions().
operator=() [2/2]
GuVrTeleopVulkanControl & guWhiteboard::GuVrTeleopVulkanControl::operator= (const struct wb_gu_vr_teleop_vulkan_control & t_other) inline
Copy Assignment Operator.
Definition at line 129 of file GuVrTeleopVulkanControl.hpp.
References wb_gu_vr_teleop_vulkan_control::movementOptions, and wb_gu_vr_teleop_vulkan_control::walkingOptions.
operator==() [1/2]
bool guWhiteboard::GuVrTeleopVulkanControl::operator== (const GuVrTeleopVulkanControl & t_other) const inline
Definition at line 134 of file GuVrTeleopVulkanControl.hpp.
References movementOptions(), and walkingOptions().
operator==() [2/2]
bool guWhiteboard::GuVrTeleopVulkanControl::operator== (const wb_gu_vr_teleop_vulkan_control & t_other) const inline
Definition at line 145 of file GuVrTeleopVulkanControl.hpp.
References GuVrTeleopVulkanControl().
set_movementOptions()
void guWhiteboard::GuVrTeleopVulkanControl::set_movementOptions (const enum VRControlMovementOptions & t_newValue) inline
Definition at line 165 of file GuVrTeleopVulkanControl.hpp.
References wb_gu_vr_teleop_vulkan_control::movementOptions.
Referenced by from_string().
set_walkingOptions()
void guWhiteboard::GuVrTeleopVulkanControl::set_walkingOptions (const enum VRControlWalkingOptions & t_newValue) inline
Definition at line 180 of file GuVrTeleopVulkanControl.hpp.
References wb_gu_vr_teleop_vulkan_control::walkingOptions.
Referenced by from_string().
to_string()
std::string guWhiteboard::GuVrTeleopVulkanControl::to_string () inline
USE_WB_GU_VR_TELEOP_VULKAN_CONTROL_C_CONVERSION
Definition at line 261 of file GuVrTeleopVulkanControl.hpp.
References GU_VR_TELEOP_VULKAN_CONTROL_TO_STRING_BUFFER_SIZE, movementOptions(), NUM_VR_CONTROL_WALKING_OPTIONS, VRMovementBack, VRMovementForward, VRMovementLeft, VRMovementRight, VRMovementRotateLeft, VRMovementRotateRight, VRResting, VRStanding, VRWalking, walkingOptions(), and wb_gu_vr_teleop_vulkan_control_to_string().
walkingOptions() [1/2]
enum VRControlWalkingOptions & guWhiteboard::GuVrTeleopVulkanControl::walkingOptions () inline
Definition at line 170 of file GuVrTeleopVulkanControl.hpp.
References wb_gu_vr_teleop_vulkan_control::walkingOptions.
Referenced by GuVrTeleopVulkanControl(), description(), operator=(), operator==(), and to_string().
walkingOptions() [2/2]
enum VRControlWalkingOptions & guWhiteboard::GuVrTeleopVulkanControl::walkingOptions () const inline
Definition at line 175 of file GuVrTeleopVulkanControl.hpp.
References wb_gu_vr_teleop_vulkan_control::walkingOptions.
The documentation for this class was generated from the following file:
typeClassDefs/GuVrTeleopVulkanControl.hpp