gusimplewhiteboard: guWhiteboard::VisionDetectionFeatures Class Reference
guWhiteboard::VisionDetectionFeatures Class Reference
Provides a C++ wrapper around wb_vision_detection_features.
#include <VisionDetectionFeatures.hpp>
Public Member Functions
VisionDetectionFeatures (uint64_t t_frameNumber=0, const struct wb_vision_detection_feature_array t_features[2]=NULLPTR)
Create a new VisionDetectionFeatures.
VisionDetectionFeatures (const VisionDetectionFeatures &t_other)
Copy Constructor.
VisionDetectionFeatures (const struct wb_vision_detection_features &t_other)
Copy Constructor.
VisionDetectionFeatures & operator= (const VisionDetectionFeatures &t_other)
Copy Assignment Operator.
VisionDetectionFeatures & operator= (const struct wb_vision_detection_features &t_other)
Copy Assignment Operator.
bool operator== (const VisionDetectionFeatures &t_other) const
bool operator!= (const VisionDetectionFeatures &t_other) const
bool operator== (const wb_vision_detection_features &t_other) const
bool operator!= (const wb_vision_detection_features &t_other) const
uint64_t & frameNumber ()
const uint64_t & frameNumber () const
void set_frameNumber (const uint64_t &t_newValue)
const VisionDetectionFeatureArray * features () const
size_t features_size () const
VisionDetectionFeatureArray & features (int t_i)
const VisionDetectionFeatureArray & features (int t_i) const
void set_features (const VisionDetectionFeatureArray *t_newValue)
void set_features (const VisionDetectionFeatureArray &t_newValue, int t_i)
VisionDetectionFeatures (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_vision_detection_features
uint64_t frameNumber
The frame number that these lines were seen in.
struct wb_vision_detection_feature_array features [2]
Features reported for each camera.
Detailed Description
Provides a C++ wrapper around wb_vision_detection_features.
Definition at line 85 of file VisionDetectionFeatures.hpp.
Constructor & Destructor Documentation
VisionDetectionFeatures() [1/4]
guWhiteboard::VisionDetectionFeatures::VisionDetectionFeatures (uint64_t t_frameNumber = 0, const struct wb_vision_detection_feature_array t_features[2] = NULLPTR) inline
Create a new VisionDetectionFeatures.
Definition at line 107 of file VisionDetectionFeatures.hpp.
Referenced by operator==().
VisionDetectionFeatures() [2/4]
guWhiteboard::VisionDetectionFeatures::VisionDetectionFeatures (const VisionDetectionFeatures & t_other) inline
Copy Constructor.
Definition at line 114 of file VisionDetectionFeatures.hpp.
References features(), and frameNumber().
VisionDetectionFeatures() [3/4]
guWhiteboard::VisionDetectionFeatures::VisionDetectionFeatures (const struct wb_vision_detection_features & t_other) inline
Copy Constructor.
Definition at line 121 of file VisionDetectionFeatures.hpp.
References wb_vision_detection_features::features, and wb_vision_detection_features::frameNumber.
VisionDetectionFeatures() [4/4]
guWhiteboard::VisionDetectionFeatures::VisionDetectionFeatures (const std::string & t_str) inline
String Constructor.
Definition at line 218 of file VisionDetectionFeatures.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::VisionDetectionFeatures::description () inline
USE_WB_VISION_DETECTION_FEATURES_C_CONVERSION
Definition at line 223 of file VisionDetectionFeatures.hpp.
References description(), features(), frameNumber(), VISION_DETECTION_FEATURES_DESC_BUFFER_SIZE, VISION_DETECTION_FEATURES_FEATURES_ARRAY_SIZE, and wb_vision_detection_features_description().
Referenced by description().
features() [1/3]
const VisionDetectionFeatureArray * guWhiteboard::VisionDetectionFeatures::features () const inline
Definition at line 184 of file VisionDetectionFeatures.hpp.
References wb_vision_detection_features::features.
Referenced by VisionDetectionFeatures(), description(), operator=(), operator==(), and to_string().
features() [2/3]
VisionDetectionFeatureArray & guWhiteboard::VisionDetectionFeatures::features (int t_i) inline
Definition at line 194 of file VisionDetectionFeatures.hpp.
References wb_vision_detection_features::features.
features() [3/3]
const VisionDetectionFeatureArray & guWhiteboard::VisionDetectionFeatures::features (int t_i) const inline
Definition at line 199 of file VisionDetectionFeatures.hpp.
References wb_vision_detection_features::features.
features_size()
size_t guWhiteboard::VisionDetectionFeatures::features_size () const inline
Definition at line 189 of file VisionDetectionFeatures.hpp.
References VISION_DETECTION_FEATURES_FEATURES_ARRAY_SIZE.
frameNumber() [1/2]
uint64_t & guWhiteboard::VisionDetectionFeatures::frameNumber () inline
Definition at line 169 of file VisionDetectionFeatures.hpp.
References wb_vision_detection_features::frameNumber.
Referenced by VisionDetectionFeatures(), description(), operator=(), operator==(), and to_string().
frameNumber() [2/2]
const uint64_t & guWhiteboard::VisionDetectionFeatures::frameNumber () const inline
Definition at line 174 of file VisionDetectionFeatures.hpp.
References wb_vision_detection_features::frameNumber.
from_string()
void guWhiteboard::VisionDetectionFeatures::from_string (const std::string & t_str) inline
USE_WB_VISION_DETECTION_FEATURES_C_CONVERSION
Definition at line 269 of file VisionDetectionFeatures.hpp.
References guWhiteboard::VisionDetectionFeatureArray::from_string(), set_features(), set_frameNumber(), VISION_DETECTION_FEATURES_DESC_BUFFER_SIZE, and VISION_DETECTION_FEATURES_FEATURES_ARRAY_SIZE.
Referenced by VisionDetectionFeatures().
operator!=() [1/2]
bool guWhiteboard::VisionDetectionFeatures::operator!= (const VisionDetectionFeatures & t_other) const inline
Definition at line 154 of file VisionDetectionFeatures.hpp.
operator!=() [2/2]
bool guWhiteboard::VisionDetectionFeatures::operator!= (const wb_vision_detection_features & t_other) const inline
Definition at line 164 of file VisionDetectionFeatures.hpp.
operator=() [1/2]
VisionDetectionFeatures & guWhiteboard::VisionDetectionFeatures::operator= (const struct wb_vision_detection_features & t_other) inline
Copy Assignment Operator.
Definition at line 136 of file VisionDetectionFeatures.hpp.
References wb_vision_detection_features::features, and wb_vision_detection_features::frameNumber.
operator=() [2/2]
VisionDetectionFeatures & guWhiteboard::VisionDetectionFeatures::operator= (const VisionDetectionFeatures & t_other) inline
Copy Assignment Operator.
Definition at line 128 of file VisionDetectionFeatures.hpp.
References features(), and frameNumber().
operator==() [1/2]
bool guWhiteboard::VisionDetectionFeatures::operator== (const VisionDetectionFeatures & t_other) const inline
Definition at line 141 of file VisionDetectionFeatures.hpp.
References features(), and frameNumber().
operator==() [2/2]
bool guWhiteboard::VisionDetectionFeatures::operator== (const wb_vision_detection_features & t_other) const inline
Definition at line 159 of file VisionDetectionFeatures.hpp.
References VisionDetectionFeatures().
set_features() [1/2]
void guWhiteboard::VisionDetectionFeatures::set_features (const VisionDetectionFeatureArray & t_newValue, int t_i) inline
Definition at line 209 of file VisionDetectionFeatures.hpp.
References wb_vision_detection_features::features.
set_features() [2/2]
void guWhiteboard::VisionDetectionFeatures::set_features (const VisionDetectionFeatureArray * t_newValue) inline
Definition at line 204 of file VisionDetectionFeatures.hpp.
References wb_vision_detection_features::features, and VISION_DETECTION_FEATURES_FEATURES_ARRAY_SIZE.
Referenced by from_string().
set_frameNumber()
void guWhiteboard::VisionDetectionFeatures::set_frameNumber (const uint64_t & t_newValue) inline
Definition at line 179 of file VisionDetectionFeatures.hpp.
References wb_vision_detection_features::frameNumber.
Referenced by from_string().
to_string()
std::string guWhiteboard::VisionDetectionFeatures::to_string () inline
USE_WB_VISION_DETECTION_FEATURES_C_CONVERSION
Definition at line 244 of file VisionDetectionFeatures.hpp.
References features(), frameNumber(), to_string(), VISION_DETECTION_FEATURES_FEATURES_ARRAY_SIZE, VISION_DETECTION_FEATURES_TO_STRING_BUFFER_SIZE, and wb_vision_detection_features_to_string().
Referenced by to_string().
The documentation for this class was generated from the following file:
typeClassDefs/VisionDetectionFeatures.hpp