gusimplewhiteboard: guWhiteboard::SENSORSLegJointSensors Class Reference
guWhiteboard::SENSORSLegJointSensors Class Reference
Provides a C++ wrapper around wb_sensors_legjointsensors.
#include <SENSORSLegJointSensors.hpp>
Public Member Functions
SENSORSLegJointSensors (float t_LKneePitch=0.0f, float t_LAnklePitch=0.0f, float t_LAnkleRoll=0.0f, float t_RKneePitch=0.0f, float t_RAnklePitch=0.0f, float t_RAnkleRoll=0.0f, float t_LHipYawPitch=0.0f, float t_LHipRoll=0.0f, float t_LHipPitch=0.0f, float t_RHipYawPitch=0.0f, float t_RHipRoll=0.0f, float t_RHipPitch=0.0f)
Create a new SENSORSLegJointSensors.
SENSORSLegJointSensors (const SENSORSLegJointSensors &t_other)
Copy Constructor.
SENSORSLegJointSensors (const struct wb_sensors_legjointsensors &t_other)
Copy Constructor.
SENSORSLegJointSensors & operator= (const SENSORSLegJointSensors &t_other)
Copy Assignment Operator.
SENSORSLegJointSensors & operator= (const struct wb_sensors_legjointsensors &t_other)
Copy Assignment Operator.
bool operator== (const SENSORSLegJointSensors &t_other) const
bool operator!= (const SENSORSLegJointSensors &t_other) const
bool operator== (const wb_sensors_legjointsensors &t_other) const
bool operator!= (const wb_sensors_legjointsensors &t_other) const
float & LKneePitch ()
const float & LKneePitch () const
void set_LKneePitch (const float &t_newValue)
float & LAnklePitch ()
const float & LAnklePitch () const
void set_LAnklePitch (const float &t_newValue)
float & LAnkleRoll ()
const float & LAnkleRoll () const
void set_LAnkleRoll (const float &t_newValue)
float & RKneePitch ()
const float & RKneePitch () const
void set_RKneePitch (const float &t_newValue)
float & RAnklePitch ()
const float & RAnklePitch () const
void set_RAnklePitch (const float &t_newValue)
float & RAnkleRoll ()
const float & RAnkleRoll () const
void set_RAnkleRoll (const float &t_newValue)
float & LHipYawPitch ()
const float & LHipYawPitch () const
void set_LHipYawPitch (const float &t_newValue)
float & LHipRoll ()
const float & LHipRoll () const
void set_LHipRoll (const float &t_newValue)
float & LHipPitch ()
const float & LHipPitch () const
void set_LHipPitch (const float &t_newValue)
float & RHipYawPitch ()
const float & RHipYawPitch () const
void set_RHipYawPitch (const float &t_newValue)
float & RHipRoll ()
const float & RHipRoll () const
void set_RHipRoll (const float &t_newValue)
float & RHipPitch ()
const float & RHipPitch () const
void set_RHipPitch (const float &t_newValue)
SENSORSLegJointSensors (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_sensors_legjointsensors
float LKneePitch
pitch of the knee joint (left)
float LAnklePitch
pitch of the ankle joint (left)
float LAnkleRoll
roll of the ankle joint (left)
float RKneePitch
pitch of the knee joint (right)
float RAnklePitch
pitch of the ankle joint (right)
float RAnkleRoll
roll of the ankle joint (right)
float LHipYawPitch
'yaw/pitch' of the hip.
float LHipRoll
roll of the hip (left)
float LHipPitch
pitch of the hip (left)
float RHipYawPitch
'yaw/pitch' of the hip.
float RHipRoll
roll of the hip (right)
float RHipPitch
pitch of the hip (right)
Detailed Description
Provides a C++ wrapper around wb_sensors_legjointsensors.
Definition at line 84 of file SENSORSLegJointSensors.hpp.
Constructor & Destructor Documentation
SENSORSLegJointSensors() [1/4]
guWhiteboard::SENSORSLegJointSensors::SENSORSLegJointSensors (float t_LKneePitch = 0.0f, float t_LAnklePitch = 0.0f, float t_LAnkleRoll = 0.0f, float t_RKneePitch = 0.0f, float t_RAnklePitch = 0.0f, float t_RAnkleRoll = 0.0f, float t_LHipYawPitch = 0.0f, float t_LHipRoll = 0.0f, float t_LHipPitch = 0.0f, float t_RHipYawPitch = 0.0f, float t_RHipRoll = 0.0f, float t_RHipPitch = 0.0f) inline
Create a new SENSORSLegJointSensors.
Definition at line 111 of file SENSORSLegJointSensors.hpp.
Referenced by operator==().
SENSORSLegJointSensors() [2/4]
guWhiteboard::SENSORSLegJointSensors::SENSORSLegJointSensors (const SENSORSLegJointSensors & t_other) inline
Copy Constructor.
Definition at line 118 of file SENSORSLegJointSensors.hpp.
References LAnklePitch(), LAnkleRoll(), LHipPitch(), LHipRoll(), LHipYawPitch(), LKneePitch(), RAnklePitch(), RAnkleRoll(), RHipPitch(), RHipRoll(), RHipYawPitch(), and RKneePitch().
SENSORSLegJointSensors() [3/4]
guWhiteboard::SENSORSLegJointSensors::SENSORSLegJointSensors (const struct wb_sensors_legjointsensors & t_other) inline
Copy Constructor.
Definition at line 125 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::LAnklePitch, wb_sensors_legjointsensors::LAnkleRoll, wb_sensors_legjointsensors::LHipPitch, wb_sensors_legjointsensors::LHipRoll, wb_sensors_legjointsensors::LHipYawPitch, wb_sensors_legjointsensors::LKneePitch, wb_sensors_legjointsensors::RAnklePitch, wb_sensors_legjointsensors::RAnkleRoll, wb_sensors_legjointsensors::RHipPitch, wb_sensors_legjointsensors::RHipRoll, wb_sensors_legjointsensors::RHipYawPitch, and wb_sensors_legjointsensors::RKneePitch.
SENSORSLegJointSensors() [4/4]
guWhiteboard::SENSORSLegJointSensors::SENSORSLegJointSensors (const std::string & t_str) inline
String Constructor.
Definition at line 360 of file SENSORSLegJointSensors.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::SENSORSLegJointSensors::description () inline
USE_WB_SENSORS_LEGJOINTSENSORS_C_CONVERSION
Definition at line 365 of file SENSORSLegJointSensors.hpp.
References LAnklePitch(), LAnkleRoll(), LHipPitch(), LHipRoll(), LHipYawPitch(), LKneePitch(), RAnklePitch(), RAnkleRoll(), RHipPitch(), RHipRoll(), RHipYawPitch(), RKneePitch(), SENSORS_LEGJOINTSENSORS_DESC_BUFFER_SIZE, and wb_sensors_legjointsensors_description().
from_string()
void guWhiteboard::SENSORSLegJointSensors::from_string (const std::string & t_str) inline
USE_WB_SENSORS_LEGJOINTSENSORS_C_CONVERSION
Definition at line 439 of file SENSORSLegJointSensors.hpp.
References SENSORS_LEGJOINTSENSORS_DESC_BUFFER_SIZE, set_LAnklePitch(), set_LAnkleRoll(), set_LHipPitch(), set_LHipRoll(), set_LHipYawPitch(), set_LKneePitch(), set_RAnklePitch(), set_RAnkleRoll(), set_RHipPitch(), set_RHipRoll(), set_RHipYawPitch(), and set_RKneePitch().
Referenced by SENSORSLegJointSensors().
LAnklePitch() [1/2]
float & guWhiteboard::SENSORSLegJointSensors::LAnklePitch () inline
Definition at line 191 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::LAnklePitch.
Referenced by SENSORSLegJointSensors(), description(), operator=(), operator==(), and to_string().
LAnklePitch() [2/2]
const float & guWhiteboard::SENSORSLegJointSensors::LAnklePitch () const inline
Definition at line 196 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::LAnklePitch.
LAnkleRoll() [1/2]
float & guWhiteboard::SENSORSLegJointSensors::LAnkleRoll () inline
Definition at line 206 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::LAnkleRoll.
Referenced by SENSORSLegJointSensors(), description(), operator=(), operator==(), and to_string().
LAnkleRoll() [2/2]
const float & guWhiteboard::SENSORSLegJointSensors::LAnkleRoll () const inline
Definition at line 211 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::LAnkleRoll.
LHipPitch() [1/2]
float & guWhiteboard::SENSORSLegJointSensors::LHipPitch () inline
Definition at line 296 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::LHipPitch.
Referenced by SENSORSLegJointSensors(), description(), operator=(), operator==(), and to_string().
LHipPitch() [2/2]
const float & guWhiteboard::SENSORSLegJointSensors::LHipPitch () const inline
Definition at line 301 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::LHipPitch.
LHipRoll() [1/2]
float & guWhiteboard::SENSORSLegJointSensors::LHipRoll () inline
Definition at line 281 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::LHipRoll.
Referenced by SENSORSLegJointSensors(), description(), operator=(), operator==(), and to_string().
LHipRoll() [2/2]
const float & guWhiteboard::SENSORSLegJointSensors::LHipRoll () const inline
Definition at line 286 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::LHipRoll.
LHipYawPitch() [1/2]
float & guWhiteboard::SENSORSLegJointSensors::LHipYawPitch () inline
Definition at line 266 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::LHipYawPitch.
Referenced by SENSORSLegJointSensors(), description(), operator=(), operator==(), and to_string().
LHipYawPitch() [2/2]
const float & guWhiteboard::SENSORSLegJointSensors::LHipYawPitch () const inline
Definition at line 271 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::LHipYawPitch.
LKneePitch() [1/2]
float & guWhiteboard::SENSORSLegJointSensors::LKneePitch () inline
Definition at line 176 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::LKneePitch.
Referenced by SENSORSLegJointSensors(), description(), operator=(), operator==(), and to_string().
LKneePitch() [2/2]
const float & guWhiteboard::SENSORSLegJointSensors::LKneePitch () const inline
Definition at line 181 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::LKneePitch.
operator!=() [1/2]
bool guWhiteboard::SENSORSLegJointSensors::operator!= (const SENSORSLegJointSensors & t_other) const inline
Definition at line 161 of file SENSORSLegJointSensors.hpp.
operator!=() [2/2]
bool guWhiteboard::SENSORSLegJointSensors::operator!= (const wb_sensors_legjointsensors & t_other) const inline
Definition at line 171 of file SENSORSLegJointSensors.hpp.
operator=() [1/2]
SENSORSLegJointSensors & guWhiteboard::SENSORSLegJointSensors::operator= (const SENSORSLegJointSensors & t_other) inline
Copy Assignment Operator.
Definition at line 132 of file SENSORSLegJointSensors.hpp.
References LAnklePitch(), LAnkleRoll(), LHipPitch(), LHipRoll(), LHipYawPitch(), LKneePitch(), RAnklePitch(), RAnkleRoll(), RHipPitch(), RHipRoll(), RHipYawPitch(), and RKneePitch().
operator=() [2/2]
SENSORSLegJointSensors & guWhiteboard::SENSORSLegJointSensors::operator= (const struct wb_sensors_legjointsensors & t_other) inline
Copy Assignment Operator.
Definition at line 140 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::LAnklePitch, wb_sensors_legjointsensors::LAnkleRoll, wb_sensors_legjointsensors::LHipPitch, wb_sensors_legjointsensors::LHipRoll, wb_sensors_legjointsensors::LHipYawPitch, wb_sensors_legjointsensors::LKneePitch, wb_sensors_legjointsensors::RAnklePitch, wb_sensors_legjointsensors::RAnkleRoll, wb_sensors_legjointsensors::RHipPitch, wb_sensors_legjointsensors::RHipRoll, wb_sensors_legjointsensors::RHipYawPitch, and wb_sensors_legjointsensors::RKneePitch.
operator==() [1/2]
bool guWhiteboard::SENSORSLegJointSensors::operator== (const SENSORSLegJointSensors & t_other) const inline
Definition at line 145 of file SENSORSLegJointSensors.hpp.
References LAnklePitch(), LAnkleRoll(), LHipPitch(), LHipRoll(), LHipYawPitch(), LKneePitch(), RAnklePitch(), RAnkleRoll(), RHipPitch(), RHipRoll(), RHipYawPitch(), and RKneePitch().
operator==() [2/2]
bool guWhiteboard::SENSORSLegJointSensors::operator== (const wb_sensors_legjointsensors & t_other) const inline
Definition at line 166 of file SENSORSLegJointSensors.hpp.
References SENSORSLegJointSensors().
RAnklePitch() [1/2]
float & guWhiteboard::SENSORSLegJointSensors::RAnklePitch () inline
Definition at line 236 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::RAnklePitch.
Referenced by SENSORSLegJointSensors(), description(), operator=(), operator==(), and to_string().
RAnklePitch() [2/2]
const float & guWhiteboard::SENSORSLegJointSensors::RAnklePitch () const inline
Definition at line 241 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::RAnklePitch.
RAnkleRoll() [1/2]
float & guWhiteboard::SENSORSLegJointSensors::RAnkleRoll () inline
Definition at line 251 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::RAnkleRoll.
Referenced by SENSORSLegJointSensors(), description(), operator=(), operator==(), and to_string().
RAnkleRoll() [2/2]
const float & guWhiteboard::SENSORSLegJointSensors::RAnkleRoll () const inline
Definition at line 256 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::RAnkleRoll.
RHipPitch() [1/2]
float & guWhiteboard::SENSORSLegJointSensors::RHipPitch () inline
Definition at line 341 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::RHipPitch.
Referenced by SENSORSLegJointSensors(), description(), operator=(), operator==(), and to_string().
RHipPitch() [2/2]
const float & guWhiteboard::SENSORSLegJointSensors::RHipPitch () const inline
Definition at line 346 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::RHipPitch.
RHipRoll() [1/2]
float & guWhiteboard::SENSORSLegJointSensors::RHipRoll () inline
Definition at line 326 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::RHipRoll.
Referenced by SENSORSLegJointSensors(), description(), operator=(), operator==(), and to_string().
RHipRoll() [2/2]
const float & guWhiteboard::SENSORSLegJointSensors::RHipRoll () const inline
Definition at line 331 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::RHipRoll.
RHipYawPitch() [1/2]
float & guWhiteboard::SENSORSLegJointSensors::RHipYawPitch () inline
Definition at line 311 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::RHipYawPitch.
Referenced by SENSORSLegJointSensors(), description(), operator=(), operator==(), and to_string().
RHipYawPitch() [2/2]
const float & guWhiteboard::SENSORSLegJointSensors::RHipYawPitch () const inline
Definition at line 316 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::RHipYawPitch.
RKneePitch() [1/2]
float & guWhiteboard::SENSORSLegJointSensors::RKneePitch () inline
Definition at line 221 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::RKneePitch.
Referenced by SENSORSLegJointSensors(), description(), operator=(), operator==(), and to_string().
RKneePitch() [2/2]
const float & guWhiteboard::SENSORSLegJointSensors::RKneePitch () const inline
Definition at line 226 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::RKneePitch.
set_LAnklePitch()
void guWhiteboard::SENSORSLegJointSensors::set_LAnklePitch (const float & t_newValue) inline
Definition at line 201 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::LAnklePitch.
Referenced by from_string().
set_LAnkleRoll()
void guWhiteboard::SENSORSLegJointSensors::set_LAnkleRoll (const float & t_newValue) inline
Definition at line 216 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::LAnkleRoll.
Referenced by from_string().
set_LHipPitch()
void guWhiteboard::SENSORSLegJointSensors::set_LHipPitch (const float & t_newValue) inline
Definition at line 306 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::LHipPitch.
Referenced by from_string().
set_LHipRoll()
void guWhiteboard::SENSORSLegJointSensors::set_LHipRoll (const float & t_newValue) inline
Definition at line 291 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::LHipRoll.
Referenced by from_string().
set_LHipYawPitch()
void guWhiteboard::SENSORSLegJointSensors::set_LHipYawPitch (const float & t_newValue) inline
Definition at line 276 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::LHipYawPitch.
Referenced by from_string().
set_LKneePitch()
void guWhiteboard::SENSORSLegJointSensors::set_LKneePitch (const float & t_newValue) inline
Definition at line 186 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::LKneePitch.
Referenced by from_string().
set_RAnklePitch()
void guWhiteboard::SENSORSLegJointSensors::set_RAnklePitch (const float & t_newValue) inline
Definition at line 246 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::RAnklePitch.
Referenced by from_string().
set_RAnkleRoll()
void guWhiteboard::SENSORSLegJointSensors::set_RAnkleRoll (const float & t_newValue) inline
Definition at line 261 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::RAnkleRoll.
Referenced by from_string().
set_RHipPitch()
void guWhiteboard::SENSORSLegJointSensors::set_RHipPitch (const float & t_newValue) inline
Definition at line 351 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::RHipPitch.
Referenced by from_string().
set_RHipRoll()
void guWhiteboard::SENSORSLegJointSensors::set_RHipRoll (const float & t_newValue) inline
Definition at line 336 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::RHipRoll.
Referenced by from_string().
set_RHipYawPitch()
void guWhiteboard::SENSORSLegJointSensors::set_RHipYawPitch (const float & t_newValue) inline
Definition at line 321 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::RHipYawPitch.
Referenced by from_string().
set_RKneePitch()
void guWhiteboard::SENSORSLegJointSensors::set_RKneePitch (const float & t_newValue) inline
Definition at line 231 of file SENSORSLegJointSensors.hpp.
References wb_sensors_legjointsensors::RKneePitch.
Referenced by from_string().
to_string()
std::string guWhiteboard::SENSORSLegJointSensors::to_string () inline
USE_WB_SENSORS_LEGJOINTSENSORS_C_CONVERSION
Definition at line 400 of file SENSORSLegJointSensors.hpp.
References LAnklePitch(), LAnkleRoll(), LHipPitch(), LHipRoll(), LHipYawPitch(), LKneePitch(), RAnklePitch(), RAnkleRoll(), RHipPitch(), RHipRoll(), RHipYawPitch(), RKneePitch(), SENSORS_LEGJOINTSENSORS_TO_STRING_BUFFER_SIZE, and wb_sensors_legjointsensors_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/SENSORSLegJointSensors.hpp