gusimplewhiteboard: guWhiteboard::NaoSonarProtectedWalkCommand Class Reference
guWhiteboard::NaoSonarProtectedWalkCommand Class Reference
Provides a C++ wrapper around wb_nao_sonar_protected_walk_command.
#include <NaoSonarProtectedWalkCommand.hpp>
Public Member Functions
NaoSonarProtectedWalkCommand (bool t_walkEngineOn=false, int16_t t_forward=0, int16_t t_left=0, int8_t t_turn=0, int8_t t_priority=1, bool t_exactStepsRequested=false, uint8_t t_speed=100, bool t_isFast=false, bool t_kickWithLeftFoot=true, bool t_useShuffle=true, bool t_leftArmLimp=false, bool t_rightArmLimp=false, uint8_t t_power=0, uint8_t t_odometryResetCounter=0, uint8_t t_bend=0)
Create a new NaoSonarProtectedWalkCommand.
NaoSonarProtectedWalkCommand (const NaoSonarProtectedWalkCommand &t_other)
Copy Constructor.
NaoSonarProtectedWalkCommand (const struct wb_nao_sonar_protected_walk_command &t_other)
Copy Constructor.
NaoSonarProtectedWalkCommand & operator= (const NaoSonarProtectedWalkCommand &t_other)
Copy Assignment Operator.
NaoSonarProtectedWalkCommand & operator= (const struct wb_nao_sonar_protected_walk_command &t_other)
Copy Assignment Operator.
bool operator== (const NaoSonarProtectedWalkCommand &t_other) const
bool operator!= (const NaoSonarProtectedWalkCommand &t_other) const
bool operator== (const wb_nao_sonar_protected_walk_command &t_other) const
bool operator!= (const wb_nao_sonar_protected_walk_command &t_other) const
bool & walkEngineOn ()
const bool & walkEngineOn () const
void set_walkEngineOn (const bool &t_newValue)
int16_t & forward ()
const int16_t & forward () const
void set_forward (const int16_t &t_newValue)
int16_t & left ()
const int16_t & left () const
void set_left (const int16_t &t_newValue)
int8_t & turn ()
const int8_t & turn () const
void set_turn (const int8_t &t_newValue)
int8_t & priority ()
const int8_t & priority () const
void set_priority (const int8_t &t_newValue)
bool & exactStepsRequested ()
const bool & exactStepsRequested () const
void set_exactStepsRequested (const bool &t_newValue)
uint8_t & speed ()
const uint8_t & speed () const
void set_speed (const uint8_t &t_newValue)
bool & isFast ()
const bool & isFast () const
void set_isFast (const bool &t_newValue)
bool & kickWithLeftFoot ()
const bool & kickWithLeftFoot () const
void set_kickWithLeftFoot (const bool &t_newValue)
bool & useShuffle ()
const bool & useShuffle () const
void set_useShuffle (const bool &t_newValue)
bool & leftArmLimp ()
const bool & leftArmLimp () const
void set_leftArmLimp (const bool &t_newValue)
bool & rightArmLimp ()
const bool & rightArmLimp () const
void set_rightArmLimp (const bool &t_newValue)
uint8_t & power ()
const uint8_t & power () const
void set_power (const uint8_t &t_newValue)
uint8_t & odometryResetCounter ()
const uint8_t & odometryResetCounter () const
void set_odometryResetCounter (const uint8_t &t_newValue)
uint8_t & bend ()
const uint8_t & bend () const
void set_bend (const uint8_t &t_newValue)
NaoSonarProtectedWalkCommand (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Static Public Member Functions
static NaoSonarProtectedWalkCommand walkProtected (int8_t t_priority, int16_t t_forward, int16_t t_left, int8_t t_turn)
WHITEBOARD_POSTER_STRING_CONVERSION.
static NaoSonarProtectedWalkCommand walkProtectedPrecisely (int8_t t_priority, int16_t t_forward, int16_t t_left, int8_t t_turn)
Convenience function to make the nao walk, with precise step distances.
static NaoSonarProtectedWalkCommand stop ()
Convenience function to make the nao stop walking.
static NaoSonarProtectedWalkCommand standWithStiffness ()
Convenience function to make the nao stand in the 'walk' position (slightly crouched), ready to immediately start walking again.
static NaoSonarProtectedWalkCommand standWithMinimalStiffness ()
Convenience function to make the nao stand in the 'STANDING' position, upright with minimal stiffness.
static NaoSonarProtectedWalkCommand disconnectWalk ()
Convenience function to disconnect the walk engine from the DCM.
Additional Inherited Members
Public Attributes inherited from wb_nao_sonar_protected_walk_command
bool walkEngineOn
connects the dcm callbacks.
int16_t forward
[-300 - 300] step-size(mm) per second, limited to +/- 300mm/step
int16_t left
[-200 - 200] step-size(mm) per second, limited to +/- 200mm/step
int8_t turn
[-85 - 85] step-size(mm) per second, limited to +/- 85deg/step
int8_t priority
subsumption priority 1: unprotected walk, command unmodified.
bool exactStepsRequested
No ratcheting, no speed 'buildup', just full step sizes.
uint8_t speed
[0 - 100] modifier for forward etc.
bool isFast
for kicks.
bool kickWithLeftFoot
which foot to use for kicking
bool useShuffle
limits the step height so the robot 'shuffles' instead of taking larger steps.
bool leftArmLimp
lower stiffness in the arms when walking, allows the arm to move a little more.
bool rightArmLimp
lower stiffness in the arms when walking, allows the arm to move a little more.
uint8_t power
[0 - 100] stiffness, auto set to minimum needed values.
uint8_t odometryResetCounter
Odometry will reset any time this is changed or incremented.
uint8_t bend
[0 - 1] controls what the robot does when stopped, 0 == STAND and lower stiffness, 1 == stay in READY, crouched and ready to walk immediately.
Detailed Description
Provides a C++ wrapper around wb_nao_sonar_protected_walk_command.
Definition at line 85 of file NaoSonarProtectedWalkCommand.hpp.
Constructor & Destructor Documentation
NaoSonarProtectedWalkCommand() [1/4]
guWhiteboard::NaoSonarProtectedWalkCommand::NaoSonarProtectedWalkCommand (bool t_walkEngineOn = false, int16_t t_forward = 0, int16_t t_left = 0, int8_t t_turn = 0, int8_t t_priority = 1, bool t_exactStepsRequested = false, uint8_t t_speed = 100, bool t_isFast = false, bool t_kickWithLeftFoot = true, bool t_useShuffle = true, bool t_leftArmLimp = false, bool t_rightArmLimp = false, uint8_t t_power = 0, uint8_t t_odometryResetCounter = 0, uint8_t t_bend = 0) inline
Create a new NaoSonarProtectedWalkCommand.
Definition at line 115 of file NaoSonarProtectedWalkCommand.hpp.
Referenced by disconnectWalk(), operator==(), stop(), and walkProtected().
NaoSonarProtectedWalkCommand() [2/4]
guWhiteboard::NaoSonarProtectedWalkCommand::NaoSonarProtectedWalkCommand (const NaoSonarProtectedWalkCommand & t_other) inline
Copy Constructor.
Definition at line 122 of file NaoSonarProtectedWalkCommand.hpp.
References bend(), exactStepsRequested(), forward(), isFast(), kickWithLeftFoot(), left(), leftArmLimp(), odometryResetCounter(), power(), priority(), rightArmLimp(), speed(), turn(), useShuffle(), and walkEngineOn().
NaoSonarProtectedWalkCommand() [3/4]
guWhiteboard::NaoSonarProtectedWalkCommand::NaoSonarProtectedWalkCommand (const struct wb_nao_sonar_protected_walk_command & t_other) inline
Copy Constructor.
Definition at line 129 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::bend, wb_nao_sonar_protected_walk_command::exactStepsRequested, wb_nao_sonar_protected_walk_command::forward, wb_nao_sonar_protected_walk_command::isFast, wb_nao_sonar_protected_walk_command::kickWithLeftFoot, wb_nao_sonar_protected_walk_command::left, wb_nao_sonar_protected_walk_command::leftArmLimp, wb_nao_sonar_protected_walk_command::odometryResetCounter, wb_nao_sonar_protected_walk_command::power, wb_nao_sonar_protected_walk_command::priority, wb_nao_sonar_protected_walk_command::rightArmLimp, wb_nao_sonar_protected_walk_command::speed, wb_nao_sonar_protected_walk_command::turn, wb_nao_sonar_protected_walk_command::useShuffle, and wb_nao_sonar_protected_walk_command::walkEngineOn.
NaoSonarProtectedWalkCommand() [4/4]
guWhiteboard::NaoSonarProtectedWalkCommand::NaoSonarProtectedWalkCommand (const std::string & t_str) inline
String Constructor.
Definition at line 412 of file NaoSonarProtectedWalkCommand.hpp.
References from_string().
Member Function Documentation
bend() [1/2]
uint8_t & guWhiteboard::NaoSonarProtectedWalkCommand::bend () inline
Definition at line 393 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::bend.
Referenced by NaoSonarProtectedWalkCommand(), description(), operator=(), operator==(), and to_string().
bend() [2/2]
const uint8_t & guWhiteboard::NaoSonarProtectedWalkCommand::bend () const inline
Definition at line 398 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::bend.
description()
std::string guWhiteboard::NaoSonarProtectedWalkCommand::description () inline
USE_WB_NAO_SONAR_PROTECTED_WALK_COMMAND_C_CONVERSION
Definition at line 417 of file NaoSonarProtectedWalkCommand.hpp.
References bend(), exactStepsRequested(), forward(), isFast(), kickWithLeftFoot(), left(), leftArmLimp(), NAO_SONAR_PROTECTED_WALK_COMMAND_DESC_BUFFER_SIZE, odometryResetCounter(), power(), priority(), rightArmLimp(), speed(), turn(), useShuffle(), walkEngineOn(), and wb_nao_sonar_protected_walk_command_description().
disconnectWalk()
static NaoSonarProtectedWalkCommand guWhiteboard::NaoSonarProtectedWalkCommand::disconnectWalk () inline static
Convenience function to disconnect the walk engine from the DCM.
This must be done in order to give control of the joints to another module, like the Motion Player. You should return to the CROUCH position via 'standWithStiffness' or 'stop' before doing this, to ensure a smooth motion control transition.
Returns
A NaoSonarProtectedWalkCommand instance
Definition at line 771 of file NaoSonarProtectedWalkCommand.hpp.
References NaoSonarProtectedWalkCommand(), set_priority(), and set_walkEngineOn().
exactStepsRequested() [1/2]
bool & guWhiteboard::NaoSonarProtectedWalkCommand::exactStepsRequested () inline
Definition at line 258 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::exactStepsRequested.
Referenced by NaoSonarProtectedWalkCommand(), description(), operator=(), operator==(), and to_string().
exactStepsRequested() [2/2]
const bool & guWhiteboard::NaoSonarProtectedWalkCommand::exactStepsRequested () const inline
Definition at line 263 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::exactStepsRequested.
forward() [1/2]
int16_t & guWhiteboard::NaoSonarProtectedWalkCommand::forward () inline
Definition at line 198 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::forward.
Referenced by NaoSonarProtectedWalkCommand(), description(), operator=(), operator==(), and to_string().
forward() [2/2]
const int16_t & guWhiteboard::NaoSonarProtectedWalkCommand::forward () const inline
Definition at line 203 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::forward.
from_string()
void guWhiteboard::NaoSonarProtectedWalkCommand::from_string (const std::string & t_str) inline
USE_WB_NAO_SONAR_PROTECTED_WALK_COMMAND_C_CONVERSION
Definition at line 503 of file NaoSonarProtectedWalkCommand.hpp.
References NAO_SONAR_PROTECTED_WALK_COMMAND_DESC_BUFFER_SIZE, set_bend(), set_exactStepsRequested(), set_forward(), set_isFast(), set_kickWithLeftFoot(), set_left(), set_leftArmLimp(), set_odometryResetCounter(), set_power(), set_priority(), set_rightArmLimp(), set_speed(), set_turn(), set_useShuffle(), and set_walkEngineOn().
Referenced by NaoSonarProtectedWalkCommand().
isFast() [1/2]
bool & guWhiteboard::NaoSonarProtectedWalkCommand::isFast () inline
Definition at line 288 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::isFast.
Referenced by NaoSonarProtectedWalkCommand(), description(), operator=(), operator==(), and to_string().
isFast() [2/2]
const bool & guWhiteboard::NaoSonarProtectedWalkCommand::isFast () const inline
Definition at line 293 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::isFast.
kickWithLeftFoot() [1/2]
bool & guWhiteboard::NaoSonarProtectedWalkCommand::kickWithLeftFoot () inline
Definition at line 303 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::kickWithLeftFoot.
Referenced by NaoSonarProtectedWalkCommand(), description(), operator=(), operator==(), and to_string().
kickWithLeftFoot() [2/2]
const bool & guWhiteboard::NaoSonarProtectedWalkCommand::kickWithLeftFoot () const inline
Definition at line 308 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::kickWithLeftFoot.
left() [1/2]
int16_t & guWhiteboard::NaoSonarProtectedWalkCommand::left () inline
Definition at line 213 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::left.
Referenced by NaoSonarProtectedWalkCommand(), description(), operator=(), operator==(), and to_string().
left() [2/2]
const int16_t & guWhiteboard::NaoSonarProtectedWalkCommand::left () const inline
Definition at line 218 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::left.
leftArmLimp() [1/2]
bool & guWhiteboard::NaoSonarProtectedWalkCommand::leftArmLimp () inline
Definition at line 333 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::leftArmLimp.
Referenced by NaoSonarProtectedWalkCommand(), description(), operator=(), operator==(), and to_string().
leftArmLimp() [2/2]
const bool & guWhiteboard::NaoSonarProtectedWalkCommand::leftArmLimp () const inline
Definition at line 338 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::leftArmLimp.
odometryResetCounter() [1/2]
uint8_t & guWhiteboard::NaoSonarProtectedWalkCommand::odometryResetCounter () inline
Definition at line 378 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::odometryResetCounter.
Referenced by NaoSonarProtectedWalkCommand(), description(), operator=(), operator==(), and to_string().
odometryResetCounter() [2/2]
const uint8_t & guWhiteboard::NaoSonarProtectedWalkCommand::odometryResetCounter () const inline
Definition at line 383 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::odometryResetCounter.
operator!=() [1/2]
bool guWhiteboard::NaoSonarProtectedWalkCommand::operator!= (const NaoSonarProtectedWalkCommand & t_other) const inline
Definition at line 168 of file NaoSonarProtectedWalkCommand.hpp.
operator!=() [2/2]
bool guWhiteboard::NaoSonarProtectedWalkCommand::operator!= (const wb_nao_sonar_protected_walk_command & t_other) const inline
Definition at line 178 of file NaoSonarProtectedWalkCommand.hpp.
operator=() [1/2]
NaoSonarProtectedWalkCommand & guWhiteboard::NaoSonarProtectedWalkCommand::operator= (const NaoSonarProtectedWalkCommand & t_other) inline
Copy Assignment Operator.
Definition at line 136 of file NaoSonarProtectedWalkCommand.hpp.
References bend(), exactStepsRequested(), forward(), isFast(), kickWithLeftFoot(), left(), leftArmLimp(), odometryResetCounter(), power(), priority(), rightArmLimp(), speed(), turn(), useShuffle(), and walkEngineOn().
operator=() [2/2]
NaoSonarProtectedWalkCommand & guWhiteboard::NaoSonarProtectedWalkCommand::operator= (const struct wb_nao_sonar_protected_walk_command & t_other) inline
Copy Assignment Operator.
Definition at line 144 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::bend, wb_nao_sonar_protected_walk_command::exactStepsRequested, wb_nao_sonar_protected_walk_command::forward, wb_nao_sonar_protected_walk_command::isFast, wb_nao_sonar_protected_walk_command::kickWithLeftFoot, wb_nao_sonar_protected_walk_command::left, wb_nao_sonar_protected_walk_command::leftArmLimp, wb_nao_sonar_protected_walk_command::odometryResetCounter, wb_nao_sonar_protected_walk_command::power, wb_nao_sonar_protected_walk_command::priority, wb_nao_sonar_protected_walk_command::rightArmLimp, wb_nao_sonar_protected_walk_command::speed, wb_nao_sonar_protected_walk_command::turn, wb_nao_sonar_protected_walk_command::useShuffle, and wb_nao_sonar_protected_walk_command::walkEngineOn.
operator==() [1/2]
bool guWhiteboard::NaoSonarProtectedWalkCommand::operator== (const NaoSonarProtectedWalkCommand & t_other) const inline
Definition at line 149 of file NaoSonarProtectedWalkCommand.hpp.
References bend(), exactStepsRequested(), forward(), isFast(), kickWithLeftFoot(), left(), leftArmLimp(), odometryResetCounter(), power(), priority(), rightArmLimp(), speed(), turn(), useShuffle(), and walkEngineOn().
operator==() [2/2]
bool guWhiteboard::NaoSonarProtectedWalkCommand::operator== (const wb_nao_sonar_protected_walk_command & t_other) const inline
Definition at line 173 of file NaoSonarProtectedWalkCommand.hpp.
References NaoSonarProtectedWalkCommand().
power() [1/2]
uint8_t & guWhiteboard::NaoSonarProtectedWalkCommand::power () inline
Definition at line 363 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::power.
Referenced by NaoSonarProtectedWalkCommand(), description(), operator=(), operator==(), and to_string().
power() [2/2]
const uint8_t & guWhiteboard::NaoSonarProtectedWalkCommand::power () const inline
Definition at line 368 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::power.
priority() [1/2]
int8_t & guWhiteboard::NaoSonarProtectedWalkCommand::priority () inline
Definition at line 243 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::priority.
Referenced by NaoSonarProtectedWalkCommand(), description(), operator=(), operator==(), and to_string().
priority() [2/2]
const int8_t & guWhiteboard::NaoSonarProtectedWalkCommand::priority () const inline
Definition at line 248 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::priority.
rightArmLimp() [1/2]
bool & guWhiteboard::NaoSonarProtectedWalkCommand::rightArmLimp () inline
Definition at line 348 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::rightArmLimp.
Referenced by NaoSonarProtectedWalkCommand(), description(), operator=(), operator==(), and to_string().
rightArmLimp() [2/2]
const bool & guWhiteboard::NaoSonarProtectedWalkCommand::rightArmLimp () const inline
Definition at line 353 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::rightArmLimp.
set_bend()
void guWhiteboard::NaoSonarProtectedWalkCommand::set_bend (const uint8_t & t_newValue) inline
Definition at line 403 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::bend.
Referenced by from_string(), standWithMinimalStiffness(), standWithStiffness(), stop(), and walkProtected().
set_exactStepsRequested()
void guWhiteboard::NaoSonarProtectedWalkCommand::set_exactStepsRequested (const bool & t_newValue) inline
Definition at line 268 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::exactStepsRequested.
Referenced by from_string(), and walkProtectedPrecisely().
set_forward()
void guWhiteboard::NaoSonarProtectedWalkCommand::set_forward (const int16_t & t_newValue) inline
Definition at line 208 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::forward.
Referenced by from_string(), stop(), and walkProtected().
set_isFast()
void guWhiteboard::NaoSonarProtectedWalkCommand::set_isFast (const bool & t_newValue) inline
Definition at line 298 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::isFast.
Referenced by from_string().
set_kickWithLeftFoot()
void guWhiteboard::NaoSonarProtectedWalkCommand::set_kickWithLeftFoot (const bool & t_newValue) inline
Definition at line 313 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::kickWithLeftFoot.
Referenced by from_string().
set_left()
void guWhiteboard::NaoSonarProtectedWalkCommand::set_left (const int16_t & t_newValue) inline
Definition at line 223 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::left.
Referenced by from_string(), stop(), and walkProtected().
set_leftArmLimp()
void guWhiteboard::NaoSonarProtectedWalkCommand::set_leftArmLimp (const bool & t_newValue) inline
Definition at line 343 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::leftArmLimp.
Referenced by from_string().
set_odometryResetCounter()
void guWhiteboard::NaoSonarProtectedWalkCommand::set_odometryResetCounter (const uint8_t & t_newValue) inline
Definition at line 388 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::odometryResetCounter.
Referenced by from_string().
set_power()
void guWhiteboard::NaoSonarProtectedWalkCommand::set_power (const uint8_t & t_newValue) inline
Definition at line 373 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::power.
Referenced by from_string().
set_priority()
void guWhiteboard::NaoSonarProtectedWalkCommand::set_priority (const int8_t & t_newValue) inline
Definition at line 253 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::priority.
Referenced by disconnectWalk(), from_string(), standWithMinimalStiffness(), standWithStiffness(), stop(), and walkProtected().
set_rightArmLimp()
void guWhiteboard::NaoSonarProtectedWalkCommand::set_rightArmLimp (const bool & t_newValue) inline
Definition at line 358 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::rightArmLimp.
Referenced by from_string().
set_speed()
void guWhiteboard::NaoSonarProtectedWalkCommand::set_speed (const uint8_t & t_newValue) inline
Definition at line 283 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::speed.
Referenced by from_string().
set_turn()
void guWhiteboard::NaoSonarProtectedWalkCommand::set_turn (const int8_t & t_newValue) inline
Definition at line 238 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::turn.
Referenced by from_string(), stop(), and walkProtected().
set_useShuffle()
void guWhiteboard::NaoSonarProtectedWalkCommand::set_useShuffle (const bool & t_newValue) inline
Definition at line 328 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::useShuffle.
Referenced by from_string().
set_walkEngineOn()
void guWhiteboard::NaoSonarProtectedWalkCommand::set_walkEngineOn (const bool & t_newValue) inline
Definition at line 193 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::walkEngineOn.
Referenced by disconnectWalk(), from_string(), standWithMinimalStiffness(), standWithStiffness(), stop(), and walkProtected().
speed() [1/2]
uint8_t & guWhiteboard::NaoSonarProtectedWalkCommand::speed () inline
Definition at line 273 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::speed.
Referenced by NaoSonarProtectedWalkCommand(), description(), operator=(), operator==(), and to_string().
speed() [2/2]
const uint8_t & guWhiteboard::NaoSonarProtectedWalkCommand::speed () const inline
Definition at line 278 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::speed.
standWithMinimalStiffness()
static NaoSonarProtectedWalkCommand guWhiteboard::NaoSonarProtectedWalkCommand::standWithMinimalStiffness () inline static
Convenience function to make the nao stand in the 'STANDING' position, upright with minimal stiffness.
Good for longer pauses in movement, to save on battery and motor wear. You should always return to the CROUCH position before giving up control of the DCM with a 'disconnectWalk'. If you don't return to that position, other motion activities like the MotionPlayer may 'jerk' when activated. You do not need to return to the CROUCH position when you issue walk commands, it will be done automatically.
Returns
A NaoSonarProtectedWalkCommand instance
Definition at line 759 of file NaoSonarProtectedWalkCommand.hpp.
References set_bend(), set_priority(), set_walkEngineOn(), and stop().
standWithStiffness()
static NaoSonarProtectedWalkCommand guWhiteboard::NaoSonarProtectedWalkCommand::standWithStiffness () inline static
Convenience function to make the nao stand in the 'walk' position (slightly crouched), ready to immediately start walking again.
This is handy for returning from the STANDING position, reached via 'standWithMinimalStiffness'.
Returns
A NaoSonarProtectedWalkCommand instance
Definition at line 745 of file NaoSonarProtectedWalkCommand.hpp.
References set_bend(), set_priority(), set_walkEngineOn(), and stop().
stop()
static NaoSonarProtectedWalkCommand guWhiteboard::NaoSonarProtectedWalkCommand::stop () inline static
Convenience function to make the nao stop walking.
The robot will slow down and stop, remaining in the 'walking' position (slightly crouched).
Returns
A NaoSonarProtectedWalkCommand instance
Definition at line 730 of file NaoSonarProtectedWalkCommand.hpp.
References NaoSonarProtectedWalkCommand(), set_bend(), set_forward(), set_left(), set_priority(), set_turn(), and set_walkEngineOn().
Referenced by standWithMinimalStiffness(), and standWithStiffness().
to_string()
std::string guWhiteboard::NaoSonarProtectedWalkCommand::to_string () inline
USE_WB_NAO_SONAR_PROTECTED_WALK_COMMAND_C_CONVERSION
Definition at line 458 of file NaoSonarProtectedWalkCommand.hpp.
References bend(), exactStepsRequested(), forward(), isFast(), kickWithLeftFoot(), left(), leftArmLimp(), NAO_SONAR_PROTECTED_WALK_COMMAND_TO_STRING_BUFFER_SIZE, odometryResetCounter(), power(), priority(), rightArmLimp(), speed(), turn(), useShuffle(), walkEngineOn(), and wb_nao_sonar_protected_walk_command_to_string().
turn() [1/2]
int8_t & guWhiteboard::NaoSonarProtectedWalkCommand::turn () inline
Definition at line 228 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::turn.
Referenced by NaoSonarProtectedWalkCommand(), description(), operator=(), operator==(), and to_string().
turn() [2/2]
const int8_t & guWhiteboard::NaoSonarProtectedWalkCommand::turn () const inline
Definition at line 233 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::turn.
useShuffle() [1/2]
bool & guWhiteboard::NaoSonarProtectedWalkCommand::useShuffle () inline
Definition at line 318 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::useShuffle.
Referenced by NaoSonarProtectedWalkCommand(), description(), operator=(), operator==(), and to_string().
useShuffle() [2/2]
const bool & guWhiteboard::NaoSonarProtectedWalkCommand::useShuffle () const inline
Definition at line 323 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::useShuffle.
walkEngineOn() [1/2]
bool & guWhiteboard::NaoSonarProtectedWalkCommand::walkEngineOn () inline
Definition at line 183 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::walkEngineOn.
Referenced by NaoSonarProtectedWalkCommand(), description(), operator=(), operator==(), and to_string().
walkEngineOn() [2/2]
const bool & guWhiteboard::NaoSonarProtectedWalkCommand::walkEngineOn () const inline
Definition at line 188 of file NaoSonarProtectedWalkCommand.hpp.
References wb_nao_sonar_protected_walk_command::walkEngineOn.
walkProtected()
static NaoSonarProtectedWalkCommand guWhiteboard::NaoSonarProtectedWalkCommand::walkProtected (int8_t t_priority, int16_t t_forward, int16_t t_left, int8_t t_turn) inline static
WHITEBOARD_POSTER_STRING_CONVERSION.
Convenience function to make the nao walk.
Parameters
t_forward see struct documentation.
t_left see struct documentation.
t_turn see struct documentation.
Returns
A NaoSonarProtectedWalkCommand instance
Definition at line 702 of file NaoSonarProtectedWalkCommand.hpp.
References NaoSonarProtectedWalkCommand(), set_bend(), set_forward(), set_left(), set_priority(), set_turn(), and set_walkEngineOn().
Referenced by walkProtectedPrecisely().
walkProtectedPrecisely()
static NaoSonarProtectedWalkCommand guWhiteboard::NaoSonarProtectedWalkCommand::walkProtectedPrecisely (int8_t t_priority, int16_t t_forward, int16_t t_left, int8_t t_turn) inline static
Convenience function to make the nao walk, with precise step distances.
There is no speed buildup with this method, it uses a consistent step size and speed. This is good for small accurate movements, like lining up a kick.
Parameters
t_forward see struct documentation.
t_left see struct documentation.
t_turn see struct documentation.
Returns
A NaoSonarProtectedWalkCommand instance
Definition at line 720 of file NaoSonarProtectedWalkCommand.hpp.
References set_exactStepsRequested(), and walkProtected().
The documentation for this class was generated from the following file:
typeClassDefs/NaoSonarProtectedWalkCommand.hpp