gusimplewhiteboard: guWhiteboard::MissionPriorityForObstacles Class Reference
guWhiteboard::MissionPriorityForObstacles Class Reference
Provides a C++ wrapper around wb_mission_priority_for_obstacles.
#include <MissionPriorityForObstacles.hpp>
Public Member Functions
MissionPriorityForObstacles (bool t_ignore_obstacles=true)
Create a new MissionPriorityForObstacles.
MissionPriorityForObstacles (const MissionPriorityForObstacles &t_other)
Copy Constructor.
MissionPriorityForObstacles (const struct wb_mission_priority_for_obstacles &t_other)
Copy Constructor.
MissionPriorityForObstacles & operator= (const MissionPriorityForObstacles &t_other)
Copy Assignment Operator.
MissionPriorityForObstacles & operator= (const struct wb_mission_priority_for_obstacles &t_other)
Copy Assignment Operator.
bool operator== (const MissionPriorityForObstacles &t_other) const
bool operator!= (const MissionPriorityForObstacles &t_other) const
bool operator== (const wb_mission_priority_for_obstacles &t_other) const
bool operator!= (const wb_mission_priority_for_obstacles &t_other) const
bool & ignore_obstacles ()
const bool & ignore_obstacles () const
void set_ignore_obstacles (const bool &t_newValue)
MissionPriorityForObstacles (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_mission_priority_for_obstacles
bool ignore_obstacles
walk ahead with high priority on target so do not deviate because of obstacles detected by sonar.
Detailed Description
Provides a C++ wrapper around wb_mission_priority_for_obstacles.
Definition at line 85 of file MissionPriorityForObstacles.hpp.
Constructor & Destructor Documentation
MissionPriorityForObstacles() [1/4]
guWhiteboard::MissionPriorityForObstacles::MissionPriorityForObstacles (bool t_ignore_obstacles = true) inline
Create a new MissionPriorityForObstacles.
Definition at line 101 of file MissionPriorityForObstacles.hpp.
Referenced by operator==().
MissionPriorityForObstacles() [2/4]
guWhiteboard::MissionPriorityForObstacles::MissionPriorityForObstacles (const MissionPriorityForObstacles & t_other) inline
Copy Constructor.
Definition at line 108 of file MissionPriorityForObstacles.hpp.
References ignore_obstacles().
MissionPriorityForObstacles() [3/4]
guWhiteboard::MissionPriorityForObstacles::MissionPriorityForObstacles (const struct wb_mission_priority_for_obstacles & t_other) inline
Copy Constructor.
Definition at line 115 of file MissionPriorityForObstacles.hpp.
References wb_mission_priority_for_obstacles::ignore_obstacles.
MissionPriorityForObstacles() [4/4]
guWhiteboard::MissionPriorityForObstacles::MissionPriorityForObstacles (const std::string & t_str) inline
String Constructor.
Definition at line 174 of file MissionPriorityForObstacles.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::MissionPriorityForObstacles::description () inline
USE_WB_MISSION_PRIORITY_FOR_OBSTACLES_C_CONVERSION
Definition at line 179 of file MissionPriorityForObstacles.hpp.
References ignore_obstacles(), MISSION_PRIORITY_FOR_OBSTACLES_DESC_BUFFER_SIZE, and wb_mission_priority_for_obstacles_description().
from_string()
void guWhiteboard::MissionPriorityForObstacles::from_string (const std::string & t_str) inline
USE_WB_MISSION_PRIORITY_FOR_OBSTACLES_C_CONVERSION
Definition at line 209 of file MissionPriorityForObstacles.hpp.
References MISSION_PRIORITY_FOR_OBSTACLES_DESC_BUFFER_SIZE, and set_ignore_obstacles().
Referenced by MissionPriorityForObstacles().
ignore_obstacles() [1/2]
bool & guWhiteboard::MissionPriorityForObstacles::ignore_obstacles () inline
Definition at line 155 of file MissionPriorityForObstacles.hpp.
References wb_mission_priority_for_obstacles::ignore_obstacles.
Referenced by MissionPriorityForObstacles(), description(), operator=(), operator==(), and to_string().
ignore_obstacles() [2/2]
const bool & guWhiteboard::MissionPriorityForObstacles::ignore_obstacles () const inline
Definition at line 160 of file MissionPriorityForObstacles.hpp.
References wb_mission_priority_for_obstacles::ignore_obstacles.
operator!=() [1/2]
bool guWhiteboard::MissionPriorityForObstacles::operator!= (const MissionPriorityForObstacles & t_other) const inline
Definition at line 140 of file MissionPriorityForObstacles.hpp.
operator!=() [2/2]
bool guWhiteboard::MissionPriorityForObstacles::operator!= (const wb_mission_priority_for_obstacles & t_other) const inline
Definition at line 150 of file MissionPriorityForObstacles.hpp.
operator=() [1/2]
MissionPriorityForObstacles & guWhiteboard::MissionPriorityForObstacles::operator= (const MissionPriorityForObstacles & t_other) inline
Copy Assignment Operator.
Definition at line 122 of file MissionPriorityForObstacles.hpp.
References ignore_obstacles().
operator=() [2/2]
MissionPriorityForObstacles & guWhiteboard::MissionPriorityForObstacles::operator= (const struct wb_mission_priority_for_obstacles & t_other) inline
Copy Assignment Operator.
Definition at line 130 of file MissionPriorityForObstacles.hpp.
References wb_mission_priority_for_obstacles::ignore_obstacles.
operator==() [1/2]
bool guWhiteboard::MissionPriorityForObstacles::operator== (const MissionPriorityForObstacles & t_other) const inline
Definition at line 135 of file MissionPriorityForObstacles.hpp.
References ignore_obstacles().
operator==() [2/2]
bool guWhiteboard::MissionPriorityForObstacles::operator== (const wb_mission_priority_for_obstacles & t_other) const inline
Definition at line 145 of file MissionPriorityForObstacles.hpp.
References MissionPriorityForObstacles().
set_ignore_obstacles()
void guWhiteboard::MissionPriorityForObstacles::set_ignore_obstacles (const bool & t_newValue) inline
Definition at line 165 of file MissionPriorityForObstacles.hpp.
References wb_mission_priority_for_obstacles::ignore_obstacles.
Referenced by from_string().
to_string()
std::string guWhiteboard::MissionPriorityForObstacles::to_string () inline
USE_WB_MISSION_PRIORITY_FOR_OBSTACLES_C_CONVERSION
Definition at line 192 of file MissionPriorityForObstacles.hpp.
References ignore_obstacles(), MISSION_PRIORITY_FOR_OBSTACLES_TO_STRING_BUFFER_SIZE, and wb_mission_priority_for_obstacles_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/MissionPriorityForObstacles.hpp