gusimplewhiteboard: guWhiteboard::PixelToRobotRelativeCoord Class Reference
guWhiteboard::PixelToRobotRelativeCoord Class Reference
Provides a C++ wrapper around wb_pixel_to_robot_relative_coord.
#include <PixelToRobotRelativeCoord.hpp>
Public Member Functions
PixelToRobotRelativeCoord (int t_i=0)
Create a new PixelToRobotRelativeCoord.
PixelToRobotRelativeCoord (const PixelToRobotRelativeCoord &t_other)
Copy Constructor.
PixelToRobotRelativeCoord (const struct wb_pixel_to_robot_relative_coord &t_other)
Copy Constructor.
PixelToRobotRelativeCoord & operator= (const PixelToRobotRelativeCoord &t_other)
Copy Assignment Operator.
PixelToRobotRelativeCoord & operator= (const struct wb_pixel_to_robot_relative_coord &t_other)
Copy Assignment Operator.
bool operator== (const PixelToRobotRelativeCoord &t_other) const
bool operator!= (const PixelToRobotRelativeCoord &t_other) const
bool operator== (const wb_pixel_to_robot_relative_coord &t_other) const
bool operator!= (const wb_pixel_to_robot_relative_coord &t_other) const
int & i ()
const int & i () const
void set_i (const int &t_newValue)
PixelToRobotRelativeCoord (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_pixel_to_robot_relative_coord
int i
Nothing.
Detailed Description
Provides a C++ wrapper around wb_pixel_to_robot_relative_coord.
Definition at line 83 of file PixelToRobotRelativeCoord.hpp.
Constructor & Destructor Documentation
PixelToRobotRelativeCoord() [1/4]
guWhiteboard::PixelToRobotRelativeCoord::PixelToRobotRelativeCoord (int t_i = 0) inline
Create a new PixelToRobotRelativeCoord.
Definition at line 99 of file PixelToRobotRelativeCoord.hpp.
Referenced by operator==().
PixelToRobotRelativeCoord() [2/4]
guWhiteboard::PixelToRobotRelativeCoord::PixelToRobotRelativeCoord (const PixelToRobotRelativeCoord & t_other) inline
Copy Constructor.
Definition at line 106 of file PixelToRobotRelativeCoord.hpp.
References i().
PixelToRobotRelativeCoord() [3/4]
guWhiteboard::PixelToRobotRelativeCoord::PixelToRobotRelativeCoord (const struct wb_pixel_to_robot_relative_coord & t_other) inline
Copy Constructor.
Definition at line 113 of file PixelToRobotRelativeCoord.hpp.
References wb_pixel_to_robot_relative_coord::i.
PixelToRobotRelativeCoord() [4/4]
guWhiteboard::PixelToRobotRelativeCoord::PixelToRobotRelativeCoord (const std::string & t_str) inline
String Constructor.
Definition at line 172 of file PixelToRobotRelativeCoord.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::PixelToRobotRelativeCoord::description () inline
USE_WB_PIXEL_TO_ROBOT_RELATIVE_COORD_C_CONVERSION
Definition at line 177 of file PixelToRobotRelativeCoord.hpp.
References i(), PIXEL_TO_ROBOT_RELATIVE_COORD_DESC_BUFFER_SIZE, and wb_pixel_to_robot_relative_coord_description().
from_string()
void guWhiteboard::PixelToRobotRelativeCoord::from_string (const std::string & t_str) inline
USE_WB_PIXEL_TO_ROBOT_RELATIVE_COORD_C_CONVERSION
Definition at line 207 of file PixelToRobotRelativeCoord.hpp.
References i(), PIXEL_TO_ROBOT_RELATIVE_COORD_DESC_BUFFER_SIZE, and set_i().
Referenced by PixelToRobotRelativeCoord().
i() [1/2]
int & guWhiteboard::PixelToRobotRelativeCoord::i () inline
Definition at line 153 of file PixelToRobotRelativeCoord.hpp.
References wb_pixel_to_robot_relative_coord::i.
Referenced by PixelToRobotRelativeCoord(), description(), from_string(), operator=(), operator==(), and to_string().
i() [2/2]
const int & guWhiteboard::PixelToRobotRelativeCoord::i () const inline
Definition at line 158 of file PixelToRobotRelativeCoord.hpp.
References wb_pixel_to_robot_relative_coord::i.
operator!=() [1/2]
bool guWhiteboard::PixelToRobotRelativeCoord::operator!= (const PixelToRobotRelativeCoord & t_other) const inline
Definition at line 138 of file PixelToRobotRelativeCoord.hpp.
operator!=() [2/2]
bool guWhiteboard::PixelToRobotRelativeCoord::operator!= (const wb_pixel_to_robot_relative_coord & t_other) const inline
Definition at line 148 of file PixelToRobotRelativeCoord.hpp.
operator=() [1/2]
PixelToRobotRelativeCoord & guWhiteboard::PixelToRobotRelativeCoord::operator= (const PixelToRobotRelativeCoord & t_other) inline
Copy Assignment Operator.
Definition at line 120 of file PixelToRobotRelativeCoord.hpp.
References i().
operator=() [2/2]
PixelToRobotRelativeCoord & guWhiteboard::PixelToRobotRelativeCoord::operator= (const struct wb_pixel_to_robot_relative_coord & t_other) inline
Copy Assignment Operator.
Definition at line 128 of file PixelToRobotRelativeCoord.hpp.
References wb_pixel_to_robot_relative_coord::i.
operator==() [1/2]
bool guWhiteboard::PixelToRobotRelativeCoord::operator== (const PixelToRobotRelativeCoord & t_other) const inline
Definition at line 133 of file PixelToRobotRelativeCoord.hpp.
References i().
operator==() [2/2]
bool guWhiteboard::PixelToRobotRelativeCoord::operator== (const wb_pixel_to_robot_relative_coord & t_other) const inline
Definition at line 143 of file PixelToRobotRelativeCoord.hpp.
References PixelToRobotRelativeCoord().
set_i()
void guWhiteboard::PixelToRobotRelativeCoord::set_i (const int & t_newValue) inline
Definition at line 163 of file PixelToRobotRelativeCoord.hpp.
References wb_pixel_to_robot_relative_coord::i.
Referenced by from_string().
to_string()
std::string guWhiteboard::PixelToRobotRelativeCoord::to_string () inline
USE_WB_PIXEL_TO_ROBOT_RELATIVE_COORD_C_CONVERSION
Definition at line 190 of file PixelToRobotRelativeCoord.hpp.
References i(), PIXEL_TO_ROBOT_RELATIVE_COORD_TO_STRING_BUFFER_SIZE, and wb_pixel_to_robot_relative_coord_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/PixelToRobotRelativeCoord.hpp