gusimplewhiteboard: guWhiteboard::MicrophoneFrequencies Class Reference
guWhiteboard::MicrophoneFrequencies Class Reference
Provides a C++ wrapper around wb_microphone_frequencies.
#include <MicrophoneFrequencies.hpp>
Public Member Functions
MicrophoneFrequencies (int16_t t_rear_left=0, int16_t t_rear_right=0, int16_t t_front_left=0, int16_t t_front_right=0)
Create a new MicrophoneFrequencies.
MicrophoneFrequencies (const MicrophoneFrequencies &t_other)
Copy Constructor.
MicrophoneFrequencies (const struct wb_microphone_frequencies &t_other)
Copy Constructor.
MicrophoneFrequencies & operator= (const MicrophoneFrequencies &t_other)
Copy Assignment Operator.
MicrophoneFrequencies & operator= (const struct wb_microphone_frequencies &t_other)
Copy Assignment Operator.
bool operator== (const MicrophoneFrequencies &t_other) const
bool operator!= (const MicrophoneFrequencies &t_other) const
bool operator== (const wb_microphone_frequencies &t_other) const
bool operator!= (const wb_microphone_frequencies &t_other) const
int16_t & rear_left ()
const int16_t & rear_left () const
void set_rear_left (const int16_t &t_newValue)
int16_t & rear_right ()
const int16_t & rear_right () const
void set_rear_right (const int16_t &t_newValue)
int16_t & front_left ()
const int16_t & front_left () const
void set_front_left (const int16_t &t_newValue)
int16_t & front_right ()
const int16_t & front_right () const
void set_front_right (const int16_t &t_newValue)
MicrophoneFrequencies (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_microphone_frequencies
int16_t rear_left
rear left frequency
int16_t rear_right
rear right frequency
int16_t front_left
front left frequency
int16_t front_right
front left frequency
Detailed Description
Provides a C++ wrapper around wb_microphone_frequencies.
Definition at line 83 of file MicrophoneFrequencies.hpp.
Constructor & Destructor Documentation
MicrophoneFrequencies() [1/4]
guWhiteboard::MicrophoneFrequencies::MicrophoneFrequencies (int16_t t_rear_left = 0, int16_t t_rear_right = 0, int16_t t_front_left = 0, int16_t t_front_right = 0) inline
Create a new MicrophoneFrequencies.
Definition at line 102 of file MicrophoneFrequencies.hpp.
Referenced by operator==().
MicrophoneFrequencies() [2/4]
guWhiteboard::MicrophoneFrequencies::MicrophoneFrequencies (const MicrophoneFrequencies & t_other) inline
Copy Constructor.
Definition at line 109 of file MicrophoneFrequencies.hpp.
References front_left(), front_right(), rear_left(), and rear_right().
MicrophoneFrequencies() [3/4]
guWhiteboard::MicrophoneFrequencies::MicrophoneFrequencies (const struct wb_microphone_frequencies & t_other) inline
Copy Constructor.
Definition at line 116 of file MicrophoneFrequencies.hpp.
References wb_microphone_frequencies::front_left, wb_microphone_frequencies::front_right, wb_microphone_frequencies::rear_left, and wb_microphone_frequencies::rear_right.
MicrophoneFrequencies() [4/4]
guWhiteboard::MicrophoneFrequencies::MicrophoneFrequencies (const std::string & t_str) inline
String Constructor.
Definition at line 223 of file MicrophoneFrequencies.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::MicrophoneFrequencies::description () inline
USE_WB_MICROPHONE_FREQUENCIES_C_CONVERSION
Definition at line 228 of file MicrophoneFrequencies.hpp.
References front_left(), front_right(), MICROPHONE_FREQUENCIES_DESC_BUFFER_SIZE, rear_left(), rear_right(), and wb_microphone_frequencies_description().
from_string()
void guWhiteboard::MicrophoneFrequencies::from_string (const std::string & t_str) inline
USE_WB_MICROPHONE_FREQUENCIES_C_CONVERSION
Definition at line 270 of file MicrophoneFrequencies.hpp.
References MICROPHONE_FREQUENCIES_DESC_BUFFER_SIZE, set_front_left(), set_front_right(), set_rear_left(), and set_rear_right().
Referenced by MicrophoneFrequencies(), and guWhiteboard::DominantFrequencies::from_string().
front_left() [1/2]
int16_t & guWhiteboard::MicrophoneFrequencies::front_left () inline
Definition at line 189 of file MicrophoneFrequencies.hpp.
References wb_microphone_frequencies::front_left.
Referenced by MicrophoneFrequencies(), description(), operator=(), operator==(), and to_string().
front_left() [2/2]
const int16_t & guWhiteboard::MicrophoneFrequencies::front_left () const inline
Definition at line 194 of file MicrophoneFrequencies.hpp.
References wb_microphone_frequencies::front_left.
front_right() [1/2]
int16_t & guWhiteboard::MicrophoneFrequencies::front_right () inline
Definition at line 204 of file MicrophoneFrequencies.hpp.
References wb_microphone_frequencies::front_right.
Referenced by MicrophoneFrequencies(), description(), operator=(), operator==(), and to_string().
front_right() [2/2]
const int16_t & guWhiteboard::MicrophoneFrequencies::front_right () const inline
Definition at line 209 of file MicrophoneFrequencies.hpp.
References wb_microphone_frequencies::front_right.
operator!=() [1/2]
bool guWhiteboard::MicrophoneFrequencies::operator!= (const MicrophoneFrequencies & t_other) const inline
Definition at line 144 of file MicrophoneFrequencies.hpp.
operator!=() [2/2]
bool guWhiteboard::MicrophoneFrequencies::operator!= (const wb_microphone_frequencies & t_other) const inline
Definition at line 154 of file MicrophoneFrequencies.hpp.
operator=() [1/2]
MicrophoneFrequencies & guWhiteboard::MicrophoneFrequencies::operator= (const MicrophoneFrequencies & t_other) inline
Copy Assignment Operator.
Definition at line 123 of file MicrophoneFrequencies.hpp.
References front_left(), front_right(), rear_left(), and rear_right().
operator=() [2/2]
MicrophoneFrequencies & guWhiteboard::MicrophoneFrequencies::operator= (const struct wb_microphone_frequencies & t_other) inline
Copy Assignment Operator.
Definition at line 131 of file MicrophoneFrequencies.hpp.
References wb_microphone_frequencies::front_left, wb_microphone_frequencies::front_right, wb_microphone_frequencies::rear_left, and wb_microphone_frequencies::rear_right.
operator==() [1/2]
bool guWhiteboard::MicrophoneFrequencies::operator== (const MicrophoneFrequencies & t_other) const inline
Definition at line 136 of file MicrophoneFrequencies.hpp.
References front_left(), front_right(), rear_left(), and rear_right().
operator==() [2/2]
bool guWhiteboard::MicrophoneFrequencies::operator== (const wb_microphone_frequencies & t_other) const inline
Definition at line 149 of file MicrophoneFrequencies.hpp.
References MicrophoneFrequencies().
rear_left() [1/2]
int16_t & guWhiteboard::MicrophoneFrequencies::rear_left () inline
Definition at line 159 of file MicrophoneFrequencies.hpp.
References wb_microphone_frequencies::rear_left.
Referenced by MicrophoneFrequencies(), description(), operator=(), operator==(), and to_string().
rear_left() [2/2]
const int16_t & guWhiteboard::MicrophoneFrequencies::rear_left () const inline
Definition at line 164 of file MicrophoneFrequencies.hpp.
References wb_microphone_frequencies::rear_left.
rear_right() [1/2]
int16_t & guWhiteboard::MicrophoneFrequencies::rear_right () inline
Definition at line 174 of file MicrophoneFrequencies.hpp.
References wb_microphone_frequencies::rear_right.
Referenced by MicrophoneFrequencies(), description(), operator=(), operator==(), and to_string().
rear_right() [2/2]
const int16_t & guWhiteboard::MicrophoneFrequencies::rear_right () const inline
Definition at line 179 of file MicrophoneFrequencies.hpp.
References wb_microphone_frequencies::rear_right.
set_front_left()
void guWhiteboard::MicrophoneFrequencies::set_front_left (const int16_t & t_newValue) inline
Definition at line 199 of file MicrophoneFrequencies.hpp.
References wb_microphone_frequencies::front_left.
Referenced by from_string().
set_front_right()
void guWhiteboard::MicrophoneFrequencies::set_front_right (const int16_t & t_newValue) inline
Definition at line 214 of file MicrophoneFrequencies.hpp.
References wb_microphone_frequencies::front_right.
Referenced by from_string().
set_rear_left()
void guWhiteboard::MicrophoneFrequencies::set_rear_left (const int16_t & t_newValue) inline
Definition at line 169 of file MicrophoneFrequencies.hpp.
References wb_microphone_frequencies::rear_left.
Referenced by from_string().
set_rear_right()
void guWhiteboard::MicrophoneFrequencies::set_rear_right (const int16_t & t_newValue) inline
Definition at line 184 of file MicrophoneFrequencies.hpp.
References wb_microphone_frequencies::rear_right.
Referenced by from_string().
to_string()
std::string guWhiteboard::MicrophoneFrequencies::to_string () inline
USE_WB_MICROPHONE_FREQUENCIES_C_CONVERSION
Definition at line 247 of file MicrophoneFrequencies.hpp.
References front_left(), front_right(), MICROPHONE_FREQUENCIES_TO_STRING_BUFFER_SIZE, rear_left(), rear_right(), and wb_microphone_frequencies_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/MicrophoneFrequencies.hpp