gusimplewhiteboard: guWhiteboard::SensorsFootSensors Class Reference
guWhiteboard::SensorsFootSensors Class Reference
Provides a C++ wrapper around wb_sensors_foot_sensors.
#include <SensorsFootSensors.hpp>
Public Member Functions
SensorsFootSensors (float t_LFoot_FSR_FrontLeft=0.0f, float t_LFoot_FSR_FrontRight=0.0f, float t_LFoot_FSR_RearLeft=0.0f, float t_LFoot_FSR_RearRight=0.0f, float t_LFoot_FSR_CenterOfPressure_X=0.0f, float t_LFoot_FSR_CenterOfPressure_Y=0.0f, float t_LFoot_FSR_TotalWeight=0.0f, float t_RFoot_FSR_FrontLeft=0.0f, float t_RFoot_FSR_FrontRight=0.0f, float t_RFoot_FSR_RearLeft=0.0f, float t_RFoot_FSR_RearRight=0.0f, float t_RFoot_FSR_CenterOfPressure_X=0.0f, float t_RFoot_FSR_CenterOfPressure_Y=0.0f, float t_RFoot_FSR_TotalWeight=0.0f, bool t_LFoot_Bumper_Left=true, bool t_LFoot_Bumper_Right=true, bool t_RFoot_Bumper_Left=true, bool t_RFoot_Bumper_Right=true)
Create a new SensorsFootSensors.
SensorsFootSensors (const SensorsFootSensors &t_other)
Copy Constructor.
SensorsFootSensors (const struct wb_sensors_foot_sensors &t_other)
Copy Constructor.
SensorsFootSensors & operator= (const SensorsFootSensors &t_other)
Copy Assignment Operator.
SensorsFootSensors & operator= (const struct wb_sensors_foot_sensors &t_other)
Copy Assignment Operator.
bool operator== (const SensorsFootSensors &t_other) const
bool operator!= (const SensorsFootSensors &t_other) const
bool operator== (const wb_sensors_foot_sensors &t_other) const
bool operator!= (const wb_sensors_foot_sensors &t_other) const
float & LFoot_FSR_FrontLeft ()
const float & LFoot_FSR_FrontLeft () const
void set_LFoot_FSR_FrontLeft (const float &t_newValue)
float & LFoot_FSR_FrontRight ()
const float & LFoot_FSR_FrontRight () const
void set_LFoot_FSR_FrontRight (const float &t_newValue)
float & LFoot_FSR_RearLeft ()
const float & LFoot_FSR_RearLeft () const
void set_LFoot_FSR_RearLeft (const float &t_newValue)
float & LFoot_FSR_RearRight ()
const float & LFoot_FSR_RearRight () const
void set_LFoot_FSR_RearRight (const float &t_newValue)
float & LFoot_FSR_CenterOfPressure_X ()
const float & LFoot_FSR_CenterOfPressure_X () const
void set_LFoot_FSR_CenterOfPressure_X (const float &t_newValue)
float & LFoot_FSR_CenterOfPressure_Y ()
const float & LFoot_FSR_CenterOfPressure_Y () const
void set_LFoot_FSR_CenterOfPressure_Y (const float &t_newValue)
float & LFoot_FSR_TotalWeight ()
const float & LFoot_FSR_TotalWeight () const
void set_LFoot_FSR_TotalWeight (const float &t_newValue)
float & RFoot_FSR_FrontLeft ()
const float & RFoot_FSR_FrontLeft () const
void set_RFoot_FSR_FrontLeft (const float &t_newValue)
float & RFoot_FSR_FrontRight ()
const float & RFoot_FSR_FrontRight () const
void set_RFoot_FSR_FrontRight (const float &t_newValue)
float & RFoot_FSR_RearLeft ()
const float & RFoot_FSR_RearLeft () const
void set_RFoot_FSR_RearLeft (const float &t_newValue)
float & RFoot_FSR_RearRight ()
const float & RFoot_FSR_RearRight () const
void set_RFoot_FSR_RearRight (const float &t_newValue)
float & RFoot_FSR_CenterOfPressure_X ()
const float & RFoot_FSR_CenterOfPressure_X () const
void set_RFoot_FSR_CenterOfPressure_X (const float &t_newValue)
float & RFoot_FSR_CenterOfPressure_Y ()
const float & RFoot_FSR_CenterOfPressure_Y () const
void set_RFoot_FSR_CenterOfPressure_Y (const float &t_newValue)
float & RFoot_FSR_TotalWeight ()
const float & RFoot_FSR_TotalWeight () const
void set_RFoot_FSR_TotalWeight (const float &t_newValue)
bool & LFoot_Bumper_Left ()
const bool & LFoot_Bumper_Left () const
void set_LFoot_Bumper_Left (const bool &t_newValue)
bool & LFoot_Bumper_Right ()
const bool & LFoot_Bumper_Right () const
void set_LFoot_Bumper_Right (const bool &t_newValue)
bool & RFoot_Bumper_Left ()
const bool & RFoot_Bumper_Left () const
void set_RFoot_Bumper_Left (const bool &t_newValue)
bool & RFoot_Bumper_Right ()
const bool & RFoot_Bumper_Right () const
void set_RFoot_Bumper_Right (const bool &t_newValue)
SensorsFootSensors (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_sensors_foot_sensors
float LFoot_FSR_FrontLeft
front left force sensor on the left foot
float LFoot_FSR_FrontRight
front right force sensor on the left foot
float LFoot_FSR_RearLeft
rear left force sensor on the left foot
float LFoot_FSR_RearRight
rear right force sensor on the left foot
float LFoot_FSR_CenterOfPressure_X
left foot center of pressure X
float LFoot_FSR_CenterOfPressure_Y
left foot center of pressure Y
float LFoot_FSR_TotalWeight
Total weight on left foot (kg)
float RFoot_FSR_FrontLeft
front left force sensor on the right foot
float RFoot_FSR_FrontRight
front right force sensor on the right foot
float RFoot_FSR_RearLeft
rear left force sensor on the right foot
float RFoot_FSR_RearRight
rear right force sensor on the right foot
float RFoot_FSR_CenterOfPressure_X
right foot center of pressure X
float RFoot_FSR_CenterOfPressure_Y
right foot center of pressure Y
float RFoot_FSR_TotalWeight
Total weight right foot (kg)
bool LFoot_Bumper_Left
left bumper on the left foot (on / off)
bool LFoot_Bumper_Right
right bumper on the left foot (on / off)
bool RFoot_Bumper_Left
left bumper on the right foot (on / off)
bool RFoot_Bumper_Right
right bumper on the right foot (on / off)
Detailed Description
Provides a C++ wrapper around wb_sensors_foot_sensors.
Definition at line 84 of file SensorsFootSensors.hpp.
Constructor & Destructor Documentation
SensorsFootSensors() [1/4]
guWhiteboard::SensorsFootSensors::SensorsFootSensors (float t_LFoot_FSR_FrontLeft = 0.0f, float t_LFoot_FSR_FrontRight = 0.0f, float t_LFoot_FSR_RearLeft = 0.0f, float t_LFoot_FSR_RearRight = 0.0f, float t_LFoot_FSR_CenterOfPressure_X = 0.0f, float t_LFoot_FSR_CenterOfPressure_Y = 0.0f, float t_LFoot_FSR_TotalWeight = 0.0f, float t_RFoot_FSR_FrontLeft = 0.0f, float t_RFoot_FSR_FrontRight = 0.0f, float t_RFoot_FSR_RearLeft = 0.0f, float t_RFoot_FSR_RearRight = 0.0f, float t_RFoot_FSR_CenterOfPressure_X = 0.0f, float t_RFoot_FSR_CenterOfPressure_Y = 0.0f, float t_RFoot_FSR_TotalWeight = 0.0f, bool t_LFoot_Bumper_Left = true, bool t_LFoot_Bumper_Right = true, bool t_RFoot_Bumper_Left = true, bool t_RFoot_Bumper_Right = true) inline
Create a new SensorsFootSensors.
Definition at line 117 of file SensorsFootSensors.hpp.
Referenced by operator==().
SensorsFootSensors() [2/4]
guWhiteboard::SensorsFootSensors::SensorsFootSensors (const SensorsFootSensors & t_other) inline
Copy Constructor.
Definition at line 124 of file SensorsFootSensors.hpp.
References LFoot_Bumper_Left(), LFoot_Bumper_Right(), LFoot_FSR_CenterOfPressure_X(), LFoot_FSR_CenterOfPressure_Y(), LFoot_FSR_FrontLeft(), LFoot_FSR_FrontRight(), LFoot_FSR_RearLeft(), LFoot_FSR_RearRight(), LFoot_FSR_TotalWeight(), RFoot_Bumper_Left(), RFoot_Bumper_Right(), RFoot_FSR_CenterOfPressure_X(), RFoot_FSR_CenterOfPressure_Y(), RFoot_FSR_FrontLeft(), RFoot_FSR_FrontRight(), RFoot_FSR_RearLeft(), RFoot_FSR_RearRight(), and RFoot_FSR_TotalWeight().
SensorsFootSensors() [3/4]
guWhiteboard::SensorsFootSensors::SensorsFootSensors (const struct wb_sensors_foot_sensors & t_other) inline
Copy Constructor.
Definition at line 131 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_Bumper_Left, wb_sensors_foot_sensors::LFoot_Bumper_Right, wb_sensors_foot_sensors::LFoot_FSR_CenterOfPressure_X, wb_sensors_foot_sensors::LFoot_FSR_CenterOfPressure_Y, wb_sensors_foot_sensors::LFoot_FSR_FrontLeft, wb_sensors_foot_sensors::LFoot_FSR_FrontRight, wb_sensors_foot_sensors::LFoot_FSR_RearLeft, wb_sensors_foot_sensors::LFoot_FSR_RearRight, wb_sensors_foot_sensors::LFoot_FSR_TotalWeight, wb_sensors_foot_sensors::RFoot_Bumper_Left, wb_sensors_foot_sensors::RFoot_Bumper_Right, wb_sensors_foot_sensors::RFoot_FSR_CenterOfPressure_X, wb_sensors_foot_sensors::RFoot_FSR_CenterOfPressure_Y, wb_sensors_foot_sensors::RFoot_FSR_FrontLeft, wb_sensors_foot_sensors::RFoot_FSR_FrontRight, wb_sensors_foot_sensors::RFoot_FSR_RearLeft, wb_sensors_foot_sensors::RFoot_FSR_RearRight, and wb_sensors_foot_sensors::RFoot_FSR_TotalWeight.
SensorsFootSensors() [4/4]
guWhiteboard::SensorsFootSensors::SensorsFootSensors (const std::string & t_str) inline
String Constructor.
Definition at line 462 of file SensorsFootSensors.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::SensorsFootSensors::description () inline
USE_WB_SENSORS_FOOT_SENSORS_C_CONVERSION
Definition at line 467 of file SensorsFootSensors.hpp.
References LFoot_Bumper_Left(), LFoot_Bumper_Right(), LFoot_FSR_CenterOfPressure_X(), LFoot_FSR_CenterOfPressure_Y(), LFoot_FSR_FrontLeft(), LFoot_FSR_FrontRight(), LFoot_FSR_RearLeft(), LFoot_FSR_RearRight(), LFoot_FSR_TotalWeight(), RFoot_Bumper_Left(), RFoot_Bumper_Right(), RFoot_FSR_CenterOfPressure_X(), RFoot_FSR_CenterOfPressure_Y(), RFoot_FSR_FrontLeft(), RFoot_FSR_FrontRight(), RFoot_FSR_RearLeft(), RFoot_FSR_RearRight(), RFoot_FSR_TotalWeight(), SENSORS_FOOT_SENSORS_DESC_BUFFER_SIZE, and wb_sensors_foot_sensors_description().
from_string()
void guWhiteboard::SensorsFootSensors::from_string (const std::string & t_str) inline
USE_WB_SENSORS_FOOT_SENSORS_C_CONVERSION
Definition at line 565 of file SensorsFootSensors.hpp.
References SENSORS_FOOT_SENSORS_DESC_BUFFER_SIZE, set_LFoot_Bumper_Left(), set_LFoot_Bumper_Right(), set_LFoot_FSR_CenterOfPressure_X(), set_LFoot_FSR_CenterOfPressure_Y(), set_LFoot_FSR_FrontLeft(), set_LFoot_FSR_FrontRight(), set_LFoot_FSR_RearLeft(), set_LFoot_FSR_RearRight(), set_LFoot_FSR_TotalWeight(), set_RFoot_Bumper_Left(), set_RFoot_Bumper_Right(), set_RFoot_FSR_CenterOfPressure_X(), set_RFoot_FSR_CenterOfPressure_Y(), set_RFoot_FSR_FrontLeft(), set_RFoot_FSR_FrontRight(), set_RFoot_FSR_RearLeft(), set_RFoot_FSR_RearRight(), and set_RFoot_FSR_TotalWeight().
Referenced by SensorsFootSensors().
LFoot_Bumper_Left() [1/2]
bool & guWhiteboard::SensorsFootSensors::LFoot_Bumper_Left () inline
Definition at line 398 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_Bumper_Left.
Referenced by SensorsFootSensors(), description(), operator=(), operator==(), and to_string().
LFoot_Bumper_Left() [2/2]
const bool & guWhiteboard::SensorsFootSensors::LFoot_Bumper_Left () const inline
Definition at line 403 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_Bumper_Left.
LFoot_Bumper_Right() [1/2]
bool & guWhiteboard::SensorsFootSensors::LFoot_Bumper_Right () inline
Definition at line 413 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_Bumper_Right.
Referenced by SensorsFootSensors(), description(), operator=(), operator==(), and to_string().
LFoot_Bumper_Right() [2/2]
const bool & guWhiteboard::SensorsFootSensors::LFoot_Bumper_Right () const inline
Definition at line 418 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_Bumper_Right.
LFoot_FSR_CenterOfPressure_X() [1/2]
float & guWhiteboard::SensorsFootSensors::LFoot_FSR_CenterOfPressure_X () inline
Definition at line 248 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_FSR_CenterOfPressure_X.
Referenced by SensorsFootSensors(), description(), operator=(), operator==(), and to_string().
LFoot_FSR_CenterOfPressure_X() [2/2]
const float & guWhiteboard::SensorsFootSensors::LFoot_FSR_CenterOfPressure_X () const inline
Definition at line 253 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_FSR_CenterOfPressure_X.
LFoot_FSR_CenterOfPressure_Y() [1/2]
float & guWhiteboard::SensorsFootSensors::LFoot_FSR_CenterOfPressure_Y () inline
Definition at line 263 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_FSR_CenterOfPressure_Y.
Referenced by SensorsFootSensors(), description(), operator=(), operator==(), and to_string().
LFoot_FSR_CenterOfPressure_Y() [2/2]
const float & guWhiteboard::SensorsFootSensors::LFoot_FSR_CenterOfPressure_Y () const inline
Definition at line 268 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_FSR_CenterOfPressure_Y.
LFoot_FSR_FrontLeft() [1/2]
float & guWhiteboard::SensorsFootSensors::LFoot_FSR_FrontLeft () inline
Definition at line 188 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_FSR_FrontLeft.
Referenced by SensorsFootSensors(), description(), operator=(), operator==(), and to_string().
LFoot_FSR_FrontLeft() [2/2]
const float & guWhiteboard::SensorsFootSensors::LFoot_FSR_FrontLeft () const inline
Definition at line 193 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_FSR_FrontLeft.
LFoot_FSR_FrontRight() [1/2]
float & guWhiteboard::SensorsFootSensors::LFoot_FSR_FrontRight () inline
Definition at line 203 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_FSR_FrontRight.
Referenced by SensorsFootSensors(), description(), operator=(), operator==(), and to_string().
LFoot_FSR_FrontRight() [2/2]
const float & guWhiteboard::SensorsFootSensors::LFoot_FSR_FrontRight () const inline
Definition at line 208 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_FSR_FrontRight.
LFoot_FSR_RearLeft() [1/2]
float & guWhiteboard::SensorsFootSensors::LFoot_FSR_RearLeft () inline
Definition at line 218 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_FSR_RearLeft.
Referenced by SensorsFootSensors(), description(), operator=(), operator==(), and to_string().
LFoot_FSR_RearLeft() [2/2]
const float & guWhiteboard::SensorsFootSensors::LFoot_FSR_RearLeft () const inline
Definition at line 223 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_FSR_RearLeft.
LFoot_FSR_RearRight() [1/2]
float & guWhiteboard::SensorsFootSensors::LFoot_FSR_RearRight () inline
Definition at line 233 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_FSR_RearRight.
Referenced by SensorsFootSensors(), description(), operator=(), operator==(), and to_string().
LFoot_FSR_RearRight() [2/2]
const float & guWhiteboard::SensorsFootSensors::LFoot_FSR_RearRight () const inline
Definition at line 238 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_FSR_RearRight.
LFoot_FSR_TotalWeight() [1/2]
float & guWhiteboard::SensorsFootSensors::LFoot_FSR_TotalWeight () inline
Definition at line 278 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_FSR_TotalWeight.
Referenced by SensorsFootSensors(), description(), operator=(), operator==(), and to_string().
LFoot_FSR_TotalWeight() [2/2]
const float & guWhiteboard::SensorsFootSensors::LFoot_FSR_TotalWeight () const inline
Definition at line 283 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_FSR_TotalWeight.
operator!=() [1/2]
bool guWhiteboard::SensorsFootSensors::operator!= (const SensorsFootSensors & t_other) const inline
Definition at line 173 of file SensorsFootSensors.hpp.
operator!=() [2/2]
bool guWhiteboard::SensorsFootSensors::operator!= (const wb_sensors_foot_sensors & t_other) const inline
Definition at line 183 of file SensorsFootSensors.hpp.
operator=() [1/2]
SensorsFootSensors & guWhiteboard::SensorsFootSensors::operator= (const SensorsFootSensors & t_other) inline
Copy Assignment Operator.
Definition at line 138 of file SensorsFootSensors.hpp.
References LFoot_Bumper_Left(), LFoot_Bumper_Right(), LFoot_FSR_CenterOfPressure_X(), LFoot_FSR_CenterOfPressure_Y(), LFoot_FSR_FrontLeft(), LFoot_FSR_FrontRight(), LFoot_FSR_RearLeft(), LFoot_FSR_RearRight(), LFoot_FSR_TotalWeight(), RFoot_Bumper_Left(), RFoot_Bumper_Right(), RFoot_FSR_CenterOfPressure_X(), RFoot_FSR_CenterOfPressure_Y(), RFoot_FSR_FrontLeft(), RFoot_FSR_FrontRight(), RFoot_FSR_RearLeft(), RFoot_FSR_RearRight(), and RFoot_FSR_TotalWeight().
operator=() [2/2]
SensorsFootSensors & guWhiteboard::SensorsFootSensors::operator= (const struct wb_sensors_foot_sensors & t_other) inline
Copy Assignment Operator.
Definition at line 146 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_Bumper_Left, wb_sensors_foot_sensors::LFoot_Bumper_Right, wb_sensors_foot_sensors::LFoot_FSR_CenterOfPressure_X, wb_sensors_foot_sensors::LFoot_FSR_CenterOfPressure_Y, wb_sensors_foot_sensors::LFoot_FSR_FrontLeft, wb_sensors_foot_sensors::LFoot_FSR_FrontRight, wb_sensors_foot_sensors::LFoot_FSR_RearLeft, wb_sensors_foot_sensors::LFoot_FSR_RearRight, wb_sensors_foot_sensors::LFoot_FSR_TotalWeight, wb_sensors_foot_sensors::RFoot_Bumper_Left, wb_sensors_foot_sensors::RFoot_Bumper_Right, wb_sensors_foot_sensors::RFoot_FSR_CenterOfPressure_X, wb_sensors_foot_sensors::RFoot_FSR_CenterOfPressure_Y, wb_sensors_foot_sensors::RFoot_FSR_FrontLeft, wb_sensors_foot_sensors::RFoot_FSR_FrontRight, wb_sensors_foot_sensors::RFoot_FSR_RearLeft, wb_sensors_foot_sensors::RFoot_FSR_RearRight, and wb_sensors_foot_sensors::RFoot_FSR_TotalWeight.
operator==() [1/2]
bool guWhiteboard::SensorsFootSensors::operator== (const SensorsFootSensors & t_other) const inline
Definition at line 151 of file SensorsFootSensors.hpp.
References LFoot_Bumper_Left(), LFoot_Bumper_Right(), LFoot_FSR_CenterOfPressure_X(), LFoot_FSR_CenterOfPressure_Y(), LFoot_FSR_FrontLeft(), LFoot_FSR_FrontRight(), LFoot_FSR_RearLeft(), LFoot_FSR_RearRight(), LFoot_FSR_TotalWeight(), RFoot_Bumper_Left(), RFoot_Bumper_Right(), RFoot_FSR_CenterOfPressure_X(), RFoot_FSR_CenterOfPressure_Y(), RFoot_FSR_FrontLeft(), RFoot_FSR_FrontRight(), RFoot_FSR_RearLeft(), RFoot_FSR_RearRight(), and RFoot_FSR_TotalWeight().
operator==() [2/2]
bool guWhiteboard::SensorsFootSensors::operator== (const wb_sensors_foot_sensors & t_other) const inline
Definition at line 178 of file SensorsFootSensors.hpp.
References SensorsFootSensors().
RFoot_Bumper_Left() [1/2]
bool & guWhiteboard::SensorsFootSensors::RFoot_Bumper_Left () inline
Definition at line 428 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_Bumper_Left.
Referenced by SensorsFootSensors(), description(), operator=(), operator==(), and to_string().
RFoot_Bumper_Left() [2/2]
const bool & guWhiteboard::SensorsFootSensors::RFoot_Bumper_Left () const inline
Definition at line 433 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_Bumper_Left.
RFoot_Bumper_Right() [1/2]
bool & guWhiteboard::SensorsFootSensors::RFoot_Bumper_Right () inline
Definition at line 443 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_Bumper_Right.
Referenced by SensorsFootSensors(), description(), operator=(), operator==(), and to_string().
RFoot_Bumper_Right() [2/2]
const bool & guWhiteboard::SensorsFootSensors::RFoot_Bumper_Right () const inline
Definition at line 448 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_Bumper_Right.
RFoot_FSR_CenterOfPressure_X() [1/2]
float & guWhiteboard::SensorsFootSensors::RFoot_FSR_CenterOfPressure_X () inline
Definition at line 353 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_FSR_CenterOfPressure_X.
Referenced by SensorsFootSensors(), description(), operator=(), operator==(), and to_string().
RFoot_FSR_CenterOfPressure_X() [2/2]
const float & guWhiteboard::SensorsFootSensors::RFoot_FSR_CenterOfPressure_X () const inline
Definition at line 358 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_FSR_CenterOfPressure_X.
RFoot_FSR_CenterOfPressure_Y() [1/2]
float & guWhiteboard::SensorsFootSensors::RFoot_FSR_CenterOfPressure_Y () inline
Definition at line 368 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_FSR_CenterOfPressure_Y.
Referenced by SensorsFootSensors(), description(), operator=(), operator==(), and to_string().
RFoot_FSR_CenterOfPressure_Y() [2/2]
const float & guWhiteboard::SensorsFootSensors::RFoot_FSR_CenterOfPressure_Y () const inline
Definition at line 373 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_FSR_CenterOfPressure_Y.
RFoot_FSR_FrontLeft() [1/2]
float & guWhiteboard::SensorsFootSensors::RFoot_FSR_FrontLeft () inline
Definition at line 293 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_FSR_FrontLeft.
Referenced by SensorsFootSensors(), description(), operator=(), operator==(), and to_string().
RFoot_FSR_FrontLeft() [2/2]
const float & guWhiteboard::SensorsFootSensors::RFoot_FSR_FrontLeft () const inline
Definition at line 298 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_FSR_FrontLeft.
RFoot_FSR_FrontRight() [1/2]
float & guWhiteboard::SensorsFootSensors::RFoot_FSR_FrontRight () inline
Definition at line 308 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_FSR_FrontRight.
Referenced by SensorsFootSensors(), description(), operator=(), operator==(), and to_string().
RFoot_FSR_FrontRight() [2/2]
const float & guWhiteboard::SensorsFootSensors::RFoot_FSR_FrontRight () const inline
Definition at line 313 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_FSR_FrontRight.
RFoot_FSR_RearLeft() [1/2]
float & guWhiteboard::SensorsFootSensors::RFoot_FSR_RearLeft () inline
Definition at line 323 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_FSR_RearLeft.
Referenced by SensorsFootSensors(), description(), operator=(), operator==(), and to_string().
RFoot_FSR_RearLeft() [2/2]
const float & guWhiteboard::SensorsFootSensors::RFoot_FSR_RearLeft () const inline
Definition at line 328 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_FSR_RearLeft.
RFoot_FSR_RearRight() [1/2]
float & guWhiteboard::SensorsFootSensors::RFoot_FSR_RearRight () inline
Definition at line 338 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_FSR_RearRight.
Referenced by SensorsFootSensors(), description(), operator=(), operator==(), and to_string().
RFoot_FSR_RearRight() [2/2]
const float & guWhiteboard::SensorsFootSensors::RFoot_FSR_RearRight () const inline
Definition at line 343 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_FSR_RearRight.
RFoot_FSR_TotalWeight() [1/2]
float & guWhiteboard::SensorsFootSensors::RFoot_FSR_TotalWeight () inline
Definition at line 383 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_FSR_TotalWeight.
Referenced by SensorsFootSensors(), description(), operator=(), operator==(), and to_string().
RFoot_FSR_TotalWeight() [2/2]
const float & guWhiteboard::SensorsFootSensors::RFoot_FSR_TotalWeight () const inline
Definition at line 388 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_FSR_TotalWeight.
set_LFoot_Bumper_Left()
void guWhiteboard::SensorsFootSensors::set_LFoot_Bumper_Left (const bool & t_newValue) inline
Definition at line 408 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_Bumper_Left.
Referenced by from_string().
set_LFoot_Bumper_Right()
void guWhiteboard::SensorsFootSensors::set_LFoot_Bumper_Right (const bool & t_newValue) inline
Definition at line 423 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_Bumper_Right.
Referenced by from_string().
set_LFoot_FSR_CenterOfPressure_X()
void guWhiteboard::SensorsFootSensors::set_LFoot_FSR_CenterOfPressure_X (const float & t_newValue) inline
Definition at line 258 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_FSR_CenterOfPressure_X.
Referenced by from_string().
set_LFoot_FSR_CenterOfPressure_Y()
void guWhiteboard::SensorsFootSensors::set_LFoot_FSR_CenterOfPressure_Y (const float & t_newValue) inline
Definition at line 273 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_FSR_CenterOfPressure_Y.
Referenced by from_string().
set_LFoot_FSR_FrontLeft()
void guWhiteboard::SensorsFootSensors::set_LFoot_FSR_FrontLeft (const float & t_newValue) inline
Definition at line 198 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_FSR_FrontLeft.
Referenced by from_string().
set_LFoot_FSR_FrontRight()
void guWhiteboard::SensorsFootSensors::set_LFoot_FSR_FrontRight (const float & t_newValue) inline
Definition at line 213 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_FSR_FrontRight.
Referenced by from_string().
set_LFoot_FSR_RearLeft()
void guWhiteboard::SensorsFootSensors::set_LFoot_FSR_RearLeft (const float & t_newValue) inline
Definition at line 228 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_FSR_RearLeft.
Referenced by from_string().
set_LFoot_FSR_RearRight()
void guWhiteboard::SensorsFootSensors::set_LFoot_FSR_RearRight (const float & t_newValue) inline
Definition at line 243 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_FSR_RearRight.
Referenced by from_string().
set_LFoot_FSR_TotalWeight()
void guWhiteboard::SensorsFootSensors::set_LFoot_FSR_TotalWeight (const float & t_newValue) inline
Definition at line 288 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::LFoot_FSR_TotalWeight.
Referenced by from_string().
set_RFoot_Bumper_Left()
void guWhiteboard::SensorsFootSensors::set_RFoot_Bumper_Left (const bool & t_newValue) inline
Definition at line 438 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_Bumper_Left.
Referenced by from_string().
set_RFoot_Bumper_Right()
void guWhiteboard::SensorsFootSensors::set_RFoot_Bumper_Right (const bool & t_newValue) inline
Definition at line 453 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_Bumper_Right.
Referenced by from_string().
set_RFoot_FSR_CenterOfPressure_X()
void guWhiteboard::SensorsFootSensors::set_RFoot_FSR_CenterOfPressure_X (const float & t_newValue) inline
Definition at line 363 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_FSR_CenterOfPressure_X.
Referenced by from_string().
set_RFoot_FSR_CenterOfPressure_Y()
void guWhiteboard::SensorsFootSensors::set_RFoot_FSR_CenterOfPressure_Y (const float & t_newValue) inline
Definition at line 378 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_FSR_CenterOfPressure_Y.
Referenced by from_string().
set_RFoot_FSR_FrontLeft()
void guWhiteboard::SensorsFootSensors::set_RFoot_FSR_FrontLeft (const float & t_newValue) inline
Definition at line 303 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_FSR_FrontLeft.
Referenced by from_string().
set_RFoot_FSR_FrontRight()
void guWhiteboard::SensorsFootSensors::set_RFoot_FSR_FrontRight (const float & t_newValue) inline
Definition at line 318 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_FSR_FrontRight.
Referenced by from_string().
set_RFoot_FSR_RearLeft()
void guWhiteboard::SensorsFootSensors::set_RFoot_FSR_RearLeft (const float & t_newValue) inline
Definition at line 333 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_FSR_RearLeft.
Referenced by from_string().
set_RFoot_FSR_RearRight()
void guWhiteboard::SensorsFootSensors::set_RFoot_FSR_RearRight (const float & t_newValue) inline
Definition at line 348 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_FSR_RearRight.
Referenced by from_string().
set_RFoot_FSR_TotalWeight()
void guWhiteboard::SensorsFootSensors::set_RFoot_FSR_TotalWeight (const float & t_newValue) inline
Definition at line 393 of file SensorsFootSensors.hpp.
References wb_sensors_foot_sensors::RFoot_FSR_TotalWeight.
Referenced by from_string().
to_string()
std::string guWhiteboard::SensorsFootSensors::to_string () inline
USE_WB_SENSORS_FOOT_SENSORS_C_CONVERSION
Definition at line 514 of file SensorsFootSensors.hpp.
References LFoot_Bumper_Left(), LFoot_Bumper_Right(), LFoot_FSR_CenterOfPressure_X(), LFoot_FSR_CenterOfPressure_Y(), LFoot_FSR_FrontLeft(), LFoot_FSR_FrontRight(), LFoot_FSR_RearLeft(), LFoot_FSR_RearRight(), LFoot_FSR_TotalWeight(), RFoot_Bumper_Left(), RFoot_Bumper_Right(), RFoot_FSR_CenterOfPressure_X(), RFoot_FSR_CenterOfPressure_Y(), RFoot_FSR_FrontLeft(), RFoot_FSR_FrontRight(), RFoot_FSR_RearLeft(), RFoot_FSR_RearRight(), RFoot_FSR_TotalWeight(), SENSORS_FOOT_SENSORS_TO_STRING_BUFFER_SIZE, and wb_sensors_foot_sensors_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/SensorsFootSensors.hpp