gusimplewhiteboard: guWhiteboard::MachineFilteredVision Class Reference
guWhiteboard::MachineFilteredVision Class Reference
Provides a C++ wrapper around wb_machine_filtered_vision.
#include <MachineFilteredVision.hpp>
Public Member Functions
MachineFilteredVision (int8_t t_ball_direction=0, uint16_t t_ball_distance=0, bool t_ball_visible=0, int8_t t_goal_direction=0, uint16_t t_goal_distance=0, bool t_goal_visible=0, enum GoalSightingType t_goal_sightingType=NoSightingType)
Create a new MachineFilteredVision.
MachineFilteredVision (const MachineFilteredVision &t_other)
Copy Constructor.
MachineFilteredVision (const struct wb_machine_filtered_vision &t_other)
Copy Constructor.
MachineFilteredVision & operator= (const MachineFilteredVision &t_other)
Copy Assignment Operator.
MachineFilteredVision & operator= (const struct wb_machine_filtered_vision &t_other)
Copy Assignment Operator.
bool operator== (const MachineFilteredVision &t_other) const
bool operator!= (const MachineFilteredVision &t_other) const
bool operator== (const wb_machine_filtered_vision &t_other) const
bool operator!= (const wb_machine_filtered_vision &t_other) const
int8_t & ball_direction ()
const int8_t & ball_direction () const
void set_ball_direction (const int8_t &t_newValue)
uint16_t & ball_distance ()
const uint16_t & ball_distance () const
void set_ball_distance (const uint16_t &t_newValue)
bool & ball_visible ()
const bool & ball_visible () const
void set_ball_visible (const bool &t_newValue)
int8_t & goal_direction ()
const int8_t & goal_direction () const
void set_goal_direction (const int8_t &t_newValue)
uint16_t & goal_distance ()
const uint16_t & goal_distance () const
void set_goal_distance (const uint16_t &t_newValue)
bool & goal_visible ()
const bool & goal_visible () const
void set_goal_visible (const bool &t_newValue)
enum GoalSightingType & goal_sightingType ()
enum GoalSightingType & goal_sightingType () const
void set_goal_sightingType (const enum GoalSightingType &t_newValue)
MachineFilteredVision (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_machine_filtered_vision
int8_t ball_direction
degrees, relative to the center of the nao torso.
uint16_t ball_distance
CM distance to the ball.
bool ball_visible
has the ball been seen enough by vision to be considered actually 'visible'.
int8_t goal_direction
degrees, relative to the center of the nao torso.
uint16_t goal_distance
CM distance to the ball.
bool goal_visible
has the ball been seen enough by vision to be considered actually 'visible'.
enum GoalSightingType goal_sightingType
The type of the goal sighting.
Detailed Description
Provides a C++ wrapper around wb_machine_filtered_vision.
Definition at line 83 of file MachineFilteredVision.hpp.
Constructor & Destructor Documentation
MachineFilteredVision() [1/4]
guWhiteboard::MachineFilteredVision::MachineFilteredVision (int8_t t_ball_direction = 0, uint16_t t_ball_distance = 0, bool t_ball_visible = 0, int8_t t_goal_direction = 0, uint16_t t_goal_distance = 0, bool t_goal_visible = 0, enum GoalSightingType t_goal_sightingType = NoSightingType) inline
Create a new MachineFilteredVision.
Definition at line 105 of file MachineFilteredVision.hpp.
Referenced by operator==().
MachineFilteredVision() [2/4]
guWhiteboard::MachineFilteredVision::MachineFilteredVision (const MachineFilteredVision & t_other) inline
Copy Constructor.
Definition at line 112 of file MachineFilteredVision.hpp.
References ball_direction(), ball_distance(), ball_visible(), goal_direction(), goal_distance(), goal_sightingType(), and goal_visible().
MachineFilteredVision() [3/4]
guWhiteboard::MachineFilteredVision::MachineFilteredVision (const struct wb_machine_filtered_vision & t_other) inline
Copy Constructor.
Definition at line 119 of file MachineFilteredVision.hpp.
References wb_machine_filtered_vision::ball_direction, wb_machine_filtered_vision::ball_distance, wb_machine_filtered_vision::ball_visible, wb_machine_filtered_vision::goal_direction, wb_machine_filtered_vision::goal_distance, wb_machine_filtered_vision::goal_sightingType, and wb_machine_filtered_vision::goal_visible.
MachineFilteredVision() [4/4]
guWhiteboard::MachineFilteredVision::MachineFilteredVision (const std::string & t_str) inline
String Constructor.
Definition at line 274 of file MachineFilteredVision.hpp.
References from_string().
Member Function Documentation
ball_direction() [1/2]
int8_t & guWhiteboard::MachineFilteredVision::ball_direction () inline
Definition at line 165 of file MachineFilteredVision.hpp.
References wb_machine_filtered_vision::ball_direction.
Referenced by MachineFilteredVision(), description(), operator=(), operator==(), and to_string().
ball_direction() [2/2]
const int8_t & guWhiteboard::MachineFilteredVision::ball_direction () const inline
Definition at line 170 of file MachineFilteredVision.hpp.
References wb_machine_filtered_vision::ball_direction.
ball_distance() [1/2]
uint16_t & guWhiteboard::MachineFilteredVision::ball_distance () inline
Definition at line 180 of file MachineFilteredVision.hpp.
References wb_machine_filtered_vision::ball_distance.
Referenced by MachineFilteredVision(), description(), operator=(), operator==(), and to_string().
ball_distance() [2/2]
const uint16_t & guWhiteboard::MachineFilteredVision::ball_distance () const inline
Definition at line 185 of file MachineFilteredVision.hpp.
References wb_machine_filtered_vision::ball_distance.
ball_visible() [1/2]
bool & guWhiteboard::MachineFilteredVision::ball_visible () inline
Definition at line 195 of file MachineFilteredVision.hpp.
References wb_machine_filtered_vision::ball_visible.
Referenced by MachineFilteredVision(), description(), operator=(), operator==(), and to_string().
ball_visible() [2/2]
const bool & guWhiteboard::MachineFilteredVision::ball_visible () const inline
Definition at line 200 of file MachineFilteredVision.hpp.
References wb_machine_filtered_vision::ball_visible.
description()
std::string guWhiteboard::MachineFilteredVision::description () inline
USE_WB_MACHINE_FILTERED_VISION_C_CONVERSION
Definition at line 279 of file MachineFilteredVision.hpp.
References ball_direction(), ball_distance(), ball_visible(), goal_direction(), goal_distance(), goal_sightingType(), goal_visible(), LeftPostSightingType, MACHINE_FILTERED_VISION_DESC_BUFFER_SIZE, NoSightingType, RightPostSightingType, and wb_machine_filtered_vision_description().
from_string()
void guWhiteboard::MachineFilteredVision::from_string (const std::string & t_str) inline
USE_WB_MACHINE_FILTERED_VISION_C_CONVERSION
Definition at line 375 of file MachineFilteredVision.hpp.
References LeftPostSightingType, MACHINE_FILTERED_VISION_DESC_BUFFER_SIZE, NoSightingType, RightPostSightingType, set_ball_direction(), set_ball_distance(), set_ball_visible(), set_goal_direction(), set_goal_distance(), set_goal_sightingType(), and set_goal_visible().
Referenced by MachineFilteredVision().
goal_direction() [1/2]
int8_t & guWhiteboard::MachineFilteredVision::goal_direction () inline
Definition at line 210 of file MachineFilteredVision.hpp.
References wb_machine_filtered_vision::goal_direction.
Referenced by MachineFilteredVision(), description(), operator=(), operator==(), and to_string().
goal_direction() [2/2]
const int8_t & guWhiteboard::MachineFilteredVision::goal_direction () const inline
Definition at line 215 of file MachineFilteredVision.hpp.
References wb_machine_filtered_vision::goal_direction.
goal_distance() [1/2]
uint16_t & guWhiteboard::MachineFilteredVision::goal_distance () inline
Definition at line 225 of file MachineFilteredVision.hpp.
References wb_machine_filtered_vision::goal_distance.
Referenced by MachineFilteredVision(), description(), operator=(), operator==(), and to_string().
goal_distance() [2/2]
const uint16_t & guWhiteboard::MachineFilteredVision::goal_distance () const inline
Definition at line 230 of file MachineFilteredVision.hpp.
References wb_machine_filtered_vision::goal_distance.
goal_sightingType() [1/2]
enum GoalSightingType & guWhiteboard::MachineFilteredVision::goal_sightingType () inline
Definition at line 255 of file MachineFilteredVision.hpp.
References wb_machine_filtered_vision::goal_sightingType.
Referenced by MachineFilteredVision(), description(), operator=(), operator==(), and to_string().
goal_sightingType() [2/2]
enum GoalSightingType & guWhiteboard::MachineFilteredVision::goal_sightingType () const inline
Definition at line 260 of file MachineFilteredVision.hpp.
References wb_machine_filtered_vision::goal_sightingType.
goal_visible() [1/2]
bool & guWhiteboard::MachineFilteredVision::goal_visible () inline
Definition at line 240 of file MachineFilteredVision.hpp.
References wb_machine_filtered_vision::goal_visible.
Referenced by MachineFilteredVision(), description(), operator=(), operator==(), and to_string().
goal_visible() [2/2]
const bool & guWhiteboard::MachineFilteredVision::goal_visible () const inline
Definition at line 245 of file MachineFilteredVision.hpp.
References wb_machine_filtered_vision::goal_visible.
operator!=() [1/2]
bool guWhiteboard::MachineFilteredVision::operator!= (const MachineFilteredVision & t_other) const inline
Definition at line 150 of file MachineFilteredVision.hpp.
operator!=() [2/2]
bool guWhiteboard::MachineFilteredVision::operator!= (const wb_machine_filtered_vision & t_other) const inline
Definition at line 160 of file MachineFilteredVision.hpp.
operator=() [1/2]
MachineFilteredVision & guWhiteboard::MachineFilteredVision::operator= (const MachineFilteredVision & t_other) inline
Copy Assignment Operator.
Definition at line 126 of file MachineFilteredVision.hpp.
References ball_direction(), ball_distance(), ball_visible(), goal_direction(), goal_distance(), goal_sightingType(), and goal_visible().
operator=() [2/2]
MachineFilteredVision & guWhiteboard::MachineFilteredVision::operator= (const struct wb_machine_filtered_vision & t_other) inline
Copy Assignment Operator.
Definition at line 134 of file MachineFilteredVision.hpp.
References wb_machine_filtered_vision::ball_direction, wb_machine_filtered_vision::ball_distance, wb_machine_filtered_vision::ball_visible, wb_machine_filtered_vision::goal_direction, wb_machine_filtered_vision::goal_distance, wb_machine_filtered_vision::goal_sightingType, and wb_machine_filtered_vision::goal_visible.
operator==() [1/2]
bool guWhiteboard::MachineFilteredVision::operator== (const MachineFilteredVision & t_other) const inline
Definition at line 139 of file MachineFilteredVision.hpp.
References ball_direction(), ball_distance(), ball_visible(), goal_direction(), goal_distance(), goal_sightingType(), and goal_visible().
operator==() [2/2]
bool guWhiteboard::MachineFilteredVision::operator== (const wb_machine_filtered_vision & t_other) const inline
Definition at line 155 of file MachineFilteredVision.hpp.
References MachineFilteredVision().
set_ball_direction()
void guWhiteboard::MachineFilteredVision::set_ball_direction (const int8_t & t_newValue) inline
Definition at line 175 of file MachineFilteredVision.hpp.
References wb_machine_filtered_vision::ball_direction.
Referenced by from_string().
set_ball_distance()
void guWhiteboard::MachineFilteredVision::set_ball_distance (const uint16_t & t_newValue) inline
Definition at line 190 of file MachineFilteredVision.hpp.
References wb_machine_filtered_vision::ball_distance.
Referenced by from_string().
set_ball_visible()
void guWhiteboard::MachineFilteredVision::set_ball_visible (const bool & t_newValue) inline
Definition at line 205 of file MachineFilteredVision.hpp.
References wb_machine_filtered_vision::ball_visible.
Referenced by from_string().
set_goal_direction()
void guWhiteboard::MachineFilteredVision::set_goal_direction (const int8_t & t_newValue) inline
Definition at line 220 of file MachineFilteredVision.hpp.
References wb_machine_filtered_vision::goal_direction.
Referenced by from_string().
set_goal_distance()
void guWhiteboard::MachineFilteredVision::set_goal_distance (const uint16_t & t_newValue) inline
Definition at line 235 of file MachineFilteredVision.hpp.
References wb_machine_filtered_vision::goal_distance.
Referenced by from_string().
set_goal_sightingType()
void guWhiteboard::MachineFilteredVision::set_goal_sightingType (const enum GoalSightingType & t_newValue) inline
Definition at line 265 of file MachineFilteredVision.hpp.
References wb_machine_filtered_vision::goal_sightingType.
Referenced by from_string().
set_goal_visible()
void guWhiteboard::MachineFilteredVision::set_goal_visible (const bool & t_newValue) inline
Definition at line 250 of file MachineFilteredVision.hpp.
References wb_machine_filtered_vision::goal_visible.
Referenced by from_string().
to_string()
std::string guWhiteboard::MachineFilteredVision::to_string () inline
USE_WB_MACHINE_FILTERED_VISION_C_CONVERSION
Definition at line 325 of file MachineFilteredVision.hpp.
References ball_direction(), ball_distance(), ball_visible(), goal_direction(), goal_distance(), goal_sightingType(), goal_visible(), LeftPostSightingType, MACHINE_FILTERED_VISION_TO_STRING_BUFFER_SIZE, NoSightingType, RightPostSightingType, and wb_machine_filtered_vision_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/MachineFilteredVision.hpp