gusimplewhiteboard: guWhiteboard::VisionDetectionGoals Class Reference
guWhiteboard::VisionDetectionGoals Class Reference
Provides a C++ wrapper around wb_vision_detection_goals.
#include <VisionDetectionGoals.hpp>
Public Member Functions
VisionDetectionGoals (uint64_t t_frameNumber=0, const struct wb_vision_detection_goal t_goals[2]=NULLPTR, uint16_t t_res_width=0, uint16_t t_res_height=0)
Create a new VisionDetectionGoals.
VisionDetectionGoals (const VisionDetectionGoals &t_other)
Copy Constructor.
VisionDetectionGoals (const struct wb_vision_detection_goals &t_other)
Copy Constructor.
VisionDetectionGoals & operator= (const VisionDetectionGoals &t_other)
Copy Assignment Operator.
VisionDetectionGoals & operator= (const struct wb_vision_detection_goals &t_other)
Copy Assignment Operator.
bool operator== (const VisionDetectionGoals &t_other) const
bool operator!= (const VisionDetectionGoals &t_other) const
bool operator== (const wb_vision_detection_goals &t_other) const
bool operator!= (const wb_vision_detection_goals &t_other) const
uint64_t & frameNumber ()
const uint64_t & frameNumber () const
void set_frameNumber (const uint64_t &t_newValue)
const VisionDetectionGoal * goals () const
size_t goals_size () const
VisionDetectionGoal & goals (int t_i)
const VisionDetectionGoal & goals (int t_i) const
void set_goals (const VisionDetectionGoal *t_newValue)
void set_goals (const VisionDetectionGoal &t_newValue, int t_i)
uint16_t & res_width ()
const uint16_t & res_width () const
void set_res_width (const uint16_t &t_newValue)
uint16_t & res_height ()
const uint16_t & res_height () const
void set_res_height (const uint16_t &t_newValue)
VisionDetectionGoals (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_vision_detection_goals
uint64_t frameNumber
visionFrameNumber
struct wb_vision_detection_goal goals [2]
goal objects
uint16_t res_width
The resolution width.
uint16_t res_height
The resolution height.
Detailed Description
Provides a C++ wrapper around wb_vision_detection_goals.
Definition at line 85 of file VisionDetectionGoals.hpp.
Constructor & Destructor Documentation
VisionDetectionGoals() [1/4]
guWhiteboard::VisionDetectionGoals::VisionDetectionGoals (uint64_t t_frameNumber = 0, const struct wb_vision_detection_goal t_goals[2] = NULLPTR, uint16_t t_res_width = 0, uint16_t t_res_height = 0) inline
Create a new VisionDetectionGoals.
Definition at line 109 of file VisionDetectionGoals.hpp.
Referenced by operator==().
VisionDetectionGoals() [2/4]
guWhiteboard::VisionDetectionGoals::VisionDetectionGoals (const VisionDetectionGoals & t_other) inline
Copy Constructor.
Definition at line 116 of file VisionDetectionGoals.hpp.
References frameNumber(), goals(), res_height(), and res_width().
VisionDetectionGoals() [3/4]
guWhiteboard::VisionDetectionGoals::VisionDetectionGoals (const struct wb_vision_detection_goals & t_other) inline
Copy Constructor.
Definition at line 123 of file VisionDetectionGoals.hpp.
References wb_vision_detection_goals::frameNumber, wb_vision_detection_goals::goals, wb_vision_detection_goals::res_height, and wb_vision_detection_goals::res_width.
VisionDetectionGoals() [4/4]
guWhiteboard::VisionDetectionGoals::VisionDetectionGoals (const std::string & t_str) inline
String Constructor.
Definition at line 252 of file VisionDetectionGoals.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::VisionDetectionGoals::description () inline
USE_WB_VISION_DETECTION_GOALS_C_CONVERSION
Definition at line 257 of file VisionDetectionGoals.hpp.
References description(), frameNumber(), goals(), res_height(), res_width(), VISION_DETECTION_GOALS_DESC_BUFFER_SIZE, VISION_DETECTION_GOALS_GOALS_ARRAY_SIZE, and wb_vision_detection_goals_description().
Referenced by description().
frameNumber() [1/2]
uint64_t & guWhiteboard::VisionDetectionGoals::frameNumber () inline
Definition at line 173 of file VisionDetectionGoals.hpp.
References wb_vision_detection_goals::frameNumber.
Referenced by VisionDetectionGoals(), description(), operator=(), operator==(), and to_string().
frameNumber() [2/2]
const uint64_t & guWhiteboard::VisionDetectionGoals::frameNumber () const inline
Definition at line 178 of file VisionDetectionGoals.hpp.
References wb_vision_detection_goals::frameNumber.
from_string()
void guWhiteboard::VisionDetectionGoals::from_string (const std::string & t_str) inline
USE_WB_VISION_DETECTION_GOALS_C_CONVERSION
Definition at line 311 of file VisionDetectionGoals.hpp.
References guWhiteboard::VisionDetectionGoal::from_string(), set_frameNumber(), set_goals(), set_res_height(), set_res_width(), VISION_DETECTION_GOALS_DESC_BUFFER_SIZE, and VISION_DETECTION_GOALS_GOALS_ARRAY_SIZE.
Referenced by VisionDetectionGoals().
goals() [1/3]
const VisionDetectionGoal * guWhiteboard::VisionDetectionGoals::goals () const inline
Definition at line 188 of file VisionDetectionGoals.hpp.
References wb_vision_detection_goals::goals.
Referenced by VisionDetectionGoals(), description(), operator=(), operator==(), and to_string().
goals() [2/3]
VisionDetectionGoal & guWhiteboard::VisionDetectionGoals::goals (int t_i) inline
Definition at line 198 of file VisionDetectionGoals.hpp.
References wb_vision_detection_goals::goals.
goals() [3/3]
const VisionDetectionGoal & guWhiteboard::VisionDetectionGoals::goals (int t_i) const inline
Definition at line 203 of file VisionDetectionGoals.hpp.
References wb_vision_detection_goals::goals.
goals_size()
size_t guWhiteboard::VisionDetectionGoals::goals_size () const inline
Definition at line 193 of file VisionDetectionGoals.hpp.
References VISION_DETECTION_GOALS_GOALS_ARRAY_SIZE.
operator!=() [1/2]
bool guWhiteboard::VisionDetectionGoals::operator!= (const VisionDetectionGoals & t_other) const inline
Definition at line 158 of file VisionDetectionGoals.hpp.
operator!=() [2/2]
bool guWhiteboard::VisionDetectionGoals::operator!= (const wb_vision_detection_goals & t_other) const inline
Definition at line 168 of file VisionDetectionGoals.hpp.
operator=() [1/2]
VisionDetectionGoals & guWhiteboard::VisionDetectionGoals::operator= (const struct wb_vision_detection_goals & t_other) inline
Copy Assignment Operator.
Definition at line 138 of file VisionDetectionGoals.hpp.
References wb_vision_detection_goals::frameNumber, wb_vision_detection_goals::goals, wb_vision_detection_goals::res_height, and wb_vision_detection_goals::res_width.
operator=() [2/2]
VisionDetectionGoals & guWhiteboard::VisionDetectionGoals::operator= (const VisionDetectionGoals & t_other) inline
Copy Assignment Operator.
Definition at line 130 of file VisionDetectionGoals.hpp.
References frameNumber(), goals(), res_height(), and res_width().
operator==() [1/2]
bool guWhiteboard::VisionDetectionGoals::operator== (const VisionDetectionGoals & t_other) const inline
Definition at line 143 of file VisionDetectionGoals.hpp.
References frameNumber(), goals(), res_height(), and res_width().
operator==() [2/2]
bool guWhiteboard::VisionDetectionGoals::operator== (const wb_vision_detection_goals & t_other) const inline
Definition at line 163 of file VisionDetectionGoals.hpp.
References VisionDetectionGoals().
res_height() [1/2]
uint16_t & guWhiteboard::VisionDetectionGoals::res_height () inline
Definition at line 233 of file VisionDetectionGoals.hpp.
References wb_vision_detection_goals::res_height.
Referenced by VisionDetectionGoals(), description(), operator=(), operator==(), and to_string().
res_height() [2/2]
const uint16_t & guWhiteboard::VisionDetectionGoals::res_height () const inline
Definition at line 238 of file VisionDetectionGoals.hpp.
References wb_vision_detection_goals::res_height.
res_width() [1/2]
uint16_t & guWhiteboard::VisionDetectionGoals::res_width () inline
Definition at line 218 of file VisionDetectionGoals.hpp.
References wb_vision_detection_goals::res_width.
Referenced by VisionDetectionGoals(), description(), operator=(), operator==(), and to_string().
res_width() [2/2]
const uint16_t & guWhiteboard::VisionDetectionGoals::res_width () const inline
Definition at line 223 of file VisionDetectionGoals.hpp.
References wb_vision_detection_goals::res_width.
set_frameNumber()
void guWhiteboard::VisionDetectionGoals::set_frameNumber (const uint64_t & t_newValue) inline
Definition at line 183 of file VisionDetectionGoals.hpp.
References wb_vision_detection_goals::frameNumber.
Referenced by from_string().
set_goals() [1/2]
void guWhiteboard::VisionDetectionGoals::set_goals (const VisionDetectionGoal & t_newValue, int t_i) inline
Definition at line 213 of file VisionDetectionGoals.hpp.
References wb_vision_detection_goals::goals.
set_goals() [2/2]
void guWhiteboard::VisionDetectionGoals::set_goals (const VisionDetectionGoal * t_newValue) inline
Definition at line 208 of file VisionDetectionGoals.hpp.
References wb_vision_detection_goals::goals, and VISION_DETECTION_GOALS_GOALS_ARRAY_SIZE.
Referenced by from_string().
set_res_height()
void guWhiteboard::VisionDetectionGoals::set_res_height (const uint16_t & t_newValue) inline
Definition at line 243 of file VisionDetectionGoals.hpp.
References wb_vision_detection_goals::res_height.
Referenced by from_string().
set_res_width()
void guWhiteboard::VisionDetectionGoals::set_res_width (const uint16_t & t_newValue) inline
Definition at line 228 of file VisionDetectionGoals.hpp.
References wb_vision_detection_goals::res_width.
Referenced by from_string().
to_string()
std::string guWhiteboard::VisionDetectionGoals::to_string () inline
USE_WB_VISION_DETECTION_GOALS_C_CONVERSION
Definition at line 282 of file VisionDetectionGoals.hpp.
References frameNumber(), goals(), res_height(), res_width(), to_string(), VISION_DETECTION_GOALS_GOALS_ARRAY_SIZE, VISION_DETECTION_GOALS_TO_STRING_BUFFER_SIZE, and wb_vision_detection_goals_to_string().
Referenced by to_string().
The documentation for this class was generated from the following file:
typeClassDefs/VisionDetectionGoals.hpp