gusimplewhiteboard: guWhiteboard::PixelCoordinate Class Reference
guWhiteboard::PixelCoordinate Class Reference
Provides a C++ wrapper around wb_pixel_coordinate.
#include <PixelCoordinate.hpp>
Public Member Functions
PixelCoordinate (int16_t t_x=0, int16_t t_y=0)
Create a new PixelCoordinate.
PixelCoordinate (const PixelCoordinate &t_other)
Copy Constructor.
PixelCoordinate (const struct wb_pixel_coordinate &t_other)
Copy Constructor.
PixelCoordinate & operator= (const PixelCoordinate &t_other)
Copy Assignment Operator.
PixelCoordinate & operator= (const struct wb_pixel_coordinate &t_other)
Copy Assignment Operator.
bool operator== (const PixelCoordinate &t_other) const
bool operator!= (const PixelCoordinate &t_other) const
bool operator== (const wb_pixel_coordinate &t_other) const
bool operator!= (const wb_pixel_coordinate &t_other) const
int16_t & x ()
const int16_t & x () const
void set_x (const int16_t &t_newValue)
int16_t & y ()
const int16_t & y () const
void set_y (const int16_t &t_newValue)
PixelCoordinate (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
PixelCoordinate (const GU::PixelCoordinate &other)
WHITEBOARD_POSTER_STRING_CONVERSION.
PixelCoordinate (const ::gu_pixel_coordinate &other)
GU::PixelCoordinate pixelCoordinate (const uint16_t resWidth, const uint16_t resHeight)
Additional Inherited Members
Public Attributes inherited from wb_pixel_coordinate
int16_t x
The x coordinate.
int16_t y
The y coordinate.
Detailed Description
Provides a C++ wrapper around wb_pixel_coordinate.
Definition at line 86 of file PixelCoordinate.hpp.
Constructor & Destructor Documentation
PixelCoordinate() [1/6]
guWhiteboard::PixelCoordinate::PixelCoordinate (int16_t t_x = 0, int16_t t_y = 0) inline
Create a new PixelCoordinate.
Definition at line 103 of file PixelCoordinate.hpp.
Referenced by operator==().
PixelCoordinate() [2/6]
guWhiteboard::PixelCoordinate::PixelCoordinate (const PixelCoordinate & t_other) inline
Copy Constructor.
Definition at line 110 of file PixelCoordinate.hpp.
References x(), and y().
PixelCoordinate() [3/6]
guWhiteboard::PixelCoordinate::PixelCoordinate (const struct wb_pixel_coordinate & t_other) inline
Copy Constructor.
Definition at line 117 of file PixelCoordinate.hpp.
References wb_pixel_coordinate::x, and wb_pixel_coordinate::y.
PixelCoordinate() [4/6]
guWhiteboard::PixelCoordinate::PixelCoordinate (const std::string & t_str) inline
String Constructor.
Definition at line 192 of file PixelCoordinate.hpp.
References from_string().
PixelCoordinate() [5/6]
guWhiteboard::PixelCoordinate::PixelCoordinate (const GU::PixelCoordinate & other) inline
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 330 of file PixelCoordinate.hpp.
PixelCoordinate() [6/6]
guWhiteboard::PixelCoordinate::PixelCoordinate (const ::gu_pixel_coordinate & other) inline
Definition at line 334 of file PixelCoordinate.hpp.
Member Function Documentation
description()
std::string guWhiteboard::PixelCoordinate::description () inline
USE_WB_PIXEL_COORDINATE_C_CONVERSION
Definition at line 197 of file PixelCoordinate.hpp.
References PIXEL_COORDINATE_DESC_BUFFER_SIZE, wb_pixel_coordinate_description(), x(), and y().
Referenced by guWhiteboard::PixelCoordinateLine::description(), guWhiteboard::VisionDetectionBall::description(), guWhiteboard::VisionDetectionGoalPost::description(), guWhiteboard::VisionDetectionHorizon::description(), and guWhiteboard::VisionFieldFeature::description().
from_string()
void guWhiteboard::PixelCoordinate::from_string (const std::string & t_str) inline
USE_WB_PIXEL_COORDINATE_C_CONVERSION
Definition at line 231 of file PixelCoordinate.hpp.
References PIXEL_COORDINATE_DESC_BUFFER_SIZE, set_x(), and set_y().
Referenced by PixelCoordinate(), guWhiteboard::PixelCoordinateLine::from_string(), guWhiteboard::VisionDetectionBall::from_string(), guWhiteboard::VisionDetectionGoalPost::from_string(), guWhiteboard::VisionDetectionHorizon::from_string(), and guWhiteboard::VisionFieldFeature::from_string().
operator!=() [1/2]
bool guWhiteboard::PixelCoordinate::operator!= (const PixelCoordinate & t_other) const inline
Definition at line 143 of file PixelCoordinate.hpp.
operator!=() [2/2]
bool guWhiteboard::PixelCoordinate::operator!= (const wb_pixel_coordinate & t_other) const inline
Definition at line 153 of file PixelCoordinate.hpp.
operator=() [1/2]
PixelCoordinate & guWhiteboard::PixelCoordinate::operator= (const PixelCoordinate & t_other) inline
Copy Assignment Operator.
Definition at line 124 of file PixelCoordinate.hpp.
References x(), and y().
operator=() [2/2]
PixelCoordinate & guWhiteboard::PixelCoordinate::operator= (const struct wb_pixel_coordinate & t_other) inline
Copy Assignment Operator.
Definition at line 132 of file PixelCoordinate.hpp.
References wb_pixel_coordinate::x, and wb_pixel_coordinate::y.
operator==() [1/2]
bool guWhiteboard::PixelCoordinate::operator== (const PixelCoordinate & t_other) const inline
Definition at line 137 of file PixelCoordinate.hpp.
References x(), and y().
operator==() [2/2]
bool guWhiteboard::PixelCoordinate::operator== (const wb_pixel_coordinate & t_other) const inline
Definition at line 148 of file PixelCoordinate.hpp.
References PixelCoordinate().
pixelCoordinate()
GU::PixelCoordinate guWhiteboard::PixelCoordinate::pixelCoordinate (const uint16_t resWidth, const uint16_t resHeight) inline
Definition at line 338 of file PixelCoordinate.hpp.
References wb_px_coord_to_px_coord().
Referenced by guWhiteboard::VisionDetectionGoalPost::bottomLeftCoordinatePixelCoordinate(), guWhiteboard::VisionDetectionGoalPost::bottomRightCoordinatePixelCoordinate(), guWhiteboard::VisionDetectionHorizon::centerCoordinatePixelCoordinate(), guWhiteboard::VisionDetectionBall::coordinatePixelCoordinate(), guWhiteboard::VisionFieldFeature::coordinatePixelCoordinate(), guWhiteboard::PixelCoordinateLine::endPixelCoordinate(), guWhiteboard::VisionDetectionHorizon::leftCoordinatePixelCoordinate(), guWhiteboard::VisionDetectionHorizon::rightCoordinatePixelCoordinate(), guWhiteboard::PixelCoordinateLine::startPixelCoordinate(), guWhiteboard::VisionDetectionGoalPost::topLeftCoordinatePixelCoordinate(), and guWhiteboard::VisionDetectionGoalPost::topRightCoordinatePixelCoordinate().
set_x()
void guWhiteboard::PixelCoordinate::set_x (const int16_t & t_newValue) inline
Definition at line 168 of file PixelCoordinate.hpp.
References wb_pixel_coordinate::x.
Referenced by from_string().
set_y()
void guWhiteboard::PixelCoordinate::set_y (const int16_t & t_newValue) inline
Definition at line 183 of file PixelCoordinate.hpp.
References wb_pixel_coordinate::y.
Referenced by from_string().
to_string()
std::string guWhiteboard::PixelCoordinate::to_string () inline
USE_WB_PIXEL_COORDINATE_C_CONVERSION
Definition at line 212 of file PixelCoordinate.hpp.
References PIXEL_COORDINATE_TO_STRING_BUFFER_SIZE, wb_pixel_coordinate_to_string(), x(), and y().
Referenced by guWhiteboard::PixelCoordinateLine::to_string(), guWhiteboard::VisionDetectionBall::to_string(), guWhiteboard::VisionDetectionGoalPost::to_string(), guWhiteboard::VisionDetectionHorizon::to_string(), and guWhiteboard::VisionFieldFeature::to_string().
x() [1/2]
int16_t & guWhiteboard::PixelCoordinate::x () inline
Definition at line 158 of file PixelCoordinate.hpp.
References wb_pixel_coordinate::x.
Referenced by PixelCoordinate(), description(), operator=(), operator==(), and to_string().
x() [2/2]
const int16_t & guWhiteboard::PixelCoordinate::x () const inline
Definition at line 163 of file PixelCoordinate.hpp.
References wb_pixel_coordinate::x.
y() [1/2]
int16_t & guWhiteboard::PixelCoordinate::y () inline
Definition at line 173 of file PixelCoordinate.hpp.
References wb_pixel_coordinate::y.
Referenced by PixelCoordinate(), description(), operator=(), operator==(), and to_string().
y() [2/2]
const int16_t & guWhiteboard::PixelCoordinate::y () const inline
Definition at line 178 of file PixelCoordinate.hpp.
References wb_pixel_coordinate::y.
The documentation for this class was generated from the following file:
typeClassDefs/PixelCoordinate.hpp