gusimplewhiteboard: guWhiteboard::SENSORSLegJointTemps Class Reference
guWhiteboard::SENSORSLegJointTemps Class Reference
Provides a C++ wrapper around wb_sensors_legjointtemps.
#include <SENSORSLegJointTemps.hpp>
Public Member Functions
SENSORSLegJointTemps (float t_LKneePitch=0.0f, float t_LAnklePitch=0.0f, float t_LAnkleRoll=0.0f, float t_RKneePitch=0.0f, float t_RAnklePitch=0.0f, float t_RAnkleRoll=0.0f)
Create a new SENSORSLegJointTemps.
SENSORSLegJointTemps (const SENSORSLegJointTemps &t_other)
Copy Constructor.
SENSORSLegJointTemps (const struct wb_sensors_legjointtemps &t_other)
Copy Constructor.
SENSORSLegJointTemps & operator= (const SENSORSLegJointTemps &t_other)
Copy Assignment Operator.
SENSORSLegJointTemps & operator= (const struct wb_sensors_legjointtemps &t_other)
Copy Assignment Operator.
bool operator== (const SENSORSLegJointTemps &t_other) const
bool operator!= (const SENSORSLegJointTemps &t_other) const
bool operator== (const wb_sensors_legjointtemps &t_other) const
bool operator!= (const wb_sensors_legjointtemps &t_other) const
float & LKneePitch ()
const float & LKneePitch () const
void set_LKneePitch (const float &t_newValue)
float & LAnklePitch ()
const float & LAnklePitch () const
void set_LAnklePitch (const float &t_newValue)
float & LAnkleRoll ()
const float & LAnkleRoll () const
void set_LAnkleRoll (const float &t_newValue)
float & RKneePitch ()
const float & RKneePitch () const
void set_RKneePitch (const float &t_newValue)
float & RAnklePitch ()
const float & RAnklePitch () const
void set_RAnklePitch (const float &t_newValue)
float & RAnkleRoll ()
const float & RAnkleRoll () const
void set_RAnkleRoll (const float &t_newValue)
SENSORSLegJointTemps (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_sensors_legjointtemps
float LKneePitch
left knee pitch temp
float LAnklePitch
left ankle pitch temp
float LAnkleRoll
left ankle roll temp
float RKneePitch
right knee pitch temp
float RAnklePitch
right ankle pitch temp
float RAnkleRoll
right ankle roll temp
Detailed Description
Provides a C++ wrapper around wb_sensors_legjointtemps.
Definition at line 84 of file SENSORSLegJointTemps.hpp.
Constructor & Destructor Documentation
SENSORSLegJointTemps() [1/4]
guWhiteboard::SENSORSLegJointTemps::SENSORSLegJointTemps (float t_LKneePitch = 0.0f, float t_LAnklePitch = 0.0f, float t_LAnkleRoll = 0.0f, float t_RKneePitch = 0.0f, float t_RAnklePitch = 0.0f, float t_RAnkleRoll = 0.0f) inline
Create a new SENSORSLegJointTemps.
Definition at line 105 of file SENSORSLegJointTemps.hpp.
Referenced by operator==().
SENSORSLegJointTemps() [2/4]
guWhiteboard::SENSORSLegJointTemps::SENSORSLegJointTemps (const SENSORSLegJointTemps & t_other) inline
Copy Constructor.
Definition at line 112 of file SENSORSLegJointTemps.hpp.
References LAnklePitch(), LAnkleRoll(), LKneePitch(), RAnklePitch(), RAnkleRoll(), and RKneePitch().
SENSORSLegJointTemps() [3/4]
guWhiteboard::SENSORSLegJointTemps::SENSORSLegJointTemps (const struct wb_sensors_legjointtemps & t_other) inline
Copy Constructor.
Definition at line 119 of file SENSORSLegJointTemps.hpp.
References wb_sensors_legjointtemps::LAnklePitch, wb_sensors_legjointtemps::LAnkleRoll, wb_sensors_legjointtemps::LKneePitch, wb_sensors_legjointtemps::RAnklePitch, wb_sensors_legjointtemps::RAnkleRoll, and wb_sensors_legjointtemps::RKneePitch.
SENSORSLegJointTemps() [4/4]
guWhiteboard::SENSORSLegJointTemps::SENSORSLegJointTemps (const std::string & t_str) inline
String Constructor.
Definition at line 258 of file SENSORSLegJointTemps.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::SENSORSLegJointTemps::description () inline
USE_WB_SENSORS_LEGJOINTTEMPS_C_CONVERSION
Definition at line 263 of file SENSORSLegJointTemps.hpp.
References LAnklePitch(), LAnkleRoll(), LKneePitch(), RAnklePitch(), RAnkleRoll(), RKneePitch(), SENSORS_LEGJOINTTEMPS_DESC_BUFFER_SIZE, and wb_sensors_legjointtemps_description().
from_string()
void guWhiteboard::SENSORSLegJointTemps::from_string (const std::string & t_str) inline
USE_WB_SENSORS_LEGJOINTTEMPS_C_CONVERSION
Definition at line 313 of file SENSORSLegJointTemps.hpp.
References SENSORS_LEGJOINTTEMPS_DESC_BUFFER_SIZE, set_LAnklePitch(), set_LAnkleRoll(), set_LKneePitch(), set_RAnklePitch(), set_RAnkleRoll(), and set_RKneePitch().
Referenced by SENSORSLegJointTemps().
LAnklePitch() [1/2]
float & guWhiteboard::SENSORSLegJointTemps::LAnklePitch () inline
Definition at line 179 of file SENSORSLegJointTemps.hpp.
References wb_sensors_legjointtemps::LAnklePitch.
Referenced by SENSORSLegJointTemps(), description(), operator=(), operator==(), and to_string().
LAnklePitch() [2/2]
const float & guWhiteboard::SENSORSLegJointTemps::LAnklePitch () const inline
Definition at line 184 of file SENSORSLegJointTemps.hpp.
References wb_sensors_legjointtemps::LAnklePitch.
LAnkleRoll() [1/2]
float & guWhiteboard::SENSORSLegJointTemps::LAnkleRoll () inline
Definition at line 194 of file SENSORSLegJointTemps.hpp.
References wb_sensors_legjointtemps::LAnkleRoll.
Referenced by SENSORSLegJointTemps(), description(), operator=(), operator==(), and to_string().
LAnkleRoll() [2/2]
const float & guWhiteboard::SENSORSLegJointTemps::LAnkleRoll () const inline
Definition at line 199 of file SENSORSLegJointTemps.hpp.
References wb_sensors_legjointtemps::LAnkleRoll.
LKneePitch() [1/2]
float & guWhiteboard::SENSORSLegJointTemps::LKneePitch () inline
Definition at line 164 of file SENSORSLegJointTemps.hpp.
References wb_sensors_legjointtemps::LKneePitch.
Referenced by SENSORSLegJointTemps(), description(), operator=(), operator==(), and to_string().
LKneePitch() [2/2]
const float & guWhiteboard::SENSORSLegJointTemps::LKneePitch () const inline
Definition at line 169 of file SENSORSLegJointTemps.hpp.
References wb_sensors_legjointtemps::LKneePitch.
operator!=() [1/2]
bool guWhiteboard::SENSORSLegJointTemps::operator!= (const SENSORSLegJointTemps & t_other) const inline
Definition at line 149 of file SENSORSLegJointTemps.hpp.
operator!=() [2/2]
bool guWhiteboard::SENSORSLegJointTemps::operator!= (const wb_sensors_legjointtemps & t_other) const inline
Definition at line 159 of file SENSORSLegJointTemps.hpp.
operator=() [1/2]
SENSORSLegJointTemps & guWhiteboard::SENSORSLegJointTemps::operator= (const SENSORSLegJointTemps & t_other) inline
Copy Assignment Operator.
Definition at line 126 of file SENSORSLegJointTemps.hpp.
References LAnklePitch(), LAnkleRoll(), LKneePitch(), RAnklePitch(), RAnkleRoll(), and RKneePitch().
operator=() [2/2]
SENSORSLegJointTemps & guWhiteboard::SENSORSLegJointTemps::operator= (const struct wb_sensors_legjointtemps & t_other) inline
Copy Assignment Operator.
Definition at line 134 of file SENSORSLegJointTemps.hpp.
References wb_sensors_legjointtemps::LAnklePitch, wb_sensors_legjointtemps::LAnkleRoll, wb_sensors_legjointtemps::LKneePitch, wb_sensors_legjointtemps::RAnklePitch, wb_sensors_legjointtemps::RAnkleRoll, and wb_sensors_legjointtemps::RKneePitch.
operator==() [1/2]
bool guWhiteboard::SENSORSLegJointTemps::operator== (const SENSORSLegJointTemps & t_other) const inline
Definition at line 139 of file SENSORSLegJointTemps.hpp.
References LAnklePitch(), LAnkleRoll(), LKneePitch(), RAnklePitch(), RAnkleRoll(), and RKneePitch().
operator==() [2/2]
bool guWhiteboard::SENSORSLegJointTemps::operator== (const wb_sensors_legjointtemps & t_other) const inline
Definition at line 154 of file SENSORSLegJointTemps.hpp.
References SENSORSLegJointTemps().
RAnklePitch() [1/2]
float & guWhiteboard::SENSORSLegJointTemps::RAnklePitch () inline
Definition at line 224 of file SENSORSLegJointTemps.hpp.
References wb_sensors_legjointtemps::RAnklePitch.
Referenced by SENSORSLegJointTemps(), description(), operator=(), operator==(), and to_string().
RAnklePitch() [2/2]
const float & guWhiteboard::SENSORSLegJointTemps::RAnklePitch () const inline
Definition at line 229 of file SENSORSLegJointTemps.hpp.
References wb_sensors_legjointtemps::RAnklePitch.
RAnkleRoll() [1/2]
float & guWhiteboard::SENSORSLegJointTemps::RAnkleRoll () inline
Definition at line 239 of file SENSORSLegJointTemps.hpp.
References wb_sensors_legjointtemps::RAnkleRoll.
Referenced by SENSORSLegJointTemps(), description(), operator=(), operator==(), and to_string().
RAnkleRoll() [2/2]
const float & guWhiteboard::SENSORSLegJointTemps::RAnkleRoll () const inline
Definition at line 244 of file SENSORSLegJointTemps.hpp.
References wb_sensors_legjointtemps::RAnkleRoll.
RKneePitch() [1/2]
float & guWhiteboard::SENSORSLegJointTemps::RKneePitch () inline
Definition at line 209 of file SENSORSLegJointTemps.hpp.
References wb_sensors_legjointtemps::RKneePitch.
Referenced by SENSORSLegJointTemps(), description(), operator=(), operator==(), and to_string().
RKneePitch() [2/2]
const float & guWhiteboard::SENSORSLegJointTemps::RKneePitch () const inline
Definition at line 214 of file SENSORSLegJointTemps.hpp.
References wb_sensors_legjointtemps::RKneePitch.
set_LAnklePitch()
void guWhiteboard::SENSORSLegJointTemps::set_LAnklePitch (const float & t_newValue) inline
Definition at line 189 of file SENSORSLegJointTemps.hpp.
References wb_sensors_legjointtemps::LAnklePitch.
Referenced by from_string().
set_LAnkleRoll()
void guWhiteboard::SENSORSLegJointTemps::set_LAnkleRoll (const float & t_newValue) inline
Definition at line 204 of file SENSORSLegJointTemps.hpp.
References wb_sensors_legjointtemps::LAnkleRoll.
Referenced by from_string().
set_LKneePitch()
void guWhiteboard::SENSORSLegJointTemps::set_LKneePitch (const float & t_newValue) inline
Definition at line 174 of file SENSORSLegJointTemps.hpp.
References wb_sensors_legjointtemps::LKneePitch.
Referenced by from_string().
set_RAnklePitch()
void guWhiteboard::SENSORSLegJointTemps::set_RAnklePitch (const float & t_newValue) inline
Definition at line 234 of file SENSORSLegJointTemps.hpp.
References wb_sensors_legjointtemps::RAnklePitch.
Referenced by from_string().
set_RAnkleRoll()
void guWhiteboard::SENSORSLegJointTemps::set_RAnkleRoll (const float & t_newValue) inline
Definition at line 249 of file SENSORSLegJointTemps.hpp.
References wb_sensors_legjointtemps::RAnkleRoll.
Referenced by from_string().
set_RKneePitch()
void guWhiteboard::SENSORSLegJointTemps::set_RKneePitch (const float & t_newValue) inline
Definition at line 219 of file SENSORSLegJointTemps.hpp.
References wb_sensors_legjointtemps::RKneePitch.
Referenced by from_string().
to_string()
std::string guWhiteboard::SENSORSLegJointTemps::to_string () inline
USE_WB_SENSORS_LEGJOINTTEMPS_C_CONVERSION
Definition at line 286 of file SENSORSLegJointTemps.hpp.
References LAnklePitch(), LAnkleRoll(), LKneePitch(), RAnklePitch(), RAnkleRoll(), RKneePitch(), SENSORS_LEGJOINTTEMPS_TO_STRING_BUFFER_SIZE, and wb_sensors_legjointtemps_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/SENSORSLegJointTemps.hpp