gusimplewhiteboard: guWhiteboard::Overheating Class Reference
guWhiteboard::Overheating Class Reference
Provides a C++ wrapper around wb_overheating.
#include <Overheating.hpp>
Public Member Functions
Overheating (bool t_overheating=false)
Create a new Overheating.
Overheating (const Overheating &t_other)
Copy Constructor.
Overheating (const struct wb_overheating &t_other)
Copy Constructor.
Overheating & operator= (const Overheating &t_other)
Copy Assignment Operator.
Overheating & operator= (const struct wb_overheating &t_other)
Copy Assignment Operator.
bool operator== (const Overheating &t_other) const
bool operator!= (const Overheating &t_other) const
bool operator== (const wb_overheating &t_other) const
bool operator!= (const wb_overheating &t_other) const
bool & overheating ()
const bool & overheating () const
void set_overheating (const bool &t_newValue)
Overheating (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_overheating
bool overheating
Is the leg sensors on the nao overheating?
Detailed Description
Provides a C++ wrapper around wb_overheating.
Definition at line 83 of file Overheating.hpp.
Constructor & Destructor Documentation
Overheating() [1/4]
guWhiteboard::Overheating::Overheating (bool t_overheating = false) inline
Create a new Overheating.
Definition at line 99 of file Overheating.hpp.
Referenced by operator==().
Overheating() [2/4]
guWhiteboard::Overheating::Overheating (const Overheating & t_other) inline
Copy Constructor.
Definition at line 106 of file Overheating.hpp.
References overheating().
Overheating() [3/4]
guWhiteboard::Overheating::Overheating (const struct wb_overheating & t_other) inline
Copy Constructor.
Definition at line 113 of file Overheating.hpp.
References wb_overheating::overheating.
Overheating() [4/4]
guWhiteboard::Overheating::Overheating (const std::string & t_str) inline
String Constructor.
Definition at line 172 of file Overheating.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::Overheating::description () inline
USE_WB_OVERHEATING_C_CONVERSION
Definition at line 177 of file Overheating.hpp.
References overheating(), OVERHEATING_DESC_BUFFER_SIZE, and wb_overheating_description().
from_string()
void guWhiteboard::Overheating::from_string (const std::string & t_str) inline
USE_WB_OVERHEATING_C_CONVERSION
Definition at line 207 of file Overheating.hpp.
References OVERHEATING_DESC_BUFFER_SIZE, and set_overheating().
Referenced by Overheating().
operator!=() [1/2]
bool guWhiteboard::Overheating::operator!= (const Overheating & t_other) const inline
Definition at line 138 of file Overheating.hpp.
operator!=() [2/2]
bool guWhiteboard::Overheating::operator!= (const wb_overheating & t_other) const inline
Definition at line 148 of file Overheating.hpp.
operator=() [1/2]
Overheating & guWhiteboard::Overheating::operator= (const Overheating & t_other) inline
Copy Assignment Operator.
Definition at line 120 of file Overheating.hpp.
References overheating().
operator=() [2/2]
Overheating & guWhiteboard::Overheating::operator= (const struct wb_overheating & t_other) inline
Copy Assignment Operator.
Definition at line 128 of file Overheating.hpp.
References wb_overheating::overheating.
operator==() [1/2]
bool guWhiteboard::Overheating::operator== (const Overheating & t_other) const inline
Definition at line 133 of file Overheating.hpp.
References overheating().
operator==() [2/2]
bool guWhiteboard::Overheating::operator== (const wb_overheating & t_other) const inline
Definition at line 143 of file Overheating.hpp.
References Overheating().
overheating() [1/2]
bool & guWhiteboard::Overheating::overheating () inline
Definition at line 153 of file Overheating.hpp.
References wb_overheating::overheating.
Referenced by Overheating(), description(), operator=(), operator==(), and to_string().
overheating() [2/2]
const bool & guWhiteboard::Overheating::overheating () const inline
Definition at line 158 of file Overheating.hpp.
References wb_overheating::overheating.
set_overheating()
void guWhiteboard::Overheating::set_overheating (const bool & t_newValue) inline
Definition at line 163 of file Overheating.hpp.
References wb_overheating::overheating.
Referenced by from_string().
to_string()
std::string guWhiteboard::Overheating::to_string () inline
USE_WB_OVERHEATING_C_CONVERSION
Definition at line 190 of file Overheating.hpp.
References overheating(), OVERHEATING_TO_STRING_BUFFER_SIZE, and wb_overheating_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/Overheating.hpp