gusimplewhiteboard: guWhiteboard::VisionDetectionBalls Class Reference
guWhiteboard::VisionDetectionBalls Class Reference
Provides a C++ wrapper around wb_vision_detection_balls.
#include <VisionDetectionBalls.hpp>
Public Member Functions
VisionDetectionBalls (uint64_t t_frameNumber=0, const struct wb_vision_detection_ball t_balls[2]=NULLPTR, uint16_t t_res_width=0, uint16_t t_res_height=0)
Create a new VisionDetectionBalls.
VisionDetectionBalls (const VisionDetectionBalls &t_other)
Copy Constructor.
VisionDetectionBalls (const struct wb_vision_detection_balls &t_other)
Copy Constructor.
VisionDetectionBalls & operator= (const VisionDetectionBalls &t_other)
Copy Assignment Operator.
VisionDetectionBalls & operator= (const struct wb_vision_detection_balls &t_other)
Copy Assignment Operator.
bool operator== (const VisionDetectionBalls &t_other) const
bool operator!= (const VisionDetectionBalls &t_other) const
bool operator== (const wb_vision_detection_balls &t_other) const
bool operator!= (const wb_vision_detection_balls &t_other) const
uint64_t & frameNumber ()
const uint64_t & frameNumber () const
void set_frameNumber (const uint64_t &t_newValue)
const VisionDetectionBall * balls () const
size_t balls_size () const
VisionDetectionBall & balls (int t_i)
const VisionDetectionBall & balls (int t_i) const
void set_balls (const VisionDetectionBall *t_newValue)
void set_balls (const VisionDetectionBall &t_newValue, int t_i)
uint16_t & res_width ()
const uint16_t & res_width () const
void set_res_width (const uint16_t &t_newValue)
uint16_t & res_height ()
const uint16_t & res_height () const
void set_res_height (const uint16_t &t_newValue)
VisionDetectionBalls (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_vision_detection_balls
uint64_t frameNumber
visionFrameNumber
struct wb_vision_detection_ball balls [2]
ball objects
uint16_t res_width
The resolution width.
uint16_t res_height
The resolution height.
Detailed Description
Provides a C++ wrapper around wb_vision_detection_balls.
Definition at line 85 of file VisionDetectionBalls.hpp.
Constructor & Destructor Documentation
VisionDetectionBalls() [1/4]
guWhiteboard::VisionDetectionBalls::VisionDetectionBalls (uint64_t t_frameNumber = 0, const struct wb_vision_detection_ball t_balls[2] = NULLPTR, uint16_t t_res_width = 0, uint16_t t_res_height = 0) inline
Create a new VisionDetectionBalls.
Definition at line 109 of file VisionDetectionBalls.hpp.
Referenced by operator==().
VisionDetectionBalls() [2/4]
guWhiteboard::VisionDetectionBalls::VisionDetectionBalls (const VisionDetectionBalls & t_other) inline
Copy Constructor.
Definition at line 116 of file VisionDetectionBalls.hpp.
References balls(), frameNumber(), res_height(), and res_width().
VisionDetectionBalls() [3/4]
guWhiteboard::VisionDetectionBalls::VisionDetectionBalls (const struct wb_vision_detection_balls & t_other) inline
Copy Constructor.
Definition at line 123 of file VisionDetectionBalls.hpp.
References wb_vision_detection_balls::balls, wb_vision_detection_balls::frameNumber, wb_vision_detection_balls::res_height, and wb_vision_detection_balls::res_width.
VisionDetectionBalls() [4/4]
guWhiteboard::VisionDetectionBalls::VisionDetectionBalls (const std::string & t_str) inline
String Constructor.
Definition at line 252 of file VisionDetectionBalls.hpp.
References from_string().
Member Function Documentation
balls() [1/3]
const VisionDetectionBall * guWhiteboard::VisionDetectionBalls::balls () const inline
Definition at line 188 of file VisionDetectionBalls.hpp.
References wb_vision_detection_balls::balls.
Referenced by VisionDetectionBalls(), description(), operator=(), operator==(), and to_string().
balls() [2/3]
VisionDetectionBall & guWhiteboard::VisionDetectionBalls::balls (int t_i) inline
Definition at line 198 of file VisionDetectionBalls.hpp.
References wb_vision_detection_balls::balls.
balls() [3/3]
const VisionDetectionBall & guWhiteboard::VisionDetectionBalls::balls (int t_i) const inline
Definition at line 203 of file VisionDetectionBalls.hpp.
References wb_vision_detection_balls::balls.
balls_size()
size_t guWhiteboard::VisionDetectionBalls::balls_size () const inline
Definition at line 193 of file VisionDetectionBalls.hpp.
References VISION_DETECTION_BALLS_BALLS_ARRAY_SIZE.
description()
std::string guWhiteboard::VisionDetectionBalls::description () inline
USE_WB_VISION_DETECTION_BALLS_C_CONVERSION
Definition at line 257 of file VisionDetectionBalls.hpp.
References balls(), description(), frameNumber(), res_height(), res_width(), VISION_DETECTION_BALLS_BALLS_ARRAY_SIZE, VISION_DETECTION_BALLS_DESC_BUFFER_SIZE, and wb_vision_detection_balls_description().
Referenced by description().
frameNumber() [1/2]
uint64_t & guWhiteboard::VisionDetectionBalls::frameNumber () inline
Definition at line 173 of file VisionDetectionBalls.hpp.
References wb_vision_detection_balls::frameNumber.
Referenced by VisionDetectionBalls(), description(), operator=(), operator==(), and to_string().
frameNumber() [2/2]
const uint64_t & guWhiteboard::VisionDetectionBalls::frameNumber () const inline
Definition at line 178 of file VisionDetectionBalls.hpp.
References wb_vision_detection_balls::frameNumber.
from_string()
void guWhiteboard::VisionDetectionBalls::from_string (const std::string & t_str) inline
USE_WB_VISION_DETECTION_BALLS_C_CONVERSION
Definition at line 311 of file VisionDetectionBalls.hpp.
References guWhiteboard::VisionDetectionBall::from_string(), set_balls(), set_frameNumber(), set_res_height(), set_res_width(), VISION_DETECTION_BALLS_BALLS_ARRAY_SIZE, and VISION_DETECTION_BALLS_DESC_BUFFER_SIZE.
Referenced by VisionDetectionBalls().
operator!=() [1/2]
bool guWhiteboard::VisionDetectionBalls::operator!= (const VisionDetectionBalls & t_other) const inline
Definition at line 158 of file VisionDetectionBalls.hpp.
operator!=() [2/2]
bool guWhiteboard::VisionDetectionBalls::operator!= (const wb_vision_detection_balls & t_other) const inline
Definition at line 168 of file VisionDetectionBalls.hpp.
operator=() [1/2]
VisionDetectionBalls & guWhiteboard::VisionDetectionBalls::operator= (const struct wb_vision_detection_balls & t_other) inline
Copy Assignment Operator.
Definition at line 138 of file VisionDetectionBalls.hpp.
References wb_vision_detection_balls::balls, wb_vision_detection_balls::frameNumber, wb_vision_detection_balls::res_height, and wb_vision_detection_balls::res_width.
operator=() [2/2]
VisionDetectionBalls & guWhiteboard::VisionDetectionBalls::operator= (const VisionDetectionBalls & t_other) inline
Copy Assignment Operator.
Definition at line 130 of file VisionDetectionBalls.hpp.
References balls(), frameNumber(), res_height(), and res_width().
operator==() [1/2]
bool guWhiteboard::VisionDetectionBalls::operator== (const VisionDetectionBalls & t_other) const inline
Definition at line 143 of file VisionDetectionBalls.hpp.
References balls(), frameNumber(), res_height(), and res_width().
operator==() [2/2]
bool guWhiteboard::VisionDetectionBalls::operator== (const wb_vision_detection_balls & t_other) const inline
Definition at line 163 of file VisionDetectionBalls.hpp.
References VisionDetectionBalls().
res_height() [1/2]
uint16_t & guWhiteboard::VisionDetectionBalls::res_height () inline
Definition at line 233 of file VisionDetectionBalls.hpp.
References wb_vision_detection_balls::res_height.
Referenced by VisionDetectionBalls(), description(), operator=(), operator==(), and to_string().
res_height() [2/2]
const uint16_t & guWhiteboard::VisionDetectionBalls::res_height () const inline
Definition at line 238 of file VisionDetectionBalls.hpp.
References wb_vision_detection_balls::res_height.
res_width() [1/2]
uint16_t & guWhiteboard::VisionDetectionBalls::res_width () inline
Definition at line 218 of file VisionDetectionBalls.hpp.
References wb_vision_detection_balls::res_width.
Referenced by VisionDetectionBalls(), description(), operator=(), operator==(), and to_string().
res_width() [2/2]
const uint16_t & guWhiteboard::VisionDetectionBalls::res_width () const inline
Definition at line 223 of file VisionDetectionBalls.hpp.
References wb_vision_detection_balls::res_width.
set_balls() [1/2]
void guWhiteboard::VisionDetectionBalls::set_balls (const VisionDetectionBall & t_newValue, int t_i) inline
Definition at line 213 of file VisionDetectionBalls.hpp.
References wb_vision_detection_balls::balls.
set_balls() [2/2]
void guWhiteboard::VisionDetectionBalls::set_balls (const VisionDetectionBall * t_newValue) inline
Definition at line 208 of file VisionDetectionBalls.hpp.
References wb_vision_detection_balls::balls, and VISION_DETECTION_BALLS_BALLS_ARRAY_SIZE.
Referenced by from_string().
set_frameNumber()
void guWhiteboard::VisionDetectionBalls::set_frameNumber (const uint64_t & t_newValue) inline
Definition at line 183 of file VisionDetectionBalls.hpp.
References wb_vision_detection_balls::frameNumber.
Referenced by from_string().
set_res_height()
void guWhiteboard::VisionDetectionBalls::set_res_height (const uint16_t & t_newValue) inline
Definition at line 243 of file VisionDetectionBalls.hpp.
References wb_vision_detection_balls::res_height.
Referenced by from_string().
set_res_width()
void guWhiteboard::VisionDetectionBalls::set_res_width (const uint16_t & t_newValue) inline
Definition at line 228 of file VisionDetectionBalls.hpp.
References wb_vision_detection_balls::res_width.
Referenced by from_string().
to_string()
std::string guWhiteboard::VisionDetectionBalls::to_string () inline
USE_WB_VISION_DETECTION_BALLS_C_CONVERSION
Definition at line 282 of file VisionDetectionBalls.hpp.
References balls(), frameNumber(), res_height(), res_width(), to_string(), VISION_DETECTION_BALLS_BALLS_ARRAY_SIZE, VISION_DETECTION_BALLS_TO_STRING_BUFFER_SIZE, and wb_vision_detection_balls_to_string().
Referenced by to_string().
The documentation for this class was generated from the following file:
typeClassDefs/VisionDetectionBalls.hpp