gusimplewhiteboard: guWhiteboard::FilteredOneDimObject Class Reference
guWhiteboard::FilteredOneDimObject Class Reference
A class to contain objects that have been filtered through localisation.
#include <FilteredOneDimObject.hpp>
Public Member Functions
FilteredOneDimObject (int32_t t_frameCounter=0, int16_t t_distance=0, int16_t t_x=0, int16_t t_y=0, int16_t t_yaw=0, bool t_isVisible=false, uint64_t t_visibilityHistory=0)
designated constructor
FilteredOneDimObject (const FilteredOneDimObject &other)
copy constructor
FilteredOneDimObject (const wb_filtered_vision_object &other)
BASECONSTRUCTOR: INTERESTING !!!!
FilteredOneDimObject & operator= (const FilteredOneDimObject &other)
copy assignment operator
FilteredOneDimObject & operator= (const wb_filtered_vision_object &other)
copy assignment operator
float horizontal_angle (const float guvision_width=640.0f, const float horiz_fov=61.0f) const
Provides an estimated horizon camera angle by looking at the head yaw value.
int ratioOfSightings (const int length=64) const
number of object sigthings over length
FilteredOneDimObject (const std::string &names)
string constructor
FilteredOneDimObject (const char *names)
const char * constructor
std::string description () const
convert to a string
void from_string (const std::string &str)
TODO: still incomplete.
Public Member Functions inherited from guWhiteboard::FilteredVisionObject
FilteredVisionObject (uint64_t t_visibilityHistory=0, int32_t t_frameCounter=0, int16_t t_distance=0, int16_t t_x=0, int16_t t_y=0, int16_t t_yaw=0, int16_t t_ray_angle=0, bool t_isVisible=true, bool t_pad1=true)
Create a new FilteredVisionObject.
FilteredVisionObject (const FilteredVisionObject &t_other)
Copy Constructor.
FilteredVisionObject (const struct wb_filtered_vision_object &t_other)
Copy Constructor.
FilteredVisionObject & operator= (const FilteredVisionObject &t_other)
Copy Assignment Operator.
FilteredVisionObject & operator= (const struct wb_filtered_vision_object &t_other)
Copy Assignment Operator.
bool operator== (const FilteredVisionObject &t_other) const
bool operator!= (const FilteredVisionObject &t_other) const
bool operator== (const wb_filtered_vision_object &t_other) const
bool operator!= (const wb_filtered_vision_object &t_other) const
uint64_t & visibilityHistory ()
const uint64_t & visibilityHistory () const
void set_visibilityHistory (const uint64_t &t_newValue)
int32_t & frameCounter ()
const int32_t & frameCounter () const
void set_frameCounter (const int32_t &t_newValue)
int16_t & distance ()
const int16_t & distance () const
void set_distance (const int16_t &t_newValue)
int16_t & x ()
const int16_t & x () const
void set_x (const int16_t &t_newValue)
int16_t & y ()
const int16_t & y () const
void set_y (const int16_t &t_newValue)
int16_t & yaw ()
const int16_t & yaw () const
void set_yaw (const int16_t &t_newValue)
int16_t & ray_angle ()
const int16_t & ray_angle () const
void set_ray_angle (const int16_t &t_newValue)
bool & isVisible ()
const bool & isVisible () const
void set_isVisible (const bool &t_newValue)
bool & pad1 ()
const bool & pad1 () const
void set_pad1 (const bool &t_newValue)
FilteredVisionObject (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_filtered_vision_object
uint64_t visibilityHistory
a 64-bit history of whether vision said visible 1 or not visible 0.
int32_t frameCounter
incremented every time we do not see the object.
int16_t distance
distance to landmark in cm
int16_t x
centre x-coordinate in image (0,0) is the centre of the image, positive is to the right
int16_t y
centre y-coordinate in image, positive is upwards
int16_t yaw
the Yaw in Degrees when the object was last used to generated filtered values.
int16_t ray_angle
In degrees, position of the object, positive is left, negative is right, with distance polar position of object in frame of reference of robot.
bool isVisible
is this a credible sighting.
bool pad1
16 bit padding .
Detailed Description
A class to contain objects that have been filtered through localisation.
Definition at line 78 of file FilteredOneDimObject.hpp.
Constructor & Destructor Documentation
FilteredOneDimObject() [1/5]
guWhiteboard::FilteredOneDimObject::FilteredOneDimObject (int32_t t_frameCounter = 0, int16_t t_distance = 0, int16_t t_x = 0, int16_t t_y = 0, int16_t t_yaw = 0, bool t_isVisible = false, uint64_t t_visibilityHistory = 0) inline
designated constructor
Definition at line 82 of file FilteredOneDimObject.hpp.
Referenced by from_string().
FilteredOneDimObject() [2/5]
guWhiteboard::FilteredOneDimObject::FilteredOneDimObject (const FilteredOneDimObject & other) inline
copy constructor
Definition at line 93 of file FilteredOneDimObject.hpp.
FilteredOneDimObject() [3/5]
guWhiteboard::FilteredOneDimObject::FilteredOneDimObject (const wb_filtered_vision_object & other) inline
BASECONSTRUCTOR: INTERESTING !!!!
Definition at line 98 of file FilteredOneDimObject.hpp.
References wb_filtered_vision_object::distance, wb_filtered_vision_object::frameCounter, wb_filtered_vision_object::isVisible, guWhiteboard::FilteredVisionObject::set_distance(), guWhiteboard::FilteredVisionObject::set_frameCounter(), guWhiteboard::FilteredVisionObject::set_isVisible(), guWhiteboard::FilteredVisionObject::set_visibilityHistory(), guWhiteboard::FilteredVisionObject::set_x(), guWhiteboard::FilteredVisionObject::set_y(), guWhiteboard::FilteredVisionObject::set_yaw(), wb_filtered_vision_object::visibilityHistory, wb_filtered_vision_object::x, wb_filtered_vision_object::y, and wb_filtered_vision_object::yaw.
FilteredOneDimObject() [4/5]
guWhiteboard::FilteredOneDimObject::FilteredOneDimObject (const std::string & names) inline
string constructor
Definition at line 181 of file FilteredOneDimObject.hpp.
References from_string().
FilteredOneDimObject() [5/5]
guWhiteboard::FilteredOneDimObject::FilteredOneDimObject (const char * names) inline
const char * constructor
Definition at line 184 of file FilteredOneDimObject.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::FilteredOneDimObject::description () const inline
convert to a string
Definition at line 188 of file FilteredOneDimObject.hpp.
References guWhiteboard::FilteredVisionObject::distance(), guWhiteboard::FilteredVisionObject::frameCounter(), guWhiteboard::FilteredVisionObject::isVisible(), ratioOfSightings(), SEPARATOR_IS_COLON, SEPARATOR_IS_COMMA, guWhiteboard::FilteredVisionObject::x(), guWhiteboard::FilteredVisionObject::y(), and guWhiteboard::FilteredVisionObject::yaw().
Referenced by guWhiteboard::FilteredArrayOneDimBall::description().
from_string()
void guWhiteboard::FilteredOneDimObject::from_string (const std::string & str) inline
TODO: still incomplete.
Definition at line 203 of file FilteredOneDimObject.hpp.
References FilteredOneDimObject(), IS_VISIBLE_ID, SEPARATOR_IS_COLON, SEPARATOR_IS_COMMA, guWhiteboard::FilteredVisionObject::set_distance(), guWhiteboard::FilteredVisionObject::set_frameCounter(), guWhiteboard::FilteredVisionObject::set_isVisible(), guWhiteboard::FilteredVisionObject::set_x(), guWhiteboard::FilteredVisionObject::set_y(), and guWhiteboard::FilteredVisionObject::set_yaw().
Referenced by FilteredOneDimObject().
horizontal_angle()
float guWhiteboard::FilteredOneDimObject::horizontal_angle (const float guvision_width = 640.0f, const float horiz_fov = 61.0f) const inline
Provides an estimated horizon camera angle by looking at the head yaw value.
Definition at line 145 of file FilteredOneDimObject.hpp.
References guWhiteboard::FilteredVisionObject::x(), and guWhiteboard::FilteredVisionObject::yaw().
operator=() [1/2]
FilteredOneDimObject & guWhiteboard::FilteredOneDimObject::operator= (const FilteredOneDimObject & other) inline
copy assignment operator
Definition at line 113 of file FilteredOneDimObject.hpp.
References guWhiteboard::FilteredVisionObject::distance(), guWhiteboard::FilteredVisionObject::frameCounter(), guWhiteboard::FilteredVisionObject::isVisible(), guWhiteboard::FilteredVisionObject::set_distance(), guWhiteboard::FilteredVisionObject::set_frameCounter(), guWhiteboard::FilteredVisionObject::set_isVisible(), guWhiteboard::FilteredVisionObject::set_visibilityHistory(), guWhiteboard::FilteredVisionObject::set_x(), guWhiteboard::FilteredVisionObject::set_y(), guWhiteboard::FilteredVisionObject::set_yaw(), guWhiteboard::FilteredVisionObject::visibilityHistory(), guWhiteboard::FilteredVisionObject::x(), guWhiteboard::FilteredVisionObject::y(), and guWhiteboard::FilteredVisionObject::yaw().
operator=() [2/2]
FilteredOneDimObject & guWhiteboard::FilteredOneDimObject::operator= (const wb_filtered_vision_object & other) inline
copy assignment operator
INTERESTING !!!!
Definition at line 128 of file FilteredOneDimObject.hpp.
References wb_filtered_vision_object::distance, wb_filtered_vision_object::frameCounter, wb_filtered_vision_object::isVisible, guWhiteboard::FilteredVisionObject::set_distance(), guWhiteboard::FilteredVisionObject::set_frameCounter(), guWhiteboard::FilteredVisionObject::set_isVisible(), guWhiteboard::FilteredVisionObject::set_visibilityHistory(), guWhiteboard::FilteredVisionObject::set_x(), guWhiteboard::FilteredVisionObject::set_y(), guWhiteboard::FilteredVisionObject::set_yaw(), wb_filtered_vision_object::visibilityHistory, wb_filtered_vision_object::x, wb_filtered_vision_object::y, and wb_filtered_vision_object::yaw.
ratioOfSightings()
int guWhiteboard::FilteredOneDimObject::ratioOfSightings (const int length = 64) const inline
number of object sigthings over length
Definition at line 157 of file FilteredOneDimObject.hpp.
References guWhiteboard::FilteredVisionObject::visibilityHistory().
Referenced by description().
The documentation for this class was generated from the following file:
typeClassDefs/FilteredOneDimObject.hpp