gusimplewhiteboard: guWhiteboard::Input3D Class Reference
guWhiteboard::Input3D Class Reference
Provides a C++ wrapper around wb_input3d.
#include <Input3D.hpp>
Public Member Functions
Input3D (int16_t t_yaw=0, int16_t t_pitch=0, int16_t t_roll=0, int16_t t_power=0)
Create a new Input3D.
Input3D (const Input3D &t_other)
Copy Constructor.
Input3D (const struct wb_input3d &t_other)
Copy Constructor.
Input3D & operator= (const Input3D &t_other)
Copy Assignment Operator.
Input3D & operator= (const struct wb_input3d &t_other)
Copy Assignment Operator.
bool operator== (const Input3D &t_other) const
bool operator!= (const Input3D &t_other) const
bool operator== (const wb_input3d &t_other) const
bool operator!= (const wb_input3d &t_other) const
int16_t & yaw ()
const int16_t & yaw () const
void set_yaw (const int16_t &t_newValue)
int16_t & pitch ()
const int16_t & pitch () const
void set_pitch (const int16_t &t_newValue)
int16_t & roll ()
const int16_t & roll () const
void set_roll (const int16_t &t_newValue)
int16_t & power ()
const int16_t & power () const
void set_power (const int16_t &t_newValue)
Input3D (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_input3d
int16_t yaw
yaw
int16_t pitch
pitch
int16_t roll
roll
int16_t power
power value, ie.
Detailed Description
Provides a C++ wrapper around wb_input3d.
Definition at line 83 of file Input3D.hpp.
Constructor & Destructor Documentation
Input3D() [1/4]
guWhiteboard::Input3D::Input3D (int16_t t_yaw = 0, int16_t t_pitch = 0, int16_t t_roll = 0, int16_t t_power = 0) inline
Create a new Input3D.
Definition at line 102 of file Input3D.hpp.
Referenced by operator==().
Input3D() [2/4]
guWhiteboard::Input3D::Input3D (const Input3D & t_other) inline
Copy Constructor.
Definition at line 109 of file Input3D.hpp.
References pitch(), power(), roll(), and yaw().
Input3D() [3/4]
guWhiteboard::Input3D::Input3D (const struct wb_input3d & t_other) inline
Copy Constructor.
Definition at line 116 of file Input3D.hpp.
References wb_input3d::pitch, wb_input3d::power, wb_input3d::roll, and wb_input3d::yaw.
Input3D() [4/4]
guWhiteboard::Input3D::Input3D (const std::string & t_str) inline
String Constructor.
Definition at line 223 of file Input3D.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::Input3D::description () inline
USE_WB_INPUT3D_C_CONVERSION
Definition at line 228 of file Input3D.hpp.
References INPUT3D_DESC_BUFFER_SIZE, pitch(), power(), roll(), wb_input3d_description(), and yaw().
from_string()
void guWhiteboard::Input3D::from_string (const std::string & t_str) inline
USE_WB_INPUT3D_C_CONVERSION
Definition at line 270 of file Input3D.hpp.
References INPUT3D_DESC_BUFFER_SIZE, set_pitch(), set_power(), set_roll(), and set_yaw().
Referenced by Input3D().
operator!=() [1/2]
bool guWhiteboard::Input3D::operator!= (const Input3D & t_other) const inline
Definition at line 144 of file Input3D.hpp.
operator!=() [2/2]
bool guWhiteboard::Input3D::operator!= (const wb_input3d & t_other) const inline
Definition at line 154 of file Input3D.hpp.
operator=() [1/2]
Input3D & guWhiteboard::Input3D::operator= (const Input3D & t_other) inline
Copy Assignment Operator.
Definition at line 123 of file Input3D.hpp.
References pitch(), power(), roll(), and yaw().
operator=() [2/2]
Input3D & guWhiteboard::Input3D::operator= (const struct wb_input3d & t_other) inline
Copy Assignment Operator.
Definition at line 131 of file Input3D.hpp.
References wb_input3d::pitch, wb_input3d::power, wb_input3d::roll, and wb_input3d::yaw.
operator==() [1/2]
bool guWhiteboard::Input3D::operator== (const Input3D & t_other) const inline
Definition at line 136 of file Input3D.hpp.
References pitch(), power(), roll(), and yaw().
operator==() [2/2]
bool guWhiteboard::Input3D::operator== (const wb_input3d & t_other) const inline
Definition at line 149 of file Input3D.hpp.
References Input3D().
pitch() [1/2]
int16_t & guWhiteboard::Input3D::pitch () inline
Definition at line 174 of file Input3D.hpp.
References wb_input3d::pitch.
Referenced by Input3D(), description(), operator=(), operator==(), and to_string().
pitch() [2/2]
const int16_t & guWhiteboard::Input3D::pitch () const inline
Definition at line 179 of file Input3D.hpp.
References wb_input3d::pitch.
power() [1/2]
int16_t & guWhiteboard::Input3D::power () inline
Definition at line 204 of file Input3D.hpp.
References wb_input3d::power.
Referenced by Input3D(), description(), operator=(), operator==(), and to_string().
power() [2/2]
const int16_t & guWhiteboard::Input3D::power () const inline
Definition at line 209 of file Input3D.hpp.
References wb_input3d::power.
roll() [1/2]
int16_t & guWhiteboard::Input3D::roll () inline
Definition at line 189 of file Input3D.hpp.
References wb_input3d::roll.
Referenced by Input3D(), description(), operator=(), operator==(), and to_string().
roll() [2/2]
const int16_t & guWhiteboard::Input3D::roll () const inline
Definition at line 194 of file Input3D.hpp.
References wb_input3d::roll.
set_pitch()
void guWhiteboard::Input3D::set_pitch (const int16_t & t_newValue) inline
Definition at line 184 of file Input3D.hpp.
References wb_input3d::pitch.
Referenced by from_string().
set_power()
void guWhiteboard::Input3D::set_power (const int16_t & t_newValue) inline
Definition at line 214 of file Input3D.hpp.
References wb_input3d::power.
Referenced by from_string().
set_roll()
void guWhiteboard::Input3D::set_roll (const int16_t & t_newValue) inline
Definition at line 199 of file Input3D.hpp.
References wb_input3d::roll.
Referenced by from_string().
set_yaw()
void guWhiteboard::Input3D::set_yaw (const int16_t & t_newValue) inline
Definition at line 169 of file Input3D.hpp.
References wb_input3d::yaw.
Referenced by from_string().
to_string()
std::string guWhiteboard::Input3D::to_string () inline
USE_WB_INPUT3D_C_CONVERSION
Definition at line 247 of file Input3D.hpp.
References INPUT3D_TO_STRING_BUFFER_SIZE, pitch(), power(), roll(), wb_input3d_to_string(), and yaw().
yaw() [1/2]
int16_t & guWhiteboard::Input3D::yaw () inline
Definition at line 159 of file Input3D.hpp.
References wb_input3d::yaw.
Referenced by Input3D(), description(), operator=(), operator==(), and to_string().
yaw() [2/2]
const int16_t & guWhiteboard::Input3D::yaw () const inline
Definition at line 164 of file Input3D.hpp.
References wb_input3d::yaw.
The documentation for this class was generated from the following file:
typeClassDefs/Input3D.hpp