gusimplewhiteboard: WBFunctorBase Class Reference
WBFunctorBase Class Reference abstract
Base class for WBFunctor.
#include <WBFunctor.h>
Public Member Functions
virtual void call (std::string s, WBMsg *m)=0
Call method for the OLD whiteboard callbacks that used WBMsg - Deprecated.
virtual void call (gu_simple_message *m)=0
Call method for the 'simple' whiteboard aka 'typed whiteboard' callbacks that passes data around in a union.
virtual void call (guWhiteboard::wb_types t, gu_simple_message *m)=0
Call method for the 'simple' whiteboard aka 'typed whiteboard' callbacks that passes data around in a union.
virtual guWhiteboard::wb_types type ()=0
getter for the WB type
virtual uint16_t get_event_count ()=0
getter for the WB event counter
virtual void set_event_count (uint16_t e)=0
setter for the WB event counter
virtual bool is_simple_wb_version ()=0
is this being used by the 'simple whiteboard' or the OLD whiteboard (which is now Deprecated)
virtual ~WBFunctorBase ()
destructor
Detailed Description
Base class for WBFunctor.
This class provides outlines the interface for WBFunctor. It is designed to assist with managing callbacks
Definition at line 40 of file WBFunctor.h.
Constructor & Destructor Documentation
~WBFunctorBase()
virtual WBFunctorBase::~WBFunctorBase () inline virtual
destructor
Definition at line 79 of file WBFunctor.h.
Member Function Documentation
call() [1/3]
virtual void WBFunctorBase::call (gu_simple_message * m) pure virtual
Call method for the 'simple' whiteboard aka 'typed whiteboard' callbacks that passes data around in a union.
Parameters
m data value
Implemented in WBFunctor< C >, WBFunctor< AmberEWon_WBFunctor_T >, WBFunctor< AmberNSon_WBFunctor_T >, WBFunctor< Arduino2PinValue_WBFunctor_T >, WBFunctor< Arduino2Pin_WBFunctor_T >, WBFunctor< Arduino3PinValue_WBFunctor_T >, WBFunctor< Arduino3Pin_WBFunctor_T >, WBFunctor< Arduino4PinValue_WBFunctor_T >, WBFunctor< Arduino4Pin_WBFunctor_T >, WBFunctor< Arduino5PinValue_WBFunctor_T >, WBFunctor< Arduino5Pin_WBFunctor_T >, WBFunctor< Arduino6PinValue_WBFunctor_T >, WBFunctor< Arduino6Pin_WBFunctor_T >, WBFunctor< Arduino7PinValue_WBFunctor_T >, WBFunctor< Arduino7Pin_WBFunctor_T >, WBFunctor< Arduino8PinValue_WBFunctor_T >, WBFunctor< Arduino8Pin_WBFunctor_T >, WBFunctor< Arduino9PinValue_WBFunctor_T >, WBFunctor< Arduino9Pin_WBFunctor_T >, WBFunctor< Ball_Calibration_File_WBFunctor_T >, WBFunctor< Ball_Calibration_Num_WBFunctor_T >, WBFunctor< Ball_Color_Num_WBFunctor_T >, WBFunctor< Ball_Found_WBFunctor_T >, WBFunctor< CBall_WBFunctor_T >, WBFunctor< CarSensorPressed_WBFunctor_T >, WBFunctor< Draw_WBFunctor_T >, WBFunctor< FFTControl_WBFunctor_T >, WBFunctor< GreenEWon_WBFunctor_T >, WBFunctor< GreenNSon_WBFunctor_T >, WBFunctor< LHandGripper_WBFunctor_T >, WBFunctor< ManuallyPenalized_WBFunctor_T >, WBFunctor< PF_ControlStatus_Modes_WBFunctor_T >, WBFunctor< ParticleOutputMapControl_WBFunctor_T >, WBFunctor< ParticleOutputMap_WBFunctor_T >, WBFunctor< PlayerNumber_WBFunctor_T >, WBFunctor< Print_WBFunctor_T >, WBFunctor< QSay_WBFunctor_T >, WBFunctor< QSpeech_WBFunctor_T >, WBFunctor< REMOVED3_WBFunctor_T >, WBFunctor< REMOVED4_WBFunctor_T >, WBFunctor< RHandGripper_WBFunctor_T >, WBFunctor< RedEWon_WBFunctor_T >, WBFunctor< RedNSon_WBFunctor_T >, WBFunctor< ReproduceWavNotSilent_WBFunctor_T >, WBFunctor< SLOT_UNUSED_WBFunctor_T >, WBFunctor< Say_WBFunctor_T >, WBFunctor< SoloTypeExample_WBFunctor_T >, WBFunctor< SpeechOutput_WBFunctor_T >, WBFunctor< Speech_WBFunctor_T >, WBFunctor< TeleoperationConnection_WBFunctor_T >, WBFunctor< TimeGTfive_WBFunctor_T >, WBFunctor< TimeGTthirty_WBFunctor_T >, WBFunctor< TimerReset_WBFunctor_T >, WBFunctor< TurnRedEW_WBFunctor_T >, WBFunctor< TurnRedNS_WBFunctor_T >, WBFunctor< UDPWBNumber_WBFunctor_T >, WBFunctor< VisionFace_WBFunctor_T >, WBFunctor< VolumeControl_WBFunctor_T >, WBFunctor< WarnEW_WBFunctor_T >, WBFunctor< WarnNS_WBFunctor_T >, WBFunctor< WavLoad_WBFunctor_T >, WBFunctor< WavPlay_WBFunctor_T >, WBFunctor< WhistleBlown_WBFunctor_T >, WBFunctor< buttonPushed_WBFunctor_T >, WBFunctor< doorOpen_WBFunctor_T >, WBFunctor< light_WBFunctor_T >, WBFunctor< motor_WBFunctor_T >, WBFunctor< sound_WBFunctor_T >, WBFunctor< timeLeft_WBFunctor_T >, WBFunctor< wb_reserved_SubscribeToAllTypes_WBFunctor_T >, wb_reserved_SubscribeToAllTypes_WBFunctor< wb_reserved_SubscribeToAllTypes_WBFunctor_T >, Print_WBFunctor< Print_WBFunctor_T >, Say_WBFunctor< Say_WBFunctor_T >, Speech_WBFunctor< Speech_WBFunctor_T >, QSay_WBFunctor< QSay_WBFunctor_T >, QSpeech_WBFunctor< QSpeech_WBFunctor_T >, SpeechOutput_WBFunctor< SpeechOutput_WBFunctor_T >, SoloTypeExample_WBFunctor< SoloTypeExample_WBFunctor_T >, PlayerNumber_WBFunctor< PlayerNumber_WBFunctor_T >, ManuallyPenalized_WBFunctor< ManuallyPenalized_WBFunctor_T >, PF_ControlStatus_Modes_WBFunctor< PF_ControlStatus_Modes_WBFunctor_T >, TeleoperationConnection_WBFunctor< TeleoperationConnection_WBFunctor_T >, UDPWBNumber_WBFunctor< UDPWBNumber_WBFunctor_T >, VisionFace_WBFunctor< VisionFace_WBFunctor_T >, Draw_WBFunctor< Draw_WBFunctor_T >, REMOVED3_WBFunctor< REMOVED3_WBFunctor_T >, REMOVED4_WBFunctor< REMOVED4_WBFunctor_T >, CBall_WBFunctor< CBall_WBFunctor_T >, GreenEWon_WBFunctor< GreenEWon_WBFunctor_T >, WarnEW_WBFunctor< WarnEW_WBFunctor_T >, TimeGTthirty_WBFunctor< TimeGTthirty_WBFunctor_T >, AmberEWon_WBFunctor< AmberEWon_WBFunctor_T >, TurnRedEW_WBFunctor< TurnRedEW_WBFunctor_T >, TimeGTfive_WBFunctor< TimeGTfive_WBFunctor_T >, RedEWon_WBFunctor< RedEWon_WBFunctor_T >, GreenNSon_WBFunctor< GreenNSon_WBFunctor_T >, WarnNS_WBFunctor< WarnNS_WBFunctor_T >, AmberNSon_WBFunctor< AmberNSon_WBFunctor_T >, TurnRedNS_WBFunctor< TurnRedNS_WBFunctor_T >, RedNSon_WBFunctor< RedNSon_WBFunctor_T >, TimerReset_WBFunctor< TimerReset_WBFunctor_T >, SLOT_UNUSED_WBFunctor< SLOT_UNUSED_WBFunctor_T >, CarSensorPressed_WBFunctor< CarSensorPressed_WBFunctor_T >, Ball_Found_WBFunctor< Ball_Found_WBFunctor_T >, Ball_Calibration_File_WBFunctor< Ball_Calibration_File_WBFunctor_T >, Ball_Calibration_Num_WBFunctor< Ball_Calibration_Num_WBFunctor_T >, Ball_Color_Num_WBFunctor< Ball_Color_Num_WBFunctor_T >, WhistleBlown_WBFunctor< WhistleBlown_WBFunctor_T >, VolumeControl_WBFunctor< VolumeControl_WBFunctor_T >, ParticleOutputMap_WBFunctor< ParticleOutputMap_WBFunctor_T >, ParticleOutputMapControl_WBFunctor< ParticleOutputMapControl_WBFunctor_T >, FFTControl_WBFunctor< FFTControl_WBFunctor_T >, WavLoad_WBFunctor< WavLoad_WBFunctor_T >, WavPlay_WBFunctor< WavPlay_WBFunctor_T >, ReproduceWavNotSilent_WBFunctor< ReproduceWavNotSilent_WBFunctor_T >, buttonPushed_WBFunctor< buttonPushed_WBFunctor_T >, doorOpen_WBFunctor< doorOpen_WBFunctor_T >, timeLeft_WBFunctor< timeLeft_WBFunctor_T >, motor_WBFunctor< motor_WBFunctor_T >, sound_WBFunctor< sound_WBFunctor_T >, light_WBFunctor< light_WBFunctor_T >, Arduino2Pin_WBFunctor< Arduino2Pin_WBFunctor_T >, Arduino2PinValue_WBFunctor< Arduino2PinValue_WBFunctor_T >, Arduino3Pin_WBFunctor< Arduino3Pin_WBFunctor_T >, Arduino3PinValue_WBFunctor< Arduino3PinValue_WBFunctor_T >, Arduino4Pin_WBFunctor< Arduino4Pin_WBFunctor_T >, Arduino4PinValue_WBFunctor< Arduino4PinValue_WBFunctor_T >, Arduino5Pin_WBFunctor< Arduino5Pin_WBFunctor_T >, Arduino5PinValue_WBFunctor< Arduino5PinValue_WBFunctor_T >, Arduino6Pin_WBFunctor< Arduino6Pin_WBFunctor_T >, Arduino6PinValue_WBFunctor< Arduino6PinValue_WBFunctor_T >, Arduino7Pin_WBFunctor< Arduino7Pin_WBFunctor_T >, Arduino7PinValue_WBFunctor< Arduino7PinValue_WBFunctor_T >, Arduino8Pin_WBFunctor< Arduino8Pin_WBFunctor_T >, Arduino8PinValue_WBFunctor< Arduino8PinValue_WBFunctor_T >, Arduino9Pin_WBFunctor< Arduino9Pin_WBFunctor_T >, Arduino9PinValue_WBFunctor< Arduino9PinValue_WBFunctor_T >, LHandGripper_WBFunctor< LHandGripper_WBFunctor_T >, and RHandGripper_WBFunctor< RHandGripper_WBFunctor_T >.
call() [2/3]
virtual void WBFunctorBase::call (guWhiteboard::wb_types t, gu_simple_message * m) pure virtual
Call method for the 'simple' whiteboard aka 'typed whiteboard' callbacks that passes data around in a union.
This version allows a 'type' overwrite. This is mostly used by the 'whiteboard poster' to impersonate other message types.
Parameters
t whiteboard 'type'
m data value
Implemented in WBFunctor< C >, WBFunctor< AmberEWon_WBFunctor_T >, WBFunctor< AmberNSon_WBFunctor_T >, WBFunctor< Arduino2PinValue_WBFunctor_T >, WBFunctor< Arduino2Pin_WBFunctor_T >, WBFunctor< Arduino3PinValue_WBFunctor_T >, WBFunctor< Arduino3Pin_WBFunctor_T >, WBFunctor< Arduino4PinValue_WBFunctor_T >, WBFunctor< Arduino4Pin_WBFunctor_T >, WBFunctor< Arduino5PinValue_WBFunctor_T >, WBFunctor< Arduino5Pin_WBFunctor_T >, WBFunctor< Arduino6PinValue_WBFunctor_T >, WBFunctor< Arduino6Pin_WBFunctor_T >, WBFunctor< Arduino7PinValue_WBFunctor_T >, WBFunctor< Arduino7Pin_WBFunctor_T >, WBFunctor< Arduino8PinValue_WBFunctor_T >, WBFunctor< Arduino8Pin_WBFunctor_T >, WBFunctor< Arduino9PinValue_WBFunctor_T >, WBFunctor< Arduino9Pin_WBFunctor_T >, WBFunctor< Ball_Calibration_File_WBFunctor_T >, WBFunctor< Ball_Calibration_Num_WBFunctor_T >, WBFunctor< Ball_Color_Num_WBFunctor_T >, WBFunctor< Ball_Found_WBFunctor_T >, WBFunctor< CBall_WBFunctor_T >, WBFunctor< CarSensorPressed_WBFunctor_T >, WBFunctor< Draw_WBFunctor_T >, WBFunctor< FFTControl_WBFunctor_T >, WBFunctor< GreenEWon_WBFunctor_T >, WBFunctor< GreenNSon_WBFunctor_T >, WBFunctor< LHandGripper_WBFunctor_T >, WBFunctor< ManuallyPenalized_WBFunctor_T >, WBFunctor< PF_ControlStatus_Modes_WBFunctor_T >, WBFunctor< ParticleOutputMapControl_WBFunctor_T >, WBFunctor< ParticleOutputMap_WBFunctor_T >, WBFunctor< PlayerNumber_WBFunctor_T >, WBFunctor< Print_WBFunctor_T >, WBFunctor< QSay_WBFunctor_T >, WBFunctor< QSpeech_WBFunctor_T >, WBFunctor< REMOVED3_WBFunctor_T >, WBFunctor< REMOVED4_WBFunctor_T >, WBFunctor< RHandGripper_WBFunctor_T >, WBFunctor< RedEWon_WBFunctor_T >, WBFunctor< RedNSon_WBFunctor_T >, WBFunctor< ReproduceWavNotSilent_WBFunctor_T >, WBFunctor< SLOT_UNUSED_WBFunctor_T >, WBFunctor< Say_WBFunctor_T >, WBFunctor< SoloTypeExample_WBFunctor_T >, WBFunctor< SpeechOutput_WBFunctor_T >, WBFunctor< Speech_WBFunctor_T >, WBFunctor< TeleoperationConnection_WBFunctor_T >, WBFunctor< TimeGTfive_WBFunctor_T >, WBFunctor< TimeGTthirty_WBFunctor_T >, WBFunctor< TimerReset_WBFunctor_T >, WBFunctor< TurnRedEW_WBFunctor_T >, WBFunctor< TurnRedNS_WBFunctor_T >, WBFunctor< UDPWBNumber_WBFunctor_T >, WBFunctor< VisionFace_WBFunctor_T >, WBFunctor< VolumeControl_WBFunctor_T >, WBFunctor< WarnEW_WBFunctor_T >, WBFunctor< WarnNS_WBFunctor_T >, WBFunctor< WavLoad_WBFunctor_T >, WBFunctor< WavPlay_WBFunctor_T >, WBFunctor< WhistleBlown_WBFunctor_T >, WBFunctor< buttonPushed_WBFunctor_T >, WBFunctor< doorOpen_WBFunctor_T >, WBFunctor< light_WBFunctor_T >, WBFunctor< motor_WBFunctor_T >, WBFunctor< sound_WBFunctor_T >, WBFunctor< timeLeft_WBFunctor_T >, and WBFunctor< wb_reserved_SubscribeToAllTypes_WBFunctor_T >.
call() [3/3]
virtual void WBFunctorBase::call (std::string s, WBMsg * m) pure virtual
Call method for the OLD whiteboard callbacks that used WBMsg - Deprecated.
Parameters
s type string value
m WBMsg data value
Implemented in WBFunctor< C >, WBFunctor< AmberEWon_WBFunctor_T >, WBFunctor< AmberNSon_WBFunctor_T >, WBFunctor< Arduino2PinValue_WBFunctor_T >, WBFunctor< Arduino2Pin_WBFunctor_T >, WBFunctor< Arduino3PinValue_WBFunctor_T >, WBFunctor< Arduino3Pin_WBFunctor_T >, WBFunctor< Arduino4PinValue_WBFunctor_T >, WBFunctor< Arduino4Pin_WBFunctor_T >, WBFunctor< Arduino5PinValue_WBFunctor_T >, WBFunctor< Arduino5Pin_WBFunctor_T >, WBFunctor< Arduino6PinValue_WBFunctor_T >, WBFunctor< Arduino6Pin_WBFunctor_T >, WBFunctor< Arduino7PinValue_WBFunctor_T >, WBFunctor< Arduino7Pin_WBFunctor_T >, WBFunctor< Arduino8PinValue_WBFunctor_T >, WBFunctor< Arduino8Pin_WBFunctor_T >, WBFunctor< Arduino9PinValue_WBFunctor_T >, WBFunctor< Arduino9Pin_WBFunctor_T >, WBFunctor< Ball_Calibration_File_WBFunctor_T >, WBFunctor< Ball_Calibration_Num_WBFunctor_T >, WBFunctor< Ball_Color_Num_WBFunctor_T >, WBFunctor< Ball_Found_WBFunctor_T >, WBFunctor< CBall_WBFunctor_T >, WBFunctor< CarSensorPressed_WBFunctor_T >, WBFunctor< Draw_WBFunctor_T >, WBFunctor< FFTControl_WBFunctor_T >, WBFunctor< GreenEWon_WBFunctor_T >, WBFunctor< GreenNSon_WBFunctor_T >, WBFunctor< LHandGripper_WBFunctor_T >, WBFunctor< ManuallyPenalized_WBFunctor_T >, WBFunctor< PF_ControlStatus_Modes_WBFunctor_T >, WBFunctor< ParticleOutputMapControl_WBFunctor_T >, WBFunctor< ParticleOutputMap_WBFunctor_T >, WBFunctor< PlayerNumber_WBFunctor_T >, WBFunctor< Print_WBFunctor_T >, WBFunctor< QSay_WBFunctor_T >, WBFunctor< QSpeech_WBFunctor_T >, WBFunctor< REMOVED3_WBFunctor_T >, WBFunctor< REMOVED4_WBFunctor_T >, WBFunctor< RHandGripper_WBFunctor_T >, WBFunctor< RedEWon_WBFunctor_T >, WBFunctor< RedNSon_WBFunctor_T >, WBFunctor< ReproduceWavNotSilent_WBFunctor_T >, WBFunctor< SLOT_UNUSED_WBFunctor_T >, WBFunctor< Say_WBFunctor_T >, WBFunctor< SoloTypeExample_WBFunctor_T >, WBFunctor< SpeechOutput_WBFunctor_T >, WBFunctor< Speech_WBFunctor_T >, WBFunctor< TeleoperationConnection_WBFunctor_T >, WBFunctor< TimeGTfive_WBFunctor_T >, WBFunctor< TimeGTthirty_WBFunctor_T >, WBFunctor< TimerReset_WBFunctor_T >, WBFunctor< TurnRedEW_WBFunctor_T >, WBFunctor< TurnRedNS_WBFunctor_T >, WBFunctor< UDPWBNumber_WBFunctor_T >, WBFunctor< VisionFace_WBFunctor_T >, WBFunctor< VolumeControl_WBFunctor_T >, WBFunctor< WarnEW_WBFunctor_T >, WBFunctor< WarnNS_WBFunctor_T >, WBFunctor< WavLoad_WBFunctor_T >, WBFunctor< WavPlay_WBFunctor_T >, WBFunctor< WhistleBlown_WBFunctor_T >, WBFunctor< buttonPushed_WBFunctor_T >, WBFunctor< doorOpen_WBFunctor_T >, WBFunctor< light_WBFunctor_T >, WBFunctor< motor_WBFunctor_T >, WBFunctor< sound_WBFunctor_T >, WBFunctor< timeLeft_WBFunctor_T >, and WBFunctor< wb_reserved_SubscribeToAllTypes_WBFunctor_T >.
get_event_count()
virtual uint16_t WBFunctorBase::get_event_count () pure virtual
getter for the WB event counter
Implemented in WBFunctor< C >, WBFunctor< AmberEWon_WBFunctor_T >, WBFunctor< AmberNSon_WBFunctor_T >, WBFunctor< Arduino2PinValue_WBFunctor_T >, WBFunctor< Arduino2Pin_WBFunctor_T >, WBFunctor< Arduino3PinValue_WBFunctor_T >, WBFunctor< Arduino3Pin_WBFunctor_T >, WBFunctor< Arduino4PinValue_WBFunctor_T >, WBFunctor< Arduino4Pin_WBFunctor_T >, WBFunctor< Arduino5PinValue_WBFunctor_T >, WBFunctor< Arduino5Pin_WBFunctor_T >, WBFunctor< Arduino6PinValue_WBFunctor_T >, WBFunctor< Arduino6Pin_WBFunctor_T >, WBFunctor< Arduino7PinValue_WBFunctor_T >, WBFunctor< Arduino7Pin_WBFunctor_T >, WBFunctor< Arduino8PinValue_WBFunctor_T >, WBFunctor< Arduino8Pin_WBFunctor_T >, WBFunctor< Arduino9PinValue_WBFunctor_T >, WBFunctor< Arduino9Pin_WBFunctor_T >, WBFunctor< Ball_Calibration_File_WBFunctor_T >, WBFunctor< Ball_Calibration_Num_WBFunctor_T >, WBFunctor< Ball_Color_Num_WBFunctor_T >, WBFunctor< Ball_Found_WBFunctor_T >, WBFunctor< CBall_WBFunctor_T >, WBFunctor< CarSensorPressed_WBFunctor_T >, WBFunctor< Draw_WBFunctor_T >, WBFunctor< FFTControl_WBFunctor_T >, WBFunctor< GreenEWon_WBFunctor_T >, WBFunctor< GreenNSon_WBFunctor_T >, WBFunctor< LHandGripper_WBFunctor_T >, WBFunctor< ManuallyPenalized_WBFunctor_T >, WBFunctor< PF_ControlStatus_Modes_WBFunctor_T >, WBFunctor< ParticleOutputMapControl_WBFunctor_T >, WBFunctor< ParticleOutputMap_WBFunctor_T >, WBFunctor< PlayerNumber_WBFunctor_T >, WBFunctor< Print_WBFunctor_T >, WBFunctor< QSay_WBFunctor_T >, WBFunctor< QSpeech_WBFunctor_T >, WBFunctor< REMOVED3_WBFunctor_T >, WBFunctor< REMOVED4_WBFunctor_T >, WBFunctor< RHandGripper_WBFunctor_T >, WBFunctor< RedEWon_WBFunctor_T >, WBFunctor< RedNSon_WBFunctor_T >, WBFunctor< ReproduceWavNotSilent_WBFunctor_T >, WBFunctor< SLOT_UNUSED_WBFunctor_T >, WBFunctor< Say_WBFunctor_T >, WBFunctor< SoloTypeExample_WBFunctor_T >, WBFunctor< SpeechOutput_WBFunctor_T >, WBFunctor< Speech_WBFunctor_T >, WBFunctor< TeleoperationConnection_WBFunctor_T >, WBFunctor< TimeGTfive_WBFunctor_T >, WBFunctor< TimeGTthirty_WBFunctor_T >, WBFunctor< TimerReset_WBFunctor_T >, WBFunctor< TurnRedEW_WBFunctor_T >, WBFunctor< TurnRedNS_WBFunctor_T >, WBFunctor< UDPWBNumber_WBFunctor_T >, WBFunctor< VisionFace_WBFunctor_T >, WBFunctor< VolumeControl_WBFunctor_T >, WBFunctor< WarnEW_WBFunctor_T >, WBFunctor< WarnNS_WBFunctor_T >, WBFunctor< WavLoad_WBFunctor_T >, WBFunctor< WavPlay_WBFunctor_T >, WBFunctor< WhistleBlown_WBFunctor_T >, WBFunctor< buttonPushed_WBFunctor_T >, WBFunctor< doorOpen_WBFunctor_T >, WBFunctor< light_WBFunctor_T >, WBFunctor< motor_WBFunctor_T >, WBFunctor< sound_WBFunctor_T >, WBFunctor< timeLeft_WBFunctor_T >, and WBFunctor< wb_reserved_SubscribeToAllTypes_WBFunctor_T >.
Referenced by whiteboard_watcher::receive_callback().
is_simple_wb_version()
virtual bool WBFunctorBase::is_simple_wb_version () pure virtual
is this being used by the 'simple whiteboard' or the OLD whiteboard (which is now Deprecated)
Implemented in WBFunctor< C >, WBFunctor< AmberEWon_WBFunctor_T >, WBFunctor< AmberNSon_WBFunctor_T >, WBFunctor< Arduino2PinValue_WBFunctor_T >, WBFunctor< Arduino2Pin_WBFunctor_T >, WBFunctor< Arduino3PinValue_WBFunctor_T >, WBFunctor< Arduino3Pin_WBFunctor_T >, WBFunctor< Arduino4PinValue_WBFunctor_T >, WBFunctor< Arduino4Pin_WBFunctor_T >, WBFunctor< Arduino5PinValue_WBFunctor_T >, WBFunctor< Arduino5Pin_WBFunctor_T >, WBFunctor< Arduino6PinValue_WBFunctor_T >, WBFunctor< Arduino6Pin_WBFunctor_T >, WBFunctor< Arduino7PinValue_WBFunctor_T >, WBFunctor< Arduino7Pin_WBFunctor_T >, WBFunctor< Arduino8PinValue_WBFunctor_T >, WBFunctor< Arduino8Pin_WBFunctor_T >, WBFunctor< Arduino9PinValue_WBFunctor_T >, WBFunctor< Arduino9Pin_WBFunctor_T >, WBFunctor< Ball_Calibration_File_WBFunctor_T >, WBFunctor< Ball_Calibration_Num_WBFunctor_T >, WBFunctor< Ball_Color_Num_WBFunctor_T >, WBFunctor< Ball_Found_WBFunctor_T >, WBFunctor< CBall_WBFunctor_T >, WBFunctor< CarSensorPressed_WBFunctor_T >, WBFunctor< Draw_WBFunctor_T >, WBFunctor< FFTControl_WBFunctor_T >, WBFunctor< GreenEWon_WBFunctor_T >, WBFunctor< GreenNSon_WBFunctor_T >, WBFunctor< LHandGripper_WBFunctor_T >, WBFunctor< ManuallyPenalized_WBFunctor_T >, WBFunctor< PF_ControlStatus_Modes_WBFunctor_T >, WBFunctor< ParticleOutputMapControl_WBFunctor_T >, WBFunctor< ParticleOutputMap_WBFunctor_T >, WBFunctor< PlayerNumber_WBFunctor_T >, WBFunctor< Print_WBFunctor_T >, WBFunctor< QSay_WBFunctor_T >, WBFunctor< QSpeech_WBFunctor_T >, WBFunctor< REMOVED3_WBFunctor_T >, WBFunctor< REMOVED4_WBFunctor_T >, WBFunctor< RHandGripper_WBFunctor_T >, WBFunctor< RedEWon_WBFunctor_T >, WBFunctor< RedNSon_WBFunctor_T >, WBFunctor< ReproduceWavNotSilent_WBFunctor_T >, WBFunctor< SLOT_UNUSED_WBFunctor_T >, WBFunctor< Say_WBFunctor_T >, WBFunctor< SoloTypeExample_WBFunctor_T >, WBFunctor< SpeechOutput_WBFunctor_T >, WBFunctor< Speech_WBFunctor_T >, WBFunctor< TeleoperationConnection_WBFunctor_T >, WBFunctor< TimeGTfive_WBFunctor_T >, WBFunctor< TimeGTthirty_WBFunctor_T >, WBFunctor< TimerReset_WBFunctor_T >, WBFunctor< TurnRedEW_WBFunctor_T >, WBFunctor< TurnRedNS_WBFunctor_T >, WBFunctor< UDPWBNumber_WBFunctor_T >, WBFunctor< VisionFace_WBFunctor_T >, WBFunctor< VolumeControl_WBFunctor_T >, WBFunctor< WarnEW_WBFunctor_T >, WBFunctor< WarnNS_WBFunctor_T >, WBFunctor< WavLoad_WBFunctor_T >, WBFunctor< WavPlay_WBFunctor_T >, WBFunctor< WhistleBlown_WBFunctor_T >, WBFunctor< buttonPushed_WBFunctor_T >, WBFunctor< doorOpen_WBFunctor_T >, WBFunctor< light_WBFunctor_T >, WBFunctor< motor_WBFunctor_T >, WBFunctor< sound_WBFunctor_T >, WBFunctor< timeLeft_WBFunctor_T >, and WBFunctor< wb_reserved_SubscribeToAllTypes_WBFunctor_T >.
Referenced by whiteboard_watcher::subscribe().
set_event_count()
virtual void WBFunctorBase::set_event_count (uint16_t e) pure virtual
setter for the WB event counter
Parameters
e new event counter value
Implemented in WBFunctor< C >, WBFunctor< AmberEWon_WBFunctor_T >, WBFunctor< AmberNSon_WBFunctor_T >, WBFunctor< Arduino2PinValue_WBFunctor_T >, WBFunctor< Arduino2Pin_WBFunctor_T >, WBFunctor< Arduino3PinValue_WBFunctor_T >, WBFunctor< Arduino3Pin_WBFunctor_T >, WBFunctor< Arduino4PinValue_WBFunctor_T >, WBFunctor< Arduino4Pin_WBFunctor_T >, WBFunctor< Arduino5PinValue_WBFunctor_T >, WBFunctor< Arduino5Pin_WBFunctor_T >, WBFunctor< Arduino6PinValue_WBFunctor_T >, WBFunctor< Arduino6Pin_WBFunctor_T >, WBFunctor< Arduino7PinValue_WBFunctor_T >, WBFunctor< Arduino7Pin_WBFunctor_T >, WBFunctor< Arduino8PinValue_WBFunctor_T >, WBFunctor< Arduino8Pin_WBFunctor_T >, WBFunctor< Arduino9PinValue_WBFunctor_T >, WBFunctor< Arduino9Pin_WBFunctor_T >, WBFunctor< Ball_Calibration_File_WBFunctor_T >, WBFunctor< Ball_Calibration_Num_WBFunctor_T >, WBFunctor< Ball_Color_Num_WBFunctor_T >, WBFunctor< Ball_Found_WBFunctor_T >, WBFunctor< CBall_WBFunctor_T >, WBFunctor< CarSensorPressed_WBFunctor_T >, WBFunctor< Draw_WBFunctor_T >, WBFunctor< FFTControl_WBFunctor_T >, WBFunctor< GreenEWon_WBFunctor_T >, WBFunctor< GreenNSon_WBFunctor_T >, WBFunctor< LHandGripper_WBFunctor_T >, WBFunctor< ManuallyPenalized_WBFunctor_T >, WBFunctor< PF_ControlStatus_Modes_WBFunctor_T >, WBFunctor< ParticleOutputMapControl_WBFunctor_T >, WBFunctor< ParticleOutputMap_WBFunctor_T >, WBFunctor< PlayerNumber_WBFunctor_T >, WBFunctor< Print_WBFunctor_T >, WBFunctor< QSay_WBFunctor_T >, WBFunctor< QSpeech_WBFunctor_T >, WBFunctor< REMOVED3_WBFunctor_T >, WBFunctor< REMOVED4_WBFunctor_T >, WBFunctor< RHandGripper_WBFunctor_T >, WBFunctor< RedEWon_WBFunctor_T >, WBFunctor< RedNSon_WBFunctor_T >, WBFunctor< ReproduceWavNotSilent_WBFunctor_T >, WBFunctor< SLOT_UNUSED_WBFunctor_T >, WBFunctor< Say_WBFunctor_T >, WBFunctor< SoloTypeExample_WBFunctor_T >, WBFunctor< SpeechOutput_WBFunctor_T >, WBFunctor< Speech_WBFunctor_T >, WBFunctor< TeleoperationConnection_WBFunctor_T >, WBFunctor< TimeGTfive_WBFunctor_T >, WBFunctor< TimeGTthirty_WBFunctor_T >, WBFunctor< TimerReset_WBFunctor_T >, WBFunctor< TurnRedEW_WBFunctor_T >, WBFunctor< TurnRedNS_WBFunctor_T >, WBFunctor< UDPWBNumber_WBFunctor_T >, WBFunctor< VisionFace_WBFunctor_T >, WBFunctor< VolumeControl_WBFunctor_T >, WBFunctor< WarnEW_WBFunctor_T >, WBFunctor< WarnNS_WBFunctor_T >, WBFunctor< WavLoad_WBFunctor_T >, WBFunctor< WavPlay_WBFunctor_T >, WBFunctor< WhistleBlown_WBFunctor_T >, WBFunctor< buttonPushed_WBFunctor_T >, WBFunctor< doorOpen_WBFunctor_T >, WBFunctor< light_WBFunctor_T >, WBFunctor< motor_WBFunctor_T >, WBFunctor< sound_WBFunctor_T >, WBFunctor< timeLeft_WBFunctor_T >, and WBFunctor< wb_reserved_SubscribeToAllTypes_WBFunctor_T >.
Referenced by whiteboard_watcher::subscribe().
type()
virtual guWhiteboard::wb_types WBFunctorBase::type () pure virtual
getter for the WB type
Implemented in WBFunctor< C >, WBFunctor< AmberEWon_WBFunctor_T >, WBFunctor< AmberNSon_WBFunctor_T >, WBFunctor< Arduino2PinValue_WBFunctor_T >, WBFunctor< Arduino2Pin_WBFunctor_T >, WBFunctor< Arduino3PinValue_WBFunctor_T >, WBFunctor< Arduino3Pin_WBFunctor_T >, WBFunctor< Arduino4PinValue_WBFunctor_T >, WBFunctor< Arduino4Pin_WBFunctor_T >, WBFunctor< Arduino5PinValue_WBFunctor_T >, WBFunctor< Arduino5Pin_WBFunctor_T >, WBFunctor< Arduino6PinValue_WBFunctor_T >, WBFunctor< Arduino6Pin_WBFunctor_T >, WBFunctor< Arduino7PinValue_WBFunctor_T >, WBFunctor< Arduino7Pin_WBFunctor_T >, WBFunctor< Arduino8PinValue_WBFunctor_T >, WBFunctor< Arduino8Pin_WBFunctor_T >, WBFunctor< Arduino9PinValue_WBFunctor_T >, WBFunctor< Arduino9Pin_WBFunctor_T >, WBFunctor< Ball_Calibration_File_WBFunctor_T >, WBFunctor< Ball_Calibration_Num_WBFunctor_T >, WBFunctor< Ball_Color_Num_WBFunctor_T >, WBFunctor< Ball_Found_WBFunctor_T >, WBFunctor< CBall_WBFunctor_T >, WBFunctor< CarSensorPressed_WBFunctor_T >, WBFunctor< Draw_WBFunctor_T >, WBFunctor< FFTControl_WBFunctor_T >, WBFunctor< GreenEWon_WBFunctor_T >, WBFunctor< GreenNSon_WBFunctor_T >, WBFunctor< LHandGripper_WBFunctor_T >, WBFunctor< ManuallyPenalized_WBFunctor_T >, WBFunctor< PF_ControlStatus_Modes_WBFunctor_T >, WBFunctor< ParticleOutputMapControl_WBFunctor_T >, WBFunctor< ParticleOutputMap_WBFunctor_T >, WBFunctor< PlayerNumber_WBFunctor_T >, WBFunctor< Print_WBFunctor_T >, WBFunctor< QSay_WBFunctor_T >, WBFunctor< QSpeech_WBFunctor_T >, WBFunctor< REMOVED3_WBFunctor_T >, WBFunctor< REMOVED4_WBFunctor_T >, WBFunctor< RHandGripper_WBFunctor_T >, WBFunctor< RedEWon_WBFunctor_T >, WBFunctor< RedNSon_WBFunctor_T >, WBFunctor< ReproduceWavNotSilent_WBFunctor_T >, WBFunctor< SLOT_UNUSED_WBFunctor_T >, WBFunctor< Say_WBFunctor_T >, WBFunctor< SoloTypeExample_WBFunctor_T >, WBFunctor< SpeechOutput_WBFunctor_T >, WBFunctor< Speech_WBFunctor_T >, WBFunctor< TeleoperationConnection_WBFunctor_T >, WBFunctor< TimeGTfive_WBFunctor_T >, WBFunctor< TimeGTthirty_WBFunctor_T >, WBFunctor< TimerReset_WBFunctor_T >, WBFunctor< TurnRedEW_WBFunctor_T >, WBFunctor< TurnRedNS_WBFunctor_T >, WBFunctor< UDPWBNumber_WBFunctor_T >, WBFunctor< VisionFace_WBFunctor_T >, WBFunctor< VolumeControl_WBFunctor_T >, WBFunctor< WarnEW_WBFunctor_T >, WBFunctor< WarnNS_WBFunctor_T >, WBFunctor< WavLoad_WBFunctor_T >, WBFunctor< WavPlay_WBFunctor_T >, WBFunctor< WhistleBlown_WBFunctor_T >, WBFunctor< buttonPushed_WBFunctor_T >, WBFunctor< doorOpen_WBFunctor_T >, WBFunctor< light_WBFunctor_T >, WBFunctor< motor_WBFunctor_T >, WBFunctor< sound_WBFunctor_T >, WBFunctor< timeLeft_WBFunctor_T >, and WBFunctor< wb_reserved_SubscribeToAllTypes_WBFunctor_T >.
Referenced by whiteboard_watcher::receive_callback(), whiteboard_watcher::subscribe(), and whiteboard_watcher::unsubscribe().
The documentation for this class was generated from the following file:
WBFunctor.h