gusimplewhiteboard: guWhiteboard::TeleoperationControl Class Reference
guWhiteboard::TeleoperationControl Class Reference
Provides a C++ wrapper around wb_teleoperation_control.
#include <TeleoperationControl.hpp>
Public Member Functions
TeleoperationControl (uint8_t t_ip=0, int32_t t_action=0, int32_t t_stance=0, int32_t t_streamType=0, int32_t t_selectedCamera=0, std::string t_sayString="")
Create a new TeleoperationControl.
TeleoperationControl (const TeleoperationControl &t_other)
Copy Constructor.
TeleoperationControl (const struct wb_teleoperation_control &t_other)
Copy Constructor.
TeleoperationControl & operator= (const TeleoperationControl &t_other)
Copy Assignment Operator.
TeleoperationControl & operator= (const struct wb_teleoperation_control &t_other)
Copy Assignment Operator.
bool operator== (const TeleoperationControl &t_other) const
bool operator!= (const TeleoperationControl &t_other) const
bool operator== (const wb_teleoperation_control &t_other) const
bool operator!= (const wb_teleoperation_control &t_other) const
uint8_t & ip ()
const uint8_t & ip () const
void set_ip (const uint8_t &t_newValue)
int32_t & action ()
const int32_t & action () const
void set_action (const int32_t &t_newValue)
int32_t & stance ()
const int32_t & stance () const
void set_stance (const int32_t &t_newValue)
int32_t & streamType ()
const int32_t & streamType () const
void set_streamType (const int32_t &t_newValue)
int32_t & selectedCamera ()
const int32_t & selectedCamera () const
void set_selectedCamera (const int32_t &t_newValue)
const char * sayString () const
size_t sayString_size () const
char & sayString (int t_i)
const char & sayString (int t_i) const
void set_sayString (const char *t_newValue)
TeleoperationControl (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_teleoperation_control
uint8_t ip
Last octet of IP address.
int32_t action
Use guWhiteboard::Motions::action enum values!
int32_t stance
guWhiteboard::Motions::stance
int32_t streamType
Use enum StreamingType (Vision_Control.h)
int32_t selectedCamera
VisionCamera.
char sayString [30]
String passed to Say_t.
Detailed Description
Provides a C++ wrapper around wb_teleoperation_control.
Definition at line 83 of file TeleoperationControl.hpp.
Constructor & Destructor Documentation
TeleoperationControl() [1/4]
guWhiteboard::TeleoperationControl::TeleoperationControl (uint8_t t_ip = 0, int32_t t_action = 0, int32_t t_stance = 0, int32_t t_streamType = 0, int32_t t_selectedCamera = 0, std::string t_sayString = "") inline
Create a new TeleoperationControl.
Definition at line 104 of file TeleoperationControl.hpp.
Referenced by operator==().
TeleoperationControl() [2/4]
guWhiteboard::TeleoperationControl::TeleoperationControl (const TeleoperationControl & t_other) inline
Copy Constructor.
Definition at line 111 of file TeleoperationControl.hpp.
References action(), ip(), sayString(), selectedCamera(), stance(), and streamType().
TeleoperationControl() [3/4]
guWhiteboard::TeleoperationControl::TeleoperationControl (const struct wb_teleoperation_control & t_other) inline
Copy Constructor.
Definition at line 118 of file TeleoperationControl.hpp.
References wb_teleoperation_control::action, wb_teleoperation_control::ip, wb_teleoperation_control::sayString, wb_teleoperation_control::selectedCamera, wb_teleoperation_control::stance, and wb_teleoperation_control::streamType.
TeleoperationControl() [4/4]
guWhiteboard::TeleoperationControl::TeleoperationControl (const std::string & t_str) inline
String Constructor.
Definition at line 267 of file TeleoperationControl.hpp.
References from_string().
Member Function Documentation
action() [1/2]
int32_t & guWhiteboard::TeleoperationControl::action () inline
Definition at line 178 of file TeleoperationControl.hpp.
References wb_teleoperation_control::action.
Referenced by TeleoperationControl(), description(), operator=(), operator==(), and to_string().
action() [2/2]
const int32_t & guWhiteboard::TeleoperationControl::action () const inline
Definition at line 183 of file TeleoperationControl.hpp.
References wb_teleoperation_control::action.
description()
std::string guWhiteboard::TeleoperationControl::description () inline
USE_WB_TELEOPERATION_CONTROL_C_CONVERSION
Definition at line 272 of file TeleoperationControl.hpp.
References action(), ip(), sayString(), selectedCamera(), stance(), streamType(), TELEOPERATIONCONTROL_DESC_BUFFER_SIZE, and wb_teleoperation_control_description().
from_string()
void guWhiteboard::TeleoperationControl::from_string (const std::string & t_str) inline
USE_WB_TELEOPERATION_CONTROL_C_CONVERSION
Definition at line 330 of file TeleoperationControl.hpp.
References wb_teleoperation_control::sayString, set_action(), set_ip(), set_selectedCamera(), set_stance(), set_streamType(), and TELEOPERATIONCONTROL_DESC_BUFFER_SIZE.
Referenced by TeleoperationControl().
ip() [1/2]
uint8_t & guWhiteboard::TeleoperationControl::ip () inline
Definition at line 163 of file TeleoperationControl.hpp.
References wb_teleoperation_control::ip.
Referenced by TeleoperationControl(), description(), operator=(), operator==(), and to_string().
ip() [2/2]
const uint8_t & guWhiteboard::TeleoperationControl::ip () const inline
Definition at line 168 of file TeleoperationControl.hpp.
References wb_teleoperation_control::ip.
operator!=() [1/2]
bool guWhiteboard::TeleoperationControl::operator!= (const TeleoperationControl & t_other) const inline
Definition at line 148 of file TeleoperationControl.hpp.
operator!=() [2/2]
bool guWhiteboard::TeleoperationControl::operator!= (const wb_teleoperation_control & t_other) const inline
Definition at line 158 of file TeleoperationControl.hpp.
operator=() [1/2]
TeleoperationControl & guWhiteboard::TeleoperationControl::operator= (const struct wb_teleoperation_control & t_other) inline
Copy Assignment Operator.
Definition at line 133 of file TeleoperationControl.hpp.
References wb_teleoperation_control::action, wb_teleoperation_control::ip, wb_teleoperation_control::sayString, wb_teleoperation_control::selectedCamera, wb_teleoperation_control::stance, and wb_teleoperation_control::streamType.
operator=() [2/2]
TeleoperationControl & guWhiteboard::TeleoperationControl::operator= (const TeleoperationControl & t_other) inline
Copy Assignment Operator.
Definition at line 125 of file TeleoperationControl.hpp.
References action(), ip(), sayString(), selectedCamera(), stance(), and streamType().
operator==() [1/2]
bool guWhiteboard::TeleoperationControl::operator== (const TeleoperationControl & t_other) const inline
Definition at line 138 of file TeleoperationControl.hpp.
References action(), ip(), sayString(), selectedCamera(), stance(), and streamType().
operator==() [2/2]
bool guWhiteboard::TeleoperationControl::operator== (const wb_teleoperation_control & t_other) const inline
Definition at line 153 of file TeleoperationControl.hpp.
References TeleoperationControl().
sayString() [1/3]
const char * guWhiteboard::TeleoperationControl::sayString () const inline
Definition at line 238 of file TeleoperationControl.hpp.
References wb_teleoperation_control::sayString.
Referenced by TeleoperationControl(), description(), operator=(), operator==(), and to_string().
sayString() [2/3]
char & guWhiteboard::TeleoperationControl::sayString (int t_i) inline
Definition at line 248 of file TeleoperationControl.hpp.
References wb_teleoperation_control::sayString.
sayString() [3/3]
const char & guWhiteboard::TeleoperationControl::sayString (int t_i) const inline
Definition at line 253 of file TeleoperationControl.hpp.
References wb_teleoperation_control::sayString.
sayString_size()
size_t guWhiteboard::TeleoperationControl::sayString_size () const inline
Definition at line 243 of file TeleoperationControl.hpp.
selectedCamera() [1/2]
int32_t & guWhiteboard::TeleoperationControl::selectedCamera () inline
Definition at line 223 of file TeleoperationControl.hpp.
References wb_teleoperation_control::selectedCamera.
Referenced by TeleoperationControl(), description(), operator=(), operator==(), and to_string().
selectedCamera() [2/2]
const int32_t & guWhiteboard::TeleoperationControl::selectedCamera () const inline
Definition at line 228 of file TeleoperationControl.hpp.
References wb_teleoperation_control::selectedCamera.
set_action()
void guWhiteboard::TeleoperationControl::set_action (const int32_t & t_newValue) inline
Definition at line 188 of file TeleoperationControl.hpp.
References wb_teleoperation_control::action.
Referenced by from_string().
set_ip()
void guWhiteboard::TeleoperationControl::set_ip (const uint8_t & t_newValue) inline
Definition at line 173 of file TeleoperationControl.hpp.
References wb_teleoperation_control::ip.
Referenced by from_string().
set_sayString()
void guWhiteboard::TeleoperationControl::set_sayString (const char * t_newValue) inline
Definition at line 258 of file TeleoperationControl.hpp.
References wb_teleoperation_control::sayString.
set_selectedCamera()
void guWhiteboard::TeleoperationControl::set_selectedCamera (const int32_t & t_newValue) inline
Definition at line 233 of file TeleoperationControl.hpp.
References wb_teleoperation_control::selectedCamera.
Referenced by from_string().
set_stance()
void guWhiteboard::TeleoperationControl::set_stance (const int32_t & t_newValue) inline
Definition at line 203 of file TeleoperationControl.hpp.
References wb_teleoperation_control::stance.
Referenced by from_string().
set_streamType()
void guWhiteboard::TeleoperationControl::set_streamType (const int32_t & t_newValue) inline
Definition at line 218 of file TeleoperationControl.hpp.
References wb_teleoperation_control::streamType.
Referenced by from_string().
stance() [1/2]
int32_t & guWhiteboard::TeleoperationControl::stance () inline
Definition at line 193 of file TeleoperationControl.hpp.
References wb_teleoperation_control::stance.
Referenced by TeleoperationControl(), description(), operator=(), operator==(), and to_string().
stance() [2/2]
const int32_t & guWhiteboard::TeleoperationControl::stance () const inline
Definition at line 198 of file TeleoperationControl.hpp.
References wb_teleoperation_control::stance.
streamType() [1/2]
int32_t & guWhiteboard::TeleoperationControl::streamType () inline
Definition at line 208 of file TeleoperationControl.hpp.
References wb_teleoperation_control::streamType.
Referenced by TeleoperationControl(), description(), operator=(), operator==(), and to_string().
streamType() [2/2]
const int32_t & guWhiteboard::TeleoperationControl::streamType () const inline
Definition at line 213 of file TeleoperationControl.hpp.
References wb_teleoperation_control::streamType.
to_string()
std::string guWhiteboard::TeleoperationControl::to_string () inline
USE_WB_TELEOPERATION_CONTROL_C_CONVERSION
Definition at line 299 of file TeleoperationControl.hpp.
References action(), ip(), sayString(), selectedCamera(), stance(), streamType(), TELEOPERATIONCONTROL_TO_STRING_BUFFER_SIZE, and wb_teleoperation_control_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/TeleoperationControl.hpp