gusimplewhiteboard: guWhiteboard::FilteredArrayOneDimBall Class Reference
guWhiteboard::FilteredArrayOneDimBall Class Reference
Class for for the array of ball sighthings TOP or Bottom.
#include <FilteredArrayOneDimBall.hpp>
Public Member Functions
FilteredArrayOneDimBall ()
designated constructor
FilteredArrayOneDimBall (const class FilteredOneDimObject &obj, enum FilteredVisionObjectType landmarkType=FVOBallTop)
constructor with one setter
FilteredArrayOneDimBall (const FilteredArrayOneDimBall &other)
copy constructor
FilteredArrayOneDimBall & operator= (const FilteredArrayOneDimBall &other)
copy assignment operator
void set_objects (const class FilteredArrayOneDimBall *t_objects)
property getter
void set_object (const class FilteredOneDimObject &obj, enum FilteredVisionObjectType landmarkType=FVOBallTop)
single vision object setter
FilteredOneDimObject get_object (enum FilteredVisionObjectType landmarkType=FVOBallTop)
single vision object setter
FilteredArrayOneDimBall (const std::string &names)
string constructor
FilteredArrayOneDimBall (const char *names)
const char * constructor
std::string description ()
convert to a string; string serialization
void from_string (const std::string &str)
build from string
Public Member Functions inherited from guWhiteboard::FilteredArrayBallSightings
FilteredArrayBallSightings (const struct wb_filtered_vision_object t_objects[2]=NULLPTR)
Create a new FilteredArrayBallSightings.
FilteredArrayBallSightings (const FilteredArrayBallSightings &t_other)
Copy Constructor.
FilteredArrayBallSightings (const struct wb_filtered_arrayballsightings &t_other)
Copy Constructor.
FilteredArrayBallSightings & operator= (const FilteredArrayBallSightings &t_other)
Copy Assignment Operator.
FilteredArrayBallSightings & operator= (const struct wb_filtered_arrayballsightings &t_other)
Copy Assignment Operator.
bool operator== (const FilteredArrayBallSightings &t_other) const
bool operator!= (const FilteredArrayBallSightings &t_other) const
bool operator== (const wb_filtered_arrayballsightings &t_other) const
bool operator!= (const wb_filtered_arrayballsightings &t_other) const
const FilteredVisionObject * objects () const
size_t objects_size () const
FilteredVisionObject & objects (int t_i)
const FilteredVisionObject & objects (int t_i) const
void set_objects (const FilteredVisionObject *t_newValue)
void set_objects (const FilteredVisionObject &t_newValue, int t_i)
FilteredArrayBallSightings (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_filtered_arrayballsightings
struct wb_filtered_vision_object objects [2]
the array containing filtered balls on separate cameras reported by vision FVO_NUM_CAMERAS =2
Detailed Description
Class for for the array of ball sighthings TOP or Bottom.
Definition at line 75 of file FilteredArrayOneDimBall.hpp.
Constructor & Destructor Documentation
FilteredArrayOneDimBall() [1/5]
guWhiteboard::FilteredArrayOneDimBall::FilteredArrayOneDimBall () inline
designated constructor
Definition at line 85 of file FilteredArrayOneDimBall.hpp.
FilteredArrayOneDimBall() [2/5]
guWhiteboard::FilteredArrayOneDimBall::FilteredArrayOneDimBall (const class FilteredOneDimObject & obj, enum FilteredVisionObjectType landmarkType = FVOBallTop) inline
constructor with one setter
Definition at line 89 of file FilteredArrayOneDimBall.hpp.
References guWhiteboard::FilteredArrayBallSightings::set_objects().
FilteredArrayOneDimBall() [3/5]
guWhiteboard::FilteredArrayOneDimBall::FilteredArrayOneDimBall (const FilteredArrayOneDimBall & other) inline
copy constructor
Definition at line 98 of file FilteredArrayOneDimBall.hpp.
FilteredArrayOneDimBall() [4/5]
guWhiteboard::FilteredArrayOneDimBall::FilteredArrayOneDimBall (const std::string & names) inline
string constructor
Definition at line 141 of file FilteredArrayOneDimBall.hpp.
References from_string().
FilteredArrayOneDimBall() [5/5]
guWhiteboard::FilteredArrayOneDimBall::FilteredArrayOneDimBall (const char * names) inline
const char * constructor
Definition at line 144 of file FilteredArrayOneDimBall.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::FilteredArrayOneDimBall::description () inline
convert to a string; string serialization
Definition at line 149 of file FilteredArrayOneDimBall.hpp.
References BOTTM_ID, guWhiteboard::FilteredOneDimObject::description(), FVO_NUM_CAMERAS, FVOBallBottom, FVOBallTop, get_object(), SEPARATOR_IS_COLON, and TOP_ID.
from_string()
void guWhiteboard::FilteredArrayOneDimBall::from_string (const std::string & str) inline
build from string
Definition at line 170 of file FilteredArrayOneDimBall.hpp.
References BOTTM_ID, FVOBallBottom, FVOBallTop, SEPARATOR_IS_COLON, set_object(), and TOP_ID.
Referenced by FilteredArrayOneDimBall().
get_object()
FilteredOneDimObject guWhiteboard::FilteredArrayOneDimBall::get_object (enum FilteredVisionObjectType landmarkType = FVOBallTop) inline
single vision object setter
Definition at line 133 of file FilteredArrayOneDimBall.hpp.
References guWhiteboard::FilteredArrayBallSightings::objects().
Referenced by description().
operator=()
FilteredArrayOneDimBall & guWhiteboard::FilteredArrayOneDimBall::operator= (const FilteredArrayOneDimBall & other) inline
copy assignment operator
Definition at line 107 of file FilteredArrayOneDimBall.hpp.
set_object()
void guWhiteboard::FilteredArrayOneDimBall::set_object (const class FilteredOneDimObject & obj, enum FilteredVisionObjectType landmarkType = FVOBallTop) inline
single vision object setter
Definition at line 127 of file FilteredArrayOneDimBall.hpp.
References guWhiteboard::FilteredArrayBallSightings::set_objects().
Referenced by from_string().
set_objects()
void guWhiteboard::FilteredArrayOneDimBall::set_objects (const class FilteredArrayOneDimBall * t_objects) inline
property getter
property setter
Parameters
t_objects setter object
Definition at line 121 of file FilteredArrayOneDimBall.hpp.
References guWhiteboard::FilteredArrayBallSightings::objects(), and wb_filtered_arrayballsightings::objects.
The documentation for this class was generated from the following file:
typeClassDefs/FilteredArrayOneDimBall.hpp