gusimplewhiteboard: guWhiteboard::LandmarkSighting Class Reference
guWhiteboard::LandmarkSighting Class Reference
Provides a C++ wrapper around wb_landmark_sighting.
#include <LandmarkSighting.hpp>
Public Member Functions
LandmarkSighting (int16_t t_direction=0, uint16_t t_distance=0, enum LandmarkSightingType t_sightingType=static_cast< enum LandmarkSightingType >(0))
Create a new LandmarkSighting.
LandmarkSighting (const LandmarkSighting &t_other)
Copy Constructor.
LandmarkSighting (const struct wb_landmark_sighting &t_other)
Copy Constructor.
LandmarkSighting & operator= (const LandmarkSighting &t_other)
Copy Assignment Operator.
LandmarkSighting & operator= (const struct wb_landmark_sighting &t_other)
Copy Assignment Operator.
bool operator== (const LandmarkSighting &t_other) const
bool operator!= (const LandmarkSighting &t_other) const
bool operator== (const wb_landmark_sighting &t_other) const
bool operator!= (const wb_landmark_sighting &t_other) const
int16_t & direction ()
const int16_t & direction () const
void set_direction (const int16_t &t_newValue)
uint16_t & distance ()
const uint16_t & distance () const
void set_distance (const uint16_t &t_newValue)
enum LandmarkSightingType & sightingType ()
enum LandmarkSightingType & sightingType () const
void set_sightingType (const enum LandmarkSightingType &t_newValue)
LandmarkSighting (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_landmark_sighting
int16_t direction
degrees, relative to the center of the nao torso.
uint16_t distance
CM distance to the center point of the sighting.
enum LandmarkSightingType sightingType
The type of sighting.
Detailed Description
Provides a C++ wrapper around wb_landmark_sighting.
Definition at line 83 of file LandmarkSighting.hpp.
Constructor & Destructor Documentation
LandmarkSighting() [1/4]
guWhiteboard::LandmarkSighting::LandmarkSighting (int16_t t_direction = 0, uint16_t t_distance = 0, enum LandmarkSightingType t_sightingType = static_cast<enum LandmarkSightingType>(0)) inline
Create a new LandmarkSighting.
Definition at line 101 of file LandmarkSighting.hpp.
Referenced by operator==().
LandmarkSighting() [2/4]
guWhiteboard::LandmarkSighting::LandmarkSighting (const LandmarkSighting & t_other) inline
Copy Constructor.
Definition at line 108 of file LandmarkSighting.hpp.
References direction(), distance(), and sightingType().
LandmarkSighting() [3/4]
guWhiteboard::LandmarkSighting::LandmarkSighting (const struct wb_landmark_sighting & t_other) inline
Copy Constructor.
Definition at line 115 of file LandmarkSighting.hpp.
References wb_landmark_sighting::direction, wb_landmark_sighting::distance, and wb_landmark_sighting::sightingType.
LandmarkSighting() [4/4]
guWhiteboard::LandmarkSighting::LandmarkSighting (const std::string & t_str) inline
String Constructor.
Definition at line 206 of file LandmarkSighting.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::LandmarkSighting::description () inline
USE_WB_LANDMARK_SIGHTING_C_CONVERSION
Definition at line 211 of file LandmarkSighting.hpp.
References BallSightingType, CornerHorizonSightingType, CornerLineSightingType, CrossLineSightingType, direction(), distance(), GenericGoalPostSightingType, GoalLandmarkSightingType, LANDMARK_SIGHTING_DESC_BUFFER_SIZE, LeftGoalPostSightingType, LineHorizonSightingType, RightGoalPostSightingType, sightingType(), StraightLineSightingType, TIntersectionLineSightingType, and wb_landmark_sighting_description().
direction() [1/2]
int16_t & guWhiteboard::LandmarkSighting::direction () inline
Definition at line 157 of file LandmarkSighting.hpp.
References wb_landmark_sighting::direction.
Referenced by LandmarkSighting(), description(), operator=(), operator==(), and to_string().
direction() [2/2]
const int16_t & guWhiteboard::LandmarkSighting::direction () const inline
Definition at line 162 of file LandmarkSighting.hpp.
References wb_landmark_sighting::direction.
distance() [1/2]
uint16_t & guWhiteboard::LandmarkSighting::distance () inline
Definition at line 172 of file LandmarkSighting.hpp.
References wb_landmark_sighting::distance.
Referenced by LandmarkSighting(), description(), operator=(), operator==(), and to_string().
distance() [2/2]
const uint16_t & guWhiteboard::LandmarkSighting::distance () const inline
Definition at line 177 of file LandmarkSighting.hpp.
References wb_landmark_sighting::distance.
from_string()
void guWhiteboard::LandmarkSighting::from_string (const std::string & t_str) inline
USE_WB_LANDMARK_SIGHTING_C_CONVERSION
Definition at line 361 of file LandmarkSighting.hpp.
References BallSightingType, CornerHorizonSightingType, CornerLineSightingType, CrossLineSightingType, GenericGoalPostSightingType, GoalLandmarkSightingType, LANDMARK_SIGHTING_DESC_BUFFER_SIZE, LeftGoalPostSightingType, LineHorizonSightingType, RightGoalPostSightingType, set_direction(), set_distance(), set_sightingType(), StraightLineSightingType, and TIntersectionLineSightingType.
Referenced by LandmarkSighting(), and guWhiteboard::MachineFilteredLocalisationVision::from_string().
operator!=() [1/2]
bool guWhiteboard::LandmarkSighting::operator!= (const LandmarkSighting & t_other) const inline
Definition at line 142 of file LandmarkSighting.hpp.
operator!=() [2/2]
bool guWhiteboard::LandmarkSighting::operator!= (const wb_landmark_sighting & t_other) const inline
Definition at line 152 of file LandmarkSighting.hpp.
operator=() [1/2]
LandmarkSighting & guWhiteboard::LandmarkSighting::operator= (const LandmarkSighting & t_other) inline
Copy Assignment Operator.
Definition at line 122 of file LandmarkSighting.hpp.
References direction(), distance(), and sightingType().
operator=() [2/2]
LandmarkSighting & guWhiteboard::LandmarkSighting::operator= (const struct wb_landmark_sighting & t_other) inline
Copy Assignment Operator.
Definition at line 130 of file LandmarkSighting.hpp.
References wb_landmark_sighting::direction, wb_landmark_sighting::distance, and wb_landmark_sighting::sightingType.
operator==() [1/2]
bool guWhiteboard::LandmarkSighting::operator== (const LandmarkSighting & t_other) const inline
Definition at line 135 of file LandmarkSighting.hpp.
References direction(), distance(), and sightingType().
operator==() [2/2]
bool guWhiteboard::LandmarkSighting::operator== (const wb_landmark_sighting & t_other) const inline
Definition at line 147 of file LandmarkSighting.hpp.
References LandmarkSighting().
set_direction()
void guWhiteboard::LandmarkSighting::set_direction (const int16_t & t_newValue) inline
Definition at line 167 of file LandmarkSighting.hpp.
References wb_landmark_sighting::direction.
Referenced by from_string().
set_distance()
void guWhiteboard::LandmarkSighting::set_distance (const uint16_t & t_newValue) inline
Definition at line 182 of file LandmarkSighting.hpp.
References wb_landmark_sighting::distance.
Referenced by from_string().
set_sightingType()
void guWhiteboard::LandmarkSighting::set_sightingType (const enum LandmarkSightingType & t_newValue) inline
Definition at line 197 of file LandmarkSighting.hpp.
References wb_landmark_sighting::sightingType.
Referenced by from_string().
sightingType() [1/2]
enum LandmarkSightingType & guWhiteboard::LandmarkSighting::sightingType () inline
Definition at line 187 of file LandmarkSighting.hpp.
References wb_landmark_sighting::sightingType.
Referenced by LandmarkSighting(), description(), guWhiteboard::MachineFilteredLocalisationVision::firstSighting(), operator=(), operator==(), and to_string().
sightingType() [2/2]
enum LandmarkSightingType & guWhiteboard::LandmarkSighting::sightingType () const inline
Definition at line 192 of file LandmarkSighting.hpp.
References wb_landmark_sighting::sightingType.
to_string()
std::string guWhiteboard::LandmarkSighting::to_string () inline
USE_WB_LANDMARK_SIGHTING_C_CONVERSION
Definition at line 284 of file LandmarkSighting.hpp.
References BallSightingType, CornerHorizonSightingType, CornerLineSightingType, CrossLineSightingType, direction(), distance(), GenericGoalPostSightingType, GoalLandmarkSightingType, LANDMARK_SIGHTING_TO_STRING_BUFFER_SIZE, LeftGoalPostSightingType, LineHorizonSightingType, RightGoalPostSightingType, sightingType(), StraightLineSightingType, TIntersectionLineSightingType, and wb_landmark_sighting_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/LandmarkSighting.hpp