gusimplewhiteboard: guWhiteboard::TopParticles Class Reference
guWhiteboard::TopParticles Class Reference
Provides a C++ wrapper around wb_top_particles.
#include <TopParticles.hpp>
Public Member Functions
TopParticles (const struct wb_particle_position t_particles[4]=NULLPTR)
Create a new TopParticles.
TopParticles (const TopParticles &t_other)
Copy Constructor.
TopParticles (const struct wb_top_particles &t_other)
Copy Constructor.
TopParticles & operator= (const TopParticles &t_other)
Copy Assignment Operator.
TopParticles & operator= (const struct wb_top_particles &t_other)
Copy Assignment Operator.
bool operator== (const TopParticles &t_other) const
bool operator!= (const TopParticles &t_other) const
bool operator== (const wb_top_particles &t_other) const
bool operator!= (const wb_top_particles &t_other) const
const ParticlePosition * particles () const
size_t particles_size () const
ParticlePosition & particles (int t_i)
const ParticlePosition & particles (int t_i) const
void set_particles (const ParticlePosition *t_newValue)
void set_particles (const ParticlePosition &t_newValue, int t_i)
TopParticles (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
const ParticlePosition topParticle ()
WHITEBOARD_POSTER_STRING_CONVERSION.
Additional Inherited Members
Public Attributes inherited from wb_top_particles
struct wb_particle_position particles [4]
these 4 should be the constant NUM_TOP_PARTICLES
Detailed Description
Provides a C++ wrapper around wb_top_particles.
Definition at line 87 of file TopParticles.hpp.
Constructor & Destructor Documentation
TopParticles() [1/4]
guWhiteboard::TopParticles::TopParticles (const struct wb_particle_position t_particles[4] = NULLPTR) inline
Create a new TopParticles.
Definition at line 108 of file TopParticles.hpp.
Referenced by operator==().
TopParticles() [2/4]
guWhiteboard::TopParticles::TopParticles (const TopParticles & t_other) inline
Copy Constructor.
Definition at line 115 of file TopParticles.hpp.
References particles().
TopParticles() [3/4]
guWhiteboard::TopParticles::TopParticles (const struct wb_top_particles & t_other) inline
Copy Constructor.
Definition at line 122 of file TopParticles.hpp.
References wb_top_particles::particles.
TopParticles() [4/4]
guWhiteboard::TopParticles::TopParticles (const std::string & t_str) inline
String Constructor.
Definition at line 200 of file TopParticles.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::TopParticles::description () inline
USE_WB_TOP_PARTICLES_C_CONVERSION
Definition at line 205 of file TopParticles.hpp.
References description(), particles(), TOPPARTICLES_DESC_BUFFER_SIZE, TOPPARTICLES_PARTICLES_ARRAY_SIZE, and wb_top_particles_description().
Referenced by description().
from_string()
void guWhiteboard::TopParticles::from_string (const std::string & t_str) inline
USE_WB_TOP_PARTICLES_C_CONVERSION
Definition at line 247 of file TopParticles.hpp.
References guWhiteboard::ParticlePosition::from_string(), set_particles(), TOPPARTICLES_DESC_BUFFER_SIZE, and TOPPARTICLES_PARTICLES_ARRAY_SIZE.
Referenced by TopParticles().
operator!=() [1/2]
bool guWhiteboard::TopParticles::operator!= (const TopParticles & t_other) const inline
Definition at line 151 of file TopParticles.hpp.
operator!=() [2/2]
bool guWhiteboard::TopParticles::operator!= (const wb_top_particles & t_other) const inline
Definition at line 161 of file TopParticles.hpp.
operator=() [1/2]
TopParticles & guWhiteboard::TopParticles::operator= (const struct wb_top_particles & t_other) inline
Copy Assignment Operator.
Definition at line 137 of file TopParticles.hpp.
References wb_top_particles::particles.
operator=() [2/2]
TopParticles & guWhiteboard::TopParticles::operator= (const TopParticles & t_other) inline
Copy Assignment Operator.
Definition at line 129 of file TopParticles.hpp.
References particles().
operator==() [1/2]
bool guWhiteboard::TopParticles::operator== (const TopParticles & t_other) const inline
Definition at line 142 of file TopParticles.hpp.
References particles().
operator==() [2/2]
bool guWhiteboard::TopParticles::operator== (const wb_top_particles & t_other) const inline
Definition at line 156 of file TopParticles.hpp.
References TopParticles().
particles() [1/3]
const ParticlePosition * guWhiteboard::TopParticles::particles () const inline
Definition at line 166 of file TopParticles.hpp.
References wb_top_particles::particles.
Referenced by TopParticles(), description(), operator=(), operator==(), to_string(), and topParticle().
particles() [2/3]
ParticlePosition & guWhiteboard::TopParticles::particles (int t_i) inline
Definition at line 176 of file TopParticles.hpp.
References wb_top_particles::particles.
particles() [3/3]
const ParticlePosition & guWhiteboard::TopParticles::particles (int t_i) const inline
Definition at line 181 of file TopParticles.hpp.
References wb_top_particles::particles.
particles_size()
size_t guWhiteboard::TopParticles::particles_size () const inline
Definition at line 171 of file TopParticles.hpp.
References TOPPARTICLES_PARTICLES_ARRAY_SIZE.
set_particles() [1/2]
void guWhiteboard::TopParticles::set_particles (const ParticlePosition & t_newValue, int t_i) inline
Definition at line 191 of file TopParticles.hpp.
References wb_top_particles::particles.
set_particles() [2/2]
void guWhiteboard::TopParticles::set_particles (const ParticlePosition * t_newValue) inline
Definition at line 186 of file TopParticles.hpp.
References wb_top_particles::particles, and TOPPARTICLES_PARTICLES_ARRAY_SIZE.
Referenced by from_string().
to_string()
std::string guWhiteboard::TopParticles::to_string () inline
USE_WB_TOP_PARTICLES_C_CONVERSION
Definition at line 224 of file TopParticles.hpp.
References particles(), to_string(), TOPPARTICLES_PARTICLES_ARRAY_SIZE, TOPPARTICLES_TO_STRING_BUFFER_SIZE, and wb_top_particles_to_string().
Referenced by to_string().
topParticle()
const ParticlePosition guWhiteboard::TopParticles::topParticle () inline
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 401 of file TopParticles.hpp.
References particles().
The documentation for this class was generated from the following file:
typeClassDefs/TopParticles.hpp