gusimplewhiteboard: guWhiteboard::ParticleOutputMap Class Reference
guWhiteboard::ParticleOutputMap Class Reference
Provides a C++ wrapper around wb_particle_output_map.
#include <ParticleOutputMap.hpp>
Public Member Functions
ParticleOutputMap (uint8_t t_fileId=0, std::string t_filePath="")
Create a new ParticleOutputMap.
ParticleOutputMap (const ParticleOutputMap &t_other)
Copy Constructor.
ParticleOutputMap (const struct wb_particle_output_map &t_other)
Copy Constructor.
ParticleOutputMap & operator= (const ParticleOutputMap &t_other)
Copy Assignment Operator.
ParticleOutputMap & operator= (const struct wb_particle_output_map &t_other)
Copy Assignment Operator.
bool operator== (const ParticleOutputMap &t_other) const
bool operator!= (const ParticleOutputMap &t_other) const
bool operator== (const wb_particle_output_map &t_other) const
bool operator!= (const wb_particle_output_map &t_other) const
uint8_t & fileId ()
const uint8_t & fileId () const
void set_fileId (const uint8_t &t_newValue)
const char * filePath () const
size_t filePath_size () const
char & filePath (int t_i)
const char & filePath (int t_i) const
void set_filePath (const char *t_newValue)
ParticleOutputMap (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_particle_output_map
uint8_t fileId
The id of the file.
char filePath [64]
The path to the file containing the list of particles.
Detailed Description
Provides a C++ wrapper around wb_particle_output_map.
Definition at line 83 of file ParticleOutputMap.hpp.
Constructor & Destructor Documentation
ParticleOutputMap() [1/4]
guWhiteboard::ParticleOutputMap::ParticleOutputMap (uint8_t t_fileId = 0, std::string t_filePath = "") inline
Create a new ParticleOutputMap.
Definition at line 100 of file ParticleOutputMap.hpp.
Referenced by operator==().
ParticleOutputMap() [2/4]
guWhiteboard::ParticleOutputMap::ParticleOutputMap (const ParticleOutputMap & t_other) inline
Copy Constructor.
Definition at line 107 of file ParticleOutputMap.hpp.
References fileId(), and filePath().
ParticleOutputMap() [3/4]
guWhiteboard::ParticleOutputMap::ParticleOutputMap (const struct wb_particle_output_map & t_other) inline
Copy Constructor.
Definition at line 114 of file ParticleOutputMap.hpp.
References wb_particle_output_map::fileId, and wb_particle_output_map::filePath.
ParticleOutputMap() [4/4]
guWhiteboard::ParticleOutputMap::ParticleOutputMap (const std::string & t_str) inline
String Constructor.
Definition at line 199 of file ParticleOutputMap.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::ParticleOutputMap::description () inline
USE_WB_PARTICLE_OUTPUT_MAP_C_CONVERSION
Definition at line 204 of file ParticleOutputMap.hpp.
References fileId(), filePath(), PARTICLE_OUTPUT_MAP_DESC_BUFFER_SIZE, and wb_particle_output_map_description().
fileId() [1/2]
uint8_t & guWhiteboard::ParticleOutputMap::fileId () inline
Definition at line 155 of file ParticleOutputMap.hpp.
References wb_particle_output_map::fileId.
Referenced by ParticleOutputMap(), description(), operator=(), operator==(), and to_string().
fileId() [2/2]
const uint8_t & guWhiteboard::ParticleOutputMap::fileId () const inline
Definition at line 160 of file ParticleOutputMap.hpp.
References wb_particle_output_map::fileId.
filePath() [1/3]
const char * guWhiteboard::ParticleOutputMap::filePath () const inline
Definition at line 170 of file ParticleOutputMap.hpp.
References wb_particle_output_map::filePath.
Referenced by ParticleOutputMap(), description(), operator=(), operator==(), and to_string().
filePath() [2/3]
char & guWhiteboard::ParticleOutputMap::filePath (int t_i) inline
Definition at line 180 of file ParticleOutputMap.hpp.
References wb_particle_output_map::filePath.
filePath() [3/3]
const char & guWhiteboard::ParticleOutputMap::filePath (int t_i) const inline
Definition at line 185 of file ParticleOutputMap.hpp.
References wb_particle_output_map::filePath.
filePath_size()
size_t guWhiteboard::ParticleOutputMap::filePath_size () const inline
Definition at line 175 of file ParticleOutputMap.hpp.
from_string()
void guWhiteboard::ParticleOutputMap::from_string (const std::string & t_str) inline
USE_WB_PARTICLE_OUTPUT_MAP_C_CONVERSION
Definition at line 246 of file ParticleOutputMap.hpp.
References wb_particle_output_map::filePath, PARTICLE_OUTPUT_MAP_DESC_BUFFER_SIZE, and set_fileId().
Referenced by ParticleOutputMap().
operator!=() [1/2]
bool guWhiteboard::ParticleOutputMap::operator!= (const ParticleOutputMap & t_other) const inline
Definition at line 140 of file ParticleOutputMap.hpp.
operator!=() [2/2]
bool guWhiteboard::ParticleOutputMap::operator!= (const wb_particle_output_map & t_other) const inline
Definition at line 150 of file ParticleOutputMap.hpp.
operator=() [1/2]
ParticleOutputMap & guWhiteboard::ParticleOutputMap::operator= (const ParticleOutputMap & t_other) inline
Copy Assignment Operator.
Definition at line 121 of file ParticleOutputMap.hpp.
References fileId(), and filePath().
operator=() [2/2]
ParticleOutputMap & guWhiteboard::ParticleOutputMap::operator= (const struct wb_particle_output_map & t_other) inline
Copy Assignment Operator.
Definition at line 129 of file ParticleOutputMap.hpp.
References wb_particle_output_map::fileId, and wb_particle_output_map::filePath.
operator==() [1/2]
bool guWhiteboard::ParticleOutputMap::operator== (const ParticleOutputMap & t_other) const inline
Definition at line 134 of file ParticleOutputMap.hpp.
References fileId(), and filePath().
operator==() [2/2]
bool guWhiteboard::ParticleOutputMap::operator== (const wb_particle_output_map & t_other) const inline
Definition at line 145 of file ParticleOutputMap.hpp.
References ParticleOutputMap().
set_fileId()
void guWhiteboard::ParticleOutputMap::set_fileId (const uint8_t & t_newValue) inline
Definition at line 165 of file ParticleOutputMap.hpp.
References wb_particle_output_map::fileId.
Referenced by from_string().
set_filePath()
void guWhiteboard::ParticleOutputMap::set_filePath (const char * t_newValue) inline
Definition at line 190 of file ParticleOutputMap.hpp.
References wb_particle_output_map::filePath.
to_string()
std::string guWhiteboard::ParticleOutputMap::to_string () inline
USE_WB_PARTICLE_OUTPUT_MAP_C_CONVERSION
Definition at line 223 of file ParticleOutputMap.hpp.
References fileId(), filePath(), PARTICLE_OUTPUT_MAP_TO_STRING_BUFFER_SIZE, and wb_particle_output_map_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/ParticleOutputMap.hpp