gusimplewhiteboard: guWhiteboard::FrequencyLimits Class Reference
guWhiteboard::FrequencyLimits Class Reference
Provides a C++ wrapper around wb_frequency_limits.
#include <FrequencyLimits.hpp>
Public Member Functions
FrequencyLimits (int16_t t_lo_freq=0, int16_t t_hi_freq=0)
Create a new FrequencyLimits.
FrequencyLimits (const FrequencyLimits &t_other)
Copy Constructor.
FrequencyLimits (const struct wb_frequency_limits &t_other)
Copy Constructor.
FrequencyLimits & operator= (const FrequencyLimits &t_other)
Copy Assignment Operator.
FrequencyLimits & operator= (const struct wb_frequency_limits &t_other)
Copy Assignment Operator.
bool operator== (const FrequencyLimits &t_other) const
bool operator!= (const FrequencyLimits &t_other) const
bool operator== (const wb_frequency_limits &t_other) const
bool operator!= (const wb_frequency_limits &t_other) const
int16_t & lo_freq ()
const int16_t & lo_freq () const
void set_lo_freq (const int16_t &t_newValue)
int16_t & hi_freq ()
const int16_t & hi_freq () const
void set_hi_freq (const int16_t &t_newValue)
FrequencyLimits (const std::string &t_str)
String Constructor.
std::string description ()
std::string to_string ()
void from_string (const std::string &t_str)
Additional Inherited Members
Public Attributes inherited from wb_frequency_limits
int16_t lo_freq
low frequency bound in Hz
int16_t hi_freq
high frequency bound in Hz
Detailed Description
Provides a C++ wrapper around wb_frequency_limits.
Definition at line 83 of file FrequencyLimits.hpp.
Constructor & Destructor Documentation
FrequencyLimits() [1/4]
guWhiteboard::FrequencyLimits::FrequencyLimits (int16_t t_lo_freq = 0, int16_t t_hi_freq = 0) inline
Create a new FrequencyLimits.
Definition at line 100 of file FrequencyLimits.hpp.
Referenced by operator==().
FrequencyLimits() [2/4]
guWhiteboard::FrequencyLimits::FrequencyLimits (const FrequencyLimits & t_other) inline
Copy Constructor.
Definition at line 107 of file FrequencyLimits.hpp.
References hi_freq(), and lo_freq().
FrequencyLimits() [3/4]
guWhiteboard::FrequencyLimits::FrequencyLimits (const struct wb_frequency_limits & t_other) inline
Copy Constructor.
Definition at line 114 of file FrequencyLimits.hpp.
References wb_frequency_limits::hi_freq, and wb_frequency_limits::lo_freq.
FrequencyLimits() [4/4]
guWhiteboard::FrequencyLimits::FrequencyLimits (const std::string & t_str) inline
String Constructor.
Definition at line 189 of file FrequencyLimits.hpp.
References from_string().
Member Function Documentation
description()
std::string guWhiteboard::FrequencyLimits::description () inline
USE_WB_FREQUENCY_LIMITS_C_CONVERSION
Definition at line 194 of file FrequencyLimits.hpp.
References FREQUENCY_LIMITS_DESC_BUFFER_SIZE, hi_freq(), lo_freq(), and wb_frequency_limits_description().
from_string()
void guWhiteboard::FrequencyLimits::from_string (const std::string & t_str) inline
USE_WB_FREQUENCY_LIMITS_C_CONVERSION
Definition at line 228 of file FrequencyLimits.hpp.
References FREQUENCY_LIMITS_DESC_BUFFER_SIZE, set_hi_freq(), and set_lo_freq().
Referenced by FrequencyLimits().
hi_freq() [1/2]
int16_t & guWhiteboard::FrequencyLimits::hi_freq () inline
Definition at line 170 of file FrequencyLimits.hpp.
References wb_frequency_limits::hi_freq.
Referenced by FrequencyLimits(), description(), operator=(), operator==(), and to_string().
hi_freq() [2/2]
const int16_t & guWhiteboard::FrequencyLimits::hi_freq () const inline
Definition at line 175 of file FrequencyLimits.hpp.
References wb_frequency_limits::hi_freq.
lo_freq() [1/2]
int16_t & guWhiteboard::FrequencyLimits::lo_freq () inline
Definition at line 155 of file FrequencyLimits.hpp.
References wb_frequency_limits::lo_freq.
Referenced by FrequencyLimits(), description(), operator=(), operator==(), and to_string().
lo_freq() [2/2]
const int16_t & guWhiteboard::FrequencyLimits::lo_freq () const inline
Definition at line 160 of file FrequencyLimits.hpp.
References wb_frequency_limits::lo_freq.
operator!=() [1/2]
bool guWhiteboard::FrequencyLimits::operator!= (const FrequencyLimits & t_other) const inline
Definition at line 140 of file FrequencyLimits.hpp.
operator!=() [2/2]
bool guWhiteboard::FrequencyLimits::operator!= (const wb_frequency_limits & t_other) const inline
Definition at line 150 of file FrequencyLimits.hpp.
operator=() [1/2]
FrequencyLimits & guWhiteboard::FrequencyLimits::operator= (const FrequencyLimits & t_other) inline
Copy Assignment Operator.
Definition at line 121 of file FrequencyLimits.hpp.
References hi_freq(), and lo_freq().
operator=() [2/2]
FrequencyLimits & guWhiteboard::FrequencyLimits::operator= (const struct wb_frequency_limits & t_other) inline
Copy Assignment Operator.
Definition at line 129 of file FrequencyLimits.hpp.
References wb_frequency_limits::hi_freq, and wb_frequency_limits::lo_freq.
operator==() [1/2]
bool guWhiteboard::FrequencyLimits::operator== (const FrequencyLimits & t_other) const inline
Definition at line 134 of file FrequencyLimits.hpp.
References hi_freq(), and lo_freq().
operator==() [2/2]
bool guWhiteboard::FrequencyLimits::operator== (const wb_frequency_limits & t_other) const inline
Definition at line 145 of file FrequencyLimits.hpp.
References FrequencyLimits().
set_hi_freq()
void guWhiteboard::FrequencyLimits::set_hi_freq (const int16_t & t_newValue) inline
Definition at line 180 of file FrequencyLimits.hpp.
References wb_frequency_limits::hi_freq.
Referenced by from_string().
set_lo_freq()
void guWhiteboard::FrequencyLimits::set_lo_freq (const int16_t & t_newValue) inline
Definition at line 165 of file FrequencyLimits.hpp.
References wb_frequency_limits::lo_freq.
Referenced by from_string().
to_string()
std::string guWhiteboard::FrequencyLimits::to_string () inline
USE_WB_FREQUENCY_LIMITS_C_CONVERSION
Definition at line 209 of file FrequencyLimits.hpp.
References FREQUENCY_LIMITS_TO_STRING_BUFFER_SIZE, hi_freq(), lo_freq(), and wb_frequency_limits_to_string().
The documentation for this class was generated from the following file:
typeClassDefs/FrequencyLimits.hpp