var files_dup =
[
    [ "OLD_WB", "dir_8586e4be6f2c8251dbbd5b06374d1461.html", "dir_8586e4be6f2c8251dbbd5b06374d1461" ],
    [ "SimpleWhiteboardTest", "dir_6f143ac8e1d12b93266fd7f7d204f783.html", "dir_6f143ac8e1d12b93266fd7f7d204f783" ],
    [ "typeClassDefs", "dir_51718dde5e26cb2a1131708db381cfe6.html", "dir_51718dde5e26cb2a1131708db381cfe6" ],
    [ "wbPerfTests", "dir_0ba5cddfffcf11bcafd763698ebda9bc.html", "dir_0ba5cddfffcf11bcafd763698ebda9bc" ],
    [ "gugenericwhiteboardobject.cpp", "gugenericwhiteboardobject_8cpp.html", null ],
    [ "gugenericwhiteboardobject.h", "gugenericwhiteboardobject_8h.html", "gugenericwhiteboardobject_8h" ],
    [ "gusimplewhiteboard.c", "gusimplewhiteboard_8c.html", "gusimplewhiteboard_8c" ],
    [ "gusimplewhiteboard.h", "gusimplewhiteboard_8h.html", "gusimplewhiteboard_8h" ],
    [ "guwhiteboard_c_types.h", "guwhiteboard__c__types_8h.html", null ],
    [ "guwhiteboard_c_types_manual_definitions.h", "guwhiteboard__c__types__manual__definitions_8h.html", null ],
    [ "guWhiteboard_gugenericwhiteboardobject.cpp", "gu_whiteboard__gugenericwhiteboardobject_8cpp.html", "gu_whiteboard__gugenericwhiteboardobject_8cpp" ],
    [ "guWhiteboard_gugenericwhiteboardobject.h", "gu_whiteboard__gugenericwhiteboardobject_8h.html", "gu_whiteboard__gugenericwhiteboardobject_8h" ],
    [ "guwhiteboarddeserialiser.c", "guwhiteboarddeserialiser_8c.html", "guwhiteboarddeserialiser_8c" ],
    [ "guwhiteboardgetter.cpp", "guwhiteboardgetter_8cpp.html", "guwhiteboardgetter_8cpp" ],
    [ "guwhiteboardgetter.h", "guwhiteboardgetter_8h.html", "guwhiteboardgetter_8h" ],
    [ "guwhiteboardposter.cpp", "guwhiteboardposter_8cpp.html", "guwhiteboardposter_8cpp" ],
    [ "guwhiteboardposter.h", "guwhiteboardposter_8h.html", "guwhiteboardposter_8h" ],
    [ "guwhiteboardserialisation.h", "guwhiteboardserialisation_8h.html", "guwhiteboardserialisation_8h" ],
    [ "guwhiteboardserialiser.c", "guwhiteboardserialiser_8c.html", "guwhiteboardserialiser_8c" ],
    [ "guwhiteboardtypelist_c_generated.h", "guwhiteboardtypelist__c__generated_8h.html", "guwhiteboardtypelist__c__generated_8h" ],
    [ "guwhiteboardtypelist_c_generated_default.h", "guwhiteboardtypelist__c__generated__default_8h.html", "guwhiteboardtypelist__c__generated__default_8h" ],
    [ "guwhiteboardtypelist_c_typestrings_generated.c", "guwhiteboardtypelist__c__typestrings__generated_8c.html", "guwhiteboardtypelist__c__typestrings__generated_8c" ],
    [ "guwhiteboardtypelist_c_typestrings_generated_default.c", "guwhiteboardtypelist__c__typestrings__generated__default_8c.html", "guwhiteboardtypelist__c__typestrings__generated__default_8c" ],
    [ "guwhiteboardtypelist_generated.h", "guwhiteboardtypelist__generated_8h.html", "guwhiteboardtypelist__generated_8h" ],
    [ "guwhiteboardwatcher.h", "guwhiteboardwatcher_8h.html", "guwhiteboardwatcher_8h" ],
    [ "libgusimplewhiteboardmain.cc", "libgusimplewhiteboardmain_8cc.html", "libgusimplewhiteboardmain_8cc" ],
    [ "WBFunctor.h", "_w_b_functor_8h.html", "_w_b_functor_8h" ],
    [ "WBFunctor_types_generated.h", "_w_b_functor__types__generated_8h.html", [
      [ "wb_reserved_SubscribeToAllTypes_WBFunctor< wb_reserved_SubscribeToAllTypes_WBFunctor_T >", "classwb__reserved___subscribe_to_all_types___w_b_functor.html", "classwb__reserved___subscribe_to_all_types___w_b_functor" ],
      [ "Print_WBFunctor< Print_WBFunctor_T >", "class_print___w_b_functor.html", "class_print___w_b_functor" ],
      [ "Say_WBFunctor< Say_WBFunctor_T >", "class_say___w_b_functor.html", "class_say___w_b_functor" ],
      [ "Speech_WBFunctor< Speech_WBFunctor_T >", "class_speech___w_b_functor.html", "class_speech___w_b_functor" ],
      [ "QSay_WBFunctor< QSay_WBFunctor_T >", "class_q_say___w_b_functor.html", "class_q_say___w_b_functor" ],
      [ "QSpeech_WBFunctor< QSpeech_WBFunctor_T >", "class_q_speech___w_b_functor.html", "class_q_speech___w_b_functor" ],
      [ "SpeechOutput_WBFunctor< SpeechOutput_WBFunctor_T >", "class_speech_output___w_b_functor.html", "class_speech_output___w_b_functor" ],
      [ "SoloTypeExample_WBFunctor< SoloTypeExample_WBFunctor_T >", "class_solo_type_example___w_b_functor.html", "class_solo_type_example___w_b_functor" ],
      [ "PlayerNumber_WBFunctor< PlayerNumber_WBFunctor_T >", "class_player_number___w_b_functor.html", "class_player_number___w_b_functor" ],
      [ "ManuallyPenalized_WBFunctor< ManuallyPenalized_WBFunctor_T >", "class_manually_penalized___w_b_functor.html", "class_manually_penalized___w_b_functor" ],
      [ "PF_ControlStatus_Modes_WBFunctor< PF_ControlStatus_Modes_WBFunctor_T >", "class_p_f___control_status___modes___w_b_functor.html", "class_p_f___control_status___modes___w_b_functor" ],
      [ "TeleoperationConnection_WBFunctor< TeleoperationConnection_WBFunctor_T >", "class_teleoperation_connection___w_b_functor.html", "class_teleoperation_connection___w_b_functor" ],
      [ "UDPWBNumber_WBFunctor< UDPWBNumber_WBFunctor_T >", "class_u_d_p_w_b_number___w_b_functor.html", "class_u_d_p_w_b_number___w_b_functor" ],
      [ "VisionFace_WBFunctor< VisionFace_WBFunctor_T >", "class_vision_face___w_b_functor.html", "class_vision_face___w_b_functor" ],
      [ "Draw_WBFunctor< Draw_WBFunctor_T >", "class_draw___w_b_functor.html", "class_draw___w_b_functor" ],
      [ "REMOVED3_WBFunctor< REMOVED3_WBFunctor_T >", "class_r_e_m_o_v_e_d3___w_b_functor.html", "class_r_e_m_o_v_e_d3___w_b_functor" ],
      [ "REMOVED4_WBFunctor< REMOVED4_WBFunctor_T >", "class_r_e_m_o_v_e_d4___w_b_functor.html", "class_r_e_m_o_v_e_d4___w_b_functor" ],
      [ "CBall_WBFunctor< CBall_WBFunctor_T >", "class_c_ball___w_b_functor.html", "class_c_ball___w_b_functor" ],
      [ "GreenEWon_WBFunctor< GreenEWon_WBFunctor_T >", "class_green_e_won___w_b_functor.html", "class_green_e_won___w_b_functor" ],
      [ "WarnEW_WBFunctor< WarnEW_WBFunctor_T >", "class_warn_e_w___w_b_functor.html", "class_warn_e_w___w_b_functor" ],
      [ "TimeGTthirty_WBFunctor< TimeGTthirty_WBFunctor_T >", "class_time_g_tthirty___w_b_functor.html", "class_time_g_tthirty___w_b_functor" ],
      [ "AmberEWon_WBFunctor< AmberEWon_WBFunctor_T >", "class_amber_e_won___w_b_functor.html", "class_amber_e_won___w_b_functor" ],
      [ "TurnRedEW_WBFunctor< TurnRedEW_WBFunctor_T >", "class_turn_red_e_w___w_b_functor.html", "class_turn_red_e_w___w_b_functor" ],
      [ "TimeGTfive_WBFunctor< TimeGTfive_WBFunctor_T >", "class_time_g_tfive___w_b_functor.html", "class_time_g_tfive___w_b_functor" ],
      [ "RedEWon_WBFunctor< RedEWon_WBFunctor_T >", "class_red_e_won___w_b_functor.html", "class_red_e_won___w_b_functor" ],
      [ "GreenNSon_WBFunctor< GreenNSon_WBFunctor_T >", "class_green_n_son___w_b_functor.html", "class_green_n_son___w_b_functor" ],
      [ "WarnNS_WBFunctor< WarnNS_WBFunctor_T >", "class_warn_n_s___w_b_functor.html", "class_warn_n_s___w_b_functor" ],
      [ "AmberNSon_WBFunctor< AmberNSon_WBFunctor_T >", "class_amber_n_son___w_b_functor.html", "class_amber_n_son___w_b_functor" ],
      [ "TurnRedNS_WBFunctor< TurnRedNS_WBFunctor_T >", "class_turn_red_n_s___w_b_functor.html", "class_turn_red_n_s___w_b_functor" ],
      [ "RedNSon_WBFunctor< RedNSon_WBFunctor_T >", "class_red_n_son___w_b_functor.html", "class_red_n_son___w_b_functor" ],
      [ "TimerReset_WBFunctor< TimerReset_WBFunctor_T >", "class_timer_reset___w_b_functor.html", "class_timer_reset___w_b_functor" ],
      [ "SLOT_UNUSED_WBFunctor< SLOT_UNUSED_WBFunctor_T >", "class_s_l_o_t___u_n_u_s_e_d___w_b_functor.html", "class_s_l_o_t___u_n_u_s_e_d___w_b_functor" ],
      [ "CarSensorPressed_WBFunctor< CarSensorPressed_WBFunctor_T >", "class_car_sensor_pressed___w_b_functor.html", "class_car_sensor_pressed___w_b_functor" ],
      [ "Ball_Found_WBFunctor< Ball_Found_WBFunctor_T >", "class_ball___found___w_b_functor.html", "class_ball___found___w_b_functor" ],
      [ "Ball_Calibration_File_WBFunctor< Ball_Calibration_File_WBFunctor_T >", "class_ball___calibration___file___w_b_functor.html", "class_ball___calibration___file___w_b_functor" ],
      [ "Ball_Calibration_Num_WBFunctor< Ball_Calibration_Num_WBFunctor_T >", "class_ball___calibration___num___w_b_functor.html", "class_ball___calibration___num___w_b_functor" ],
      [ "Ball_Color_Num_WBFunctor< Ball_Color_Num_WBFunctor_T >", "class_ball___color___num___w_b_functor.html", "class_ball___color___num___w_b_functor" ],
      [ "WhistleBlown_WBFunctor< WhistleBlown_WBFunctor_T >", "class_whistle_blown___w_b_functor.html", "class_whistle_blown___w_b_functor" ],
      [ "VolumeControl_WBFunctor< VolumeControl_WBFunctor_T >", "class_volume_control___w_b_functor.html", "class_volume_control___w_b_functor" ],
      [ "ParticleOutputMap_WBFunctor< ParticleOutputMap_WBFunctor_T >", "class_particle_output_map___w_b_functor.html", "class_particle_output_map___w_b_functor" ],
      [ "ParticleOutputMapControl_WBFunctor< ParticleOutputMapControl_WBFunctor_T >", "class_particle_output_map_control___w_b_functor.html", "class_particle_output_map_control___w_b_functor" ],
      [ "FFTControl_WBFunctor< FFTControl_WBFunctor_T >", "class_f_f_t_control___w_b_functor.html", "class_f_f_t_control___w_b_functor" ],
      [ "WavLoad_WBFunctor< WavLoad_WBFunctor_T >", "class_wav_load___w_b_functor.html", "class_wav_load___w_b_functor" ],
      [ "WavPlay_WBFunctor< WavPlay_WBFunctor_T >", "class_wav_play___w_b_functor.html", "class_wav_play___w_b_functor" ],
      [ "ReproduceWavNotSilent_WBFunctor< ReproduceWavNotSilent_WBFunctor_T >", "class_reproduce_wav_not_silent___w_b_functor.html", "class_reproduce_wav_not_silent___w_b_functor" ],
      [ "buttonPushed_WBFunctor< buttonPushed_WBFunctor_T >", "classbutton_pushed___w_b_functor.html", "classbutton_pushed___w_b_functor" ],
      [ "doorOpen_WBFunctor< doorOpen_WBFunctor_T >", "classdoor_open___w_b_functor.html", "classdoor_open___w_b_functor" ],
      [ "timeLeft_WBFunctor< timeLeft_WBFunctor_T >", "classtime_left___w_b_functor.html", "classtime_left___w_b_functor" ],
      [ "motor_WBFunctor< motor_WBFunctor_T >", "classmotor___w_b_functor.html", "classmotor___w_b_functor" ],
      [ "sound_WBFunctor< sound_WBFunctor_T >", "classsound___w_b_functor.html", "classsound___w_b_functor" ],
      [ "light_WBFunctor< light_WBFunctor_T >", "classlight___w_b_functor.html", "classlight___w_b_functor" ],
      [ "Arduino2Pin_WBFunctor< Arduino2Pin_WBFunctor_T >", "class_arduino2_pin___w_b_functor.html", "class_arduino2_pin___w_b_functor" ],
      [ "Arduino2PinValue_WBFunctor< Arduino2PinValue_WBFunctor_T >", "class_arduino2_pin_value___w_b_functor.html", "class_arduino2_pin_value___w_b_functor" ],
      [ "Arduino3Pin_WBFunctor< Arduino3Pin_WBFunctor_T >", "class_arduino3_pin___w_b_functor.html", "class_arduino3_pin___w_b_functor" ],
      [ "Arduino3PinValue_WBFunctor< Arduino3PinValue_WBFunctor_T >", "class_arduino3_pin_value___w_b_functor.html", "class_arduino3_pin_value___w_b_functor" ],
      [ "Arduino4Pin_WBFunctor< Arduino4Pin_WBFunctor_T >", "class_arduino4_pin___w_b_functor.html", "class_arduino4_pin___w_b_functor" ],
      [ "Arduino4PinValue_WBFunctor< Arduino4PinValue_WBFunctor_T >", "class_arduino4_pin_value___w_b_functor.html", "class_arduino4_pin_value___w_b_functor" ],
      [ "Arduino5Pin_WBFunctor< Arduino5Pin_WBFunctor_T >", "class_arduino5_pin___w_b_functor.html", "class_arduino5_pin___w_b_functor" ],
      [ "Arduino5PinValue_WBFunctor< Arduino5PinValue_WBFunctor_T >", "class_arduino5_pin_value___w_b_functor.html", "class_arduino5_pin_value___w_b_functor" ],
      [ "Arduino6Pin_WBFunctor< Arduino6Pin_WBFunctor_T >", "class_arduino6_pin___w_b_functor.html", "class_arduino6_pin___w_b_functor" ],
      [ "Arduino6PinValue_WBFunctor< Arduino6PinValue_WBFunctor_T >", "class_arduino6_pin_value___w_b_functor.html", "class_arduino6_pin_value___w_b_functor" ],
      [ "Arduino7Pin_WBFunctor< Arduino7Pin_WBFunctor_T >", "class_arduino7_pin___w_b_functor.html", "class_arduino7_pin___w_b_functor" ],
      [ "Arduino7PinValue_WBFunctor< Arduino7PinValue_WBFunctor_T >", "class_arduino7_pin_value___w_b_functor.html", "class_arduino7_pin_value___w_b_functor" ],
      [ "Arduino8Pin_WBFunctor< Arduino8Pin_WBFunctor_T >", "class_arduino8_pin___w_b_functor.html", "class_arduino8_pin___w_b_functor" ],
      [ "Arduino8PinValue_WBFunctor< Arduino8PinValue_WBFunctor_T >", "class_arduino8_pin_value___w_b_functor.html", "class_arduino8_pin_value___w_b_functor" ],
      [ "Arduino9Pin_WBFunctor< Arduino9Pin_WBFunctor_T >", "class_arduino9_pin___w_b_functor.html", "class_arduino9_pin___w_b_functor" ],
      [ "Arduino9PinValue_WBFunctor< Arduino9PinValue_WBFunctor_T >", "class_arduino9_pin_value___w_b_functor.html", "class_arduino9_pin_value___w_b_functor" ],
      [ "LHandGripper_WBFunctor< LHandGripper_WBFunctor_T >", "class_l_hand_gripper___w_b_functor.html", "class_l_hand_gripper___w_b_functor" ],
      [ "RHandGripper_WBFunctor< RHandGripper_WBFunctor_T >", "class_r_hand_gripper___w_b_functor.html", "class_r_hand_gripper___w_b_functor" ]
    ] ]
];