gusimplewhiteboard: guwhiteboardposter.h File Reference
guwhiteboardposter.h File Reference
#include <string>
#include <map>
#include <stdbool.h>
#include "GCGameState.hpp"
#include "SensorsHandSensors.hpp"
#include "SensorsHeadSensors.hpp"
#include "MOTION_Commands.hpp"
#include "MOTION_Status.hpp"
#include "HAL_HeadTarget.hpp"
#include "SensorsFootSensors.hpp"
#include "SensorsBodySensors.hpp"
#include "SENSORSLedsSensors.hpp"
#include "SENSORSLegJointTemps.hpp"
#include "SENSORSTorsoJointTemps.hpp"
#include "SENSORSLegJointSensors.hpp"
#include "SENSORSTorsoJointSensors.hpp"
#include "SENSORSSonarSensors.hpp"
#include "FSMControlStatus.hpp"
#include "FSMNames.hpp"
#include "FilteredArrayOneDimObjects.hpp"
#include "NAO_State.hpp"
#include "VisionControlStatus.hpp"
#include "FFTStatus.hpp"
#include "FilteredArrayOneDimSonar.hpp"
#include "TopParticles.hpp"
#include "FilteredArrayBallSightings.hpp"
#include "WEBOTS_NXT_bridge.hpp"
#include "WEBOTS_NXT_encoders.hpp"
#include "WEBOTS_NXT_camera.hpp"
#include "WEBOTS_NXT_walk_isRunning.hpp"
#include "WEBOTS_NXT_deadReakoning_walk.hpp"
#include "WEBOTS_NXT_colorLine_walk.hpp"
#include "WEBOTS_NXT_gridMotions.hpp"
#include "VisionBall.hpp"
#include "VisionGoals.hpp"
#include "WalkData.hpp"
#include "TeleoperationControlStatus.hpp"
#include "WEBOTS_NXT_bumper.hpp"
#include "WEBOTS_NXT_vector_bridge.hpp"
#include "VisionLines.hpp"
#include "DifferentialRobotControlStatus.hpp"
#include "Point2D.hpp"
#include "FSMState.hpp"
#include "Giraff_MainSerialInterface.hpp"
#include "NXT_Interface.hpp"
#include "APM_Interface.hpp"
#include "OculusPrimeInterface.hpp"
#include "Input3D.hpp"
#include "Oculus_PrimeSerialInterface.hpp"
#include "IOPins.hpp"
#include "NXT_Two_Touch_Status.hpp"
#include "NXT_Sound_Control.hpp"
#include "NXT_Lights_Control.hpp"
#include "Clocks.hpp"
#include "Channels.hpp"
#include "SwitchSubsumption.hpp"
#include "TotoDoingMotion.hpp"
#include "Count.hpp"
#include "SwitchSubsumptionTrafficLights.hpp"
#include "HalArmTarget.hpp"
#include "VisionFieldFeatures.hpp"
#include "VisionRobots.hpp"
#include "VisionDetectionHorizons.hpp"
#include "NaoWalkCommand.hpp"
#include "NaoWalkStatus.hpp"
#include "HalLegTarget.hpp"
#include "VisionDetectionGoals.hpp"
#include "TeleoperationControl.hpp"
#include "TeleoperationStatus.hpp"
#include "VisionDetectionBalls.hpp"
#include "TeleoperationControlVR.hpp"
#include "MachineFilteredVision.hpp"
#include "MicrowaveStatus.hpp"
#include "Buttons.hpp"
#include "MachineFilteredLocalisationVision.hpp"
#include "NaoJointListFloat.hpp"
#include "DataLogger.hpp"
#include "MachineFilteredLines.hpp"
#include "Location.hpp"
#include "NaoSonarProtectedWalkCommand.hpp"
#include "NaoObstacleDirection.hpp"
#include "DominantFrequencies.hpp"
#include "MissionPriorityForObstacles.hpp"
#include "FrequencyLimits.hpp"
#include "HeadJointSensors.hpp"
#include "AdjustPositionConfidence.hpp"
#include "GuVrTeleopVulkanControl.hpp"
#include "TemperatureSensors.hpp"
#include "Overheating.hpp"
#include "BallPosition.hpp"
#include "MemoryImageControlStatus.hpp"
#include "MyPosition.hpp"
#include "VisionDetectionLines.hpp"
#include "VisionDetectionFeatures.hpp"
#include "gusimplewhiteboard.h"
#include "guwhiteboardtypelist_c_generated.h"
Classes
struct guWhiteboard::whiteboard_types_map
Map structure from strings to message types.
Namespaces
namespace guWhiteboard
/file APM_Interface.h
Functions
bool whiteboard_post (const char *message_type, const char *message_content)
/file guwhiteboardposter.h
bool whiteboard_post_to (gu_simple_whiteboard_descriptor *wbd, const char *message_type, const char *message_content)
A generic C function that posts to a given whiteboard.
bool whiteboard_postmsg (int message_index, const char *message_content)
Generic C function that posts a message with a given message number to the whiteboard.
bool whiteboard_postmsg_to (gu_simple_whiteboard_descriptor *wbd, int message_index, const char *message_content)
Generic C function that posts a message with a given message number to a given whiteboard.
guWhiteboard::wb_types whiteboard_type_for_message_named (const char *message_type)
Generic C function that returns the type for a given message name.
bool guWhiteboard::post (std::string message_type, std::string message_content, gu_simple_whiteboard_descriptor *wbd=NULLPTR)
A generic C++ function that posts to the whiteboard.
bool guWhiteboard::postmsg (guWhiteboard::wb_types message_index, std::string message_content, gu_simple_whiteboard_descriptor *wbd=NULLPTR)
Generic C++ function that posts a message with a given message number to the whiteboard.
Variables
struct whiteboard_types_map guWhiteboard::types_map
Global map from names to message types.
Function Documentation
whiteboard_post()
bool whiteboard_post (const char * message_type, const char * message_content)
/file guwhiteboardposter.h
Created by Carl Lusty in 2018. Copyright (c) 2013-2020 Carl Lusty and Rene Hexel All rights reserved. Auto-generated, don't modify! A generic C function that posts to the whiteboard. Both the message type and the message content are strings.
Definition at line 33 of file guwhiteboardposter.cpp.
References guWhiteboard::types_map, and whiteboard_postmsg().
whiteboard_post_to()
bool whiteboard_post_to (gu_simple_whiteboard_descriptor * wbd, const char * message_type, const char * message_content)
A generic C function that posts to a given whiteboard.
Both the message type and the message content are strings.
Definition at line 38 of file guwhiteboardposter.cpp.
References guWhiteboard::types_map, and whiteboard_postmsg_to().
whiteboard_postmsg()
bool whiteboard_postmsg (int message_index, const char * message_content)
Generic C function that posts a message with a given message number to the whiteboard.
Definition at line 43 of file guwhiteboardposter.cpp.
References guWhiteboard::postmsg().
Referenced by whiteboard_post().
whiteboard_postmsg_to()
bool whiteboard_postmsg_to (gu_simple_whiteboard_descriptor * wbd, int message_index, const char * message_content)
Generic C function that posts a message with a given message number to a given whiteboard.
Definition at line 48 of file guwhiteboardposter.cpp.
References guWhiteboard::postmsg().
Referenced by whiteboard_post_to().
whiteboard_type_for_message_named()
guWhiteboard::wb_types whiteboard_type_for_message_named (const char * message_type)
Generic C function that returns the type for a given message name.
Definition at line 28 of file guwhiteboardposter.cpp.
References guWhiteboard::types_map.