gusimplewhiteboard: guwhiteboardgetter.cpp File Reference
guwhiteboardgetter.cpp File Reference
#include <string>
#include <sstream>
#include <vector>
#include <cstdlib>
#include <gu_util.h>
#include "guwhiteboardtypelist_generated.h"
#include "guwhiteboardgetter.h"
Namespaces
namespace guWhiteboard
/file APM_Interface.h
Macros
#define WHITEBOARD_POSTER_STRING_CONVERSION
/file guwhiteboardgetter.cpp
Functions
char * whiteboard_get (const char *message_type, gu_simple_message *msg)
/file guwhiteboardgetter.h
char * whiteboard_get_from (gu_simple_whiteboard_descriptor *wbd, const char *message_type)
A generic C function that gets a message from the given whiteboard.
char * whiteboard_getmsg (int message_index, gu_simple_message *msg)
Generic C function that gets a message with a given message number from the whiteboard.
char * whiteboard_getmsg_from (gu_simple_whiteboard_descriptor *wbd, int message_index)
Generic C function that gets a message with a given message number from the given whiteboard.
string guWhiteboard::getmsg (std::string message_type, gu_simple_message *msg=NULLPTR, gu_simple_whiteboard_descriptor *wbd=NULLPTR)
A generic C++ function that gets a string from the whiteboard.
string guWhiteboard::getmsg (wb_types message_index, gu_simple_message *msg, gu_simple_whiteboard_descriptor *wbd)
Macro Definition Documentation
WHITEBOARD_POSTER_STRING_CONVERSION
#define WHITEBOARD_POSTER_STRING_CONVERSION
/file guwhiteboardgetter.cpp
Created by Carl Lusty in 2018. Copyright (c) 2013-2020 Carl Lusty and Rene Hexel All rights reserved. Auto-generated, don't modify!
Definition at line 19 of file guwhiteboardgetter.cpp.
Function Documentation
whiteboard_get()
char * whiteboard_get (const char * message_type, gu_simple_message * msg)
/file guwhiteboardgetter.h
Created by Carl Lusty in 2018. Copyright (c) 2013-2020 Carl Lusty and Rene Hexel All rights reserved. Auto-generated, don't modify! A generic C function that gets a message from the whiteboard. Both the message type and the message content are strings. The returned message string has to be freed!
Definition at line 33 of file guwhiteboardgetter.cpp.
References guWhiteboard::types_map, and whiteboard_getmsg().
whiteboard_get_from()
char * whiteboard_get_from (gu_simple_whiteboard_descriptor * wbd, const char * message_type)
A generic C function that gets a message from the given whiteboard.
Both the message type and the message content are strings. The returned message string has to be freed!
Definition at line 38 of file guwhiteboardgetter.cpp.
References guWhiteboard::types_map, and whiteboard_getmsg_from().
whiteboard_getmsg()
char * whiteboard_getmsg (int message_index, gu_simple_message * msg)
Generic C function that gets a message with a given message number from the whiteboard.
The returned message string has to be freed!
Definition at line 43 of file guwhiteboardgetter.cpp.
References guWhiteboard::getmsg().
Referenced by whiteboard_get().
whiteboard_getmsg_from()
char * whiteboard_getmsg_from (gu_simple_whiteboard_descriptor * wbd, int message_index)
Generic C function that gets a message with a given message number from the given whiteboard.
The returned message string has to be freed!
Definition at line 48 of file guwhiteboardgetter.cpp.
References guWhiteboard::getmsg().
Referenced by whiteboard_get_from().