gusimplewhiteboard: guwhiteboardposter.cpp File Reference
guwhiteboardposter.cpp File Reference
#include <string>
#include <vector>
#include <cstdlib>
#include "guwhiteboardtypelist_generated.h"
#include "guwhiteboardposter.h"
Namespaces
namespace guWhiteboard
/file APM_Interface.h
Macros
#define WHITEBOARD_POSTER_STRING_CONVERSION
/file guwhiteboardposter.cpp
Functions
wb_types whiteboard_type_for_message_named (const char *message_type)
Generic C function that returns the type for a given message name.
bool whiteboard_post (const char *message_type, const char *message_content)
/file guwhiteboardposter.h
bool whiteboard_post_to (gu_simple_whiteboard_descriptor *wbd, const char *message_type, const char *message_content)
A generic C function that posts to a given whiteboard.
bool whiteboard_postmsg (int message_index, const char *message_content)
Generic C function that posts a message with a given message number to the whiteboard.
bool whiteboard_postmsg_to (gu_simple_whiteboard_descriptor *wbd, int message_index, const char *message_content)
Generic C function that posts a message with a given message number to a given whiteboard.
bool guWhiteboard::post (std::string message_type, std::string message_content, gu_simple_whiteboard_descriptor *wbd=NULLPTR)
A generic C++ function that posts to the whiteboard.
bool guWhiteboard::postmsg (wb_types message_index, std::string message_content, gu_simple_whiteboard_descriptor *wbd)
Macro Definition Documentation
WHITEBOARD_POSTER_STRING_CONVERSION
#define WHITEBOARD_POSTER_STRING_CONVERSION
/file guwhiteboardposter.cpp
Created by Carl Lusty in 2018. Copyright (c) 2013-2020 Carl Lusty and Rene Hexel All rights reserved. Auto-generated, don't modify!
Definition at line 17 of file guwhiteboardposter.cpp.
Function Documentation
whiteboard_post()
bool whiteboard_post (const char * message_type, const char * message_content)
/file guwhiteboardposter.h
Created by Carl Lusty in 2018. Copyright (c) 2013-2020 Carl Lusty and Rene Hexel All rights reserved. Auto-generated, don't modify! A generic C function that posts to the whiteboard. Both the message type and the message content are strings.
Definition at line 33 of file guwhiteboardposter.cpp.
References guWhiteboard::types_map, and whiteboard_postmsg().
whiteboard_post_to()
bool whiteboard_post_to (gu_simple_whiteboard_descriptor * wbd, const char * message_type, const char * message_content)
A generic C function that posts to a given whiteboard.
Both the message type and the message content are strings.
Definition at line 38 of file guwhiteboardposter.cpp.
References guWhiteboard::types_map, and whiteboard_postmsg_to().
whiteboard_postmsg()
bool whiteboard_postmsg (int message_index, const char * message_content)
Generic C function that posts a message with a given message number to the whiteboard.
Definition at line 43 of file guwhiteboardposter.cpp.
References guWhiteboard::postmsg().
Referenced by whiteboard_post().
whiteboard_postmsg_to()
bool whiteboard_postmsg_to (gu_simple_whiteboard_descriptor * wbd, int message_index, const char * message_content)
Generic C function that posts a message with a given message number to a given whiteboard.
Definition at line 48 of file guwhiteboardposter.cpp.
References guWhiteboard::postmsg().
Referenced by whiteboard_post_to().
whiteboard_type_for_message_named()
wb_types whiteboard_type_for_message_named (const char * message_type)
Generic C function that returns the type for a given message name.
Definition at line 28 of file guwhiteboardposter.cpp.
References guWhiteboard::types_map.