gusimplewhiteboard: wb_dominant_frequencies Struct Reference
wb_dominant_frequencies Struct Reference
Frequency quadruple for rear and front stereo channels.
#include <wb_dominant_frequencies.h>
Public Attributes
struct wb_r_m_s_levels rms
RMS levels of dominant frequency.
struct wb_microphone_frequencies frequencies [static_cast< int >(((GU_SIMPLE_WHITEBOARD_BUFSIZE - sizeof(struct wb_r_m_s_levels))/sizeof(struct wb_microphone_frequencies)))]
dominant frequencies
Detailed Description
Frequency quadruple for rear and front stereo channels.
Definition at line 118 of file wb_dominant_frequencies.h.
Member Data Documentation
frequencies
struct wb_microphone_frequencies wb_dominant_frequencies::frequencies[ static_cast< int >(((GU_SIMPLE_WHITEBOARD_BUFSIZE - sizeof(struct wb_r_m_s_levels))/sizeof(struct wb_microphone_frequencies)))]
dominant frequencies
Definition at line 129 of file wb_dominant_frequencies.h.
Referenced by guWhiteboard::DominantFrequencies::DominantFrequencies(), guWhiteboard::DominantFrequencies::frequencies(), guWhiteboard::DominantFrequencies::operator=(), guWhiteboard::DominantFrequencies::set_frequencies(), and wb_dominant_frequencies_from_network_serialised().
rms
struct wb_r_m_s_levels wb_dominant_frequencies::rms
RMS levels of dominant frequency.
Definition at line 124 of file wb_dominant_frequencies.h.
Referenced by guWhiteboard::DominantFrequencies::DominantFrequencies(), guWhiteboard::DominantFrequencies::operator=(), guWhiteboard::DominantFrequencies::rms(), and guWhiteboard::DominantFrequencies::set_rms().
The documentation for this struct was generated from the following file:
typeClassDefs/wb_dominant_frequencies.h