gusimplewhiteboard: gsw_simple_message Union Reference
gsw_simple_message Union Reference
union type that is used to store data in shared memory
#include <gusimplewhiteboard.h>
Public Attributes
unsigned long long ulonglong
unsigned long long value
long long slonglong
long long value
unsigned long ulong
unsigned long value
long slong
singed long value
unsigned uint
unsigned integer
int sint
signed integer
unsigned short ushort
unsigned short
short sshort
signed short
unsigned char uchar
unsigned char
signed char schar
signed char
char xchar
standard char
long double slongdouble
long double
double sdouble
signed double
float sfloat
signed float
uint64_t u64
unsigned 64 bit value
uint32_t u32
unsigned 32 bit value
uint16_t u16
unsigned 16 bit value
uint8_t u8
unsigned 8 bit value
int64_t s64
signed 64 bit value
int32_t s32
signed 32 bit value
int16_t s16
signed 16 bit value
int8_t s8
signed 8 bit value
unsigned long long ullvec [128/sizeof(unsigned long long)]
vector types
unsigned long ulvec [128/sizeof(unsigned long)]
unsigned long array
unsigned uivec [128/sizeof(unsigned)]
unsigned array
unsigned short usvec [128/sizeof(unsigned short)]
unsigned short array
unsigned char ucvec [128/sizeof(unsigned char)]
unsigned char array
long long llvec [128/sizeof(long long)]
long long array
long lvec [128/sizeof(long)]
long array
int ivec [128/sizeof(int)]
int array
short svec [128/sizeof(short)]
short array
signed char cvec [128/sizeof(signed char)]
signed char array
bool bvec [128/sizeof(bool)]
bool array
uint64_t u64vec [128/sizeof(uint64_t)]
u_int64_t array
uint32_t u32vec [128/sizeof(uint32_t)]
u_int32_t array
uint16_t u16vec [128/sizeof(uint16_t)]
u_int16_t array
uint8_t u8vec [128]
u_int8_t array
int64_t s64vec [128/sizeof(int64_t)]
int64_t array
int32_t s32vec [128/sizeof(int32_t)]
int32_t array
int16_t s16vec [128/sizeof(int16_t)]
int16_t array
int8_t s8vec [128]
int8_t array
struct {
int16_t x
int16_t y
int16_t z
int16_t a
int16_t b
int16_t c
int16_t d
int16_t e
} coord
simple 16 bit integer coordinates
struct {
double x
double y
double z
double a
double b
double c
double d
double e
} dcoord
simple double coordinates
struct {
float x
float y
float z
float a
float b
float c
float d
float e
} fcoord
simple float coordinates
char string [128]
string type
struct {
uint16_t value
char string [128 -sizeof(uint16_t)]
} hash
whiteboard hash type
struct {
char data [128 -2]
unsigned char len
unsigned char type
} wbmsg
compatibility WBMsg type
Detailed Description
union type that is used to store data in shared memory
Definition at line 188 of file gusimplewhiteboard.h.
Member Data Documentation
a [1/3]
int16_t gsw_simple_message::a
Definition at line 251 of file gusimplewhiteboard.h.
a [2/3]
double gsw_simple_message::a
Definition at line 252 of file gusimplewhiteboard.h.
a [3/3]
float gsw_simple_message::a
Definition at line 253 of file gusimplewhiteboard.h.
b [1/3]
int16_t gsw_simple_message::b
Definition at line 251 of file gusimplewhiteboard.h.
b [2/3]
double gsw_simple_message::b
Definition at line 252 of file gusimplewhiteboard.h.
b [3/3]
float gsw_simple_message::b
Definition at line 253 of file gusimplewhiteboard.h.
bvec
bool gsw_simple_message::bvec[128/sizeof(bool)]
bool array
Definition at line 236 of file gusimplewhiteboard.h.
Referenced by generic_whiteboard_object< object_type >::get_from(), and generic_whiteboard_object< object_type >::set().
c [1/3]
int16_t gsw_simple_message::c
Definition at line 251 of file gusimplewhiteboard.h.
c [2/3]
double gsw_simple_message::c
Definition at line 252 of file gusimplewhiteboard.h.
c [3/3]
float gsw_simple_message::c
Definition at line 253 of file gusimplewhiteboard.h.
struct { ... } gsw_simple_message::coord
simple 16 bit integer coordinates
cvec
signed char gsw_simple_message::cvec[128/sizeof(signed char)]
signed char array
Definition at line 235 of file gusimplewhiteboard.h.
d [1/3]
int16_t gsw_simple_message::d
Definition at line 251 of file gusimplewhiteboard.h.
d [2/3]
double gsw_simple_message::d
Definition at line 252 of file gusimplewhiteboard.h.
d [3/3]
float gsw_simple_message::d
Definition at line 253 of file gusimplewhiteboard.h.
data
char gsw_simple_message::data[128 -2]
Definition at line 262 of file gusimplewhiteboard.h.
Referenced by guWhiteboard::Whiteboard::addMessage(), and guWhiteboard::Whiteboard::getWBMsg().
struct { ... } gsw_simple_message::dcoord
simple double coordinates
e [1/3]
int16_t gsw_simple_message::e
Definition at line 251 of file gusimplewhiteboard.h.
e [2/3]
double gsw_simple_message::e
Definition at line 252 of file gusimplewhiteboard.h.
e [3/3]
float gsw_simple_message::e
Definition at line 253 of file gusimplewhiteboard.h.
struct { ... } gsw_simple_message::fcoord
simple float coordinates
struct { ... } gsw_simple_message::hash
whiteboard hash type
Referenced by guWhiteboard::RemoteWhiteboard::getKnownTypesForMachine().
ivec
int gsw_simple_message::ivec[128/sizeof(int)]
int array
Definition at line 233 of file gusimplewhiteboard.h.
Referenced by guWhiteboard::Whiteboard::addMessage(), generic_whiteboard_object< object_type >::get_from(), guWhiteboard::Whiteboard::getWBMsg(), and generic_whiteboard_object< object_type >::set().
len
unsigned char gsw_simple_message::len
Definition at line 262 of file gusimplewhiteboard.h.
Referenced by guWhiteboard::Whiteboard::addMessage(), guWhiteboard::Whiteboard::getMessage(), and guWhiteboard::Whiteboard::getWBMsg().
llvec
long long gsw_simple_message::llvec[128/sizeof(long long)]
long long array
Definition at line 231 of file gusimplewhiteboard.h.
lvec
long gsw_simple_message::lvec[128/sizeof(long)]
long array
Definition at line 232 of file gusimplewhiteboard.h.
s16
int16_t gsw_simple_message::s16
signed 16 bit value
Definition at line 219 of file gusimplewhiteboard.h.
s16vec
int16_t gsw_simple_message::s16vec[128/sizeof(int16_t)]
int16_t array
Definition at line 245 of file gusimplewhiteboard.h.
s32
int32_t gsw_simple_message::s32
signed 32 bit value
Definition at line 218 of file gusimplewhiteboard.h.
s32vec
int32_t gsw_simple_message::s32vec[128/sizeof(int32_t)]
int32_t array
Definition at line 244 of file gusimplewhiteboard.h.
s64
int64_t gsw_simple_message::s64
signed 64 bit value
Definition at line 217 of file gusimplewhiteboard.h.
s64vec
int64_t gsw_simple_message::s64vec[128/sizeof(int64_t)]
int64_t array
Definition at line 243 of file gusimplewhiteboard.h.
s8
int8_t gsw_simple_message::s8
signed 8 bit value
Definition at line 220 of file gusimplewhiteboard.h.
s8vec
int8_t gsw_simple_message::s8vec[128]
int8_t array
Definition at line 246 of file gusimplewhiteboard.h.
schar
signed char gsw_simple_message::schar
signed char
Definition at line 202 of file gusimplewhiteboard.h.
sdouble
double gsw_simple_message::sdouble
signed double
Definition at line 206 of file gusimplewhiteboard.h.
sfloat
float gsw_simple_message::sfloat
signed float
Definition at line 207 of file gusimplewhiteboard.h.
Referenced by guWhiteboard::Whiteboard::addMessage(), and guWhiteboard::Whiteboard::getWBMsg().
sint
int gsw_simple_message::sint
signed integer
Definition at line 198 of file gusimplewhiteboard.h.
Referenced by guWhiteboard::Whiteboard::addMessage(), and guWhiteboard::Whiteboard::getWBMsg().
slong
long gsw_simple_message::slong
singed long value
Definition at line 196 of file gusimplewhiteboard.h.
slongdouble
long double gsw_simple_message::slongdouble
long double
Definition at line 205 of file gusimplewhiteboard.h.
slonglong
long long gsw_simple_message::slonglong
long long value
Definition at line 194 of file gusimplewhiteboard.h.
sshort
short gsw_simple_message::sshort
signed short
Definition at line 200 of file gusimplewhiteboard.h.
string
char gsw_simple_message::string[128 -sizeof(uint16_t)]
string type
Definition at line 256 of file gusimplewhiteboard.h.
Referenced by generic_whiteboard_object< object_type >::get_from(), guWhiteboard::RemoteWhiteboard::getKnownTypesForMachine(), and generic_whiteboard_object< object_type >::set().
svec
short gsw_simple_message::svec[128/sizeof(short)]
short array
Definition at line 234 of file gusimplewhiteboard.h.
type
unsigned char gsw_simple_message::type
Definition at line 262 of file gusimplewhiteboard.h.
Referenced by guWhiteboard::Whiteboard::addMessage(), guWhiteboard::Whiteboard::getMessage(), and guWhiteboard::Whiteboard::getWBMsg().
u16
uint16_t gsw_simple_message::u16
unsigned 16 bit value
Definition at line 214 of file gusimplewhiteboard.h.
u16vec
uint16_t gsw_simple_message::u16vec[128/sizeof(uint16_t)]
u_int16_t array
Definition at line 240 of file gusimplewhiteboard.h.
u32
uint32_t gsw_simple_message::u32
unsigned 32 bit value
Definition at line 213 of file gusimplewhiteboard.h.
u32vec
uint32_t gsw_simple_message::u32vec[128/sizeof(uint32_t)]
u_int32_t array
Definition at line 239 of file gusimplewhiteboard.h.
u64
uint64_t gsw_simple_message::u64
unsigned 64 bit value
Definition at line 212 of file gusimplewhiteboard.h.
u64vec
uint64_t gsw_simple_message::u64vec[128/sizeof(uint64_t)]
u_int64_t array
Definition at line 238 of file gusimplewhiteboard.h.
u8
uint8_t gsw_simple_message::u8
unsigned 8 bit value
Definition at line 215 of file gusimplewhiteboard.h.
u8vec
uint8_t gsw_simple_message::u8vec[128]
u_int8_t array
Definition at line 241 of file gusimplewhiteboard.h.
uchar
unsigned char gsw_simple_message::uchar
unsigned char
Definition at line 201 of file gusimplewhiteboard.h.
ucvec
unsigned char gsw_simple_message::ucvec[128/sizeof(unsigned char)]
unsigned char array
Definition at line 229 of file gusimplewhiteboard.h.
uint
unsigned gsw_simple_message::uint
unsigned integer
Definition at line 197 of file gusimplewhiteboard.h.
uivec
unsigned gsw_simple_message::uivec[128/sizeof(unsigned)]
unsigned array
Definition at line 227 of file gusimplewhiteboard.h.
ullvec
unsigned long long gsw_simple_message::ullvec[128/sizeof(unsigned long long)]
vector types
unsigned long long array
Definition at line 225 of file gusimplewhiteboard.h.
ulong
unsigned long gsw_simple_message::ulong
unsigned long value
Definition at line 195 of file gusimplewhiteboard.h.
ulonglong
unsigned long long gsw_simple_message::ulonglong
unsigned long long value
Definition at line 193 of file gusimplewhiteboard.h.
ulvec
unsigned long gsw_simple_message::ulvec[128/sizeof(unsigned long)]
unsigned long array
Definition at line 226 of file gusimplewhiteboard.h.
ushort
unsigned short gsw_simple_message::ushort
unsigned short
Definition at line 199 of file gusimplewhiteboard.h.
usvec
unsigned short gsw_simple_message::usvec[128/sizeof(unsigned short)]
unsigned short array
Definition at line 228 of file gusimplewhiteboard.h.
value
uint16_t gsw_simple_message::value
Definition at line 259 of file gusimplewhiteboard.h.
struct { ... } gsw_simple_message::wbmsg
compatibility WBMsg type
Referenced by guWhiteboard::Whiteboard::addMessage(), guWhiteboard::Whiteboard::getMessage(), and guWhiteboard::Whiteboard::getWBMsg().
x [1/3]
int16_t gsw_simple_message::x
Definition at line 251 of file gusimplewhiteboard.h.
x [2/3]
double gsw_simple_message::x
Definition at line 252 of file gusimplewhiteboard.h.
x [3/3]
float gsw_simple_message::x
Definition at line 253 of file gusimplewhiteboard.h.
xchar
char gsw_simple_message::xchar
standard char
Definition at line 203 of file gusimplewhiteboard.h.
y [1/3]
int16_t gsw_simple_message::y
Definition at line 251 of file gusimplewhiteboard.h.
y [2/3]
double gsw_simple_message::y
Definition at line 252 of file gusimplewhiteboard.h.
y [3/3]
float gsw_simple_message::y
Definition at line 253 of file gusimplewhiteboard.h.
z [1/3]
int16_t gsw_simple_message::z
Definition at line 251 of file gusimplewhiteboard.h.
z [2/3]
double gsw_simple_message::z
Definition at line 252 of file gusimplewhiteboard.h.
z [3/3]
float gsw_simple_message::z
Definition at line 253 of file gusimplewhiteboard.h.
The documentation for this union was generated from the following file:
gusimplewhiteboard.h