gusimplewhiteboard: typeClassDefs/wb_nao_walk_status.h File Reference
wb_nao_walk_status.h File Reference
#include <gu_util.h>
#include <stdint.h>
#include "wb_odometry.h"
Classes
struct wb_nao_walk_status
WHITEBOARD_POSTER_STRING_CONVERSION.
Macros
#define _XOPEN_SOURCE 700
#define NAOWALKSTATUS_GENERATED
#define NAOWALKSTATUS_C_STRUCT wb_nao_walk_status
#define NAOWALKSTATUS_NUMBER_OF_VARIABLES 3
#define NAOWALKSTATUS_DESC_BUFFER_SIZE 1078
#define NAOWALKSTATUS_TO_STRING_BUFFER_SIZE 1032
Enumerations
enum WalkEngineState { wes_Disconnected = 0 , wes_Walking , wes_StoppedReady , wes_StoppedStanding }
Functions
const char * wb_nao_walk_status_description (const struct wb_nao_walk_status *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_nao_walk_status_to_string (const struct wb_nao_walk_status *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_nao_walk_status * wb_nao_walk_status_from_string (struct wb_nao_walk_status *self, const char *str)
Convert from a string.
size_t wb_nao_walk_status_to_network_serialised (const struct wb_nao_walk_status *self, char *dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
size_t wb_nao_walk_status_from_network_serialised (const char *src, struct wb_nao_walk_status *dst)
Network stream deserialisation.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 72 of file wb_nao_walk_status.h.
NAOWALKSTATUS_C_STRUCT
#define NAOWALKSTATUS_C_STRUCT wb_nao_walk_status
Definition at line 98 of file wb_nao_walk_status.h.
NAOWALKSTATUS_DESC_BUFFER_SIZE
#define NAOWALKSTATUS_DESC_BUFFER_SIZE 1078
Definition at line 102 of file wb_nao_walk_status.h.
NAOWALKSTATUS_GENERATED
#define NAOWALKSTATUS_GENERATED
Definition at line 97 of file wb_nao_walk_status.h.
NAOWALKSTATUS_NUMBER_OF_VARIABLES
#define NAOWALKSTATUS_NUMBER_OF_VARIABLES 3
Definition at line 99 of file wb_nao_walk_status.h.
NAOWALKSTATUS_TO_STRING_BUFFER_SIZE
#define NAOWALKSTATUS_TO_STRING_BUFFER_SIZE 1032
Definition at line 103 of file wb_nao_walk_status.h.
Enumeration Type Documentation
WalkEngineState
enum WalkEngineState
Enumerator
wes_Disconnected
Not connected to the DCM, does not control any joints in this state.
wes_Walking
Walking around, includes stopping, kicking, transition from Standing etc... basically the walk engine is doing something.
wes_StoppedReady
In the Crouched stance, ready to walk again straight away but not currently moving anywhere.
wes_StoppedStanding
In the Standing position, this position uses less power than Stopped / Crouched, it is a minimal stiffness posture. The robot it standing taller than the StoppedReady pose, with the legs straight.
Definition at line 90 of file wb_nao_walk_status.h.
Function Documentation
wb_nao_walk_status_description()
const char * wb_nao_walk_status_description (const struct wb_nao_walk_status * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_nao_walk_status.c.
References ODOMETRY_DESC_BUFFER_SIZE, wb_odometry_description(), wes_Disconnected, wes_StoppedReady, wes_StoppedStanding, and wes_Walking.
Referenced by guWhiteboard::NaoWalkStatus::description().
wb_nao_walk_status_from_network_serialised()
size_t wb_nao_walk_status_from_network_serialised (const char * src, struct wb_nao_walk_status * dst)
Network stream deserialisation.
Network stream deserialisation.
Definition at line 427 of file wb_nao_walk_status.c.
References ntohl, wb_nao_walk_status::odometryResetCounter, and wb_nao_walk_status::walkEngineState.
wb_nao_walk_status_from_string()
struct wb_nao_walk_status * wb_nao_walk_status_from_string (struct wb_nao_walk_status * self, const char * str)
Convert from a string.
Definition at line 253 of file wb_nao_walk_status.c.
References NAOWALKSTATUS_DESC_BUFFER_SIZE, wb_odometry_from_string(), wes_Disconnected, wes_StoppedReady, wes_StoppedStanding, and wes_Walking.
wb_nao_walk_status_to_network_serialised()
size_t wb_nao_walk_status_to_network_serialised (const struct wb_nao_walk_status * self, char * dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
Network stream serialisation
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 388 of file wb_nao_walk_status.c.
References htonl.
wb_nao_walk_status_to_string()
const char * wb_nao_walk_status_to_string (const struct wb_nao_walk_status * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 189 of file wb_nao_walk_status.c.
References ODOMETRY_TO_STRING_BUFFER_SIZE, wb_odometry_to_string(), wes_Disconnected, wes_StoppedReady, wes_StoppedStanding, and wes_Walking.
Referenced by guWhiteboard::NaoWalkStatus::to_string().