gusimplewhiteboard: typeClassDefs/wb_pixel_coordinate_line.c File Reference
wb_pixel_coordinate_line.c File Reference
#include "wb_pixel_coordinate_line.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <limits.h>
Macros
#define htonll(x) bswap_64(x)
#define ntohll(x) bswap_64(x)
#define htonl(x) bswap_32(x)
#define ntohl(x) bswap_32(x)
#define htons(x) bswap_16(x)
#define ntohs(x) bswap_16(x)
Functions
const char * wb_pixel_coordinate_line_description (const struct wb_pixel_coordinate_line *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_pixel_coordinate_line_to_string (const struct wb_pixel_coordinate_line *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_pixel_coordinate_line * wb_pixel_coordinate_line_from_string (struct wb_pixel_coordinate_line *self, const char *str)
Convert from a string.
size_t wb_pixel_coordinate_line_to_network_serialised (const struct wb_pixel_coordinate_line *self, char *dst)
Convert to a compressed, serialised, network byte order byte stream.
size_t wb_pixel_coordinate_line_from_network_serialised (const char *src, struct wb_pixel_coordinate_line *dst)
Convert from a compressed, serialised, network byte order byte stream.
gu_pixel_coordinate wb_pixel_coordinate_line_start_px_coord (const struct wb_pixel_coordinate_line self, const uint16_t resWidth, const uint16_t resHeight)
WHITEBOARD_POSTER_STRING_CONVERSION.
gu_pixel_coordinate wb_pixel_coordinate_line_end_px_coord (const struct wb_pixel_coordinate_line self, const uint16_t resWidth, const uint16_t resHeight)
Macro Definition Documentation
htonl
#define htonl (x) bswap_32(x)
Definition at line 97 of file wb_pixel_coordinate_line.c.
htonll
#define htonll (x) bswap_64(x)
Definition at line 93 of file wb_pixel_coordinate_line.c.
htons
#define htons (x) bswap_16(x)
Definition at line 101 of file wb_pixel_coordinate_line.c.
ntohl
#define ntohl (x) bswap_32(x)
Definition at line 98 of file wb_pixel_coordinate_line.c.
ntohll
#define ntohll (x) bswap_64(x)
Definition at line 94 of file wb_pixel_coordinate_line.c.
ntohs
#define ntohs (x) bswap_16(x)
Definition at line 102 of file wb_pixel_coordinate_line.c.
Function Documentation
wb_pixel_coordinate_line_description()
const char * wb_pixel_coordinate_line_description (const struct wb_pixel_coordinate_line * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_pixel_coordinate_line.c.
References PIXEL_COORDINATE_DESC_BUFFER_SIZE, and wb_pixel_coordinate_description().
Referenced by guWhiteboard::PixelCoordinateLine::description(), wb_vision_detection_line_array_description(), and wb_vision_line_description().
wb_pixel_coordinate_line_end_px_coord()
gu_pixel_coordinate wb_pixel_coordinate_line_end_px_coord (const struct wb_pixel_coordinate_line self, const uint16_t resWidth, const uint16_t resHeight)
Definition at line 349 of file wb_pixel_coordinate_line.c.
References wb_pixel_coordinate_line::end, and wb_px_coord_to_px_coord().
wb_pixel_coordinate_line_from_network_serialised()
size_t wb_pixel_coordinate_line_from_network_serialised (const char * src, struct wb_pixel_coordinate_line * dst)
Convert from a compressed, serialised, network byte order byte stream.
Network stream deserialisation.
Definition at line 333 of file wb_pixel_coordinate_line.c.
wb_pixel_coordinate_line_from_string()
struct wb_pixel_coordinate_line * wb_pixel_coordinate_line_from_string (struct wb_pixel_coordinate_line * self, const char * str)
Convert from a string.
Definition at line 217 of file wb_pixel_coordinate_line.c.
References PIXEL_COORDINATE_LINE_DESC_BUFFER_SIZE, and wb_pixel_coordinate_from_string().
Referenced by wb_vision_detection_line_array_from_string(), and wb_vision_line_from_string().
wb_pixel_coordinate_line_start_px_coord()
gu_pixel_coordinate wb_pixel_coordinate_line_start_px_coord (const struct wb_pixel_coordinate_line self, const uint16_t resWidth, const uint16_t resHeight)
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 345 of file wb_pixel_coordinate_line.c.
References wb_pixel_coordinate_line::start, and wb_px_coord_to_px_coord().
wb_pixel_coordinate_line_to_network_serialised()
size_t wb_pixel_coordinate_line_to_network_serialised (const struct wb_pixel_coordinate_line * self, char * dst)
Convert to a compressed, serialised, network byte order byte stream.
Network stream serialisation.
Definition at line 320 of file wb_pixel_coordinate_line.c.
wb_pixel_coordinate_line_to_string()
const char * wb_pixel_coordinate_line_to_string (const struct wb_pixel_coordinate_line * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 171 of file wb_pixel_coordinate_line.c.
References PIXEL_COORDINATE_TO_STRING_BUFFER_SIZE, and wb_pixel_coordinate_to_string().
Referenced by guWhiteboard::PixelCoordinateLine::to_string(), wb_vision_detection_line_array_to_string(), and wb_vision_line_to_string().