gusimplewhiteboard: typeClassDefs/wb_vision_field_feature.c File Reference
wb_vision_field_feature.c File Reference
#include "wb_vision_field_feature.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <limits.h>
Macros
#define htonll(x) bswap_64(x)
#define ntohll(x) bswap_64(x)
#define htonl(x) bswap_32(x)
#define ntohl(x) bswap_32(x)
#define htons(x) bswap_16(x)
#define ntohs(x) bswap_16(x)
Functions
const char * wb_vision_field_feature_description (const struct wb_vision_field_feature *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_vision_field_feature_to_string (const struct wb_vision_field_feature *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_vision_field_feature * wb_vision_field_feature_from_string (struct wb_vision_field_feature *self, const char *str)
Convert from a string.
size_t wb_vision_field_feature_to_network_serialised (const struct wb_vision_field_feature *self, char *dst)
Convert to a compressed, serialised, network byte order byte stream.
size_t wb_vision_field_feature_from_network_serialised (const char *src, struct wb_vision_field_feature *dst)
Convert from a compressed, serialised, network byte order byte stream.
gu_pixel_coordinate wb_vision_field_feature_coordinate_px_coord (const struct wb_vision_field_feature self, const uint16_t resWidth, const uint16_t resHeight)
WHITEBOARD_POSTER_STRING_CONVERSION.
Macro Definition Documentation
htonl
#define htonl (x) bswap_32(x)
Definition at line 97 of file wb_vision_field_feature.c.
htonll
#define htonll (x) bswap_64(x)
Definition at line 93 of file wb_vision_field_feature.c.
htons
#define htons (x) bswap_16(x)
Definition at line 101 of file wb_vision_field_feature.c.
ntohl
#define ntohl (x) bswap_32(x)
Definition at line 98 of file wb_vision_field_feature.c.
ntohll
#define ntohll (x) bswap_64(x)
Definition at line 94 of file wb_vision_field_feature.c.
ntohs
#define ntohs (x) bswap_16(x)
Definition at line 102 of file wb_vision_field_feature.c.
Function Documentation
wb_vision_field_feature_coordinate_px_coord()
gu_pixel_coordinate wb_vision_field_feature_coordinate_px_coord (const struct wb_vision_field_feature self, const uint16_t resWidth, const uint16_t resHeight)
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 348 of file wb_vision_field_feature.c.
References wb_vision_field_feature::coordinate, and wb_px_coord_to_px_coord().
wb_vision_field_feature_description()
const char * wb_vision_field_feature_description (const struct wb_vision_field_feature * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_vision_field_feature.c.
References PIXEL_COORDINATE_DESC_BUFFER_SIZE, and wb_pixel_coordinate_description().
Referenced by guWhiteboard::VisionFieldFeature::description(), and wb_vision_field_features_description().
wb_vision_field_feature_from_network_serialised()
size_t wb_vision_field_feature_from_network_serialised (const char * src, struct wb_vision_field_feature * dst)
Convert from a compressed, serialised, network byte order byte stream.
Network stream deserialisation.
Definition at line 323 of file wb_vision_field_feature.c.
References wb_vision_field_feature::camera.
wb_vision_field_feature_from_string()
struct wb_vision_field_feature * wb_vision_field_feature_from_string (struct wb_vision_field_feature * self, const char * str)
Convert from a string.
Definition at line 195 of file wb_vision_field_feature.c.
References VISION_FIELD_FEATURE_DESC_BUFFER_SIZE, and wb_pixel_coordinate_from_string().
Referenced by wb_vision_field_features_from_string().
wb_vision_field_feature_to_network_serialised()
size_t wb_vision_field_feature_to_network_serialised (const struct wb_vision_field_feature * self, char * dst)
Convert to a compressed, serialised, network byte order byte stream.
Network stream serialisation.
Definition at line 298 of file wb_vision_field_feature.c.
wb_vision_field_feature_to_string()
const char * wb_vision_field_feature_to_string (const struct wb_vision_field_feature * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 160 of file wb_vision_field_feature.c.
References PIXEL_COORDINATE_TO_STRING_BUFFER_SIZE, and wb_pixel_coordinate_to_string().
Referenced by guWhiteboard::VisionFieldFeature::to_string(), and wb_vision_field_features_to_string().