gusimplewhiteboard: typeClassDefs/wb_filtered_arrayballsightings.c File Reference
wb_filtered_arrayballsightings.c File Reference
#include "wb_filtered_arrayballsightings.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <limits.h>
Macros
#define htonll(x) bswap_64(x)
#define ntohll(x) bswap_64(x)
#define htonl(x) bswap_32(x)
#define ntohl(x) bswap_32(x)
#define htons(x) bswap_16(x)
#define ntohs(x) bswap_16(x)
Functions
const char * wb_filtered_arrayballsightings_description (const struct wb_filtered_arrayballsightings *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_filtered_arrayballsightings_to_string (const struct wb_filtered_arrayballsightings *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_filtered_arrayballsightings * wb_filtered_arrayballsightings_from_string (struct wb_filtered_arrayballsightings *self, const char *str)
Convert from a string.
size_t wb_filtered_arrayballsightings_to_network_serialised (const struct wb_filtered_arrayballsightings *self, char *dst)
Convert to a compressed, serialised, network byte order byte stream.
size_t wb_filtered_arrayballsightings_from_network_serialised (const char *src, struct wb_filtered_arrayballsightings *dst)
Convert from a compressed, serialised, network byte order byte stream.
Macro Definition Documentation
htonl
#define htonl (x) bswap_32(x)
Definition at line 97 of file wb_filtered_arrayballsightings.c.
htonll
#define htonll (x) bswap_64(x)
Definition at line 93 of file wb_filtered_arrayballsightings.c.
htons
#define htons (x) bswap_16(x)
Definition at line 101 of file wb_filtered_arrayballsightings.c.
ntohl
#define ntohl (x) bswap_32(x)
Definition at line 98 of file wb_filtered_arrayballsightings.c.
ntohll
#define ntohll (x) bswap_64(x)
Definition at line 94 of file wb_filtered_arrayballsightings.c.
ntohs
#define ntohs (x) bswap_16(x)
Definition at line 102 of file wb_filtered_arrayballsightings.c.
Function Documentation
wb_filtered_arrayballsightings_description()
const char * wb_filtered_arrayballsightings_description (const struct wb_filtered_arrayballsightings * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_filtered_arrayballsightings.c.
References FILTERED_ARRAYBALLSIGHTINGS_OBJECTS_ARRAY_SIZE, FILTERED_VISION_OBJECT_DESC_BUFFER_SIZE, and wb_filtered_vision_object_description().
Referenced by guWhiteboard::FilteredArrayBallSightings::description().
wb_filtered_arrayballsightings_from_network_serialised()
size_t wb_filtered_arrayballsightings_from_network_serialised (const char * src, struct wb_filtered_arrayballsightings * dst)
Convert from a compressed, serialised, network byte order byte stream.
Network stream deserialisation.
Definition at line 394 of file wb_filtered_arrayballsightings.c.
References wb_filtered_arrayballsightings::objects.
wb_filtered_arrayballsightings_from_string()
struct wb_filtered_arrayballsightings * wb_filtered_arrayballsightings_from_string (struct wb_filtered_arrayballsightings * self, const char * str)
Convert from a string.
Definition at line 205 of file wb_filtered_arrayballsightings.c.
References FILTERED_ARRAYBALLSIGHTINGS_DESC_BUFFER_SIZE, FILTERED_ARRAYBALLSIGHTINGS_OBJECTS_ARRAY_SIZE, and wb_filtered_vision_object_from_string().
wb_filtered_arrayballsightings_to_network_serialised()
size_t wb_filtered_arrayballsightings_to_network_serialised (const struct wb_filtered_arrayballsightings * self, char * dst)
Convert to a compressed, serialised, network byte order byte stream.
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 362 of file wb_filtered_arrayballsightings.c.
wb_filtered_arrayballsightings_to_string()
const char * wb_filtered_arrayballsightings_to_string (const struct wb_filtered_arrayballsightings * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 165 of file wb_filtered_arrayballsightings.c.
References FILTERED_ARRAYBALLSIGHTINGS_OBJECTS_ARRAY_SIZE, FILTERED_VISION_OBJECT_TO_STRING_BUFFER_SIZE, and wb_filtered_vision_object_to_string().
Referenced by guWhiteboard::FilteredArrayBallSightings::to_string().