gusimplewhiteboard: typeClassDefs/wb_particle_position.h File Reference
wb_particle_position.h File Reference
#include <gu_util.h>
#include <stdint.h>
#include "wb_point2d.h"
Classes
struct wb_particle_position
WHITEBOARD_POSTER_STRING_CONVERSION.
Macros
#define _XOPEN_SOURCE 700
#define PARTICLE_POSITION_GENERATED
#define PARTICLE_POSITION_C_STRUCT wb_particle_position
#define PARTICLE_POSITION_NUMBER_OF_VARIABLES 3
#define PARTICLE_POSITION_DESC_BUFFER_SIZE 624
#define PARTICLE_POSITION_TO_STRING_BUFFER_SIZE 587
Functions
const char * wb_particle_position_description (const struct wb_particle_position *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_particle_position_to_string (const struct wb_particle_position *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_particle_position * wb_particle_position_from_string (struct wb_particle_position *self, const char *str)
Convert from a string.
size_t wb_particle_position_to_network_serialised (const struct wb_particle_position *self, char *dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
size_t wb_particle_position_from_network_serialised (const char *src, struct wb_particle_position *dst)
Network stream deserialisation.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 72 of file wb_particle_position.h.
PARTICLE_POSITION_C_STRUCT
#define PARTICLE_POSITION_C_STRUCT wb_particle_position
Definition at line 91 of file wb_particle_position.h.
PARTICLE_POSITION_DESC_BUFFER_SIZE
#define PARTICLE_POSITION_DESC_BUFFER_SIZE 624
Definition at line 95 of file wb_particle_position.h.
PARTICLE_POSITION_GENERATED
#define PARTICLE_POSITION_GENERATED
Definition at line 90 of file wb_particle_position.h.
PARTICLE_POSITION_NUMBER_OF_VARIABLES
#define PARTICLE_POSITION_NUMBER_OF_VARIABLES 3
Definition at line 92 of file wb_particle_position.h.
PARTICLE_POSITION_TO_STRING_BUFFER_SIZE
#define PARTICLE_POSITION_TO_STRING_BUFFER_SIZE 587
Definition at line 96 of file wb_particle_position.h.
Function Documentation
wb_particle_position_description()
const char * wb_particle_position_description (const struct wb_particle_position * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_particle_position.c.
References POINT2D_DESC_BUFFER_SIZE, and wb_point2d_description().
Referenced by guWhiteboard::ParticlePosition::description(), and wb_top_particles_description().
wb_particle_position_from_network_serialised()
size_t wb_particle_position_from_network_serialised (const char * src, struct wb_particle_position * dst)
Network stream deserialisation.
Network stream deserialisation.
Definition at line 348 of file wb_particle_position.c.
References wb_particle_position::headingInDegrees, and ntohs.
wb_particle_position_from_string()
struct wb_particle_position * wb_particle_position_from_string (struct wb_particle_position * self, const char * str)
Convert from a string.
Definition at line 211 of file wb_particle_position.c.
References PARTICLE_POSITION_DESC_BUFFER_SIZE, and wb_point2d_from_string().
Referenced by wb_top_particles_from_string().
wb_particle_position_to_network_serialised()
size_t wb_particle_position_to_network_serialised (const struct wb_particle_position * self, char * dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
Network stream serialisation
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 321 of file wb_particle_position.c.
References htons.
wb_particle_position_to_string()
const char * wb_particle_position_to_string (const struct wb_particle_position * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 168 of file wb_particle_position.c.
References POINT2D_TO_STRING_BUFFER_SIZE, and wb_point2d_to_string().
Referenced by guWhiteboard::ParticlePosition::to_string(), and wb_top_particles_to_string().