gusimplewhiteboard: typeClassDefs/wb_microphone_frequencies.h File Reference
wb_microphone_frequencies.h File Reference
#include <gu_util.h>
#include <stdint.h>
Classes
struct wb_microphone_frequencies
WHITEBOARD_POSTER_STRING_CONVERSION.
Macros
#define _XOPEN_SOURCE 700
#define MICROPHONE_FREQUENCIES_GENERATED
#define MICROPHONE_FREQUENCIES_C_STRUCT wb_microphone_frequencies
#define MICROPHONE_FREQUENCIES_NUMBER_OF_VARIABLES 4
#define MICROPHONE_FREQUENCIES_DESC_BUFFER_SIZE 75
#define MICROPHONE_FREQUENCIES_TO_STRING_BUFFER_SIZE 31
Functions
const char * wb_microphone_frequencies_description (const struct wb_microphone_frequencies *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_microphone_frequencies_to_string (const struct wb_microphone_frequencies *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_microphone_frequencies * wb_microphone_frequencies_from_string (struct wb_microphone_frequencies *self, const char *str)
Convert from a string.
size_t wb_microphone_frequencies_to_network_serialised (const struct wb_microphone_frequencies *self, char *dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
size_t wb_microphone_frequencies_from_network_serialised (const char *src, struct wb_microphone_frequencies *dst)
Network stream deserialisation.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 72 of file wb_microphone_frequencies.h.
MICROPHONE_FREQUENCIES_C_STRUCT
#define MICROPHONE_FREQUENCIES_C_STRUCT wb_microphone_frequencies
Definition at line 91 of file wb_microphone_frequencies.h.
MICROPHONE_FREQUENCIES_DESC_BUFFER_SIZE
#define MICROPHONE_FREQUENCIES_DESC_BUFFER_SIZE 75
Definition at line 95 of file wb_microphone_frequencies.h.
MICROPHONE_FREQUENCIES_GENERATED
#define MICROPHONE_FREQUENCIES_GENERATED
Definition at line 90 of file wb_microphone_frequencies.h.
MICROPHONE_FREQUENCIES_NUMBER_OF_VARIABLES
#define MICROPHONE_FREQUENCIES_NUMBER_OF_VARIABLES 4
Definition at line 92 of file wb_microphone_frequencies.h.
MICROPHONE_FREQUENCIES_TO_STRING_BUFFER_SIZE
#define MICROPHONE_FREQUENCIES_TO_STRING_BUFFER_SIZE 31
Definition at line 96 of file wb_microphone_frequencies.h.
Function Documentation
wb_microphone_frequencies_description()
const char * wb_microphone_frequencies_description (const struct wb_microphone_frequencies * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_microphone_frequencies.c.
Referenced by guWhiteboard::MicrophoneFrequencies::description(), and wb_dominant_frequencies_description().
wb_microphone_frequencies_from_network_serialised()
size_t wb_microphone_frequencies_from_network_serialised (const char * src, struct wb_microphone_frequencies * dst)
Network stream deserialisation.
Network stream deserialisation.
Definition at line 389 of file wb_microphone_frequencies.c.
References wb_microphone_frequencies::front_left, wb_microphone_frequencies::front_right, ntohs, wb_microphone_frequencies::rear_left, and wb_microphone_frequencies::rear_right.
wb_microphone_frequencies_from_string()
struct wb_microphone_frequencies * wb_microphone_frequencies_from_string (struct wb_microphone_frequencies * self, const char * str)
Convert from a string.
Definition at line 205 of file wb_microphone_frequencies.c.
References MICROPHONE_FREQUENCIES_DESC_BUFFER_SIZE.
Referenced by wb_dominant_frequencies_from_string().
wb_microphone_frequencies_to_network_serialised()
size_t wb_microphone_frequencies_to_network_serialised (const struct wb_microphone_frequencies * self, char * dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
Network stream serialisation
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 322 of file wb_microphone_frequencies.c.
References htons.
wb_microphone_frequencies_to_string()
const char * wb_microphone_frequencies_to_string (const struct wb_microphone_frequencies * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 165 of file wb_microphone_frequencies.c.
Referenced by guWhiteboard::MicrophoneFrequencies::to_string(), and wb_dominant_frequencies_to_string().