gusimplewhiteboard: typeClassDefs/wb_line_sighting.c File Reference
wb_line_sighting.c File Reference
#include "wb_line_sighting.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <limits.h>
Macros
#define htonll(x) bswap_64(x)
#define ntohll(x) bswap_64(x)
#define htonl(x) bswap_32(x)
#define ntohl(x) bswap_32(x)
#define htons(x) bswap_16(x)
#define ntohs(x) bswap_16(x)
Functions
const char * wb_line_sighting_description (const struct wb_line_sighting *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_line_sighting_to_string (const struct wb_line_sighting *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_line_sighting * wb_line_sighting_from_string (struct wb_line_sighting *self, const char *str)
Convert from a string.
size_t wb_line_sighting_to_network_serialised (const struct wb_line_sighting *self, char *dst)
Convert to a compressed, serialised, network byte order byte stream.
size_t wb_line_sighting_from_network_serialised (const char *src, struct wb_line_sighting *dst)
Convert from a compressed, serialised, network byte order byte stream.
Macro Definition Documentation
htonl
#define htonl (x) bswap_32(x)
Definition at line 97 of file wb_line_sighting.c.
htonll
#define htonll (x) bswap_64(x)
Definition at line 93 of file wb_line_sighting.c.
htons
#define htons (x) bswap_16(x)
Definition at line 101 of file wb_line_sighting.c.
ntohl
#define ntohl (x) bswap_32(x)
Definition at line 98 of file wb_line_sighting.c.
ntohll
#define ntohll (x) bswap_64(x)
Definition at line 94 of file wb_line_sighting.c.
ntohs
#define ntohs (x) bswap_16(x)
Definition at line 102 of file wb_line_sighting.c.
Function Documentation
wb_line_sighting_description()
const char * wb_line_sighting_description (const struct wb_line_sighting * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_line_sighting.c.
References FieldLineSightingType, HorizonLineSightingType, POLAR_COORDINATE_DESC_BUFFER_SIZE, and wb_polar_coordinate_description().
Referenced by guWhiteboard::LineSighting::description(), and wb_machine_filtered_lines_description().
wb_line_sighting_from_network_serialised()
size_t wb_line_sighting_from_network_serialised (const char * src, struct wb_line_sighting * dst)
Convert from a compressed, serialised, network byte order byte stream.
Network stream deserialisation.
Definition at line 405 of file wb_line_sighting.c.
References ntohl, and wb_line_sighting::sightingType.
wb_line_sighting_from_string()
struct wb_line_sighting * wb_line_sighting_from_string (struct wb_line_sighting * self, const char * str)
Convert from a string.
Definition at line 255 of file wb_line_sighting.c.
References FieldLineSightingType, HorizonLineSightingType, LINE_SIGHTING_DESC_BUFFER_SIZE, and wb_polar_coordinate_from_string().
Referenced by wb_machine_filtered_lines_from_string().
wb_line_sighting_to_network_serialised()
size_t wb_line_sighting_to_network_serialised (const struct wb_line_sighting * self, char * dst)
Convert to a compressed, serialised, network byte order byte stream.
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 380 of file wb_line_sighting.c.
References htonl.
wb_line_sighting_to_string()
const char * wb_line_sighting_to_string (const struct wb_line_sighting * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 190 of file wb_line_sighting.c.
References FieldLineSightingType, HorizonLineSightingType, POLAR_COORDINATE_TO_STRING_BUFFER_SIZE, and wb_polar_coordinate_to_string().
Referenced by guWhiteboard::LineSighting::to_string(), and wb_machine_filtered_lines_to_string().