gusimplewhiteboard: typeClassDefs/wb_vision_field_feature.h File Reference
wb_vision_field_feature.h File Reference
#include <gu_util.h>
#include <stdint.h>
#include "wb_pixel_coordinate.h"
#include <guunits/guunits.h>
#include <gucoordinates/gucoordinates.h>
Classes
struct wb_vision_field_feature
WHITEBOARD_POSTER_STRING_CONVERSION.
Macros
#define _XOPEN_SOURCE 700
#define VISION_FIELD_FEATURE_GENERATED
#define VISION_FIELD_FEATURE_C_STRUCT wb_vision_field_feature
#define VISION_FIELD_FEATURE_NUMBER_OF_VARIABLES 2
#define VISION_FIELD_FEATURE_DESC_BUFFER_SIZE 536
#define VISION_FIELD_FEATURE_TO_STRING_BUFFER_SIZE 518
Functions
const char * wb_vision_field_feature_description (const struct wb_vision_field_feature *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_vision_field_feature_to_string (const struct wb_vision_field_feature *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_vision_field_feature * wb_vision_field_feature_from_string (struct wb_vision_field_feature *self, const char *str)
Convert from a string.
gu_pixel_coordinate wb_vision_field_feature_coordinate_px_coord (const struct wb_vision_field_feature self, const uint16_t resWidth, const uint16_t resHeight)
WHITEBOARD_POSTER_STRING_CONVERSION.
size_t wb_vision_field_feature_to_network_serialised (const struct wb_vision_field_feature *self, char *dst)
Network stream serialisation.
size_t wb_vision_field_feature_from_network_serialised (const char *src, struct wb_vision_field_feature *dst)
Network stream deserialisation.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 72 of file wb_vision_field_feature.h.
VISION_FIELD_FEATURE_C_STRUCT
#define VISION_FIELD_FEATURE_C_STRUCT wb_vision_field_feature
Definition at line 95 of file wb_vision_field_feature.h.
VISION_FIELD_FEATURE_DESC_BUFFER_SIZE
#define VISION_FIELD_FEATURE_DESC_BUFFER_SIZE 536
Definition at line 99 of file wb_vision_field_feature.h.
VISION_FIELD_FEATURE_GENERATED
#define VISION_FIELD_FEATURE_GENERATED
Definition at line 94 of file wb_vision_field_feature.h.
VISION_FIELD_FEATURE_NUMBER_OF_VARIABLES
#define VISION_FIELD_FEATURE_NUMBER_OF_VARIABLES 2
Definition at line 96 of file wb_vision_field_feature.h.
VISION_FIELD_FEATURE_TO_STRING_BUFFER_SIZE
#define VISION_FIELD_FEATURE_TO_STRING_BUFFER_SIZE 518
Definition at line 100 of file wb_vision_field_feature.h.
Function Documentation
wb_vision_field_feature_coordinate_px_coord()
gu_pixel_coordinate wb_vision_field_feature_coordinate_px_coord (const struct wb_vision_field_feature self, const uint16_t resWidth, const uint16_t resHeight)
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 348 of file wb_vision_field_feature.c.
References wb_vision_field_feature::coordinate, and wb_px_coord_to_px_coord().
wb_vision_field_feature_description()
const char * wb_vision_field_feature_description (const struct wb_vision_field_feature * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_vision_field_feature.c.
References PIXEL_COORDINATE_DESC_BUFFER_SIZE, and wb_pixel_coordinate_description().
Referenced by guWhiteboard::VisionFieldFeature::description(), and wb_vision_field_features_description().
wb_vision_field_feature_from_network_serialised()
size_t wb_vision_field_feature_from_network_serialised (const char * src, struct wb_vision_field_feature * dst)
Network stream deserialisation.
Network stream deserialisation.
Definition at line 323 of file wb_vision_field_feature.c.
References wb_vision_field_feature::camera.
wb_vision_field_feature_from_string()
struct wb_vision_field_feature * wb_vision_field_feature_from_string (struct wb_vision_field_feature * self, const char * str)
Convert from a string.
Definition at line 195 of file wb_vision_field_feature.c.
References VISION_FIELD_FEATURE_DESC_BUFFER_SIZE, and wb_pixel_coordinate_from_string().
Referenced by wb_vision_field_features_from_string().
wb_vision_field_feature_to_network_serialised()
size_t wb_vision_field_feature_to_network_serialised (const struct wb_vision_field_feature * self, char * dst)
Network stream serialisation.
Network stream serialisation.
Definition at line 298 of file wb_vision_field_feature.c.
wb_vision_field_feature_to_string()
const char * wb_vision_field_feature_to_string (const struct wb_vision_field_feature * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 160 of file wb_vision_field_feature.c.
References PIXEL_COORDINATE_TO_STRING_BUFFER_SIZE, and wb_pixel_coordinate_to_string().
Referenced by guWhiteboard::VisionFieldFeature::to_string(), and wb_vision_field_features_to_string().