gusimplewhiteboard: typeClassDefs/wb_machine_filtered_localisation_vision.h File Reference
wb_machine_filtered_localisation_vision.h File Reference
#include <gu_util.h>
#include <stdint.h>
#include "wb_landmark_sighting.h"
Classes
struct wb_machine_filtered_localisation_vision
Results of the FSM (and sub machines) "SMFilterVision".
Macros
#define _XOPEN_SOURCE 700
#define MACHINE_FILTERED_LOCALISATION_VISION_GENERATED
#define MACHINE_FILTERED_LOCALISATION_VISION_C_STRUCT wb_machine_filtered_localisation_vision
#define MACHINE_FILTERED_LOCALISATION_VISION_NUMBER_OF_VARIABLES 2
#define MACHINE_FILTERED_LOCALISATION_VISION_DESC_BUFFER_SIZE 546
#define MACHINE_FILTERED_LOCALISATION_VISION_TO_STRING_BUFFER_SIZE 518
#define MACHINE_FILTERED_LOCALISATION_VISION_SIGHTINGS_ARRAY_SIZE 12
WHITEBOARD_POSTER_STRING_CONVERSION.
Functions
const char * wb_machine_filtered_localisation_vision_description (const struct wb_machine_filtered_localisation_vision *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_machine_filtered_localisation_vision_to_string (const struct wb_machine_filtered_localisation_vision *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_machine_filtered_localisation_vision * wb_machine_filtered_localisation_vision_from_string (struct wb_machine_filtered_localisation_vision *self, const char *str)
Convert from a string.
size_t wb_machine_filtered_localisation_vision_to_network_serialised (const struct wb_machine_filtered_localisation_vision *self, char *dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
size_t wb_machine_filtered_localisation_vision_from_network_serialised (const char *src, struct wb_machine_filtered_localisation_vision *dst)
Network stream deserialisation.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 72 of file wb_machine_filtered_localisation_vision.h.
MACHINE_FILTERED_LOCALISATION_VISION_C_STRUCT
#define MACHINE_FILTERED_LOCALISATION_VISION_C_STRUCT wb_machine_filtered_localisation_vision
Definition at line 91 of file wb_machine_filtered_localisation_vision.h.
MACHINE_FILTERED_LOCALISATION_VISION_DESC_BUFFER_SIZE
#define MACHINE_FILTERED_LOCALISATION_VISION_DESC_BUFFER_SIZE 546
Definition at line 95 of file wb_machine_filtered_localisation_vision.h.
MACHINE_FILTERED_LOCALISATION_VISION_GENERATED
#define MACHINE_FILTERED_LOCALISATION_VISION_GENERATED
Definition at line 90 of file wb_machine_filtered_localisation_vision.h.
MACHINE_FILTERED_LOCALISATION_VISION_NUMBER_OF_VARIABLES
#define MACHINE_FILTERED_LOCALISATION_VISION_NUMBER_OF_VARIABLES 2
Definition at line 92 of file wb_machine_filtered_localisation_vision.h.
MACHINE_FILTERED_LOCALISATION_VISION_SIGHTINGS_ARRAY_SIZE
#define MACHINE_FILTERED_LOCALISATION_VISION_SIGHTINGS_ARRAY_SIZE 12
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 99 of file wb_machine_filtered_localisation_vision.h.
MACHINE_FILTERED_LOCALISATION_VISION_TO_STRING_BUFFER_SIZE
#define MACHINE_FILTERED_LOCALISATION_VISION_TO_STRING_BUFFER_SIZE 518
Definition at line 96 of file wb_machine_filtered_localisation_vision.h.
Function Documentation
wb_machine_filtered_localisation_vision_description()
const char * wb_machine_filtered_localisation_vision_description (const struct wb_machine_filtered_localisation_vision * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_machine_filtered_localisation_vision.c.
References LANDMARK_SIGHTING_DESC_BUFFER_SIZE, MACHINE_FILTERED_LOCALISATION_VISION_SIGHTINGS_ARRAY_SIZE, and wb_landmark_sighting_description().
Referenced by guWhiteboard::MachineFilteredLocalisationVision::description().
wb_machine_filtered_localisation_vision_from_network_serialised()
size_t wb_machine_filtered_localisation_vision_from_network_serialised (const char * src, struct wb_machine_filtered_localisation_vision * dst)
Network stream deserialisation.
Network stream deserialisation.
Definition at line 431 of file wb_machine_filtered_localisation_vision.c.
References wb_machine_filtered_localisation_vision::numberOfSightings, and wb_machine_filtered_localisation_vision::sightings.
wb_machine_filtered_localisation_vision_from_string()
struct wb_machine_filtered_localisation_vision * wb_machine_filtered_localisation_vision_from_string (struct wb_machine_filtered_localisation_vision * self, const char * str)
Convert from a string.
Definition at line 221 of file wb_machine_filtered_localisation_vision.c.
References MACHINE_FILTERED_LOCALISATION_VISION_DESC_BUFFER_SIZE, MACHINE_FILTERED_LOCALISATION_VISION_SIGHTINGS_ARRAY_SIZE, and wb_landmark_sighting_from_string().
wb_machine_filtered_localisation_vision_to_network_serialised()
size_t wb_machine_filtered_localisation_vision_to_network_serialised (const struct wb_machine_filtered_localisation_vision * self, char * dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
Network stream serialisation
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 385 of file wb_machine_filtered_localisation_vision.c.
wb_machine_filtered_localisation_vision_to_string()
const char * wb_machine_filtered_localisation_vision_to_string (const struct wb_machine_filtered_localisation_vision * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 173 of file wb_machine_filtered_localisation_vision.c.
References LANDMARK_SIGHTING_TO_STRING_BUFFER_SIZE, MACHINE_FILTERED_LOCALISATION_VISION_SIGHTINGS_ARRAY_SIZE, and wb_landmark_sighting_to_string().
Referenced by guWhiteboard::MachineFilteredLocalisationVision::to_string().