gusimplewhiteboard: typeClassDefs/wb_line_sighting.h File Reference
wb_line_sighting.h File Reference
#include <gu_util.h>
#include <stdint.h>
#include "wb_polar_coordinate.h"
Classes
struct wb_line_sighting
WHITEBOARD_POSTER_STRING_CONVERSION.
Macros
#define _XOPEN_SOURCE 700
#define LINE_SIGHTING_GENERATED
#define LINE_SIGHTING_C_STRUCT wb_line_sighting
#define LINE_SIGHTING_NUMBER_OF_VARIABLES 3
#define LINE_SIGHTING_DESC_BUFFER_SIZE 1575
#define LINE_SIGHTING_TO_STRING_BUFFER_SIZE 1541
Enumerations
enum LineSightingType { HorizonLineSightingType , FieldLineSightingType }
Functions
const char * wb_line_sighting_description (const struct wb_line_sighting *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_line_sighting_to_string (const struct wb_line_sighting *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_line_sighting * wb_line_sighting_from_string (struct wb_line_sighting *self, const char *str)
Convert from a string.
size_t wb_line_sighting_to_network_serialised (const struct wb_line_sighting *self, char *dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
size_t wb_line_sighting_from_network_serialised (const char *src, struct wb_line_sighting *dst)
Network stream deserialisation.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 72 of file wb_line_sighting.h.
LINE_SIGHTING_C_STRUCT
#define LINE_SIGHTING_C_STRUCT wb_line_sighting
Definition at line 96 of file wb_line_sighting.h.
LINE_SIGHTING_DESC_BUFFER_SIZE
#define LINE_SIGHTING_DESC_BUFFER_SIZE 1575
Definition at line 100 of file wb_line_sighting.h.
LINE_SIGHTING_GENERATED
#define LINE_SIGHTING_GENERATED
Definition at line 95 of file wb_line_sighting.h.
LINE_SIGHTING_NUMBER_OF_VARIABLES
#define LINE_SIGHTING_NUMBER_OF_VARIABLES 3
Definition at line 97 of file wb_line_sighting.h.
LINE_SIGHTING_TO_STRING_BUFFER_SIZE
#define LINE_SIGHTING_TO_STRING_BUFFER_SIZE 1541
Definition at line 101 of file wb_line_sighting.h.
Enumeration Type Documentation
LineSightingType
enum LineSightingType
Enumerator
HorizonLineSightingType
FieldLineSightingType
Definition at line 90 of file wb_line_sighting.h.
Function Documentation
wb_line_sighting_description()
const char * wb_line_sighting_description (const struct wb_line_sighting * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_line_sighting.c.
References FieldLineSightingType, HorizonLineSightingType, POLAR_COORDINATE_DESC_BUFFER_SIZE, and wb_polar_coordinate_description().
Referenced by guWhiteboard::LineSighting::description(), and wb_machine_filtered_lines_description().
wb_line_sighting_from_network_serialised()
size_t wb_line_sighting_from_network_serialised (const char * src, struct wb_line_sighting * dst)
Network stream deserialisation.
Network stream deserialisation.
Definition at line 405 of file wb_line_sighting.c.
References ntohl, and wb_line_sighting::sightingType.
wb_line_sighting_from_string()
struct wb_line_sighting * wb_line_sighting_from_string (struct wb_line_sighting * self, const char * str)
Convert from a string.
Definition at line 255 of file wb_line_sighting.c.
References FieldLineSightingType, HorizonLineSightingType, LINE_SIGHTING_DESC_BUFFER_SIZE, and wb_polar_coordinate_from_string().
Referenced by wb_machine_filtered_lines_from_string().
wb_line_sighting_to_network_serialised()
size_t wb_line_sighting_to_network_serialised (const struct wb_line_sighting * self, char * dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
Network stream serialisation
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 380 of file wb_line_sighting.c.
References htonl.
wb_line_sighting_to_string()
const char * wb_line_sighting_to_string (const struct wb_line_sighting * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 190 of file wb_line_sighting.c.
References FieldLineSightingType, HorizonLineSightingType, POLAR_COORDINATE_TO_STRING_BUFFER_SIZE, and wb_polar_coordinate_to_string().
Referenced by guWhiteboard::LineSighting::to_string(), and wb_machine_filtered_lines_to_string().