gusimplewhiteboard: typeClassDefs/wb_filtered_arrayonedimobjects.h File Reference
wb_filtered_arrayonedimobjects.h File Reference
#include <gu_util.h>
#include <stdint.h>
#include "wb_filtered_vision_object.h"
#include "wb_filtered_vision_object_type.h"
Classes
struct wb_filtered_arrayonedimobjects
The class of landmarks filtered regarding goal sightings.
Macros
#define _XOPEN_SOURCE 700
#define FILTERED_ARRAYONEDIMOBJECTS_GENERATED
#define FILTERED_ARRAYONEDIMOBJECTS_C_STRUCT wb_filtered_arrayonedimobjects
#define FILTERED_ARRAYONEDIMOBJECTS_NUMBER_OF_VARIABLES 1
#define FILTERED_ARRAYONEDIMOBJECTS_DESC_BUFFER_SIZE 521
#define FILTERED_ARRAYONEDIMOBJECTS_TO_STRING_BUFFER_SIZE 513
#define FILTERED_ARRAYONEDIMOBJECTS_OBJECTS_ARRAY_SIZE 4
WHITEBOARD_POSTER_STRING_CONVERSION.
Functions
const char * wb_filtered_arrayonedimobjects_description (const struct wb_filtered_arrayonedimobjects *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_filtered_arrayonedimobjects_to_string (const struct wb_filtered_arrayonedimobjects *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_filtered_arrayonedimobjects * wb_filtered_arrayonedimobjects_from_string (struct wb_filtered_arrayonedimobjects *self, const char *str)
Convert from a string.
size_t wb_filtered_arrayonedimobjects_to_network_serialised (const struct wb_filtered_arrayonedimobjects *self, char *dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
size_t wb_filtered_arrayonedimobjects_from_network_serialised (const char *src, struct wb_filtered_arrayonedimobjects *dst)
Network stream deserialisation.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 72 of file wb_filtered_arrayonedimobjects.h.
FILTERED_ARRAYONEDIMOBJECTS_C_STRUCT
#define FILTERED_ARRAYONEDIMOBJECTS_C_STRUCT wb_filtered_arrayonedimobjects
Definition at line 92 of file wb_filtered_arrayonedimobjects.h.
FILTERED_ARRAYONEDIMOBJECTS_DESC_BUFFER_SIZE
#define FILTERED_ARRAYONEDIMOBJECTS_DESC_BUFFER_SIZE 521
Definition at line 96 of file wb_filtered_arrayonedimobjects.h.
FILTERED_ARRAYONEDIMOBJECTS_GENERATED
#define FILTERED_ARRAYONEDIMOBJECTS_GENERATED
Definition at line 91 of file wb_filtered_arrayonedimobjects.h.
FILTERED_ARRAYONEDIMOBJECTS_NUMBER_OF_VARIABLES
#define FILTERED_ARRAYONEDIMOBJECTS_NUMBER_OF_VARIABLES 1
Definition at line 93 of file wb_filtered_arrayonedimobjects.h.
FILTERED_ARRAYONEDIMOBJECTS_OBJECTS_ARRAY_SIZE
#define FILTERED_ARRAYONEDIMOBJECTS_OBJECTS_ARRAY_SIZE 4
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 100 of file wb_filtered_arrayonedimobjects.h.
FILTERED_ARRAYONEDIMOBJECTS_TO_STRING_BUFFER_SIZE
#define FILTERED_ARRAYONEDIMOBJECTS_TO_STRING_BUFFER_SIZE 513
Definition at line 97 of file wb_filtered_arrayonedimobjects.h.
Function Documentation
wb_filtered_arrayonedimobjects_description()
const char * wb_filtered_arrayonedimobjects_description (const struct wb_filtered_arrayonedimobjects * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_filtered_arrayonedimobjects.c.
References FILTERED_ARRAYONEDIMOBJECTS_OBJECTS_ARRAY_SIZE, FILTERED_VISION_OBJECT_DESC_BUFFER_SIZE, and wb_filtered_vision_object_description().
Referenced by guWhiteboard::FilteredArrayOneDimObjects::description().
wb_filtered_arrayonedimobjects_from_network_serialised()
size_t wb_filtered_arrayonedimobjects_from_network_serialised (const char * src, struct wb_filtered_arrayonedimobjects * dst)
Network stream deserialisation.
Network stream deserialisation.
Definition at line 394 of file wb_filtered_arrayonedimobjects.c.
References wb_filtered_arrayonedimobjects::objects.
wb_filtered_arrayonedimobjects_from_string()
struct wb_filtered_arrayonedimobjects * wb_filtered_arrayonedimobjects_from_string (struct wb_filtered_arrayonedimobjects * self, const char * str)
Convert from a string.
Definition at line 205 of file wb_filtered_arrayonedimobjects.c.
References FILTERED_ARRAYONEDIMOBJECTS_DESC_BUFFER_SIZE, FILTERED_ARRAYONEDIMOBJECTS_OBJECTS_ARRAY_SIZE, and wb_filtered_vision_object_from_string().
wb_filtered_arrayonedimobjects_to_network_serialised()
size_t wb_filtered_arrayonedimobjects_to_network_serialised (const struct wb_filtered_arrayonedimobjects * self, char * dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
Network stream serialisation
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 362 of file wb_filtered_arrayonedimobjects.c.
wb_filtered_arrayonedimobjects_to_string()
const char * wb_filtered_arrayonedimobjects_to_string (const struct wb_filtered_arrayonedimobjects * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 165 of file wb_filtered_arrayonedimobjects.c.
References FILTERED_ARRAYONEDIMOBJECTS_OBJECTS_ARRAY_SIZE, FILTERED_VISION_OBJECT_TO_STRING_BUFFER_SIZE, and wb_filtered_vision_object_to_string().
Referenced by guWhiteboard::FilteredArrayOneDimObjects::to_string().