gusimplewhiteboard: typeClassDefs/wb_hal_leg_target.h File Reference
wb_hal_leg_target.h File Reference
#include <gu_util.h>
#include <stdint.h>
Classes
struct wb_hal_leg_target
WHITEBOARD_POSTER_STRING_CONVERSION.
Macros
#define _XOPEN_SOURCE 700
#define LEFT_LEG (static_cast<uint8_t>(0))
#define RIGHT_LEG (static_cast<uint8_t>(1))
#define HIP_YAWPITCH_LIMIT_BACK_DEG -65.62f
Issued Commands that exceed the movement limits given below are treated as NO-OP.
#define HIP_YAWPITCH_LIMIT_FRONT_DEG 42.44f
#define LEFT_HIP_ROLL_OUT_DEG 45.29f
#define LEFT_HIP_ROLL_IN_DEG -21.74f
#define LEFT_HIP_PITCH_FRONT_DEG -88.00f
#define LEFT_HIP_PITCH_BACK_DEG 27.73f
#define LEFT_KNEE_PITCH_FRONT_DEG -5.29f
#define LEFT_KNEE_PITCH_BACK_DEG 121.04f
#define LEFT_ANKLE_PITCH_FRONT_DEG -68.15f
#define LEFT_ANKLE_PITCH_BACK_DEG 52.86f
#define LEFT_ANKLE_ROLL_OUT_DEG 44.06f
#define LEFT_ANKLE_ROLL_IN_DEG -22.79f
#define RIGHT_HIP_ROLL_OUT_DEG -45.29f
#define RIGHT_HIP_ROLL_IN_DEG 21.74f
#define RIGHT_HIP_PITCH_FRONT_DEG -88.00f
#define RIGHT_HIP_PITCH_BACK_DEG 27.73f
#define RIGHT_KNEE_PITCH_FRONT_DEG -5.90f
#define RIGHT_KNEE_PITCH_BACK_DEG 121.47f
#define RIGHT_ANKLE_PITCH_FRONT_DEG -67.97f
#define RIGHT_ANKLE_PITCH_BACK_DEG 53.40f
#define RIGHT_ANKLE_ROLL_OUT_DEG -44.06f
#define RIGHT_ANKLE_ROLL_IN_DEG 22.80f
#define HIP_YAWPITCH_LIMIT_BACK_RAD -1.145303f
Limits expressed in radians.
#define HIP_YAWPITCH_LIMIT_FRONT_RAD 0.740810f
#define LEFT_HIP_ROLL_OUT_RAD 0.790477f
#define LEFT_HIP_ROLL_IN_RAD -0.379472f
#define LEFT_HIP_PITCH_FRONT_RAD -1.535889f
#define LEFT_HIP_PITCH_BACK_RAD 0.484090f
#define LEFT_KNEE_PITCH_FRONT_RAD -0.092346f
#define LEFT_KNEE_PITCH_BACK_RAD 2.112528f
#define LEFT_ANKLE_PITCH_FRONT_RAD -1.189516f
#define LEFT_ANKLE_PITCH_BACK_RAD 0.922747f
#define LEFT_ANKLE_ROLL_OUT_RAD 0.769001f
#define LEFT_ANKLE_ROLL_IN_RAD -0.397880f
#define RIGHT_HIP_ROLL_OUT_RAD -0.790477f
#define RIGHT_HIP_ROLL_IN_RAD 0.379472f
#define RIGHT_HIP_PITCH_FRONT_RAD -1.535889f
#define RIGHT_HIP_PITCH_BACK_RAD 0.484090f
#define RIGHT_KNEE_PITCH_FRONT_RAD -0.103083f
#define RIGHT_KNEE_PITCH_BACK_RAD 2.120198f
#define RIGHT_ANKLE_PITCH_FRONT_RAD -1.186448f
#define RIGHT_ANKLE_PITCH_BACK_RAD 0.932056f
#define RIGHT_ANKLE_ROLL_OUT_RAD -0.768992f
#define RIGHT_ANKLE_ROLL_IN_RAD 0.397935f
#define HAL_LEG_TARGET_GENERATED
#define HAL_LEG_TARGET_C_STRUCT wb_hal_leg_target
#define HAL_LEG_TARGET_NUMBER_OF_VARIABLES 23
#define HAL_LEG_TARGET_DESC_BUFFER_SIZE 691
#define HAL_LEG_TARGET_TO_STRING_BUFFER_SIZE 204
Functions
const char * wb_hal_leg_target_description (const struct wb_hal_leg_target *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_hal_leg_target_to_string (const struct wb_hal_leg_target *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_hal_leg_target * wb_hal_leg_target_from_string (struct wb_hal_leg_target *self, const char *str)
Convert from a string.
const char * wb_hal_leg_target_value_description (const struct wb_hal_leg_target *self, char *toString, size_t bufferSize)
WHITEBOARD_POSTER_STRING_CONVERSION.
size_t wb_hal_leg_target_to_network_serialised (const struct wb_hal_leg_target *self, char *dst)
Network stream serialisation.
size_t wb_hal_leg_target_from_network_serialised (const char *src, struct wb_hal_leg_target *dst)
Network stream deserialisation.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 72 of file wb_hal_leg_target.h.
HAL_LEG_TARGET_C_STRUCT
#define HAL_LEG_TARGET_C_STRUCT wb_hal_leg_target
Definition at line 156 of file wb_hal_leg_target.h.
HAL_LEG_TARGET_DESC_BUFFER_SIZE
#define HAL_LEG_TARGET_DESC_BUFFER_SIZE 691
Definition at line 160 of file wb_hal_leg_target.h.
HAL_LEG_TARGET_GENERATED
#define HAL_LEG_TARGET_GENERATED
Definition at line 155 of file wb_hal_leg_target.h.
HAL_LEG_TARGET_NUMBER_OF_VARIABLES
#define HAL_LEG_TARGET_NUMBER_OF_VARIABLES 23
Definition at line 157 of file wb_hal_leg_target.h.
HAL_LEG_TARGET_TO_STRING_BUFFER_SIZE
#define HAL_LEG_TARGET_TO_STRING_BUFFER_SIZE 204
Definition at line 161 of file wb_hal_leg_target.h.
HIP_YAWPITCH_LIMIT_BACK_DEG
#define HIP_YAWPITCH_LIMIT_BACK_DEG -65.62f
Issued Commands that exceed the movement limits given below are treated as NO-OP.
I.e. the pose of the joint is not altered by the command. Limits expressed in degrees (from Aldebaran Docs ./family/nao_h25/joints_h25.html)
Definition at line 104 of file wb_hal_leg_target.h.
HIP_YAWPITCH_LIMIT_BACK_RAD
#define HIP_YAWPITCH_LIMIT_BACK_RAD -1.145303f
Limits expressed in radians.
Definition at line 130 of file wb_hal_leg_target.h.
HIP_YAWPITCH_LIMIT_FRONT_DEG
#define HIP_YAWPITCH_LIMIT_FRONT_DEG 42.44f
Definition at line 105 of file wb_hal_leg_target.h.
HIP_YAWPITCH_LIMIT_FRONT_RAD
#define HIP_YAWPITCH_LIMIT_FRONT_RAD 0.740810f
Definition at line 131 of file wb_hal_leg_target.h.
LEFT_ANKLE_PITCH_BACK_DEG
#define LEFT_ANKLE_PITCH_BACK_DEG 52.86f
Definition at line 114 of file wb_hal_leg_target.h.
LEFT_ANKLE_PITCH_BACK_RAD
#define LEFT_ANKLE_PITCH_BACK_RAD 0.922747f
Definition at line 140 of file wb_hal_leg_target.h.
LEFT_ANKLE_PITCH_FRONT_DEG
#define LEFT_ANKLE_PITCH_FRONT_DEG -68.15f
Definition at line 113 of file wb_hal_leg_target.h.
LEFT_ANKLE_PITCH_FRONT_RAD
#define LEFT_ANKLE_PITCH_FRONT_RAD -1.189516f
Definition at line 139 of file wb_hal_leg_target.h.
LEFT_ANKLE_ROLL_IN_DEG
#define LEFT_ANKLE_ROLL_IN_DEG -22.79f
Definition at line 116 of file wb_hal_leg_target.h.
LEFT_ANKLE_ROLL_IN_RAD
#define LEFT_ANKLE_ROLL_IN_RAD -0.397880f
Definition at line 142 of file wb_hal_leg_target.h.
LEFT_ANKLE_ROLL_OUT_DEG
#define LEFT_ANKLE_ROLL_OUT_DEG 44.06f
Definition at line 115 of file wb_hal_leg_target.h.
LEFT_ANKLE_ROLL_OUT_RAD
#define LEFT_ANKLE_ROLL_OUT_RAD 0.769001f
Definition at line 141 of file wb_hal_leg_target.h.
LEFT_HIP_PITCH_BACK_DEG
#define LEFT_HIP_PITCH_BACK_DEG 27.73f
Definition at line 110 of file wb_hal_leg_target.h.
LEFT_HIP_PITCH_BACK_RAD
#define LEFT_HIP_PITCH_BACK_RAD 0.484090f
Definition at line 136 of file wb_hal_leg_target.h.
LEFT_HIP_PITCH_FRONT_DEG
#define LEFT_HIP_PITCH_FRONT_DEG -88.00f
Definition at line 109 of file wb_hal_leg_target.h.
LEFT_HIP_PITCH_FRONT_RAD
#define LEFT_HIP_PITCH_FRONT_RAD -1.535889f
Definition at line 135 of file wb_hal_leg_target.h.
LEFT_HIP_ROLL_IN_DEG
#define LEFT_HIP_ROLL_IN_DEG -21.74f
Definition at line 108 of file wb_hal_leg_target.h.
LEFT_HIP_ROLL_IN_RAD
#define LEFT_HIP_ROLL_IN_RAD -0.379472f
Definition at line 134 of file wb_hal_leg_target.h.
LEFT_HIP_ROLL_OUT_DEG
#define LEFT_HIP_ROLL_OUT_DEG 45.29f
Definition at line 107 of file wb_hal_leg_target.h.
LEFT_HIP_ROLL_OUT_RAD
#define LEFT_HIP_ROLL_OUT_RAD 0.790477f
Definition at line 133 of file wb_hal_leg_target.h.
LEFT_KNEE_PITCH_BACK_DEG
#define LEFT_KNEE_PITCH_BACK_DEG 121.04f
Definition at line 112 of file wb_hal_leg_target.h.
LEFT_KNEE_PITCH_BACK_RAD
#define LEFT_KNEE_PITCH_BACK_RAD 2.112528f
Definition at line 138 of file wb_hal_leg_target.h.
LEFT_KNEE_PITCH_FRONT_DEG
#define LEFT_KNEE_PITCH_FRONT_DEG -5.29f
Definition at line 111 of file wb_hal_leg_target.h.
LEFT_KNEE_PITCH_FRONT_RAD
#define LEFT_KNEE_PITCH_FRONT_RAD -0.092346f
Definition at line 137 of file wb_hal_leg_target.h.
LEFT_LEG
#define LEFT_LEG (static_cast<uint8_t>(0))
Definition at line 91 of file wb_hal_leg_target.h.
RIGHT_ANKLE_PITCH_BACK_DEG
#define RIGHT_ANKLE_PITCH_BACK_DEG 53.40f
Definition at line 125 of file wb_hal_leg_target.h.
RIGHT_ANKLE_PITCH_BACK_RAD
#define RIGHT_ANKLE_PITCH_BACK_RAD 0.932056f
Definition at line 151 of file wb_hal_leg_target.h.
RIGHT_ANKLE_PITCH_FRONT_DEG
#define RIGHT_ANKLE_PITCH_FRONT_DEG -67.97f
Definition at line 124 of file wb_hal_leg_target.h.
RIGHT_ANKLE_PITCH_FRONT_RAD
#define RIGHT_ANKLE_PITCH_FRONT_RAD -1.186448f
Definition at line 150 of file wb_hal_leg_target.h.
RIGHT_ANKLE_ROLL_IN_DEG
#define RIGHT_ANKLE_ROLL_IN_DEG 22.80f
Definition at line 127 of file wb_hal_leg_target.h.
RIGHT_ANKLE_ROLL_IN_RAD
#define RIGHT_ANKLE_ROLL_IN_RAD 0.397935f
Definition at line 153 of file wb_hal_leg_target.h.
RIGHT_ANKLE_ROLL_OUT_DEG
#define RIGHT_ANKLE_ROLL_OUT_DEG -44.06f
Definition at line 126 of file wb_hal_leg_target.h.
RIGHT_ANKLE_ROLL_OUT_RAD
#define RIGHT_ANKLE_ROLL_OUT_RAD -0.768992f
Definition at line 152 of file wb_hal_leg_target.h.
RIGHT_HIP_PITCH_BACK_DEG
#define RIGHT_HIP_PITCH_BACK_DEG 27.73f
Definition at line 121 of file wb_hal_leg_target.h.
RIGHT_HIP_PITCH_BACK_RAD
#define RIGHT_HIP_PITCH_BACK_RAD 0.484090f
Definition at line 147 of file wb_hal_leg_target.h.
RIGHT_HIP_PITCH_FRONT_DEG
#define RIGHT_HIP_PITCH_FRONT_DEG -88.00f
Definition at line 120 of file wb_hal_leg_target.h.
RIGHT_HIP_PITCH_FRONT_RAD
#define RIGHT_HIP_PITCH_FRONT_RAD -1.535889f
Definition at line 146 of file wb_hal_leg_target.h.
RIGHT_HIP_ROLL_IN_DEG
#define RIGHT_HIP_ROLL_IN_DEG 21.74f
Definition at line 119 of file wb_hal_leg_target.h.
RIGHT_HIP_ROLL_IN_RAD
#define RIGHT_HIP_ROLL_IN_RAD 0.379472f
Definition at line 145 of file wb_hal_leg_target.h.
RIGHT_HIP_ROLL_OUT_DEG
#define RIGHT_HIP_ROLL_OUT_DEG -45.29f
Definition at line 118 of file wb_hal_leg_target.h.
RIGHT_HIP_ROLL_OUT_RAD
#define RIGHT_HIP_ROLL_OUT_RAD -0.790477f
Definition at line 144 of file wb_hal_leg_target.h.
RIGHT_KNEE_PITCH_BACK_DEG
#define RIGHT_KNEE_PITCH_BACK_DEG 121.47f
Definition at line 123 of file wb_hal_leg_target.h.
RIGHT_KNEE_PITCH_BACK_RAD
#define RIGHT_KNEE_PITCH_BACK_RAD 2.120198f
Definition at line 149 of file wb_hal_leg_target.h.
RIGHT_KNEE_PITCH_FRONT_DEG
#define RIGHT_KNEE_PITCH_FRONT_DEG -5.90f
Definition at line 122 of file wb_hal_leg_target.h.
RIGHT_KNEE_PITCH_FRONT_RAD
#define RIGHT_KNEE_PITCH_FRONT_RAD -0.103083f
Definition at line 148 of file wb_hal_leg_target.h.
RIGHT_LEG
#define RIGHT_LEG (static_cast<uint8_t>(1))
Definition at line 92 of file wb_hal_leg_target.h.
Function Documentation
wb_hal_leg_target_description()
const char * wb_hal_leg_target_description (const struct wb_hal_leg_target * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 310 of file wb_hal_leg_target.c.
Referenced by guWhiteboard::HalLegTarget::description().
wb_hal_leg_target_from_network_serialised()
size_t wb_hal_leg_target_from_network_serialised (const char * src, struct wb_hal_leg_target * dst)
Network stream deserialisation.
Network stream deserialisation.
Definition at line 1229 of file wb_hal_leg_target.c.
References ntohl, ntohs, wb_hal_leg_target::target_anklepitch, wb_hal_leg_target::target_anklepitch_active, wb_hal_leg_target::target_anklepitchstiffness, wb_hal_leg_target::target_ankleroll, wb_hal_leg_target::target_ankleroll_active, wb_hal_leg_target::target_anklerollstiffness, wb_hal_leg_target::target_hippitch, wb_hal_leg_target::target_hippitch_active, wb_hal_leg_target::target_hippitchstiffness, wb_hal_leg_target::target_hiproll, wb_hal_leg_target::target_hiproll_active, wb_hal_leg_target::target_hiprollstiffness, wb_hal_leg_target::target_hipyawpitch, wb_hal_leg_target::target_hipyawpitch_active, wb_hal_leg_target::target_hipyawpitchstiffness, wb_hal_leg_target::target_kneepitch, wb_hal_leg_target::target_kneepitch_active, wb_hal_leg_target::target_kneepitchstiffness, wb_hal_leg_target::target_leg, wb_hal_leg_target::target_leg_at_goal, wb_hal_leg_target::target_leg_stop, wb_hal_leg_target::target_movement_time, and wb_hal_leg_target::target_pliability.
wb_hal_leg_target_from_string()
struct wb_hal_leg_target * wb_hal_leg_target_from_string (struct wb_hal_leg_target * self, const char * str)
Convert from a string.
Definition at line 694 of file wb_hal_leg_target.c.
References HAL_LEG_TARGET_DESC_BUFFER_SIZE.
wb_hal_leg_target_to_network_serialised()
size_t wb_hal_leg_target_to_network_serialised (const struct wb_hal_leg_target * self, char * dst)
Network stream serialisation.
Network stream serialisation.
Definition at line 944 of file wb_hal_leg_target.c.
References htonl, and htons.
wb_hal_leg_target_to_string()
const char * wb_hal_leg_target_to_string (const struct wb_hal_leg_target * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 502 of file wb_hal_leg_target.c.
Referenced by guWhiteboard::HalLegTarget::to_string().
wb_hal_leg_target_value_description()
const char * wb_hal_leg_target_value_description (const struct wb_hal_leg_target * self, char * toString, size_t bufferSize)
WHITEBOARD_POSTER_STRING_CONVERSION.
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 124 of file wb_hal_leg_target.c.
Referenced by guWhiteboard::HalLegTarget::valueDescription().