gusimplewhiteboard: typeClassDefs/wb_vision_detection_goal.h File Reference
wb_vision_detection_goal.h File Reference
#include <gu_util.h>
#include <stdint.h>
#include "wb_vision_detection_goal_post.h"
Classes
struct wb_vision_detection_goal
WHITEBOARD_POSTER_STRING_CONVERSION.
Macros
#define _XOPEN_SOURCE 700
#define VISION_DETECTION_GOAL_GENERATED
#define VISION_DETECTION_GOAL_C_STRUCT wb_vision_detection_goal
#define VISION_DETECTION_GOAL_NUMBER_OF_VARIABLES 3
#define VISION_DETECTION_GOAL_DESC_BUFFER_SIZE 1566
#define VISION_DETECTION_GOAL_TO_STRING_BUFFER_SIZE 1541
Enumerations
enum GoalOptions { NoGoalDetected = 0 , SinglePostGoal , DoublePostGoal }
Functions
const char * wb_vision_detection_goal_description (const struct wb_vision_detection_goal *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_vision_detection_goal_to_string (const struct wb_vision_detection_goal *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_vision_detection_goal * wb_vision_detection_goal_from_string (struct wb_vision_detection_goal *self, const char *str)
Convert from a string.
size_t wb_vision_detection_goal_to_network_serialised (const struct wb_vision_detection_goal *self, char *dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
size_t wb_vision_detection_goal_from_network_serialised (const char *src, struct wb_vision_detection_goal *dst)
Network stream deserialisation.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 72 of file wb_vision_detection_goal.h.
VISION_DETECTION_GOAL_C_STRUCT
#define VISION_DETECTION_GOAL_C_STRUCT wb_vision_detection_goal
Definition at line 98 of file wb_vision_detection_goal.h.
VISION_DETECTION_GOAL_DESC_BUFFER_SIZE
#define VISION_DETECTION_GOAL_DESC_BUFFER_SIZE 1566
Definition at line 102 of file wb_vision_detection_goal.h.
VISION_DETECTION_GOAL_GENERATED
#define VISION_DETECTION_GOAL_GENERATED
Definition at line 97 of file wb_vision_detection_goal.h.
VISION_DETECTION_GOAL_NUMBER_OF_VARIABLES
#define VISION_DETECTION_GOAL_NUMBER_OF_VARIABLES 3
Definition at line 99 of file wb_vision_detection_goal.h.
VISION_DETECTION_GOAL_TO_STRING_BUFFER_SIZE
#define VISION_DETECTION_GOAL_TO_STRING_BUFFER_SIZE 1541
Definition at line 103 of file wb_vision_detection_goal.h.
Enumeration Type Documentation
GoalOptions
enum GoalOptions
Enumerator
NoGoalDetected
SinglePostGoal
DoublePostGoal
Definition at line 91 of file wb_vision_detection_goal.h.
Function Documentation
wb_vision_detection_goal_description()
const char * wb_vision_detection_goal_description (const struct wb_vision_detection_goal * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_vision_detection_goal.c.
References DoublePostGoal, NoGoalDetected, SinglePostGoal, VISION_DETECTION_GOAL_POST_DESC_BUFFER_SIZE, and wb_vision_detection_goal_post_description().
Referenced by guWhiteboard::VisionDetectionGoal::description(), and wb_vision_detection_goals_description().
wb_vision_detection_goal_from_network_serialised()
size_t wb_vision_detection_goal_from_network_serialised (const char * src, struct wb_vision_detection_goal * dst)
Network stream deserialisation.
Network stream deserialisation.
Definition at line 420 of file wb_vision_detection_goal.c.
References ntohl, and wb_vision_detection_goal::sightingType.
wb_vision_detection_goal_from_string()
struct wb_vision_detection_goal * wb_vision_detection_goal_from_string (struct wb_vision_detection_goal * self, const char * str)
Convert from a string.
Definition at line 265 of file wb_vision_detection_goal.c.
References DoublePostGoal, NoGoalDetected, SinglePostGoal, VISION_DETECTION_GOAL_DESC_BUFFER_SIZE, and wb_vision_detection_goal_post_from_string().
Referenced by wb_vision_detection_goals_from_string().
wb_vision_detection_goal_to_network_serialised()
size_t wb_vision_detection_goal_to_network_serialised (const struct wb_vision_detection_goal * self, char * dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
Network stream serialisation
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 395 of file wb_vision_detection_goal.c.
References htonl.
wb_vision_detection_goal_to_string()
const char * wb_vision_detection_goal_to_string (const struct wb_vision_detection_goal * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 195 of file wb_vision_detection_goal.c.
References DoublePostGoal, NoGoalDetected, SinglePostGoal, VISION_DETECTION_GOAL_POST_TO_STRING_BUFFER_SIZE, and wb_vision_detection_goal_post_to_string().
Referenced by guWhiteboard::VisionDetectionGoal::to_string(), and wb_vision_detection_goals_to_string().