gusimplewhiteboard: typeClassDefs/wb_vision_detection_line_array.c File Reference
wb_vision_detection_line_array.c File Reference
#include "wb_vision_detection_line_array.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <limits.h>
Macros
#define htonll(x) bswap_64(x)
#define ntohll(x) bswap_64(x)
#define htonl(x) bswap_32(x)
#define ntohl(x) bswap_32(x)
#define htons(x) bswap_16(x)
#define ntohs(x) bswap_16(x)
Functions
const char * wb_vision_detection_line_array_description (const struct wb_vision_detection_line_array *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_vision_detection_line_array_to_string (const struct wb_vision_detection_line_array *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_vision_detection_line_array * wb_vision_detection_line_array_from_string (struct wb_vision_detection_line_array *self, const char *str)
Convert from a string.
size_t wb_vision_detection_line_array_to_network_serialised (const struct wb_vision_detection_line_array *self, char *dst)
Convert to a compressed, serialised, network byte order byte stream.
size_t wb_vision_detection_line_array_from_network_serialised (const char *src, struct wb_vision_detection_line_array *dst)
Convert from a compressed, serialised, network byte order byte stream.
Macro Definition Documentation
htonl
#define htonl (x) bswap_32(x)
Definition at line 97 of file wb_vision_detection_line_array.c.
htonll
#define htonll (x) bswap_64(x)
Definition at line 93 of file wb_vision_detection_line_array.c.
htons
#define htons (x) bswap_16(x)
Definition at line 101 of file wb_vision_detection_line_array.c.
ntohl
#define ntohl (x) bswap_32(x)
Definition at line 98 of file wb_vision_detection_line_array.c.
ntohll
#define ntohll (x) bswap_64(x)
Definition at line 94 of file wb_vision_detection_line_array.c.
ntohs
#define ntohs (x) bswap_16(x)
Definition at line 102 of file wb_vision_detection_line_array.c.
Function Documentation
wb_vision_detection_line_array_description()
const char * wb_vision_detection_line_array_description (const struct wb_vision_detection_line_array * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_vision_detection_line_array.c.
References PIXEL_COORDINATE_LINE_DESC_BUFFER_SIZE, VISION_DETECTION_LINE_ARRAY_LINES_ARRAY_SIZE, and wb_pixel_coordinate_line_description().
Referenced by guWhiteboard::VisionDetectionLineArray::description(), and wb_vision_detection_lines_description().
wb_vision_detection_line_array_from_network_serialised()
size_t wb_vision_detection_line_array_from_network_serialised (const char * src, struct wb_vision_detection_line_array * dst)
Convert from a compressed, serialised, network byte order byte stream.
Network stream deserialisation.
Definition at line 431 of file wb_vision_detection_line_array.c.
References wb_vision_detection_line_array::lines, and wb_vision_detection_line_array::numLines.
wb_vision_detection_line_array_from_string()
struct wb_vision_detection_line_array * wb_vision_detection_line_array_from_string (struct wb_vision_detection_line_array * self, const char * str)
Convert from a string.
Definition at line 221 of file wb_vision_detection_line_array.c.
References VISION_DETECTION_LINE_ARRAY_DESC_BUFFER_SIZE, VISION_DETECTION_LINE_ARRAY_LINES_ARRAY_SIZE, and wb_pixel_coordinate_line_from_string().
Referenced by wb_vision_detection_lines_from_string().
wb_vision_detection_line_array_to_network_serialised()
size_t wb_vision_detection_line_array_to_network_serialised (const struct wb_vision_detection_line_array * self, char * dst)
Convert to a compressed, serialised, network byte order byte stream.
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 385 of file wb_vision_detection_line_array.c.
wb_vision_detection_line_array_to_string()
const char * wb_vision_detection_line_array_to_string (const struct wb_vision_detection_line_array * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 173 of file wb_vision_detection_line_array.c.
References PIXEL_COORDINATE_LINE_TO_STRING_BUFFER_SIZE, VISION_DETECTION_LINE_ARRAY_LINES_ARRAY_SIZE, and wb_pixel_coordinate_line_to_string().
Referenced by guWhiteboard::VisionDetectionLineArray::to_string(), and wb_vision_detection_lines_to_string().