gusimplewhiteboard: typeClassDefs/wb_vision_detection_goal_post.c File Reference
wb_vision_detection_goal_post.c File Reference
#include "wb_vision_detection_goal_post.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <limits.h>
Macros
#define htonll(x) bswap_64(x)
#define ntohll(x) bswap_64(x)
#define htonl(x) bswap_32(x)
#define ntohl(x) bswap_32(x)
#define htons(x) bswap_16(x)
#define ntohs(x) bswap_16(x)
Functions
const char * wb_vision_detection_goal_post_description (const struct wb_vision_detection_goal_post *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_vision_detection_goal_post_to_string (const struct wb_vision_detection_goal_post *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_vision_detection_goal_post * wb_vision_detection_goal_post_from_string (struct wb_vision_detection_goal_post *self, const char *str)
Convert from a string.
size_t wb_vision_detection_goal_post_to_network_serialised (const struct wb_vision_detection_goal_post *self, char *dst)
Convert to a compressed, serialised, network byte order byte stream.
size_t wb_vision_detection_goal_post_from_network_serialised (const char *src, struct wb_vision_detection_goal_post *dst)
Convert from a compressed, serialised, network byte order byte stream.
gu_pixel_coordinate wb_vision_detection_goal_post_topLeftCoordinate_px_coord (const struct wb_vision_detection_goal_post self, const uint16_t resWidth, const uint16_t resHeight)
WHITEBOARD_POSTER_STRING_CONVERSION.
gu_pixel_coordinate wb_vision_detection_goal_post_topRightCoordinate_px_coord (const struct wb_vision_detection_goal_post self, const uint16_t resWidth, const uint16_t resHeight)
gu_pixel_coordinate wb_vision_detection_goal_post_bottomLeftCoordinate_px_coord (const struct wb_vision_detection_goal_post self, const uint16_t resWidth, const uint16_t resHeight)
gu_pixel_coordinate wb_vision_detection_goal_post_bottomRightCoordinate_px_coord (const struct wb_vision_detection_goal_post self, const uint16_t resWidth, const uint16_t resHeight)
Macro Definition Documentation
htonl
#define htonl (x) bswap_32(x)
Definition at line 97 of file wb_vision_detection_goal_post.c.
htonll
#define htonll (x) bswap_64(x)
Definition at line 93 of file wb_vision_detection_goal_post.c.
htons
#define htons (x) bswap_16(x)
Definition at line 101 of file wb_vision_detection_goal_post.c.
ntohl
#define ntohl (x) bswap_32(x)
Definition at line 98 of file wb_vision_detection_goal_post.c.
ntohll
#define ntohll (x) bswap_64(x)
Definition at line 94 of file wb_vision_detection_goal_post.c.
ntohs
#define ntohs (x) bswap_16(x)
Definition at line 102 of file wb_vision_detection_goal_post.c.
Function Documentation
wb_vision_detection_goal_post_bottomLeftCoordinate_px_coord()
gu_pixel_coordinate wb_vision_detection_goal_post_bottomLeftCoordinate_px_coord (const struct wb_vision_detection_goal_post self, const uint16_t resWidth, const uint16_t resHeight)
Definition at line 647 of file wb_vision_detection_goal_post.c.
References wb_vision_detection_goal_post::bottomLeftCoordinate, and wb_px_coord_to_px_coord().
wb_vision_detection_goal_post_bottomRightCoordinate_px_coord()
gu_pixel_coordinate wb_vision_detection_goal_post_bottomRightCoordinate_px_coord (const struct wb_vision_detection_goal_post self, const uint16_t resWidth, const uint16_t resHeight)
Definition at line 651 of file wb_vision_detection_goal_post.c.
References wb_vision_detection_goal_post::bottomRightCoordinate, and wb_px_coord_to_px_coord().
wb_vision_detection_goal_post_description()
const char * wb_vision_detection_goal_post_description (const struct wb_vision_detection_goal_post * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_vision_detection_goal_post.c.
References FullPostSeen, GenericPost, LeftPost, NoPostDetected, PartialPostSeen, PIXEL_COORDINATE_DESC_BUFFER_SIZE, RightPost, and wb_pixel_coordinate_description().
Referenced by guWhiteboard::VisionDetectionGoalPost::description(), and wb_vision_detection_goal_description().
wb_vision_detection_goal_post_from_network_serialised()
size_t wb_vision_detection_goal_post_from_network_serialised (const char * src, struct wb_vision_detection_goal_post * dst)
Convert from a compressed, serialised, network byte order byte stream.
Network stream deserialisation.
Definition at line 599 of file wb_vision_detection_goal_post.c.
References ntohl, wb_vision_detection_goal_post::orientation, and wb_vision_detection_goal_post::sightingType.
wb_vision_detection_goal_post_from_string()
struct wb_vision_detection_goal_post * wb_vision_detection_goal_post_from_string (struct wb_vision_detection_goal_post * self, const char * str)
Convert from a string.
Definition at line 389 of file wb_vision_detection_goal_post.c.
References FullPostSeen, GenericPost, LeftPost, NoPostDetected, PartialPostSeen, RightPost, VISION_DETECTION_GOAL_POST_DESC_BUFFER_SIZE, and wb_pixel_coordinate_from_string().
Referenced by wb_vision_detection_goal_from_string().
wb_vision_detection_goal_post_to_network_serialised()
size_t wb_vision_detection_goal_post_to_network_serialised (const struct wb_vision_detection_goal_post * self, char * dst)
Convert to a compressed, serialised, network byte order byte stream.
Network stream serialisation.
Definition at line 560 of file wb_vision_detection_goal_post.c.
References htonl.
wb_vision_detection_goal_post_to_string()
const char * wb_vision_detection_goal_post_to_string (const struct wb_vision_detection_goal_post * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 257 of file wb_vision_detection_goal_post.c.
References FullPostSeen, GenericPost, LeftPost, NoPostDetected, PartialPostSeen, PIXEL_COORDINATE_TO_STRING_BUFFER_SIZE, RightPost, and wb_pixel_coordinate_to_string().
Referenced by guWhiteboard::VisionDetectionGoalPost::to_string(), and wb_vision_detection_goal_to_string().
wb_vision_detection_goal_post_topLeftCoordinate_px_coord()
gu_pixel_coordinate wb_vision_detection_goal_post_topLeftCoordinate_px_coord (const struct wb_vision_detection_goal_post self, const uint16_t resWidth, const uint16_t resHeight)
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 639 of file wb_vision_detection_goal_post.c.
References wb_vision_detection_goal_post::topLeftCoordinate, and wb_px_coord_to_px_coord().
wb_vision_detection_goal_post_topRightCoordinate_px_coord()
gu_pixel_coordinate wb_vision_detection_goal_post_topRightCoordinate_px_coord (const struct wb_vision_detection_goal_post self, const uint16_t resWidth, const uint16_t resHeight)
Definition at line 643 of file wb_vision_detection_goal_post.c.
References wb_vision_detection_goal_post::topRightCoordinate, and wb_px_coord_to_px_coord().