gusimplewhiteboard: typeClassDefs/wb_vision_detection_horizon.h File Reference
wb_vision_detection_horizon.h File Reference
#include <gu_util.h>
#include <stdint.h>
#include "wb_pixel_coordinate.h"
#include <guunits/guunits.h>
#include <gucoordinates/gucoordinates.h>
Classes
struct wb_vision_detection_horizon
WHITEBOARD_POSTER_STRING_CONVERSION.
Macros
#define _XOPEN_SOURCE 700
#define VISION_DETECTION_HORIZON_GENERATED
#define VISION_DETECTION_HORIZON_C_STRUCT wb_vision_detection_horizon
#define VISION_DETECTION_HORIZON_NUMBER_OF_VARIABLES 4
#define VISION_DETECTION_HORIZON_DESC_BUFFER_SIZE 2115
#define VISION_DETECTION_HORIZON_TO_STRING_BUFFER_SIZE 2055
Enumerations
enum HorizonOptions { OnlyField = 0 , SingleHorizon , CornerHorizon , HorizonFailed }
Functions
const char * wb_vision_detection_horizon_description (const struct wb_vision_detection_horizon *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_vision_detection_horizon_to_string (const struct wb_vision_detection_horizon *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_vision_detection_horizon * wb_vision_detection_horizon_from_string (struct wb_vision_detection_horizon *self, const char *str)
Convert from a string.
gu_pixel_coordinate wb_vision_detection_horizon_leftCoordinate_px_coord (const struct wb_vision_detection_horizon self, const uint16_t resWidth, const uint16_t resHeight)
WHITEBOARD_POSTER_STRING_CONVERSION.
gu_pixel_coordinate wb_vision_detection_horizon_centerCoordinate_px_coord (const struct wb_vision_detection_horizon self, const uint16_t resWidth, const uint16_t resHeight)
gu_pixel_coordinate wb_vision_detection_horizon_rightCoordinate_px_coord (const struct wb_vision_detection_horizon self, const uint16_t resWidth, const uint16_t resHeight)
size_t wb_vision_detection_horizon_to_network_serialised (const struct wb_vision_detection_horizon *self, char *dst)
Network stream serialisation.
size_t wb_vision_detection_horizon_from_network_serialised (const char *src, struct wb_vision_detection_horizon *dst)
Network stream deserialisation.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 72 of file wb_vision_detection_horizon.h.
VISION_DETECTION_HORIZON_C_STRUCT
#define VISION_DETECTION_HORIZON_C_STRUCT wb_vision_detection_horizon
Definition at line 110 of file wb_vision_detection_horizon.h.
VISION_DETECTION_HORIZON_DESC_BUFFER_SIZE
#define VISION_DETECTION_HORIZON_DESC_BUFFER_SIZE 2115
Definition at line 114 of file wb_vision_detection_horizon.h.
VISION_DETECTION_HORIZON_GENERATED
#define VISION_DETECTION_HORIZON_GENERATED
Definition at line 109 of file wb_vision_detection_horizon.h.
VISION_DETECTION_HORIZON_NUMBER_OF_VARIABLES
#define VISION_DETECTION_HORIZON_NUMBER_OF_VARIABLES 4
Definition at line 111 of file wb_vision_detection_horizon.h.
VISION_DETECTION_HORIZON_TO_STRING_BUFFER_SIZE
#define VISION_DETECTION_HORIZON_TO_STRING_BUFFER_SIZE 2055
Definition at line 115 of file wb_vision_detection_horizon.h.
Enumeration Type Documentation
HorizonOptions
enum HorizonOptions
Enumerator
OnlyField
SingleHorizon
CornerHorizon
HorizonFailed
Definition at line 90 of file wb_vision_detection_horizon.h.
Function Documentation
wb_vision_detection_horizon_centerCoordinate_px_coord()
gu_pixel_coordinate wb_vision_detection_horizon_centerCoordinate_px_coord (const struct wb_vision_detection_horizon self, const uint16_t resWidth, const uint16_t resHeight)
Definition at line 509 of file wb_vision_detection_horizon.c.
References wb_vision_detection_horizon::centerCoordinate, and wb_px_coord_to_px_coord().
wb_vision_detection_horizon_description()
const char * wb_vision_detection_horizon_description (const struct wb_vision_detection_horizon * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_vision_detection_horizon.c.
References CornerHorizon, HorizonFailed, OnlyField, PIXEL_COORDINATE_DESC_BUFFER_SIZE, SingleHorizon, and wb_pixel_coordinate_description().
Referenced by guWhiteboard::VisionDetectionHorizon::description(), and wb_vision_detection_horizons_description().
wb_vision_detection_horizon_from_network_serialised()
size_t wb_vision_detection_horizon_from_network_serialised (const char * src, struct wb_vision_detection_horizon * dst)
Network stream deserialisation.
Network stream deserialisation.
Definition at line 480 of file wb_vision_detection_horizon.c.
References wb_vision_detection_horizon::horizonType, and ntohl.
wb_vision_detection_horizon_from_string()
struct wb_vision_detection_horizon * wb_vision_detection_horizon_from_string (struct wb_vision_detection_horizon * self, const char * str)
Convert from a string.
Definition at line 313 of file wb_vision_detection_horizon.c.
References CornerHorizon, HorizonFailed, OnlyField, SingleHorizon, VISION_DETECTION_HORIZON_DESC_BUFFER_SIZE, and wb_pixel_coordinate_from_string().
Referenced by wb_vision_detection_horizons_from_string().
wb_vision_detection_horizon_leftCoordinate_px_coord()
gu_pixel_coordinate wb_vision_detection_horizon_leftCoordinate_px_coord (const struct wb_vision_detection_horizon self, const uint16_t resWidth, const uint16_t resHeight)
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 505 of file wb_vision_detection_horizon.c.
References wb_vision_detection_horizon::leftCoordinate, and wb_px_coord_to_px_coord().
wb_vision_detection_horizon_rightCoordinate_px_coord()
gu_pixel_coordinate wb_vision_detection_horizon_rightCoordinate_px_coord (const struct wb_vision_detection_horizon self, const uint16_t resWidth, const uint16_t resHeight)
Definition at line 513 of file wb_vision_detection_horizon.c.
References wb_vision_detection_horizon::rightCoordinate, and wb_px_coord_to_px_coord().
wb_vision_detection_horizon_to_network_serialised()
size_t wb_vision_detection_horizon_to_network_serialised (const struct wb_vision_detection_horizon * self, char * dst)
Network stream serialisation.
Network stream serialisation.
Definition at line 455 of file wb_vision_detection_horizon.c.
References htonl.
wb_vision_detection_horizon_to_string()
const char * wb_vision_detection_horizon_to_string (const struct wb_vision_detection_horizon * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 219 of file wb_vision_detection_horizon.c.
References CornerHorizon, HorizonFailed, OnlyField, PIXEL_COORDINATE_TO_STRING_BUFFER_SIZE, SingleHorizon, and wb_pixel_coordinate_to_string().
Referenced by guWhiteboard::VisionDetectionHorizon::to_string(), and wb_vision_detection_horizons_to_string().