gusimplewhiteboard: typeClassDefs/wb_top_particles.h File Reference
wb_top_particles.h File Reference
#include <gu_util.h>
#include <stdint.h>
#include "wb_particle_position.h"
Classes
struct wb_top_particles
The class of the top particles in a Localization Filter.
Macros
#define _XOPEN_SOURCE 700
#define TOPPARTICLES_GENERATED
#define TOPPARTICLES_C_STRUCT wb_top_particles
#define TOPPARTICLES_NUMBER_OF_VARIABLES 1
#define TOPPARTICLES_DESC_BUFFER_SIZE 523
#define TOPPARTICLES_TO_STRING_BUFFER_SIZE 513
#define TOPPARTICLES_PARTICLES_ARRAY_SIZE 4
WHITEBOARD_POSTER_STRING_CONVERSION.
Enumerations
enum PF_ControlStatus_Modes {
PF_Running =0 , PF_New_Game , PF_After_Penalized , PF_After_Fall ,
PF_Manual_Placement
}
commands to set the Grid Particle Filer Status
Functions
const char * wb_top_particles_description (const struct wb_top_particles *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_top_particles_to_string (const struct wb_top_particles *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_top_particles * wb_top_particles_from_string (struct wb_top_particles *self, const char *str)
Convert from a string.
size_t wb_top_particles_to_network_serialised (const struct wb_top_particles *self, char *dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
size_t wb_top_particles_from_network_serialised (const char *src, struct wb_top_particles *dst)
Network stream deserialisation.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 72 of file wb_top_particles.h.
TOPPARTICLES_C_STRUCT
#define TOPPARTICLES_C_STRUCT wb_top_particles
Definition at line 104 of file wb_top_particles.h.
TOPPARTICLES_DESC_BUFFER_SIZE
#define TOPPARTICLES_DESC_BUFFER_SIZE 523
Definition at line 108 of file wb_top_particles.h.
TOPPARTICLES_GENERATED
#define TOPPARTICLES_GENERATED
Definition at line 103 of file wb_top_particles.h.
TOPPARTICLES_NUMBER_OF_VARIABLES
#define TOPPARTICLES_NUMBER_OF_VARIABLES 1
Definition at line 105 of file wb_top_particles.h.
TOPPARTICLES_PARTICLES_ARRAY_SIZE
#define TOPPARTICLES_PARTICLES_ARRAY_SIZE 4
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 112 of file wb_top_particles.h.
TOPPARTICLES_TO_STRING_BUFFER_SIZE
#define TOPPARTICLES_TO_STRING_BUFFER_SIZE 513
Definition at line 109 of file wb_top_particles.h.
Enumeration Type Documentation
PF_ControlStatus_Modes
enum PF_ControlStatus_Modes
commands to set the Grid Particle Filer Status
Enumerator
PF_Running
PF is running.
PF_New_Game
A FSM should set this, the PF is reset as per playerNumber.
PF_After_Penalized
Sides of our field are the reset positions.
PF_After_Fall
headings are reset randomly
PF_Manual_Placement
maybe after 34 seconds and manual placelemnt
Definition at line 93 of file wb_top_particles.h.
Function Documentation
wb_top_particles_description()
const char * wb_top_particles_description (const struct wb_top_particles * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_top_particles.c.
References PARTICLE_POSITION_DESC_BUFFER_SIZE, TOPPARTICLES_PARTICLES_ARRAY_SIZE, and wb_particle_position_description().
Referenced by guWhiteboard::TopParticles::description().
wb_top_particles_from_network_serialised()
size_t wb_top_particles_from_network_serialised (const char * src, struct wb_top_particles * dst)
Network stream deserialisation.
Network stream deserialisation.
Definition at line 394 of file wb_top_particles.c.
References wb_top_particles::particles.
wb_top_particles_from_string()
struct wb_top_particles * wb_top_particles_from_string (struct wb_top_particles * self, const char * str)
Convert from a string.
Definition at line 205 of file wb_top_particles.c.
References TOPPARTICLES_DESC_BUFFER_SIZE, TOPPARTICLES_PARTICLES_ARRAY_SIZE, and wb_particle_position_from_string().
wb_top_particles_to_network_serialised()
size_t wb_top_particles_to_network_serialised (const struct wb_top_particles * self, char * dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
Network stream serialisation
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 362 of file wb_top_particles.c.
wb_top_particles_to_string()
const char * wb_top_particles_to_string (const struct wb_top_particles * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 165 of file wb_top_particles.c.
References PARTICLE_POSITION_TO_STRING_BUFFER_SIZE, TOPPARTICLES_PARTICLES_ARRAY_SIZE, and wb_particle_position_to_string().
Referenced by guWhiteboard::TopParticles::to_string().