gusimplewhiteboard: typeClassDefs/wb_vision_detection_features.h File Reference
wb_vision_detection_features.h File Reference
#include <gu_util.h>
#include <stdint.h>
#include "wb_vision_detection_feature_array.h"
Classes
struct wb_vision_detection_features
Results for the Feature Detector (guvision).
Macros
#define _XOPEN_SOURCE 700
#define VISION_DETECTION_FEATURES_GENERATED
#define VISION_DETECTION_FEATURES_C_STRUCT wb_vision_detection_features
#define VISION_DETECTION_FEATURES_NUMBER_OF_VARIABLES 2
#define VISION_DETECTION_FEATURES_DESC_BUFFER_SIZE 556
#define VISION_DETECTION_FEATURES_TO_STRING_BUFFER_SIZE 535
#define VISION_DETECTION_FEATURES_FEATURES_ARRAY_SIZE 2
WHITEBOARD_POSTER_STRING_CONVERSION.
Functions
const char * wb_vision_detection_features_description (const struct wb_vision_detection_features *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_vision_detection_features_to_string (const struct wb_vision_detection_features *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_vision_detection_features * wb_vision_detection_features_from_string (struct wb_vision_detection_features *self, const char *str)
Convert from a string.
size_t wb_vision_detection_features_to_network_serialised (const struct wb_vision_detection_features *self, char *dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
size_t wb_vision_detection_features_from_network_serialised (const char *src, struct wb_vision_detection_features *dst)
Network stream deserialisation.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 72 of file wb_vision_detection_features.h.
VISION_DETECTION_FEATURES_C_STRUCT
#define VISION_DETECTION_FEATURES_C_STRUCT wb_vision_detection_features
Definition at line 91 of file wb_vision_detection_features.h.
VISION_DETECTION_FEATURES_DESC_BUFFER_SIZE
#define VISION_DETECTION_FEATURES_DESC_BUFFER_SIZE 556
Definition at line 95 of file wb_vision_detection_features.h.
VISION_DETECTION_FEATURES_FEATURES_ARRAY_SIZE
#define VISION_DETECTION_FEATURES_FEATURES_ARRAY_SIZE 2
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 99 of file wb_vision_detection_features.h.
VISION_DETECTION_FEATURES_GENERATED
#define VISION_DETECTION_FEATURES_GENERATED
Definition at line 90 of file wb_vision_detection_features.h.
VISION_DETECTION_FEATURES_NUMBER_OF_VARIABLES
#define VISION_DETECTION_FEATURES_NUMBER_OF_VARIABLES 2
Definition at line 92 of file wb_vision_detection_features.h.
VISION_DETECTION_FEATURES_TO_STRING_BUFFER_SIZE
#define VISION_DETECTION_FEATURES_TO_STRING_BUFFER_SIZE 535
Definition at line 96 of file wb_vision_detection_features.h.
Function Documentation
wb_vision_detection_features_description()
const char * wb_vision_detection_features_description (const struct wb_vision_detection_features * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_vision_detection_features.c.
References VISION_DETECTION_FEATURE_ARRAY_DESC_BUFFER_SIZE, VISION_DETECTION_FEATURES_FEATURES_ARRAY_SIZE, and wb_vision_detection_feature_array_description().
Referenced by guWhiteboard::VisionDetectionFeatures::description().
wb_vision_detection_features_from_network_serialised()
size_t wb_vision_detection_features_from_network_serialised (const char * src, struct wb_vision_detection_features * dst)
Network stream deserialisation.
Network stream deserialisation.
Definition at line 443 of file wb_vision_detection_features.c.
References wb_vision_detection_features::features, wb_vision_detection_features::frameNumber, and ntohll.
wb_vision_detection_features_from_string()
struct wb_vision_detection_features * wb_vision_detection_features_from_string (struct wb_vision_detection_features * self, const char * str)
Convert from a string.
Definition at line 229 of file wb_vision_detection_features.c.
References VISION_DETECTION_FEATURES_DESC_BUFFER_SIZE, VISION_DETECTION_FEATURES_FEATURES_ARRAY_SIZE, and wb_vision_detection_feature_array_from_string().
wb_vision_detection_features_to_network_serialised()
size_t wb_vision_detection_features_to_network_serialised (const struct wb_vision_detection_features * self, char * dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
Network stream serialisation
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 397 of file wb_vision_detection_features.c.
References htonll.
wb_vision_detection_features_to_string()
const char * wb_vision_detection_features_to_string (const struct wb_vision_detection_features * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 177 of file wb_vision_detection_features.c.
References VISION_DETECTION_FEATURE_ARRAY_TO_STRING_BUFFER_SIZE, VISION_DETECTION_FEATURES_FEATURES_ARRAY_SIZE, and wb_vision_detection_feature_array_to_string().
Referenced by guWhiteboard::VisionDetectionFeatures::to_string().