gusimplewhiteboard: typeClassDefs/wb_filtered_vision_object.c File Reference
wb_filtered_vision_object.c File Reference
#include "wb_filtered_vision_object.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <limits.h>
Macros
#define htonll(x) bswap_64(x)
#define ntohll(x) bswap_64(x)
#define htonl(x) bswap_32(x)
#define ntohl(x) bswap_32(x)
#define htons(x) bswap_16(x)
#define ntohs(x) bswap_16(x)
Functions
const char * wb_filtered_vision_object_description (const struct wb_filtered_vision_object *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_filtered_vision_object_to_string (const struct wb_filtered_vision_object *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_filtered_vision_object * wb_filtered_vision_object_from_string (struct wb_filtered_vision_object *self, const char *str)
Convert from a string.
size_t wb_filtered_vision_object_to_network_serialised (const struct wb_filtered_vision_object *self, char *dst)
Convert to a compressed, serialised, network byte order byte stream.
size_t wb_filtered_vision_object_from_network_serialised (const char *src, struct wb_filtered_vision_object *dst)
Convert from a compressed, serialised, network byte order byte stream.
Macro Definition Documentation
htonl
#define htonl (x) bswap_32(x)
Definition at line 97 of file wb_filtered_vision_object.c.
htonll
#define htonll (x) bswap_64(x)
Definition at line 93 of file wb_filtered_vision_object.c.
htons
#define htons (x) bswap_16(x)
Definition at line 101 of file wb_filtered_vision_object.c.
ntohl
#define ntohl (x) bswap_32(x)
Definition at line 98 of file wb_filtered_vision_object.c.
ntohll
#define ntohll (x) bswap_64(x)
Definition at line 94 of file wb_filtered_vision_object.c.
ntohs
#define ntohs (x) bswap_16(x)
Definition at line 102 of file wb_filtered_vision_object.c.
Function Documentation
wb_filtered_vision_object_description()
const char * wb_filtered_vision_object_description (const struct wb_filtered_vision_object * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_filtered_vision_object.c.
Referenced by guWhiteboard::FilteredVisionObject::description(), wb_filtered_arrayballsightings_description(), and wb_filtered_arrayonedimobjects_description().
wb_filtered_vision_object_from_network_serialised()
size_t wb_filtered_vision_object_from_network_serialised (const char * src, struct wb_filtered_vision_object * dst)
Convert from a compressed, serialised, network byte order byte stream.
Network stream deserialisation.
Definition at line 574 of file wb_filtered_vision_object.c.
References wb_filtered_vision_object::distance, wb_filtered_vision_object::frameCounter, wb_filtered_vision_object::isVisible, ntohl, ntohll, ntohs, wb_filtered_vision_object::pad1, wb_filtered_vision_object::ray_angle, wb_filtered_vision_object::visibilityHistory, wb_filtered_vision_object::x, wb_filtered_vision_object::y, and wb_filtered_vision_object::yaw.
wb_filtered_vision_object_from_string()
struct wb_filtered_vision_object * wb_filtered_vision_object_from_string (struct wb_filtered_vision_object * self, const char * str)
Convert from a string.
Definition at line 293 of file wb_filtered_vision_object.c.
References FILTERED_VISION_OBJECT_DESC_BUFFER_SIZE.
Referenced by wb_filtered_arrayballsightings_from_string(), and wb_filtered_arrayonedimobjects_from_string().
wb_filtered_vision_object_to_network_serialised()
size_t wb_filtered_vision_object_to_network_serialised (const struct wb_filtered_vision_object * self, char * dst)
Convert to a compressed, serialised, network byte order byte stream.
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 449 of file wb_filtered_vision_object.c.
References htonl, htonll, and htons.
wb_filtered_vision_object_to_string()
const char * wb_filtered_vision_object_to_string (const struct wb_filtered_vision_object * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 209 of file wb_filtered_vision_object.c.
Referenced by guWhiteboard::FilteredVisionObject::to_string(), wb_filtered_arrayballsightings_to_string(), and wb_filtered_arrayonedimobjects_to_string().