gusimplewhiteboard: typeClassDefs/wb_pixel_coordinate_line.h File Reference
wb_pixel_coordinate_line.h File Reference
#include <gu_util.h>
#include <stdint.h>
#include "wb_pixel_coordinate.h"
#include <guunits/guunits.h>
#include <gucoordinates/gucoordinates.h>
Classes
struct wb_pixel_coordinate_line
WHITEBOARD_POSTER_STRING_CONVERSION.
Macros
#define _XOPEN_SOURCE 700
#define PIXEL_COORDINATE_LINE_GENERATED
#define PIXEL_COORDINATE_LINE_C_STRUCT wb_pixel_coordinate_line
#define PIXEL_COORDINATE_LINE_NUMBER_OF_VARIABLES 2
#define PIXEL_COORDINATE_LINE_DESC_BUFFER_SIZE 1037
#define PIXEL_COORDINATE_LINE_TO_STRING_BUFFER_SIZE 1027
Functions
const char * wb_pixel_coordinate_line_description (const struct wb_pixel_coordinate_line *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_pixel_coordinate_line_to_string (const struct wb_pixel_coordinate_line *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_pixel_coordinate_line * wb_pixel_coordinate_line_from_string (struct wb_pixel_coordinate_line *self, const char *str)
Convert from a string.
gu_pixel_coordinate wb_pixel_coordinate_line_start_px_coord (const struct wb_pixel_coordinate_line self, const uint16_t resWidth, const uint16_t resHeight)
WHITEBOARD_POSTER_STRING_CONVERSION.
gu_pixel_coordinate wb_pixel_coordinate_line_end_px_coord (const struct wb_pixel_coordinate_line self, const uint16_t resWidth, const uint16_t resHeight)
size_t wb_pixel_coordinate_line_to_network_serialised (const struct wb_pixel_coordinate_line *self, char *dst)
Network stream serialisation.
size_t wb_pixel_coordinate_line_from_network_serialised (const char *src, struct wb_pixel_coordinate_line *dst)
Network stream deserialisation.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 72 of file wb_pixel_coordinate_line.h.
PIXEL_COORDINATE_LINE_C_STRUCT
#define PIXEL_COORDINATE_LINE_C_STRUCT wb_pixel_coordinate_line
Definition at line 98 of file wb_pixel_coordinate_line.h.
PIXEL_COORDINATE_LINE_DESC_BUFFER_SIZE
#define PIXEL_COORDINATE_LINE_DESC_BUFFER_SIZE 1037
Definition at line 102 of file wb_pixel_coordinate_line.h.
PIXEL_COORDINATE_LINE_GENERATED
#define PIXEL_COORDINATE_LINE_GENERATED
Definition at line 97 of file wb_pixel_coordinate_line.h.
PIXEL_COORDINATE_LINE_NUMBER_OF_VARIABLES
#define PIXEL_COORDINATE_LINE_NUMBER_OF_VARIABLES 2
Definition at line 99 of file wb_pixel_coordinate_line.h.
PIXEL_COORDINATE_LINE_TO_STRING_BUFFER_SIZE
#define PIXEL_COORDINATE_LINE_TO_STRING_BUFFER_SIZE 1027
Definition at line 103 of file wb_pixel_coordinate_line.h.
Function Documentation
wb_pixel_coordinate_line_description()
const char * wb_pixel_coordinate_line_description (const struct wb_pixel_coordinate_line * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_pixel_coordinate_line.c.
References PIXEL_COORDINATE_DESC_BUFFER_SIZE, and wb_pixel_coordinate_description().
Referenced by guWhiteboard::PixelCoordinateLine::description(), wb_vision_detection_line_array_description(), and wb_vision_line_description().
wb_pixel_coordinate_line_end_px_coord()
gu_pixel_coordinate wb_pixel_coordinate_line_end_px_coord (const struct wb_pixel_coordinate_line self, const uint16_t resWidth, const uint16_t resHeight)
Definition at line 349 of file wb_pixel_coordinate_line.c.
References wb_pixel_coordinate_line::end, and wb_px_coord_to_px_coord().
wb_pixel_coordinate_line_from_network_serialised()
size_t wb_pixel_coordinate_line_from_network_serialised (const char * src, struct wb_pixel_coordinate_line * dst)
Network stream deserialisation.
Network stream deserialisation.
Definition at line 333 of file wb_pixel_coordinate_line.c.
wb_pixel_coordinate_line_from_string()
struct wb_pixel_coordinate_line * wb_pixel_coordinate_line_from_string (struct wb_pixel_coordinate_line * self, const char * str)
Convert from a string.
Definition at line 217 of file wb_pixel_coordinate_line.c.
References PIXEL_COORDINATE_LINE_DESC_BUFFER_SIZE, and wb_pixel_coordinate_from_string().
Referenced by wb_vision_detection_line_array_from_string(), and wb_vision_line_from_string().
wb_pixel_coordinate_line_start_px_coord()
gu_pixel_coordinate wb_pixel_coordinate_line_start_px_coord (const struct wb_pixel_coordinate_line self, const uint16_t resWidth, const uint16_t resHeight)
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 345 of file wb_pixel_coordinate_line.c.
References wb_pixel_coordinate_line::start, and wb_px_coord_to_px_coord().
wb_pixel_coordinate_line_to_network_serialised()
size_t wb_pixel_coordinate_line_to_network_serialised (const struct wb_pixel_coordinate_line * self, char * dst)
Network stream serialisation.
Network stream serialisation.
Definition at line 320 of file wb_pixel_coordinate_line.c.
wb_pixel_coordinate_line_to_string()
const char * wb_pixel_coordinate_line_to_string (const struct wb_pixel_coordinate_line * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 171 of file wb_pixel_coordinate_line.c.
References PIXEL_COORDINATE_TO_STRING_BUFFER_SIZE, and wb_pixel_coordinate_to_string().
Referenced by guWhiteboard::PixelCoordinateLine::to_string(), wb_vision_detection_line_array_to_string(), and wb_vision_line_to_string().