gusimplewhiteboard: typeClassDefs/wb_vision_detection_balls.h File Reference
wb_vision_detection_balls.h File Reference
#include <gu_util.h>
#include <stdint.h>
#include "wb_vision_detection_ball.h"
Classes
struct wb_vision_detection_balls
Array of fieldBalls, one instance reported by each camera.
Macros
#define _XOPEN_SOURCE 700
#define VISION_DETECTION_BALLS_GENERATED
#define VISION_DETECTION_BALLS_C_STRUCT wb_vision_detection_balls
#define VISION_DETECTION_BALLS_NUMBER_OF_VARIABLES 4
#define VISION_DETECTION_BALLS_DESC_BUFFER_SIZE 588
#define VISION_DETECTION_BALLS_TO_STRING_BUFFER_SIZE 549
#define VISION_DETECTION_BALLS_BALLS_ARRAY_SIZE 2
WHITEBOARD_POSTER_STRING_CONVERSION.
Functions
const char * wb_vision_detection_balls_description (const struct wb_vision_detection_balls *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_vision_detection_balls_to_string (const struct wb_vision_detection_balls *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_vision_detection_balls * wb_vision_detection_balls_from_string (struct wb_vision_detection_balls *self, const char *str)
Convert from a string.
size_t wb_vision_detection_balls_to_network_serialised (const struct wb_vision_detection_balls *self, char *dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
size_t wb_vision_detection_balls_from_network_serialised (const char *src, struct wb_vision_detection_balls *dst)
Network stream deserialisation.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 72 of file wb_vision_detection_balls.h.
VISION_DETECTION_BALLS_BALLS_ARRAY_SIZE
#define VISION_DETECTION_BALLS_BALLS_ARRAY_SIZE 2
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 100 of file wb_vision_detection_balls.h.
VISION_DETECTION_BALLS_C_STRUCT
#define VISION_DETECTION_BALLS_C_STRUCT wb_vision_detection_balls
Definition at line 92 of file wb_vision_detection_balls.h.
VISION_DETECTION_BALLS_DESC_BUFFER_SIZE
#define VISION_DETECTION_BALLS_DESC_BUFFER_SIZE 588
Definition at line 96 of file wb_vision_detection_balls.h.
VISION_DETECTION_BALLS_GENERATED
#define VISION_DETECTION_BALLS_GENERATED
Definition at line 91 of file wb_vision_detection_balls.h.
VISION_DETECTION_BALLS_NUMBER_OF_VARIABLES
#define VISION_DETECTION_BALLS_NUMBER_OF_VARIABLES 4
Definition at line 93 of file wb_vision_detection_balls.h.
VISION_DETECTION_BALLS_TO_STRING_BUFFER_SIZE
#define VISION_DETECTION_BALLS_TO_STRING_BUFFER_SIZE 549
Definition at line 97 of file wb_vision_detection_balls.h.
Function Documentation
wb_vision_detection_balls_description()
const char * wb_vision_detection_balls_description (const struct wb_vision_detection_balls * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_vision_detection_balls.c.
References VISION_DETECTION_BALL_DESC_BUFFER_SIZE, VISION_DETECTION_BALLS_BALLS_ARRAY_SIZE, and wb_vision_detection_ball_description().
Referenced by guWhiteboard::VisionDetectionBalls::description().
wb_vision_detection_balls_from_network_serialised()
size_t wb_vision_detection_balls_from_network_serialised (const char * src, struct wb_vision_detection_balls * dst)
Network stream deserialisation.
Network stream deserialisation.
Definition at line 517 of file wb_vision_detection_balls.c.
References wb_vision_detection_balls::balls, wb_vision_detection_balls::frameNumber, ntohll, ntohs, wb_vision_detection_balls::res_height, and wb_vision_detection_balls::res_width.
wb_vision_detection_balls_from_string()
struct wb_vision_detection_balls * wb_vision_detection_balls_from_string (struct wb_vision_detection_balls * self, const char * str)
Convert from a string.
Definition at line 261 of file wb_vision_detection_balls.c.
References VISION_DETECTION_BALLS_BALLS_ARRAY_SIZE, VISION_DETECTION_BALLS_DESC_BUFFER_SIZE, and wb_vision_detection_ball_from_string().
wb_vision_detection_balls_to_network_serialised()
size_t wb_vision_detection_balls_to_network_serialised (const struct wb_vision_detection_balls * self, char * dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
Network stream serialisation
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 443 of file wb_vision_detection_balls.c.
References htonll, and htons.
wb_vision_detection_balls_to_string()
const char * wb_vision_detection_balls_to_string (const struct wb_vision_detection_balls * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 193 of file wb_vision_detection_balls.c.
References VISION_DETECTION_BALL_TO_STRING_BUFFER_SIZE, VISION_DETECTION_BALLS_BALLS_ARRAY_SIZE, and wb_vision_detection_ball_to_string().
Referenced by guWhiteboard::VisionDetectionBalls::to_string().