gusimplewhiteboard: typeClassDefs/wb_microphone_frequencies.c File Reference
wb_microphone_frequencies.c File Reference
#include "wb_microphone_frequencies.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <limits.h>
Macros
#define htonll(x) bswap_64(x)
#define ntohll(x) bswap_64(x)
#define htonl(x) bswap_32(x)
#define ntohl(x) bswap_32(x)
#define htons(x) bswap_16(x)
#define ntohs(x) bswap_16(x)
Functions
const char * wb_microphone_frequencies_description (const struct wb_microphone_frequencies *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_microphone_frequencies_to_string (const struct wb_microphone_frequencies *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_microphone_frequencies * wb_microphone_frequencies_from_string (struct wb_microphone_frequencies *self, const char *str)
Convert from a string.
size_t wb_microphone_frequencies_to_network_serialised (const struct wb_microphone_frequencies *self, char *dst)
Convert to a compressed, serialised, network byte order byte stream.
size_t wb_microphone_frequencies_from_network_serialised (const char *src, struct wb_microphone_frequencies *dst)
Convert from a compressed, serialised, network byte order byte stream.
Macro Definition Documentation
htonl
#define htonl (x) bswap_32(x)
Definition at line 97 of file wb_microphone_frequencies.c.
htonll
#define htonll (x) bswap_64(x)
Definition at line 93 of file wb_microphone_frequencies.c.
htons
#define htons (x) bswap_16(x)
Definition at line 101 of file wb_microphone_frequencies.c.
ntohl
#define ntohl (x) bswap_32(x)
Definition at line 98 of file wb_microphone_frequencies.c.
ntohll
#define ntohll (x) bswap_64(x)
Definition at line 94 of file wb_microphone_frequencies.c.
ntohs
#define ntohs (x) bswap_16(x)
Definition at line 102 of file wb_microphone_frequencies.c.
Function Documentation
wb_microphone_frequencies_description()
const char * wb_microphone_frequencies_description (const struct wb_microphone_frequencies * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_microphone_frequencies.c.
Referenced by guWhiteboard::MicrophoneFrequencies::description(), and wb_dominant_frequencies_description().
wb_microphone_frequencies_from_network_serialised()
size_t wb_microphone_frequencies_from_network_serialised (const char * src, struct wb_microphone_frequencies * dst)
Convert from a compressed, serialised, network byte order byte stream.
Network stream deserialisation.
Definition at line 389 of file wb_microphone_frequencies.c.
References wb_microphone_frequencies::front_left, wb_microphone_frequencies::front_right, ntohs, wb_microphone_frequencies::rear_left, and wb_microphone_frequencies::rear_right.
wb_microphone_frequencies_from_string()
struct wb_microphone_frequencies * wb_microphone_frequencies_from_string (struct wb_microphone_frequencies * self, const char * str)
Convert from a string.
Definition at line 205 of file wb_microphone_frequencies.c.
References MICROPHONE_FREQUENCIES_DESC_BUFFER_SIZE.
Referenced by wb_dominant_frequencies_from_string().
wb_microphone_frequencies_to_network_serialised()
size_t wb_microphone_frequencies_to_network_serialised (const struct wb_microphone_frequencies * self, char * dst)
Convert to a compressed, serialised, network byte order byte stream.
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 322 of file wb_microphone_frequencies.c.
References htons.
wb_microphone_frequencies_to_string()
const char * wb_microphone_frequencies_to_string (const struct wb_microphone_frequencies * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 165 of file wb_microphone_frequencies.c.
Referenced by guWhiteboard::MicrophoneFrequencies::to_string(), and wb_dominant_frequencies_to_string().