gusimplewhiteboard: typeClassDefs/wb_pixel_coordinate.h File Reference
wb_pixel_coordinate.h File Reference
#include <gu_util.h>
#include <stdint.h>
#include <guunits/guunits.h>
#include <gucoordinates/gucoordinates.h>
Classes
struct wb_pixel_coordinate
WHITEBOARD_POSTER_STRING_CONVERSION.
Macros
#define _XOPEN_SOURCE 700
#define PIXEL_COORDINATE_GENERATED
#define PIXEL_COORDINATE_C_STRUCT wb_pixel_coordinate
#define PIXEL_COORDINATE_NUMBER_OF_VARIABLES 2
#define PIXEL_COORDINATE_DESC_BUFFER_SIZE 19
#define PIXEL_COORDINATE_TO_STRING_BUFFER_SIZE 15
Functions
const char * wb_pixel_coordinate_description (const struct wb_pixel_coordinate *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_pixel_coordinate_to_string (const struct wb_pixel_coordinate *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_pixel_coordinate * wb_pixel_coordinate_from_string (struct wb_pixel_coordinate *self, const char *str)
Convert from a string.
struct wb_pixel_coordinate px_coord_to_wb_px_coord (const gu_pixel_coordinate coord)
WHITEBOARD_POSTER_STRING_CONVERSION.
gu_pixel_coordinate wb_px_coord_to_px_coord (const struct wb_pixel_coordinate coord, const uint16_t resWidth, const uint16_t resHeight)
size_t wb_pixel_coordinate_to_network_serialised (const struct wb_pixel_coordinate *self, char *dst)
Network stream serialisation.
size_t wb_pixel_coordinate_from_network_serialised (const char *src, struct wb_pixel_coordinate *dst)
Network stream deserialisation.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 72 of file wb_pixel_coordinate.h.
PIXEL_COORDINATE_C_STRUCT
#define PIXEL_COORDINATE_C_STRUCT wb_pixel_coordinate
Definition at line 92 of file wb_pixel_coordinate.h.
PIXEL_COORDINATE_DESC_BUFFER_SIZE
#define PIXEL_COORDINATE_DESC_BUFFER_SIZE 19
Definition at line 96 of file wb_pixel_coordinate.h.
PIXEL_COORDINATE_GENERATED
#define PIXEL_COORDINATE_GENERATED
Definition at line 91 of file wb_pixel_coordinate.h.
PIXEL_COORDINATE_NUMBER_OF_VARIABLES
#define PIXEL_COORDINATE_NUMBER_OF_VARIABLES 2
Definition at line 93 of file wb_pixel_coordinate.h.
PIXEL_COORDINATE_TO_STRING_BUFFER_SIZE
#define PIXEL_COORDINATE_TO_STRING_BUFFER_SIZE 15
Definition at line 97 of file wb_pixel_coordinate.h.
Function Documentation
px_coord_to_wb_px_coord()
struct wb_pixel_coordinate px_coord_to_wb_px_coord (const gu_pixel_coordinate coord)
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 355 of file wb_pixel_coordinate.c.
wb_pixel_coordinate_description()
const char * wb_pixel_coordinate_description (const struct wb_pixel_coordinate * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_pixel_coordinate.c.
Referenced by guWhiteboard::PixelCoordinate::description(), wb_pixel_coordinate_line_description(), wb_vision_detection_ball_description(), wb_vision_detection_goal_post_description(), wb_vision_detection_horizon_description(), and wb_vision_field_feature_description().
wb_pixel_coordinate_from_network_serialised()
size_t wb_pixel_coordinate_from_network_serialised (const char * src, struct wb_pixel_coordinate * dst)
Network stream deserialisation.
Network stream deserialisation.
Definition at line 315 of file wb_pixel_coordinate.c.
References ntohs, wb_pixel_coordinate::x, and wb_pixel_coordinate::y.
wb_pixel_coordinate_from_string()
struct wb_pixel_coordinate * wb_pixel_coordinate_from_string (struct wb_pixel_coordinate * self, const char * str)
Convert from a string.
Definition at line 173 of file wb_pixel_coordinate.c.
References PIXEL_COORDINATE_DESC_BUFFER_SIZE.
Referenced by wb_pixel_coordinate_line_from_string(), wb_vision_detection_ball_from_string(), wb_vision_detection_goal_post_from_string(), wb_vision_detection_horizon_from_string(), and wb_vision_field_feature_from_string().
wb_pixel_coordinate_to_network_serialised()
size_t wb_pixel_coordinate_to_network_serialised (const struct wb_pixel_coordinate * self, char * dst)
Network stream serialisation.
Network stream serialisation.
Definition at line 276 of file wb_pixel_coordinate.c.
References htons.
wb_pixel_coordinate_to_string()
const char * wb_pixel_coordinate_to_string (const struct wb_pixel_coordinate * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 149 of file wb_pixel_coordinate.c.
Referenced by guWhiteboard::PixelCoordinate::to_string(), wb_pixel_coordinate_line_to_string(), wb_vision_detection_ball_to_string(), wb_vision_detection_goal_post_to_string(), wb_vision_detection_horizon_to_string(), and wb_vision_field_feature_to_string().
wb_px_coord_to_px_coord()
gu_pixel_coordinate wb_px_coord_to_px_coord (const struct wb_pixel_coordinate coord, const uint16_t resWidth, const uint16_t resHeight)
Definition at line 361 of file wb_pixel_coordinate.c.
References wb_pixel_coordinate::x, and wb_pixel_coordinate::y.
Referenced by guWhiteboard::PixelCoordinate::pixelCoordinate(), wb_pixel_coordinate_line_end_px_coord(), wb_pixel_coordinate_line_start_px_coord(), wb_vision_detection_ball_coordinate_px_coord(), wb_vision_detection_goal_post_bottomLeftCoordinate_px_coord(), wb_vision_detection_goal_post_bottomRightCoordinate_px_coord(), wb_vision_detection_goal_post_topLeftCoordinate_px_coord(), wb_vision_detection_goal_post_topRightCoordinate_px_coord(), wb_vision_detection_horizon_centerCoordinate_px_coord(), wb_vision_detection_horizon_leftCoordinate_px_coord(), wb_vision_detection_horizon_rightCoordinate_px_coord(), and wb_vision_field_feature_coordinate_px_coord().