gusimplewhiteboard: typeClassDefs/wb_polar_coordinate.c File Reference
wb_polar_coordinate.c File Reference
#include "wb_polar_coordinate.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <limits.h>
Macros
#define htonll(x) bswap_64(x)
#define ntohll(x) bswap_64(x)
#define htonl(x) bswap_32(x)
#define ntohl(x) bswap_32(x)
#define htons(x) bswap_16(x)
#define ntohs(x) bswap_16(x)
Functions
const char * wb_polar_coordinate_description (const struct wb_polar_coordinate *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_polar_coordinate_to_string (const struct wb_polar_coordinate *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_polar_coordinate * wb_polar_coordinate_from_string (struct wb_polar_coordinate *self, const char *str)
Convert from a string.
size_t wb_polar_coordinate_to_network_serialised (const struct wb_polar_coordinate *self, char *dst)
Convert to a compressed, serialised, network byte order byte stream.
size_t wb_polar_coordinate_from_network_serialised (const char *src, struct wb_polar_coordinate *dst)
Convert from a compressed, serialised, network byte order byte stream.
Macro Definition Documentation
htonl
#define htonl (x) bswap_32(x)
Definition at line 97 of file wb_polar_coordinate.c.
htonll
#define htonll (x) bswap_64(x)
Definition at line 93 of file wb_polar_coordinate.c.
htons
#define htons (x) bswap_16(x)
Definition at line 101 of file wb_polar_coordinate.c.
ntohl
#define ntohl (x) bswap_32(x)
Definition at line 98 of file wb_polar_coordinate.c.
ntohll
#define ntohll (x) bswap_64(x)
Definition at line 94 of file wb_polar_coordinate.c.
ntohs
#define ntohs (x) bswap_16(x)
Definition at line 102 of file wb_polar_coordinate.c.
Function Documentation
wb_polar_coordinate_description()
const char * wb_polar_coordinate_description (const struct wb_polar_coordinate * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_polar_coordinate.c.
Referenced by guWhiteboard::PolarCoordinate::description(), wb_line_sighting_description(), and wb_vision_detection_feature_description().
wb_polar_coordinate_from_network_serialised()
size_t wb_polar_coordinate_from_network_serialised (const char * src, struct wb_polar_coordinate * dst)
Convert from a compressed, serialised, network byte order byte stream.
Network stream deserialisation.
Definition at line 315 of file wb_polar_coordinate.c.
References wb_polar_coordinate::direction, wb_polar_coordinate::distance, and ntohs.
wb_polar_coordinate_from_string()
struct wb_polar_coordinate * wb_polar_coordinate_from_string (struct wb_polar_coordinate * self, const char * str)
Convert from a string.
Definition at line 173 of file wb_polar_coordinate.c.
References POLAR_COORDINATE_DESC_BUFFER_SIZE.
Referenced by wb_line_sighting_from_string(), and wb_vision_detection_feature_from_string().
wb_polar_coordinate_to_network_serialised()
size_t wb_polar_coordinate_to_network_serialised (const struct wb_polar_coordinate * self, char * dst)
Convert to a compressed, serialised, network byte order byte stream.
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 276 of file wb_polar_coordinate.c.
References htons.
wb_polar_coordinate_to_string()
const char * wb_polar_coordinate_to_string (const struct wb_polar_coordinate * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 149 of file wb_polar_coordinate.c.
Referenced by guWhiteboard::PolarCoordinate::to_string(), wb_line_sighting_to_string(), and wb_vision_detection_feature_to_string().