gusimplewhiteboard: typeClassDefs/wb_vision_lines.c File Reference
wb_vision_lines.c File Reference
#include "wb_vision_lines.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <limits.h>
Macros
#define htonll(x) bswap_64(x)
#define ntohll(x) bswap_64(x)
#define htonl(x) bswap_32(x)
#define ntohl(x) bswap_32(x)
#define htons(x) bswap_16(x)
#define ntohs(x) bswap_16(x)
Functions
const char * wb_vision_lines_description (const struct wb_vision_lines *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_vision_lines_to_string (const struct wb_vision_lines *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_vision_lines * wb_vision_lines_from_string (struct wb_vision_lines *self, const char *str)
Convert from a string.
size_t wb_vision_lines_to_network_serialised (const struct wb_vision_lines *self, char *dst)
Convert to a compressed, serialised, network byte order byte stream.
size_t wb_vision_lines_from_network_serialised (const char *src, struct wb_vision_lines *dst)
Convert from a compressed, serialised, network byte order byte stream.
Macro Definition Documentation
htonl
#define htonl (x) bswap_32(x)
Definition at line 97 of file wb_vision_lines.c.
htonll
#define htonll (x) bswap_64(x)
Definition at line 93 of file wb_vision_lines.c.
htons
#define htons (x) bswap_16(x)
Definition at line 101 of file wb_vision_lines.c.
ntohl
#define ntohl (x) bswap_32(x)
Definition at line 98 of file wb_vision_lines.c.
ntohll
#define ntohll (x) bswap_64(x)
Definition at line 94 of file wb_vision_lines.c.
ntohs
#define ntohs (x) bswap_16(x)
Definition at line 102 of file wb_vision_lines.c.
Function Documentation
wb_vision_lines_description()
const char * wb_vision_lines_description (const struct wb_vision_lines * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_vision_lines.c.
References VISION_LINE_DESC_BUFFER_SIZE, VISION_LINES_LINES_ARRAY_SIZE, and wb_vision_line_description().
Referenced by guWhiteboard::VisionLines::description().
wb_vision_lines_from_network_serialised()
size_t wb_vision_lines_from_network_serialised (const char * src, struct wb_vision_lines * dst)
Convert from a compressed, serialised, network byte order byte stream.
Network stream deserialisation.
Definition at line 554 of file wb_vision_lines.c.
References wb_vision_lines::frameNumber, wb_vision_lines::lines, ntohll, ntohs, wb_vision_lines::numLines, wb_vision_lines::res_height, and wb_vision_lines::res_width.
wb_vision_lines_from_string()
struct wb_vision_lines * wb_vision_lines_from_string (struct wb_vision_lines * self, const char * str)
Convert from a string.
Definition at line 277 of file wb_vision_lines.c.
References VISION_LINES_DESC_BUFFER_SIZE, VISION_LINES_LINES_ARRAY_SIZE, and wb_vision_line_from_string().
wb_vision_lines_to_network_serialised()
size_t wb_vision_lines_to_network_serialised (const struct wb_vision_lines * self, char * dst)
Convert to a compressed, serialised, network byte order byte stream.
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 466 of file wb_vision_lines.c.
References htonll, and htons.
wb_vision_lines_to_string()
const char * wb_vision_lines_to_string (const struct wb_vision_lines * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 201 of file wb_vision_lines.c.
References VISION_LINE_TO_STRING_BUFFER_SIZE, VISION_LINES_LINES_ARRAY_SIZE, and wb_vision_line_to_string().
Referenced by guWhiteboard::VisionLines::to_string().