gusimplewhiteboard: typeClassDefs/wb_vision_detection_goal_post.h File Reference
wb_vision_detection_goal_post.h File Reference
#include <gu_util.h>
#include <stdint.h>
#include "wb_pixel_coordinate.h"
#include <guunits/guunits.h>
#include <gucoordinates/gucoordinates.h>
Classes
struct wb_vision_detection_goal_post
WHITEBOARD_POSTER_STRING_CONVERSION.
Macros
#define _XOPEN_SOURCE 700
#define VISION_DETECTION_GOAL_POST_GENERATED
#define VISION_DETECTION_GOAL_POST_C_STRUCT wb_vision_detection_goal_post
#define VISION_DETECTION_GOAL_POST_NUMBER_OF_VARIABLES 6
#define VISION_DETECTION_GOAL_POST_DESC_BUFFER_SIZE 3188
#define VISION_DETECTION_GOAL_POST_TO_STRING_BUFFER_SIZE 3083
Enumerations
enum GoalPostOptions { NoPostDetected = 0 , PartialPostSeen , FullPostSeen }
enum GoalPostOrientation { GenericPost = 0 , LeftPost , RightPost }
Functions
const char * wb_vision_detection_goal_post_description (const struct wb_vision_detection_goal_post *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_vision_detection_goal_post_to_string (const struct wb_vision_detection_goal_post *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_vision_detection_goal_post * wb_vision_detection_goal_post_from_string (struct wb_vision_detection_goal_post *self, const char *str)
Convert from a string.
gu_pixel_coordinate wb_vision_detection_goal_post_topLeftCoordinate_px_coord (const struct wb_vision_detection_goal_post self, const uint16_t resWidth, const uint16_t resHeight)
WHITEBOARD_POSTER_STRING_CONVERSION.
gu_pixel_coordinate wb_vision_detection_goal_post_topRightCoordinate_px_coord (const struct wb_vision_detection_goal_post self, const uint16_t resWidth, const uint16_t resHeight)
gu_pixel_coordinate wb_vision_detection_goal_post_bottomLeftCoordinate_px_coord (const struct wb_vision_detection_goal_post self, const uint16_t resWidth, const uint16_t resHeight)
gu_pixel_coordinate wb_vision_detection_goal_post_bottomRightCoordinate_px_coord (const struct wb_vision_detection_goal_post self, const uint16_t resWidth, const uint16_t resHeight)
size_t wb_vision_detection_goal_post_to_network_serialised (const struct wb_vision_detection_goal_post *self, char *dst)
Network stream serialisation.
size_t wb_vision_detection_goal_post_from_network_serialised (const char *src, struct wb_vision_detection_goal_post *dst)
Network stream deserialisation.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 72 of file wb_vision_detection_goal_post.h.
VISION_DETECTION_GOAL_POST_C_STRUCT
#define VISION_DETECTION_GOAL_POST_C_STRUCT wb_vision_detection_goal_post
Definition at line 119 of file wb_vision_detection_goal_post.h.
VISION_DETECTION_GOAL_POST_DESC_BUFFER_SIZE
#define VISION_DETECTION_GOAL_POST_DESC_BUFFER_SIZE 3188
Definition at line 123 of file wb_vision_detection_goal_post.h.
VISION_DETECTION_GOAL_POST_GENERATED
#define VISION_DETECTION_GOAL_POST_GENERATED
Definition at line 118 of file wb_vision_detection_goal_post.h.
VISION_DETECTION_GOAL_POST_NUMBER_OF_VARIABLES
#define VISION_DETECTION_GOAL_POST_NUMBER_OF_VARIABLES 6
Definition at line 120 of file wb_vision_detection_goal_post.h.
VISION_DETECTION_GOAL_POST_TO_STRING_BUFFER_SIZE
#define VISION_DETECTION_GOAL_POST_TO_STRING_BUFFER_SIZE 3083
Definition at line 124 of file wb_vision_detection_goal_post.h.
Enumeration Type Documentation
GoalPostOptions
enum GoalPostOptions
Enumerator
NoPostDetected
Didn't see a post.
PartialPostSeen
Saw part of a post. Part in the image, part out.
FullPostSeen
Saw the entire post.
Definition at line 90 of file wb_vision_detection_goal_post.h.
GoalPostOrientation
enum GoalPostOrientation
Enumerator
GenericPost
Could not determine post orientation.
LeftPost
This is the left post of a goal.
RightPost
This is the right post of a goal.
Definition at line 96 of file wb_vision_detection_goal_post.h.
Function Documentation
wb_vision_detection_goal_post_bottomLeftCoordinate_px_coord()
gu_pixel_coordinate wb_vision_detection_goal_post_bottomLeftCoordinate_px_coord (const struct wb_vision_detection_goal_post self, const uint16_t resWidth, const uint16_t resHeight)
Definition at line 647 of file wb_vision_detection_goal_post.c.
References wb_vision_detection_goal_post::bottomLeftCoordinate, and wb_px_coord_to_px_coord().
wb_vision_detection_goal_post_bottomRightCoordinate_px_coord()
gu_pixel_coordinate wb_vision_detection_goal_post_bottomRightCoordinate_px_coord (const struct wb_vision_detection_goal_post self, const uint16_t resWidth, const uint16_t resHeight)
Definition at line 651 of file wb_vision_detection_goal_post.c.
References wb_vision_detection_goal_post::bottomRightCoordinate, and wb_px_coord_to_px_coord().
wb_vision_detection_goal_post_description()
const char * wb_vision_detection_goal_post_description (const struct wb_vision_detection_goal_post * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_vision_detection_goal_post.c.
References FullPostSeen, GenericPost, LeftPost, NoPostDetected, PartialPostSeen, PIXEL_COORDINATE_DESC_BUFFER_SIZE, RightPost, and wb_pixel_coordinate_description().
Referenced by guWhiteboard::VisionDetectionGoalPost::description(), and wb_vision_detection_goal_description().
wb_vision_detection_goal_post_from_network_serialised()
size_t wb_vision_detection_goal_post_from_network_serialised (const char * src, struct wb_vision_detection_goal_post * dst)
Network stream deserialisation.
Network stream deserialisation.
Definition at line 599 of file wb_vision_detection_goal_post.c.
References ntohl, wb_vision_detection_goal_post::orientation, and wb_vision_detection_goal_post::sightingType.
wb_vision_detection_goal_post_from_string()
struct wb_vision_detection_goal_post * wb_vision_detection_goal_post_from_string (struct wb_vision_detection_goal_post * self, const char * str)
Convert from a string.
Definition at line 389 of file wb_vision_detection_goal_post.c.
References FullPostSeen, GenericPost, LeftPost, NoPostDetected, PartialPostSeen, RightPost, VISION_DETECTION_GOAL_POST_DESC_BUFFER_SIZE, and wb_pixel_coordinate_from_string().
Referenced by wb_vision_detection_goal_from_string().
wb_vision_detection_goal_post_to_network_serialised()
size_t wb_vision_detection_goal_post_to_network_serialised (const struct wb_vision_detection_goal_post * self, char * dst)
Network stream serialisation.
Network stream serialisation.
Definition at line 560 of file wb_vision_detection_goal_post.c.
References htonl.
wb_vision_detection_goal_post_to_string()
const char * wb_vision_detection_goal_post_to_string (const struct wb_vision_detection_goal_post * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 257 of file wb_vision_detection_goal_post.c.
References FullPostSeen, GenericPost, LeftPost, NoPostDetected, PartialPostSeen, PIXEL_COORDINATE_TO_STRING_BUFFER_SIZE, RightPost, and wb_pixel_coordinate_to_string().
Referenced by guWhiteboard::VisionDetectionGoalPost::to_string(), and wb_vision_detection_goal_to_string().
wb_vision_detection_goal_post_topLeftCoordinate_px_coord()
gu_pixel_coordinate wb_vision_detection_goal_post_topLeftCoordinate_px_coord (const struct wb_vision_detection_goal_post self, const uint16_t resWidth, const uint16_t resHeight)
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 639 of file wb_vision_detection_goal_post.c.
References wb_vision_detection_goal_post::topLeftCoordinate, and wb_px_coord_to_px_coord().
wb_vision_detection_goal_post_topRightCoordinate_px_coord()
gu_pixel_coordinate wb_vision_detection_goal_post_topRightCoordinate_px_coord (const struct wb_vision_detection_goal_post self, const uint16_t resWidth, const uint16_t resHeight)
Definition at line 643 of file wb_vision_detection_goal_post.c.
References wb_vision_detection_goal_post::topRightCoordinate, and wb_px_coord_to_px_coord().