gusimplewhiteboard: typeClassDefs/wb_odometry.h File Reference
wb_odometry.h File Reference
#include <gu_util.h>
#include <stdint.h>
#include <float.h>
Classes
struct wb_odometry
WHITEBOARD_POSTER_STRING_CONVERSION.
Macros
#define _XOPEN_SOURCE 700
#define ODOMETRY_GENERATED
#define ODOMETRY_C_STRUCT wb_odometry
#define ODOMETRY_NUMBER_OF_VARIABLES 3
#define ODOMETRY_DESC_BUFFER_SIZE 215
#define ODOMETRY_TO_STRING_BUFFER_SIZE 197
Functions
const char * wb_odometry_description (const struct wb_odometry *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_odometry_to_string (const struct wb_odometry *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_odometry * wb_odometry_from_string (struct wb_odometry *self, const char *str)
Convert from a string.
size_t wb_odometry_to_network_serialised (const struct wb_odometry *self, char *dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
size_t wb_odometry_from_network_serialised (const char *src, struct wb_odometry *dst)
Network stream deserialisation.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 72 of file wb_odometry.h.
ODOMETRY_C_STRUCT
#define ODOMETRY_C_STRUCT wb_odometry
Definition at line 93 of file wb_odometry.h.
ODOMETRY_DESC_BUFFER_SIZE
#define ODOMETRY_DESC_BUFFER_SIZE 215
Definition at line 97 of file wb_odometry.h.
ODOMETRY_GENERATED
#define ODOMETRY_GENERATED
Definition at line 92 of file wb_odometry.h.
ODOMETRY_NUMBER_OF_VARIABLES
#define ODOMETRY_NUMBER_OF_VARIABLES 3
Definition at line 94 of file wb_odometry.h.
ODOMETRY_TO_STRING_BUFFER_SIZE
#define ODOMETRY_TO_STRING_BUFFER_SIZE 197
Definition at line 98 of file wb_odometry.h.
Function Documentation
wb_odometry_description()
const char * wb_odometry_description (const struct wb_odometry * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_odometry.c.
Referenced by guWhiteboard::Odometry::description(), and wb_nao_walk_status_description().
wb_odometry_from_network_serialised()
size_t wb_odometry_from_network_serialised (const char * src, struct wb_odometry * dst)
Network stream deserialisation.
Network stream deserialisation.
Definition at line 316 of file wb_odometry.c.
wb_odometry_from_string()
struct wb_odometry * wb_odometry_from_string (struct wb_odometry * self, const char * str)
Convert from a string.
Definition at line 189 of file wb_odometry.c.
References ODOMETRY_DESC_BUFFER_SIZE.
Referenced by wb_nao_walk_status_from_string().
wb_odometry_to_network_serialised()
size_t wb_odometry_to_network_serialised (const struct wb_odometry * self, char * dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
Network stream serialisation
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 299 of file wb_odometry.c.
wb_odometry_to_string()
const char * wb_odometry_to_string (const struct wb_odometry * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 157 of file wb_odometry.c.
Referenced by guWhiteboard::Odometry::to_string(), and wb_nao_walk_status_to_string().