gusimplewhiteboard: typeClassDefs/wb_vision_detection_horizons.h File Reference
wb_vision_detection_horizons.h File Reference
#include <gu_util.h>
#include <stdint.h>
#include "wb_vision_detection_horizon.h"
Classes
struct wb_vision_detection_horizons
Array of fieldHorizons, one instance reported by each camera.
Macros
#define _XOPEN_SOURCE 700
#define VISION_DETECTION_HORIZONS_GENERATED
#define VISION_DETECTION_HORIZONS_C_STRUCT wb_vision_detection_horizons
#define VISION_DETECTION_HORIZONS_NUMBER_OF_VARIABLES 4
#define VISION_DETECTION_HORIZONS_DESC_BUFFER_SIZE 591
#define VISION_DETECTION_HORIZONS_TO_STRING_BUFFER_SIZE 549
#define VISION_DETECTION_HORIZONS_HORIZONS_ARRAY_SIZE 2
WHITEBOARD_POSTER_STRING_CONVERSION.
Functions
const char * wb_vision_detection_horizons_description (const struct wb_vision_detection_horizons *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_vision_detection_horizons_to_string (const struct wb_vision_detection_horizons *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_vision_detection_horizons * wb_vision_detection_horizons_from_string (struct wb_vision_detection_horizons *self, const char *str)
Convert from a string.
size_t wb_vision_detection_horizons_to_network_serialised (const struct wb_vision_detection_horizons *self, char *dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
size_t wb_vision_detection_horizons_from_network_serialised (const char *src, struct wb_vision_detection_horizons *dst)
Network stream deserialisation.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 72 of file wb_vision_detection_horizons.h.
VISION_DETECTION_HORIZONS_C_STRUCT
#define VISION_DETECTION_HORIZONS_C_STRUCT wb_vision_detection_horizons
Definition at line 91 of file wb_vision_detection_horizons.h.
VISION_DETECTION_HORIZONS_DESC_BUFFER_SIZE
#define VISION_DETECTION_HORIZONS_DESC_BUFFER_SIZE 591
Definition at line 95 of file wb_vision_detection_horizons.h.
VISION_DETECTION_HORIZONS_GENERATED
#define VISION_DETECTION_HORIZONS_GENERATED
Definition at line 90 of file wb_vision_detection_horizons.h.
VISION_DETECTION_HORIZONS_HORIZONS_ARRAY_SIZE
#define VISION_DETECTION_HORIZONS_HORIZONS_ARRAY_SIZE 2
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 99 of file wb_vision_detection_horizons.h.
VISION_DETECTION_HORIZONS_NUMBER_OF_VARIABLES
#define VISION_DETECTION_HORIZONS_NUMBER_OF_VARIABLES 4
Definition at line 92 of file wb_vision_detection_horizons.h.
VISION_DETECTION_HORIZONS_TO_STRING_BUFFER_SIZE
#define VISION_DETECTION_HORIZONS_TO_STRING_BUFFER_SIZE 549
Definition at line 96 of file wb_vision_detection_horizons.h.
Function Documentation
wb_vision_detection_horizons_description()
const char * wb_vision_detection_horizons_description (const struct wb_vision_detection_horizons * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_vision_detection_horizons.c.
References VISION_DETECTION_HORIZON_DESC_BUFFER_SIZE, VISION_DETECTION_HORIZONS_HORIZONS_ARRAY_SIZE, and wb_vision_detection_horizon_description().
Referenced by guWhiteboard::VisionDetectionHorizons::description().
wb_vision_detection_horizons_from_network_serialised()
size_t wb_vision_detection_horizons_from_network_serialised (const char * src, struct wb_vision_detection_horizons * dst)
Network stream deserialisation.
Network stream deserialisation.
Definition at line 517 of file wb_vision_detection_horizons.c.
References wb_vision_detection_horizons::frameNumber, wb_vision_detection_horizons::horizons, ntohll, ntohs, wb_vision_detection_horizons::res_height, and wb_vision_detection_horizons::res_width.
wb_vision_detection_horizons_from_string()
struct wb_vision_detection_horizons * wb_vision_detection_horizons_from_string (struct wb_vision_detection_horizons * self, const char * str)
Convert from a string.
Definition at line 261 of file wb_vision_detection_horizons.c.
References VISION_DETECTION_HORIZONS_DESC_BUFFER_SIZE, VISION_DETECTION_HORIZONS_HORIZONS_ARRAY_SIZE, and wb_vision_detection_horizon_from_string().
wb_vision_detection_horizons_to_network_serialised()
size_t wb_vision_detection_horizons_to_network_serialised (const struct wb_vision_detection_horizons * self, char * dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
Network stream serialisation
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 443 of file wb_vision_detection_horizons.c.
References htonll, and htons.
wb_vision_detection_horizons_to_string()
const char * wb_vision_detection_horizons_to_string (const struct wb_vision_detection_horizons * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 193 of file wb_vision_detection_horizons.c.
References VISION_DETECTION_HORIZON_TO_STRING_BUFFER_SIZE, VISION_DETECTION_HORIZONS_HORIZONS_ARRAY_SIZE, and wb_vision_detection_horizon_to_string().
Referenced by guWhiteboard::VisionDetectionHorizons::to_string().