gusimplewhiteboard: typeClassDefs/wb_hal_arm_target.c File Reference
wb_hal_arm_target.c File Reference
#include "wb_hal_arm_target.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <limits.h>
Macros
#define htonll(x) bswap_64(x)
#define ntohll(x) bswap_64(x)
#define htonl(x) bswap_32(x)
#define ntohl(x) bswap_32(x)
#define htons(x) bswap_16(x)
#define ntohs(x) bswap_16(x)
Functions
const char * wb_hal_arm_target_value_description (const struct wb_hal_arm_target *self, char *toString, size_t bufferSize)
Convert to a string.
const char * wb_hal_arm_target_description (const struct wb_hal_arm_target *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_hal_arm_target_to_string (const struct wb_hal_arm_target *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_hal_arm_target * wb_hal_arm_target_from_string (struct wb_hal_arm_target *self, const char *str)
Convert from a string.
size_t wb_hal_arm_target_to_network_serialised (const struct wb_hal_arm_target *self, char *dst)
Convert to a compressed, serialised, network byte order byte stream.
size_t wb_hal_arm_target_from_network_serialised (const char *src, struct wb_hal_arm_target *dst)
Convert from a compressed, serialised, network byte order byte stream.
Macro Definition Documentation
htonl
#define htonl (x) bswap_32(x)
Definition at line 97 of file wb_hal_arm_target.c.
htonll
#define htonll (x) bswap_64(x)
Definition at line 93 of file wb_hal_arm_target.c.
htons
#define htons (x) bswap_16(x)
Definition at line 101 of file wb_hal_arm_target.c.
ntohl
#define ntohl (x) bswap_32(x)
Definition at line 98 of file wb_hal_arm_target.c.
ntohll
#define ntohll (x) bswap_64(x)
Definition at line 94 of file wb_hal_arm_target.c.
ntohs
#define ntohs (x) bswap_16(x)
Definition at line 102 of file wb_hal_arm_target.c.
Function Documentation
wb_hal_arm_target_description()
const char * wb_hal_arm_target_description (const struct wb_hal_arm_target * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 310 of file wb_hal_arm_target.c.
Referenced by guWhiteboard::HalArmTarget::description().
wb_hal_arm_target_from_network_serialised()
size_t wb_hal_arm_target_from_network_serialised (const char * src, struct wb_hal_arm_target * dst)
Convert from a compressed, serialised, network byte order byte stream.
Network stream deserialisation.
Definition at line 1229 of file wb_hal_arm_target.c.
References ntohl, ntohs, wb_hal_arm_target::target_arm, wb_hal_arm_target::target_arm_at_goal, wb_hal_arm_target::target_arm_stop, wb_hal_arm_target::target_elbowroll, wb_hal_arm_target::target_elbowroll_active, wb_hal_arm_target::target_elbowrollstiffness, wb_hal_arm_target::target_elbowyaw, wb_hal_arm_target::target_elbowyaw_active, wb_hal_arm_target::target_elbowyawstiffness, wb_hal_arm_target::target_hand, wb_hal_arm_target::target_hand_active, wb_hal_arm_target::target_handstiffness, wb_hal_arm_target::target_movement_time, wb_hal_arm_target::target_pliability, wb_hal_arm_target::target_shoulderpitch, wb_hal_arm_target::target_shoulderpitch_active, wb_hal_arm_target::target_shoulderpitchstiffness, wb_hal_arm_target::target_shoulderroll, wb_hal_arm_target::target_shoulderroll_active, wb_hal_arm_target::target_shoulderrollstiffness, wb_hal_arm_target::target_wrist_active, wb_hal_arm_target::target_wristyaw, and wb_hal_arm_target::target_wristyawstiffness.
wb_hal_arm_target_from_string()
struct wb_hal_arm_target * wb_hal_arm_target_from_string (struct wb_hal_arm_target * self, const char * str)
Convert from a string.
Definition at line 694 of file wb_hal_arm_target.c.
References HAL_ARM_TARGET_DESC_BUFFER_SIZE.
wb_hal_arm_target_to_network_serialised()
size_t wb_hal_arm_target_to_network_serialised (const struct wb_hal_arm_target * self, char * dst)
Convert to a compressed, serialised, network byte order byte stream.
Network stream serialisation.
Definition at line 944 of file wb_hal_arm_target.c.
References htonl, and htons.
wb_hal_arm_target_to_string()
const char * wb_hal_arm_target_to_string (const struct wb_hal_arm_target * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 502 of file wb_hal_arm_target.c.
Referenced by guWhiteboard::HalArmTarget::to_string().
wb_hal_arm_target_value_description()
const char * wb_hal_arm_target_value_description (const struct wb_hal_arm_target * self, char * toString, size_t bufferSize)
Convert to a string.
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 124 of file wb_hal_arm_target.c.
Referenced by guWhiteboard::HalArmTarget::valueDescription().