gusimplewhiteboard: typeClassDefs/wb_dominant_frequencies.h File Reference
wb_dominant_frequencies.h File Reference
#include <gu_util.h>
#include <stdint.h>
#include "wb_microphone_frequencies.h"
#include "wb_r_m_s_levels.h"
Classes
struct wb_dominant_frequencies
Frequency quadruple for rear and front stereo channels.
Macros
#define _XOPEN_SOURCE 700
#define DOMINANT_NUMFREQ ((GU_SIMPLE_WHITEBOARD_BUFSIZE - sizeof(struct wb_r_m_s_levels)) / sizeof(struct wb_microphone_frequencies))
#define DOMINANT_NUMFREQi static_cast<int>(DOMINANT_NUMFREQ)
#define DOMINANT_FREQUENCIES_GENERATED
#define DOMINANT_FREQUENCIES_C_STRUCT wb_dominant_frequencies
#define DOMINANT_FREQUENCIES_NUMBER_OF_VARIABLES 2
#define DOMINANT_FREQUENCIES_DESC_BUFFER_SIZE 1043
#define DOMINANT_FREQUENCIES_TO_STRING_BUFFER_SIZE 1027
#define DOMINANT_FREQUENCIES_FREQUENCIES_ARRAY_SIZE DOMINANT_NUMFREQi
WHITEBOARD_POSTER_STRING_CONVERSION.
Functions
const char * wb_dominant_frequencies_description (const struct wb_dominant_frequencies *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_dominant_frequencies_to_string (const struct wb_dominant_frequencies *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_dominant_frequencies * wb_dominant_frequencies_from_string (struct wb_dominant_frequencies *self, const char *str)
Convert from a string.
size_t wb_dominant_frequencies_to_network_serialised (const struct wb_dominant_frequencies *self, char *dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
size_t wb_dominant_frequencies_from_network_serialised (const char *src, struct wb_dominant_frequencies *dst)
Network stream deserialisation.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 72 of file wb_dominant_frequencies.h.
DOMINANT_FREQUENCIES_C_STRUCT
#define DOMINANT_FREQUENCIES_C_STRUCT wb_dominant_frequencies
Definition at line 101 of file wb_dominant_frequencies.h.
DOMINANT_FREQUENCIES_DESC_BUFFER_SIZE
#define DOMINANT_FREQUENCIES_DESC_BUFFER_SIZE 1043
Definition at line 105 of file wb_dominant_frequencies.h.
DOMINANT_FREQUENCIES_FREQUENCIES_ARRAY_SIZE
#define DOMINANT_FREQUENCIES_FREQUENCIES_ARRAY_SIZE DOMINANT_NUMFREQi
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 109 of file wb_dominant_frequencies.h.
DOMINANT_FREQUENCIES_GENERATED
#define DOMINANT_FREQUENCIES_GENERATED
Definition at line 100 of file wb_dominant_frequencies.h.
DOMINANT_FREQUENCIES_NUMBER_OF_VARIABLES
#define DOMINANT_FREQUENCIES_NUMBER_OF_VARIABLES 2
Definition at line 102 of file wb_dominant_frequencies.h.
DOMINANT_FREQUENCIES_TO_STRING_BUFFER_SIZE
#define DOMINANT_FREQUENCIES_TO_STRING_BUFFER_SIZE 1027
Definition at line 106 of file wb_dominant_frequencies.h.
DOMINANT_NUMFREQ
#define DOMINANT_NUMFREQ ((GU_SIMPLE_WHITEBOARD_BUFSIZE - sizeof(struct wb_r_m_s_levels)) / sizeof(struct wb_microphone_frequencies))
Definition at line 92 of file wb_dominant_frequencies.h.
DOMINANT_NUMFREQi
#define DOMINANT_NUMFREQi static_cast<int>(DOMINANT_NUMFREQ)
Definition at line 94 of file wb_dominant_frequencies.h.
Function Documentation
wb_dominant_frequencies_description()
const char * wb_dominant_frequencies_description (const struct wb_dominant_frequencies * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 126 of file wb_dominant_frequencies.c.
References DOMINANT_FREQUENCIES_FREQUENCIES_ARRAY_SIZE, MICROPHONE_FREQUENCIES_DESC_BUFFER_SIZE, RMS_LEVELS_DESC_BUFFER_SIZE, wb_microphone_frequencies_description(), and wb_r_m_s_levels_description().
Referenced by guWhiteboard::DominantFrequencies::description().
wb_dominant_frequencies_from_network_serialised()
size_t wb_dominant_frequencies_from_network_serialised (const char * src, struct wb_dominant_frequencies * dst)
Network stream deserialisation.
Network stream deserialisation.
Definition at line 440 of file wb_dominant_frequencies.c.
References DOMINANT_NUMFREQi, and wb_dominant_frequencies::frequencies.
wb_dominant_frequencies_from_string()
struct wb_dominant_frequencies * wb_dominant_frequencies_from_string (struct wb_dominant_frequencies * self, const char * str)
Convert from a string.
Definition at line 244 of file wb_dominant_frequencies.c.
References DOMINANT_FREQUENCIES_DESC_BUFFER_SIZE, DOMINANT_FREQUENCIES_FREQUENCIES_ARRAY_SIZE, wb_microphone_frequencies_from_string(), and wb_r_m_s_levels_from_string().
wb_dominant_frequencies_to_network_serialised()
size_t wb_dominant_frequencies_to_network_serialised (const struct wb_dominant_frequencies * self, char * dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
Network stream serialisation
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 408 of file wb_dominant_frequencies.c.
References DOMINANT_NUMFREQi.
wb_dominant_frequencies_to_string()
const char * wb_dominant_frequencies_to_string (const struct wb_dominant_frequencies * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 185 of file wb_dominant_frequencies.c.
References DOMINANT_FREQUENCIES_FREQUENCIES_ARRAY_SIZE, MICROPHONE_FREQUENCIES_TO_STRING_BUFFER_SIZE, RMS_LEVELS_TO_STRING_BUFFER_SIZE, wb_microphone_frequencies_to_string(), and wb_r_m_s_levels_to_string().
Referenced by guWhiteboard::DominantFrequencies::to_string().