gusimplewhiteboard: typeClassDefs/wb_vision_detection_feature_array.h File Reference
wb_vision_detection_feature_array.h File Reference
#include <gu_util.h>
#include <stdint.h>
#include "wb_vision_detection_feature.h"
Classes
struct wb_vision_detection_feature_array
Results for the Feature Detector (guvision).
Macros
#define _XOPEN_SOURCE 700
#define VISION_DETECTION_FEATURE_ARRAY_GENERATED
#define VISION_DETECTION_FEATURE_ARRAY_C_STRUCT wb_vision_detection_feature_array
#define VISION_DETECTION_FEATURE_ARRAY_NUMBER_OF_VARIABLES 2
#define VISION_DETECTION_FEATURE_ARRAY_DESC_BUFFER_SIZE 539
#define VISION_DETECTION_FEATURE_ARRAY_TO_STRING_BUFFER_SIZE 518
#define VISION_DETECTION_FEATURE_ARRAY_FEATURES_ARRAY_SIZE 7
WHITEBOARD_POSTER_STRING_CONVERSION.
Functions
const char * wb_vision_detection_feature_array_description (const struct wb_vision_detection_feature_array *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_vision_detection_feature_array_to_string (const struct wb_vision_detection_feature_array *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_vision_detection_feature_array * wb_vision_detection_feature_array_from_string (struct wb_vision_detection_feature_array *self, const char *str)
Convert from a string.
size_t wb_vision_detection_feature_array_to_network_serialised (const struct wb_vision_detection_feature_array *self, char *dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
size_t wb_vision_detection_feature_array_from_network_serialised (const char *src, struct wb_vision_detection_feature_array *dst)
Network stream deserialisation.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 72 of file wb_vision_detection_feature_array.h.
VISION_DETECTION_FEATURE_ARRAY_C_STRUCT
#define VISION_DETECTION_FEATURE_ARRAY_C_STRUCT wb_vision_detection_feature_array
Definition at line 91 of file wb_vision_detection_feature_array.h.
VISION_DETECTION_FEATURE_ARRAY_DESC_BUFFER_SIZE
#define VISION_DETECTION_FEATURE_ARRAY_DESC_BUFFER_SIZE 539
Definition at line 95 of file wb_vision_detection_feature_array.h.
VISION_DETECTION_FEATURE_ARRAY_FEATURES_ARRAY_SIZE
#define VISION_DETECTION_FEATURE_ARRAY_FEATURES_ARRAY_SIZE 7
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 99 of file wb_vision_detection_feature_array.h.
VISION_DETECTION_FEATURE_ARRAY_GENERATED
#define VISION_DETECTION_FEATURE_ARRAY_GENERATED
Definition at line 90 of file wb_vision_detection_feature_array.h.
VISION_DETECTION_FEATURE_ARRAY_NUMBER_OF_VARIABLES
#define VISION_DETECTION_FEATURE_ARRAY_NUMBER_OF_VARIABLES 2
Definition at line 92 of file wb_vision_detection_feature_array.h.
VISION_DETECTION_FEATURE_ARRAY_TO_STRING_BUFFER_SIZE
#define VISION_DETECTION_FEATURE_ARRAY_TO_STRING_BUFFER_SIZE 518
Definition at line 96 of file wb_vision_detection_feature_array.h.
Function Documentation
wb_vision_detection_feature_array_description()
const char * wb_vision_detection_feature_array_description (const struct wb_vision_detection_feature_array * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_vision_detection_feature_array.c.
References VISION_DETECTION_FEATURE_ARRAY_FEATURES_ARRAY_SIZE, VISION_DETECTION_FEATURE_DESC_BUFFER_SIZE, and wb_vision_detection_feature_description().
Referenced by guWhiteboard::VisionDetectionFeatureArray::description(), and wb_vision_detection_features_description().
wb_vision_detection_feature_array_from_network_serialised()
size_t wb_vision_detection_feature_array_from_network_serialised (const char * src, struct wb_vision_detection_feature_array * dst)
Network stream deserialisation.
Network stream deserialisation.
Definition at line 431 of file wb_vision_detection_feature_array.c.
References wb_vision_detection_feature_array::features, and wb_vision_detection_feature_array::numFeatures.
wb_vision_detection_feature_array_from_string()
struct wb_vision_detection_feature_array * wb_vision_detection_feature_array_from_string (struct wb_vision_detection_feature_array * self, const char * str)
Convert from a string.
Definition at line 221 of file wb_vision_detection_feature_array.c.
References VISION_DETECTION_FEATURE_ARRAY_DESC_BUFFER_SIZE, VISION_DETECTION_FEATURE_ARRAY_FEATURES_ARRAY_SIZE, and wb_vision_detection_feature_from_string().
Referenced by wb_vision_detection_features_from_string().
wb_vision_detection_feature_array_to_network_serialised()
size_t wb_vision_detection_feature_array_to_network_serialised (const struct wb_vision_detection_feature_array * self, char * dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
Network stream serialisation
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 385 of file wb_vision_detection_feature_array.c.
wb_vision_detection_feature_array_to_string()
const char * wb_vision_detection_feature_array_to_string (const struct wb_vision_detection_feature_array * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 173 of file wb_vision_detection_feature_array.c.
References VISION_DETECTION_FEATURE_ARRAY_FEATURES_ARRAY_SIZE, VISION_DETECTION_FEATURE_TO_STRING_BUFFER_SIZE, and wb_vision_detection_feature_to_string().
Referenced by guWhiteboard::VisionDetectionFeatureArray::to_string(), and wb_vision_detection_features_to_string().