gusimplewhiteboard: typeClassDefs/wb_vision_detection_lines.h File Reference
wb_vision_detection_lines.h File Reference
#include <gu_util.h>
#include <stdint.h>
#include "wb_vision_detection_line_array.h"
Classes
struct wb_vision_detection_lines
Results for the Line Ray Tracer (guvision).
Macros
#define _XOPEN_SOURCE 700
#define VISION_DETECTION_LINES_GENERATED
#define VISION_DETECTION_LINES_C_STRUCT wb_vision_detection_lines
#define VISION_DETECTION_LINES_NUMBER_OF_VARIABLES 4
#define VISION_DETECTION_LINES_DESC_BUFFER_SIZE 588
#define VISION_DETECTION_LINES_TO_STRING_BUFFER_SIZE 549
#define VISION_DETECTION_LINES_LINES_ARRAY_SIZE 2
WHITEBOARD_POSTER_STRING_CONVERSION.
Functions
const char * wb_vision_detection_lines_description (const struct wb_vision_detection_lines *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_vision_detection_lines_to_string (const struct wb_vision_detection_lines *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_vision_detection_lines * wb_vision_detection_lines_from_string (struct wb_vision_detection_lines *self, const char *str)
Convert from a string.
size_t wb_vision_detection_lines_to_network_serialised (const struct wb_vision_detection_lines *self, char *dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
size_t wb_vision_detection_lines_from_network_serialised (const char *src, struct wb_vision_detection_lines *dst)
Network stream deserialisation.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 72 of file wb_vision_detection_lines.h.
VISION_DETECTION_LINES_C_STRUCT
#define VISION_DETECTION_LINES_C_STRUCT wb_vision_detection_lines
Definition at line 91 of file wb_vision_detection_lines.h.
VISION_DETECTION_LINES_DESC_BUFFER_SIZE
#define VISION_DETECTION_LINES_DESC_BUFFER_SIZE 588
Definition at line 95 of file wb_vision_detection_lines.h.
VISION_DETECTION_LINES_GENERATED
#define VISION_DETECTION_LINES_GENERATED
Definition at line 90 of file wb_vision_detection_lines.h.
VISION_DETECTION_LINES_LINES_ARRAY_SIZE
#define VISION_DETECTION_LINES_LINES_ARRAY_SIZE 2
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 99 of file wb_vision_detection_lines.h.
VISION_DETECTION_LINES_NUMBER_OF_VARIABLES
#define VISION_DETECTION_LINES_NUMBER_OF_VARIABLES 4
Definition at line 92 of file wb_vision_detection_lines.h.
VISION_DETECTION_LINES_TO_STRING_BUFFER_SIZE
#define VISION_DETECTION_LINES_TO_STRING_BUFFER_SIZE 549
Definition at line 96 of file wb_vision_detection_lines.h.
Function Documentation
wb_vision_detection_lines_description()
const char * wb_vision_detection_lines_description (const struct wb_vision_detection_lines * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_vision_detection_lines.c.
References VISION_DETECTION_LINE_ARRAY_DESC_BUFFER_SIZE, VISION_DETECTION_LINES_LINES_ARRAY_SIZE, and wb_vision_detection_line_array_description().
Referenced by guWhiteboard::VisionDetectionLines::description().
wb_vision_detection_lines_from_network_serialised()
size_t wb_vision_detection_lines_from_network_serialised (const char * src, struct wb_vision_detection_lines * dst)
Network stream deserialisation.
Network stream deserialisation.
Definition at line 517 of file wb_vision_detection_lines.c.
References wb_vision_detection_lines::frameNumber, wb_vision_detection_lines::lines, ntohll, ntohs, wb_vision_detection_lines::res_height, and wb_vision_detection_lines::res_width.
wb_vision_detection_lines_from_string()
struct wb_vision_detection_lines * wb_vision_detection_lines_from_string (struct wb_vision_detection_lines * self, const char * str)
Convert from a string.
Definition at line 261 of file wb_vision_detection_lines.c.
References VISION_DETECTION_LINES_DESC_BUFFER_SIZE, VISION_DETECTION_LINES_LINES_ARRAY_SIZE, and wb_vision_detection_line_array_from_string().
wb_vision_detection_lines_to_network_serialised()
size_t wb_vision_detection_lines_to_network_serialised (const struct wb_vision_detection_lines * self, char * dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
Network stream serialisation
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 443 of file wb_vision_detection_lines.c.
References htonll, and htons.
wb_vision_detection_lines_to_string()
const char * wb_vision_detection_lines_to_string (const struct wb_vision_detection_lines * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 193 of file wb_vision_detection_lines.c.
References VISION_DETECTION_LINE_ARRAY_TO_STRING_BUFFER_SIZE, VISION_DETECTION_LINES_LINES_ARRAY_SIZE, and wb_vision_detection_line_array_to_string().
Referenced by guWhiteboard::VisionDetectionLines::to_string().