gusimplewhiteboard: typeClassDefs/wb_particle_position.c File Reference
wb_particle_position.c File Reference
#include "wb_particle_position.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <limits.h>
Macros
#define htonll(x) bswap_64(x)
#define ntohll(x) bswap_64(x)
#define htonl(x) bswap_32(x)
#define ntohl(x) bswap_32(x)
#define htons(x) bswap_16(x)
#define ntohs(x) bswap_16(x)
Functions
const char * wb_particle_position_description (const struct wb_particle_position *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_particle_position_to_string (const struct wb_particle_position *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_particle_position * wb_particle_position_from_string (struct wb_particle_position *self, const char *str)
Convert from a string.
size_t wb_particle_position_to_network_serialised (const struct wb_particle_position *self, char *dst)
Convert to a compressed, serialised, network byte order byte stream.
size_t wb_particle_position_from_network_serialised (const char *src, struct wb_particle_position *dst)
Convert from a compressed, serialised, network byte order byte stream.
Macro Definition Documentation
htonl
#define htonl (x) bswap_32(x)
Definition at line 97 of file wb_particle_position.c.
htonll
#define htonll (x) bswap_64(x)
Definition at line 93 of file wb_particle_position.c.
htons
#define htons (x) bswap_16(x)
Definition at line 101 of file wb_particle_position.c.
ntohl
#define ntohl (x) bswap_32(x)
Definition at line 98 of file wb_particle_position.c.
ntohll
#define ntohll (x) bswap_64(x)
Definition at line 94 of file wb_particle_position.c.
ntohs
#define ntohs (x) bswap_16(x)
Definition at line 102 of file wb_particle_position.c.
Function Documentation
wb_particle_position_description()
const char * wb_particle_position_description (const struct wb_particle_position * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_particle_position.c.
References POINT2D_DESC_BUFFER_SIZE, and wb_point2d_description().
Referenced by guWhiteboard::ParticlePosition::description(), and wb_top_particles_description().
wb_particle_position_from_network_serialised()
size_t wb_particle_position_from_network_serialised (const char * src, struct wb_particle_position * dst)
Convert from a compressed, serialised, network byte order byte stream.
Network stream deserialisation.
Definition at line 348 of file wb_particle_position.c.
References wb_particle_position::headingInDegrees, and ntohs.
wb_particle_position_from_string()
struct wb_particle_position * wb_particle_position_from_string (struct wb_particle_position * self, const char * str)
Convert from a string.
Definition at line 211 of file wb_particle_position.c.
References PARTICLE_POSITION_DESC_BUFFER_SIZE, and wb_point2d_from_string().
Referenced by wb_top_particles_from_string().
wb_particle_position_to_network_serialised()
size_t wb_particle_position_to_network_serialised (const struct wb_particle_position * self, char * dst)
Convert to a compressed, serialised, network byte order byte stream.
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 321 of file wb_particle_position.c.
References htons.
wb_particle_position_to_string()
const char * wb_particle_position_to_string (const struct wb_particle_position * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 168 of file wb_particle_position.c.
References POINT2D_TO_STRING_BUFFER_SIZE, and wb_point2d_to_string().
Referenced by guWhiteboard::ParticlePosition::to_string(), and wb_top_particles_to_string().