gusimplewhiteboard: typeClassDefs/wb_vision_detection_ball.h File Reference
wb_vision_detection_ball.h File Reference
#include <gu_util.h>
#include <stdint.h>
#include "wb_pixel_coordinate.h"
#include <guunits/guunits.h>
#include <gucoordinates/gucoordinates.h>
Classes
struct wb_vision_detection_ball
WHITEBOARD_POSTER_STRING_CONVERSION.
Macros
#define _XOPEN_SOURCE 700
#define BALL_OPTIONS_ENUM
#define VISION_DETECTION_BALL_GENERATED
#define VISION_DETECTION_BALL_C_STRUCT wb_vision_detection_ball
#define VISION_DETECTION_BALL_NUMBER_OF_VARIABLES 4
#define VISION_DETECTION_BALL_DESC_BUFFER_SIZE 1097
#define VISION_DETECTION_BALL_TO_STRING_BUFFER_SIZE 1041
Enumerations
enum BallOptions { NoBallDetected = 0 , BallDetected }
Functions
const char * wb_vision_detection_ball_description (const struct wb_vision_detection_ball *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_vision_detection_ball_to_string (const struct wb_vision_detection_ball *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_vision_detection_ball * wb_vision_detection_ball_from_string (struct wb_vision_detection_ball *self, const char *str)
Convert from a string.
gu_pixel_coordinate wb_vision_detection_ball_coordinate_px_coord (const struct wb_vision_detection_ball self, const uint16_t resWidth, const uint16_t resHeight)
WHITEBOARD_POSTER_STRING_CONVERSION.
size_t wb_vision_detection_ball_to_network_serialised (const struct wb_vision_detection_ball *self, char *dst)
Network stream serialisation.
size_t wb_vision_detection_ball_from_network_serialised (const char *src, struct wb_vision_detection_ball *dst)
Network stream deserialisation.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 72 of file wb_vision_detection_ball.h.
BALL_OPTIONS_ENUM
#define BALL_OPTIONS_ENUM
Definition at line 90 of file wb_vision_detection_ball.h.
VISION_DETECTION_BALL_C_STRUCT
#define VISION_DETECTION_BALL_C_STRUCT wb_vision_detection_ball
Definition at line 102 of file wb_vision_detection_ball.h.
VISION_DETECTION_BALL_DESC_BUFFER_SIZE
#define VISION_DETECTION_BALL_DESC_BUFFER_SIZE 1097
Definition at line 106 of file wb_vision_detection_ball.h.
VISION_DETECTION_BALL_GENERATED
#define VISION_DETECTION_BALL_GENERATED
Definition at line 101 of file wb_vision_detection_ball.h.
VISION_DETECTION_BALL_NUMBER_OF_VARIABLES
#define VISION_DETECTION_BALL_NUMBER_OF_VARIABLES 4
Definition at line 103 of file wb_vision_detection_ball.h.
VISION_DETECTION_BALL_TO_STRING_BUFFER_SIZE
#define VISION_DETECTION_BALL_TO_STRING_BUFFER_SIZE 1041
Definition at line 107 of file wb_vision_detection_ball.h.
Enumeration Type Documentation
BallOptions
enum BallOptions
Enumerator
NoBallDetected
No Ball Found.
BallDetected
Ball Found.
Definition at line 91 of file wb_vision_detection_ball.h.
Function Documentation
wb_vision_detection_ball_coordinate_px_coord()
gu_pixel_coordinate wb_vision_detection_ball_coordinate_px_coord (const struct wb_vision_detection_ball self, const uint16_t resWidth, const uint16_t resHeight)
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 489 of file wb_vision_detection_ball.c.
References wb_vision_detection_ball::coordinate, and wb_px_coord_to_px_coord().
wb_vision_detection_ball_description()
const char * wb_vision_detection_ball_description (const struct wb_vision_detection_ball * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_vision_detection_ball.c.
References BallDetected, NoBallDetected, PIXEL_COORDINATE_DESC_BUFFER_SIZE, and wb_pixel_coordinate_description().
Referenced by guWhiteboard::VisionDetectionBall::description(), and wb_vision_detection_balls_description().
wb_vision_detection_ball_from_network_serialised()
size_t wb_vision_detection_ball_from_network_serialised (const char * src, struct wb_vision_detection_ball * dst)
Network stream deserialisation.
Network stream deserialisation.
Definition at line 434 of file wb_vision_detection_ball.c.
References wb_vision_detection_ball::horizontalRadius, ntohl, ntohs, wb_vision_detection_ball::sightingType, and wb_vision_detection_ball::verticalRadius.
wb_vision_detection_ball_from_string()
struct wb_vision_detection_ball * wb_vision_detection_ball_from_string (struct wb_vision_detection_ball * self, const char * str)
Convert from a string.
Definition at line 249 of file wb_vision_detection_ball.c.
References BallDetected, NoBallDetected, VISION_DETECTION_BALL_DESC_BUFFER_SIZE, and wb_pixel_coordinate_from_string().
Referenced by wb_vision_detection_balls_from_string().
wb_vision_detection_ball_to_network_serialised()
size_t wb_vision_detection_ball_to_network_serialised (const struct wb_vision_detection_ball * self, char * dst)
Network stream serialisation.
Network stream serialisation.
Definition at line 381 of file wb_vision_detection_ball.c.
References htonl, and htons.
wb_vision_detection_ball_to_string()
const char * wb_vision_detection_ball_to_string (const struct wb_vision_detection_ball * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 187 of file wb_vision_detection_ball.c.
References BallDetected, NoBallDetected, PIXEL_COORDINATE_TO_STRING_BUFFER_SIZE, and wb_pixel_coordinate_to_string().
Referenced by guWhiteboard::VisionDetectionBall::to_string(), and wb_vision_detection_balls_to_string().