gusimplewhiteboard: typeClassDefs/wb_vision_line.h File Reference
wb_vision_line.h File Reference
#include <gu_util.h>
#include <stdint.h>
#include "wb_pixel_coordinate_line.h"
Classes
struct wb_vision_line
WHITEBOARD_POSTER_STRING_CONVERSION.
Macros
#define _XOPEN_SOURCE 700
#define VISION_LINE_GENERATED
#define VISION_LINE_C_STRUCT wb_vision_line
#define VISION_LINE_NUMBER_OF_VARIABLES 2
#define VISION_LINE_DESC_BUFFER_SIZE 1054
#define VISION_LINE_TO_STRING_BUFFER_SIZE 1027
Functions
const char * wb_vision_line_description (const struct wb_vision_line *self, char *descString, size_t bufferSize)
Convert to a description string.
const char * wb_vision_line_to_string (const struct wb_vision_line *self, char *toString, size_t bufferSize)
Convert to a string.
struct wb_vision_line * wb_vision_line_from_string (struct wb_vision_line *self, const char *str)
Convert from a string.
size_t wb_vision_line_to_network_serialised (const struct wb_vision_line *self, char *dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
size_t wb_vision_line_from_network_serialised (const char *src, struct wb_vision_line *dst)
Network stream deserialisation.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 72 of file wb_vision_line.h.
VISION_LINE_C_STRUCT
#define VISION_LINE_C_STRUCT wb_vision_line
Definition at line 91 of file wb_vision_line.h.
VISION_LINE_DESC_BUFFER_SIZE
#define VISION_LINE_DESC_BUFFER_SIZE 1054
Definition at line 95 of file wb_vision_line.h.
VISION_LINE_GENERATED
#define VISION_LINE_GENERATED
Definition at line 90 of file wb_vision_line.h.
VISION_LINE_NUMBER_OF_VARIABLES
#define VISION_LINE_NUMBER_OF_VARIABLES 2
Definition at line 92 of file wb_vision_line.h.
VISION_LINE_TO_STRING_BUFFER_SIZE
#define VISION_LINE_TO_STRING_BUFFER_SIZE 1027
Definition at line 96 of file wb_vision_line.h.
Function Documentation
wb_vision_line_description()
const char * wb_vision_line_description (const struct wb_vision_line * self, char * descString, size_t bufferSize)
Convert to a description string.
Definition at line 125 of file wb_vision_line.c.
References PIXEL_COORDINATE_LINE_DESC_BUFFER_SIZE, and wb_pixel_coordinate_line_description().
Referenced by guWhiteboard::VisionLine::description(), and wb_vision_lines_description().
wb_vision_line_from_network_serialised()
size_t wb_vision_line_from_network_serialised (const char * src, struct wb_vision_line * dst)
Network stream deserialisation.
Network stream deserialisation.
Definition at line 333 of file wb_vision_line.c.
wb_vision_line_from_string()
struct wb_vision_line * wb_vision_line_from_string (struct wb_vision_line * self, const char * str)
Convert from a string.
Definition at line 217 of file wb_vision_line.c.
References VISION_LINE_DESC_BUFFER_SIZE, and wb_pixel_coordinate_line_from_string().
Referenced by wb_vision_lines_from_string().
wb_vision_line_to_network_serialised()
size_t wb_vision_line_to_network_serialised (const struct wb_vision_line * self, char * dst)
WHITEBOARD_POSTER_STRING_CONVERSION.
Network stream serialisation
WHITEBOARD_POSTER_STRING_CONVERSION.
Definition at line 320 of file wb_vision_line.c.
wb_vision_line_to_string()
const char * wb_vision_line_to_string (const struct wb_vision_line * self, char * toString, size_t bufferSize)
Convert to a string.
Definition at line 171 of file wb_vision_line.c.
References PIXEL_COORDINATE_LINE_TO_STRING_BUFFER_SIZE, and wb_pixel_coordinate_line_to_string().
Referenced by guWhiteboard::VisionLine::to_string(), and wb_vision_lines_to_string().